cocci_test_suite() {
	struct ttm_bo_driver cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 994 */;
	struct ttm_mem_reg *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 991 */;
	struct drm_vram_mm *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 964 */;
	bool cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 946 */;
	struct drm_gem_vram_object *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 934 */;
	struct ttm_placement *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 932 */;
	struct ttm_buffer_object *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 931 */;
	struct ttm_mem_type_manager *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 909 */;
	uint32_t cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 908 */;
	struct ttm_bo_device *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 908 */;
	int cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 908 */;
	struct ttm_backend_func cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 877 */;
	struct ttm_tt *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 871 */;
	void cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 871 */;
	struct drm_simple_display_pipe *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 768 */;
	struct drm_plane_state *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 714 */;
	struct drm_plane *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 713 */;
	struct drm_gem_object *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 636 */;
	uint64_t *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 634 */;
	unsigned int cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 62 */;
	struct drm_mode_create_dumb *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 610 */;
	struct drm_file *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 608 */;
	struct ttm_bo_kmap_obj *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 562 */;
	u32 cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 511 */;
	bool *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 364 */;
	void *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 363 */;
	struct ttm_operation_ctx cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 216 */;
	s64 cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 204 */;
	u64 cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 186 */;
	const struct drm_gem_object_funcs cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 15 */;
	unsigned long cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 142 */;
	size_t cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 141 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 139 */;
	uint64_t cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1094 */;
	struct drm_minor *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1038 */;
	const struct drm_info_list cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1024 */[];
	struct drm_printer cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1016 */;
	struct drm_mm *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1015 */;
	struct drm_info_node *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1013 */;
	struct seq_file *cocci_id/* drivers/gpu/drm/drm_gem_vram_helper.c 1011 */;
}
