cocci_test_suite() {
	struct drm_mode_config *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 93 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 92 */;
	struct drm_display_mode *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 90 */;
	enum drm_mode_status cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 88 */;
	const struct drm_encoder_helper_funcs cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 78 */;
	struct komeda_data_flow_cfg cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 43 */;
	struct komeda_layer *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 42 */;
	struct drm_writeback_job *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 41 */;
	struct komeda_crtc_state *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 40 */;
	struct drm_connector_state *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 38 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 37 */;
	struct drm_encoder *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 36 */;
	struct komeda_dev *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 186 */;
	struct komeda_kms_dev *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 185 */;
	int cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 185 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 16 */;
	u32 *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 145 */;
	struct drm_display_info *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 144 */;
	struct drm_writeback_connector *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 143 */;
	struct komeda_wb_connector *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 142 */;
	struct komeda_data_flow_cfg *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 14 */;
	struct komeda_crtc *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 139 */;
	const struct drm_connector_funcs cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 129 */;
	struct drm_connector *cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 123 */;
	void cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 123 */;
	uint32_t cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 118 */;
	bool cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 111 */;
	enum drm_connector_status cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 110 */;
	const struct drm_connector_helper_funcs cocci_id/* drivers/gpu/drm/arm/display/komeda/komeda_wb_connector.c 105 */;
}
