cocci_test_suite() {
	const u64 *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 940 */;
	u64 cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 939 */[MODIFIERS_COUNT_MAX];
	u32 *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 937 */;
	unsigned long cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 931 */;
	enum drm_plane_type cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 930 */;
	const struct malidp_hw_regmap *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 928 */;
	struct malidp_drm *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 927 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 925 */;
	const struct drm_plane_helper_funcs cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 919 */;
	struct malidp_crtc_state *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 894 */;
	dma_addr_t cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 718 */;
	void cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 70 */;
	const s16 cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 642 */[][DRM_COLOR_RANGE_MAX][MALIDP_COLORADJ_NUM_COEFFS];
	unsigned int cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 616 */[3];
	unsigned int cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 513 */;
	u16 cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 511 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 510 */;
	struct malidp_plane *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 507 */;
	struct drm_plane_state *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 505 */;
	struct drm_plane *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 504 */;
	int cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 482 */;
	u8 cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 469 */;
	u32 cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 468 */;
	enum mmu_prefetch_mode cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 468 */;
	struct scatterlist *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 341 */;
	struct sg_table *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 340 */;
	struct drm_gem_cma_object *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 339 */;
	struct drm_gem_object *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 338 */;
	bool cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 332 */;
	struct malidp_plane_state *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 332 */;
	struct iommu_domain *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 316 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 273 */;
	const struct drm_plane_funcs cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 259 */;
	const struct drm_format_info *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 151 */;
	u64 cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 149 */;
	const struct drm_plane_state *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 136 */;
	struct drm_printer *cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 135 */;
	const char *const cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 129 */[];
	enum drm_color_range cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 1015 */;
	enum drm_color_encoding cocci_id/* drivers/gpu/drm/arm/malidp_planes.c 1014 */;
}
