cocci_test_suite() {
	enum drm_plane_type cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 769 */;
	const uint32_t cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 740 */[];
	const struct drm_plane_funcs cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 729 */;
	const struct rcar_du_plane_state cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 718 */;
	uint64_t *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 715 */;
	const struct drm_plane_state *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 714 */;
	struct drm_property *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 714 */;
	uint64_t cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 700 */;
	const struct drm_plane_helper_funcs cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 645 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 570 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 569 */;
	const struct rcar_du_format_info **cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 567 */;
	struct drm_plane_state *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 566 */;
	struct drm_plane *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 565 */;
	int cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 565 */;
	unsigned int cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 556 */;
	struct rcar_du_device *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 545 */;
	const struct rcar_du_plane_state *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 543 */;
	struct rcar_du_group *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 542 */;
	void cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 542 */;
	const struct drm_rect *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 520 */;
	u32 cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 468 */;
	struct drm_gem_cma_object *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 343 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 342 */;
	u32 cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 336 */[2];
	struct rcar_du_plane *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 146 */;
	struct rcar_du_plane_state *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 144 */;
	bool cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 134 */;
	unsigned int cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 132 */[RCAR_DU_MAX_GROUPS];
	struct drm_atomic_state *cocci_id/* drivers/gpu/drm/rcar-du/rcar_du_plane.c 129 */;
}
