cocci_test_suite() {
	struct seq_file *cocci_id/* kernel/sched/psi.c 987 */;
	void *cocci_id/* kernel/sched/psi.c 987 */;
	enum psi_res cocci_id/* kernel/sched/psi.c 940 */;
	struct rq *cocci_id/* kernel/sched/psi.c 906 */;
	struct rq_flags cocci_id/* kernel/sched/psi.c 905 */;
	unsigned int cocci_id/* kernel/sched/psi.c 904 */;
	struct task_struct *cocci_id/* kernel/sched/psi.c 902 */;
	struct css_set *cocci_id/* kernel/sched/psi.c 902 */;
	struct psi_group_cpu cocci_id/* kernel/sched/psi.c 872 */;
	unsigned long *cocci_id/* kernel/sched/psi.c 813 */;
	struct cgroup *cocci_id/* kernel/sched/psi.c 726 */;
	void **cocci_id/* kernel/sched/psi.c 723 */;
	struct kthread_delayed_work cocci_id/* kernel/sched/psi.c 586 */;
	struct kthread_delayed_work *cocci_id/* kernel/sched/psi.c 581 */;
	struct kthread_work *cocci_id/* kernel/sched/psi.c 579 */;
	struct kthread_worker *cocci_id/* kernel/sched/psi.c 558 */;
	u64 *cocci_id/* kernel/sched/psi.c 507 */;
	struct psi_trigger *cocci_id/* kernel/sched/psi.c 493 */;
	struct psi_window *cocci_id/* kernel/sched/psi.c 446 */;
	struct psi_group cocci_id/* kernel/sched/psi.c 419 */;
	bool cocci_id/* kernel/sched/psi.c 415 */;
	struct delayed_work *cocci_id/* kernel/sched/psi.c 412 */;
	struct work_struct *cocci_id/* kernel/sched/psi.c 410 */;
	u32 cocci_id/* kernel/sched/psi.c 321 */[NR_PSI_STATES];
	u32 cocci_id/* kernel/sched/psi.c 308 */;
	u64 cocci_id/* kernel/sched/psi.c 306 */[NR_PSI_STATES - 1];
	u32 *cocci_id/* kernel/sched/psi.c 304 */;
	enum psi_aggregators cocci_id/* kernel/sched/psi.c 303 */;
	struct psi_group *cocci_id/* kernel/sched/psi.c 302 */;
	unsigned long cocci_id/* kernel/sched/psi.c 285 */;
	u64 cocci_id/* kernel/sched/psi.c 283 */;
	unsigned long cocci_id/* kernel/sched/psi.c 282 */[3];
	int cocci_id/* kernel/sched/psi.c 282 */;
	void cocci_id/* kernel/sched/psi.c 282 */;
	enum psi_states cocci_id/* kernel/sched/psi.c 243 */;
	struct psi_group_cpu *cocci_id/* kernel/sched/psi.c 241 */;
	unsigned int *cocci_id/* kernel/sched/psi.c 216 */;
	void __init cocci_id/* kernel/sched/psi.c 205 */;
	void cocci_id/* kernel/sched/psi.c 180 */(struct work_struct *work);
	int __init cocci_id/* kernel/sched/psi.c 1281 */;
	const struct file_operations cocci_id/* kernel/sched/psi.c 1272 */;
	__poll_t cocci_id/* kernel/sched/psi.c 1239 */;
	poll_table *cocci_id/* kernel/sched/psi.c 1239 */;
	loff_t *cocci_id/* kernel/sched/psi.c 1234 */;
	size_t cocci_id/* kernel/sched/psi.c 1234 */;
	const char __user *cocci_id/* kernel/sched/psi.c 1233 */;
	ssize_t cocci_id/* kernel/sched/psi.c 1233 */;
	char cocci_id/* kernel/sched/psi.c 1194 */[32];
	void __rcu __force **cocci_id/* kernel/sched/psi.c 1172 */;
	struct psi_trigger cocci_id/* kernel/sched/psi.c 1084 */;
	struct kref *cocci_id/* kernel/sched/psi.c 1082 */;
	struct sched_param cocci_id/* kernel/sched/psi.c 1054 */;
	char *cocci_id/* kernel/sched/psi.c 1008 */;
	struct inode *cocci_id/* kernel/sched/psi.c 1002 */;
	struct file *cocci_id/* kernel/sched/psi.c 1002 */;
	__typeof__(struct psi_group_cpu) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
