cocci_test_suite() {
	struct drm_i915_gem_object *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 949 */;
	const struct intel_crtc_state *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 919 */;
	struct drm_intel_overlay_put_image *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 917 */;
	struct intel_crtc *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 881 */;
	enum pipe cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 757 */;
	struct overlay_registers __iomem *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 754 */;
	const struct intel_plane_state *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 671 */;
	const u16 cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 581 */[N_PHASES][N_HORIZ_UV_TAPS];
	const u16 cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 561 */[N_PHASES][N_HORIZ_Y_TAPS];
	u32 cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 546 */;
	struct drm_i915_private *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 546 */;
	short cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 508 */;
	u32 *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 397 */;
	typeof(*overlay) cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 387 */;
	struct i915_active *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 384 */;
	struct intel_frontbuffer *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 282 */;
	int cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 226 */;
	void (*cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 223 */)(struct intel_overlay *);
	struct intel_overlay *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 223 */;
	struct i915_request *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 222 */;
	u8 cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 203 */;
	struct pci_dev *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 202 */;
	void cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 199 */;
	struct intel_overlay {
		struct drm_i915_private *i915;
		struct intel_context *context;
		struct intel_crtc *crtc;
		struct i915_vma *vma;
		struct i915_vma *old_vma;
		bool active;
		bool pfit_active;
		u32 pfit_vscale_ratio;
		u32 color_key:24;
		u32 color_key_enabled:1;
		u32 brightness,contrast,saturation;
		u32 old_xscale,old_yscale;
		struct drm_i915_gem_object *reg_bo;
		struct overlay_registers __iomem *regs;
		u32 flip_addr;
		struct i915_active last_flip;
		void (*flip_complete)(struct intel_overlay *ovl);
	} cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 177 */;
	struct drm_i915_error_state_buf *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1432 */;
	struct intel_overlay_error_state *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1409 */;
	struct intel_overlay_error_state {
		struct overlay_registers regs;
		unsigned long base;
		u32 dovsta;
		u32 isr;
	} cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1402 */;
	struct overlay_registers cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1367 */;
	struct i915_vma *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1300 */;
	struct overlay_registers {
		u32 OBUF_0Y;
		u32 OBUF_1Y;
		u32 OBUF_0U;
		u32 OBUF_0V;
		u32 OBUF_1U;
		u32 OBUF_1V;
		u32 OSTRIDE;
		u32 YRGB_VPH;
		u32 UV_VPH;
		u32 HORZ_PH;
		u32 INIT_PHS;
		u32 DWINPOS;
		u32 DWINSZ;
		u32 SWIDTH;
		u32 SWIDTHSW;
		u32 SHEIGHT;
		u32 YRGBSCALE;
		u32 UVSCALE;
		u32 OCLRC0;
		u32 OCLRC1;
		u32 DCLRKV;
		u32 DCLRKM;
		u32 SCLRKVH;
		u32 SCLRKVL;
		u32 SCLRKEN;
		u32 OCONFIG;
		u32 OCMD;
		u32 RESERVED1;
		u32 OSTART_0Y;
		u32 OSTART_1Y;
		u32 OSTART_0U;
		u32 OSTART_0V;
		u32 OSTART_1U;
		u32 OSTART_1V;
		u32 OTILEOFF_0Y;
		u32 OTILEOFF_1Y;
		u32 OTILEOFF_0U;
		u32 OTILEOFF_0V;
		u32 OTILEOFF_1U;
		u32 OTILEOFF_1V;
		u32 FASTHSCALE;
		u32 UVSCALEV;
		u32 RESERVEDC[(0x200 - 0xA8) / 4];
		u16 Y_VCOEFS[N_VERT_Y_TAPS * N_PHASES];
		u16 RESERVEDD[0x100 / 2 - N_VERT_Y_TAPS * N_PHASES];
		u16 Y_HCOEFS[N_HORIZ_Y_TAPS * N_PHASES];
		u16 RESERVEDE[0x200 / 2 - N_HORIZ_Y_TAPS * N_PHASES];
		u16 UV_VCOEFS[N_VERT_UV_TAPS * N_PHASES];
		u16 RESERVEDF[0x100 / 2 - N_VERT_UV_TAPS * N_PHASES];
		u16 UV_HCOEFS[N_HORIZ_UV_TAPS * N_PHASES];
		u16 RESERVEDG[0x100 / 2 - N_HORIZ_UV_TAPS * N_PHASES];
	} cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 123 */;
	struct drm_file *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1221 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1220 */;
	void *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1220 */;
	struct drm_intel_overlay_attrs *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1203 */;
	bool cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1191 */;
	struct drm_crtc *cocci_id/* drivers/gpu/drm/i915/display/intel_overlay.c 1064 */;
}
