cocci_test_suite() {
	const struct amd_ip_funcs cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 995 */;
	enum amd_powergating_state cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 990 */;
	u32 *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 980 */;
	enum amd_clockgating_state cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 968 */;
	unsigned long long cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 875 */;
	u64 cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 637 */;
	enum amdgpu_interrupt_state cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 60 */;
	struct amdgpu_gmc *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 588 */;
	unsigned cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 567 */[AMDGPU_MAX_VMHUBS];
	struct amdgpu_device *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 549 */;
	void *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 547 */;
	int cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 547 */;
	const struct amdgpu_gmc_funcs cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 532 */;
	struct amdgpu_bo_va_mapping *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 514 */;
	uint64_t *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 490 */;
	void cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 425 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 388 */;
	struct amdgpu_vmhub *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 387 */;
	bool cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 386 */;
	unsigned cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 384 */;
	uint64_t cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 383 */;
	struct amdgpu_ring *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 383 */;
	struct amdgpu_job *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 324 */;
	struct dma_fence *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 323 */;
	const unsigned cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 251 */;
	u32 cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 249 */;
	unsigned int cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 245 */;
	const struct amdgpu_irq_src_funcs cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 191 */;
	struct amdgpu_task_info cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 152 */;
	struct amdgpu_iv_entry *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 129 */;
	struct amdgpu_irq_src *cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 128 */;
	const struct amdgpu_ip_block_version cocci_id/* drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c 1013 */;
}
