cocci_test_suite() {
	struct mm_struct *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 96 */;
	struct amdgpu_bo *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 95 */;
	struct drm_gem_object *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 94 */;
	struct amdgpu_bo_list_entry cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 75 */;
	struct amdgpu_bo_list cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 74 */;
	size_t cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 70 */;
	uint64_t cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 69 */;
	struct amdgpu_bo_list *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 68 */;
	struct amdgpu_bo_list_entry *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 67 */;
	struct amdgpu_bo_list **cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 64 */;
	struct drm_file *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 62 */;
	struct amdgpu_device *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 62 */;
	struct kref *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 47 */;
	struct rcu_head *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 39 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 271 */;
	union drm_amdgpu_bo_list *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 270 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 265 */;
	void *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 265 */;
	unsigned cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 246 */;
	unsigned long cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 238 */;
	struct drm_amdgpu_bo_list_entry *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 228 */;
	const uint32_t cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 227 */;
	struct drm_amdgpu_bo_list_entry cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 227 */;
	const void __user *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 226 */;
	struct drm_amdgpu_bo_list_entry **cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 224 */;
	struct drm_amdgpu_bo_list_in *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 223 */;
	int cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 223 */;
	struct list_head cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 191 */[AMDGPU_BO_LIST_NUM_BUCKETS];
	struct list_head *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 185 */;
	struct amdgpu_fpriv *cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 158 */;
	void cocci_id/* drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c 158 */;
}
