cocci_test_suite() {
	SmuMetrics_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 885 */;
	enum amd_pp_sensors cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 882 */;
	void *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 868 */;
	SmuMetrics_t *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 860 */;
	struct smu_temperature_range *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 836 */;
	struct arcturus_dpm_table *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 780 */;
	enum smu_clk_type cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 778 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 73 */[SMU_MSG_MAX_COUNT];
	struct pp_clock_levels_with_latency cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 609 */;
	int32_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 598 */;
	struct pp_clock_levels_with_latency *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 581 */;
	struct atom_smc_dpm_info_v4_6 cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 536 */;
	uint8_t **cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 524 */;
	struct atom_smc_dpm_info_v4_6 *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 517 */;
	PPTable_t *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 516 */;
	struct smu_table_context *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 515 */;
	PPTable_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 506 */;
	struct smu_11_0_powerplay_table *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 496 */;
	struct amdgpu_ras cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 45 */;
	struct arcturus_dpm_state *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 405 */;
	PPCLK_e cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 366 */;
	uint32_t *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 352 */;
	struct smu_power_state cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 337 */;
	struct arcturus_dpm_table cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 322 */;
	struct smu_dpm_context *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 317 */;
	struct smu_context *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 315 */;
	int cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 315 */;
	enum PP_SMC_POWER_PROFILE cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 275 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 260 */;
	const struct pptable_funcs cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 2078 */;
	struct i2c_adapter *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 2066 */;
	struct amdgpu_device *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 2050 */;
	const struct i2c_algorithm cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 2043 */;
	u32 cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 2037 */;
	struct i2c_msg *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1963 */;
	uint16_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1916 */;
	struct smu_table *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1897 */;
	SwI2cRequest_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1894 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 189 */[PP_SMC_POWER_PROFILE_COUNT];
	SwI2cCmd_t *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1868 */;
	uint8_t *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1856 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1855 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1855 */;
	SwI2cRequest_t *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1854 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 184 */[SMU_POWER_SOURCE_COUNT];
	struct smu_power_gate *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1827 */;
	struct smu_power_context *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1826 */;
	bool cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1824 */;
	uint64_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1819 */;
	unsigned long cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1817 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1816 */[2];
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 172 */[SMU_TABLE_COUNT];
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 143 */[SMU_FEATURE_COUNT];
	void cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1382 */;
	long *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1344 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 132 */[SMU_CLK_COUNT];
	int16_t cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1319 */;
	const char *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1308 */[];
	char *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1306 */;
	enum amd_dpm_forced_level cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1219 */;
	struct amdgpu_hive_info *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1141 */;
	struct arcturus_single_dpm_table *cocci_id/* drivers/gpu/drm/amd/powerplay/arcturus_ppt.c 1110 */;
}
