cocci_test_suite() {
	uint32_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 745 */;
	fInt cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 671 */[2];
	fInt cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 661 */;
	READ_EFUSE_VALUE_PARAMETER cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 658 */;
	EFUSE_INPUT_PARAMETER cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 657 */;
	EFUSE_LOGISTIC_FUNC_PARAM cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 654 */;
	EFUSE_LINEAR_FUNC_PARAM cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 651 */;
	struct amdgpu_device *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 650 */;
	ATOM_ASIC_PROFILING_INFO_V3_4 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 649 */;
	bool cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 647 */;
	uint16_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 645 */;
	uint16_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 644 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 642 */;
	ATOM_GPIO_PIN_LUT *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 628 */;
	pp_atomctrl_gpio_pin_assignment *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 625 */;
	ATOM_GPIO_PIN_ASSIGNMENT cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 590 */;
	const ATOM_GPIO_PIN_ASSIGNMENT *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 579 */;
	ATOM_GPIO_PIN_LUT cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 575 */;
	ATOM_MEMORY_SETTING_DATA_BLOCK *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 54 */;
	unsigned int cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 534 */;
	pp_atomctrl_voltage_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 529 */;
	COMPUTE_GPU_CLOCK_OUTPUT_PARAMETERS_V1_6 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 445 */;
	pp_atomctrl_clock_dividers_vi *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 442 */;
	COMPUTE_GPU_CLOCK_OUTPUT_PARAMETERS_V1_7 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 413 */;
	pp_atomctrl_clock_dividers_ai *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 410 */;
	union voltage_object_info {
		struct _ATOM_VOLTAGE_OBJECT_INFO v1;
		struct _ATOM_VOLTAGE_OBJECT_INFO_V2 v2;
		struct _ATOM_VOLTAGE_OBJECT_INFO_V3_1 v3;
	} cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 41 */;
	COMPUTE_MEMORY_ENGINE_PLL_PARAMETERS_V4 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 353 */;
	pp_atomctrl_clock_dividers_kong *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 350 */;
	COMPUTE_MEMORY_CLOCK_PARAM_PARAMETERS_V2_3 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 323 */;
	pp_atomctrl_memory_clock_param_ai *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 320 */;
	COMPUTE_MEMORY_CLOCK_PARAM_PARAMETERS_V2_2 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 302 */;
	COMPUTE_MEMORY_CLOCK_PARAM_PARAMETERS_V2_1 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 254 */;
	pp_atomctrl_memory_clock_param *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 250 */;
	ATOM_VOLTAGE_OBJECT_INFO_V3_1 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 223 */;
	const ATOM_VOLTAGE_OBJECT_INFO_V3_1 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 219 */;
	union voltage_object_info *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 206 */;
	ATOM_VOLTAGE_OBJECT_INFO *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 201 */;
	SET_ENGINE_CLOCK_PS_ALLOCATION cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 179 */;
	ATOM_ASIC_PROFILING_INFO_V3_3 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1547 */;
	void cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1534 */;
	char *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1497 */;
	ATOM_ASIC_PROFILING_INFO_V2_1 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1496 */;
	ATOM_ASIC_PROFILING_INFO_V2_1 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1480 */;
	u16 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1479 */;
	SET_VOLTAGE_PARAMETERS_V1_3 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1457 */;
	SET_VOLTAGE_PS_ALLOCATION cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1456 */;
	const ATOM_VOLTAGE_OBJECT_V3 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1438 */;
	ATOM_VOLTAGE_OBJECT_INFO_V3_1 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1435 */;
	ATOM_ASIC_PROFILING_INFO_V3_6 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1390 */;
	struct pp_atom_ctrl__avfs_parameters *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1388 */;
	ATOM_INIT_REG_BLOCK *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 138 */;
	ATOM_VRAM_INFO_HEADER_V2_1 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 137 */;
	ATOM_SMU_INFO_V2_1 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1367 */;
	struct pp_atom_ctrl_sclk_range_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1360 */;
	GET_EVV_VOLTAGE_INFO_OUTPUT_PARAMETER_V1_3 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1355 */;
	pp_atomctrl_mc_reg_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 135 */;
	GET_VOLTAGE_INFO_INPUT_PARAMETER_V1_3 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1343 */;
	DYNAMICE_MEMORY_SETTINGS_PARAMETER_V2_1 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1322 */;
	ATOM_ASIC_SS_ASSIGNMENT cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1241 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1235 */;
	uint8_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1232 */;
	pp_atomctrl_internal_ss_info cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1223 */;
	ATOM_ASIC_SS_ASSIGNMENT *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1220 */;
	ATOM_ASIC_INTERNAL_SS_INFO *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1219 */;
	pp_atomctrl_internal_ss_info *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1217 */;
	const uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1216 */;
	const uint8_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1215 */;
	struct pp_hwmgr *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1214 */;
	int cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1214 */;
	u16 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1201 */;
	u8 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1200 */;
	void *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1197 */;
	ATOM_FIRMWARE_INFO *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1185 */;
	ATOM_FIRMWARE_INFO_V2_1 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1181 */;
	ATOM_FIRMWARE_INFO_V2_1 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1180 */;
	ATOM_COMMON_TABLE_HEADER *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1166 */;
	GET_EVV_VOLTAGE_INFO_OUTPUT_PARAMETER_V1_2 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1155 */;
	GET_VOLTAGE_INFO_INPUT_PARAMETER_V1_2 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 1125 */;
	ATOM_INIT_REG_INDEX_FORMAT *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 108 */;
	ATOM_INIT_REG_INDEX_FORMAT cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/ppatomctrl.c 107 */;
}
