cocci_test_suite() {
	struct pp_hw_power_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 94 */;
	struct vega10_power_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 93 */;
	const ULONG cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 91 */;
	ULONG cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 91 */;
	struct vega10_hwmgr cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 825 */;
	struct pp_atomfwctrl_voltage_table cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 822 */;
	enum{CLK_SMNCLK=0, CLK_SOCCLK, CLK_MP0CLK, CLK_MP1CLK, CLK_LCLK, CLK_DCEFCLK, CLK_VCLK, CLK_DCLK, CLK_ECLK, CLK_UCLK, CLK_GFXCLK, CLK_COUNT,} cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 76 */;
	struct phm_ppt_v1_mm_clock_voltage_dependency_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 665 */;
	unsigned cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 662 */;
	uint16_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 650 */;
	struct vega10_leakage_voltage *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 649 */;
	const uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 59 */[];
	uint16_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 554 */;
	const struct pp_hwmgr_func cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5326 */;
	PHM_PerformanceLevel *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5252 */;
	PHM_PerformanceLevelDesignation cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5251 */;
	enum pp_mp1_state cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5227 */;
	struct vega10_dpm_table cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5190 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 519 */;
	int32_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 517 */;
	struct vega10_odn_clock_voltage_dependency_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5165 */;
	long *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5162 */;
	phm_ppt_v1_voltage_lookup_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 516 */;
	struct vega10_single_dpm_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 5000 */;
	struct vega10_odn_dpm_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4999 */;
	enum PP_OD_DPM_TABLE_COMMAND cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4994 */;
	const char *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4925 */[6];
	const char *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4918 */[7];
	const uint8_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4911 */[6][4];
	char *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4907 */;
	struct PP_TemperatureRange cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4889 */;
	PPTable_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4887 */;
	struct PP_TemperatureRange *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4884 */;
	bool *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4650 */;
	const struct vega10_performance_level *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4640 */;
	uint8_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4595 */;
	Watermarks_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4590 */;
	uint64_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4410 */;
	const char *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4375 */[];
	struct dm_pp_wm_sets_with_clock_ranges_soc15 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4361 */;
	struct pp_clock_levels_with_voltage *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4317 */;
	struct pp_clock_levels_with_latency *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4293 */;
	struct phm_clock_and_voltage_limits *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4204 */;
	struct amd_pp_simple_clock_info *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4200 */;
	enum amd_dpm_forced_level cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4143 */;
	enum pp_clock_type cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 4084 */;
	struct pp_display_clock_request cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3927 */;
	DSPCLK_e cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3863 */;
	enum amd_pp_clock_type cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3861 */;
	struct pp_display_clock_request *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3858 */;
	uint64_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3837 */;
	int *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3772 */;
	uint32_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3755 */;
	void cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3468 */;
	struct vega10_dpm_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3331 */;
	const struct phm_set_power_state_input *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3284 */;
	const void *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3281 */;
	int32_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3147 */;
	struct phm_ppt_v2_information *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3145 */;
	const struct phm_clock_and_voltage_limits *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3142 */;
	bool cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3138 */;
	struct PP_Clocks cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3137 */;
	struct amdgpu_device *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3132 */;
	const struct pp_power_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3130 */;
	struct pp_power_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3129 */;
	struct pp_atomfwctrl_avfs_parameters cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 311 */;
	unsigned long cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3096 */;
	struct phm_ppt_v1_clock_voltage_dependency_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 309 */[3];
	struct phm_ppt_v1_voltage_lookup_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 308 */;
	struct vega10_odn_vddc_lookup_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 307 */;
	ATOM_Vega10_MCLK_Dependency_Table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3018 */;
	ATOM_Vega10_GFXCLK_Dependency_Table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3014 */;
	ATOM_Vega10_SOCCLK_Dependency_Table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3010 */;
	ATOM_Vega10_POWERPLAYTABLE *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3008 */;
	ATOM_Vega10_State *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3007 */;
	struct vega10_performance_level *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3006 */;
	ATOM_Vega10_GFXCLK_Dependency_Record_V2 *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3003 */;
	void *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 3000 */;
	struct vega10_power_state cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2996 */;
	struct pp_atomfwctrl_bios_boot_up_values cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2498 */;
	struct phm_ppt_v1_clock_voltage_dependency_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2459 */;
	AvfsFuseOverride_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2424 */;
	struct phm_fuses_default cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2421 */;
	struct pp_atomfwctrl_gpio_parameters cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2339 */;
	struct vega10_hwmgr *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2324 */;
	struct pp_hwmgr *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2322 */;
	int cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2322 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 2293 */;
	struct pp_atomfwctrl_clock_dividers_soc15 cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1996 */;
	PllSetting_t *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1548 */;
	struct vega10_pcie_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1506 */;
	struct phm_ppt_v1_pcie_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1245 */;
	struct vega10_dpm_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1213 */;
	unsigned int cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1132 */;
	struct pp_atomfwctrl_voltage_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1049 */;
	phm_ppt_v1_clock_voltage_dependency_table *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 1048 */;
	const struct pp_hw_power_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 104 */;
	const struct vega10_power_state *cocci_id/* drivers/gpu/drm/amd/powerplay/hwmgr/vega10_hwmgr.c 103 */;
}
