cocci_test_suite() {
	enum smu_clk_type cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 993 */[];
	struct pp_clock_levels_with_latency *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 909 */;
	enum smu_clk_type cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 845 */;
	struct smu_11_0_dpm_context *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 718 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 713 */[3];
	enum SMU_11_0_ODFEATURE_ID cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 701 */;
	DpmDescriptor_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 691 */;
	struct smu_power_gate *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 645 */;
	struct smu_power_context *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 644 */;
	struct smu_11_0_dpm_context cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 587 */;
	struct smu_dpm_context *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 582 */;
	int cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 580 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 57 */[SMU_MSG_MAX_COUNT];
	void *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 567 */;
	SmuMetrics_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 560 */;
	Watermarks_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 539 */;
	struct smu_table *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 533 */;
	PPTable_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 520 */;
	struct smu_baco_context *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 512 */;
	uint8_t **cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 424 */;
	struct atom_smc_dpm_info_v4_5 *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 417 */;
	PPTable_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 416 */;
	struct smu_table_context *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 415 */;
	uint64_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 332 */;
	uint32_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 323 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 310 */;
	struct amdgpu_device *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 308 */;
	bool cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 306 */;
	struct smu_context *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 306 */;
	enum PP_SMC_POWER_PROFILE cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 291 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 277 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 205 */[PP_SMC_POWER_PROFILE_COUNT];
	const struct pptable_funcs cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 2000 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 200 */[SMU_POWER_SOURCE_COUNT];
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 185 */[SMU_TABLE_COUNT];
	enum SMU_11_0_ODSETTING_ID cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1829 */;
	struct smu_11_0_overdrive_table *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1828 */;
	enum PP_OD_DPM_TABLE_COMMAND cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1823 */;
	long cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1823 */[];
	OverDriveTable_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1802 */;
	struct smu_11_0_overdrive_table cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1791 */;
	OverDriveTable_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1758 */;
	void cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1758 */;
	struct smu_11_0_max_sustainable_clocks *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1657 */;
	struct smu_11_0_powerplay_table *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1642 */;
	struct smu_temperature_range *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1639 */;
	uint16_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1530 */;
	uint16_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1529 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1423 */;
	Watermarks_t *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1397 */;
	struct dm_pp_wm_sets_with_clock_ranges_soc15 *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1392 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 139 */[SMU_FEATURE_COUNT];
	struct pp_display_clock_request cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1353 */;
	struct smu_clocks cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1352 */;
	enum amd_dpm_forced_level cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1310 */;
	struct smu_11_0_cmn2aisc_mapping cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 124 */[SMU_CLK_COUNT];
	long *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1230 */;
	const char *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1138 */[];
	int16_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1137 */;
	DpmActivityMonitorCoeffInt_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1135 */;
	char *cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1133 */;
	uint64_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1092 */;
	unsigned long cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1090 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1089 */[2];
	SmuMetrics_t cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1062 */;
	enum amd_pp_sensors cocci_id/* drivers/gpu/drm/amd/powerplay/navi10_ppt.c 1058 */;
}
