cocci_test_suite() {
	struct dc_bios *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 960 */;
	struct dc_context *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 959 */;
	unsigned int cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 958 */;
	struct dce110_resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 956 */;
	struct dc *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 955 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 954 */;
	bool cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 953 */;
	const struct resource_funcs cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 943 */;
	struct dc_link *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 909 */;
	int cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 907 */;
	const struct resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 904 */;
	struct resource_context *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 903 */;
	struct stream_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 902 */;
	const struct dc_plane_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 893 */;
	struct dc_caps *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 893 */;
	struct resource_pool **cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 884 */;
	struct pipe_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 799 */;
	struct dc_stream_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 797 */;
	struct dc_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 796 */;
	const struct dc *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 795 */;
	enum dc_status cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 794 */;
	struct clock_source **cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 722 */;
	void cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 722 */;
	struct dce110_clk_src cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 706 */;
	struct dce110_clk_src *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 705 */;
	const struct dce110_clk_src_regs *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 702 */;
	enum clock_source_id cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 701 */;
	struct clock_source *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 698 */;
	struct dce_i2c_hw cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 688 */;
	struct dce_i2c_hw *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 683 */;
	const struct dce_i2c_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 679 */;
	const struct dce_i2c_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 675 */;
	const struct dce_i2c_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 666 */[];
	struct aux_engine_dce110 cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 650 */;
	struct aux_engine_dce110 *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 649 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 647 */;
	struct dce_aux *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 645 */;
	struct dce110_opp cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 635 */;
	struct dce110_opp *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 634 */;
	struct output_pixel_processor *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 630 */;
	struct dce110_link_encoder cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 612 */;
	struct dce110_link_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 611 */;
	const struct encoder_init_data *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 609 */;
	struct link_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 608 */;
	const struct encoder_feature_support cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 601 */;
	struct dce_ipp cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 589 */;
	struct dce_ipp *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 589 */;
	struct input_pixel_processor *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 586 */;
	struct dce_transform cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 576 */;
	struct dce_transform *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 575 */;
	struct transform *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 571 */;
	struct transform **cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 565 */;
	struct dce_mem_input cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 552 */;
	struct dce_mem_input *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 552 */;
	struct mem_input *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 548 */;
	const struct dce110_aux_registers_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 544 */;
	const struct dce110_aux_registers_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 540 */;
	const struct dce_mem_input_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 535 */;
	const struct dce_mem_input_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 530 */;
	const struct dce_mem_input_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 521 */[];
	const struct resource_create_funcs cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 510 */;
	struct dce_hwseq cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 499 */;
	struct dce_hwseq *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 496 */;
	const struct dce_hwseq_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 492 */;
	const struct dce_hwseq_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 488 */;
	const struct dce_hwseq_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 484 */;
	struct dce110_stream_encoder cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 471 */;
	struct dce110_stream_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 470 */;
	enum engine_id cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 467 */;
	struct dce110_timing_generator cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 457 */;
	struct dce110_timing_generator *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 456 */;
	const struct dce110_timing_generator_offsets *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 454 */;
	struct timing_generator *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 451 */;
	struct audio *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 444 */;
	struct resource_straps *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 435 */;
	enum transmitter cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 403 */;
	const struct dc_plane_cap cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 369 */;
	const struct resource_caps cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 361 */;
	const struct bios_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 356 */;
	const struct dce_abm_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 350 */;
	const struct dce_abm_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 346 */;
	const struct dce_abm_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 342 */;
	const struct dce_dmcu_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 338 */;
	const struct dce_dmcu_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 334 */;
	const struct dce_dmcu_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 330 */;
	const struct dce110_clk_src_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 326 */;
	const struct dce110_clk_src_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 322 */;
	const struct dce110_clk_src_regs cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 316 */[];
	const struct dce_audio_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 307 */;
	const struct dce_audio_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 303 */;
	const struct dce_audio_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 293 */[];
	const struct dce110_aux_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 279 */[];
	const struct dce_opp_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 270 */;
	const struct dce_opp_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 266 */;
	const struct dce_opp_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 257 */[];
	const struct dce_stream_encoder_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 248 */;
	const struct dce_stream_encoder_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 244 */;
	const struct dce110_stream_enc_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 234 */[];
	const struct dce110_link_enc_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 218 */[];
	const struct dce110_link_enc_hpd_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 204 */[];
	const struct dce110_link_enc_aux_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 190 */[];
	const struct dce_transform_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 181 */;
	const struct dce_transform_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 177 */;
	const struct dce_transform_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 168 */[];
	const struct dce_ipp_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 159 */;
	const struct dce_ipp_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 155 */;
	const struct dce_ipp_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 146 */[];
	struct dce110_resource_pool cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 1135 */;
	struct resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 1130 */;
	const struct dce110_timing_generator_offsets cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 106 */[];
	struct irq_service_init_data cocci_id/* drivers/gpu/drm/amd/display/dc/dce100/dce100_resource.c 1028 */;
}
