cocci_test_suite() {
	struct pipe_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 918 */;
	struct dc_stream_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 916 */;
	struct dc_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 915 */;
	const struct dc *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 914 */;
	enum dc_status cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 913 */;
	const struct dc_stream_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 859 */;
	struct pixel_clk_params *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 857 */;
	const struct pipe_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 856 */;
	struct clock_source **cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 768 */;
	struct dce110_clk_src cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 752 */;
	struct dce110_clk_src *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 751 */;
	const struct dce110_clk_src_regs *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 748 */;
	enum clock_source_id cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 747 */;
	struct clock_source *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 744 */;
	struct dce_i2c_hw cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 734 */;
	struct dce_i2c_hw *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 729 */;
	const struct dce_i2c_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 725 */;
	const struct dce_i2c_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 721 */;
	const struct dce_i2c_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 712 */[];
	struct aux_engine_dce110 cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 696 */;
	struct aux_engine_dce110 *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 695 */;
	uint32_t cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 693 */;
	struct dce_aux *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 691 */;
	struct dce110_opp cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 681 */;
	struct dce110_opp *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 680 */;
	struct output_pixel_processor *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 676 */;
	struct dce110_link_encoder cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 658 */;
	struct dce110_link_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 657 */;
	const struct encoder_init_data *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 655 */;
	struct link_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 654 */;
	const struct encoder_feature_support cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 647 */;
	struct dce_ipp cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 635 */;
	struct dce_ipp *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 635 */;
	struct input_pixel_processor *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 632 */;
	struct dce_transform cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 622 */;
	struct dce_transform *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 621 */;
	struct transform *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 617 */;
	struct transform **cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 611 */;
	struct dce_mem_input cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 598 */;
	struct dce_mem_input *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 598 */;
	struct mem_input *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 594 */;
	const struct dce_mem_input_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 588 */;
	const struct dce_mem_input_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 583 */;
	const struct dce_mem_input_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 577 */[];
	const struct resource_create_funcs cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 566 */;
	struct dce_hwseq cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 553 */;
	struct dce_hwseq *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 550 */;
	const struct dce_hwseq_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 546 */;
	const struct dce_hwseq_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 542 */;
	const struct dce_hwseq_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 538 */;
	struct dce110_stream_encoder cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 520 */;
	struct dce110_stream_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 519 */;
	enum engine_id cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 516 */;
	struct dce110_timing_generator cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 506 */;
	struct dce110_timing_generator *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 505 */;
	const struct dce110_timing_generator_offsets *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 503 */;
	struct timing_generator *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 500 */;
	struct audio *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 493 */;
	struct resource_straps *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 484 */;
	enum transmitter cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 452 */;
	const struct dc_plane_cap cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 391 */;
	const struct resource_caps cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 373 */;
	const struct bios_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 368 */;
	const struct dce110_clk_src_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 364 */;
	const struct dce110_clk_src_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 360 */;
	const struct dce110_clk_src_regs cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 354 */[];
	const struct dce_audio_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 342 */;
	const struct dce_audio_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 338 */;
	const struct dce_audio_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 328 */[];
	const struct dce110_aux_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 314 */[];
	const struct dce_opp_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 304 */;
	const struct dce_opp_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 300 */;
	const struct dce_opp_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 291 */[];
	const struct dce110_aux_registers_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 282 */;
	const struct dce110_aux_registers_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 278 */;
	const struct dce_stream_encoder_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 274 */;
	const struct dce_stream_encoder_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 270 */;
	const struct dce110_stream_enc_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 264 */[];
	const struct dce110_link_enc_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 248 */[];
	const struct dce110_link_enc_hpd_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 233 */[];
	const struct dce110_link_enc_aux_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 219 */[];
	const struct dce_transform_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 210 */;
	const struct dce_transform_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 206 */;
	const struct dce_transform_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 200 */[];
	const struct dce_ipp_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 191 */;
	const struct dce_ipp_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 187 */;
	const struct dce_ipp_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 181 */[];
	const struct dce_abm_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 172 */;
	const struct dce_abm_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 168 */;
	const struct dce_abm_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 164 */;
	const struct dce_dmcu_mask cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 160 */;
	const struct dce_dmcu_shift cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 156 */;
	const struct dce_dmcu_registers cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 152 */;
	struct dce110_resource_pool cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1505 */;
	struct resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1499 */;
	struct irq_service_init_data cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1401 */;
	struct dc_bios *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1324 */;
	struct dc_context *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1323 */;
	unsigned int cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1322 */;
	struct hw_asic_id cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1320 */;
	struct dce110_resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1319 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1317 */;
	bool cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1316 */;
	struct hw_asic_id *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1308 */;
	const struct resource_caps *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1307 */;
	struct dm_pp_clock_levels cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1253 */;
	struct dc *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1251 */;
	void cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1251 */;
	const struct resource_funcs cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1202 */;
	struct dc_link *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1176 */;
	int cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1174 */;
	const struct dce110_timing_generator_offsets cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 117 */[];
	struct stream_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1169 */;
	struct resource_pool **cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1160 */;
	struct tg_color cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1117 */;
	struct resource_context *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1100 */;
	const struct resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1096 */;
	struct dc_plane_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1033 */;
	struct dc_caps *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1011 */;
	const struct dc_plane_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dce110/dce110_resource.c 1010 */;
}
