cocci_test_suite() {
	struct output_pixel_processor *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 988 */;
	struct dc_log_buffer_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 98 */;
	const unsigned int cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 76 */;
	const uint32_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 75 */;
	enum dc_status cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 735 */;
	struct dc_bios *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 669 */;
	int cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 641 */;
	struct hubp *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 640 */;
	struct dce_hwseq *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 639 */;
	struct dc *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 637 */;
	void cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 637 */;
	unsigned int cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 466 */;
	struct link_enc_state cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 394 */;
	struct link_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 392 */;
	struct enc_state cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 373 */;
	struct stream_encoder *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 372 */;
	struct dcn_dsc_state cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 357 */;
	struct display_stream_compressor *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 356 */;
	const struct hw_sequencer_funcs cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3318 */;
	struct dc_clock_config *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3309 */;
	enum dc_clock_type cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3308 */;
	struct dc_clocks *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3274 */;
	struct dc_clock_config cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3273 */;
	const uint8_t *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3257 */;
	struct encoder_unblank_param cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3236 */;
	struct dc_link_settings *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3234 */;
	enum vertical_interrupt_ref_point cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3175 */;
	uint32_t *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3172 */;
	enum vline_select cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3171 */;
	struct pipe_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3170 */;
	struct dcn_otg_state cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 316 */;
	const struct dc_crtc_timing *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3145 */;
	struct dc_crtc_timing cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3087 */;
	struct dc_crtc_timing *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3073 */;
	struct custom_float_format cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3045 */;
	struct dpp_cursor_attributes cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3043 */;
	struct fixed31_32 cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3042 */;
	struct dc_cursor_attributes *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 3031 */;
	struct mpcc_state cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 300 */;
	struct dc_cursor_mi_param cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2968 */;
	struct dc_cursor_position cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2965 */;
	struct dchub_init_data *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2955 */;
	struct dc_plane_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2933 */;
	enum pipe_gating_control cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2926 */;
	uint8_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2924 */;
	struct crtc_stereo_flags cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2855 */;
	enum display_dongle_type cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2837 */;
	enum dc_timing_3d_format cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2820 */;
	enum view_3d_format cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2819 */;
	struct crtc_stereo_flags *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2817 */;
	const struct dc_static_screen_events *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2799 */;
	struct crtc_position *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2788 */;
	struct pipe_ctx **cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2786 */;
	struct drr_params cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2763 */;
	struct hubbub *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2730 */;
	struct dcn_dpp_state cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 259 */;
	bool cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2569 */;
	bool cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2568 */[4];
	uint32_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2567 */;
	struct timing_generator *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2566 */;
	struct dc_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2563 */;
	const struct dc_stream_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2561 */;
	struct dc_stream_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2424 */;
	struct stream_resource *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2423 */;
	struct tg_color cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2422 */;
	enum dc_color_space cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2421 */;
	struct plane_size cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2295 */;
	struct _vcs_dpi_display_ttu_regs_st *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 226 */;
	struct mpc_tree *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2199 */;
	struct mpc *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2198 */;
	struct mpcc *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2197 */;
	struct mpcc_blnd_cfg cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2194 */;
	struct dc_bias_and_scale cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2171 */;
	const struct dc_plane_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2149 */;
	struct dc_bias_and_scale *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2148 */;
	int32_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2111 */;
	struct tg_color *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2071 */;
	const struct pipe_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 2034 */;
	int16_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1967 */;
	uint16_t *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1953 */;
	struct _vcs_dpi_display_dlg_regs_st *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 194 */;
	uint16_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1939 */;
	struct dpp_grph_csc_adjustment cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1905 */;
	struct vm_context0_param cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1824 */;
	struct vm_system_aperture_param cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1823 */;
	struct dcn10_hubp *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1822 */;
	uint64_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1813 */;
	struct vm_context0_param *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1776 */;
	int64_t cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1770 */;
	struct vm_system_aperture_param *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1751 */;
	struct _vcs_dpi_display_rq_regs_st *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 169 */;
	struct dc_context *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1608 */;
	struct pipe_ctx *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1606 */[];
	struct dc_transfer_func *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1450 */;
	const struct dc_transfer_func *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1401 */;
	PHYSICAL_ADDRESS_LOC cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1375 */;
	const struct dc *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1372 */;
	struct dcn_hubp_state *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 137 */;
	PHYSICAL_ADDRESS_LOC *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1345 */;
	struct clock_source *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1333 */;
	struct audio *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1278 */;
	void *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 126 */;
	struct dc_link *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1250 */;
	struct resource_pool *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1186 */;
	struct dmcu *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1183 */;
	struct abm *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1182 */;
	struct dpp *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 1132 */;
	struct dcn_hubbub_wm_set *cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 111 */;
	struct dcn_hubbub_wm cocci_id/* drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c 101 */;
}
