cocci_test_suite() {
	struct drm_clip_rect *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 996 */;
	struct drm_file *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 994 */;
	void *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 99 */;
	unsigned long cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 97 */;
	struct ttm_bo_kmap_obj cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 96 */;
	u32 cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 93 */;
	struct vmw_private *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 91 */;
	enum SVGA3dSurfaceFormat cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 895 */;
	struct drm_connector_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 814 */;
	struct drm_connector *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 813 */;
	struct vmw_connector_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 756 */;
	struct {
		u32 cmd;
		SVGAFifoCmdDefineAlphaCursor cursor;
	} *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 61 */;
	struct vmw_crtc_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 588 */;
	u32 *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 58 */;
	struct drm_pending_vblank_event *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 563 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 488 */;
	struct vmw_surface *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 487 */;
	struct drm_plane_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 483 */;
	struct drm_plane *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 482 */;
	struct vmw_display_unit *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 42 */;
	s32 cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 383 */;
	struct vmw_plane_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 382 */;
	typeof(*vfbs) cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2829 */;
	struct vmw_framebuffer_surface *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2828 */;
	typeof(*vfbbo) cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2823 */;
	struct vmw_framebuffer_bo *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2822 */;
	char *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2807 */;
	struct drm_rect cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2799 */;
	struct drm_atomic_helper_damage_iter cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2798 */;
	struct vmw_du_update_plane *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2794 */;
	struct drm_display_mode **cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2652 */;
	struct drm_crtc **cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2651 */;
	struct drm_connector **cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2650 */;
	size_t cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2606 */;
	SVGA3dBox *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2605 */;
	struct {
		SVGA3dCmdHeader header;
		SVGA3dCmdUpdateGBImage body;
	} *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2601 */;
	struct drm_vmw_size *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2600 */;
	struct vmw_fence_obj *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2561 */;
	struct drm_vmw_fence_rep __user *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2558 */;
	struct vmw_fence_obj **cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2557 */;
	struct vmw_validation_context *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2556 */;
	struct vmw_display_unit *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2447 */[VMWGFX_NUM_DISPLAY_UNITS];
	struct vmw_kms_dirty *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2445 */;
	const struct drm_vmw_rect *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2441 */;
	const struct drm_clip_rect *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2440 */;
	struct drm_vmw_rect cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2356 */;
	void __user *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2341 */;
	struct drm_vmw_update_layout_arg *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2339 */;
	struct drm_mode_config *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2338 */;
	struct drm_display_mode cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2241 */;
	struct drm_display_mode *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2239 */;
	struct drm_display_mode cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2134 */[];
	enum drm_connector_status cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2119 */;
	struct drm_modeset_acquire_ctx *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2098 */;
	u16 *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2096 */;
	struct drm_modeset_acquire_ctx cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2028 */;
	struct drm_connector_list_iter cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2027 */;
	struct drm_rect *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 2022 */;
	struct vmw_vga_topology_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1951 */;
	struct drm_vmw_cursor_bypass_arg *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1842 */;
	SVGA3dCopyBox cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 180 */;
	SVGA3dCmdSurfaceDMA cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 179 */;
	struct drm_vmw_rect *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1737 */;
	int32_t cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1736 */;
	const struct drm_mode_config_funcs cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1725 */;
	struct vmw_dma_cmd cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 162 */;
	struct vmw_dma_cmd {
		SVGA3dCmdHeader header;
		SVGA3dCmdSurfaceDMA dma;
	} *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 156 */;
	unsigned cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 153 */;
	struct drm_crtc *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1525 */;
	struct drm_atomic_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1525 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1524 */;
	SVGA3dCopyBox *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 152 */;
	SVGA3dCmdHeader *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 147 */;
	struct ttm_buffer_object *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 146 */;
	u64 cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1458 */;
	struct ttm_object_file *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 145 */;
	struct ttm_base_object *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1377 */;
	struct vmw_framebuffer **cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1217 */;
	void cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1203 */;
	struct drm_format_name_buf cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1151 */;
	unsigned int cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1150 */;
	struct vmw_resource *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1149 */;
	struct drm_vmw_size cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1148 */;
	uint32_t cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1147 */;
	struct vmw_surface **cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1145 */;
	struct vmw_buffer_object *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1144 */;
	const struct drm_mode_fb_cmd2 *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1143 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1142 */;
	int cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1142 */;
	struct ttm_placement *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1072 */;
	struct vmw_framebuffer *cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1068 */;
	const struct drm_framebuffer_funcs cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1059 */;
	struct drm_clip_rect cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 1002 */;
	bool cocci_id/* drivers/gpu/drm/vmwgfx/vmwgfx_kms.c 100 */;
}
