cocci_test_suite() {
	gfp_t cocci_id/* drivers/gpu/drm/tegra/drm.c 967 */;
	struct iova *cocci_id/* drivers/gpu/drm/tegra/drm.c 965 */;
	dma_addr_t *cocci_id/* drivers/gpu/drm/tegra/drm.c 963 */;
	size_t cocci_id/* drivers/gpu/drm/tegra/drm.c 963 */;
	void cocci_id/* drivers/gpu/drm/tegra/drm.c 942 */;
	struct iommu_group *cocci_id/* drivers/gpu/drm/tegra/drm.c 910 */;
	struct tegra_drm *cocci_id/* drivers/gpu/drm/tegra/drm.c 909 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/tegra/drm.c 908 */;
	struct iommu_domain *cocci_id/* drivers/gpu/drm/tegra/drm.c 907 */;
	struct host1x_client *cocci_id/* drivers/gpu/drm/tegra/drm.c 905 */;
	int cocci_id/* drivers/gpu/drm/tegra/drm.c 905 */;
	struct drm_driver cocci_id/* drivers/gpu/drm/tegra/drm.c 850 */;
	struct drm_minor *cocci_id/* drivers/gpu/drm/tegra/drm.c 842 */;
	struct drm_info_list cocci_id/* drivers/gpu/drm/tegra/drm.c 837 */[];
	struct drm_printer cocci_id/* drivers/gpu/drm/tegra/drm.c 826 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/tegra/drm.c 804 */;
	struct drm_info_node *cocci_id/* drivers/gpu/drm/tegra/drm.c 802 */;
	struct seq_file *cocci_id/* drivers/gpu/drm/tegra/drm.c 800 */;
	const struct drm_mode_config_helper_funcs cocci_id/* drivers/gpu/drm/tegra/drm.c 80 */;
	const struct file_operations cocci_id/* drivers/gpu/drm/tegra/drm.c 765 */;
	const struct drm_ioctl_desc cocci_id/* drivers/gpu/drm/tegra/drm.c 732 */[];
	struct drm_tegra_gem_get_flags *cocci_id/* drivers/gpu/drm/tegra/drm.c 712 */;
	struct drm_tegra_gem_set_flags *cocci_id/* drivers/gpu/drm/tegra/drm.c 687 */;
	struct drm_tegra_gem_get_tiling *cocci_id/* drivers/gpu/drm/tegra/drm.c 647 */;
	enum tegra_bo_tiling_mode cocci_id/* drivers/gpu/drm/tegra/drm.c 595 */;
	struct drm_tegra_gem_set_tiling *cocci_id/* drivers/gpu/drm/tegra/drm.c 594 */;
	struct host1x_syncpt_base *cocci_id/* drivers/gpu/drm/tegra/drm.c 559 */;
	struct drm_tegra_get_syncpt_base *cocci_id/* drivers/gpu/drm/tegra/drm.c 557 */;
	const struct drm_mode_config_funcs cocci_id/* drivers/gpu/drm/tegra/drm.c 53 */;
	struct drm_tegra_get_syncpt *cocci_id/* drivers/gpu/drm/tegra/drm.c 504 */;
	struct drm_tegra_close_channel *cocci_id/* drivers/gpu/drm/tegra/drm.c 480 */;
	void *cocci_id/* drivers/gpu/drm/tegra/drm.c 476 */;
	struct drm_tegra_open_channel *cocci_id/* drivers/gpu/drm/tegra/drm.c 448 */;
	struct tegra_drm_context *cocci_id/* drivers/gpu/drm/tegra/drm.c 423 */;
	struct tegra_drm_client *cocci_id/* drivers/gpu/drm/tegra/drm.c 422 */;
	struct tegra_drm_file *cocci_id/* drivers/gpu/drm/tegra/drm.c 421 */;
	struct drm_atomic_state *cocci_id/* drivers/gpu/drm/tegra/drm.c 42 */;
	struct drm_tegra_syncpt_wait *cocci_id/* drivers/gpu/drm/tegra/drm.c 409 */;
	struct drm_tegra_syncpt_incr *cocci_id/* drivers/gpu/drm/tegra/drm.c 395 */;
	struct drm_tegra_syncpt_read *cocci_id/* drivers/gpu/drm/tegra/drm.c 380 */;
	struct tegra_drm_file {
		struct idr contexts;
		struct mutex lock;
	} cocci_id/* drivers/gpu/drm/tegra/drm.c 36 */;
	struct drm_tegra_gem_mmap *cocci_id/* drivers/gpu/drm/tegra/drm.c 359 */;
	struct drm_tegra_gem_create *cocci_id/* drivers/gpu/drm/tegra/drm.c 345 */;
	struct drm_tegra_cmdbuf cocci_id/* drivers/gpu/drm/tegra/drm.c 217 */;
	struct host1x_job *cocci_id/* drivers/gpu/drm/tegra/drm.c 175 */;
	struct host1x_syncpt *cocci_id/* drivers/gpu/drm/tegra/drm.c 174 */;
	struct drm_gem_object **cocci_id/* drivers/gpu/drm/tegra/drm.c 173 */;
	struct host1x *cocci_id/* drivers/gpu/drm/tegra/drm.c 172 */;
	struct drm_tegra_syncpt cocci_id/* drivers/gpu/drm/tegra/drm.c 171 */;
	struct drm_tegra_syncpt __user *cocci_id/* drivers/gpu/drm/tegra/drm.c 170 */;
	struct drm_tegra_cmdbuf __user *cocci_id/* drivers/gpu/drm/tegra/drm.c 168 */;
	unsigned int cocci_id/* drivers/gpu/drm/tegra/drm.c 166 */;
	struct drm_tegra_submit *cocci_id/* drivers/gpu/drm/tegra/drm.c 162 */;
	void __exit cocci_id/* drivers/gpu/drm/tegra/drm.c 1361 */;
	int __init cocci_id/* drivers/gpu/drm/tegra/drm.c 1341 */;
	struct platform_driver *const cocci_id/* drivers/gpu/drm/tegra/drm.c 1329 */[];
	struct host1x_driver cocci_id/* drivers/gpu/drm/tegra/drm.c 1319 */;
	const struct of_device_id cocci_id/* drivers/gpu/drm/tegra/drm.c 1284 */[];
	struct device *cocci_id/* drivers/gpu/drm/tegra/drm.c 1273 */;
	struct drm_tegra_reloc __user *cocci_id/* drivers/gpu/drm/tegra/drm.c 121 */;
	struct host1x_reloc *cocci_id/* drivers/gpu/drm/tegra/drm.c 120 */;
	unsigned long cocci_id/* drivers/gpu/drm/tegra/drm.c 1135 */;
	dma_addr_t cocci_id/* drivers/gpu/drm/tegra/drm.c 1134 */;
	u64 cocci_id/* drivers/gpu/drm/tegra/drm.c 1132 */;
	struct tegra_bo *cocci_id/* drivers/gpu/drm/tegra/drm.c 110 */;
	struct drm_gem_object *cocci_id/* drivers/gpu/drm/tegra/drm.c 109 */;
	u32 cocci_id/* drivers/gpu/drm/tegra/drm.c 107 */;
	struct drm_file *cocci_id/* drivers/gpu/drm/tegra/drm.c 107 */;
	struct host1x_bo *cocci_id/* drivers/gpu/drm/tegra/drm.c 106 */;
	struct drm_driver *cocci_id/* drivers/gpu/drm/tegra/drm.c 1042 */;
	struct host1x_device *cocci_id/* drivers/gpu/drm/tegra/drm.c 1040 */;
}
