cocci_test_suite() {
	unsigned long cocci_id/* drivers/gpu/drm/tegra/sor.c 999 */;
	const struct drm_dp_link_ops cocci_id/* drivers/gpu/drm/tegra/sor.c 949 */;
	const struct tegra_sor_soc *cocci_id/* drivers/gpu/drm/tegra/sor.c 806 */;
	struct clk_init_data cocci_id/* drivers/gpu/drm/tegra/sor.c 598 */;
	const char *cocci_id/* drivers/gpu/drm/tegra/sor.c 595 */;
	struct clk *cocci_id/* drivers/gpu/drm/tegra/sor.c 594 */;
	const struct clk_ops cocci_id/* drivers/gpu/drm/tegra/sor.c 589 */;
	u32 cocci_id/* drivers/gpu/drm/tegra/sor.c 570 */;
	struct tegra_clk_sor_pad *cocci_id/* drivers/gpu/drm/tegra/sor.c 567 */;
	u8 cocci_id/* drivers/gpu/drm/tegra/sor.c 565 */;
	struct clk_hw *cocci_id/* drivers/gpu/drm/tegra/sor.c 565 */;
	int cocci_id/* drivers/gpu/drm/tegra/sor.c 541 */;
	const char *constcocci_id/* drivers/gpu/drm/tegra/sor.c 528 */[2][2];
	struct tegra_clk_sor_pad cocci_id/* drivers/gpu/drm/tegra/sor.c 525 */;
	struct tegra_clk_sor_pad {
		struct clk_hw hw;
		struct tegra_sor *sor;
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 518 */;
	struct tegra_sor cocci_id/* drivers/gpu/drm/tegra/sor.c 477 */;
	struct host1x_client *cocci_id/* drivers/gpu/drm/tegra/sor.c 475 */;
	struct tegra_sor *cocci_id/* drivers/gpu/drm/tegra/sor.c 474 */;
	struct tegra_sor_config {
		u32 bits_per_pixel;
		u32 active_polarity;
		u32 active_count;
		u32 tu_size;
		u32 active_frac;
		u32 watermark;
		u32 hblank_symbols;
		u32 vblank_symbols;
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 461 */;
	struct tegra_sor_state cocci_id/* drivers/gpu/drm/tegra/sor.c 458 */;
	struct tegra_sor_state {
		struct drm_connector_state base;
		unsigned int link_speed;
		unsigned long pclk;
		unsigned int bpc;
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 447 */;
	struct tegra_sor {
		struct host1x_client client;
		struct tegra_output output;
		struct device *dev;
		const struct tegra_sor_soc *soc;
		void __iomem *regs;
		unsigned int index;
		unsigned int irq;
		struct reset_control *rst;
		struct clk *clk_parent;
		struct clk *clk_safe;
		struct clk *clk_out;
		struct clk *clk_pad;
		struct clk *clk_dp;
		struct clk *clk;
		u8 xbar_cfg[5];
		struct drm_dp_link link;
		struct drm_dp_aux *aux;
		struct drm_info_list *debugfs_files;
		const struct tegra_sor_ops *ops;
		enum tegra_io_pad pad;
		struct tegra_sor_hdmi_settings *settings;
		unsigned int num_settings;
		struct regulator *avdd_io_supply;
		struct regulator *vdd_pll_supply;
		struct regulator *hdmi_supply;
		struct delayed_work scdc;
		bool scdc_enabled;
		struct tegra_hda_format format;
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 405 */;
	struct platform_driver cocci_id/* drivers/gpu/drm/tegra/sor.c 4004 */;
	struct device *cocci_id/* drivers/gpu/drm/tegra/sor.c 3984 */;
	struct tegra_sor_ops {
		const char *name;
		int (*probe)(struct tegra_sor *sor);
		int (*remove)(struct tegra_sor *sor);
		void (*audio_enable)(struct tegra_sor *sor);
		void (*audio_disable)(struct tegra_sor *sor);
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 397 */;
	char *cocci_id/* drivers/gpu/drm/tegra/sor.c 3843 */;
	struct tegra_sor_soc {
		bool supports_lvds;
		bool supports_hdmi;
		bool supports_dp;
		bool supports_audio;
		bool supports_hdcp;
		const struct tegra_sor_regs *regs;
		bool has_nvdisplay;
		const struct tegra_sor_hdmi_settings *settings;
		unsigned int num_settings;
		const u8 *xbar_cfg;
		const u8 *lane_map;
		const u8 *voltage_swing[4][4];
		const u8 *pre_emphasis[4][4];
		const u8 *post_cursor[4][4];
		const u8 *tx_pu[4][4];
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 373 */;
	struct resource *cocci_id/* drivers/gpu/drm/tegra/sor.c 3638 */;
	struct platform_device *cocci_id/* drivers/gpu/drm/tegra/sor.c 3634 */;
	irqreturn_t cocci_id/* drivers/gpu/drm/tegra/sor.c 3605 */;
	void *cocci_id/* drivers/gpu/drm/tegra/sor.c 3605 */;
	struct tegra_sor_hdmi_settings {
		unsigned long frequency;
		u8 vcocap;
		u8 filter;
		u8 ichpmp;
		u8 loadadj;
		u8 tmds_termadj;
		u8 tx_pu_value;
		u8 bg_temp_coef;
		u8 bg_vref_level;
		u8 avdd10_level;
		u8 avdd14_level;
		u8 sparepll;
		u8 drive_current[4];
		u8 preemphasis[4];
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 36 */;
	struct tegra_sor_regs {
		unsigned int head_state0;
		unsigned int head_state1;
		unsigned int head_state2;
		unsigned int head_state3;
		unsigned int head_state4;
		unsigned int head_state5;
		unsigned int pll0;
		unsigned int pll1;
		unsigned int pll2;
		unsigned int pll3;
		unsigned int dp_padctl0;
		unsigned int dp_padctl2;
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 358 */;
	u32 cocci_id/* drivers/gpu/drm/tegra/sor.c 3567 */[5];
	struct device_node *cocci_id/* drivers/gpu/drm/tegra/sor.c 3566 */;
	const struct of_device_id cocci_id/* drivers/gpu/drm/tegra/sor.c 3553 */[];
	const struct tegra_sor_soc cocci_id/* drivers/gpu/drm/tegra/sor.c 3317 */;
	const u8 cocci_id/* drivers/gpu/drm/tegra/sor.c 3269 */[4][4][4];
	const u8 cocci_id/* drivers/gpu/drm/tegra/sor.c 3217 */[4];
	const struct tegra_sor_regs cocci_id/* drivers/gpu/drm/tegra/sor.c 3201 */;
	const u8 cocci_id/* drivers/gpu/drm/tegra/sor.c 3197 */[5];
	const struct host1x_client_ops cocci_id/* drivers/gpu/drm/tegra/sor.c 3192 */;
	const struct drm_encoder_helper_funcs *cocci_id/* drivers/gpu/drm/tegra/sor.c 3057 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/tegra/sor.c 3056 */;
	const struct tegra_sor_ops cocci_id/* drivers/gpu/drm/tegra/sor.c 3048 */;
	const struct drm_encoder_helper_funcs cocci_id/* drivers/gpu/drm/tegra/sor.c 2944 */;
	struct drm_display_info *cocci_id/* drivers/gpu/drm/tegra/sor.c 2736 */;
	struct tegra_sor_config cocci_id/* drivers/gpu/drm/tegra/sor.c 2733 */;
	struct tegra_dc *cocci_id/* drivers/gpu/drm/tegra/sor.c 2667 */;
	struct drm_encoder *cocci_id/* drivers/gpu/drm/tegra/sor.c 2664 */;
	struct tegra_sor_hdmi_settings *cocci_id/* drivers/gpu/drm/tegra/sor.c 2266 */;
	struct drm_scdc *cocci_id/* drivers/gpu/drm/tegra/sor.c 2208 */;
	struct work_struct *cocci_id/* drivers/gpu/drm/tegra/sor.c 2193 */;
	struct i2c_adapter *cocci_id/* drivers/gpu/drm/tegra/sor.c 2157 */;
	struct hdmi_audio_infoframe cocci_id/* drivers/gpu/drm/tegra/sor.c 2034 */;
	u8 cocci_id/* drivers/gpu/drm/tegra/sor.c 2033 */[HDMI_INFOFRAME_SIZE(AUDIO)];
	const struct tegra_sor_hdmi_settings cocci_id/* drivers/gpu/drm/tegra/sor.c 200 */[];
	struct hdmi_avi_infoframe cocci_id/* drivers/gpu/drm/tegra/sor.c 1928 */;
	u8 cocci_id/* drivers/gpu/drm/tegra/sor.c 1927 */[HDMI_INFOFRAME_SIZE(AVI)];
	const void *cocci_id/* drivers/gpu/drm/tegra/sor.c 1873 */;
	const u8 *cocci_id/* drivers/gpu/drm/tegra/sor.c 1861 */;
	size_t cocci_id/* drivers/gpu/drm/tegra/sor.c 1861 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/tegra/sor.c 1814 */;
	const struct drm_encoder_funcs cocci_id/* drivers/gpu/drm/tegra/sor.c 1808 */;
	const struct drm_connector_helper_funcs cocci_id/* drivers/gpu/drm/tegra/sor.c 1803 */;
	struct drm_display_mode *cocci_id/* drivers/gpu/drm/tegra/sor.c 1798 */;
	enum drm_mode_status cocci_id/* drivers/gpu/drm/tegra/sor.c 1796 */;
	const struct drm_connector_funcs cocci_id/* drivers/gpu/drm/tegra/sor.c 1768 */;
	struct tegra_sor_state *cocci_id/* drivers/gpu/drm/tegra/sor.c 1756 */;
	struct drm_connector_state *cocci_id/* drivers/gpu/drm/tegra/sor.c 1753 */;
	struct tegra_output *cocci_id/* drivers/gpu/drm/tegra/sor.c 1744 */;
	bool cocci_id/* drivers/gpu/drm/tegra/sor.c 1742 */;
	struct drm_connector *cocci_id/* drivers/gpu/drm/tegra/sor.c 1742 */;
	enum drm_connector_status cocci_id/* drivers/gpu/drm/tegra/sor.c 1741 */;
	struct dentry *cocci_id/* drivers/gpu/drm/tegra/sor.c 1688 */;
	struct drm_minor *cocci_id/* drivers/gpu/drm/tegra/sor.c 1687 */;
	const struct drm_info_list cocci_id/* drivers/gpu/drm/tegra/sor.c 1678 */[];
	const struct debugfs_reg32 cocci_id/* drivers/gpu/drm/tegra/sor.c 1532 */[];
	struct drm_crtc *cocci_id/* drivers/gpu/drm/tegra/sor.c 1492 */;
	struct drm_info_node *cocci_id/* drivers/gpu/drm/tegra/sor.c 1490 */;
	struct seq_file *cocci_id/* drivers/gpu/drm/tegra/sor.c 1488 */;
	const struct tegra_sor_config *cocci_id/* drivers/gpu/drm/tegra/sor.c 1244 */;
	void cocci_id/* drivers/gpu/drm/tegra/sor.c 1243 */;
	unsigned int cocci_id/* drivers/gpu/drm/tegra/sor.c 1161 */;
	struct tegra_sor_params cocci_id/* drivers/gpu/drm/tegra/sor.c 1159 */;
	u64 cocci_id/* drivers/gpu/drm/tegra/sor.c 1158 */;
	const u64 cocci_id/* drivers/gpu/drm/tegra/sor.c 1156 */;
	struct drm_dp_link *cocci_id/* drivers/gpu/drm/tegra/sor.c 1154 */;
	struct tegra_sor_config *cocci_id/* drivers/gpu/drm/tegra/sor.c 1153 */;
	const struct drm_display_mode *cocci_id/* drivers/gpu/drm/tegra/sor.c 1152 */;
	s64 cocci_id/* drivers/gpu/drm/tegra/sor.c 1090 */;
	struct tegra_sor_params *cocci_id/* drivers/gpu/drm/tegra/sor.c 1084 */;
	struct tegra_sor_params {
		unsigned int num_clocks;
		u64 ratio;
		u64 precision;
		unsigned int active_polarity;
		unsigned int active_count;
		unsigned int active_frac;
		unsigned int tu_size;
		unsigned int error;
	} cocci_id/* drivers/gpu/drm/tegra/sor.c 1068 */;
}
