cocci_test_suite() {
	struct atmel_hlcdc_dma_channel_dscr cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 997 */;
	const struct atmel_hlcdc_layer_desc *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 992 */;
	struct atmel_hlcdc_dc *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 991 */;
	uint32_t cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 99 */[];
	struct drm_device *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 989 */;
	int cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 989 */;
	enum drm_plane_type cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 952 */;
	const struct drm_plane_funcs cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 938 */;
	void cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 919 */;
	dma_addr_t cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 846 */;
	struct atmel_hlcdc_dma_channel_dscr *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 845 */;
	struct atmel_hlcdc_plane_state *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 839 */;
	struct drm_plane *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 838 */;
	const struct drm_plane_helper_funcs cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 832 */;
	struct atmel_hlcdc_plane_state cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 76 */;
	unsigned int cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 642 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 603 */;
	const struct drm_display_mode *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 602 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 601 */;
	struct atmel_hlcdc_plane *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 597 */;
	struct drm_plane_state *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 595 */;
	const struct atmel_hlcdc_layer_cfg_layout *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 520 */;
	unsigned int cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 483 */[2];
	struct drm_gem_cma_object *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 449 */;
	struct atmel_hlcdc_plane_state {
		struct drm_plane_state base;
		int crtc_x;
		int crtc_y;
		unsigned int crtc_w;
		unsigned int crtc_h;
		uint32_t src_x;
		uint32_t src_y;
		uint32_t src_w;
		uint32_t src_h;
		int disc_x;
		int disc_y;
		int disc_w;
		int disc_h;
		int ahb_id;
		int bpp[ATMEL_HLCDC_LAYER_MAX_PLANES];
		unsigned int offsets[ATMEL_HLCDC_LAYER_MAX_PLANES];
		int xstride[ATMEL_HLCDC_LAYER_MAX_PLANES];
		int pstride[ATMEL_HLCDC_LAYER_MAX_PLANES];
		int nplanes;
		struct atmel_hlcdc_dma_channel_dscr *dscrs[ATMEL_HLCDC_LAYER_MAX_PLANES];
	} cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 44 */;
	struct drm_color_lut *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 418 */;
	struct drm_crtc *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 417 */;
	const struct drm_format_info *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 362 */;
	const u32 *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 273 */;
	u32 cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 193 */[];
	u32 cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 126 */;
	u32 *cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 126 */;
	struct atmel_hlcdc_formats cocci_id/* drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_plane.c 121 */;
}
