cocci_test_suite() {
	irqreturn_t cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 929 */;
	struct drm_exynos_pending_g2d_event cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 919 */;
	struct timespec64 cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 913 */;
	u32 cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 908 */;
	struct g2d_data cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 871 */;
	struct work_struct *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 869 */;
	struct g2d_runqueue_node cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 823 */;
	struct drm_exynos_g2d_userptr cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 735 */;
	struct exynos_drm_gem *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 717 */;
	dma_addr_t *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 701 */;
	enum g2d_reg_type cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 634 */;
	struct g2d_buf_desc *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 633 */;
	bool cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 632 */;
	unsigned int cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 605 */;
	struct g2d_cmdlist_userptr *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 555 */;
	struct sg_table *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 426 */;
	void **cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 422 */;
	struct page **cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 380 */;
	struct g2d_cmdlist_node cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 365 */;
	void cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 355 */;
	struct g2d_data {
		struct device *dev;
		struct clk *gate_clk;
		void __iomem *regs;
		int irq;
		struct workqueue_struct *g2d_workq;
		struct work_struct runqueue_work;
		struct drm_device *drm_dev;
		unsigned long flags;
		struct g2d_cmdlist_node *cmdlist_node;
		struct list_head free_cmdlist;
		struct mutex cmdlist_mutex;
		dma_addr_t cmdlist_pool;
		void *cmdlist_pool_virt;
		unsigned long cmdlist_dma_attrs;
		struct g2d_runqueue_node *runqueue_node;
		struct list_head runqueue;
		struct mutex runqueue_mutex;
		struct kmem_cache *runqueue_slab;
		unsigned long current_pool;
		unsigned long max_pool;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 233 */;
	struct g2d_runqueue_node {
		struct list_head list;
		struct list_head run_cmdlist;
		struct list_head event_list;
		struct drm_file *filp;
		pid_t pid;
		struct completion complete;
		int async;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 223 */;
	struct g2d_cmdlist_node {
		struct list_head list;
		struct g2d_cmdlist *cmdlist;
		dma_addr_t dma_addr;
		struct g2d_buf_info buf_info;
		struct drm_exynos_pending_g2d_event *event;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 214 */;
	struct g2d_cmdlist_userptr {
		struct list_head list;
		dma_addr_t dma_addr;
		unsigned long userptr;
		unsigned long size;
		struct frame_vector *vec;
		struct sg_table *sgt;
		atomic_t refcount;
		bool in_pool;
		bool out_of_list;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 203 */;
	struct drm_exynos_pending_g2d_event {
		struct drm_pending_event base;
		struct drm_exynos_g2d_event event;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 198 */;
	struct g2d_buf_info {
		unsigned int map_nr;
		enum g2d_reg_type reg_types[MAX_REG_TYPE_NR];
		void *obj[MAX_REG_TYPE_NR];
		unsigned int types[MAX_REG_TYPE_NR];
		struct g2d_buf_desc descs[MAX_REG_TYPE_NR];
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 190 */;
	struct g2d_buf_desc {
		unsigned int format;
		unsigned int stride;
		unsigned int left_x;
		unsigned int top_y;
		unsigned int right_x;
		unsigned int bottom_y;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 171 */;
	struct platform_driver cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1614 */;
	const struct of_device_id cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1607 */[];
	struct g2d_cmdlist {
		u32 head;
		unsigned long data[G2D_CMDLIST_DATA_NUM];
		u32 last;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 154 */;
	struct resource *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1448 */;
	struct platform_device *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1445 */;
	const struct component_ops cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1440 */;
	enum g2d_flag_bits{G2D_BIT_SUSPEND_RUNQUEUE, G2D_BIT_ENGINE_BUSY,} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 141 */;
	struct device *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1396 */;
	struct list_head *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1302 */;
	struct g2d_runqueue_node *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1301 */;
	struct drm_exynos_g2d_exec *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1300 */;
	enum g2d_reg_type{REG_TYPE_NONE=-1, REG_TYPE_SRC, REG_TYPE_SRC_PLANE2, REG_TYPE_DST, REG_TYPE_DST_PLANE2, REG_TYPE_PAT, REG_TYPE_MSK, MAX_REG_TYPE_NR,} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 130 */;
	struct g2d_data *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1299 */;
	struct exynos_drm_private *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1298 */;
	struct drm_exynos_file_private *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1297 */;
	struct drm_file *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1295 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1294 */;
	void *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1294 */;
	int cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1294 */;
	enum{BUF_TYPE_GEM=1, BUF_TYPE_USERPTR,} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 125 */;
	void __user *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1236 */;
	unsigned long cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1233 */;
	struct g2d_cmdlist *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1145 */;
	struct g2d_cmdlist_node *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1144 */;
	struct drm_exynos_pending_g2d_event *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1143 */;
	struct drm_exynos_g2d_cmd *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1142 */;
	struct drm_exynos_g2d_set_cmdlist *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1141 */;
	struct drm_exynos_g2d_get_ver *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1127 */;
	struct g2d_buf_info *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_g2d.c 1029 */;
}
