cocci_test_suite() {
	struct fimd_driver_data {
		unsigned int timing_base;
		unsigned int lcdblk_offset;
		unsigned int lcdblk_vt_shift;
		unsigned int lcdblk_bypass_shift;
		unsigned int lcdblk_mic_bypass_shift;
		unsigned int trg_type;
		unsigned int has_shadowcon:1;
		unsigned int has_clksel:1;
		unsigned int has_limited_fmt:1;
		unsigned int has_vidoutcon:1;
		unsigned int has_vtsel:1;
		unsigned int has_mic_bypass:1;
		unsigned int has_dp_clk:1;
		unsigned int has_hw_trigger:1;
		unsigned int has_trigger_per_te:1;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 95 */;
	dma_addr_t cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 794 */;
	struct drm_framebuffer *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 793 */;
	struct exynos_drm_plane_state *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 790 */;
	struct exynos_drm_crtc *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 761 */;
	void cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 761 */;
	uint32_t cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 642 */;
	struct exynos_drm_plane cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 639 */;
	const struct fimd_driver_data *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 457 */;
	void __iomem *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 435 */;
	u32 cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 395 */;
	unsigned long cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 394 */;
	struct drm_display_mode *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 392 */;
	struct drm_crtc_state *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 390 */;
	const unsigned int cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 228 */[WINDOWS_NR];
	const uint32_t cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 220 */[];
	const enum drm_plane_type cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 212 */[WINDOWS_NR];
	const struct of_device_id cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 195 */[];
	struct fimd_context {
		struct device *dev;
		struct drm_device *drm_dev;
		struct exynos_drm_crtc *crtc;
		struct exynos_drm_plane planes[WINDOWS_NR];
		struct exynos_drm_plane_config configs[WINDOWS_NR];
		struct clk *bus_clk;
		struct clk *lcd_clk;
		void __iomem *regs;
		struct regmap *sysreg;
		unsigned long irq_flags;
		u32 vidcon0;
		u32 vidcon1;
		u32 vidout_con;
		u32 i80ifcon;
		bool i80_if;
		bool suspended;
		wait_queue_head_t wait_vsync_queue;
		atomic_t wait_vsync_event;
		atomic_t win_updated;
		atomic_t triggering;
		u32 clkdiv;
		const struct fimd_driver_data *driver_data;
		struct drm_encoder *encoder;
		struct exynos_drm_clk dp_clk;
	} cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 167 */;
	struct platform_driver cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1282 */;
	struct fimd_driver_data cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 126 */;
	struct fimd_context *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1253 */;
	struct device *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1251 */;
	int cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1251 */;
	struct resource *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1119 */;
	struct device_node *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1118 */;
	struct platform_device *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1114 */;
	const struct component_ops cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1109 */;
	unsigned int cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1059 */;
	struct exynos_drm_plane *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1058 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1057 */;
	void *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1054 */;
	irqreturn_t cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1021 */;
	const struct exynos_drm_crtc_ops cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1008 */;
	struct fimd_context cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1002 */;
	bool cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1000 */;
	struct exynos_drm_clk *cocci_id/* drivers/gpu/drm/exynos/exynos_drm_fimd.c 1000 */;
}
