cocci_test_suite() {
	struct edid *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 972 */;
	const struct drm_bridge_funcs cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 959 */;
	struct drm_display_mode cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 937 */;
	const struct drm_display_mode *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 928 */;
	struct hdmi_audio_infoframe *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 832 */;
	struct hdmi_audio_params *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 831 */;
	int cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 828 */;
	unsigned int cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 732 */;
	struct drm_minor *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 730 */;
	struct drm_info_list cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 726 */[];
	struct drm_info_node *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 664 */;
	char *const cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 637 */[];
	struct seq_file *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 598 */;
	u8 cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 517 */[HDMI_INFOFRAME_HEADER_SIZE + HDMI_VENDOR_INFOFRAME_MAX_SIZE];
	struct hdmi_vendor_infoframe cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 516 */;
	u8 cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 477 */[HDMI_INFOFRAME_SIZE(AUDIO)];
	u8 cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 435 */[HDMI_INFOFRAME_SIZE(AVI)];
	struct hdmi_avi_infoframe cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 434 */;
	struct drm_display_mode *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 433 */;
	unsigned long cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 341 */;
	const u8 *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 339 */;
	u32 cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 241 */;
	struct sti_hdmi *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 239 */;
	void cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 239 */;
	irqreturn_t cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 218 */;
	struct sti_hdmi_connector cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 168 */;
	struct sti_hdmi_connector {
		struct drm_connector drm_connector;
		struct drm_encoder *encoder;
		struct sti_hdmi *hdmi;
		struct drm_property *colorspace_property;
	} cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 160 */;
	struct platform_driver cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1479 */;
	struct hdmi_phy_ops *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1402 */;
	struct resource *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1369 */;
	struct device_node *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1368 */;
	struct platform_device *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1364 */;
	const struct of_device_id cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1354 */[];
	const struct component_ops cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1349 */;
	struct drm_bridge *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1262 */;
	struct cec_connector_info cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1260 */;
	struct sti_hdmi_connector *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1259 */;
	struct drm_encoder *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1258 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1257 */;
	struct hdmi_codec_pdata cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1232 */;
	const struct hdmi_codec_ops cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1222 */;
	struct drm_connector *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1214 */;
	uint8_t *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1211 */;
	size_t cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1211 */;
	bool cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1197 */;
	struct device *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1197 */;
	void *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1197 */;
	struct hdmi_codec_params *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1167 */;
	struct hdmi_codec_daifmt *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1166 */;
	const struct drm_connector_funcs cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1124 */;
	uint64_t *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1095 */;
	struct drm_property *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1094 */;
	const struct drm_connector_state *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1093 */;
	uint64_t cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1076 */;
	struct drm_connector_state *cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1074 */;
	enum drm_connector_status cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1032 */;
	const struct drm_connector_helper_funcs cocci_id/* drivers/gpu/drm/sti/sti_hdmi.c 1025 */;
}
