cocci_test_suite() {
	struct msm_gpu_config cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 941 */;
	struct adreno_platform_config *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 940 */;
	const struct adreno_gpu_funcs *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 938 */;
	struct platform_device *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 936 */;
	struct drm_device *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 936 */;
	struct adreno_ocmem *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 929 */;
	struct ocmem *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 901 */;
	struct ocmem_buf *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 900 */;
	struct dev_pm_opp *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 857 */;
	unsigned long cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 856 */;
	unsigned int cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 834 */;
	struct device_node *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 824 */;
	struct device *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 822 */;
	uint32_t cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 792 */;
	int cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 784 */;
	struct adreno_gpu *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 783 */;
	void cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 781 */;
	struct drm_printer *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 697 */;
	bool *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 656 */;
	void **cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 655 */;
	long cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 629 */;
	char cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 628 */[ASCII85_BUFSZ];
	u32 *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 624 */;
	char *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 624 */;
	size_t cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 624 */;
	struct msm_gpu_state cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 608 */;
	struct kref *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 605 */;
	struct msm_gpu_state *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 589 */;
	u32 cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 568 */;
	bool cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 508 */;
	unsigned cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 421 */;
	struct msm_drm_private *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 419 */;
	struct msm_file_private *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 416 */;
	struct msm_gem_submit *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 415 */;
	struct msm_ringbuffer *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 392 */;
	struct msm_gpu *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 392 */;
	ssize_t cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 32 */;
	void *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 318 */;
	const struct firmware *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 315 */;
	u64 *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 315 */;
	struct drm_gem_object *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 314 */;
	phys_addr_t cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 31 */;
	struct resource cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 30 */;
	const char *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 210 */;
	uint64_t *cocci_id/* drivers/gpu/drm/msm/adreno/adreno_gpu.c 160 */;
}
