cocci_test_suite() {
	const struct hdmi_phy_cfg cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 757 */;
	const char *constcocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 753 */[];
	struct hdmi_8996_post_divider {
		u64 vco_freq;
		int hsclk_divsel;
		int vco_ratio;
		int tx_band_sel;
		int half_rate_mode;
	} cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 73 */;
	char cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 726 */[32];
	struct clk *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 710 */;
	struct device *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 708 */;
	struct platform_device *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 706 */;
	struct clk_init_data cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 698 */;
	struct clk_ops cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 685 */;
	struct hdmi_pll_8996 *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 675 */;
	struct clk_hw *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 673 */;
	void cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 664 */;
	u64 cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 648 */;
	unsigned long *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 634 */;
	long cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 632 */;
	unsigned long cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 546 */;
	u32 cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 545 */;
	struct hdmi_phy *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 543 */;
	int cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 543 */;
	struct hdmi_8996_phy_pll_reg_cfg {
		u32 tx_lx_lane_mode[HDMI_NUM_TX_CHANNEL];
		u32 tx_lx_tx_band[HDMI_NUM_TX_CHANNEL];
		u32 com_svs_mode_clk_sel;
		u32 com_hsclk_sel;
		u32 com_pll_cctrl_mode0;
		u32 com_pll_rctrl_mode0;
		u32 com_cp_ctrl_mode0;
		u32 com_dec_start_mode0;
		u32 com_div_frac_start1_mode0;
		u32 com_div_frac_start2_mode0;
		u32 com_div_frac_start3_mode0;
		u32 com_integloop_gain0_mode0;
		u32 com_integloop_gain1_mode0;
		u32 com_lock_cmp_en;
		u32 com_lock_cmp1_mode0;
		u32 com_lock_cmp2_mode0;
		u32 com_lock_cmp3_mode0;
		u32 com_core_clk_en;
		u32 com_coreclk_div;
		u32 com_vco_tune_ctrl;
		u32 tx_lx_tx_drv_lvl[HDMI_NUM_TX_CHANNEL];
		u32 tx_lx_tx_emp_post1_lvl[HDMI_NUM_TX_CHANNEL];
		u32 tx_lx_vmode_ctrl1[HDMI_NUM_TX_CHANNEL];
		u32 tx_lx_vmode_ctrl2[HDMI_NUM_TX_CHANNEL];
		u32 tx_lx_res_code_lane_tx[HDMI_NUM_TX_CHANNEL];
		u32 tx_lx_hp_pd_enables[HDMI_NUM_TX_CHANNEL];
		u32 phy_mode;
	} cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 41 */;
	struct hdmi_8996_phy_pll_reg_cfg cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 400 */;
	struct hdmi_pll_8996 cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 39 */;
	struct hdmi_pll_8996 {
		struct platform_device *pdev;
		struct clk_hw clk_hw;
		void __iomem *mmio_qserdes_com;
		void __iomem *mmio_qserdes_tx[HDMI_NUM_TX_CHANNEL];
	} cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 29 */;
	struct hdmi_8996_post_divider cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 221 */;
	struct hdmi_8996_phy_pll_reg_cfg *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 219 */;
	u64 cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 171 */[60];
	int cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 168 */[];
	struct hdmi_8996_post_divider *cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 166 */;
	bool cocci_id/* drivers/gpu/drm/msm/hdmi/hdmi_phy_8996.c 120 */;
}
