cocci_test_suite() {
	struct acpi_table_dmar *cocci_id/* drivers/iommu/dmar.c 889 */;
	struct dmar_res_callback cocci_id/* drivers/iommu/dmar.c 881 */;
	int __init cocci_id/* drivers/iommu/dmar.c 878 */;
	void __iomem *cocci_id/* drivers/iommu/dmar.c 844 */;
	int __ref cocci_id/* drivers/iommu/dmar.c 840 */;
	int *cocci_id/* drivers/iommu/dmar.c 80 */;
	struct acpi_device *cocci_id/* drivers/iommu/dmar.c 745 */;
	acpi_handle cocci_id/* drivers/iommu/dmar.c 744 */;
	struct acpi_table_dmar cocci_id/* drivers/iommu/dmar.c 740 */;
	void *cocci_id/* drivers/iommu/dmar.c 740 */;
	struct acpi_dmar_andd *cocci_id/* drivers/iommu/dmar.c 735 */;
	struct acpi_dmar_hardware_unit cocci_id/* drivers/iommu/dmar.c 702 */;
	struct acpi_dmar_pci_path *cocci_id/* drivers/iommu/dmar.c 698 */;
	struct device *cocci_id/* drivers/iommu/dmar.c 696 */;
	struct acpi_dmar_device_scope *cocci_id/* drivers/iommu/dmar.c 695 */;
	struct acpi_dmar_hardware_unit *cocci_id/* drivers/iommu/dmar.c 694 */;
	u8 cocci_id/* drivers/iommu/dmar.c 690 */;
	void __init cocci_id/* drivers/iommu/dmar.c 690 */;
	const struct iommu_ops cocci_id/* drivers/iommu/dmar.c 66 */;
	struct dmar_dev_scope cocci_id/* drivers/iommu/dmar.c 643 */[];
	void cocci_id/* drivers/iommu/dmar.c 64 */(struct intel_iommu *iommu);
	int cocci_id/* drivers/iommu/dmar.c 63 */(struct dmar_drhd_unit *drhd);
	unsigned long cocci_id/* drivers/iommu/dmar.c 61 */[BITS_TO_LONGS(DMAR_UNITS_SUPPORTED)];
	int __init cocci_id/* drivers/iommu/dmar.c 597 */;
	struct acpi_table_header *__initdata cocci_id/* drivers/iommu/dmar.c 59 */;
	struct dmar_res_callback *cocci_id/* drivers/iommu/dmar.c 588 */;
	struct acpi_dmar_rhsa cocci_id/* drivers/iommu/dmar.c 516 */;
	struct acpi_dmar_atsr cocci_id/* drivers/iommu/dmar.c 512 */;
	struct acpi_dmar_reserved_memory cocci_id/* drivers/iommu/dmar.c 505 */;
	struct acpi_dmar_atsr *cocci_id/* drivers/iommu/dmar.c 494 */;
	struct acpi_dmar_reserved_memory *cocci_id/* drivers/iommu/dmar.c 493 */;
	struct acpi_dmar_rhsa *cocci_id/* drivers/iommu/dmar.c 460 */;
	struct dmar_res_callback {
		dmar_res_handler_t cb[ACPI_DMAR_TYPE_RESERVED];
		void *arg[ACPI_DMAR_TYPE_RESERVED];
		bool ignore_unhandled;
		bool print_entry;
	} cocci_id/* drivers/iommu/dmar.c 37 */;
	int (*cocci_id/* drivers/iommu/dmar.c 36 */)(struct acpi_dmar_header *,
						     void *);
	struct notifier_block cocci_id/* drivers/iommu/dmar.c 356 */;
	struct notifier_block *cocci_id/* drivers/iommu/dmar.c 325 */;
	struct acpi_table_header *cocci_id/* drivers/iommu/dmar.c 2157 */;
	struct acpi_table_header **cocci_id/* drivers/iommu/dmar.c 2152 */;
	struct dmar_dev_scope *cocci_id/* drivers/iommu/dmar.c 212 */;
	acpi_status cocci_id/* drivers/iommu/dmar.c 2098 */;
	acpi_handle *cocci_id/* drivers/iommu/dmar.c 2084 */;
	void **cocci_id/* drivers/iommu/dmar.c 2082 */;
	struct acpi_dmar_header *cocci_id/* drivers/iommu/dmar.c 1955 */;
	int cocci_id/* drivers/iommu/dmar.c 1930 */[];
	union acpi_object *cocci_id/* drivers/iommu/dmar.c 1927 */;
	dmar_res_handler_t cocci_id/* drivers/iommu/dmar.c 1924 */;
	bool cocci_id/* drivers/iommu/dmar.c 1918 */;
	guid_t cocci_id/* drivers/iommu/dmar.c 1905 */;
	u16 cocci_id/* drivers/iommu/dmar.c 1727 */;
	irqreturn_t cocci_id/* drivers/iommu/dmar.c 1702 */;
	const char *cocci_id/* drivers/iommu/dmar.c 1682 */;
	struct msi_msg *cocci_id/* drivers/iommu/dmar.c 1665 */;
	struct irq_data *cocci_id/* drivers/iommu/dmar.c 1638 */;
	const char *const cocci_id/* drivers/iommu/dmar.c 1525 */[];
	const char *cocci_id/* drivers/iommu/dmar.c 1507 */[];
	enum faulttype{DMA_REMAP, INTR_REMAP, UNKNOWN,} cocci_id/* drivers/iommu/dmar.c 1501 */;
	struct page *cocci_id/* drivers/iommu/dmar.c 1453 */;
	u64 cocci_id/* drivers/iommu/dmar.c 1417 */;
	struct q_inval *cocci_id/* drivers/iommu/dmar.c 1416 */;
	unsigned long cocci_id/* drivers/iommu/dmar.c 1415 */;
	u32 cocci_id/* drivers/iommu/dmar.c 1414 */;
	struct intel_iommu *cocci_id/* drivers/iommu/dmar.c 1412 */;
	void cocci_id/* drivers/iommu/dmar.c 1412 */;
	cycles_t cocci_id/* drivers/iommu/dmar.c 1381 */;
	unsigned cocci_id/* drivers/iommu/dmar.c 1352 */;
	unsigned int cocci_id/* drivers/iommu/dmar.c 1328 */;
	struct qi_desc cocci_id/* drivers/iommu/dmar.c 1316 */;
	size_t cocci_id/* drivers/iommu/dmar.c 125 */;
	struct pci_dev *cocci_id/* drivers/iommu/dmar.c 122 */;
	struct dmar_pci_notify_info *cocci_id/* drivers/iommu/dmar.c 121 */;
	char cocci_id/* drivers/iommu/dmar.c 119 */[64];
	struct qi_desc *cocci_id/* drivers/iommu/dmar.c 1170 */;
	unsigned long long cocci_id/* drivers/iommu/dmar.c 1062 */;
	struct dmar_dev_scope **cocci_id/* drivers/iommu/dmar.c 103 */;
	struct dmar_drhd_unit *cocci_id/* drivers/iommu/dmar.c 1011 */;
	int cocci_id/* drivers/iommu/dmar.c 1011 */;
	struct dmar_dev_scope cocci_id/* drivers/iommu/dmar.c 100 */;
}
