cocci_test_suite() {
	struct platform_driver cocci_id/* drivers/usb/host/fhci-hcd.c 815 */;
	const struct of_device_id cocci_id/* drivers/usb/host/fhci-hcd.c 809 */[];
	struct device *cocci_id/* drivers/usb/host/fhci-hcd.c 781 */;
	enum fhci_mem_alloc cocci_id/* drivers/usb/host/fhci-hcd.c 64 */;
	enum of_gpio_flags cocci_id/* drivers/usb/host/fhci-hcd.c 634 */;
	u32 cocci_id/* drivers/usb/host/fhci-hcd.c 63 */;
	struct fhci_usb *cocci_id/* drivers/usb/host/fhci-hcd.c 63 */;
	const u32 *cocci_id/* drivers/usb/host/fhci-hcd.c 570 */;
	u16 cocci_id/* drivers/usb/host/fhci-hcd.c 57 */;
	const char *cocci_id/* drivers/usb/host/fhci-hcd.c 569 */;
	unsigned int cocci_id/* drivers/usb/host/fhci-hcd.c 568 */;
	struct resource cocci_id/* drivers/usb/host/fhci-hcd.c 566 */;
	struct device_node *cocci_id/* drivers/usb/host/fhci-hcd.c 563 */;
	struct platform_device *cocci_id/* drivers/usb/host/fhci-hcd.c 560 */;
	struct fhci_hcd cocci_id/* drivers/usb/host/fhci-hcd.c 537 */;
	const struct hc_driver cocci_id/* drivers/usb/host/fhci-hcd.c 534 */;
	int cocci_id/* drivers/usb/host/fhci-hcd.c 527 */;
	struct td *cocci_id/* drivers/usb/host/fhci-hcd.c 518 */;
	unsigned long cocci_id/* drivers/usb/host/fhci-hcd.c 511 */;
	struct ed *cocci_id/* drivers/usb/host/fhci-hcd.c 510 */;
	struct usb_host_endpoint *cocci_id/* drivers/usb/host/fhci-hcd.c 507 */;
	struct usb_hcd *cocci_id/* drivers/usb/host/fhci-hcd.c 506 */;
	void cocci_id/* drivers/usb/host/fhci-hcd.c 506 */;
	struct urb_priv *cocci_id/* drivers/usb/host/fhci-hcd.c 481 */;
	struct urb *cocci_id/* drivers/usb/host/fhci-hcd.c 464 */;
	gfp_t cocci_id/* drivers/usb/host/fhci-hcd.c 385 */;
	struct fhci_hcd *cocci_id/* drivers/usb/host/fhci-hcd.c 303 */;
	void *cocci_id/* drivers/usb/host/fhci-hcd.c 241 */;
	u8 cocci_id/* drivers/usb/host/fhci-hcd.c 150 */;
}
