cocci_test_suite() {
	const struct timing_reg *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 997 */;
	u32 cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 994 */;
	u32 *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 992 */;
	struct exynos5_dmc *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 992 */;
	int cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 992 */;
	struct dmc_opp_table {
		u32 freq_hz;
		u32 volt_uv;
	} cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 99 */;
	struct devfreq_dev_profile cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 947 */;
	struct device *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 931 */;
	struct devfreq_dev_status *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 893 */;
	void cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 864 */;
	u64 cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 839 */;
	struct devfreq_event_data cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 691 */;
	unsigned long cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 690 */;
	unsigned long *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 687 */;
	struct dev_pm_opp *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 619 */;
	struct dmc_opp_table cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 311 */;
	struct devfreq_dev_profile *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 296 */;
	bool cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 273 */;
	const struct timing_reg cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 176 */[];
	struct timing_reg {
		char *name;
		int bit_beg;
		int bit_end;
		unsigned int val;
	} cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 160 */;
	struct platform_driver cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1539 */;
	const struct of_device_id cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1533 */[];
	int cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1378 */[2];
	struct resource *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1377 */;
	struct device_node *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1375 */;
	struct platform_device *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1371 */;
	irqreturn_t cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1343 */;
	void *cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1343 */;
	struct devfreq_event_dev cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1290 */;
	unsigned int cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 1208 */;
	struct exynos5_dmc {
		struct device *dev;
		struct devfreq *df;
		struct devfreq_simple_ondemand_data gov_data;
		void __iomem *base_drexi0;
		void __iomem *base_drexi1;
		struct regmap *clk_regmap;
		struct mutex lock;
		unsigned long curr_rate;
		unsigned long curr_volt;
		unsigned long bypass_rate;
		struct dmc_opp_table *opp;
		struct dmc_opp_table opp_bypass;
		int opp_count;
		u32 timings_arr_size;
		u32 *timing_row;
		u32 *timing_data;
		u32 *timing_power;
		const struct lpddr3_timings *timings;
		const struct lpddr3_min_tck *min_tck;
		u32 bypass_timing_row;
		u32 bypass_timing_data;
		u32 bypass_timing_power;
		struct regulator *vdd_mif;
		struct clk *fout_spll;
		struct clk *fout_bpll;
		struct clk *mout_spll;
		struct clk *mout_bpll;
		struct clk *mout_mclk_cdrex;
		struct clk *mout_mx_mspll_ccore;
		struct clk *mx_mspll_ccore_phy;
		struct clk *mout_mx_mspll_ccore_phy;
		struct devfreq_event_dev **counter;
		int num_counters;
		u64 last_overflow_ts[2];
		unsigned long load;
		unsigned long total;
		bool in_irq_mode;
	} cocci_id/* drivers/memory/samsung/exynos5422-dmc.c 110 */;
}
