cocci_test_suite() {
	void __exit cocci_id/* drivers/edac/skx_common.c 96 */;
	struct mem_ctl_info *cocci_id/* drivers/edac/skx_common.c 574 */;
	struct decoded_addr cocci_id/* drivers/edac/skx_common.c 573 */;
	struct mce *cocci_id/* drivers/edac/skx_common.c 572 */;
	void *cocci_id/* drivers/edac/skx_common.c 570 */;
	struct notifier_block *cocci_id/* drivers/edac/skx_common.c 569 */;
	unsigned long cocci_id/* drivers/edac/skx_common.c 569 */;
	enum hw_event_mc_err_type cocci_id/* drivers/edac/skx_common.c 480 */;
	const struct mce *cocci_id/* drivers/edac/skx_common.c 477 */;
	int __init cocci_id/* drivers/edac/skx_common.c 44 */;
	void cocci_id/* drivers/edac/skx_common.c 44 */;
	struct skx_pvt cocci_id/* drivers/edac/skx_common.c 409 */;
	struct skx_pvt *cocci_id/* drivers/edac/skx_common.c 398 */;
	struct edac_mc_layer cocci_id/* drivers/edac/skx_common.c 397 */[2];
	get_dimm_config_f cocci_id/* drivers/edac/skx_common.c 394 */;
	skx_decode_f cocci_id/* drivers/edac/skx_common.c 39 */;
	char cocci_id/* drivers/edac/skx_common.c 38 */[MSG_SIZE];
	char *cocci_id/* drivers/edac/skx_common.c 36 */;
	u64 *cocci_id/* drivers/edac/skx_common.c 35 */;
	u16 cocci_id/* drivers/edac/skx_common.c 349 */;
	const char *const *cocci_id/* drivers/edac/skx_common.c 34 */;
	int cocci_id/* drivers/edac/skx_common.c 33 */;
	int cocci_id/* drivers/edac/skx_common.c 32 */[ARRAY_SIZE(component_names)];
	u64 cocci_id/* drivers/edac/skx_common.c 311 */;
	struct skx_imc *cocci_id/* drivers/edac/skx_common.c 308 */;
	struct dimm_info *cocci_id/* drivers/edac/skx_common.c 307 */;
	const char *cocci_id/* drivers/edac/skx_common.c 292 */;
	int cocci_id/* drivers/edac/skx_common.c 252 */[];
	const char *const cocci_id/* drivers/edac/skx_common.c 25 */[];
	struct pci_dev *cocci_id/* drivers/edac/skx_common.c 207 */;
	struct list_head **cocci_id/* drivers/edac/skx_common.c 205 */;
	enum type cocci_id/* drivers/edac/skx_common.c 204 */;
	unsigned int cocci_id/* drivers/edac/skx_common.c 204 */;
	u32 cocci_id/* drivers/edac/skx_common.c 186 */;
	u8 *cocci_id/* drivers/edac/skx_common.c 173 */;
	skx_show_retry_log_f cocci_id/* drivers/edac/skx_common.c 154 */;
	struct skx_dev *cocci_id/* drivers/edac/skx_common.c 104 */;
	bool cocci_id/* drivers/edac/skx_common.c 102 */;
	struct decoded_addr *cocci_id/* drivers/edac/skx_common.c 102 */;
}
