cocci_test_suite() {
	const unsigned long cocci_id/* drivers/edac/edac_mc.c 970 */;
	const bool cocci_id/* drivers/edac/edac_mc.c 969 */;
	const char *cocci_id/* drivers/edac/edac_mc.c 964 */;
	const int cocci_id/* drivers/edac/edac_mc.c 963 */[EDAC_MAX_LAYERS];
	const u16 cocci_id/* drivers/edac/edac_mc.c 962 */;
	const char *cocci_id/* drivers/edac/edac_mc.c 902 */[];
	const struct kernel_param *cocci_id/* drivers/edac/edac_mc.c 88 */;
	struct csrow_info **cocci_id/* drivers/edac/edac_mc.c 863 */;
	struct page *cocci_id/* drivers/edac/edac_mc.c 832 */;
	u32 cocci_id/* drivers/edac/edac_mc.c 724 */;
	const struct attribute_group **cocci_id/* drivers/edac/edac_mc.c 709 */;
	struct delayed_work *cocci_id/* drivers/edac/edac_mc.c 578 */;
	struct work_struct *cocci_id/* drivers/edac/edac_mc.c 576 */;
	struct mem_ctl_info cocci_id/* drivers/edac/edac_mc.c 544 */;
	struct list_head *cocci_id/* drivers/edac/edac_mc.c 539 */;
	struct mem_ctl_info *cocci_id/* drivers/edac/edac_mc.c 536 */;
	struct device *cocci_id/* drivers/edac/edac_mc.c 536 */;
	bool cocci_id/* drivers/edac/edac_mc.c 521 */;
	u32 *cocci_id/* drivers/edac/edac_mc.c 379 */;
	unsigned int cocci_id/* drivers/edac/edac_mc.c 319 */[EDAC_MAX_LAYERS];
	struct rank_info *cocci_id/* drivers/edac/edac_mc.c 316 */;
	struct edac_mc_layer *cocci_id/* drivers/edac/edac_mc.c 310 */;
	int cocci_id/* drivers/edac/edac_mc.c 282 */;
	struct csrow_info *cocci_id/* drivers/edac/edac_mc.c 281 */;
	void cocci_id/* drivers/edac/edac_mc.c 279 */;
	unsigned long cocci_id/* drivers/edac/edac_mc.c 269 */;
	char *cocci_id/* drivers/edac/edac_mc.c 267 */;
	char cocci_id/* drivers/edac/edac_mc.c 264 */;
	short cocci_id/* drivers/edac/edac_mc.c 262 */;
	long long cocci_id/* drivers/edac/edac_mc.c 259 */;
	long cocci_id/* drivers/edac/edac_mc.c 258 */;
	void **cocci_id/* drivers/edac/edac_mc.c 242 */;
	void *cocci_id/* drivers/edac/edac_mc.c 242 */;
	unsigned int cocci_id/* drivers/edac/edac_mc.c 242 */;
	const char *const cocci_id/* drivers/edac/edac_mc.c 198 */[];
	char cocci_id/* drivers/edac/edac_mc.c 150 */[80];
	struct dimm_info *cocci_id/* drivers/edac/edac_mc.c 117 */;
	struct edac_raw_error_desc *cocci_id/* drivers/edac/edac_mc.c 1116 */;
	int cocci_id/* drivers/edac/edac_mc.c 1114 */[EDAC_MAX_LAYERS];
	const int cocci_id/* drivers/edac/edac_mc.c 1105 */;
	const struct kernel_param_ops cocci_id/* drivers/edac/edac_mc.c 110 */;
	const enum hw_event_mc_err_type cocci_id/* drivers/edac/edac_mc.c 1099 */;
	u8 cocci_id/* drivers/edac/edac_mc.c 1061 */;
}
