cocci_test_suite() {
	struct resource cocci_id/* drivers/soc/fsl/qe/qe.c 73 */;
	int cocci_id/* drivers/soc/fsl/qe/qe.c 72 */;
	struct device_node *cocci_id/* drivers/soc/fsl/qe/qe.c 71 */;
	phys_addr_t cocci_id/* drivers/soc/fsl/qe/qe.c 69 */;
	void cocci_id/* drivers/soc/fsl/qe/qe.c 69 */;
	struct platform_driver cocci_id/* drivers/soc/fsl/qe/qe.c 685 */;
	const struct of_device_id cocci_id/* drivers/soc/fsl/qe/qe.c 680 */[];
	struct platform_device *cocci_id/* drivers/soc/fsl/qe/qe.c 675 */;
	int __init cocci_id/* drivers/soc/fsl/qe/qe.c 654 */;
	const u64 *cocci_id/* drivers/soc/fsl/qe/qe.c 608 */;
	u64 cocci_id/* drivers/soc/fsl/qe/qe.c 607 */;
	struct property *cocci_id/* drivers/soc/fsl/qe/qe.c 568 */;
	struct qe_firmware_info *cocci_id/* drivers/soc/fsl/qe/qe.c 565 */;
	const struct qe_microcode *cocci_id/* drivers/soc/fsl/qe/qe.c 535 */;
	__be32 *cocci_id/* drivers/soc/fsl/qe/qe.c 502 */;
	void *cocci_id/* drivers/soc/fsl/qe/qe.c 502 */;
	__be32 cocci_id/* drivers/soc/fsl/qe/qe.c 492 */;
	u8 cocci_id/* drivers/soc/fsl/qe/qe.c 49 */[QE_NUM_OF_SNUM];
	struct qe_microcode cocci_id/* drivers/soc/fsl/qe/qe.c 484 */;
	struct qe_immap __iomem *cocci_id/* drivers/soc/fsl/qe/qe.c 46 */;
	const struct qe_header *cocci_id/* drivers/soc/fsl/qe/qe.c 454 */;
	struct qe_firmware cocci_id/* drivers/soc/fsl/qe/qe.c 452 */;
	size_t cocci_id/* drivers/soc/fsl/qe/qe.c 452 */;
	const struct qe_firmware *cocci_id/* drivers/soc/fsl/qe/qe.c 447 */;
	const __be32 *cocci_id/* drivers/soc/fsl/qe/qe.c 408 */;
	const void *cocci_id/* drivers/soc/fsl/qe/qe.c 405 */;
	struct qe_firmware_info cocci_id/* drivers/soc/fsl/qe/qe.c 391 */;
	int cocci_id/* drivers/soc/fsl/qe/qe.c 37 */(void);
	struct sdma __iomem *cocci_id/* drivers/soc/fsl/qe/qe.c 366 */;
	void cocci_id/* drivers/soc/fsl/qe/qe.c 36 */(void);
	const u8 *cocci_id/* drivers/soc/fsl/qe/qe.c 357 */;
	unsigned long cocci_id/* drivers/soc/fsl/qe/qe.c 339 */;
	const u8 cocci_id/* drivers/soc/fsl/qe/qe.c 282 */[];
	enum qe_clock cocci_id/* drivers/soc/fsl/qe/qe.c 244 */;
	const char *cocci_id/* drivers/soc/fsl/qe/qe.c 244 */;
	const u32 *cocci_id/* drivers/soc/fsl/qe/qe.c 168 */;
	unsigned int cocci_id/* drivers/soc/fsl/qe/qe.c 159 */;
	u8 cocci_id/* drivers/soc/fsl/qe/qe.c 107 */;
	u32 cocci_id/* drivers/soc/fsl/qe/qe.c 107 */;
}
