cocci_test_suite() {
	struct ms_bootblock_sysinf *cocci_id/* drivers/usb/storage/ene_ub6250.c 937 */;
	struct ms_bootblock_sysent *cocci_id/* drivers/usb/storage/ene_ub6250.c 936 */;
	unsigned char cocci_id/* drivers/usb/storage/ene_ub6250.c 591 */[36];
	struct us_data *cocci_id/* drivers/usb/storage/ene_ub6250.c 589 */;
	struct scsi_cmnd *cocci_id/* drivers/usb/storage/ene_ub6250.c 589 */;
	int cocci_id/* drivers/usb/storage/ene_ub6250.c 589 */;
	unsigned char cocci_id/* drivers/usb/storage/ene_ub6250.c 576 */[18];
	struct ene_ub6250_info *cocci_id/* drivers/usb/storage/ene_ub6250.c 575 */;
	unsigned int cocci_id/* drivers/usb/storage/ene_ub6250.c 499 */;
	struct bulk_cs_wrap *cocci_id/* drivers/usb/storage/ene_ub6250.c 496 */;
	void cocci_id/* drivers/usb/storage/ene_ub6250.c 484 */;
	int cocci_id/* drivers/usb/storage/ene_ub6250.c 482 */(struct us_data *us,
							       unsigned char flag);
	int cocci_id/* drivers/usb/storage/ene_ub6250.c 481 */(struct us_data *us);
	struct ene_ub6250_info {
		u8 *bbuf;
		struct SD_STATUS SD_Status;
		struct MS_STATUS MS_Status;
		struct SM_STATUS SM_Status;
		u16 SD_Block_Mult;
		u8 SD_READ_BL_LEN;
		u16 SD_C_SIZE;
		u8 SD_C_SIZE_MULT;
		u8 SD_SPEC_VER;
		u8 SD_CSD_VER;
		u8 SD20_HIGH_CAPACITY;
		u32 HC_C_SIZE;
		u8 MMC_SPEC_VER;
		u8 MMC_BusWidth;
		u8 MMC_HIGH_CAPACITY;
		bool MS_SWWP;
		u32 MSP_TotalBlock;
		struct ms_lib_ctrl MS_Lib;
		bool MS_IsRWPage;
		u16 MS_Model;
		u8 SM_DeviceID;
		u8 SM_CardID;
		unsigned char *testbuf;
		u8 BIN_FLAG;
		u32 bl_num;
		int SrbStatus;
		bool Power_IsResum;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 434 */;
	struct ms_lib_ctrl {
		u32 flags;
		u32 BytesPerSector;
		u32 NumberOfCylinder;
		u32 SectorsPerCylinder;
		u16 cardType;
		u16 blockSize;
		u16 PagesPerBlock;
		u16 NumberOfPhyBlock;
		u16 NumberOfLogBlock;
		u16 NumberOfSegment;
		u16 *Phy2LogMap;
		u16 *Log2PhyMap;
		u16 wrtblk;
		unsigned char *pagemap[(MS_MAX_PAGES_PER_BLOCK + (MS_LIB_BITS_PER_BYTE - 1)) / MS_LIB_BITS_PER_BYTE];
		unsigned char *blkpag;
		struct ms_lib_type_extdat *blkext;
		unsigned char copybuf[512];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 409 */;
	struct ms_lib_type_extdat {
		u8 reserved;
		u8 intr;
		u8 status0;
		u8 status1;
		u8 ovrflg;
		u8 mngflg;
		u16 logadr;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 399 */;
	struct ms_bootblock_cis_idi {
		union {
			struct ms_bootblock_cis cis;
			u8 dmy[256];
		} cis;
		union {
			struct ms_bootblock_idi idi;
			u8 dmy[256];
		} idi;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 385 */;
	struct ms_bootblock_page0 {
		struct ms_bootblock_header header;
		struct ms_bootblock_sysent sysent;
		struct ms_bootblock_sysinf sysinf;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 379 */;
	struct ms_bootblock_header {
		u16 wBlockID;
		u16 wFormatVersion;
		u8 bReserved1[184];
		u8 bNumberOfDataEntry;
		u8 bReserved2[179];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 371 */;
	struct ms_bootblock_sysinf {
		u8 bMsClass;
		u8 bCardType;
		u16 wBlockSize;
		u16 wBlockNumber;
		u16 wTotalBlockNumber;
		u16 wPageSize;
		u8 bExtraSize;
		u8 bSecuritySupport;
		u8 bAssemblyDate[8];
		u8 bFactoryArea[4];
		u8 bAssemblyMakerCode;
		u8 bAssemblyMachineCode[3];
		u16 wMemoryMakerCode;
		u16 wMemoryDeviceCode;
		u16 wMemorySize;
		u8 bReserved1;
		u8 bReserved2;
		u8 bVCC;
		u8 bVPP;
		u16 wControllerChipNumber;
		u16 wControllerFunction;
		u8 bReserved3[9];
		u8 bParallelSupport;
		u16 wFormatValue;
		u8 bFormatType;
		u8 bUsage;
		u8 bDeviceType;
		u8 bReserved4[22];
		u8 bFUValue3;
		u8 bFUValue4;
		u8 bReserved5[15];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 337 */;
	struct ms_bootblock_sysent {
		struct ms_bootblock_sysent_rec entry[MS_NUMBER_OF_SYSTEM_ENTRY];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 333 */;
	struct ms_bootblock_sysent_rec {
		u32 dwStart;
		u32 dwSize;
		u8 bType;
		u8 bReserved[3];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 326 */;
	struct ms_bootblock_idi {
#define MS_IDI_GENERAL_CONF 0x848A
		u16 wIDIgeneralConfiguration;
		u16 wIDInumberOfCylinder;
		u16 wIDIreserved0;
		u16 wIDInumberOfHead;
		u16 wIDIbytesPerTrack;
		u16 wIDIbytesPerSector;
		u16 wIDIsectorsPerTrack;
		u16 wIDItotalSectors[2];
		u16 wIDIreserved1[11];
		u16 wIDIbufferType;
		u16 wIDIbufferSize;
		u16 wIDIlongCmdECC;
		u16 wIDIfirmVersion[4];
		u16 wIDImodelName[20];
		u16 wIDIreserved2;
		u16 wIDIlongWordSupported;
		u16 wIDIdmaSupported;
		u16 wIDIreserved3;
		u16 wIDIpioTiming;
		u16 wIDIdmaTiming;
		u16 wIDItransferParameter;
		u16 wIDIformattedCylinder;
		u16 wIDIformattedHead;
		u16 wIDIformattedSectorsPerTrack;
		u16 wIDIformattedTotalSectors[2];
		u16 wIDImultiSector;
		u16 wIDIlbaSectors[2];
		u16 wIDIsingleWordDMA;
		u16 wIDImultiWordDMA;
		u16 wIDIreserved4[192];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 292 */;
	struct ms_bootblock_cis {
		u8 bCistplDEVICE[6];
		u8 bCistplDEVICE0C[6];
		u8 bCistplJEDECC[4];
		u8 bCistplMANFID[6];
		u8 bCistplVER1[32];
		u8 bCistplFUNCID[4];
		u8 bCistplFUNCE0[4];
		u8 bCistplFUNCE1[5];
		u8 bCistplCONF[7];
		u8 bCistplCFTBLENT0[10];
		u8 bCistplCFTBLENT1[8];
		u8 bCistplCFTBLENT2[12];
		u8 bCistplCFTBLENT3[8];
		u8 bCistplCFTBLENT4[17];
		u8 bCistplCFTBLENT5[8];
		u8 bCistplCFTBLENT6[17];
		u8 bCistplCFTBLENT7[8];
		u8 bCistplNOLINK[3];
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 271 */;
	struct SM_STATUS {
		u8 Insert:1;
		u8 Ready:1;
		u8 MediaChange:1;
		u8 Reserved:3;
		u8 WtP:1;
		u8 IsMS:1;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 262 */;
	struct MS_STATUS {
		u8 Insert:1;
		u8 Ready:1;
		u8 MediaChange:1;
		u8 IsMSPro:1;
		u8 IsMSPHG:1;
		u8 Reserved1:1;
		u8 WtP:1;
		u8 Reserved2:1;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 251 */;
	struct usb_driver cocci_id/* drivers/usb/storage/ene_ub6250.c 2429 */;
	struct SM_STATUS *cocci_id/* drivers/usb/storage/ene_ub6250.c 2417 */;
	struct SD_STATUS {
		u8 Insert:1;
		u8 Ready:1;
		u8 MediaChange:1;
		u8 IsMMC:1;
		u8 HiCapacity:1;
		u8 HiSpeed:1;
		u8 WtP:1;
		u8 Reserved:1;
	} cocci_id/* drivers/usb/storage/ene_ub6250.c 240 */;
	struct ene_ub6250_info cocci_id/* drivers/usb/storage/ene_ub6250.c 2339 */;
	const struct usb_device_id *cocci_id/* drivers/usb/storage/ene_ub6250.c 2325 */;
	struct usb_interface *cocci_id/* drivers/usb/storage/ene_ub6250.c 2324 */;
	struct scsi_host_template cocci_id/* drivers/usb/storage/ene_ub6250.c 2322 */;
	struct SD_STATUS *cocci_id/* drivers/usb/storage/ene_ub6250.c 2171 */;
	struct MS_STATUS *cocci_id/* drivers/usb/storage/ene_ub6250.c 2102 */;
	struct ms_bootblock_page0 *cocci_id/* drivers/usb/storage/ene_ub6250.c 1991 */;
	struct ms_lib_type_extdat cocci_id/* drivers/usb/storage/ene_ub6250.c 1955 */;
	const struct firmware *cocci_id/* drivers/usb/storage/ene_ub6250.c 1884 */;
	unsigned char *cocci_id/* drivers/usb/storage/ene_ub6250.c 1883 */;
	char *cocci_id/* drivers/usb/storage/ene_ub6250.c 1882 */;
	u8 cocci_id/* drivers/usb/storage/ene_ub6250.c 1857 */;
	u32 *cocci_id/* drivers/usb/storage/ene_ub6250.c 1856 */;
	u32 cocci_id/* drivers/usb/storage/ene_ub6250.c 1852 */;
	u16 cocci_id/* drivers/usb/storage/ene_ub6250.c 1851 */;
	u8 *cocci_id/* drivers/usb/storage/ene_ub6250.c 1849 */;
	unsigned char cocci_id/* drivers/usb/storage/ene_ub6250.c 1842 */;
	struct bulk_cb_wrap cocci_id/* drivers/usb/storage/ene_ub6250.c 1837 */;
	struct bulk_cb_wrap *cocci_id/* drivers/usb/storage/ene_ub6250.c 1834 */;
	void *cocci_id/* drivers/usb/storage/ene_ub6250.c 1832 */;
	u16 *cocci_id/* drivers/usb/storage/ene_ub6250.c 1521 */;
	struct scatterlist *cocci_id/* drivers/usb/storage/ene_ub6250.c 1492 */;
	unsigned char cocci_id/* drivers/usb/storage/ene_ub6250.c 1491 */[8];
	unsigned char cocci_id/* drivers/usb/storage/ene_ub6250.c 1471 */[12];
	struct ms_lib_type_extdat *cocci_id/* drivers/usb/storage/ene_ub6250.c 1350 */;
	struct ms_bootblock_cis_idi *cocci_id/* drivers/usb/storage/ene_ub6250.c 1051 */;
	struct ms_bootblock_idi *cocci_id/* drivers/usb/storage/ene_ub6250.c 1036 */;
}
