cocci_test_suite() {
	struct v4l2_ext_control cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 956 */;
	struct v4l2_control *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 952 */;
	struct v4l2_query_ext_ctrl *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 923 */;
	struct v4l2_queryctrl *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 914 */;
	u8 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 868 */;
	unsigned int *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 863 */;
	struct uvc_entity *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 828 */;
	const struct uvc_entity *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 827 */;
	struct v4l2_input *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 823 */;
	struct uvc_streaming *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 779 */;
	struct v4l2_create_buffers *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 776 */;
	struct file *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 775 */;
	void *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 775 */;
	struct v4l2_buffer *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 763 */;
	struct v4l2_exportbuffer *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 752 */;
	struct v4l2_requestbuffers *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 705 */;
	struct uvc_streaming_control cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 689 */;
	struct v4l2_format *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 639 */;
	u32 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 601 */;
	enum v4l2_buf_type cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 600 */;
	struct uvc_format *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 599 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 597 */;
	struct video_device *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 582 */;
	struct v4l2_capability *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 580 */;
	void cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 491 */;
	struct uvc_fh *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 475 */;
	int cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 475 */;
	s32 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 399 */;
	struct v4l2_fract cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 368 */;
	unsigned int cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 35 */;
	struct uvc_control_mapping *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 34 */;
	struct uvc_xu_control_mapping *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 32 */;
	struct uvc_video_chain *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 31 */;
	u8 *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 161 */;
	u16 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 156 */;
	struct uvc_frame **cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 152 */;
	struct uvc_format **cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 152 */;
	struct uvc_streaming_control *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 151 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1507 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1468 */;
	__poll_t cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1444 */;
	poll_table *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1444 */;
	struct vm_area_struct *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1434 */;
	loff_t *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1428 */;
	size_t cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1428 */;
	char __user *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1427 */;
	ssize_t cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1427 */;
	void __user *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1390 */;
	union {
		struct uvc_xu_control_mapping xmap;
		struct uvc_xu_control_query xqry;
	} cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1386 */;
	unsigned long cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1383 */;
	struct uvc_xu_control_query32 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1380 */;
	struct uvc_xu_control_mapping32 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1379 */;
	struct uvc_xu_control_query32 __user *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1372 */;
	const struct uvc_xu_control_query *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1371 */;
	struct uvc_xu_control_query cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1361 */;
	const struct uvc_frame *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 136 */;
	const struct uvc_xu_control_query32 __user *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1354 */;
	struct uvc_xu_control_query *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1353 */;
	const struct uvc_format *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 135 */;
	struct uvc_xu_control_query32 {
		u8 unit;
		u8 selector;
		u8 query;
		u16 size;
		compat_caddr_t data;
	} cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1345 */;
	typeof(*up) cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1335 */;
	struct uvc_xu_control_mapping32 __user *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1333 */;
	const struct uvc_xu_control_mapping *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1332 */;
	compat_caddr_t cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1317 */;
	struct uvc_xu_control_mapping32 *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1316 */;
	const struct uvc_xu_control_mapping32 __user *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1314 */;
	struct uvc_xu_control_mapping32 {
		u32 id;
		u8 name[32];
		u8 entity[16];
		u8 selector;
		u8 size;
		u8 offset;
		u32 v4l2_type;
		u32 data_type;
		compat_caddr_t menu_info;
		u32 menu_count;
		u32 reserved[4];
	} cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1296 */;
	bool cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1276 */;
	long cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1276 */;
	const struct v4l2_event_subscription *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1266 */;
	struct v4l2_fh *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1265 */;
	const u32 cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 123 */;
	struct uvc_frame *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1210 */;
	struct v4l2_frmivalenum *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1205 */;
	struct v4l2_frmsizeenum *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1165 */;
	struct v4l2_streamparm *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1142 */;
	struct v4l2_selection *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1108 */;
	struct v4l2_querymenu *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1099 */;
	struct v4l2_queryctrl cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1016 */;
	struct v4l2_ext_control *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1010 */;
	struct v4l2_ext_controls *cocci_id/* drivers/media/usb/uvc/uvc_v4l2.c 1006 */;
}
