cocci_test_suite() {
	struct i2c_msg cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 712 */[2];
	struct dvb_usb_adapter *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 706 */;
	struct i2c_board_info cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 627 */;
	struct i2c_adapter *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 626 */;
	struct i2c_client *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 625 */;
	struct anysee_state *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 624 */;
	u8 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 621 */;
	void *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 621 */;
	const char *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 620 */;
	struct dvb_usb_device *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 620 */;
	int cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 620 */;
	struct dvb_frontend *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 525 */;
	u8 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 493 */[3];
	u8 *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 37 */;
	struct cxd2820r_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 368 */;
	struct isl6423_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 361 */;
	struct stv6110_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 355 */;
	struct stv0900_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 344 */;
	struct cx24116_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 338 */;
	struct tda18212_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 321 */;
	struct zl10353_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 290 */;
	struct mt352_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 285 */;
	struct tda10023_config cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 274 */;
	struct i2c_algorithm cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 247 */;
	u32 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 242 */;
	u8 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 198 */[52];
	struct i2c_msg *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 193 */;
	u16 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 142 */;
	struct usb_driver cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1413 */;
	const struct usb_device_id cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1404 */[];
	struct anysee_state cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1381 */;
	struct dvb_usb_device_properties cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1377 */;
	void cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1322 */;
	struct dvb_ca_en50221 *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1264 */;
	u8 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1160 */[];
	struct dvb_usb_rc *cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1143 */;
	u8 cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1118 */[2];
	struct dvb_tuner_ops cocci_id/* drivers/media/usb/dvb-usb-v2/anysee.c 1031 */;
}
