cocci_test_suite() {
	u16 cocci_id/* drivers/usb/typec/tcpm/tcpm.c 971 */;
	bool cocci_id/* drivers/usb/typec/tcpm/tcpm.c 963 */;
	u32 cocci_id/* drivers/usb/typec/tcpm/tcpm.c 947 */;
	const __le32 *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 944 */;
	const u32 cocci_id/* drivers/usb/typec/tcpm/tcpm.c 933 */;
	enum pd_msg_request cocci_id/* drivers/usb/typec/tcpm/tcpm.c 924 */;
	enum typec_cc_polarity cocci_id/* drivers/usb/typec/tcpm/tcpm.c 670 */;
	enum typec_orientation cocci_id/* drivers/usb/typec/tcpm/tcpm.c 649 */;
	enum usb_role cocci_id/* drivers/usb/typec/tcpm/tcpm.c 648 */;
	enum tcpm_transmit_status cocci_id/* drivers/usb/typec/tcpm/tcpm.c 639 */;
	enum tcpm_transmit_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 603 */;
	const struct tcpm_port *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 598 */;
	char cocci_id/* drivers/usb/typec/tcpm/tcpm.c 568 */[NAME_MAX];
	struct seq_file *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 547 */;
	void *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 547 */;
	char cocci_id/* drivers/usb/typec/tcpm/tcpm.c 493 */[64];
	struct tcpc_dev *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4668 */;
	struct device *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4668 */;
	char *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4640 */;
	size_t cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4638 */;
	struct power_supply_config cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4636 */;
	int cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4634 */;
	enum power_supply_usb_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4626 */[];
	const union power_supply_propval *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4562 */;
	enum power_supply_property cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4525 */;
	struct power_supply *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4524 */;
	union power_supply_propval *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4506 */;
	enum power_supply_property cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4450 */[];
	enum tcpm_psy_online_states{TCPM_PSY_OFFLINE=0, TCPM_PSY_FIXED_ONLINE, TCPM_PSY_PROG_ONLINE,} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4444 */;
	struct fwnode_handle *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4367 */;
	const struct typec_operations cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4349 */;
	enum typec_port_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4322 */;
	unsigned long cocci_id/* drivers/usb/typec/tcpm/tcpm.c 417 */;
	u64 cocci_id/* drivers/usb/typec/tcpm/tcpm.c 416 */;
	char cocci_id/* drivers/usb/typec/tcpm/tcpm.c 415 */[LOG_BUFFER_ENTRY_SIZE];
	va_list cocci_id/* drivers/usb/typec/tcpm/tcpm.c 413 */;
	const char *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 413 */;
	enum typec_role cocci_id/* drivers/usb/typec/tcpm/tcpm.c 4031 */;
	enum typec_data_role cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3964 */;
	struct typec_port *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3964 */;
	struct tcpm_port cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3903 */;
	struct work_struct *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3901 */;
	enum tcpm_state cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3613 */;
	enum typec_cc_status cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3609 */;
	struct tcpm_port *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3609 */;
	void cocci_id/* drivers/usb/typec/tcpm/tcpm.c 3609 */;
	struct pd_rx_event {
		struct work_struct work;
		struct tcpm_port *port;
		struct pd_message msg;
	} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 334 */;
	unsigned int cocci_id/* drivers/usb/typec/tcpm/tcpm.c 2850 */;
	enum typec_pwr_opmode cocci_id/* drivers/usb/typec/tcpm/tcpm.c 2849 */;
	u32 *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 2419 */;
	int *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 2122 */;
	struct pd_message cocci_id/* drivers/usb/typec/tcpm/tcpm.c 2006 */;
	struct pd_rx_event *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1990 */;
	struct tcpm_port {
		struct device *dev;
		struct mutex lock;
		struct workqueue_struct *wq;
		struct typec_capability typec_caps;
		struct typec_port *typec_port;
		struct tcpc_dev *tcpc;
		struct usb_role_switch *role_sw;
		enum typec_role vconn_role;
		enum typec_role pwr_role;
		enum typec_data_role data_role;
		enum typec_pwr_opmode pwr_opmode;
		struct usb_pd_identity partner_ident;
		struct typec_partner_desc partner_desc;
		struct typec_partner *partner;
		enum typec_cc_status cc_req;
		enum typec_cc_status cc1;
		enum typec_cc_status cc2;
		enum typec_cc_polarity polarity;
		bool attached;
		bool connected;
		enum typec_port_type port_type;
		bool vbus_present;
		bool vbus_never_low;
		bool vbus_source;
		bool vbus_charge;
		bool send_discover;
		bool op_vsafe5v;
		int try_role;
		int try_snk_count;
		int try_src_count;
		enum pd_msg_request queued_message;
		enum tcpm_state enter_state;
		enum tcpm_state prev_state;
		enum tcpm_state state;
		enum tcpm_state delayed_state;
		unsigned long delayed_runtime;
		unsigned long delay_ms;
		spinlock_t pd_event_lock;
		u32 pd_events;
		struct work_struct event_work;
		struct delayed_work state_machine;
		struct delayed_work vdm_state_machine;
		bool state_machine_running;
		struct completion tx_complete;
		enum tcpm_transmit_status tx_status;
		struct mutex swap_lock;
		bool swap_pending;
		bool non_pd_role_swap;
		struct completion swap_complete;
		int swap_status;
		unsigned int negotiated_rev;
		unsigned int message_id;
		unsigned int caps_count;
		unsigned int hard_reset_count;
		bool pd_capable;
		bool explicit_contract;
		unsigned int rx_msgid;
		u32 sink_request;
		u32 source_caps[PDO_MAX_OBJECTS];
		unsigned int nr_source_caps;
		u32 sink_caps[PDO_MAX_OBJECTS];
		unsigned int nr_sink_caps;
		u32 src_pdo[PDO_MAX_OBJECTS];
		unsigned int nr_src_pdo;
		u32 snk_pdo[PDO_MAX_OBJECTS];
		unsigned int nr_snk_pdo;
		u32 snk_vdo[VDO_MAX_OBJECTS];
		unsigned int nr_snk_vdo;
		unsigned int operating_snk_mw;
		bool update_sink_caps;
		u32 current_limit;
		u32 supply_voltage;
		struct power_supply *psy;
		struct power_supply_desc psy_desc;
		enum power_supply_usb_type usb_type;
		u32 bist_request;
		enum vdm_states vdm_state;
		u32 vdm_retries;
		u32 vdo_data[VDO_MAX_SIZE];
		u8 vdo_count;
		u32 vdo_retry;
		struct pd_pps_data pps_data;
		struct completion pps_complete;
		bool pps_pending;
		int pps_status;
		struct pd_mode_data mode_data;
		struct typec_altmode *partner_altmode[ALTMODE_DISCOVERY_MAX];
		struct typec_altmode *port_altmode[ALTMODE_DISCOVERY_MAX];
		unsigned long max_wait;
		bool self_powered;
#ifdef CONFIG_DEBUG_FS
		struct dentry *dentry;
		struct mutex logbuffer_lock;
		int logbuffer_head;
		int logbuffer_tail;
		u8 *logbuffer[LOG_BUFFER_ENTRIES];
#endif
	} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 194 */;
	struct pd_rx_event cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1937 */;
	enum pd_ext_msg_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1882 */;
	struct pd_pps_data {
		u32 min_volt;
		u32 max_volt;
		u32 max_curr;
		u32 out_volt;
		u32 op_curr;
		bool supported;
		bool active;
	} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 184 */;
	struct pd_mode_data {
		int svid_index;
		int nsvids;
		u16 svids[SVID_DISCOVERY_MAX];
		int altmodes;
		struct typec_altmode_desc altmode_desc[ALTMODE_DISCOVERY_MAX];
	} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 176 */;
	enum pd_ctrl_msg_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1681 */;
	const struct pd_message *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1679 */;
	enum pd_data_msg_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1571 */;
	int cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1540 */(struct tcpm_port *port,
							     enum pd_ctrl_msg_type type);
	enum pd_msg_request{PD_MSG_NONE=0, PD_MSG_CTRL_REJECT, PD_MSG_CTRL_WAIT, PD_MSG_CTRL_NOT_SUPP, PD_MSG_DATA_SINK_CAP, PD_MSG_DATA_SOURCE_CAP,} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 153 */;
	const struct typec_altmode_ops cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1523 */;
	const u32 *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1511 */;
	struct typec_altmode *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1478 */;
	enum vdm_states{VDM_STATE_ERR_BUSY=-3, VDM_STATE_ERR_SEND=-2, VDM_STATE_ERR_TMOUT=-1, VDM_STATE_DONE=0, VDM_STATE_READY=1, VDM_STATE_BUSY=2, VDM_STATE_WAIT_RSP_BUSY=3,} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 142 */;
	enum pd_pdo_type cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1407 */;
	enum pdo_err cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1389 */;
	const char *constcocci_id/* drivers/usb/typec/tcpm/tcpm.c 1370 */[];
	enum pdo_err{PDO_NO_ERR, PDO_ERR_NO_VSAFE5V, PDO_ERR_VSAFE5V_NOT_FIRST, PDO_ERR_PDO_TYPE_NOT_IN_ORDER, PDO_ERR_FIXED_NOT_SORTED, PDO_ERR_VARIABLE_BATT_NOT_SORTED, PDO_ERR_DUPE_PDO, PDO_ERR_PPS_APDO_NOT_SORTED, PDO_ERR_DUPE_PPS_APDO,} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1358 */;
	enum vdm_states cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1341 */;
	enum tcpm_state{INVALID_STATE, TOGGLING, SRC_UNATTACHED, SRC_ATTACH_WAIT, SRC_ATTACHED, SRC_STARTUP, SRC_SEND_CAPABILITIES, SRC_SEND_CAPABILITIES_TIMEOUT, SRC_NEGOTIATE_CAPABILITIES, SRC_TRANSITION_SUPPLY, SRC_READY, SRC_WAIT_NEW_CAPABILITIES, SNK_UNATTACHED, SNK_ATTACH_WAIT, SNK_DEBOUNCED, SNK_ATTACHED, SNK_STARTUP, SNK_DISCOVERY, SNK_DISCOVERY_DEBOUNCE, SNK_DISCOVERY_DEBOUNCE_DONE, SNK_WAIT_CAPABILITIES, SNK_NEGOTIATE_CAPABILITIES, SNK_NEGOTIATE_PPS_CAPABILITIES, SNK_TRANSITION_SINK, SNK_TRANSITION_SINK_VBUS, SNK_READY, ACC_UNATTACHED, DEBUG_ACC_ATTACHED, AUDIO_ACC_ATTACHED, AUDIO_ACC_DEBOUNCE, HARD_RESET_SEND, HARD_RESET_START, SRC_HARD_RESET_VBUS_OFF, SRC_HARD_RESET_VBUS_ON, SNK_HARD_RESET_SINK_OFF, SNK_HARD_RESET_WAIT_VBUS, SNK_HARD_RESET_SINK_ON, SOFT_RESET, SOFT_RESET_SEND, DR_SWAP_ACCEPT, DR_SWAP_SEND, DR_SWAP_SEND_TIMEOUT, DR_SWAP_CANCEL, DR_SWAP_CHANGE_DR, PR_SWAP_ACCEPT, PR_SWAP_SEND, PR_SWAP_SEND_TIMEOUT, PR_SWAP_CANCEL, PR_SWAP_START, PR_SWAP_SRC_SNK_TRANSITION_OFF, PR_SWAP_SRC_SNK_SOURCE_OFF, PR_SWAP_SRC_SNK_SOURCE_OFF_CC_DEBOUNCED, PR_SWAP_SRC_SNK_SINK_ON, PR_SWAP_SNK_SRC_SINK_OFF, PR_SWAP_SNK_SRC_SOURCE_ON, PR_SWAP_SNK_SRC_SOURCE_ON_VBUS_RAMPED_UP, VCONN_SWAP_ACCEPT, VCONN_SWAP_SEND, VCONN_SWAP_SEND_TIMEOUT, VCONN_SWAP_CANCEL, VCONN_SWAP_START, VCONN_SWAP_WAIT_FOR_VCONN, VCONN_SWAP_TURN_ON_VCONN, VCONN_SWAP_TURN_OFF_VCONN, SNK_TRY, SNK_TRY_WAIT, SNK_TRY_WAIT_DEBOUNCE, SNK_TRY_WAIT_DEBOUNCE_CHECK_VBUS, SRC_TRYWAIT, SRC_TRYWAIT_DEBOUNCE, SRC_TRYWAIT_UNATTACHED, SRC_TRY, SRC_TRY_WAIT, SRC_TRY_DEBOUNCE, SNK_TRYWAIT, SNK_TRYWAIT_DEBOUNCE, SNK_TRYWAIT_VBUS, BIST_RX, GET_STATUS_SEND, GET_STATUS_SEND_TIMEOUT, GET_PPS_STATUS_SEND, GET_PPS_STATUS_SEND_TIMEOUT, ERROR_RECOVERY, PORT_RESET, PORT_RESET_WAIT_OFF,} cocci_id/* drivers/usb/typec/tcpm/tcpm.c 134 */;
	u32 cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1202 */[8];
	u32 cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1051 */[PD_MAX_PAYLOAD];
	struct typec_altmode_desc *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1003 */;
	struct pd_mode_data *cocci_id/* drivers/usb/typec/tcpm/tcpm.c 1002 */;
}
