cocci_test_suite() {
	struct vicodec_dev_instance {
		struct video_device vfd;
		struct mutex mutex;
		spinlock_t lock;
		struct v4l2_m2m_dev *m2m_dev;
	} cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 97 */;
	enum{V4L2_M2M_SRC=0, V4L2_M2M_DST=1,} cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 92 */;
	struct v4l2_plane_pix_format *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 845 */;
	struct vicodec_q_data {
		unsigned int coded_width;
		unsigned int coded_height;
		unsigned int visible_width;
		unsigned int visible_height;
		unsigned int sizeimage;
		unsigned int vb2_sizeimage;
		unsigned int sequence;
		const struct v4l2_fwht_pixfmt_info *info;
	} cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 81 */;
	struct v4l2_pix_format *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 773 */;
	struct v4l2_pix_format_mplane *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 772 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 768 */;
	struct platform_device cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 75 */;
	bool cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 715 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 714 */;
	struct device *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 71 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 705 */;
	const struct v4l2_event cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 673 */;
	struct fwht_cframe_hdr *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 651 */;
	const struct v4l2_fwht_pixfmt_info cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 63 */;
	const struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 556 */;
	struct pixfmt_info {
		u32 id;
		unsigned int bytesperline_mult;
		unsigned int sizeimage_mult;
		unsigned int sizeimage_div;
		unsigned int luma_step;
		unsigned int chroma_step;
		unsigned int width_div;
		unsigned int height_div;
	} cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 51 */;
	const struct fwht_cframe_hdr *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 485 */;
	u32 cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 415 */;
	void *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 409 */;
	struct fwht_cframe_hdr cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 394 */;
	const u8 cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 353 */[];
	u8 **cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 351 */;
	enum vb2_buffer_state cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 350 */;
	struct vicodec_q_data *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 315 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 289 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 287 */;
	struct media_request *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 273 */;
	struct vicodec_dev *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 262 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 259 */;
	struct vicodec_ctx *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 258 */;
	int __init cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2280 */;
	void __exit cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2274 */;
	struct platform_driver cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2266 */;
	struct platform_device *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2148 */;
	struct vicodec_dev cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2136 */;
	struct v4l2_device *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2134 */;
	struct video_device *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2096 */;
	const char *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2094 */;
	struct vicodec_dev_instance *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2093 */;
	const struct v4l2_m2m_ops cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2087 */;
	const struct media_device_ops cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2082 */;
	const struct video_device cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2073 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2064 */;
	struct vb2_buffer cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2023 */;
	struct v4l2_ctrl *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2016 */;
	struct media_request_object *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 2013 */;
	struct v4l2_ctrl_handler *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1889 */;
	struct v4l2_ctrl_fwht_params cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1877 */;
	const struct v4l2_ctrl_config cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1874 */;
	const struct v4l2_ctrl_ops cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1869 */;
	const struct v4l2_ctrl_fwht_params *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1828 */;
	struct v4l2_m2m_buffer cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1768 */;
	const struct vb2_ops cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1745 */;
	unsigned int cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 174 */;
	u8 *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 173 */;
	int cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 172 */;
	struct v4l2_fwht_state *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 170 */;
	const u8 *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 169 */;
	const struct v4l2_fwht_pixfmt_info *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 169 */;
	void cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 169 */;
	enum v4l2_buf_type cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 154 */;
	struct vicodec_ctx cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 150 */;
	struct file *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 148 */;
	long cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1459 */;
	struct device *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1413 */[];
	unsigned int cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1412 */[];
	unsigned int *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1411 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1361 */;
	const struct v4l2_event_subscription *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1343 */;
	struct v4l2_fh *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1342 */;
	struct v4l2_frmsizeenum *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1314 */;
	struct v4l2_decoder_cmd *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1286 */;
	struct v4l2_encoder_cmd *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1258 */;
	struct vicodec_ctx {
		struct v4l2_fh fh;
		struct vicodec_dev *dev;
		bool is_enc;
		bool is_stateless;
		bool is_draining;
		bool next_is_last;
		bool has_stopped;
		spinlock_t *lock;
		struct v4l2_ctrl_handler hdl;
		struct vb2_v4l2_buffer *last_src_buf;
		struct vicodec_q_data q_data[2];
		struct v4l2_fwht_state state;
		u32 cur_buf_offset;
		u32 comp_max_size;
		u32 comp_size;
		u32 header_size;
		u32 comp_magic_cnt;
		bool comp_has_frame;
		bool comp_has_next_frame;
		bool first_source_change_sent;
		bool source_changed;
	} cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 115 */;
	struct v4l2_selection *cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 1147 */;
	struct vicodec_dev {
		struct v4l2_device v4l2_dev;
		struct vicodec_dev_instance stateful_enc;
		struct vicodec_dev_instance stateful_dec;
		struct vicodec_dev_instance stateless_dec;
#ifdef CONFIG_MEDIA_CONTROLLER
		struct media_device mdev;
#endif
	} cocci_id/* drivers/media/platform/vicodec/vicodec-core.c 104 */;
}
