cocci_test_suite() {
	const struct rvin_group_route cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 947 */[];
	const struct rvin_info cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 940 */;
	struct v4l2_async_subdev cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 866 */;
	struct v4l2_fwnode_endpoint *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 796 */;
	struct device *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 795 */;
	const struct v4l2_async_notifier_operations cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 789 */;
	struct v4l2_async_subdev *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 769 */;
	struct v4l2_async_notifier *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 767 */;
	const struct rvin_group_route *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 71 */;
	unsigned char cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 69 */;
	enum rvin_csi_id cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 68 */;
	struct rvin_parallel_entity cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 651 */;
	struct rvin_parallel_entity *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 618 */;
	struct media_entity *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 53 */;
	struct v4l2_subdev_mbus_code_enum cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 440 */;
	unsigned int cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 420 */;
	struct v4l2_subdev *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 418 */;
	const struct v4l2_ctrl_ops cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 410 */;
	struct v4l2_ctrl *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 396 */;
	u32 cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 307 */;
	struct kref *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 288 */;
	struct device_node *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 255 */;
	const struct of_device_id *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 254 */;
	struct media_device *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 253 */;
	struct rvin_group *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 244 */;
	void cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 244 */;
	const struct media_device_ops cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 224 */;
	struct rvin_dev cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 147 */;
	struct platform_driver cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1389 */;
	struct rvin_dev *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1294 */;
	const struct soc_device_attribute *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1293 */;
	struct platform_device *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1291 */;
	int cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1291 */;
	const struct soc_device_attribute cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1283 */[];
	const struct of_device_id cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 1210 */[];
	struct media_pad *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 121 */;
	struct video_device *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 120 */;
	struct rvin_group cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 116 */;
	struct media_link *cocci_id/* drivers/media/platform/rcar-vin/rcar-core.c 112 */;
}
