cocci_test_suite() {
	struct v4l2_subdev *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 977 */;
	struct v4l2_mbus_framefmt *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 955 */;
	struct v4l2_mbus_framefmt cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 954 */;
	unsigned int cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 922 */;
	struct exynos_video_entity *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 920 */;
	struct fimc_fmt **cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 915 */;
	bool cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 914 */;
	struct v4l2_mbus_frame_desc cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 867 */;
	struct v4l2_plane_pix_format *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 864 */;
	struct v4l2_subdev_format cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 776 */;
	struct media_pad *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 747 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 733 */;
	struct file *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 732 */;
	void *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 732 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 724 */;
	u32 cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 581 */;
	const struct fimc_pix_limit *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 579 */;
	const struct fimc_variant *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 578 */;
	u32 *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 573 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 559 */;
	int cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 463 */(struct fimc_dev *fimc);
	const struct vb2_ops cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 453 */;
	struct fimc_vid_buffer cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 403 */;
	struct fimc_vid_buffer *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 402 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 401 */;
	void cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 399 */;
	unsigned long cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 385 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 377 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 375 */;
	struct device *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 341 */[];
	unsigned int cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 341 */[];
	void cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 310 */(struct vb2_buffer *vb);
	s32 cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 222 */;
	const struct v4l2_subdev_internal_ops cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1878 */;
	struct video_device *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1856 */;
	struct fimc_pipeline *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 180 */;
	struct v4l2_device *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1731 */;
	struct v4l2_format cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1715 */;
	const struct v4l2_subdev_ops cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1708 */;
	const struct v4l2_subdev_pad_ops cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1700 */;
	struct v4l2_subdev_selection *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1598 */;
	struct v4l2_subdev_format *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1491 */;
	struct v4l2_subdev_mbus_code_enum *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1478 */;
	struct v4l2_subdev_pad_config *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1477 */;
	struct fimc_md *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1445 */;
	const struct media_entity_operations cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1423 */;
	const struct media_pad *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1383 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1354 */;
	struct v4l2_rect cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1320 */;
	struct v4l2_rect *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1303 */;
	struct v4l2_selection *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1266 */;
	struct v4l2_requestbuffers *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1252 */;
	enum v4l2_buf_type cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1236 */;
	struct fimc_source_info *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1190 */;
	struct media_entity *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1189 */;
	struct v4l2_plane_pix_format cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1166 */[FIMC_MAX_PLANES];
	unsigned int *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1093 */;
	struct v4l2_input *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1068 */;
	struct fimc_fmt *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1024 */;
	struct fimc_frame *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1023 */;
	struct v4l2_pix_format_mplane *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1022 */;
	struct fimc_ctx *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1021 */;
	struct fimc_vid_cap *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1020 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1018 */;
	struct fimc_dev *cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1017 */;
	int cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1017 */;
	enum fimc_color_fmt cocci_id/* drivers/media/platform/exynos4-is/fimc-capture.c 1004 */;
}
