cocci_test_suite() {
	struct device *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 85 */[];
	unsigned int cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 84 */[];
	struct vb2_queue *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 83 */;
	unsigned int *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 83 */;
	struct vsp1_pipeline *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 60 */;
	size_t cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 58 */;
	u32 cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 518 */;
	const unsigned int *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 517 */;
	const struct vsp1_entity_operations *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 516 */;
	enum vsp1_entity_type cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 515 */;
	const char *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 515 */;
	struct vsp1_device *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 514 */;
	struct vsp1_entity *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 507 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 490 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 470 */;
	struct v4l2_meta_format *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 457 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 453 */;
	struct v4l2_fh *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 441 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 439 */;
	struct file *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 438 */;
	void *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 438 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 420 */;
	const struct v4l2_subdev_ops cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 411 */;
	const struct v4l2_subdev_pad_ops cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 402 */;
	struct v4l2_subdev_format *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 373 */;
	struct vsp1_histogram_buffer cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 32 */;
	unsigned int cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 296 */;
	struct v4l2_rect *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 206 */;
	struct v4l2_mbus_framefmt *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 205 */;
	struct v4l2_subdev_selection *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 201 */;
	struct v4l2_subdev_frame_size_enum *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 189 */;
	struct v4l2_subdev_pad_config *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 188 */;
	struct v4l2_subdev *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 187 */;
	struct v4l2_subdev_mbus_code_enum *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 174 */;
	const struct vb2_ops cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 158 */;
	unsigned long cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 127 */;
	void cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 122 */;
	struct vsp1_histogram_buffer *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 109 */;
	struct vsp1_histogram *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 108 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 107 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 105 */;
	int cocci_id/* drivers/media/platform/vsp1/vsp1_histo.c 105 */;
}
