cocci_test_suite() {
	struct isp_parallel_cfg *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 963 */;
	unsigned int *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 936 */;
	enum v4l2_field cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 886 */;
	const struct isp_format_info *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 807 */;
	struct isp_pipeline *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 805 */;
	void __user *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 735 */;
	long cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 735 */;
	u32 cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 710 */;
	struct ispccdc_fpc cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 708 */;
	struct omap3isp_ccdc_fpc cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 707 */;
	unsigned long cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 667 */;
	struct omap3isp_ccdc_update_config *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 664 */;
	struct ispccdc_lsc *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 493 */;
	u16 cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 407 */;
	struct isp_ccdc_device cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 389 */;
	struct ispccdc_lsc cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 388 */;
	struct work_struct *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 383 */;
	struct list_head *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 368 */;
	const unsigned int cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 35 */[];
	struct v4l2_mbus_framefmt *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 31 */(struct isp_ccdc_device *ccdc,
											      struct v4l2_subdev_pad_config *cfg,
											      unsigned int pad,
											      enum v4l2_subdev_format_whence which);
	struct ispccdc_lsc_config_req *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 309 */;
	struct media_entity *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2635 */;
	const struct v4l2_mbus_framefmt *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 262 */;
	struct v4l2_device *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2600 */;
	const struct media_entity_operations cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2588 */;
	const struct media_pad *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2504 */;
	const struct v4l2_subdev_internal_ops cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2486 */;
	const struct v4l2_subdev_ops cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2479 */;
	const struct v4l2_subdev_pad_ops cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2468 */;
	const struct v4l2_subdev_video_ops cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2463 */;
	const struct v4l2_subdev_core_ops cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2456 */;
	struct v4l2_subdev_fh *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2440 */;
	struct isp_bus_cfg *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2416 */;
	struct media_link *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2400 */;
	struct v4l2_subdev_format *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2306 */;
	struct v4l2_subdev_selection *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2221 */;
	struct v4l2_mbus_framefmt cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2184 */;
	struct v4l2_subdev_frame_size_enum *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2181 */;
	struct v4l2_subdev_mbus_code_enum *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 2115 */;
	struct omap3isp_ccdc_lsc_config *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 207 */;
	dma_addr_t cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 196 */;
	enum v4l2_subdev_format_whence cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1943 */;
	struct v4l2_subdev_pad_config *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1942 */;
	struct v4l2_rect *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1941 */;
	unsigned int cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1933 */;
	struct v4l2_mbus_framefmt *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1931 */;
	struct v4l2_event_subscription *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1850 */;
	struct v4l2_fh *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1849 */;
	void *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1830 */;
	const struct isp_video_operations cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1814 */;
	struct isp_video *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1783 */;
	struct isp_buffer *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1582 */;
	bool cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1534 */;
	struct v4l2_event cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1460 */;
	struct video_device *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1459 */;
	struct isp_device *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1313 */;
	struct isp_ccdc_device *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1311 */;
	int cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1311 */;
	void cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1311 */;
	struct media_pad *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1124 */;
	struct v4l2_subdev_format cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1121 */;
	const struct v4l2_rect *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1119 */;
	struct v4l2_subdev *cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1117 */;
	const u32 cocci_id/* drivers/media/platform/omap3isp/ispccdc.c 1077 */;
}
