cocci_test_suite() {
	struct s5p_mfc_fmt cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 33 */[];
	struct v4l2_format cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2685 */;
	struct v4l2_ctrl_config cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2615 */;
	const struct v4l2_ioctl_ops *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2605 */;
	struct vb2_ops *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2600 */;
	const struct s5p_mfc_codec_ops *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2595 */;
	struct vb2_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2584 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2421 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2420 */;
	struct device *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2369 */[];
	unsigned int *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2368 */;
	dma_addr_t cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2356 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2345 */;
	struct s5p_mfc_fmt *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2345 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2321 */;
	const struct v4l2_event_subscription *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2311 */;
	struct v4l2_fh *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2310 */;
	struct v4l2_encoder_cmd *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2269 */;
	struct v4l2_streamparm *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2252 */;
	const struct v4l2_ctrl_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 2229 */;
	struct v4l2_ctrl *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1772 */;
	const int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1760 */[];
	int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1758 */;
	struct s5p_mfc_ctx *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1757 */;
	void cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1757 */;
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1730 */[V4L2_MPEG_VIDEO_H264_VUI_SAR_IDC_EXTENDED + 1];
	enum v4l2_mpeg_video_h264_vui_sar_idc cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1728 */;
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1710 */[];
	enum v4l2_mpeg_video_hevc_level cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1708 */;
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1695 */[V4L2_MPEG_VIDEO_MPEG4_LEVEL_5 + 1];
	enum v4l2_mpeg_video_mpeg4_level cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1693 */;
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1676 */[V4L2_MPEG_VIDEO_H264_LEVEL_4_0 + 1];
	enum v4l2_mpeg_video_h264_level cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1674 */;
	enum v4l2_buf_type cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1663 */;
	struct v4l2_exportbuffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1637 */;
	const struct v4l2_event cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1611 */;
	struct v4l2_buffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1609 */;
	struct file *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1609 */;
	void *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1609 */;
	struct v4l2_requestbuffers *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1474 */;
	struct v4l2_pix_format_mplane *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1349 */;
	bool cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1312 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1311 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1300 */;
	const struct s5p_mfc_codec_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1291 */;
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1214 */;
	unsigned long cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1211 */;
	struct s5p_mfc_dev *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1209 */;
	struct s5p_mfc_enc_params *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1145 */;
	struct mfc_control cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 112 */[];
	struct s5p_mfc_buf cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1115 */;
	struct s5p_mfc_buf *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1110 */;
	const char *const cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1067 */[];
	const char *const *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1065 */;
	u32 cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 1065 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_enc.c 100 */;
}
