cocci_test_suite() {
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/via-camera.c 993 */;
	struct v4l2_subdev_frame_interval_enum cocci_id/* drivers/media/platform/via-camera.c 967 */;
	struct v4l2_frmivalenum *cocci_id/* drivers/media/platform/via-camera.c 964 */;
	struct v4l2_frmsizeenum *cocci_id/* drivers/media/platform/via-camera.c 943 */;
	struct v4l2_streamparm *cocci_id/* drivers/media/platform/via-camera.c 927 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/via-camera.c 916 */;
	struct v4l2_format cocci_id/* drivers/media/platform/via-camera.c 887 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/via-camera.c 874 */;
	struct v4l2_subdev_pad_config cocci_id/* drivers/media/platform/via-camera.c 846 */;
	struct v4l2_pix_format *cocci_id/* drivers/media/platform/via-camera.c 843 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/via-camera.c 793 */;
	struct file *cocci_id/* drivers/media/platform/via-camera.c 792 */;
	void *cocci_id/* drivers/media/platform/via-camera.c 792 */;
	const u32 cocci_id/* drivers/media/platform/via-camera.c 790 */;
	const struct v4l2_pix_format cocci_id/* drivers/media/platform/via-camera.c 780 */;
	unsigned int *cocci_id/* drivers/media/platform/via-camera.c 763 */;
	struct v4l2_input *cocci_id/* drivers/media/platform/via-camera.c 753 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/via-camera.c 734 */;
	const struct vb2_ops cocci_id/* drivers/media/platform/via-camera.c 674 */;
	struct device *cocci_id/* drivers/media/platform/via-camera.c 608 */[];
	unsigned int cocci_id/* drivers/media/platform/via-camera.c 607 */[];
	struct via_camera {
		struct v4l2_device v4l2_dev;
		struct v4l2_ctrl_handler ctrl_handler;
		struct video_device vdev;
		struct v4l2_subdev *sensor;
		struct platform_device *platdev;
		struct viafb_dev *viadev;
		struct mutex lock;
		enum viacam_opstate opstate;
		unsigned long flags;
		struct pm_qos_request qos_request;
		int power_gpio;
		int reset_gpio;
		void __iomem *mmio;
		void __iomem *fbmem;
		u32 fb_offset;
		unsigned int cb_offsets[3];
		u8 __iomem *cb_addrs[3];
		int n_cap_bufs;
		struct vb2_queue vq;
		struct list_head buffer_queue;
		u32 sequence;
		struct v4l2_pix_format sensor_format;
		struct v4l2_pix_format user_format;
		u32 mbus_code;
	} cocci_id/* drivers/media/platform/via-camera.c 60 */;
	enum viacam_opstate{S_IDLE=0, S_RUNNING=1,} cocci_id/* drivers/media/platform/via-camera.c 58 */;
	struct via_buffer cocci_id/* drivers/media/platform/via-camera.c 577 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/via-camera.c 575 */;
	struct via_buffer *cocci_id/* drivers/media/platform/via-camera.c 573 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/via-camera.c 573 */;
	unsigned long cocci_id/* drivers/media/platform/via-camera.c 534 */;
	bool cocci_id/* drivers/media/platform/via-camera.c 45 */;
	unsigned int cocci_id/* drivers/media/platform/via-camera.c 412 */;
	struct sg_table *cocci_id/* drivers/media/platform/via-camera.c 347 */;
	irqreturn_t cocci_id/* drivers/media/platform/via-camera.c 342 */;
	struct v4l2_subdev_format cocci_id/* drivers/media/platform/via-camera.c 255 */;
	struct v4l2_control cocci_id/* drivers/media/platform/via-camera.c 241 */;
	void cocci_id/* drivers/media/platform/via-camera.c 219 */;
	int cocci_id/* drivers/media/platform/via-camera.c 181 */;
	unsigned cocci_id/* drivers/media/platform/via-camera.c 166 */;
	u32 cocci_id/* drivers/media/platform/via-camera.c 164 */;
	struct via_format *cocci_id/* drivers/media/platform/via-camera.c 164 */;
	struct via_format {
		__u32 pixelformat;
		int bpp;
		u32 mbus_code;
	} cocci_id/* drivers/media/platform/via-camera.c 147 */[];
	struct platform_driver cocci_id/* drivers/media/platform/via-camera.c 1312 */;
	struct via_camera cocci_id/* drivers/media/platform/via-camera.c 1177 */;
	struct via_camera *cocci_id/* drivers/media/platform/via-camera.c 116 */;
	struct i2c_board_info cocci_id/* drivers/media/platform/via-camera.c 1140 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/via-camera.c 1139 */;
	struct viafb_dev *cocci_id/* drivers/media/platform/via-camera.c 1138 */;
	struct i2c_adapter *cocci_id/* drivers/media/platform/via-camera.c 1137 */;
	struct platform_device *cocci_id/* drivers/media/platform/via-camera.c 1134 */;
	struct ov7670_config cocci_id/* drivers/media/platform/via-camera.c 1129 */;
	u8 cocci_id/* drivers/media/platform/via-camera.c 1108 */;
	struct pci_bus *cocci_id/* drivers/media/platform/via-camera.c 1107 */;
	const struct video_device cocci_id/* drivers/media/platform/via-camera.c 1085 */;
	struct viafb_pm_hooks cocci_id/* drivers/media/platform/via-camera.c 1074 */;
	struct via_buffer {
		struct vb2_v4l2_buffer vbuf;
		struct list_head queue;
	} cocci_id/* drivers/media/platform/via-camera.c 106 */;
	enum viacam_opstate cocci_id/* drivers/media/platform/via-camera.c 1029 */;
}
