cocci_test_suite() {
	struct vb2_queue *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 945 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 944 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 942 */;
	struct device *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 886 */[];
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 885 */[];
	unsigned int *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 884 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 860 */;
	const struct v4l2_event_subscription *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 846 */;
	struct v4l2_fh *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 845 */;
	struct s5p_mfc_buf cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 831 */;
	struct v4l2_decoder_cmd *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 805 */;
	struct file *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 804 */;
	void *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 804 */;
	u32 cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 754 */;
	struct v4l2_selection *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 750 */;
	const struct v4l2_ctrl_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 743 */;
	struct v4l2_ctrl *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 711 */;
	enum v4l2_buf_type cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 675 */;
	struct v4l2_exportbuffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 646 */;
	const struct v4l2_event cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 616 */;
	struct v4l2_buffer *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 614 */;
	struct v4l2_requestbuffers *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 493 */;
	struct s5p_mfc_dev *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 492 */;
	struct s5p_mfc_ctx *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 492 */;
	int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 492 */;
	struct s5p_mfc_buf_size *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 398 */;
	struct v4l2_pix_format_mplane *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 304 */;
	struct s5p_mfc_fmt cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 30 */[];
	bool cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 265 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 264 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 252 */;
	const struct s5p_mfc_codec_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 243 */;
	struct mfc_control cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 160 */[];
	struct v4l2_format *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 148 */;
	struct s5p_mfc_fmt *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 148 */;
	unsigned int cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 148 */;
	struct v4l2_format cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1170 */;
	struct v4l2_ctrl_config cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1117 */;
	const struct v4l2_ioctl_ops *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1107 */;
	struct vb2_ops *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1102 */;
	const struct s5p_mfc_codec_ops *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1097 */;
	void cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1097 */;
	struct vb2_ops cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1087 */;
	struct s5p_mfc_buf *cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1061 */;
	unsigned long cocci_id/* drivers/media/platform/s5p-mfc/s5p_mfc_dec.c 1060 */;
}
