cocci_test_suite() {
	struct vpe_us_coeffs {
		unsigned short anchor_fid0_c0;
		unsigned short anchor_fid0_c1;
		unsigned short anchor_fid0_c2;
		unsigned short anchor_fid0_c3;
		unsigned short interp_fid0_c0;
		unsigned short interp_fid0_c1;
		unsigned short interp_fid0_c2;
		unsigned short interp_fid0_c3;
		unsigned short anchor_fid1_c0;
		unsigned short anchor_fid1_c1;
		unsigned short anchor_fid1_c2;
		unsigned short anchor_fid1_c3;
		unsigned short interp_fid1_c0;
		unsigned short interp_fid1_c1;
		unsigned short interp_fid1_c2;
		unsigned short interp_fid1_c3;
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 87 */;
	u32 *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 840 */;
	struct vpe_mmr_adb *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 839 */;
	const struct vpe_dei_regs *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 825 */;
	bool cocci_id/* drivers/media/platform/ti-vpe/vpe.c 796 */;
	struct vpdma_data_format *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 767 */;
	const unsigned short *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 662 */;
	unsigned long cocci_id/* drivers/media/platform/ti-vpe/vpe.c 601 */;
	struct vpe_dev *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 600 */;
	struct device *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 549 */;
	size_t cocci_id/* drivers/media/platform/ti-vpe/vpe.c 547 */;
	struct vpe_mmr_adb {
		struct vpdma_adb_hdr out_fmt_hdr;
		u32 out_fmt_reg[1];
		u32 out_fmt_pad[3];
		struct vpdma_adb_hdr us1_hdr;
		u32 us1_regs[8];
		struct vpdma_adb_hdr us2_hdr;
		u32 us2_regs[8];
		struct vpdma_adb_hdr us3_hdr;
		u32 us3_regs[8];
		struct vpdma_adb_hdr dei_hdr;
		u32 dei_regs[8];
		struct vpdma_adb_hdr sc_hdr0;
		u32 sc_regs0[7];
		u32 sc_pad0[1];
		struct vpdma_adb_hdr sc_hdr8;
		u32 sc_regs8[6];
		u32 sc_pad8[2];
		struct vpdma_adb_hdr sc_hdr17;
		u32 sc_regs17[9];
		u32 sc_pad17[3];
		struct vpdma_adb_hdr csc_hdr;
		u32 csc_regs[6];
		u32 csc_pad[2];
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 489 */;
	enum v4l2_buf_type cocci_id/* drivers/media/platform/ti-vpe/vpe.c 431 */;
	struct vpe_ctx {
		struct v4l2_fh fh;
		struct vpe_dev *dev;
		struct v4l2_ctrl_handler hdl;
		unsigned int field;
		unsigned int sequence;
		unsigned int aborting;
		unsigned int bufs_per_job;
		unsigned int bufs_completed;
		struct vpe_q_data q_data[2];
		struct vb2_v4l2_buffer *src_vbs[VPE_MAX_SRC_BUFS];
		struct vb2_v4l2_buffer *dst_vb;
		dma_addr_t mv_buf_dma[2];
		void *mv_buf[2];
		size_t mv_buf_size;
		struct vpdma_buf mmr_adb;
		struct vpdma_buf sc_coeff_h;
		struct vpdma_buf sc_coeff_v;
		struct vpdma_desc_list desc_list;
		bool deinterlacing;
		bool load_mmrs;
		unsigned int src_mv_buf_selector;
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 395 */;
	struct vpe_dev {
		struct v4l2_device v4l2_dev;
		struct video_device vfd;
		struct v4l2_m2m_dev *m2m_dev;
		atomic_t num_instances;
		dma_addr_t loaded_mmrs;
		struct mutex dev_mutex;
		spinlock_t lock;
		int irq;
		void __iomem *base;
		struct resource *res;
		struct vpdma_data vpdma_data;
		struct vpdma_data *vpdma;
		struct sc_data *sc;
		struct csc_data *csc;
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 372 */;
	unsigned int cocci_id/* drivers/media/platform/ti-vpe/vpe.c 352 */;
	enum{Q_DATA_SRC=0, Q_DATA_DST=1,} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 343 */;
	struct vpe_q_data {
		struct v4l2_format format;
		unsigned int flags;
		struct v4l2_rect c_rect;
		struct vpe_fmt *fmt;
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 321 */;
	struct platform_driver cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2654 */;
	const struct of_device_id cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2645 */[];
	struct video_device *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2495 */;
	struct platform_device *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2492 */;
	const struct v4l2_m2m_ops cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2464 */;
	const struct video_device cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2454 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2445 */;
	struct vpe_fmt cocci_id/* drivers/media/platform/ti-vpe/vpe.c 234 */[];
	struct vpe_mmr_adb cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2298 */;
	struct v4l2_ctrl_handler *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2275 */;
	struct vpe_fmt {
		u32 fourcc;
		u8 types;
		u8 coplanar;
		const struct vpdma_data_format *vpdma_fmt[VPE_MAX_PLANES];
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 226 */;
	const struct v4l2_ctrl_config cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2257 */;
	struct v4l2_m2m_buffer cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2232 */;
	const struct vb2_ops cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2211 */;
	enum vb2_buffer_state cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2127 */;
	long cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2086 */;
	struct device *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2028 */[];
	unsigned int cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2028 */[];
	unsigned int *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 2027 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1995 */;
	const struct v4l2_ctrl_ops cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1991 */;
	struct vpe_ctx cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1976 */;
	struct v4l2_ctrl *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1973 */;
	struct v4l2_selection cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1942 */;
	struct v4l2_selection *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1806 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1738 */;
	struct vpe_q_data *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1737 */;
	struct v4l2_pix_format_mplane *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1735 */;
	struct vpe_ctx *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1733 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1733 */;
	const struct vpe_port_data cocci_id/* drivers/media/platform/ti-vpe/vpe.c 173 */[11];
	const struct v4l2_format_info *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1604 */;
	struct v4l2_plane_pix_format *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1600 */;
	struct file *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1553 */;
	struct vpe_fmt *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1533 */;
	u32 cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1530 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1530 */;
	int cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1530 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1521 */;
	struct vpe_port_data {
		enum vpdma_channel channel;
		u8 vb_index;
		u8 vb_part;
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 152 */;
	const struct vpe_dei_regs cocci_id/* drivers/media/platform/ti-vpe/vpe.c 140 */;
	irqreturn_t cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1365 */;
	struct vpe_dei_regs {
		unsigned long mdt_spacial_freq_thr_reg;
		unsigned long edi_config_reg;
		unsigned long edi_lut_reg0;
		unsigned long edi_lut_reg1;
		unsigned long edi_lut_reg2;
		unsigned long edi_lut_reg3;
	} cocci_id/* drivers/media/platform/ti-vpe/vpe.c 128 */;
	struct sc_data *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1213 */;
	void *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1210 */;
	dma_addr_t cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1093 */;
	const struct vpe_us_coeffs cocci_id/* drivers/media/platform/ti-vpe/vpe.c 109 */[];
	const struct vpdma_data_format *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1089 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1086 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1085 */;
	const struct vpe_port_data *cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1084 */;
	void cocci_id/* drivers/media/platform/ti-vpe/vpe.c 1081 */;
}
