cocci_test_suite() {
	const struct isi_format *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 998 */[ARRAY_SIZE(isi_formats)];
	const struct isi_format cocci_id/* drivers/media/platform/atmel/atmel-isi.c 952 */[];
	struct atmel_isi {
		spinlock_t irqlock;
		struct device *dev;
		void __iomem *regs;
		int sequence;
		struct fbd *p_fb_descriptors;
		dma_addr_t fb_descriptors_phys;
		struct list_head dma_desc_head;
		struct isi_dma_desc dma_desc[VIDEO_MAX_FRAME];
		bool enable_preview_path;
		struct completion complete;
		struct clk *pclk;
		unsigned int irq;
		struct isi_platform_data pdata;
		u16 width_flags;
		struct list_head video_buffer_list;
		struct frame_buffer *active;
		struct v4l2_device v4l2_dev;
		struct video_device *vdev;
		struct v4l2_async_notifier notifier;
		struct isi_graph_entity entity;
		struct v4l2_format fmt;
		const struct isi_format **user_formats;
		unsigned int num_user_formats;
		const struct isi_format *current_fmt;
		struct mutex lock;
		struct vb2_queue queue;
	} cocci_id/* drivers/media/platform/atmel/atmel-isi.c 94 */;
	struct v4l2_format cocci_id/* drivers/media/platform/atmel/atmel-isi.c 933 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/atmel/atmel-isi.c 921 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/atmel/atmel-isi.c 889 */;
	bool cocci_id/* drivers/media/platform/atmel/atmel-isi.c 872 */;
	struct isi_format {
		u32 fourcc;
		u32 mbus_code;
		u8 bpp;
		u32 swap;
	} cocci_id/* drivers/media/platform/atmel/atmel-isi.c 86 */;
	struct v4l2_fwnode_endpoint cocci_id/* drivers/media/platform/atmel/atmel-isi.c 790 */;
	struct device_node *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 789 */;
	struct platform_device *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 787 */;
	int cocci_id/* drivers/media/platform/atmel/atmel-isi.c 786 */;
	struct v4l2_subdev_frame_interval_enum cocci_id/* drivers/media/platform/atmel/atmel-isi.c 733 */;
	struct v4l2_frmivalenum *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 729 */;
	struct v4l2_subdev_frame_size_enum cocci_id/* drivers/media/platform/atmel/atmel-isi.c 704 */;
	struct v4l2_frmsizeenum *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 700 */;
	struct isi_graph_entity {
		struct device_node *node;
		struct v4l2_async_subdev asd;
		struct v4l2_subdev *subdev;
	} cocci_id/* drivers/media/platform/atmel/atmel-isi.c 70 */;
	struct v4l2_streamparm *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 685 */;
	unsigned int *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 672 */;
	struct v4l2_input *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 662 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 653 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 641 */;
	struct file *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 640 */;
	void *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 640 */;
	struct frame_buffer {
		struct vb2_v4l2_buffer vb;
		struct isi_dma_desc *p_dma_desc;
		struct list_head list;
	} cocci_id/* drivers/media/platform/atmel/atmel-isi.c 64 */;
	struct v4l2_subdev_format cocci_id/* drivers/media/platform/atmel/atmel-isi.c 598 */;
	struct isi_dma_desc {
		struct list_head list;
		struct fbd *p_fbd;
		dma_addr_t fbd_phys;
	} cocci_id/* drivers/media/platform/atmel/atmel-isi.c 57 */;
	struct v4l2_subdev_pad_config cocci_id/* drivers/media/platform/atmel/atmel-isi.c 562 */;
	struct v4l2_pix_format *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 561 */;
	const struct isi_format **cocci_id/* drivers/media/platform/atmel/atmel-isi.c 558 */;
	unsigned int cocci_id/* drivers/media/platform/atmel/atmel-isi.c 542 */;
	const struct isi_format *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 541 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 532 */;
	struct fbd *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 52 */;
	const struct vb2_ops cocci_id/* drivers/media/platform/atmel/atmel-isi.c 519 */;
	struct fbd {
		u32 fb_address;
		u32 dma_ctrl;
		u32 next_fbd_address;
	} cocci_id/* drivers/media/platform/atmel/atmel-isi.c 43 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 347 */;
	void cocci_id/* drivers/media/platform/atmel/atmel-isi.c 347 */;
	struct isi_dma_desc cocci_id/* drivers/media/platform/atmel/atmel-isi.c 331 */;
	struct isi_dma_desc *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 312 */;
	struct device *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 273 */[];
	unsigned int cocci_id/* drivers/media/platform/atmel/atmel-isi.c 273 */[];
	unsigned long cocci_id/* drivers/media/platform/atmel/atmel-isi.c 245 */;
	u32 cocci_id/* drivers/media/platform/atmel/atmel-isi.c 195 */;
	struct frame_buffer cocci_id/* drivers/media/platform/atmel/atmel-isi.c 192 */;
	struct frame_buffer *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 178 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 177 */;
	irqreturn_t cocci_id/* drivers/media/platform/atmel/atmel-isi.c 174 */;
	struct atmel_isi *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 174 */;
	struct platform_driver cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1333 */;
	const struct of_device_id cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1327 */[];
	const struct dev_pm_ops cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1322 */;
	struct device *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1314 */;
	struct fbd cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1224 */;
	struct atmel_isi cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1162 */;
	struct resource *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1159 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1158 */;
	const struct v4l2_async_notifier_operations cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1095 */;
	struct v4l2_async_subdev *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1084 */;
	struct v4l2_async_notifier *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1082 */;
	struct isi_format *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1028 */;
	struct v4l2_subdev_mbus_code_enum cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1001 */;
	struct v4l2_subdev *cocci_id/* drivers/media/platform/atmel/atmel-isi.c 1000 */;
}
