cocci_test_suite() {
	struct v4l2_bt_timings *cocci_id/* drivers/media/platform/davinci/vpif_display.c 916 */;
	struct vpif_channel_config_params *cocci_id/* drivers/media/platform/davinci/vpif_display.c 914 */;
	struct v4l2_output cocci_id/* drivers/media/platform/davinci/vpif_display.c 881 */;
	struct vpif_display_chan_config *cocci_id/* drivers/media/platform/davinci/vpif_display.c 880 */;
	struct video_device *cocci_id/* drivers/media/platform/davinci/vpif_display.c 878 */;
	struct vpif_display_config *cocci_id/* drivers/media/platform/davinci/vpif_display.c 877 */;
	struct v4l2_enum_dv_timings *cocci_id/* drivers/media/platform/davinci/vpif_display.c 875 */;
	struct file *cocci_id/* drivers/media/platform/davinci/vpif_display.c 874 */;
	u32 cocci_id/* drivers/media/platform/davinci/vpif_display.c 812 */;
	const char *cocci_id/* drivers/media/platform/davinci/vpif_display.c 777 */;
	struct vpif_subdev_info *cocci_id/* drivers/media/platform/davinci/vpif_display.c 776 */;
	struct v4l2_output *cocci_id/* drivers/media/platform/davinci/vpif_display.c 744 */;
	struct channel_obj *cocci_id/* drivers/media/platform/davinci/vpif_display.c 74 */;
	v4l2_std_id *cocci_id/* drivers/media/platform/davinci/vpif_display.c 723 */;
	struct vb2_buffer *cocci_id/* drivers/media/platform/davinci/vpif_display.c 71 */;
	v4l2_std_id cocci_id/* drivers/media/platform/davinci/vpif_display.c 675 */;
	struct v4l2_pix_format *cocci_id/* drivers/media/platform/davinci/vpif_display.c 657 */;
	struct v4l2_format *cocci_id/* drivers/media/platform/davinci/vpif_display.c 607 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/media/platform/davinci/vpif_display.c 596 */;
	struct v4l2_capability *cocci_id/* drivers/media/platform/davinci/vpif_display.c 583 */;
	struct vpif_disp_buffer *cocci_id/* drivers/media/platform/davinci/vpif_display.c 58 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/media/platform/davinci/vpif_display.c 58 */;
	void cocci_id/* drivers/media/platform/davinci/vpif_display.c 55 */(struct channel_obj *ch,
									    int muxmode);
	void cocci_id/* drivers/media/platform/davinci/vpif_display.c 54 */(struct channel_obj *ch);
	struct device *cocci_id/* drivers/media/platform/davinci/vpif_display.c 53 */;
	struct vpif_device cocci_id/* drivers/media/platform/davinci/vpif_display.c 52 */;
	unsigned int cocci_id/* drivers/media/platform/davinci/vpif_display.c 506 */;
	struct video_obj *cocci_id/* drivers/media/platform/davinci/vpif_display.c 505 */;
	enum v4l2_field cocci_id/* drivers/media/platform/davinci/vpif_display.c 504 */;
	struct vpif_params *cocci_id/* drivers/media/platform/davinci/vpif_display.c 503 */;
	u8 cocci_id/* drivers/media/platform/davinci/vpif_display.c 50 */[VPIF_NUMOBJECTS][2];
	const struct vpif_channel_config_params *cocci_id/* drivers/media/platform/davinci/vpif_display.c 434 */;
	int cocci_id/* drivers/media/platform/davinci/vpif_display.c 38 */;
	int *cocci_id/* drivers/media/platform/davinci/vpif_display.c 369 */;
	struct vpif_device *cocci_id/* drivers/media/platform/davinci/vpif_display.c 363 */;
	irqreturn_t cocci_id/* drivers/media/platform/davinci/vpif_display.c 361 */;
	void *cocci_id/* drivers/media/platform/davinci/vpif_display.c 361 */;
	struct common_obj *cocci_id/* drivers/media/platform/davinci/vpif_display.c 323 */;
	struct vpif_disp_buffer cocci_id/* drivers/media/platform/davinci/vpif_display.c 310 */;
	unsigned long cocci_id/* drivers/media/platform/davinci/vpif_display.c 305 */;
	const struct vb2_ops cocci_id/* drivers/media/platform/davinci/vpif_display.c 293 */;
	struct platform_driver cocci_id/* drivers/media/platform/davinci/vpif_display.c 1450 */;
	struct resource *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1252 */;
	struct i2c_adapter *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1251 */;
	struct platform_device *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1248 */;
	const struct v4l2_async_notifier_operations cocci_id/* drivers/media/platform/davinci/vpif_display.c 1239 */;
	unsigned cocci_id/* drivers/media/platform/davinci/vpif_display.c 117 */;
	struct device *cocci_id/* drivers/media/platform/davinci/vpif_display.c 113 */[];
	unsigned int cocci_id/* drivers/media/platform/davinci/vpif_display.c 113 */[];
	struct v4l2_async_subdev *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1122 */;
	struct v4l2_subdev *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1121 */;
	struct v4l2_async_notifier *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1120 */;
	unsigned int *cocci_id/* drivers/media/platform/davinci/vpif_display.c 112 */;
	void cocci_id/* drivers/media/platform/davinci/vpif_display.c 1112 */;
	struct vb2_queue *cocci_id/* drivers/media/platform/davinci/vpif_display.c 111 */;
	struct channel_obj cocci_id/* drivers/media/platform/davinci/vpif_display.c 1095 */;
	const struct v4l2_file_operations cocci_id/* drivers/media/platform/davinci/vpif_display.c 1077 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/media/platform/davinci/vpif_display.c 1047 */;
	struct v4l2_dv_timings *cocci_id/* drivers/media/platform/davinci/vpif_display.c 1006 */;
}
