cocci_test_suite() {
	void __init cocci_id/* drivers/clk/rockchip/clk.c 624 */;
	struct notifier_block cocci_id/* drivers/clk/rockchip/clk.c 619 */;
	void (*cocci_id/* drivers/clk/rockchip/clk.c 608 */)(void);
	unsigned int cocci_id/* drivers/clk/rockchip/clk.c 607 */;
	const char *const cocci_id/* drivers/clk/rockchip/clk.c 592 */[];
	const struct rockchip_cpuclk_rate_table *cocci_id/* drivers/clk/rockchip/clk.c 575 */;
	const struct rockchip_cpuclk_reg_data *cocci_id/* drivers/clk/rockchip/clk.c 574 */;
	u8 cocci_id/* drivers/clk/rockchip/clk.c 573 */;
	const char *const *cocci_id/* drivers/clk/rockchip/clk.c 572 */;
	const char *cocci_id/* drivers/clk/rockchip/clk.c 572 */;
	const struct clk_ops *cocci_id/* drivers/clk/rockchip/clk.c 50 */;
	struct clk_divider *cocci_id/* drivers/clk/rockchip/clk.c 49 */;
	struct clk_gate *cocci_id/* drivers/clk/rockchip/clk.c 48 */;
	spinlock_t *cocci_id/* drivers/clk/rockchip/clk.c 44 */;
	struct rockchip_clk_branch *cocci_id/* drivers/clk/rockchip/clk.c 439 */;
	struct clk_div_table *cocci_id/* drivers/clk/rockchip/clk.c 42 */;
	struct rockchip_pll_clock *cocci_id/* drivers/clk/rockchip/clk.c 414 */;
	struct clk *cocci_id/* drivers/clk/rockchip/clk.c 407 */;
	struct rockchip_clk_provider *cocci_id/* drivers/clk/rockchip/clk.c 406 */;
	void cocci_id/* drivers/clk/rockchip/clk.c 406 */;
	void __init cocci_id/* drivers/clk/rockchip/clk.c 398 */;
	struct rockchip_clk_provider cocci_id/* drivers/clk/rockchip/clk.c 371 */;
	struct clk **cocci_id/* drivers/clk/rockchip/clk.c 368 */;
	void __iomem *cocci_id/* drivers/clk/rockchip/clk.c 365 */;
	struct rockchip_clk_provider *__init cocci_id/* drivers/clk/rockchip/clk.c 364 */;
	struct device_node *cocci_id/* drivers/clk/rockchip/clk.c 364 */;
	struct clk_fixed_factor *cocci_id/* drivers/clk/rockchip/clk.c 325 */;
	struct clk_init_data cocci_id/* drivers/clk/rockchip/clk.c 270 */;
	struct clk_fractional_divider *cocci_id/* drivers/clk/rockchip/clk.c 220 */;
	unsigned long *cocci_id/* drivers/clk/rockchip/clk.c 180 */;
	struct clk_hw *cocci_id/* drivers/clk/rockchip/clk.c 179 */;
	struct clk_mux *cocci_id/* drivers/clk/rockchip/clk.c 145 */;
	struct rockchip_clk_frac *cocci_id/* drivers/clk/rockchip/clk.c 144 */;
	struct clk_notifier_data *cocci_id/* drivers/clk/rockchip/clk.c 143 */;
	void *cocci_id/* drivers/clk/rockchip/clk.c 141 */;
	unsigned long cocci_id/* drivers/clk/rockchip/clk.c 141 */;
	struct notifier_block *cocci_id/* drivers/clk/rockchip/clk.c 140 */;
	int cocci_id/* drivers/clk/rockchip/clk.c 140 */;
	struct rockchip_clk_frac cocci_id/* drivers/clk/rockchip/clk.c 138 */;
	struct rockchip_clk_frac {
		struct notifier_block clk_nb;
		struct clk_fractional_divider div;
		struct clk_gate gate;
		struct clk_mux mux;
		const struct clk_ops *mux_ops;
		int mux_frac_idx;
		bool rate_change_remuxed;
		int rate_change_idx;
	} cocci_id/* drivers/clk/rockchip/clk.c 124 */;
}
