cocci_test_suite() {
	const struct config_item_type cocci_id/* drivers/usb/gadget/function/f_hid.c 991 */;
	struct configfs_attribute *cocci_id/* drivers/usb/gadget/function/f_hid.c 982 */[];
	struct f_hid_opts *cocci_id/* drivers/usb/gadget/function/f_hid.c 975 */;
	struct config_item *cocci_id/* drivers/usb/gadget/function/f_hid.c 973 */;
	char *cocci_id/* drivers/usb/gadget/function/f_hid.c 973 */;
	ssize_t cocci_id/* drivers/usb/gadget/function/f_hid.c 973 */;
	const char *cocci_id/* drivers/usb/gadget/function/f_hid.c 942 */;
	size_t cocci_id/* drivers/usb/gadget/function/f_hid.c 942 */;
	int cocci_id/* drivers/usb/gadget/function/f_hid.c 931 */;
	struct hid_descriptor cocci_id/* drivers/usb/gadget/function/f_hid.c 88 */;
	struct configfs_item_operations cocci_id/* drivers/usb/gadget/function/f_hid.c 876 */;
	struct usb_interface_descriptor cocci_id/* drivers/usb/gadget/function/f_hid.c 76 */;
	struct device *cocci_id/* drivers/usb/gadget/function/f_hid.c 749 */;
	struct usb_string *cocci_id/* drivers/usb/gadget/function/f_hid.c 748 */;
	struct usb_configuration *cocci_id/* drivers/usb/gadget/function/f_hid.c 744 */;
	const struct file_operations cocci_id/* drivers/usb/gadget/function/f_hid.c 734 */;
	struct usb_function *cocci_id/* drivers/usb/gadget/function/f_hid.c 68 */;
	struct usb_composite_dev *cocci_id/* drivers/usb/gadget/function/f_hid.c 637 */;
	unsigned short cocci_id/* drivers/usb/gadget/function/f_hid.c 567 */;
	u8 *cocci_id/* drivers/usb/gadget/function/f_hid.c 528 */;
	__u16 cocci_id/* drivers/usb/gadget/function/f_hid.c 503 */;
	const struct usb_ctrlrequest *cocci_id/* drivers/usb/gadget/function/f_hid.c 497 */;
	struct f_hidg cocci_id/* drivers/usb/gadget/function/f_hid.c 445 */;
	struct f_hidg *cocci_id/* drivers/usb/gadget/function/f_hid.c 444 */;
	struct inode *cocci_id/* drivers/usb/gadget/function/f_hid.c 442 */;
	struct file *cocci_id/* drivers/usb/gadget/function/f_hid.c 442 */;
	__poll_t cocci_id/* drivers/usb/gadget/function/f_hid.c 416 */;
	poll_table *cocci_id/* drivers/usb/gadget/function/f_hid.c 416 */;
	struct f_hidg {
		unsigned char bInterfaceSubClass;
		unsigned char bInterfaceProtocol;
		unsigned char protocol;
		unsigned short report_desc_length;
		char *report_desc;
		unsigned short report_length;
		struct list_head completed_out_req;
		spinlock_t read_spinlock;
		wait_queue_head_t read_queue;
		unsigned int qlen;
		spinlock_t write_spinlock;
		bool write_pending;
		wait_queue_head_t write_queue;
		struct usb_request *req;
		int minor;
		struct cdev cdev;
		struct usb_function func;
		struct usb_ep *in_ep;
		struct usb_ep *out_ep;
	} cocci_id/* drivers/usb/gadget/function/f_hid.c 39 */;
	unsigned cocci_id/* drivers/usb/gadget/function/f_hid.c 364 */;
	const char __user *cocci_id/* drivers/usb/gadget/function/f_hid.c 334 */;
	struct f_hidg_req_list {
		struct usb_request *req;
		unsigned int pos;
		struct list_head list;
	} cocci_id/* drivers/usb/gadget/function/f_hid.c 33 */;
	struct usb_ep *cocci_id/* drivers/usb/gadget/function/f_hid.c 318 */;
	void cocci_id/* drivers/usb/gadget/function/f_hid.c 318 */;
	unsigned int cocci_id/* drivers/usb/gadget/function/f_hid.c 285 */;
	struct f_hidg_req_list cocci_id/* drivers/usb/gadget/function/f_hid.c 276 */;
	struct class *cocci_id/* drivers/usb/gadget/function/f_hid.c 26 */;
	unsigned long cocci_id/* drivers/usb/gadget/function/f_hid.c 249 */;
	struct usb_request *cocci_id/* drivers/usb/gadget/function/f_hid.c 248 */;
	struct f_hidg_req_list *cocci_id/* drivers/usb/gadget/function/f_hid.c 247 */;
	loff_t *cocci_id/* drivers/usb/gadget/function/f_hid.c 244 */;
	char __user *cocci_id/* drivers/usb/gadget/function/f_hid.c 243 */;
	struct usb_gadget_strings *cocci_id/* drivers/usb/gadget/function/f_hid.c 235 */[];
	struct usb_gadget_strings cocci_id/* drivers/usb/gadget/function/f_hid.c 230 */;
	struct usb_string cocci_id/* drivers/usb/gadget/function/f_hid.c 225 */[];
	struct usb_descriptor_header *cocci_id/* drivers/usb/gadget/function/f_hid.c 213 */;
	struct usb_descriptor_header *cocci_id/* drivers/usb/gadget/function/f_hid.c 212 */[];
	struct usb_endpoint_descriptor cocci_id/* drivers/usb/gadget/function/f_hid.c 188 */;
	dev_t cocci_id/* drivers/usb/gadget/function/f_hid.c 1139 */;
	struct usb_gadget *cocci_id/* drivers/usb/gadget/function/f_hid.c 1136 */;
	struct usb_ss_ep_comp_descriptor cocci_id/* drivers/usb/gadget/function/f_hid.c 112 */;
	struct f_hid_opts cocci_id/* drivers/usb/gadget/function/f_hid.c 1095 */;
	struct usb_function_instance *cocci_id/* drivers/usb/gadget/function/f_hid.c 1085 */;
}
