cocci_test_suite() {
	struct serial_icounter_struct *cocci_id/* drivers/usb/class/cdc-acm.c 977 */;
	struct async_icount cocci_id/* drivers/usb/class/cdc-acm.c 937 */;
	struct serial_struct *cocci_id/* drivers/usb/class/cdc-acm.c 893 */;
	struct acm *cocci_id/* drivers/usb/class/cdc-acm.c 87 */;
	int cocci_id/* drivers/usb/class/cdc-acm.c 87 */;
	const unsigned char *cocci_id/* drivers/usb/class/cdc-acm.c 753 */;
	struct file *cocci_id/* drivers/usb/class/cdc-acm.c 745 */;
	struct acm_wb *cocci_id/* drivers/usb/class/cdc-acm.c 706 */;
	struct acm cocci_id/* drivers/usb/class/cdc-acm.c 635 */;
	struct tty_port *cocci_id/* drivers/usb/class/cdc-acm.c 633 */;
	struct work_struct *cocci_id/* drivers/usb/class/cdc-acm.c 554 */;
	void cocci_id/* drivers/usb/class/cdc-acm.c 53 */(struct tty_struct *tty,
							  struct ktermios *termios_old);
	struct tty_driver *cocci_id/* drivers/usb/class/cdc-acm.c 48 */;
	bool cocci_id/* drivers/usb/class/cdc-acm.c 472 */;
	struct usb_driver cocci_id/* drivers/usb/class/cdc-acm.c 47 */;
	gfp_t cocci_id/* drivers/usb/class/cdc-acm.c 420 */;
	unsigned char *cocci_id/* drivers/usb/class/cdc-acm.c 409 */;
	struct usb_cdc_notification cocci_id/* drivers/usb/class/cdc-acm.c 375 */;
	unsigned int cocci_id/* drivers/usb/class/cdc-acm.c 345 */;
	struct usb_cdc_notification *cocci_id/* drivers/usb/class/cdc-acm.c 344 */;
	struct urb *cocci_id/* drivers/usb/class/cdc-acm.c 341 */;
	void cocci_id/* drivers/usb/class/cdc-acm.c 341 */;
	struct device_attribute *cocci_id/* drivers/usb/class/cdc-acm.c 240 */;
	char *cocci_id/* drivers/usb/class/cdc-acm.c 240 */;
	ssize_t cocci_id/* drivers/usb/class/cdc-acm.c 239 */;
	void __exit cocci_id/* drivers/usb/class/cdc-acm.c 1985 */;
	int __init cocci_id/* drivers/usb/class/cdc-acm.c 1949 */;
	const struct tty_operations cocci_id/* drivers/usb/class/cdc-acm.c 1924 */;
	const struct usb_device_id cocci_id/* drivers/usb/class/cdc-acm.c 1656 */[];
	pm_message_t cocci_id/* drivers/usb/class/cdc-acm.c 1559 */;
	struct tty_struct *cocci_id/* drivers/usb/class/cdc-acm.c 1508 */;
	struct usb_interface *cocci_id/* drivers/usb/class/cdc-acm.c 1505 */;
	struct usb_cdc_country_functional_desc *cocci_id/* drivers/usb/class/cdc-acm.c 1413 */;
	struct acm_rb *cocci_id/* drivers/usb/class/cdc-acm.c 1358 */;
	struct device *cocci_id/* drivers/usb/class/cdc-acm.c 1141 */;
	unsigned long cocci_id/* drivers/usb/class/cdc-acm.c 1137 */;
	u8 *cocci_id/* drivers/usb/class/cdc-acm.c 1134 */;
	struct usb_cdc_parsed_header cocci_id/* drivers/usb/class/cdc-acm.c 1130 */;
	struct usb_device *cocci_id/* drivers/usb/class/cdc-acm.c 1129 */;
	struct usb_endpoint_descriptor *cocci_id/* drivers/usb/class/cdc-acm.c 1126 */;
	struct usb_cdc_call_mgmt_descriptor *cocci_id/* drivers/usb/class/cdc-acm.c 1121 */;
	struct usb_cdc_union_desc *cocci_id/* drivers/usb/class/cdc-acm.c 1120 */;
	const struct usb_device_id *cocci_id/* drivers/usb/class/cdc-acm.c 1118 */;
	void *cocci_id/* drivers/usb/class/cdc-acm.c 111 */;
	const struct tty_port_operations cocci_id/* drivers/usb/class/cdc-acm.c 1065 */;
	struct usb_cdc_line_coding cocci_id/* drivers/usb/class/cdc-acm.c 1018 */;
	struct ktermios *cocci_id/* drivers/usb/class/cdc-acm.c 1014 */;
}
