cocci_test_suite() {
	struct fsi_master_acf {
		struct fsi_master master;
		struct device *dev;
		struct regmap *scu;
		struct mutex lock;
		struct gpio_desc *gpio_clk;
		struct gpio_desc *gpio_data;
		struct gpio_desc *gpio_trans;
		struct gpio_desc *gpio_enable;
		struct gpio_desc *gpio_mux;
		uint16_t gpio_clk_vreg;
		uint16_t gpio_clk_dreg;
		uint16_t gpio_dat_vreg;
		uint16_t gpio_dat_dreg;
		uint16_t gpio_tra_vreg;
		uint16_t gpio_tra_dreg;
		uint8_t gpio_clk_bit;
		uint8_t gpio_dat_bit;
		uint8_t gpio_tra_bit;
		uint32_t cf_mem_addr;
		size_t cf_mem_size;
		void __iomem *cf_mem;
		void __iomem *cvic;
		struct gen_pool *sram_pool;
		void __iomem *sram;
		bool is_ast2500;
		bool external_mode;
		bool trace_enabled;
		uint32_t last_addr;
		uint8_t t_send_delay;
		uint8_t t_echo_delay;
		uint32_t cvic_sw_irq;
	} cocci_id/* drivers/fsi/fsi-master-ast-cf.c 87 */;
	const u8 *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 833 */;
	uint16_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 832 */;
	const struct firmware *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 831 */;
	struct fsi_master *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 666 */;
	struct fsi_msg cocci_id/* drivers/fsi/fsi-master-ast-cf.c 602 */;
	u8 *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 517 */;
	__be16 *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 515 */;
	__be32 *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 513 */;
	char *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 443 */;
	char cocci_id/* drivers/fsi/fsi-master-ast-cf.c 442 */[52];
	uint8_t *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 268 */;
	bool cocci_id/* drivers/fsi/fsi-master-ast-cf.c 214 */;
	int cocci_id/* drivers/fsi/fsi-master-ast-cf.c 213 */;
	const void *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 211 */;
	uint32_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 210 */;
	size_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 210 */;
	uint8_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 209 */;
	struct fsi_msg *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 209 */;
	struct fsi_master_acf *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 208 */;
	void cocci_id/* drivers/fsi/fsi-master-ast-cf.c 208 */;
	int32_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 170 */;
	uint32_t *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 167 */;
	struct platform_driver cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1430 */;
	const struct of_device_id cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1424 */[];
	void __iomem *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1349 */;
	uint64_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 130 */;
	struct fsi_msg {
		uint64_t msg;
		uint8_t bits;
	} cocci_id/* drivers/fsi/fsi-master-ast-cf.c 122 */;
	struct resource cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1218 */;
	struct gpio_desc *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1217 */;
	struct genpool_data_fixed cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1215 */;
	struct device_node *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1214 */;
	struct platform_device *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1212 */;
	const struct aspeed_gpio_copro_ops cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1207 */;
	struct fsi_master_acf cocci_id/* drivers/fsi/fsi-master-ast-cf.c 120 */;
	void *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1176 */;
	unsigned int cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1151 */;
	u8 cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1131 */;
	unsigned long cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1093 */;
	const char *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1090 */;
	struct device_attribute *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1081 */;
	struct device *cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1080 */;
	ssize_t cocci_id/* drivers/fsi/fsi-master-ast-cf.c 1080 */;
}
