cocci_test_suite() {
	struct vme_dma_pattern *cocci_id/* drivers/vme/vme.c 979 */;
	dma_addr_t *cocci_id/* drivers/vme/vme.c 87 */;
	void *cocci_id/* drivers/vme/vme.c 86 */;
	size_t cocci_id/* drivers/vme/vme.c 86 */;
	struct vme_master_resource *cocci_id/* drivers/vme/vme.c 832 */;
	unsigned long cocci_id/* drivers/vme/vme.c 802 */;
	phys_addr_t cocci_id/* drivers/vme/vme.c 801 */;
	struct vm_area_struct *cocci_id/* drivers/vme/vme.c 798 */;
	loff_t cocci_id/* drivers/vme/vme.c 665 */;
	ssize_t cocci_id/* drivers/vme/vme.c 664 */;
	struct vme_lm_resource cocci_id/* drivers/vme/vme.c 65 */;
	int *cocci_id/* drivers/vme/vme.c 625 */;
	struct vme_dma_resource cocci_id/* drivers/vme/vme.c 61 */;
	struct vme_slave_resource cocci_id/* drivers/vme/vme.c 57 */;
	struct vme_master_resource cocci_id/* drivers/vme/vme.c 53 */;
	struct vme_resource *cocci_id/* drivers/vme/vme.c 48 */;
	struct vme_slave_resource *cocci_id/* drivers/vme/vme.c 452 */;
	struct vme_dev cocci_id/* drivers/vme/vme.c 42 */;
	struct device *cocci_id/* drivers/vme/vme.c 40 */;
	int __init cocci_id/* drivers/vme/vme.c 38 */(void);
	int __init cocci_id/* drivers/vme/vme.c 2022 */;
	struct bus_type cocci_id/* drivers/vme/vme.c 2014 */;
	struct vme_driver cocci_id/* drivers/vme/vme.c 1977 */;
	struct device_driver *cocci_id/* drivers/vme/vme.c 1973 */;
	struct vme_bridge *cocci_id/* drivers/vme/vme.c 1900 */;
	struct vme_driver *cocci_id/* drivers/vme/vme.c 1898 */;
	unsigned int cocci_id/* drivers/vme/vme.c 1898 */;
	int cocci_id/* drivers/vme/vme.c 1898 */;
	struct vme_dev *cocci_id/* drivers/vme/vme.c 1857 */;
	struct vme_lm_resource *cocci_id/* drivers/vme/vme.c 1649 */;
	void (*cocci_id/* drivers/vme/vme.c 1646 */)(void *);
	u32 *cocci_id/* drivers/vme/vme.c 1609 */;
	unsigned long long *cocci_id/* drivers/vme/vme.c 1608 */;
	void (*cocci_id/* drivers/vme/vme.c 1313 */)(int, int, void *);
	struct vme_error_handler cocci_id/* drivers/vme/vme.c 1263 */;
	u32 cocci_id/* drivers/vme/vme.c 1260 */;
	struct vme_error_handler *cocci_id/* drivers/vme/vme.c 1258 */;
	struct list_head *cocci_id/* drivers/vme/vme.c 1257 */;
	unsigned long long cocci_id/* drivers/vme/vme.c 1255 */;
	void cocci_id/* drivers/vme/vme.c 1254 */;
	struct vme_dma_resource *cocci_id/* drivers/vme/vme.c 1224 */;
	struct vme_dma_list *cocci_id/* drivers/vme/vme.c 1118 */;
	struct vme_dma_attr *cocci_id/* drivers/vme/vme.c 1094 */;
	struct vme_dma_vme *cocci_id/* drivers/vme/vme.c 1060 */;
	struct vme_dma_pci *cocci_id/* drivers/vme/vme.c 1017 */;
	dma_addr_t cocci_id/* drivers/vme/vme.c 1014 */;
}
