cocci_test_suite() {
	void cocci_id/* drivers/staging/qlge/qlge_main.c 99 */(struct net_device *);
	const struct pci_device_id cocci_id/* drivers/staging/qlge/qlge_main.c 89 */[];
	u64 cocci_id/* drivers/staging/qlge/qlge_main.c 868 */;
	u64 *cocci_id/* drivers/staging/qlge/qlge_main.c 854 */;
	struct flash_params_8012 cocci_id/* drivers/staging/qlge/qlge_main.c 765 */;
	struct flash_params_8000 cocci_id/* drivers/staging/qlge/qlge_main.c 713 */;
	u8 cocci_id/* drivers/staging/qlge/qlge_main.c 700 */[6];
	__le32 *cocci_id/* drivers/staging/qlge/qlge_main.c 698 */;
	__le16 *cocci_id/* drivers/staging/qlge/qlge_main.c 652 */;
	const char *cocci_id/* drivers/staging/qlge/qlge_main.c 648 */;
	struct intr_context *cocci_id/* drivers/staging/qlge/qlge_main.c 635 */;
	const u32 cocci_id/* drivers/staging/qlge/qlge_main.c 54 */;
	struct pci_driver cocci_id/* drivers/staging/qlge/qlge_main.c 4851 */;
	pm_message_t cocci_id/* drivers/staging/qlge/qlge_main.c 4787 */;
	const struct pci_error_handlers cocci_id/* drivers/staging/qlge/qlge_main.c 4781 */;
	enum pci_channel_state cocci_id/* drivers/staging/qlge/qlge_main.c 4702 */;
	pci_ers_result_t cocci_id/* drivers/staging/qlge/qlge_main.c 4701 */;
	const char cocci_id/* drivers/staging/qlge/qlge_main.c 47 */[];
	netdev_tx_t cocci_id/* drivers/staging/qlge/qlge_main.c 4652 */;
	char cocci_id/* drivers/staging/qlge/qlge_main.c 46 */[];
	const struct pci_device_id *cocci_id/* drivers/staging/qlge/qlge_main.c 4577 */;
	struct timer_list *cocci_id/* drivers/staging/qlge/qlge_main.c 4562 */;
	const struct net_device_ops cocci_id/* drivers/staging/qlge/qlge_main.c 4547 */;
	char *cocci_id/* drivers/staging/qlge/qlge_main.c 454 */;
	char cocci_id/* drivers/staging/qlge/qlge_main.c 453 */[ETH_ALEN];
	struct ql_mpi_coredump cocci_id/* drivers/staging/qlge/qlge_main.c 4487 */;
	struct pci_dev *cocci_id/* drivers/staging/qlge/qlge_main.c 4409 */;
	const struct nic_operations cocci_id/* drivers/staging/qlge/qlge_main.c 4318 */;
	struct ql_adapter cocci_id/* drivers/staging/qlge/qlge_main.c 4286 */;
	struct work_struct *cocci_id/* drivers/staging/qlge/qlge_main.c 4283 */;
	struct sockaddr *cocci_id/* drivers/staging/qlge/qlge_main.c 4257 */;
	struct netdev_hw_addr *cocci_id/* drivers/staging/qlge/qlge_main.c 4167 */;
	struct net_device_stats *cocci_id/* drivers/staging/qlge/qlge_main.c 4127 */;
	struct ql_net_rsp_iocb cocci_id/* drivers/staging/qlge/qlge_main.c 4010 */;
	struct ob_mac_iocb_req cocci_id/* drivers/staging/qlge/qlge_main.c 3989 */;
	void *cocci_id/* drivers/staging/qlge/qlge_main.c 3984 */;
	struct net_device *cocci_id/* drivers/staging/qlge/qlge_main.c 3758 */;
	unsigned long cocci_id/* drivers/staging/qlge/qlge_main.c 3716 */;
	struct ricb *cocci_id/* drivers/staging/qlge/qlge_main.c 3469 */;
	const u8 cocci_id/* drivers/staging/qlge/qlge_main.c 3462 */[];
	struct msix_entry cocci_id/* drivers/staging/qlge/qlge_main.c 3175 */;
	struct wqicb *cocci_id/* drivers/staging/qlge/qlge_main.c 3104 */;
	struct cqicb cocci_id/* drivers/staging/qlge/qlge_main.c 3030 */;
	u32 __iomem *cocci_id/* drivers/staging/qlge/qlge_main.c 3017 */;
	__le64 *cocci_id/* drivers/staging/qlge/qlge_main.c 3000 */;
	void __iomem *cocci_id/* drivers/staging/qlge/qlge_main.c 2996 */;
	struct cqicb *cocci_id/* drivers/staging/qlge/qlge_main.c 2991 */;
	struct rx_ring *cocci_id/* drivers/staging/qlge/qlge_main.c 2892 */;
	struct qlge_bq_desc cocci_id/* drivers/staging/qlge/qlge_main.c 2839 */;
	void cocci_id/* drivers/staging/qlge/qlge_main.c 2813 */;
	unsigned int cocci_id/* drivers/staging/qlge/qlge_main.c 2750 */;
	struct qlge_bq *cocci_id/* drivers/staging/qlge/qlge_main.c 2749 */;
	struct tx_ring_desc cocci_id/* drivers/staging/qlge/qlge_main.c 2732 */;
	struct tx_ring *cocci_id/* drivers/staging/qlge/qlge_main.c 2721 */;
	struct ob_mac_iocb_req *cocci_id/* drivers/staging/qlge/qlge_main.c 2694 */;
	struct tx_ring_desc *cocci_id/* drivers/staging/qlge/qlge_main.c 2692 */;
	u32 *cocci_id/* drivers/staging/qlge/qlge_main.c 262 */;
	struct udphdr cocci_id/* drivers/staging/qlge/qlge_main.c 2554 */;
	__sum16 *cocci_id/* drivers/staging/qlge/qlge_main.c 2534 */;
	struct iphdr *cocci_id/* drivers/staging/qlge/qlge_main.c 2533 */;
	struct ob_mac_tso_iocb_req *cocci_id/* drivers/staging/qlge/qlge_main.c 2530 */;
	__be16 cocci_id/* drivers/staging/qlge/qlge_main.c 2492 */;
	irqreturn_t cocci_id/* drivers/staging/qlge/qlge_main.c 2414 */;
	u8 *cocci_id/* drivers/staging/qlge/qlge_main.c 2329 */;
	u32 cocci_id/* drivers/staging/qlge/qlge_main.c 2326 */;
	u16 cocci_id/* drivers/staging/qlge/qlge_main.c 2324 */;
	struct ql_adapter *cocci_id/* drivers/staging/qlge/qlge_main.c 2324 */;
	int cocci_id/* drivers/staging/qlge/qlge_main.c 2324 */;
	netdev_features_t cocci_id/* drivers/staging/qlge/qlge_main.c 2307 */;
	struct rx_ring cocci_id/* drivers/staging/qlge/qlge_main.c 2215 */;
	struct napi_struct *cocci_id/* drivers/staging/qlge/qlge_main.c 2213 */;
	struct ib_ae_iocb_rsp *cocci_id/* drivers/staging/qlge/qlge_main.c 2193 */;
	struct ql_net_rsp_iocb *cocci_id/* drivers/staging/qlge/qlge_main.c 2173 */;
	struct ob_mac_iocb_rsp *cocci_id/* drivers/staging/qlge/qlge_main.c 2125 */;
	size_t cocci_id/* drivers/staging/qlge/qlge_main.c 1706 */;
	struct qlge_bq_desc *cocci_id/* drivers/staging/qlge/qlge_main.c 1704 */;
	struct ib_mac_iocb_rsp *cocci_id/* drivers/staging/qlge/qlge_main.c 1700 */;
	struct sk_buff *cocci_id/* drivers/staging/qlge/qlge_main.c 1698 */;
	u16 *cocci_id/* drivers/staging/qlge/qlge_main.c 1422 */;
	size_t *cocci_id/* drivers/staging/qlge/qlge_main.c 1420 */;
	struct nic_stats *cocci_id/* drivers/staging/qlge/qlge_main.c 1386 */;
	u8 cocci_id/* drivers/staging/qlge/qlge_main.c 1383 */;
	struct tx_buf_desc cocci_id/* drivers/staging/qlge/qlge_main.c 1337 */;
	struct oal cocci_id/* drivers/staging/qlge/qlge_main.c 1320 */;
	skb_frag_t *cocci_id/* drivers/staging/qlge/qlge_main.c 1297 */;
	struct tx_buf_desc *cocci_id/* drivers/staging/qlge/qlge_main.c 1263 */;
	dma_addr_t cocci_id/* drivers/staging/qlge/qlge_main.c 1261 */;
	bool cocci_id/* drivers/staging/qlge/qlge_main.c 1170 */;
	gfp_t cocci_id/* drivers/staging/qlge/qlge_main.c 1167 */;
	struct page *cocci_id/* drivers/staging/qlge/qlge_main.c 1069 */;
	struct qlge_page_chunk *cocci_id/* drivers/staging/qlge/qlge_main.c 1066 */;
	const char *const cocci_id/* drivers/staging/qlge/qlge_main.c 1023 */[];
	int cocci_id/* drivers/staging/qlge/qlge_main.c 100 */(struct ql_adapter *);
}
