cocci_test_suite() {
	char cocci_id/* drivers/staging/fbtft/fbtft-core.c 999 */[16];
	char cocci_id/* drivers/staging/fbtft/fbtft-core.c 998 */[128];
	int cocci_id/* drivers/staging/fbtft/fbtft-core.c 997 */[64];
	u32 cocci_id/* drivers/staging/fbtft/fbtft-core.c 908 */;
	char cocci_id/* drivers/staging/fbtft/fbtft-core.c 793 */[50];
	struct gpio_desc **cocci_id/* drivers/staging/fbtft/fbtft-core.c 76 */;
	struct fbtft_par cocci_id/* drivers/staging/fbtft/fbtft-core.c 645 */;
	struct fb_deferred_io cocci_id/* drivers/staging/fbtft/fbtft-core.c 627 */;
	struct fb_ops cocci_id/* drivers/staging/fbtft/fbtft-core.c 623 */;
	char *cocci_id/* drivers/staging/fbtft/fbtft-core.c 57 */;
	char cocci_id/* drivers/staging/fbtft/fbtft-core.c 56 */[512];
	const s16 *cocci_id/* drivers/staging/fbtft/fbtft-core.c 559 */;
	u8 *cocci_id/* drivers/staging/fbtft/fbtft-core.c 550 */;
	va_list cocci_id/* drivers/staging/fbtft/fbtft-core.c 55 */;
	struct fb_deferred_io *cocci_id/* drivers/staging/fbtft/fbtft-core.c 549 */;
	struct fb_ops *cocci_id/* drivers/staging/fbtft/fbtft-core.c 548 */;
	struct fbtft_platform_data *cocci_id/* drivers/staging/fbtft/fbtft-core.c 544 */;
	struct device *cocci_id/* drivers/staging/fbtft/fbtft-core.c 543 */;
	struct fbtft_display *cocci_id/* drivers/staging/fbtft/fbtft-core.c 542 */;
	const char *cocci_id/* drivers/staging/fbtft/fbtft-core.c 53 */;
	void *cocci_id/* drivers/staging/fbtft/fbtft-core.c 53 */;
	size_t cocci_id/* drivers/staging/fbtft/fbtft-core.c 53 */;
	const struct device *cocci_id/* drivers/staging/fbtft/fbtft-core.c 52 */;
	void cocci_id/* drivers/staging/fbtft/fbtft-core.c 52 */;
	struct fbtft_ops *cocci_id/* drivers/staging/fbtft/fbtft-core.c 485 */;
	u32 *cocci_id/* drivers/staging/fbtft/fbtft-core.c 446 */;
	struct fb_bitfield *cocci_id/* drivers/staging/fbtft/fbtft-core.c 425 */;
	unsigned int cocci_id/* drivers/staging/fbtft/fbtft-core.c 425 */;
	loff_t *cocci_id/* drivers/staging/fbtft/fbtft-core.c 409 */;
	const char __user *cocci_id/* drivers/staging/fbtft/fbtft-core.c 408 */;
	ssize_t cocci_id/* drivers/staging/fbtft/fbtft-core.c 408 */;
	const struct fb_image *cocci_id/* drivers/staging/fbtft/fbtft-core.c 396 */;
	const struct fb_copyarea *cocci_id/* drivers/staging/fbtft/fbtft-core.c 383 */;
	const struct fb_fillrect *cocci_id/* drivers/staging/fbtft/fbtft-core.c 370 */;
	struct page *cocci_id/* drivers/staging/fbtft/fbtft-core.c 335 */;
	struct list_head *cocci_id/* drivers/staging/fbtft/fbtft-core.c 331 */;
	struct fb_info *cocci_id/* drivers/staging/fbtft/fbtft-core.c 331 */;
	unsigned long cocci_id/* drivers/staging/fbtft/fbtft-core.c 33 */;
	long cocci_id/* drivers/staging/fbtft/fbtft-core.c 241 */;
	ktime_t cocci_id/* drivers/staging/fbtft/fbtft-core.c 240 */;
	struct backlight_properties cocci_id/* drivers/staging/fbtft/fbtft-core.c 178 */;
	const struct backlight_ops cocci_id/* drivers/staging/fbtft/fbtft-core.c 170 */;
	struct backlight_device *cocci_id/* drivers/staging/fbtft/fbtft-core.c 155 */;
	int cocci_id/* drivers/staging/fbtft/fbtft-core.c 155 */;
	bool cocci_id/* drivers/staging/fbtft/fbtft-core.c 140 */;
	struct fbtft_par *cocci_id/* drivers/staging/fbtft/fbtft-core.c 139 */;
	struct platform_device *cocci_id/* drivers/staging/fbtft/fbtft-core.c 1209 */;
	struct spi_device *cocci_id/* drivers/staging/fbtft/fbtft-core.c 1208 */;
	const char **cocci_id/* drivers/staging/fbtft/fbtft-core.c 1184 */;
}
