cocci_test_suite() {
	struct hif_mib_set_association_mode cocci_id/* drivers/staging/wfx/sta.c 966 */;
	struct ieee80211_sta *cocci_id/* drivers/staging/wfx/sta.c 965 */;
	struct sk_buff *cocci_id/* drivers/staging/wfx/sta.c 96 */;
	const struct wfx_ht_info *cocci_id/* drivers/staging/wfx/sta.c 955 */;
	void *cocci_id/* drivers/staging/wfx/sta.c 928 */;
	struct hif_mib_template_frame *cocci_id/* drivers/staging/wfx/sta.c 902 */;
	struct ieee80211_mgmt *cocci_id/* drivers/staging/wfx/sta.c 901 */;
	struct hif_req_start cocci_id/* drivers/staging/wfx/sta.c 842 */;
	struct hif_ie_flags cocci_id/* drivers/staging/wfx/sta.c 824 */;
	u8 cocci_id/* drivers/staging/wfx/sta.c 823 */[3];
	struct wfx_link_entry *cocci_id/* drivers/staging/wfx/sta.c 772 */;
	struct hif_req_join cocci_id/* drivers/staging/wfx/sta.c 653 */;
	struct cfg80211_bss *cocci_id/* drivers/staging/wfx/sta.c 652 */;
	const u8 *cocci_id/* drivers/staging/wfx/sta.c 650 */;
	const u16 *cocci_id/* drivers/staging/wfx/sta.c 622 */;
	const int cocci_id/* drivers/staging/wfx/sta.c 619 */;
	struct wfx_vif cocci_id/* drivers/staging/wfx/sta.c 539 */;
	struct work_struct *cocci_id/* drivers/staging/wfx/sta.c 537 */;
	u8 cocci_id/* drivers/staging/wfx/sta.c 470 */;
	struct wfx_hif_event *cocci_id/* drivers/staging/wfx/sta.c 43 */;
	bool cocci_id/* drivers/staging/wfx/sta.c 417 */;
	struct wfx_dev *cocci_id/* drivers/staging/wfx/sta.c 417 */;
	int cocci_id/* drivers/staging/wfx/sta.c 417 */;
	struct list_head *cocci_id/* drivers/staging/wfx/sta.c 41 */;
	void cocci_id/* drivers/staging/wfx/sta.c 41 */;
	struct hif_req_set_pm_mode cocci_id/* drivers/staging/wfx/sta.c 376 */;
	const struct hif_req_set_pm_mode *cocci_id/* drivers/staging/wfx/sta.c 374 */;
	u16 *cocci_id/* drivers/staging/wfx/sta.c 342 */;
	struct hif_req_edca_queue_params *cocci_id/* drivers/staging/wfx/sta.c 337 */;
	u16 cocci_id/* drivers/staging/wfx/sta.c 330 */;
	const struct ieee80211_tx_queue_params *cocci_id/* drivers/staging/wfx/sta.c 330 */;
	u64 cocci_id/* drivers/staging/wfx/sta.c 311 */;
	unsigned int *cocci_id/* drivers/staging/wfx/sta.c 310 */;
	unsigned int cocci_id/* drivers/staging/wfx/sta.c 309 */;
	struct netdev_hw_addr *cocci_id/* drivers/staging/wfx/sta.c 284 */;
	struct netdev_hw_addr_list *cocci_id/* drivers/staging/wfx/sta.c 281 */;
	struct ieee80211_supported_band *cocci_id/* drivers/staging/wfx/sta.c 28 */;
	struct hif_ie_table_entry cocci_id/* drivers/staging/wfx/sta.c 220 */[];
	struct hif_mib_bcn_filter_enable cocci_id/* drivers/staging/wfx/sta.c 219 */;
	struct hif_mib_uc_mc_bc_data_frame_condition cocci_id/* drivers/staging/wfx/sta.c 167 */;
	struct hif_mib_mac_addr_data_frame_condition cocci_id/* drivers/staging/wfx/sta.c 166 */;
	struct hif_mib_set_data_filtering cocci_id/* drivers/staging/wfx/sta.c 165 */;
	struct hif_mib_config_data_filter cocci_id/* drivers/staging/wfx/sta.c 164 */;
	struct wfx_grp_addr_table *cocci_id/* drivers/staging/wfx/sta.c 161 */;
	struct hif_req_edca_queue_params cocci_id/* drivers/staging/wfx/sta.c 1471 */[];
	struct wfx_vif *cocci_id/* drivers/staging/wfx/sta.c 1468 */;
	struct ieee80211_vif *cocci_id/* drivers/staging/wfx/sta.c 1464 */;
	struct ieee80211_conf *cocci_id/* drivers/staging/wfx/sta.c 1418 */;
	struct ieee80211_channel *cocci_id/* drivers/staging/wfx/sta.c 1394 */;
	struct ieee80211_chanctx_conf *cocci_id/* drivers/staging/wfx/sta.c 1374 */;
	struct ieee80211_hw *cocci_id/* drivers/staging/wfx/sta.c 1373 */;
	struct hif_ind_suspend_resume_tx *cocci_id/* drivers/staging/wfx/sta.c 1345 */;
	struct ieee80211_ampdu_params *cocci_id/* drivers/staging/wfx/sta.c 1331 */;
	struct timer_list *cocci_id/* drivers/staging/wfx/sta.c 1317 */;
	long cocci_id/* drivers/staging/wfx/sta.c 1291 */;
	struct wfx_sta_priv *cocci_id/* drivers/staging/wfx/sta.c 1280 */;
	u8 *cocci_id/* drivers/staging/wfx/sta.c 1240 */;
	enum sta_notify_cmd cocci_id/* drivers/staging/wfx/sta.c 1186 */;
	const struct wfx_edca_params *cocci_id/* drivers/staging/wfx/sta.c 116 */;
	struct hif_mib_rcpi_rssi_threshold cocci_id/* drivers/staging/wfx/sta.c 1146 */;
	struct hif_mib_arp_ip_addr_table cocci_id/* drivers/staging/wfx/sta.c 1037 */;
	u32 cocci_id/* drivers/staging/wfx/sta.c 1025 */;
	struct ieee80211_bss_conf *cocci_id/* drivers/staging/wfx/sta.c 1024 */;
}
