cocci_test_suite() {
	const void __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 876 */;
	struct vchiq_create_service cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 871 */;
	struct user_service {
		struct vchiq_service *service;
		void *userdata;
		struct vchiq_instance *instance;
		char is_vchi;
		char dequeue_pending;
		char close_pending;
		int message_available_pos;
		int msg_insert;
		int msg_remove;
		struct completion insert_event;
		struct completion remove_event;
		struct completion close_event;
		struct vchiq_header *msg_queue[MSG_QUEUE_SIZE];
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 84 */;
	void cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 82 */(struct timer_list *t);
	struct vchiq_io_copy_callback_context cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 780 */;
	struct vchiq_element *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 777 */;
	struct vchiq_io_copy_callback_context *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 734 */;
	size_t cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 732 */;
	ssize_t cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 731 */;
	struct vchiq_io_copy_callback_context {
		struct vchiq_element *element;
		size_t element_offset;
		unsigned long elements_to_go;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 725 */;
	void cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 708 */;
	unsigned long cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 614 */;
	bool cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 597 */;
	struct vchiq_service *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 595 */;
	unsigned int cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 587 */;
	int cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 524 */;
	struct vchiq_completion_data *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 523 */;
	void *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 521 */;
	struct vchiq_header *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 520 */;
	struct user_service *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 520 */;
	enum vchiq_reason cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 519 */;
	struct vchiq_instance *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 519 */;
	enum vchiq_status cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 518 */;
	struct bulk_waiter_node cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 477 */;
	struct vchiq_bulk *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 459 */;
	struct bulk_waiter_node *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 439 */;
	enum vchiq_bulk_dir cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 434 */;
	enum vchiq_bulk_mode cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 410 */;
	const void *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 384 */;
	void __exit cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3321 */;
	int __init cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3287 */;
	struct platform_driver cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3278 */;
	struct device *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3207 */;
	struct vchiq_drvdata *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3206 */;
	const struct of_device_id *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3205 */;
	struct device_node *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3204 */;
	struct platform_device_info cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3183 */;
	const struct of_device_id cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3173 */[];
	char cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3144 */[16];
	enum vchiq_connstate cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3140 */;
	unsigned int *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 307 */;
	const struct vchiq_service_params *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 306 */;
	struct service_data_struct *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3018 */;
	struct service_data_struct {
		int fourcc;
		int clientid;
		int use_count;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 3008 */;
	struct timer_list *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2970 */;
	struct vchiq_debugfs_node *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2922 */;
	int *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2835 */;
	enum USE_TYPE_E cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2698 */;
	struct vchiq_arm_state *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2559 */;
	struct vchiq_state *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2557 */;
	enum vc_resume_status cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2509 */;
	enum vc_suspend_status cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2472 */;
	struct vchiq_service_params cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2303 */;
	const struct file_operations cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2245 */;
	struct dump_context cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2214 */;
	loff_t *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2212 */;
	char __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2211 */;
	char cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2125 */[80];
	char cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2107 */;
	struct dump_context *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2077 */;
	const char *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 2075 */;
	struct inode *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1919 */;
	struct file *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1896 */;
	long cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1895 */;
	struct vchiq_get_config32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1884 */;
	struct vchiq_get_config __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1876 */;
	struct vchiq_get_config32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1869 */;
	struct vchiq_get_config32 {
		unsigned int config_size;
		compat_uptr_t pconfig;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1863 */;
	struct vchiq_dequeue_message32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1849 */;
	struct vchiq_dequeue_message __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1841 */;
	struct vchiq_dequeue_message32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1834 */;
	struct vchiq_dequeue_message32 {
		unsigned int handle;
		int blocking;
		unsigned int bufsize;
		compat_uptr_t buf;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1826 */;
	struct vchiq_await_completion32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1816 */;
	struct vchiq_instance **cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 180 */;
	enum vchiq_status cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 175 */(unsigned int handle,
													  void *data,
													  unsigned int size,
													  enum vchiq_bulk_dir dir);
	struct vchiq_completion_data32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1713 */;
	void *__user*cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1700 */;
	void __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1699 */;
	compat_uptr_t cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1698 */;
	unsigned int __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1696 */;
	struct vchiq_completion_data32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1695 */;
	struct vchiq_completion_data cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1693 */;
	struct vchiq_completion_data __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1692 */;
	struct vchiq_await_completion __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1691 */;
	struct vchiq_await_completion32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1684 */;
	struct vchiq_await_completion32 {
		unsigned int count;
		compat_uptr_t buf;
		unsigned int msgbufsize;
		unsigned int msgbufcount;
		compat_uptr_t msgbufs;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1675 */;
	struct vchiq_completion_data32 {
		enum vchiq_reason reason;
		compat_uptr_t header;
		compat_uptr_t service_userdata;
		compat_uptr_t bulk_userdata;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1668 */;
	struct vchiq_queue_bulk_transfer32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1629 */;
	struct vchiq_queue_bulk_transfer __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1627 */;
	struct vchiq_queue_bulk_transfer32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1618 */;
	struct vchiq_queue_bulk_transfer32 {
		unsigned int handle;
		compat_uptr_t data;
		unsigned int size;
		compat_uptr_t userdata;
		enum vchiq_bulk_mode mode;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1609 */;
	struct vchiq_element32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1585 */[MAX_ELEMENTS];
	struct vchiq_queue_message32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1566 */;
	struct vchiq_element __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1561 */;
	struct vchiq_queue_message __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1560 */;
	struct vchiq_queue_message32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1553 */;
	struct vchiq_queue_message32 {
		unsigned int handle;
		unsigned int count;
		compat_uptr_t elements;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1546 */;
	struct vchiq_element32 {
		compat_uptr_t data;
		unsigned int size;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1541 */;
	const char *constcocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 151 */[];
	struct vchiq_create_service32 __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1500 */;
	struct vchiq_create_service __user *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1499 */;
	struct vchiq_create_service32 cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1491 */;
	struct vchiq_create_service32 {
		struct vchiq_service_params32 params;
		int is_open;
		int is_vchi;
		unsigned int handle;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1483 */;
	struct vchiq_service_params32 {
		int fourcc;
		compat_uptr_t callback;
		compat_uptr_t userdata;
		short version;
		short version_min;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1475 */;
	struct vchiq_drvdata cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 143 */;
	struct platform_device *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 141 */;
	struct vchiq_set_service_option cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1398 */;
	struct class *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 138 */;
	struct vchiq_config cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1378 */;
	struct vchiq_get_config cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1377 */;
	struct vchiq_state cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 137 */;
	dev_t cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 136 */;
	struct cdev cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 135 */;
	struct vchiq_dequeue_message cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1289 */;
	struct dump_context {
		char __user *buf;
		size_t actual;
		size_t space;
		loff_t offset;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 128 */;
	struct vchiq_await_completion *cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1273 */;
	struct vchiq_header cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1200 */;
	struct vchiq_await_completion cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1130 */;
	const enum vchiq_bulk_mode cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1110 */;
	struct vchiq_instance {
		struct vchiq_state *state;
		struct vchiq_completion_data completions[MAX_COMPLETIONS];
		int completion_insert;
		int completion_remove;
		struct completion insert_event;
		struct completion remove_event;
		struct mutex completion_mutex;
		int connected;
		int closing;
		int pid;
		int mark;
		int use_close_delivered;
		int trace;
		struct list_head bulk_waiter_list;
		struct mutex bulk_waiter_list_mutex;
		struct vchiq_debugfs_node debugfs_node;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 106 */;
	struct vchiq_queue_bulk_transfer cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1042 */;
	struct vchiq_element cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1029 */;
	struct vchiq_element cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1026 */[MAX_ELEMENTS];
	struct vchiq_queue_message cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 1014 */;
	struct bulk_waiter_node {
		struct bulk_waiter bulk_waiter;
		int pid;
		struct list_head list;
	} cocci_id/* drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c 100 */;
}
