cocci_test_suite() {
	u8 *cocci_id/* drivers/staging/uwb/drp.c 97 */;
	struct uwb_rc_cmd_set_drp_ie *cocci_id/* drivers/staging/uwb/drp.c 93 */;
	struct uwb_rc_evt_drp cocci_id/* drivers/staging/uwb/drp.c 810 */;
	struct uwb_dev_addr cocci_id/* drivers/staging/uwb/drp.c 798 */;
	struct uwb_event *cocci_id/* drivers/staging/uwb/drp.c 792 */;
	void *cocci_id/* drivers/staging/uwb/drp.c 734 */;
	struct uwb_ie_hdr *cocci_id/* drivers/staging/uwb/drp.c 733 */;
	size_t cocci_id/* drivers/staging/uwb/drp.c 730 */;
	struct uwb_ie_drp_avail *cocci_id/* drivers/staging/uwb/drp.c 718 */;
	struct uwb_dev *cocci_id/* drivers/staging/uwb/drp.c 717 */;
	struct uwb_mas_bm cocci_id/* drivers/staging/uwb/drp.c 609 */;
	struct device *cocci_id/* drivers/staging/uwb/drp.c 608 */;
	struct timer_list *cocci_id/* drivers/staging/uwb/drp.c 595 */;
	unsigned long cocci_id/* drivers/staging/uwb/drp.c 574 */;
	struct uwb_cnflt_alien cocci_id/* drivers/staging/uwb/drp.c 569 */;
	struct work_struct *cocci_id/* drivers/staging/uwb/drp.c 566 */;
	unsigned cocci_id/* drivers/staging/uwb/drp.c 562 */;
	struct uwb_cnflt_alien *cocci_id/* drivers/staging/uwb/drp.c 560 */;
	enum uwb_drp_reason cocci_id/* drivers/staging/uwb/drp.c 523 */;
	struct uwb_rc_evt_set_drp_ie *cocci_id/* drivers/staging/uwb/drp.c 50 */;
	struct uwb_rceb *cocci_id/* drivers/staging/uwb/drp.c 48 */;
	ssize_t cocci_id/* drivers/staging/uwb/drp.c 48 */;
	struct uwb_rc_evt_drp *cocci_id/* drivers/staging/uwb/drp.c 365 */;
	struct uwb_rsv_move *cocci_id/* drivers/staging/uwb/drp.c 288 */;
	struct uwb_drp_backoff_win *cocci_id/* drivers/staging/uwb/drp.c 287 */;
	struct uwb_rc *cocci_id/* drivers/staging/uwb/drp.c 286 */;
	struct uwb_mas_bm *cocci_id/* drivers/staging/uwb/drp.c 284 */;
	bool cocci_id/* drivers/staging/uwb/drp.c 283 */;
	void cocci_id/* drivers/staging/uwb/drp.c 282 */;
	enum uwb_drp_conflict_action{UWB_DRP_CONFLICT_MANTAIN=0, UWB_DRP_CONFLICT_ACT1, UWB_DRP_CONFLICT_ACT2, UWB_DRP_CONFLICT_ACT3,} cocci_id/* drivers/staging/uwb/drp.c 18 */;
	struct uwb_rsv *cocci_id/* drivers/staging/uwb/drp.c 162 */;
	struct uwb_ie_drp *cocci_id/* drivers/staging/uwb/drp.c 161 */;
	int cocci_id/* drivers/staging/uwb/drp.c 161 */;
	struct uwb_ie_drp_avail cocci_id/* drivers/staging/uwb/drp.c 124 */;
}
