cocci_test_suite() {
	unsigned int *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 724 */;
	unsigned long cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 711 */;
	struct comedi_insn *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 710 */;
	const unsigned char cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 523 */[7];
	const struct comedi_lrange cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 510 */;
	const unsigned int cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 501 */[8];
	struct pci230_private {
		spinlock_t isr_spinlock;
		spinlock_t res_spinlock;
		spinlock_t ai_stop_spinlock;
		spinlock_t ao_stop_spinlock;
		unsigned long daqio;
		int intr_cpuid;
		unsigned short hwver;
		unsigned short adccon;
		unsigned short daccon;
		unsigned short adcfifothresh;
		unsigned short adcg;
		unsigned char ier;
		unsigned char res_owned[NUM_OWNERS];
		unsigned int intr_running:1;
		unsigned int ai_bipolar:1;
		unsigned int ao_bipolar:1;
		unsigned int ai_cmd_started:1;
		unsigned int ao_cmd_started:1;
	} cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 479 */;
	const struct pci230_board cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 450 */[];
	struct pci230_board {
		const char *name;
		unsigned short id;
		unsigned char ai_bits;
		unsigned char ao_bits;
		unsigned char min_hwver;
		unsigned int have_dio:1;
	} cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 441 */;
	enum{OWNER_AICMD, OWNER_AOCMD, NUM_OWNERS,} cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 421 */;
	enum{RES_Z2CT0=BIT(0), RES_Z2CT1=BIT(1), RES_Z2CT2=BIT(2),} cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 415 */;
	struct pci_driver cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2565 */;
	const struct pci_device_id cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2558 */[];
	const struct pci_device_id *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2552 */;
	struct pci_dev *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2551 */;
	int cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2551 */;
	struct comedi_driver cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2544 */;
	irqreturn_t cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2281 */;
	void *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2281 */;
	struct comedi_subdevice *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2274 */;
	struct comedi_device *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2273 */;
	u64 cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2246 */;
	struct comedi_async *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2087 */;
	unsigned char cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2084 */;
	unsigned short cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 2083 */;
	void cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 1859 */;
	const struct pci230_board *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 1509 */;
	bool cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 1412 */;
	unsigned int cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 1408 */;
	struct pci230_private *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 1407 */;
	struct comedi_cmd *cocci_id/* drivers/staging/comedi/drivers/amplc_pci230.c 1405 */;
}
