cocci_test_suite() {
	struct video_device *cocci_id/* drivers/staging/most/video/video.c 72 */;
	struct mbo cocci_id/* drivers/staging/most/video/video.c 66 */;
	bool cocci_id/* drivers/staging/most/video/video.c 59 */;
	struct list_head cocci_id/* drivers/staging/most/video/video.c 56 */;
	void __exit cocci_id/* drivers/staging/most/video/video.c 553 */;
	void cocci_id/* drivers/staging/most/video/video.c 553 */;
	int __init cocci_id/* drivers/staging/most/video/video.c 538 */;
	struct most_video_dev *cocci_id/* drivers/staging/most/video/video.c 513 */;
	struct most_interface *cocci_id/* drivers/staging/most/video/video.c 510 */;
	int cocci_id/* drivers/staging/most/video/video.c 510 */;
	struct comp_fh {
		struct v4l2_fh fh;
		struct most_video_dev *mdev;
		u32 offs;
	} cocci_id/* drivers/staging/most/video/video.c 49 */;
	struct most_channel_config *cocci_id/* drivers/staging/most/video/video.c 452 */;
	char *cocci_id/* drivers/staging/most/video/video.c 452 */;
	struct most_video_dev cocci_id/* drivers/staging/most/video/video.c 445 */;
	struct v4l2_device *cocci_id/* drivers/staging/most/video/video.c 442 */;
	unsigned long cocci_id/* drivers/staging/most/video/video.c 388 */;
	struct mbo *cocci_id/* drivers/staging/most/video/video.c 386 */;
	const struct video_device cocci_id/* drivers/staging/most/video/video.c 359 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/staging/most/video/video.c 347 */;
	const struct v4l2_file_operations cocci_id/* drivers/staging/most/video/video.c 338 */;
	unsigned int *cocci_id/* drivers/staging/most/video/video.c 319 */;
	struct v4l2_input *cocci_id/* drivers/staging/most/video/video.c 302 */;
	struct most_video_dev {
		struct most_interface *iface;
		int ch_idx;
		struct list_head list;
		bool mute;
		struct list_head pending_mbos;
		spinlock_t list_lock;
		struct v4l2_device v4l2_dev;
		atomic_t access_ref;
		struct video_device *vdev;
		unsigned int ctrl_input;
		struct mutex lock;
		wait_queue_head_t wait_data;
	} cocci_id/* drivers/staging/most/video/video.c 30 */;
	v4l2_std_id *cocci_id/* drivers/staging/most/video/video.c 295 */;
	struct core_component cocci_id/* drivers/staging/most/video/video.c 28 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/staging/most/video/video.c 257 */;
	void *cocci_id/* drivers/staging/most/video/video.c 256 */;
	struct v4l2_capability *cocci_id/* drivers/staging/most/video/video.c 244 */;
	struct v4l2_format *cocci_id/* drivers/staging/most/video/video.c 230 */;
	unsigned int cocci_id/* drivers/staging/most/video/video.c 229 */;
	__poll_t cocci_id/* drivers/staging/most/video/video.c 202 */;
	poll_table *cocci_id/* drivers/staging/most/video/video.c 202 */;
	const int cocci_id/* drivers/staging/most/video/video.c 176 */;
	struct mbo *const cocci_id/* drivers/staging/most/video/video.c 175 */;
	loff_t *cocci_id/* drivers/staging/most/video/video.c 153 */;
	size_t cocci_id/* drivers/staging/most/video/video.c 153 */;
	char __user *cocci_id/* drivers/staging/most/video/video.c 152 */;
	ssize_t cocci_id/* drivers/staging/most/video/video.c 152 */;
	struct comp_fh *cocci_id/* drivers/staging/most/video/video.c 119 */;
	struct file *cocci_id/* drivers/staging/most/video/video.c 117 */;
}
