cocci_test_suite() {
	unsigned cocci_id/* drivers/hid/hid-logitech-hidpp.c 984 */;
	const u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 860 */;
	u32 cocci_id/* drivers/hid/hid-logitech-hidpp.c 803 */;
	u32 *cocci_id/* drivers/hid/hid-logitech-hidpp.c 777 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 514 */[3];
	unsigned long long cocci_id/* drivers/hid/hid-logitech-hidpp.c 448 */;
	char **cocci_id/* drivers/hid/hid-logitech-hidpp.c 405 */;
	struct hid_driver cocci_id/* drivers/hid/hid-logitech-hidpp.c 3821 */;
	const struct hid_usage_id cocci_id/* drivers/hid/hid-logitech-hidpp.c 3816 */[];
	struct hidpp_device cocci_id/* drivers/hid/hid-logitech-hidpp.c 375 */;
	struct work_struct *cocci_id/* drivers/hid/hid-logitech-hidpp.c 373 */;
	void cocci_id/* drivers/hid/hid-logitech-hidpp.c 373 */;
	const struct hid_device_id cocci_id/* drivers/hid/hid-logitech-hidpp.c 3712 */[];
	struct hidpp_ff_private_data cocci_id/* drivers/hid/hid-logitech-hidpp.c 3542 */;
	const struct hid_device_id *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3536 */;
	struct hid_report cocci_id/* drivers/hid/hid-logitech-hidpp.c 3532 */;
	struct hid_report *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3529 */;
	struct list_head *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3528 */;
	struct hid_report_enum *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3473 */;
	const struct attribute_group cocci_id/* drivers/hid/hid-logitech-hidpp.c 3467 */;
	struct attribute *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3462 */[];
	bool cocci_id/* drivers/hid/hid-logitech-hidpp.c 34 */;
	unsigned long cocci_id/* drivers/hid/hid-logitech-hidpp.c 3222 */;
	struct hidpp_battery *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3220 */;
	enum power_supply_property *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3219 */;
	struct power_supply_desc *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3218 */;
	struct power_supply_config cocci_id/* drivers/hid/hid-logitech-hidpp.c 3217 */;
	atomic_t cocci_id/* drivers/hid/hid-logitech-hidpp.c 3216 */;
	struct hidpp_scroll_counter *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3195 */;
	__s32 cocci_id/* drivers/hid/hid-logitech-hidpp.c 3189 */;
	struct hid_usage *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3189 */;
	struct hid_field *cocci_id/* drivers/hid/hid-logitech-hidpp.c 3188 */;
	unsigned long **cocci_id/* drivers/hid/hid-logitech-hidpp.c 3011 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2918 */[5];
	unsigned int cocci_id/* drivers/hid/hid-logitech-hidpp.c 2895 */;
	char *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2894 */;
	const char cocci_id/* drivers/hid/hid-logitech-hidpp.c 2884 */[];
	unsigned int *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2881 */;
	struct input_dev *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2862 */;
	s8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2784 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2710 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2686 */[HIDPP_AUTOCENTER_PARAMS_LENGTH];
	struct hidpp_report cocci_id/* drivers/hid/hid-logitech-hidpp.c 2685 */;
	struct hidpp_ff_private_data *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2683 */;
	struct k400_private_data cocci_id/* drivers/hid/hid-logitech-hidpp.c 2656 */;
	struct k400_private_data *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2654 */;
	struct hidpp_touchpad_fw_items cocci_id/* drivers/hid/hid-logitech-hidpp.c 2631 */;
	struct k400_private_data {
		u8 feature_index;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 2624 */;
	struct wtp_data cocci_id/* drivers/hid/hid-logitech-hidpp.c 2399 */;
	struct wtp_data *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2397 */;
	u8 *cocci_id/* drivers/hid/hid-logitech-hidpp.c 238 */;
	struct hidpp_touchpad_raw_info cocci_id/* drivers/hid/hid-logitech-hidpp.c 2368 */;
	struct wtp_data {
		u16 x_size,y_size;
		u8 finger_count;
		u8 mt_feature_index;
		u8 button_feature_index;
		u8 maxcontacts;
		bool flip_y;
		unsigned int resolution;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 2193 */;
	struct hidpp_device *cocci_id/* drivers/hid/hid-logitech-hidpp.c 214 */;
	struct hidpp_report *cocci_id/* drivers/hid/hid-logitech-hidpp.c 212 */;
	struct hid_device *cocci_id/* drivers/hid/hid-logitech-hidpp.c 211 */;
	int cocci_id/* drivers/hid/hid-logitech-hidpp.c 211 */;
	struct hid_input cocci_id/* drivers/hid/hid-logitech-hidpp.c 2109 */;
	const u16 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2100 */;
	const struct usb_device_descriptor *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2099 */;
	struct hid_input *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2097 */;
	void cocci_id/* drivers/hid/hid-logitech-hidpp.c 209 */(struct hidpp_device *hidpp_dev);
	struct ff_device *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2081 */;
	const char *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2060 */;
	size_t cocci_id/* drivers/hid/hid-logitech-hidpp.c 2060 */;
	struct device_attribute *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2050 */;
	struct device *cocci_id/* drivers/hid/hid-logitech-hidpp.c 2050 */;
	ssize_t cocci_id/* drivers/hid/hid-logitech-hidpp.c 2050 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2038 */[4];
	u16 cocci_id/* drivers/hid/hid-logitech-hidpp.c 2013 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 1994 */[2];
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 1848 */[20];
	struct ff_effect *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1845 */;
	struct hidpp_ff_work_data *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1820 */;
	struct hidpp_ff_work_data cocci_id/* drivers/hid/hid-logitech-hidpp.c 1752 */;
	const char *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1731 */[];
	const u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 1724 */[];
	const signed short cocci_id/* drivers/hid/hid-logitech-hidpp.c 1702 */[];
	struct hidpp_ff_work_data {
		struct work_struct work;
		struct hidpp_ff_private_data *data;
		int effect_id;
		u8 command;
		u8 params[HIDPP_FF_MAX_PARAMS];
		u8 size;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 1693 */;
	struct hidpp_ff_private_data {
		struct hidpp_device *hidpp;
		u8 feature_index;
		u8 version;
		u16 gain;
		s16 range;
		u8 slot_autocenter;
		u8 num_effects;
		int *effect_ids;
		struct workqueue_struct *wq;
		atomic_t workqueue_size;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 1680 */;
	struct hidpp_device {
		struct hid_device *hid_dev;
		struct input_dev *input;
		struct mutex send_mutex;
		void *send_receive_buf;
		char *name;
		wait_queue_head_t wait;
		int very_long_report_length;
		bool answer_available;
		u8 protocol_major;
		u8 protocol_minor;
		void *private_data;
		struct work_struct work;
		struct kfifo delayed_work_fifo;
		atomic_t connected;
		struct input_dev *delayed_input;
		unsigned long quirks;
		unsigned long capabilities;
		struct hidpp_battery battery;
		struct hidpp_scroll_counter vertical_wheel_counter;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 165 */;
	struct hidpp_touchpad_raw_xy cocci_id/* drivers/hid/hid-logitech-hidpp.c 1628 */;
	struct hidpp_touchpad_raw_xy *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1626 */;
	struct hidpp_touchpad_raw_xy_finger *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1609 */;
	struct hidpp_scroll_counter {
		int wheel_multiplier;
		int remainder;
		int direction;
		unsigned long long last_time;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 158 */;
	struct hidpp_touchpad_raw_info *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1558 */;
	struct hidpp_touchpad_raw_xy {
		u16 timestamp;
		struct hidpp_touchpad_raw_xy_finger fingers[2];
		u8 spurious_flag;
		u8 end_of_frame;
		u8 finger_count;
		u8 button;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 1548 */;
	struct hidpp_touchpad_raw_xy_finger {
		u8 contact_type;
		u8 contact_status;
		u16 x;
		u16 y;
		u8 z;
		u8 area;
		u8 finger_id;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 1538 */;
	struct hidpp_touchpad_raw_info {
		u16 x_size;
		u16 y_size;
		u8 z_range;
		u8 area_range;
		u8 timestamp_unit;
		u8 maxcontacts;
		u8 origin;
		u16 res;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 1527 */;
	struct hidpp_touchpad_fw_items *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1488 */;
	struct hidpp_touchpad_fw_items {
		uint8_t presence;
		uint8_t desired_state;
		uint8_t state;
		uint8_t persistent;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 1475 */;
	struct hidpp_battery {
		u8 feature_index;
		u8 solar_feature_index;
		struct power_supply_desc desc;
		struct power_supply *ps;
		char name[64];
		int status;
		int capacity;
		int level;
		bool online;
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 135 */;
	u8 cocci_id/* drivers/hid/hid-logitech-hidpp.c 1293 */[1];
	struct hidpp_report {
		u8 report_id;
		u8 device_index;
		union {
			struct fap fap;
			struct rap rap;
			u8 rawbytes[sizeof(struct fap)];
		};
	}__packed cocci_id/* drivers/hid/hid-logitech-hidpp.c 125 */;
	union power_supply_propval *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1238 */;
	enum power_supply_property cocci_id/* drivers/hid/hid-logitech-hidpp.c 1237 */;
	struct power_supply *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1236 */;
	enum power_supply_property cocci_id/* drivers/hid/hid-logitech-hidpp.c 1225 */[];
	struct rap {
		u8 sub_id;
		u8 reg_address;
		u8 params[HIDPP_REPORT_VERY_LONG_MAX_LENGTH - 4U];
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 119 */;
	struct fap {
		u8 feature_index;
		u8 funcindex_clientid;
		u8 params[HIDPP_REPORT_VERY_LONG_MAX_LENGTH - 4U];
	} cocci_id/* drivers/hid/hid-logitech-hidpp.c 113 */;
	int *cocci_id/* drivers/hid/hid-logitech-hidpp.c 1093 */;
}
