cocci_test_suite() {
	u16 cocci_id/* drivers/hid/hid-sony.c 931 */;
	struct input_dev *cocci_id/* drivers/hid/hid-sony.c 927 */;
	struct hid_input cocci_id/* drivers/hid/hid-sony.c 926 */;
	const u8 cocci_id/* drivers/hid/hid-sony.c 875 */[];
	u8 cocci_id/* drivers/hid/hid-sony.c 84 */[];
	unsigned int cocci_id/* drivers/hid/hid-sony.c 814 */;
	unsigned long **cocci_id/* drivers/hid/hid-sony.c 811 */;
	int *cocci_id/* drivers/hid/hid-sony.c 811 */;
	struct hid_usage *cocci_id/* drivers/hid/hid-sony.c 810 */;
	struct hid_field *cocci_id/* drivers/hid/hid-sony.c 810 */;
	struct hid_input *cocci_id/* drivers/hid/hid-sony.c 809 */;
	int cocci_id/* drivers/hid/hid-sony.c 809 */;
	unsigned int *cocci_id/* drivers/hid/hid-sony.c 666 */;
	u8 cocci_id/* drivers/hid/hid-sony.c 621 */;
	unsigned long cocci_id/* drivers/hid/hid-sony.c 620 */;
	const char *cocci_id/* drivers/hid/hid-sony.c 616 */;
	size_t cocci_id/* drivers/hid/hid-sony.c 616 */;
	char *cocci_id/* drivers/hid/hid-sony.c 606 */;
	struct device_attribute *cocci_id/* drivers/hid/hid-sony.c 605 */;
	struct device *cocci_id/* drivers/hid/hid-sony.c 604 */;
	ssize_t cocci_id/* drivers/hid/hid-sony.c 604 */;
	enum sony_worker cocci_id/* drivers/hid/hid-sony.c 586 */;
	void cocci_id/* drivers/hid/hid-sony.c 583 */(struct sony_sc *sc);
	struct sony_sc {
		spinlock_t lock;
		struct list_head list_node;
		struct hid_device *hdev;
		struct input_dev *touchpad;
		struct input_dev *sensor_dev;
		struct led_classdev *leds[MAX_LEDS];
		unsigned long quirks;
		struct work_struct hotplug_worker;
		struct work_struct state_worker;
		void (*send_output_report)(struct sony_sc *);
		struct power_supply *battery;
		struct power_supply_desc battery_desc;
		int device_id;
		unsigned fw_version;
		unsigned hw_version;
		u8 *output_report_dmabuf;
#ifdef CONFIG_SONY_FF
		u8 left;
		u8 right;
#endif
		u8 mac_address[6];
		u8 hotplug_worker_initialized;
		u8 state_worker_initialized;
		u8 defer_initialization;
		u8 cable_state;
		u8 battery_charging;
		u8 battery_capacity;
		u8 led_state[MAX_LEDS];
		u8 led_delay_on[MAX_LEDS];
		u8 led_delay_off[MAX_LEDS];
		u8 led_count;
		bool timestamp_initialized;
		u16 prev_timestamp;
		unsigned int timestamp_us;
		u8 ds4_bt_poll_interval;
		enum ds4_dongle_state ds4_dongle_state;
		struct ds4_calibration_data ds4_calib_data[6];
	} cocci_id/* drivers/hid/hid-sony.c 538 */;
	enum sony_worker{SONY_WORKER_STATE, SONY_WORKER_HOTPLUG,} cocci_id/* drivers/hid/hid-sony.c 533 */;
	enum ds4_dongle_state{DONGLE_DISCONNECTED, DONGLE_CALIBRATING, DONGLE_CONNECTED, DONGLE_DISABLED,} cocci_id/* drivers/hid/hid-sony.c 526 */;
	struct ds4_calibration_data {
		int abs_code;
		short bias;
		int sens_numer;
		int sens_denom;
	} cocci_id/* drivers/hid/hid-sony.c 515 */;
	struct motion_output_report_02 {
		u8 type,zero;
		u8 r,g,b;
		u8 zero2;
		u8 rumble;
	} cocci_id/* drivers/hid/hid-sony.c 470 */;
	union sixaxis_output_report_01 {
		struct sixaxis_output_report data;
		u8 buf[36];
	} cocci_id/* drivers/hid/hid-sony.c 465 */;
	struct sixaxis_output_report {
		u8 report_id;
		struct sixaxis_rumble rumble;
		u8 padding[4];
		u8 leds_bitmap;
		struct sixaxis_led led[4];
		struct sixaxis_led _reserved;
	}__packed cocci_id/* drivers/hid/hid-sony.c 456 */;
	struct sixaxis_rumble {
		u8 padding;
		u8 right_duration;
		u8 right_motor_on;
		u8 left_duration;
		u8 left_motor_force;
	}__packed cocci_id/* drivers/hid/hid-sony.c 448 */;
	struct sixaxis_led {
		u8 time_enabled;
		u8 duty_length;
		u8 enabled;
		u8 duty_off;
		u8 duty_on;
	}__packed cocci_id/* drivers/hid/hid-sony.c 440 */;
	enum power_supply_property cocci_id/* drivers/hid/hid-sony.c 433 */[];
	const struct {
		int x;
		int y;
	} cocci_id/* drivers/hid/hid-sony.c 428 */[];
	void __exit cocci_id/* drivers/hid/hid-sony.c 3034 */;
	int __init cocci_id/* drivers/hid/hid-sony.c 3027 */;
	const unsigned int cocci_id/* drivers/hid/hid-sony.c 302 */[];
	struct hid_driver cocci_id/* drivers/hid/hid-sony.c 3010 */;
	const struct hid_device_id cocci_id/* drivers/hid/hid-sony.c 2952 */[];
	pm_message_t cocci_id/* drivers/hid/hid-sony.c 2917 */;
	const struct hid_device_id *cocci_id/* drivers/hid/hid-sony.c 2823 */;
	void (*cocci_id/* drivers/hid/hid-sony.c 2559 */)(struct sony_sc *);
	struct power_supply_config cocci_id/* drivers/hid/hid-sony.c 2325 */;
	union power_supply_propval *cocci_id/* drivers/hid/hid-sony.c 2281 */;
	enum power_supply_property cocci_id/* drivers/hid/hid-sony.c 2280 */;
	struct power_supply *cocci_id/* drivers/hid/hid-sony.c 2279 */;
	struct ff_effect *cocci_id/* drivers/hid/hid-sony.c 2240 */;
	union sixaxis_output_report_01 cocci_id/* drivers/hid/hid-sony.c 2215 */;
	struct motion_output_report_02 *cocci_id/* drivers/hid/hid-sony.c 2179 */;
	struct sixaxis_output_report cocci_id/* drivers/hid/hid-sony.c 2072 */;
	struct sixaxis_output_report *cocci_id/* drivers/hid/hid-sony.c 2067 */;
	const union sixaxis_output_report_01 cocci_id/* drivers/hid/hid-sony.c 2055 */;
	void *cocci_id/* drivers/hid/hid-sony.c 2025 */;
	struct led_classdev cocci_id/* drivers/hid/hid-sony.c 2019 */;
	const u8 cocci_id/* drivers/hid/hid-sony.c 1988 */[4];
	u8 cocci_id/* drivers/hid/hid-sony.c 1959 */[MAX_LEDS];
	const char *constcocci_id/* drivers/hid/hid-sony.c 1957 */[];
	struct led_classdev *cocci_id/* drivers/hid/hid-sony.c 1900 */;
	unsigned long *cocci_id/* drivers/hid/hid-sony.c 1900 */;
	enum led_brightness cocci_id/* drivers/hid/hid-sony.c 1878 */;
	s32 *cocci_id/* drivers/hid/hid-sony.c 1813 */;
	struct hid_report cocci_id/* drivers/hid/hid-sony.c 1812 */;
	struct hid_report *cocci_id/* drivers/hid/hid-sony.c 1811 */;
	struct list_head *cocci_id/* drivers/hid/hid-sony.c 1809 */;
	struct hid_device *cocci_id/* drivers/hid/hid-sony.c 1808 */;
	struct sony_sc *cocci_id/* drivers/hid/hid-sony.c 1806 */;
	void cocci_id/* drivers/hid/hid-sony.c 1806 */;
	const u8 cocci_id/* drivers/hid/hid-sony.c 1785 */[7][3];
	const u8 cocci_id/* drivers/hid/hid-sony.c 1758 */[10][4];
	enum ds4_dongle_state cocci_id/* drivers/hid/hid-sony.c 1708 */;
	struct sony_sc cocci_id/* drivers/hid/hid-sony.c 1706 */;
	struct work_struct *cocci_id/* drivers/hid/hid-sony.c 1704 */;
	u32 cocci_id/* drivers/hid/hid-sony.c 1595 */;
	short cocci_id/* drivers/hid/hid-sony.c 1568 */;
	u8 *cocci_id/* drivers/hid/hid-sony.c 1566 */;
	const int cocci_id/* drivers/hid/hid-sony.c 1496 */;
	s8 cocci_id/* drivers/hid/hid-sony.c 1136 */;
	bool cocci_id/* drivers/hid/hid-sony.c 1088 */;
	struct ds4_calibration_data *cocci_id/* drivers/hid/hid-sony.c 1013 */;
}
