cocci_test_suite() {
	struct wr_msg_ctl_info cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 908 */;
	struct wr_msg_ctl_info *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 905 */;
	struct ishtp_device cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 890 */;
	struct ish_hw cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 890 */;
	const struct ishtp_hw_ops cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 865 */;
	struct ipc_rst_payload_type cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 780 */;
	bool cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 75 */;
	uint16_t cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 731 */;
	struct pci_dev *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 729 */;
	struct ishtp_device *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 727 */;
	int cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 727 */;
	unsigned int cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 677 */;
	uint32_t cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 62 */;
	irqreturn_t cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 617 */;
	uint64_t cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 552 */;
	unsigned long cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 551 */;
	void cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 549 */;
	struct work_struct *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 525 */;
	unsigned char cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 399 */[IPC_FULL_MSG_SIZE];
	void *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 397 */;
	size_t cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 397 */;
	struct ish_hw *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 32 */;
	struct time_sync_format cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 285 */;
	struct ipc_time_update_msg cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 284 */;
	void (*cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 252 */)(void *);
	struct ishtp_msg_hdr cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 226 */;
	uint32_t *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 223 */;
	unsigned char *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 219 */;
	const struct ishtp_device *cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 204 */;
	struct work_struct cocci_id/* drivers/hid/intel-ish-hid/ipc/ipc.c 17 */;
}
