cocci_test_suite() {
	struct zfcp_fc_wka_port *cocci_id/* drivers/s390/scsi/zfcp_fc.c 992 */;
	u8 cocci_id/* drivers/s390/scsi/zfcp_fc.c 961 */;
	struct fc_bsg_reply *cocci_id/* drivers/s390/scsi/zfcp_fc.c 950 */;
	struct zfcp_fsf_ct_els *cocci_id/* drivers/s390/scsi/zfcp_fc.c 949 */;
	struct bsg_job *cocci_id/* drivers/s390/scsi/zfcp_fc.c 948 */;
	struct zfcp_fc_rspn_req *cocci_id/* drivers/s390/scsi/zfcp_fc.c 878 */;
	struct zfcp_fc_gspn_rsp *cocci_id/* drivers/s390/scsi/zfcp_fc.c 834 */;
	struct zfcp_fc_gspn_req *cocci_id/* drivers/s390/scsi/zfcp_fc.c 833 */;
	char cocci_id/* drivers/s390/scsi/zfcp_fc.c 831 */[];
	struct delayed_work *cocci_id/* drivers/s390/scsi/zfcp_fc.c 786 */;
	struct fc_gpn_ft_resp *cocci_id/* drivers/s390/scsi/zfcp_fc.c 717 */;
	struct scatterlist *cocci_id/* drivers/s390/scsi/zfcp_fc.c 715 */;
	struct list_head *cocci_id/* drivers/s390/scsi/zfcp_fc.c 697 */;
	struct zfcp_fc_gpn_ft_req *cocci_id/* drivers/s390/scsi/zfcp_fc.c 678 */;
	struct zfcp_fc_gpn_ft_req cocci_id/* drivers/s390/scsi/zfcp_fc.c 669 */;
	struct zfcp_port cocci_id/* drivers/s390/scsi/zfcp_fc.c 572 */;
	struct work_struct *cocci_id/* drivers/s390/scsi/zfcp_fc.c 569 */;
	struct fc_els_adisc cocci_id/* drivers/s390/scsi/zfcp_fc.c 547 */;
	struct Scsi_Host *cocci_id/* drivers/s390/scsi/zfcp_fc.c 536 */;
	struct zfcp_fc_req *cocci_id/* drivers/s390/scsi/zfcp_fc.c 534 */;
	int cocci_id/* drivers/s390/scsi/zfcp_fc.c 532 */;
	struct fc_els_adisc *cocci_id/* drivers/s390/scsi/zfcp_fc.c 505 */;
	void *cocci_id/* drivers/s390/scsi/zfcp_fc.c 501 */;
	unsigned long long cocci_id/* drivers/s390/scsi/zfcp_fc.c 483 */;
	struct zfcp_fc_gid_pn_req *cocci_id/* drivers/s390/scsi/zfcp_fc.c 378 */;
	unsigned int cocci_id/* drivers/s390/scsi/zfcp_fc.c 37 */;
	u16 cocci_id/* drivers/s390/scsi/zfcp_fc.c 364 */;
	struct fc_ct_hdr *cocci_id/* drivers/s390/scsi/zfcp_fc.c 364 */;
	struct zfcp_fc_gid_pn_rsp *cocci_id/* drivers/s390/scsi/zfcp_fc.c 348 */;
	struct fsf_status_read_buffer *cocci_id/* drivers/s390/scsi/zfcp_fc.c 332 */;
	struct fc_els_logo *cocci_id/* drivers/s390/scsi/zfcp_fc.c 320 */;
	bool cocci_id/* drivers/s390/scsi/zfcp_fc.c 32 */;
	struct fc_els_flogi *cocci_id/* drivers/s390/scsi/zfcp_fc.c 309 */;
	u64 cocci_id/* drivers/s390/scsi/zfcp_fc.c 291 */;
	u32 *cocci_id/* drivers/s390/scsi/zfcp_fc.c 286 */;
	struct fc_els_rscn_page cocci_id/* drivers/s390/scsi/zfcp_fc.c 261 */;
	struct fc_els_rscn *cocci_id/* drivers/s390/scsi/zfcp_fc.c 250 */;
	u32 cocci_id/* drivers/s390/scsi/zfcp_fc.c 25 */[];
	struct zfcp_port *cocci_id/* drivers/s390/scsi/zfcp_fc.c 236 */;
	struct zfcp_adapter *cocci_id/* drivers/s390/scsi/zfcp_fc.c 235 */;
	unsigned long cocci_id/* drivers/s390/scsi/zfcp_fc.c 234 */;
	struct fc_els_rscn_page *cocci_id/* drivers/s390/scsi/zfcp_fc.c 232 */;
	u32 cocci_id/* drivers/s390/scsi/zfcp_fc.c 231 */;
	struct zfcp_fsf_req *cocci_id/* drivers/s390/scsi/zfcp_fc.c 231 */;
	void cocci_id/* drivers/s390/scsi/zfcp_fc.c 231 */;
	struct kmem_cache *cocci_id/* drivers/s390/scsi/zfcp_fc.c 23 */;
	struct zfcp_fc_wka_port cocci_id/* drivers/s390/scsi/zfcp_fc.c 175 */;
	struct zfcp_fc_event cocci_id/* drivers/s390/scsi/zfcp_fc.c 132 */;
	struct zfcp_fc_event *cocci_id/* drivers/s390/scsi/zfcp_fc.c 130 */;
	enum fc_host_event_code cocci_id/* drivers/s390/scsi/zfcp_fc.c 128 */;
	struct zfcp_fc_wka_ports cocci_id/* drivers/s390/scsi/zfcp_fc.c 1086 */;
	struct zfcp_fc_wka_ports *cocci_id/* drivers/s390/scsi/zfcp_fc.c 1084 */;
	struct fc_rport *cocci_id/* drivers/s390/scsi/zfcp_fc.c 1052 */;
	struct fc_bsg_request *cocci_id/* drivers/s390/scsi/zfcp_fc.c 1051 */;
	struct zfcp_adapter cocci_id/* drivers/s390/scsi/zfcp_fc.c 105 */;
	struct zfcp_fc_events cocci_id/* drivers/s390/scsi/zfcp_fc.c 104 */;
	struct zfcp_fc_events *cocci_id/* drivers/s390/scsi/zfcp_fc.c 103 */;
}
