cocci_test_suite() {
	struct qdio_buffer cocci_id/* drivers/s390/cio/qdio_setup.c 84 */;
	void *cocci_id/* drivers/s390/cio/qdio_setup.c 61 */;
	struct qaob cocci_id/* drivers/s390/cio/qdio_setup.c 565 */;
	struct qdio_buffer **cocci_id/* drivers/s390/cio/qdio_setup.c 56 */;
	unsigned int cocci_id/* drivers/s390/cio/qdio_setup.c 56 */;
	struct qdio_q cocci_id/* drivers/s390/cio/qdio_setup.c 559 */;
	int __init cocci_id/* drivers/s390/cio/qdio_setup.c 555 */;
	struct qdio_output_q *cocci_id/* drivers/s390/cio/qdio_setup.c 548 */;
	char cocci_id/* drivers/s390/cio/qdio_setup.c 516 */[80];
	struct ccw_device *cocci_id/* drivers/s390/cio/qdio_setup.c 514 */;
	struct qdr cocci_id/* drivers/s390/cio/qdio_setup.c 468 */;
	struct ciw *cocci_id/* drivers/s390/cio/qdio_setup.c 455 */;
	struct qdio_initialize *cocci_id/* drivers/s390/cio/qdio_setup.c 453 */;
	struct qdesfmt0 cocci_id/* drivers/s390/cio/qdio_setup.c 422 */;
	unsigned long cocci_id/* drivers/s390/cio/qdio_setup.c 399 */;
	int cocci_id/* drivers/s390/cio/qdio_setup.c 396 */;
	struct qdio_q **cocci_id/* drivers/s390/cio/qdio_setup.c 395 */;
	struct qdio_irq *cocci_id/* drivers/s390/cio/qdio_setup.c 394 */;
	void cocci_id/* drivers/s390/cio/qdio_setup.c 394 */;
	struct chsc_ssqd_area *cocci_id/* drivers/s390/cio/qdio_setup.c 301 */;
	struct qdio_ssqd_desc *cocci_id/* drivers/s390/cio/qdio_setup.c 299 */;
	struct subchannel_id *cocci_id/* drivers/s390/cio/qdio_setup.c 298 */;
	unsigned char cocci_id/* drivers/s390/cio/qdio_setup.c 273 */;
	struct qaob *cocci_id/* drivers/s390/cio/qdio_setup.c 26 */;
	struct kmem_cache *cocci_id/* drivers/s390/cio/qdio_setup.c 24 */;
	struct qdio_outbuf_state *cocci_id/* drivers/s390/cio/qdio_setup.c 217 */;
	struct sl *cocci_id/* drivers/s390/cio/qdio_setup.c 190 */;
	char *cocci_id/* drivers/s390/cio/qdio_setup.c 190 */;
	qdio_handler_t *cocci_id/* drivers/s390/cio/qdio_setup.c 169 */;
	struct slib *cocci_id/* drivers/s390/cio/qdio_setup.c 147 */;
	struct qdio_q *cocci_id/* drivers/s390/cio/qdio_setup.c 139 */;
	unsigned long *cocci_id/* drivers/s390/cio/qdio_setup.c 104 */;
	unsigned char *cocci_id/* drivers/s390/cio/qdio_setup.c 103 */;
}
