cocci_test_suite() {
	struct f54_data {
		struct rmi_function *fn;
		u8 num_rx_electrodes;
		u8 num_tx_electrodes;
		u8 capabilities;
		u16 clock_rate;
		u8 family;
		enum rmi_f54_report_type report_type;
		u8 *report_data;
		int report_size;
		bool is_busy;
		struct mutex status_mutex;
		struct mutex data_mutex;
		struct workqueue_struct *workqueue;
		struct delayed_work work;
		unsigned long timeout;
		struct completion cmd_done;
		struct v4l2_device v4l2;
		struct v4l2_pix_format format;
		struct video_device vdev;
		struct vb2_queue queue;
		struct mutex lock;
		u32 sequence;
		int input;
		enum rmi_f54_report_type inputs[F54_MAX_REPORT_TYPE];
	} cocci_id/* drivers/input/rmi4/rmi_f54.c 84 */;
	struct rmi_function_handler cocci_id/* drivers/input/rmi4/rmi_f54.c 733 */;
	const char *const cocci_id/* drivers/input/rmi4/rmi_f54.c 73 */[];
	struct f54_data cocci_id/* drivers/input/rmi4/rmi_f54.c 650 */;
	enum rmi_f54_report_type{F54_REPORT_NONE=0, F54_8BIT_IMAGE=1, F54_16BIT_IMAGE=2, F54_RAW_16BIT_IMAGE=3, F54_TRUE_BASELINE=9, F54_FULL_RAW_CAP=19, F54_FULL_RAW_CAP_RX_OFFSET_REMOVED=20, F54_MAX_REPORT_TYPE,} cocci_id/* drivers/input/rmi4/rmi_f54.c 62 */;
	u8 cocci_id/* drivers/input/rmi4/rmi_f54.c 610 */[6];
	struct rmi_driver *cocci_id/* drivers/input/rmi4/rmi_f54.c 599 */;
	struct rmi_function *cocci_id/* drivers/input/rmi4/rmi_f54.c 597 */;
	u8 cocci_id/* drivers/input/rmi4/rmi_f54.c 525 */[2];
	struct work_struct *cocci_id/* drivers/input/rmi4/rmi_f54.c 521 */;
	const struct video_device cocci_id/* drivers/input/rmi4/rmi_f54.c 512 */;
	const struct v4l2_ioctl_ops cocci_id/* drivers/input/rmi4/rmi_f54.c 488 */;
	struct v4l2_streamparm *cocci_id/* drivers/input/rmi4/rmi_f54.c 477 */;
	struct v4l2_fmtdesc *cocci_id/* drivers/input/rmi4/rmi_f54.c 461 */;
	struct file *cocci_id/* drivers/input/rmi4/rmi_f54.c 460 */;
	void *cocci_id/* drivers/input/rmi4/rmi_f54.c 460 */;
	struct v4l2_format *cocci_id/* drivers/input/rmi4/rmi_f54.c 451 */;
	struct v4l2_pix_format *cocci_id/* drivers/input/rmi4/rmi_f54.c 411 */;
	struct v4l2_input *cocci_id/* drivers/input/rmi4/rmi_f54.c 390 */;
	struct v4l2_capability *cocci_id/* drivers/input/rmi4/rmi_f54.c 377 */;
	struct vb2_v4l2_buffer cocci_id/* drivers/input/rmi4/rmi_f54.c 370 */;
	const struct vb2_queue cocci_id/* drivers/input/rmi4/rmi_f54.c 367 */;
	const struct vb2_ops cocci_id/* drivers/input/rmi4/rmi_f54.c 359 */;
	int cocci_id/* drivers/input/rmi4/rmi_f54.c 293 */;
	enum vb2_buffer_state cocci_id/* drivers/input/rmi4/rmi_f54.c 291 */;
	u16 *cocci_id/* drivers/input/rmi4/rmi_f54.c 290 */;
	struct vb2_v4l2_buffer *cocci_id/* drivers/input/rmi4/rmi_f54.c 288 */;
	struct vb2_buffer *cocci_id/* drivers/input/rmi4/rmi_f54.c 286 */;
	void cocci_id/* drivers/input/rmi4/rmi_f54.c 286 */;
	struct device *cocci_id/* drivers/input/rmi4/rmi_f54.c 273 */[];
	unsigned int cocci_id/* drivers/input/rmi4/rmi_f54.c 272 */[];
	struct vb2_queue *cocci_id/* drivers/input/rmi4/rmi_f54.c 271 */;
	unsigned int *cocci_id/* drivers/input/rmi4/rmi_f54.c 271 */;
	const struct v4l2_file_operations cocci_id/* drivers/input/rmi4/rmi_f54.c 261 */;
	u32 *cocci_id/* drivers/input/rmi4/rmi_f54.c 232 */;
	u16 cocci_id/* drivers/input/rmi4/rmi_f54.c 223 */;
	u8 cocci_id/* drivers/input/rmi4/rmi_f54.c 210 */;
	struct rmi_driver_data *cocci_id/* drivers/input/rmi4/rmi_f54.c 209 */;
	struct rmi_device *cocci_id/* drivers/input/rmi4/rmi_f54.c 208 */;
	size_t cocci_id/* drivers/input/rmi4/rmi_f54.c 206 */;
	unsigned int cocci_id/* drivers/input/rmi4/rmi_f54.c 142 */;
	enum rmi_f54_report_type cocci_id/* drivers/input/rmi4/rmi_f54.c 123 */;
	bool cocci_id/* drivers/input/rmi4/rmi_f54.c 122 */;
	struct f54_data *cocci_id/* drivers/input/rmi4/rmi_f54.c 122 */;
}
