cocci_test_suite() {
	bool cocci_id/* drivers/input/rmi4/rmi_f11.c 768 */;
	u8 cocci_id/* drivers/input/rmi4/rmi_f11.c 767 */[RMI_F11_QUERY_SIZE];
	struct rmi_device *cocci_id/* drivers/input/rmi4/rmi_f11.c 730 */;
	u16 cocci_id/* drivers/input/rmi4/rmi_f11.c 729 */;
	struct f11_2d_ctrl *cocci_id/* drivers/input/rmi4/rmi_f11.c 729 */;
	struct rmi_function *cocci_id/* drivers/input/rmi4/rmi_f11.c 728 */;
	u8 cocci_id/* drivers/input/rmi4/rmi_f11.c 652 */;
	struct f11_2d_data *cocci_id/* drivers/input/rmi4/rmi_f11.c 634 */;
	struct f11_2d_sensor_queries *cocci_id/* drivers/input/rmi4/rmi_f11.c 633 */;
	struct rmi_2d_sensor *cocci_id/* drivers/input/rmi4/rmi_f11.c 632 */;
	struct f11_data *cocci_id/* drivers/input/rmi4/rmi_f11.c 630 */;
	int cocci_id/* drivers/input/rmi4/rmi_f11.c 630 */;
	const u8 *cocci_id/* drivers/input/rmi4/rmi_f11.c 571 */;
	u8 *cocci_id/* drivers/input/rmi4/rmi_f11.c 541 */;
	enum f11_finger_state cocci_id/* drivers/input/rmi4/rmi_f11.c 537 */;
	struct rmi_2d_sensor_abs_object *cocci_id/* drivers/input/rmi4/rmi_f11.c 536 */;
	void cocci_id/* drivers/input/rmi4/rmi_f11.c 534 */;
	s8 cocci_id/* drivers/input/rmi4/rmi_f11.c 526 */;
	enum f11_finger_state{F11_NO_FINGER=0x00, F11_PRESENT=0x01, F11_INACCURATE=0x02, F11_RESERVED=0x03,} cocci_id/* drivers/input/rmi4/rmi_f11.c 515 */;
	struct f11_data {
		bool has_query9;
		bool has_query11;
		bool has_query12;
		bool has_query27;
		bool has_query28;
		bool has_acm;
		struct f11_2d_ctrl dev_controls;
		struct mutex dev_controls_mutex;
		u16 rezero_wait_ms;
		struct rmi_2d_sensor sensor;
		struct f11_2d_sensor_queries sens_query;
		struct f11_2d_data data;
		struct rmi_2d_sensor_platform_data sensor_pdata;
		unsigned long *abs_mask;
		unsigned long *rel_mask;
	} cocci_id/* drivers/input/rmi4/rmi_f11.c 497 */;
	struct f11_2d_data {
		u8 *f_state;
		u8 *abs_pos;
		s8 *rel_pos;
		u8 *gest_1;
		u8 *gest_2;
		s8 *pinch;
		u8 *flick;
		u8 *rotate;
		u8 *shapes;
		s8 *multi_scroll;
		s8 *scroll_zones;
	} cocci_id/* drivers/input/rmi4/rmi_f11.c 471 */;
	struct f11_2d_ctrl {
		u8 ctrl0_11[RMI_F11_CTRL_REG_COUNT];
		u16 ctrl0_11_address;
	} cocci_id/* drivers/input/rmi4/rmi_f11.c 432 */;
	struct f11_2d_sensor_queries {
		u8 nr_fingers;
		bool has_rel;
		bool has_abs;
		bool has_gestures;
		bool has_sensitivity_adjust;
		bool configurable;
		u8 nr_x_electrodes;
		u8 nr_y_electrodes;
		u8 max_electrodes;
		u8 abs_data_size;
		bool has_anchored_finger;
		bool has_adj_hyst;
		bool has_dribble;
		bool has_bending_correction;
		bool has_large_object_suppression;
		bool has_jitter_filter;
		u8 f11_2d_query6;
		bool has_single_tap;
		bool has_tap_n_hold;
		bool has_double_tap;
		bool has_early_tap;
		bool has_flick;
		bool has_press;
		bool has_pinch;
		bool has_chiral;
		bool query7_nonzero;
		bool has_palm_det;
		bool has_rotate;
		bool has_touch_shapes;
		bool has_scroll_zones;
		bool has_individual_scroll_zones;
		bool has_mf_scroll;
		bool has_mf_edge_motion;
		bool has_mf_scroll_inertia;
		bool query8_nonzero;
		bool has_pen;
		bool has_proximity;
		bool has_palm_det_sensitivity;
		bool has_suppress_on_palm_detect;
		bool has_two_pen_thresholds;
		bool has_contact_geometry;
		bool has_pen_hover_discrimination;
		bool has_pen_filters;
		u8 nr_touch_shapes;
		bool has_z_tuning;
		bool has_algorithm_selection;
		bool has_w_tuning;
		bool has_pitch_info;
		bool has_finger_size;
		bool has_segmentation_aggressiveness;
		bool has_XY_clip;
		bool has_drumming_filter;
		bool has_gapless_finger;
		bool has_gapless_finger_tuning;
		bool has_8bit_w;
		bool has_adjustable_mapping;
		bool has_info2;
		bool has_physical_props;
		bool has_finger_limit;
		bool has_linear_coeff_2;
		u8 jitter_window_size;
		u8 jitter_filter_type;
		u8 light_control;
		bool is_clear;
		u8 clickpad_props;
		u8 mouse_buttons;
		bool has_advanced_gestures;
		u16 x_sensor_size_mm;
		u16 y_sensor_size_mm;
	} cocci_id/* drivers/input/rmi4/rmi_f11.c 311 */;
	struct rmi_function_handler cocci_id/* drivers/input/rmi4/rmi_f11.c 1339 */;
	struct rmi_driver_data *cocci_id/* drivers/input/rmi4/rmi_f11.c 1267 */;
	irqreturn_t cocci_id/* drivers/input/rmi4/rmi_f11.c 1263 */;
	void *cocci_id/* drivers/input/rmi4/rmi_f11.c 1263 */;
	struct rmi_driver *cocci_id/* drivers/input/rmi4/rmi_f11.c 1241 */;
	struct rmi_2d_sensor_abs_object cocci_id/* drivers/input/rmi4/rmi_f11.c 1184 */;
	struct input_mt_pos cocci_id/* drivers/input/rmi4/rmi_f11.c 1178 */;
	unsigned long *cocci_id/* drivers/input/rmi4/rmi_f11.c 1074 */;
	char *cocci_id/* drivers/input/rmi4/rmi_f11.c 1074 */;
	struct f11_data cocci_id/* drivers/input/rmi4/rmi_f11.c 1059 */;
	unsigned long cocci_id/* drivers/input/rmi4/rmi_f11.c 1054 */;
	const struct rmi_device_platform_data *cocci_id/* drivers/input/rmi4/rmi_f11.c 1045 */;
}
