cocci_test_suite() {
	const struct input_mt *cocci_id/* drivers/input/evdev.c 935 */;
	struct input_keymap_entry cocci_id/* drivers/input/evdev.c 816 */;
	size_t cocci_id/* drivers/input/evdev.c 80 */;
	unsigned long *cocci_id/* drivers/input/evdev.c 79 */;
	const char *cocci_id/* drivers/input/evdev.c 776 */;
	long cocci_id/* drivers/input/evdev.c 698 */;
	compat_long_t __user *cocci_id/* drivers/input/evdev.c 691 */;
	compat_long_t *cocci_id/* drivers/input/evdev.c 689 */;
	compat_long_t cocci_id/* drivers/input/evdev.c 681 */;
	const void __user *cocci_id/* drivers/input/evdev.c 676 */;
	int cocci_id/* drivers/input/evdev.c 675 */;
	void __user *cocci_id/* drivers/input/evdev.c 648 */;
	__poll_t cocci_id/* drivers/input/evdev.c 622 */;
	poll_table *cocci_id/* drivers/input/evdev.c 622 */;
	const size_t cocci_id/* drivers/input/evdev.c 58 */[EV_CNT];
	loff_t *cocci_id/* drivers/input/evdev.c 571 */;
	char __user *cocci_id/* drivers/input/evdev.c 570 */;
	ssize_t cocci_id/* drivers/input/evdev.c 570 */;
	const char __user *cocci_id/* drivers/input/evdev.c 514 */;
	struct inode *cocci_id/* drivers/input/evdev.c 480 */;
	struct input_dev *cocci_id/* drivers/input/evdev.c 471 */;
	struct evdev_client {
		unsigned int head;
		unsigned int tail;
		unsigned int packet_head;
		spinlock_t buffer_lock;
		struct fasync_struct *fasync;
		struct evdev *evdev;
		struct list_head node;
		enum input_clock_type clk_type;
		bool revoked;
		unsigned long *evmasks[EV_CNT];
		unsigned int bufsize;
		struct input_event buffer[];
	} cocci_id/* drivers/input/evdev.c 41 */;
	struct evdev *cocci_id/* drivers/input/evdev.c 386 */;
	struct device *cocci_id/* drivers/input/evdev.c 343 */;
	fl_owner_t cocci_id/* drivers/input/evdev.c 329 */;
	struct input_value cocci_id/* drivers/input/evdev.c 317 */[];
	const struct input_value *cocci_id/* drivers/input/evdev.c 292 */;
	struct evdev {
		int open;
		struct input_handle handle;
		wait_queue_head_t wait;
		struct evdev_client __rcu *grab;
		struct list_head client_list;
		spinlock_t client_lock;
		struct mutex mutex;
		struct device dev;
		struct cdev cdev;
		bool exist;
	} cocci_id/* drivers/input/evdev.c 28 */;
	const struct input_event *cocci_id/* drivers/input/evdev.c 215 */;
	enum input_clock_type cocci_id/* drivers/input/evdev.c 177 */;
	struct input_event cocci_id/* drivers/input/evdev.c 147 */;
	struct timespec64 cocci_id/* drivers/input/evdev.c 146 */;
	void __exit cocci_id/* drivers/input/evdev.c 1450 */;
	ktime_t *cocci_id/* drivers/input/evdev.c 145 */;
	int __init cocci_id/* drivers/input/evdev.c 1445 */;
	struct input_handler cocci_id/* drivers/input/evdev.c 1434 */;
	const struct input_device_id cocci_id/* drivers/input/evdev.c 1427 */[];
	struct evdev cocci_id/* drivers/input/evdev.c 1365 */;
	const struct input_device_id *cocci_id/* drivers/input/evdev.c 1351 */;
	struct input_handler *cocci_id/* drivers/input/evdev.c 1350 */;
	struct input_handle *cocci_id/* drivers/input/evdev.c 1334 */;
	const struct file_operations cocci_id/* drivers/input/evdev.c 1304 */;
	struct ff_effect __user *cocci_id/* drivers/input/evdev.c 1199 */;
	unsigned long cocci_id/* drivers/input/evdev.c 1089 */;
	struct input_id cocci_id/* drivers/input/evdev.c 1062 */;
	struct input_event *cocci_id/* drivers/input/evdev.c 106 */;
	int __user *cocci_id/* drivers/input/evdev.c 1050 */;
	bool cocci_id/* drivers/input/evdev.c 105 */;
	struct ff_effect cocci_id/* drivers/input/evdev.c 1049 */;
	struct input_mask cocci_id/* drivers/input/evdev.c 1048 */;
	struct input_absinfo cocci_id/* drivers/input/evdev.c 1047 */;
	struct file *cocci_id/* drivers/input/evdev.c 1041 */;
	u8 __user *cocci_id/* drivers/input/evdev.c 1029 */;
	struct evdev_client *cocci_id/* drivers/input/evdev.c 101 */;
	unsigned int cocci_id/* drivers/input/evdev.c 101 */;
	void cocci_id/* drivers/input/evdev.c 101 */;
	u32 cocci_id/* drivers/input/evdev.c 1006 */;
}
