cocci_test_suite() {
	struct i2c_msg cocci_id/* drivers/input/mouse/cyapa.c 95 */[];
	const struct attribute_group cocci_id/* drivers/input/mouse/cyapa.c 931 */;
	struct attribute *cocci_id/* drivers/input/mouse/cyapa.c 926 */[];
	u8 *cocci_id/* drivers/input/mouse/cyapa.c 92 */;
	irqreturn_t cocci_id/* drivers/input/mouse/cyapa.c 676 */;
	u16 cocci_id/* drivers/input/mouse/cyapa.c 581 */;
	int cocci_id/* drivers/input/mouse/cyapa.c 42 */(struct cyapa *cyapa);
	struct input_dev *cocci_id/* drivers/input/mouse/cyapa.c 413 */;
	void cocci_id/* drivers/input/mouse/cyapa.c 413 */;
	const char cocci_id/* drivers/input/mouse/cyapa.c 40 */[];
	unsigned int cocci_id/* drivers/input/mouse/cyapa.c 279 */;
	bool cocci_id/* drivers/input/mouse/cyapa.c 169 */;
	u8 cocci_id/* drivers/input/mouse/cyapa.c 167 */[32];
	u8 cocci_id/* drivers/input/mouse/cyapa.c 166 */[BL_STATUS_SIZE];
	struct i2c_driver cocci_id/* drivers/input/mouse/cyapa.c 1487 */;
	const struct of_device_id cocci_id/* drivers/input/mouse/cyapa.c 1480 */[];
	u8 cocci_id/* drivers/input/mouse/cyapa.c 148 */;
	struct i2c_client *cocci_id/* drivers/input/mouse/cyapa.c 148 */;
	const struct acpi_device_id cocci_id/* drivers/input/mouse/cyapa.c 1470 */[];
	const struct i2c_device_id cocci_id/* drivers/input/mouse/cyapa.c 1463 */[];
	int __maybe_unused cocci_id/* drivers/input/mouse/cyapa.c 1403 */;
	char cocci_id/* drivers/input/mouse/cyapa.c 132 */[32];
	const void *cocci_id/* drivers/input/mouse/cyapa.c 129 */;
	struct cyapa cocci_id/* drivers/input/mouse/cyapa.c 1268 */;
	union i2c_smbus_data cocci_id/* drivers/input/mouse/cyapa.c 1254 */;
	const struct i2c_device_id *cocci_id/* drivers/input/mouse/cyapa.c 1249 */;
	void *cocci_id/* drivers/input/mouse/cyapa.c 1241 */;
	char *cocci_id/* drivers/input/mouse/cyapa.c 1160 */;
	int cocci_id/* drivers/input/mouse/cyapa.c 1141 */;
	struct cyapa *cocci_id/* drivers/input/mouse/cyapa.c 1140 */;
	const char *cocci_id/* drivers/input/mouse/cyapa.c 1138 */;
	size_t cocci_id/* drivers/input/mouse/cyapa.c 1138 */;
	struct device_attribute *cocci_id/* drivers/input/mouse/cyapa.c 1137 */;
	struct device *cocci_id/* drivers/input/mouse/cyapa.c 1136 */;
	ssize_t cocci_id/* drivers/input/mouse/cyapa.c 1136 */;
	char cocci_id/* drivers/input/mouse/cyapa.c 1081 */[NAME_MAX];
	const struct firmware *cocci_id/* drivers/input/mouse/cyapa.c 1016 */;
}
