cocci_test_suite() {
	char **cocci_id/* arch/powerpc/kernel/setup-common.c 860 */;
	struct machdep_calls *cocci_id/* arch/powerpc/kernel/setup-common.c 81 */;
	unsigned long long cocci_id/* arch/powerpc/kernel/setup-common.c 805 */;
	unsigned short cocci_id/* arch/powerpc/kernel/setup-common.c 796 */;
	struct machdep_calls cocci_id/* arch/powerpc/kernel/setup-common.c 79 */;
	struct dentry *cocci_id/* arch/powerpc/kernel/setup-common.c 784 */;
	bool cocci_id/* arch/powerpc/kernel/setup-common.c 761 */;
	const void *cocci_id/* arch/powerpc/kernel/setup-common.c 760 */;
	int __init cocci_id/* arch/powerpc/kernel/setup-common.c 757 */;
	struct notifier_block cocci_id/* arch/powerpc/kernel/setup-common.c 730 */;
	struct notifier_block *cocci_id/* arch/powerpc/kernel/setup-common.c 721 */;
	void **cocci_id/* arch/powerpc/kernel/setup-common.c 613 */;
	unsigned int cocci_id/* arch/powerpc/kernel/setup-common.c 600 */;
	struct platform_device *cocci_id/* arch/powerpc/kernel/setup-common.c 575 */;
	struct device_node *cocci_id/* arch/powerpc/kernel/setup-common.c 574 */;
	int cocci_id/* arch/powerpc/kernel/setup-common.c 572 */;
	void cocci_id/* arch/powerpc/kernel/setup-common.c 572 */;
	__be32 cocci_id/* arch/powerpc/kernel/setup-common.c 462 */;
	const __be32 *cocci_id/* arch/powerpc/kernel/setup-common.c 461 */;
	u32 *cocci_id/* arch/powerpc/kernel/setup-common.c 426 */;
	cpumask_t cocci_id/* arch/powerpc/kernel/setup-common.c 397 */;
	void __init cocci_id/* arch/powerpc/kernel/setup-common.c 372 */;
	const struct seq_operations cocci_id/* arch/powerpc/kernel/setup-common.c 365 */;
	loff_t *cocci_id/* arch/powerpc/kernel/setup-common.c 355 */;
	struct seq_file *cocci_id/* arch/powerpc/kernel/setup-common.c 355 */;
	void *cocci_id/* arch/powerpc/kernel/setup-common.c 355 */;
	unsigned long cocci_id/* arch/powerpc/kernel/setup-common.c 351 */;
	u32 cocci_id/* arch/powerpc/kernel/setup-common.c 263 */;
	const char *cocci_id/* arch/powerpc/kernel/setup-common.c 197 */;
	void (*cocci_id/* arch/powerpc/kernel/setup-common.c 177 */)(void);
	char *cocci_id/* arch/powerpc/kernel/setup-common.c 151 */;
	struct screen_info cocci_id/* arch/powerpc/kernel/setup-common.c 101 */;
	__typeof__(unsigned int) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
