cocci_test_suite() {
	const char *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 953 */;
	int64_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 905 */;
	uint8_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 904 */;
	uint64_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 902 */;
	struct device_node *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 901 */;
	struct pnv_phb *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 900 */;
	struct pci_controller *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 899 */;
	u32 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 851 */;
	struct eeh_dev *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 849 */;
	struct pci_dn *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 848 */;
	struct pci_dev *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 846 */;
	int cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 846 */;
	int *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 722 */;
	__be16 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 614 */;
	u8 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 613 */;
	uint32_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 370 */;
	int __init cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1719 */;
	void cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1719 */;
	u64 *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 169 */;
	void *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 169 */;
	struct eeh_ops cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1677 */;
	u64 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 160 */;
	const struct file_operations cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 154 */;
	__be64 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1451 */;
	struct pnv_ioda_pe *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1384 */;
	u16 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1381 */;
	struct eeh_pe **cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1381 */;
	long cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1327 */;
	struct OpalIoP7IOCErrorData *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1299 */;
	u32 *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1274 */;
	char cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 127 */[50];
	unsigned long cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 126 */;
	bool cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1252 */;
	s64 cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1215 */;
	loff_t *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 121 */;
	size_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 121 */;
	const char __user *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 120 */;
	struct eeh_pe *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1193 */;
	struct file *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 119 */;
	ssize_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 119 */;
	char *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1177 */;
	struct pci_bus *cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1082 */;
	struct eeh_dev cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 1054 */;
	irqreturn_t cocci_id/* arch/powerpc/platforms/powernv/eeh-powernv.c 102 */;
}
