cocci_test_suite() {
	gpa_t cocci_id/* arch/powerpc/kvm/book3s_hv.c 796 */;
	struct dtl_entry *cocci_id/* arch/powerpc/kvm/book3s_hv.c 691 */;
	struct device_node *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5632 */;
	struct sibling_subcore_state cocci_id/* arch/powerpc/kvm/book3s_hv.c 5579 */;
	struct sibling_subcore_state *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5568 */;
	struct kvmppc_ops cocci_id/* arch/powerpc/kvm/book3s_hv.c 5518 */;
	struct dtl_entry cocci_id/* arch/powerpc/kvm/book3s_hv.c 541 */;
	ulong *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5392 */;
	struct lppaca cocci_id/* arch/powerpc/kvm/book3s_hv.c 533 */;
	struct kvm_ppc_mmuv3_cfg *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5316 */;
	unsigned int cocci_id/* arch/powerpc/kvm/book3s_hv.c 5279 */[];
	struct kvm_ppc_resize_hpt cocci_id/* arch/powerpc/kvm/book3s_hv.c 5245 */;
	struct kvm_get_htab_fd cocci_id/* arch/powerpc/kvm/book3s_hv.c 5235 */;
	u32 __user *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5225 */;
	u32 cocci_id/* arch/powerpc/kvm/book3s_hv.c 5222 */;
	void __user *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5216 */;
	long cocci_id/* arch/powerpc/kvm/book3s_hv.c 5212 */;
	struct kvm_kernel_irqfd cocci_id/* arch/powerpc/kvm/book3s_hv.c 5179 */;
	struct kvm_kernel_irqfd *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5178 */;
	struct irq_bypass_producer *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5175 */;
	struct irq_bypass_consumer *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5174 */;
	struct reg_vpa cocci_id/* arch/powerpc/kvm/book3s_hv.c 514 */;
	struct irq_desc *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5130 */;
	struct reg_vpa *cocci_id/* arch/powerpc/kvm/book3s_hv.c 508 */;
	struct irq_chip *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5045 */;
	struct kvmppc_irq_map *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5043 */;
	struct kvmppc_passthru_irqmap cocci_id/* arch/powerpc/kvm/book3s_hv.c 5037 */;
	struct kvmppc_passthru_irqmap *cocci_id/* arch/powerpc/kvm/book3s_hv.c 5035 */;
	ulong cocci_id/* arch/powerpc/kvm/book3s_hv.c 5004 */;
	int *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4998 */;
	long int cocci_id/* arch/powerpc/kvm/book3s_hv.c 4959 */;
	struct kvmppc_vpa *cocci_id/* arch/powerpc/kvm/book3s_hv.c 490 */;
	void *cocci_id/* arch/powerpc/kvm/book3s_hv.c 486 */;
	char cocci_id/* arch/powerpc/kvm/book3s_hv.c 4812 */[32];
	struct kvmppc_host_rm_core cocci_id/* arch/powerpc/kvm/book3s_hv.c 4755 */;
	struct kvmppc_host_rm_ops cocci_id/* arch/powerpc/kvm/book3s_hv.c 4751 */;
	struct kvmppc_host_rm_ops *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4742 */;
	struct reg_vpa {
		u32 dummy;
		union {
			__be16 hword;
			__be32 word;
		} length;
	} cocci_id/* arch/powerpc/kvm/book3s_hv.c 465 */;
	struct kvm_hpt_info cocci_id/* arch/powerpc/kvm/book3s_hv.c 4615 */;
	struct vm_area_struct *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4607 */;
	enum kvm_mr_change cocci_id/* arch/powerpc/kvm/book3s_hv.c 4490 */;
	const struct kvm_memory_slot *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4488 */;
	const struct kvm_userspace_memory_region *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4487 */;
	struct lppaca *cocci_id/* arch/powerpc/kvm/book3s_hv.c 442 */;
	unsigned long *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4401 */;
	struct kvm_memory_slot *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4398 */;
	struct kvm_memslots *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4397 */;
	struct kvm_dirty_log *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4395 */;
	struct kvm_ppc_one_seg_page_size *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4364 */;
	struct kvm_ppc_smmu_info *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4362 */;
	struct kvm_ppc_one_seg_page_size **cocci_id/* arch/powerpc/kvm/book3s_hv.c 4341 */;
	unsigned long cocci_id/* arch/powerpc/kvm/book3s_hv.c 4221 */[3];
	struct kvm_nested_guest *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4046 */;
	struct kvm_run *cocci_id/* arch/powerpc/kvm/book3s_hv.c 4038 */;
	ktime_t cocci_id/* arch/powerpc/kvm/book3s_hv.c 3789 */;
	s32 cocci_id/* arch/powerpc/kvm/book3s_hv.c 3638 */;
	struct hv_guest_state cocci_id/* arch/powerpc/kvm/book3s_hv.c 3600 */;
	s64 cocci_id/* arch/powerpc/kvm/book3s_hv.c 3396 */;
	struct kvm_split_mode cocci_id/* arch/powerpc/kvm/book3s_hv.c 3052 */;
	struct core_info cocci_id/* arch/powerpc/kvm/book3s_hv.c 3050 */;
	struct preempted_vcore_list *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2870 */;
	void cocci_id/* arch/powerpc/kvm/book3s_hv.c 2868 */;
	int cocci_id/* arch/powerpc/kvm/book3s_hv.c 2804 */;
	bool cocci_id/* arch/powerpc/kvm/book3s_hv.c 2802 */;
	struct kvmppc_vcore *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2802 */;
	struct core_info *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2802 */;
	int cocci_id/* arch/powerpc/kvm/book3s_hv.c 2757 */[MAX_SUBCORES];
	struct core_info {
		int n_subcores;
		int max_subcore_threads;
		int total_threads;
		int subcore_threads[MAX_SUBCORES];
		struct kvmppc_vcore *vc[MAX_SUBCORES];
	} cocci_id/* arch/powerpc/kvm/book3s_hv.c 2745 */;
	struct preempted_vcore_list {
		struct list_head list;
		spinlock_t lock;
	} cocci_id/* arch/powerpc/kvm/book3s_hv.c 2693 */;
	cpumask_t *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2539 */;
	struct paca_struct *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2493 */;
	int cocci_id/* arch/powerpc/kvm/book3s_hv.c 2471 */(void);
	struct swait_queue_head *cocci_id/* arch/powerpc/kvm/book3s_hv.c 234 */;
	struct kvm *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2255 */;
	char cocci_id/* arch/powerpc/kvm/book3s_hv.c 2254 */[16];
	unsigned int cocci_id/* arch/powerpc/kvm/book3s_hv.c 2252 */;
	const struct file_operations cocci_id/* arch/powerpc/kvm/book3s_hv.c 2242 */;
	const char __user *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2236 */;
	unsigned long cocci_id/* arch/powerpc/kvm/book3s_hv.c 2191 */;
	struct kvmhv_tb_accumulator *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2188 */;
	loff_t cocci_id/* arch/powerpc/kvm/book3s_hv.c 2179 */;
	u64 cocci_id/* arch/powerpc/kvm/book3s_hv.c 2178 */;
	struct kvmhv_tb_accumulator cocci_id/* arch/powerpc/kvm/book3s_hv.c 2177 */;
	char *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2176 */;
	loff_t *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2172 */;
	size_t cocci_id/* arch/powerpc/kvm/book3s_hv.c 2172 */;
	char __user *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2171 */;
	ssize_t cocci_id/* arch/powerpc/kvm/book3s_hv.c 2171 */;
	struct debugfs_timings_state *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2149 */;
	struct kvm_vcpu *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2148 */;
	struct inode *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2146 */;
	struct file *cocci_id/* arch/powerpc/kvm/book3s_hv.c 2146 */;
	struct debugfs_timings_state {
		struct kvm_vcpu *vcpu;
		unsigned int buflen;
		char buf[N_TIMINGS * 100];
	} cocci_id/* arch/powerpc/kvm/book3s_hv.c 2140 */;
	struct kvm_vcpu cocci_id/* arch/powerpc/kvm/book3s_hv.c 2131 */;
	struct debugfs_timings_element {
		const char *name;
		size_t offset;
	} cocci_id/* arch/powerpc/kvm/book3s_hv.c 2127 */[];
	struct kvmppc_vcore cocci_id/* arch/powerpc/kvm/book3s_hv.c 2109 */;
	union kvmppc_one_reg *cocci_id/* arch/powerpc/kvm/book3s_hv.c 1637 */;
	struct kvm_sregs cocci_id/* arch/powerpc/kvm/book3s_hv.c 1556 */;
	struct kvm_sregs *cocci_id/* arch/powerpc/kvm/book3s_hv.c 1552 */;
	unsigned long cocci_id/* arch/powerpc/kvm/book3s_hv.c 155 */[MAX_SMT_THREADS + 1];
	int cocci_id/* arch/powerpc/kvm/book3s_hv.c 139 */(struct kvm_vcpu *vcpu);
	struct task_struct *cocci_id/* arch/powerpc/kvm/book3s_hv.c 1265 */;
	struct kernel_param_ops cocci_id/* arch/powerpc/kvm/book3s_hv.c 114 */;
	__typeof__(struct preempted_vcore_list) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
