cocci_test_suite() {
	struct acpi_madt_local_apic_override *cocci_id/* arch/ia64/kernel/acpi.c 94 */;
	u64 cocci_id/* arch/ia64/kernel/acpi.c 882 */;
	u8 cocci_id/* arch/ia64/kernel/acpi.c 88 */;
	int __init cocci_id/* arch/ia64/kernel/acpi.c 872 */;
	struct acpi_table_madt *cocci_id/* arch/ia64/kernel/acpi.c 87 */;
	struct acpi_madt_io_sapic *cocci_id/* arch/ia64/kernel/acpi.c 832 */;
	union acpi_object *cocci_id/* arch/ia64/kernel/acpi.c 831 */;
	struct acpi_buffer cocci_id/* arch/ia64/kernel/acpi.c 830 */;
	void **cocci_id/* arch/ia64/kernel/acpi.c 828 */;
	void *cocci_id/* arch/ia64/kernel/acpi.c 828 */;
	acpi_status cocci_id/* arch/ia64/kernel/acpi.c 827 */;
	phys_cpuid_t cocci_id/* arch/ia64/kernel/acpi.c 805 */;
	int __ref cocci_id/* arch/ia64/kernel/acpi.c 805 */;
	cpumask_t cocci_id/* arch/ia64/kernel/acpi.c 785 */;
	acpi_handle cocci_id/* arch/ia64/kernel/acpi.c 783 */;
	int *cocci_id/* arch/ia64/kernel/acpi.c 783 */;
	int cocci_id/* arch/ia64/kernel/acpi.c 783 */;
	void __iomem *cocci_id/* arch/ia64/kernel/acpi.c 78 */;
	void __init cocci_id/* arch/ia64/kernel/acpi.c 78 */;
	void __init __iomem *cocci_id/* arch/ia64/kernel/acpi.c 73 */;
	unsigned long cocci_id/* arch/ia64/kernel/acpi.c 73 */;
	u32 *cocci_id/* arch/ia64/kernel/acpi.c 702 */;
	unsigned cocci_id/* arch/ia64/kernel/acpi.c 702 */;
	u32 cocci_id/* arch/ia64/kernel/acpi.c 687 */;
	unsigned int *cocci_id/* arch/ia64/kernel/acpi.c 687 */;
	int __init cocci_id/* arch/ia64/kernel/acpi.c 610 */;
	void cocci_id/* arch/ia64/kernel/acpi.c 610 */;
	struct acpi_table_fadt *cocci_id/* arch/ia64/kernel/acpi.c 559 */;
	struct acpi_table_header *cocci_id/* arch/ia64/kernel/acpi.c 556 */;
	enum acpi_irq_model_id cocci_id/* arch/ia64/kernel/acpi.c 54 */;
	struct device *cocci_id/* arch/ia64/kernel/acpi.c 526 */;
	int cocci_id/* arch/ia64/kernel/acpi.c 50 */[ACPI_MAX_PLATFORM_INTERRUPTS];
	unsigned int cocci_id/* arch/ia64/kernel/acpi.c 42 */;
	struct node_memblk_s *cocci_id/* arch/ia64/kernel/acpi.c 406 */;
	struct acpi_srat_mem_affinity *cocci_id/* arch/ia64/kernel/acpi.c 402 */;
	struct acpi_srat_cpu_affinity *cocci_id/* arch/ia64/kernel/acpi.c 375 */;
	void __init cocci_id/* arch/ia64/kernel/acpi.c 374 */;
	struct acpi_table_header cocci_id/* arch/ia64/kernel/acpi.c 363 */;
	struct acpi_table_slit *cocci_id/* arch/ia64/kernel/acpi.c 359 */;
	struct acpi_table_slit __initdata *cocci_id/* arch/ia64/kernel/acpi.c 329 */;
	u32 cocci_id/* arch/ia64/kernel/acpi.c 326 */[PXM_FLAG_LEN];
	int __initdata cocci_id/* arch/ia64/kernel/acpi.c 325 */;
	char *cocci_id/* arch/ia64/kernel/acpi.c 277 */;
	struct acpi_madt_nmi_source *cocci_id/* arch/ia64/kernel/acpi.c 266 */;
	struct acpi_madt_interrupt_override *cocci_id/* arch/ia64/kernel/acpi.c 246 */;
	const unsigned long cocci_id/* arch/ia64/kernel/acpi.c 244 */;
	union acpi_subtable_headers *cocci_id/* arch/ia64/kernel/acpi.c 243 */;
	struct acpi_madt_interrupt_source *cocci_id/* arch/ia64/kernel/acpi.c 162 */;
	unsigned int __initdata cocci_id/* arch/ia64/kernel/acpi.c 156 */;
	struct acpi_madt_local_apic_nmi *cocci_id/* arch/ia64/kernel/acpi.c 132 */;
	struct acpi_madt_local_sapic *cocci_id/* arch/ia64/kernel/acpi.c 111 */;
}
