cocci_test_suite() {
	unsigned long *cocci_id/* arch/sparc/kernel/time_64.c 895 */;
	struct sparc64_tick_ops *cocci_id/* arch/sparc/kernel/time_64.c 819 */;
	struct get_tick_patch *cocci_id/* arch/sparc/kernel/time_64.c 802 */;
	unsigned int *cocci_id/* arch/sparc/kernel/time_64.c 801 */;
	void __init cocci_id/* arch/sparc/kernel/time_64.c 799 */;
	u64 cocci_id/* arch/sparc/kernel/time_64.c 794 */;
	struct clocksource *cocci_id/* arch/sparc/kernel/time_64.c 794 */;
	unsigned long cocci_id/* arch/sparc/kernel/time_64.c 779 */;
	void cocci_id/* arch/sparc/kernel/time_64.c 779 */;
	struct clocksource cocci_id/* arch/sparc/kernel/time_64.c 771 */;
	struct clock_event_device *cocci_id/* arch/sparc/kernel/time_64.c 743 */;
	void __irq_entry cocci_id/* arch/sparc/kernel/time_64.c 716 */;
	struct clock_event_device cocci_id/* arch/sparc/kernel/time_64.c 706 */;
	struct notifier_block cocci_id/* arch/sparc/kernel/time_64.c 678 */;
	struct freq_table *cocci_id/* arch/sparc/kernel/time_64.c 657 */;
	unsigned int cocci_id/* arch/sparc/kernel/time_64.c 656 */;
	struct cpufreq_freqs *cocci_id/* arch/sparc/kernel/time_64.c 655 */;
	void *cocci_id/* arch/sparc/kernel/time_64.c 653 */;
	struct notifier_block *cocci_id/* arch/sparc/kernel/time_64.c 652 */;
	struct freq_table {
		unsigned long clock_tick_ref;
		unsigned int ref_freq;
	} cocci_id/* arch/sparc/kernel/time_64.c 634 */;
	int __init cocci_id/* arch/sparc/kernel/time_64.c 600 */;
	struct pt_regs *cocci_id/* arch/sparc/kernel/time_64.c 57 */;
	struct device_node *cocci_id/* arch/sparc/kernel/time_64.c 559 */;
	struct platform_device cocci_id/* arch/sparc/kernel/time_64.c 548 */;
	struct m48t59_plat_data cocci_id/* arch/sparc/kernel/time_64.c 543 */;
	u8 cocci_id/* arch/sparc/kernel/time_64.c 535 */;
	void __iomem *cocci_id/* arch/sparc/kernel/time_64.c 530 */;
	u32 cocci_id/* arch/sparc/kernel/time_64.c 527 */;
	struct device *cocci_id/* arch/sparc/kernel/time_64.c 527 */;
	unsigned char cocci_id/* arch/sparc/kernel/time_64.c 527 */;
	struct platform_driver cocci_id/* arch/sparc/kernel/time_64.c 519 */;
	const struct of_device_id cocci_id/* arch/sparc/kernel/time_64.c 511 */[];
	struct platform_device *cocci_id/* arch/sparc/kernel/time_64.c 501 */;
	int cocci_id/* arch/sparc/kernel/time_64.c 501 */;
	struct resource *cocci_id/* arch/sparc/kernel/time_64.c 446 */;
	struct resource cocci_id/* arch/sparc/kernel/time_64.c 435 */;
	struct sparc64_tick_ops cocci_id/* arch/sparc/kernel/time_64.c 421 */;
	long cocci_id/* arch/sparc/kernel/time_64.c 413 */;
	unsigned long long cocci_id/* arch/sparc/kernel/time_64.c 387 */;
	char cocci_id/* arch/sparc/kernel/time_64.c 170 */[128];
	bool cocci_id/* arch/sparc/kernel/time_64.c 168 */;
	phandle cocci_id/* arch/sparc/kernel/time_64.c 166 */;
	__typeof__(struct freq_table) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
	__typeof__(struct clock_event_device) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
