cocci_test_suite() {
	struct davinci_cpuidle_config cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 985 */;
	void __iomem *__init cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 964 */;
	void __iomem *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 963 */;
	char *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 871 */;
	phys_addr_t cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 868 */;
	bool cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 864 */;
	struct davinci_mmc_config *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 810 */;
	void *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 757 */;
	struct da8xx_lcdc_platform_data *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 691 */;
	struct da8xx_lcdc_platform_data cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 656 */;
	struct lcd_ctrl_config cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 651 */;
	struct uio_pruss_pdata cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 630 */;
	struct plat_serial8250_port cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 62 */[];
	struct snd_platform_data *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 553 */;
	void __init cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 553 */;
	struct platform_device cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 476 */;
	struct resource cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 448 */[];
	struct emac_platform_data cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 404 */;
	struct davinci_i2c_platform_data *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 341 */;
	struct edma_rsv_info *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 275 */[2];
	struct platform_device *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 244 */;
	struct edma_rsv_info *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 242 */;
	int __init cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 242 */;
	const struct dma_slave_map cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 227 */[];
	const struct platform_device_info cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 217 */;
	struct edma_soc_info cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 146 */;
	s8 cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 135 */[][2];
	struct regmap *__init cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1155 */;
	void cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1155 */;
	const struct regmap_config cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1139 */;
	struct regmap *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1137 */;
	int cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1127 */;
	unsigned long cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1125 */;
	u64 cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1112 */;
	struct clk *cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1086 */;
	unsigned cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1068 */;
	struct davinci_spi_platform_data cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 1032 */[];
	struct platform_device cocci_id/* arch/arm/mach-davinci/devices-da8xx.c 102 */[];
}
