cocci_test_suite() {
	struct stm32_adc_calib {
		u32 calfact_s;
		u32 calfact_d;
		u32 lincalfact[STM32H7_LINCALFACT_NUM];
		bool calibrated;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 97 */;
	const struct iio_chan_spec *cocci_id/* drivers/iio/adc/stm32-adc.c 956 */;
	const struct stm32_adc_regs *cocci_id/* drivers/iio/adc/stm32-adc.c 955 */;
	const unsigned long *cocci_id/* drivers/iio/adc/stm32-adc.c 952 */;
	struct stm32_adc_trig_info {
		const char *name;
		enum stm32_adc_extsel extsel;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 85 */;
	enum stm32h7_adc_dmngt cocci_id/* drivers/iio/adc/stm32-adc.c 600 */;
	enum stm32_adc_extsel{STM32_EXT0, STM32_EXT1, STM32_EXT2, STM32_EXT3, STM32_EXT4, STM32_EXT5, STM32_EXT6, STM32_EXT7, STM32_EXT8, STM32_EXT9, STM32_EXT10, STM32_EXT11, STM32_EXT12, STM32_EXT13, STM32_EXT14, STM32_EXT15, STM32_EXT16, STM32_EXT17, STM32_EXT18, STM32_EXT19, STM32_EXT20,} cocci_id/* drivers/iio/adc/stm32-adc.c 56 */;
	unsigned long cocci_id/* drivers/iio/adc/stm32-adc.c 482 */;
	enum stm32_adc_exten{STM32_EXTEN_SWTRIG, STM32_EXTEN_HWTRIG_RISING_EDGE, STM32_EXTEN_HWTRIG_FALLING_EDGE, STM32_EXTEN_HWTRIG_BOTH_EDGES,} cocci_id/* drivers/iio/adc/stm32-adc.c 48 */;
	u16 cocci_id/* drivers/iio/adc/stm32-adc.c 461 */;
	const struct stm32_adc_regspec cocci_id/* drivers/iio/adc/stm32-adc.c 337 */;
	const unsigned int cocci_id/* drivers/iio/adc/stm32-adc.c 333 */[STM32_ADC_MAX_SMP + 1];
	const struct stm32_adc_regs cocci_id/* drivers/iio/adc/stm32-adc.c 308 */[];
	struct stm32_adc_trig_info cocci_id/* drivers/iio/adc/stm32-adc.c 285 */[];
	const struct stm32_adc_regs cocci_id/* drivers/iio/adc/stm32-adc.c 262 */[STM32_ADC_MAX_SQ + 1];
	const struct stm32_adc_info cocci_id/* drivers/iio/adc/stm32-adc.c 239 */;
	const unsigned int cocci_id/* drivers/iio/adc/stm32-adc.c 233 */[];
	struct stm32_adc_info {
		int max_channels;
		const unsigned int *resolutions;
		const unsigned int num_res;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 227 */;
	struct stm32_adc_diff_channel {
		u32 vinp;
		u32 vinn;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 216 */;
	struct platform_driver cocci_id/* drivers/iio/adc/stm32-adc.c 2017 */;
	const struct of_device_id cocci_id/* drivers/iio/adc/stm32-adc.c 2009 */[];
	const struct stm32_adc_cfg cocci_id/* drivers/iio/adc/stm32-adc.c 1976 */;
	struct stm32_adc {
		struct stm32_adc_common *common;
		u32 offset;
		const struct stm32_adc_cfg *cfg;
		struct completion completion;
		u16 buffer[STM32_ADC_MAX_SQ];
		struct clk *clk;
		int irq;
		spinlock_t lock;
		unsigned int bufi;
		unsigned int num_conv;
		u32 res;
		u32 trigger_polarity;
		struct dma_chan *dma_chan;
		u8 *rx_buf;
		dma_addr_t rx_dma_buf;
		unsigned int rx_buf_sz;
		u32 difsel;
		u32 pcsel;
		u32 smpr_val[2];
		struct stm32_adc_calib cal;
		char chan_name[STM32_ADC_CH_MAX][STM32_ADC_CH_SZ];
	} cocci_id/* drivers/iio/adc/stm32-adc.c 192 */;
	const struct stm32_adc_cfg *cocci_id/* drivers/iio/adc/stm32-adc.c 1800 */;
	struct platform_device *cocci_id/* drivers/iio/adc/stm32-adc.c 1782 */;
	dma_addr_t cocci_id/* drivers/iio/adc/stm32-adc.c 1763 */;
	struct dma_slave_config cocci_id/* drivers/iio/adc/stm32-adc.c 1746 */;
	struct iio_chan_spec cocci_id/* drivers/iio/adc/stm32-adc.c 1688 */;
	u32 *cocci_id/* drivers/iio/adc/stm32-adc.c 1670 */;
	const __be32 *cocci_id/* drivers/iio/adc/stm32-adc.c 1646 */;
	struct property *cocci_id/* drivers/iio/adc/stm32-adc.c 1645 */;
	struct stm32_adc_diff_channel cocci_id/* drivers/iio/adc/stm32-adc.c 1644 */[STM32_ADC_CH_MAX];
	const struct stm32_adc_info *cocci_id/* drivers/iio/adc/stm32-adc.c 1643 */;
	struct device_node *cocci_id/* drivers/iio/adc/stm32-adc.c 1641 */;
	char *cocci_id/* drivers/iio/adc/stm32-adc.c 1607 */;
	bool cocci_id/* drivers/iio/adc/stm32-adc.c 1604 */;
	u32 cocci_id/* drivers/iio/adc/stm32-adc.c 1603 */;
	struct iio_chan_spec *cocci_id/* drivers/iio/adc/stm32-adc.c 1603 */;
	struct stm32_adc_cfg {
		const struct stm32_adc_regspec *regs;
		const struct stm32_adc_info *adc_info;
		struct stm32_adc_trig_info *trigs;
		bool clk_required;
		bool has_vregready;
		int (*prepare)(struct stm32_adc *);
		void (*start_conv)(struct stm32_adc *, bool dma);
		void (*stop_conv)(struct stm32_adc *);
		void (*unprepare)(struct stm32_adc *);
		const unsigned int *smp_cycles;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 155 */;
	const struct iio_chan_spec_ext_info cocci_id/* drivers/iio/adc/stm32-adc.c 1549 */[];
	u16 *cocci_id/* drivers/iio/adc/stm32-adc.c 1529 */;
	struct iio_poll_func *cocci_id/* drivers/iio/adc/stm32-adc.c 1514 */;
	const struct iio_buffer_setup_ops cocci_id/* drivers/iio/adc/stm32-adc.c 1507 */;
	void cocci_id/* drivers/iio/adc/stm32-adc.c 1475 */;
	struct device *cocci_id/* drivers/iio/adc/stm32-adc.c 1420 */;
	struct stm32_adc *cocci_id/* drivers/iio/adc/stm32-adc.c 1419 */;
	struct iio_dev *cocci_id/* drivers/iio/adc/stm32-adc.c 1417 */;
	int cocci_id/* drivers/iio/adc/stm32-adc.c 1417 */;
	struct stm32_adc cocci_id/* drivers/iio/adc/stm32-adc.c 140 */;
	dma_cookie_t cocci_id/* drivers/iio/adc/stm32-adc.c 1383 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/iio/adc/stm32-adc.c 1382 */;
	void *cocci_id/* drivers/iio/adc/stm32-adc.c 1372 */;
	enum dma_status cocci_id/* drivers/iio/adc/stm32-adc.c 1350 */;
	struct dma_tx_state cocci_id/* drivers/iio/adc/stm32-adc.c 1349 */;
	unsigned int cocci_id/* drivers/iio/adc/stm32-adc.c 1347 */;
	const struct iio_info cocci_id/* drivers/iio/adc/stm32-adc.c 1338 */;
	unsigned *cocci_id/* drivers/iio/adc/stm32-adc.c 1315 */;
	unsigned cocci_id/* drivers/iio/adc/stm32-adc.c 1314 */;
	const struct of_phandle_args *cocci_id/* drivers/iio/adc/stm32-adc.c 1288 */;
	struct stm32_adc_regspec {
		const u32 dr;
		const struct stm32_adc_regs ier_eoc;
		const struct stm32_adc_regs isr_eoc;
		const struct stm32_adc_regs *sqr;
		const struct stm32_adc_regs exten;
		const struct stm32_adc_regs extsel;
		const struct stm32_adc_regs res;
		const u32 smpr[2];
		const struct stm32_adc_regs *smp_bits;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 128 */;
	const struct stm32_adc_regspec *cocci_id/* drivers/iio/adc/stm32-adc.c 1212 */;
	irqreturn_t cocci_id/* drivers/iio/adc/stm32-adc.c 1208 */;
	int *cocci_id/* drivers/iio/adc/stm32-adc.c 1168 */;
	long cocci_id/* drivers/iio/adc/stm32-adc.c 1168 */;
	struct stm32_adc_regs {
		int reg;
		int mask;
		int shift;
	} cocci_id/* drivers/iio/adc/stm32-adc.c 110 */;
	const struct iio_enum cocci_id/* drivers/iio/adc/stm32-adc.c 1085 */;
	const char *constcocci_id/* drivers/iio/adc/stm32-adc.c 1081 */[];
	struct iio_trigger *cocci_id/* drivers/iio/adc/stm32-adc.c 1003 */;
}
