cocci_test_suite() {
	const struct iio_info cocci_id/* drivers/iio/adc/at91_adc.c 987 */;
	struct at91_adc_data *cocci_id/* drivers/iio/adc/at91_adc.c 966 */;
	struct at91_adc_trigger cocci_id/* drivers/iio/adc/at91_adc.c 922 */;
	struct at91_adc_caps *cocci_id/* drivers/iio/adc/at91_adc.c 881 */;
	struct device *cocci_id/* drivers/iio/adc/at91_adc.c 835 */;
	const struct of_device_id cocci_id/* drivers/iio/adc/at91_adc.c 832 */[];
	const int cocci_id/* drivers/iio/adc/at91_adc.c 810 */[];
	const char **cocci_id/* drivers/iio/adc/at91_adc.c 766 */;
	u32 *cocci_id/* drivers/iio/adc/at91_adc.c 747 */;
	struct device_node *cocci_id/* drivers/iio/adc/at91_adc.c 744 */;
	struct platform_device *cocci_id/* drivers/iio/adc/at91_adc.c 741 */;
	int *cocci_id/* drivers/iio/adc/at91_adc.c 688 */;
	long cocci_id/* drivers/iio/adc/at91_adc.c 688 */;
	void cocci_id/* drivers/iio/adc/at91_adc.c 681 */;
	struct at91_adc_trigger *cocci_id/* drivers/iio/adc/at91_adc.c 604 */;
	struct iio_trigger *cocci_id/* drivers/iio/adc/at91_adc.c 603 */;
	const struct iio_trigger_ops cocci_id/* drivers/iio/adc/at91_adc.c 599 */;
	const struct iio_chan_spec *cocci_id/* drivers/iio/adc/at91_adc.c 574 */;
	u8 cocci_id/* drivers/iio/adc/at91_adc.c 556 */;
	struct at91_adc_reg_desc *cocci_id/* drivers/iio/adc/at91_adc.c 553 */;
	bool cocci_id/* drivers/iio/adc/at91_adc.c 549 */;
	char *cocci_id/* drivers/iio/adc/at91_adc.c 528 */;
	const char *cocci_id/* drivers/iio/adc/at91_adc.c 522 */;
	struct iio_chan_spec cocci_id/* drivers/iio/adc/at91_adc.c 487 */;
	unsigned long cocci_id/* drivers/iio/adc/at91_adc.c 471 */;
	struct iio_chan_spec *cocci_id/* drivers/iio/adc/at91_adc.c 469 */;
	const uint32_t cocci_id/* drivers/iio/adc/at91_adc.c 423 */;
	u32 cocci_id/* drivers/iio/adc/at91_adc.c 422 */;
	struct at91_adc_state *cocci_id/* drivers/iio/adc/at91_adc.c 421 */;
	struct iio_dev *cocci_id/* drivers/iio/adc/at91_adc.c 420 */;
	irqreturn_t cocci_id/* drivers/iio/adc/at91_adc.c 418 */;
	void *cocci_id/* drivers/iio/adc/at91_adc.c 418 */;
	int cocci_id/* drivers/iio/adc/at91_adc.c 418 */;
	struct iio_poll_func *cocci_id/* drivers/iio/adc/at91_adc.c 247 */;
	struct at91_adc_state {
		struct clk *adc_clk;
		u16 *buffer;
		unsigned long channels_mask;
		struct clk *clk;
		bool done;
		int irq;
		u16 last_value;
		int chnb;
		struct mutex lock;
		u8 num_channels;
		void __iomem *reg_base;
		struct at91_adc_reg_desc *registers;
		u32 startup_time;
		u8 sample_hold_time;
		bool sleep_mode;
		struct iio_trigger **trig;
		struct at91_adc_trigger *trigger_list;
		u32 trigger_number;
		bool use_external;
		u32 vref_mv;
		u32 res;
		bool low_res;
		wait_queue_head_t wq_data_avail;
		struct at91_adc_caps *caps;
#define CHAN_MASK_TOUCHSCREEN_4WIRE (0xf << 0)
#define CHAN_MASK_TOUCHSCREEN_5WIRE (0x1f << 0)
				enum atmel_adc_ts_type touchscreen_type;
		struct input_dev *ts_input;
		u16 ts_sample_period_val;
		u32 ts_pressure_threshold;
		u16 ts_pendbc;
		bool ts_bufferedmeasure;
		u32 ts_prev_absx;
		u32 ts_prev_absy;
	} cocci_id/* drivers/iio/adc/at91_adc.c 193 */;
	struct at91_adc_caps {
		bool has_ts;
		bool has_tsmr;
		u8 ts_filter_average;
		u8 ts_pen_detect_sensitivity;
		u32 (*calc_startup_ticks)(u32 startup_time, u32 adc_clk_khz);
		u8 num_channels;
		struct at91_adc_reg_desc registers;
	} cocci_id/* drivers/iio/adc/at91_adc.c 175 */;
	struct at91_adc_reg_desc {
		u8 channel_base;
		u32 drdy_mask;
		u8 status_register;
		u8 trigger_register;
		u32 mr_prescal_mask;
		u32 mr_startup_mask;
	} cocci_id/* drivers/iio/adc/at91_adc.c 166 */;
	struct platform_driver cocci_id/* drivers/iio/adc/at91_adc.c 1470 */;
	const struct platform_device_id cocci_id/* drivers/iio/adc/at91_adc.c 1451 */[];
	struct at91_adc_caps cocci_id/* drivers/iio/adc/at91_adc.c 1383 */;
	struct at91_adc_state cocci_id/* drivers/iio/adc/at91_adc.c 1158 */;
	struct resource *cocci_id/* drivers/iio/adc/at91_adc.c 1155 */;
	unsigned int cocci_id/* drivers/iio/adc/at91_adc.c 1151 */;
	struct input_dev *cocci_id/* drivers/iio/adc/at91_adc.c 1091 */;
}
