cocci_test_suite() {
	int cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 97 */;
	void cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 94 */;
	struct platform_driver cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 703 */;
	struct pci_bus *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 691 */;
	struct bridge_regs *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 622 */;
	char cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 574 */[26];
	struct fwnode_handle *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 573 */;
	struct pci_host_bridge *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 571 */;
	struct xtalk_bridge_platform_data *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 568 */;
	struct platform_device *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 566 */;
	u8 cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 531 */[64];
	char cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 530 */[24];
	struct nvmem_device *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 529 */;
	u64 cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 527 */;
	char *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 527 */;
	const char *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 518 */;
	const void *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 516 */;
	const struct {
		char *match;
		void (*setup)(struct bridge_controller *bc);
	} cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 489 */[];
	u32 *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 45 */;
	struct irq_alloc_info cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 437 */;
	u8 cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 434 */;
	const struct pci_dev *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 434 */;
	const struct irq_domain_ops cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 418 */;
	u32 cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 379 */;
	struct bridge_irq_chip_data *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 375 */;
	bool cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 373 */;
	struct irq_data *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 373 */;
	struct irq_domain *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 372 */;
	phys_addr_t cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 36 */;
	dma_addr_t cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 36 */;
	struct device *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 36 */;
	struct irq_alloc_info *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 337 */;
	void *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 334 */;
	unsigned int cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 333 */;
	struct irq_chip cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 326 */;
	struct bridge_controller *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 31 */;
	const struct cpumask *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 302 */;
	struct pci_dev *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 30 */;
	struct bridge_irq_chip_data {
		struct bridge_controller *bc;
		nasid_t nasid;
	} cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 297 */;
	struct pci_ops cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 292 */;
	u16 *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 148 */;
	u8 *cocci_id/* arch/mips/pci/pci-xtalk-bridge.c 146 */;
}
