cocci_test_suite() {
	struct kvm_dirty_log *cocci_id/* arch/mips/kvm/mips.c 993 */;
	struct kvm_enable_cap cocci_id/* arch/mips/kvm/mips.c 958 */;
	unsigned cocci_id/* arch/mips/kvm/mips.c 942 */;
	struct kvm_reg_list cocci_id/* arch/mips/kvm/mips.c 941 */;
	struct kvm_reg_list __user *cocci_id/* arch/mips/kvm/mips.c 940 */;
	struct kvm_one_reg cocci_id/* arch/mips/kvm/mips.c 928 */;
	struct kvm_mips_interrupt cocci_id/* arch/mips/kvm/mips.c 903 */;
	void __user *cocci_id/* arch/mips/kvm/mips.c 900 */;
	struct kvm_vcpu *cocci_id/* arch/mips/kvm/mips.c 899 */;
	struct kvm_enable_cap *cocci_id/* arch/mips/kvm/mips.c 870 */;
	s32 cocci_id/* arch/mips/kvm/mips.c 772 */;
	u32 cocci_id/* arch/mips/kvm/mips.c 744 */;
	u32 __user *cocci_id/* arch/mips/kvm/mips.c 743 */;
	s64 cocci_id/* arch/mips/kvm/mips.c 651 */[2];
	s64 cocci_id/* arch/mips/kvm/mips.c 650 */;
	struct mips_fpu_struct *cocci_id/* arch/mips/kvm/mips.c 648 */;
	const struct kvm_one_reg *cocci_id/* arch/mips/kvm/mips.c 645 */;
	u64 cocci_id/* arch/mips/kvm/mips.c 596 */;
	u64 __user *cocci_id/* arch/mips/kvm/mips.c 594 */;
	u64 cocci_id/* arch/mips/kvm/mips.c 525 */[];
	struct kvm_mp_state *cocci_id/* arch/mips/kvm/mips.c 514 */;
	struct kvm_mips_interrupt *cocci_id/* arch/mips/kvm/mips.c 480 */;
	struct kvm_run *cocci_id/* arch/mips/kvm/mips.c 435 */;
	struct kvm_guest_debug *cocci_id/* arch/mips/kvm/mips.c 430 */;
	struct kvm_stats_debugfs_item cocci_id/* arch/mips/kvm/mips.c 43 */[];
	struct kvm_vcpu cocci_id/* arch/mips/kvm/mips.c 289 */;
	u32 *cocci_id/* arch/mips/kvm/mips.c 268 */;
	const char *cocci_id/* arch/mips/kvm/mips.c 266 */;
	void *cocci_id/* arch/mips/kvm/mips.c 266 */;
	void cocci_id/* arch/mips/kvm/mips.c 266 */;
	enum kvm_mr_change cocci_id/* arch/mips/kvm/mips.c 235 */;
	const struct kvm_memory_slot *cocci_id/* arch/mips/kvm/mips.c 233 */;
	const struct kvm_userspace_memory_region *cocci_id/* arch/mips/kvm/mips.c 232 */;
	struct kvm *cocci_id/* arch/mips/kvm/mips.c 231 */;
	unsigned long cocci_id/* arch/mips/kvm/mips.c 192 */;
	struct kvm_memory_slot *cocci_id/* arch/mips/kvm/mips.c 191 */;
	struct file *cocci_id/* arch/mips/kvm/mips.c 185 */;
	unsigned int cocci_id/* arch/mips/kvm/mips.c 185 */;
	long cocci_id/* arch/mips/kvm/mips.c 185 */;
	void __exit cocci_id/* arch/mips/kvm/mips.c 1738 */;
	int __init cocci_id/* arch/mips/kvm/mips.c 1715 */;
	struct notifier_block cocci_id/* arch/mips/kvm/mips.c 1711 */;
	struct pt_regs *cocci_id/* arch/mips/kvm/mips.c 1675 */;
	struct die_args *cocci_id/* arch/mips/kvm/mips.c 1674 */;
	struct notifier_block *cocci_id/* arch/mips/kvm/mips.c 1671 */;
	enum emulation_result cocci_id/* arch/mips/kvm/mips.c 1287 */;
	int cocci_id/* arch/mips/kvm/mips.c 126 */;
	struct kvm_translation *cocci_id/* arch/mips/kvm/mips.c 1256 */;
	enum hrtimer_restart cocci_id/* arch/mips/kvm/mips.c 1227 */;
	struct hrtimer *cocci_id/* arch/mips/kvm/mips.c 1227 */;
	struct kvm_regs *cocci_id/* arch/mips/kvm/mips.c 1198 */;
	struct mips_coproc *cocci_id/* arch/mips/kvm/mips.c 1153 */;
	vm_fault_t cocci_id/* arch/mips/kvm/mips.c 1092 */;
	struct vm_fault *cocci_id/* arch/mips/kvm/mips.c 1092 */;
	struct kvm_fpu *cocci_id/* arch/mips/kvm/mips.c 1082 */;
	struct kvm_sregs *cocci_id/* arch/mips/kvm/mips.c 1067 */;
	struct kvm_memslots *cocci_id/* arch/mips/kvm/mips.c 1018 */;
	struct kvm_clear_dirty_log *cocci_id/* arch/mips/kvm/mips.c 1016 */;
	bool cocci_id/* arch/mips/kvm/mips.c 101 */;
}
