cocci_test_suite() {
	u64 *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 79 */;
	void __exit cocci_id/* arch/x86/kernel/cpu/mce/inject.c 689 */;
	int __init cocci_id/* arch/x86/kernel/cpu/mce/inject.c 672 */;
	unsigned int cocci_id/* arch/x86/kernel/cpu/mce/inject.c 663 */;
	void __init cocci_id/* arch/x86/kernel/cpu/mce/inject.c 661 */;
	void cocci_id/* arch/x86/kernel/cpu/mce/inject.c 661 */;
	struct dfs_node {
		char *name;
		const struct file_operations *fops;
		umode_t perm;
	} cocci_id/* arch/x86/kernel/cpu/mce/inject.c 646 */[];
	enum injection_type cocci_id/* arch/x86/kernel/cpu/mce/inject.c 62 */;
	const char cocci_id/* arch/x86/kernel/cpu/mce/inject.c 589 */[];
	struct mce *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 563 */;
	void *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 561 */;
	const char *const cocci_id/* arch/x86/kernel/cpu/mce/inject.c 53 */[];
	u8 cocci_id/* arch/x86/kernel/cpu/mce/inject.c 486 */;
	u64 cocci_id/* arch/x86/kernel/cpu/mce/inject.c 484 */;
	enum injection_type{SW_INJ=0, HW_INJ, DFR_INT_INJ, THR_INT_INJ, N_INJ_TYPES,} cocci_id/* arch/x86/kernel/cpu/mce/inject.c 45 */;
	struct pci_dev *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 425 */;
	struct amd_northbridge *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 424 */;
	u16 cocci_id/* arch/x86/kernel/cpu/mce/inject.c 422 */;
	struct cpuinfo_x86 *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 414 */;
	u32 cocci_id/* arch/x86/kernel/cpu/mce/inject.c 412 */;
	struct dentry *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 40 */;
	struct mce cocci_id/* arch/x86/kernel/cpu/mce/inject.c 39 */;
	const struct file_operations cocci_id/* arch/x86/kernel/cpu/mce/inject.c 372 */;
	const char __user *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 344 */;
	char cocci_id/* arch/x86/kernel/cpu/mce/inject.c 336 */[MAX_FLAG_OPT_SIZE];
	loff_t *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 334 */;
	size_t cocci_id/* arch/x86/kernel/cpu/mce/inject.c 334 */;
	struct file *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 333 */;
	char __user *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 333 */;
	ssize_t cocci_id/* arch/x86/kernel/cpu/mce/inject.c 333 */;
	const char *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 320 */;
	int cocci_id/* arch/x86/kernel/cpu/mce/inject.c 320 */;
	bool cocci_id/* arch/x86/kernel/cpu/mce/inject.c 300 */;
	struct notifier_block cocci_id/* arch/x86/kernel/cpu/mce/inject.c 292 */;
	struct notifier_block *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 277 */;
	unsigned long cocci_id/* arch/x86/kernel/cpu/mce/inject.c 277 */;
	void __maybe_unused cocci_id/* arch/x86/kernel/cpu/mce/inject.c 222 */;
	struct pt_regs *cocci_id/* arch/x86/kernel/cpu/mce/inject.c 159 */;
	cpumask_var_t cocci_id/* arch/x86/kernel/cpu/mce/inject.c 156 */;
	struct pt_regs cocci_id/* arch/x86/kernel/cpu/mce/inject.c 140 */;
	mce_banks_t cocci_id/* arch/x86/kernel/cpu/mce/inject.c 129 */;
}
