cocci_test_suite() {
	unsigned long cocci_id/* arch/x86/platform/efi/efi.c 996 */;
	efi_status_t cocci_id/* arch/x86/platform/efi/efi.c 995 */;
	void *cocci_id/* arch/x86/platform/efi/efi.c 994 */;
	int cocci_id/* arch/x86/platform/efi/efi.c 993 */;
	void __init cocci_id/* arch/x86/platform/efi/efi.c 991 */;
	void cocci_id/* arch/x86/platform/efi/efi.c 991 */;
	int *cocci_id/* arch/x86/platform/efi/efi.c 855 */;
	void *__init cocci_id/* arch/x86/platform/efi/efi.c 855 */;
	const unsigned long *const cocci_id/* arch/x86/platform/efi/efi.c 67 */[];
	efi_config_table_type_t cocci_id/* arch/x86/platform/efi/efi.c 60 */[]__initdata;
	efi_system_table_t cocci_id/* arch/x86/platform/efi/efi.c 58 */;
	struct efi cocci_id/* arch/x86/platform/efi/efi.c 57 */;
	__u64 cocci_id/* arch/x86/platform/efi/efi.c 556 */;
	efi_system_table_t *cocci_id/* arch/x86/platform/efi/efi.c 552 */;
	char cocci_id/* arch/x86/platform/efi/efi.c 542 */[100];
	efi_char16_t *cocci_id/* arch/x86/platform/efi/efi.c 541 */;
	efi_runtime_services_64_t cocci_id/* arch/x86/platform/efi/efi.c 487 */;
	efi_runtime_services_64_t *cocci_id/* arch/x86/platform/efi/efi.c 484 */;
	efi_set_virtual_address_map_t *cocci_id/* arch/x86/platform/efi/efi.c 475 */;
	efi_runtime_services_32_t cocci_id/* arch/x86/platform/efi/efi.c 463 */;
	efi_runtime_services_32_t *cocci_id/* arch/x86/platform/efi/efi.c 460 */;
	efi_system_table_32_t *cocci_id/* arch/x86/platform/efi/efi.c 415 */;
	struct efi_setup_data *cocci_id/* arch/x86/platform/efi/efi.c 360 */;
	efi_system_table_64_t *cocci_id/* arch/x86/platform/efi/efi.c 359 */;
	u64 cocci_id/* arch/x86/platform/efi/efi.c 333 */;
	const efi_memory_desc_t *cocci_id/* arch/x86/platform/efi/efi.c 317 */;
	char cocci_id/* arch/x86/platform/efi/efi.c 284 */[64];
	bool __init cocci_id/* arch/x86/platform/efi/efi.c 280 */;
	phys_addr_t cocci_id/* arch/x86/platform/efi/efi.c 237 */;
	struct efi_memory_map_data cocci_id/* arch/x86/platform/efi/efi.c 236 */;
	struct efi_info *cocci_id/* arch/x86/platform/efi/efi.c 235 */;
	bool cocci_id/* arch/x86/platform/efi/efi.c 216 */;
	unsigned long long cocci_id/* arch/x86/platform/efi/efi.c 164 */;
	unsigned int cocci_id/* arch/x86/platform/efi/efi.c 1121 */;
	char *cocci_id/* arch/x86/platform/efi/efi.c 1105 */;
	int __init cocci_id/* arch/x86/platform/efi/efi.c 1105 */;
	pgd_t *cocci_id/* arch/x86/platform/efi/efi.c 108 */;
	efi_memory_desc_t *cocci_id/* arch/x86/platform/efi/efi.c 1048 */;
	u32 cocci_id/* arch/x86/platform/efi/efi.c 103 */;
	efi_status_t __init cocci_id/* arch/x86/platform/efi/efi.c 100 */;
}
