cocci_test_suite() {
	const struct op_msrs *cocci_id/* arch/x86/oprofile/nmi_int.c 94 */;
	void *cocci_id/* arch/x86/oprofile/nmi_int.c 92 */;
	char *cocci_id/* arch/x86/oprofile/nmi_int.c 677 */;
	__u8 cocci_id/* arch/x86/oprofile/nmi_int.c 675 */;
	int __init cocci_id/* arch/x86/oprofile/nmi_int.c 673 */;
	struct pt_regs *cocci_id/* arch/x86/oprofile/nmi_int.c 64 */;
	const struct kernel_param *cocci_id/* arch/x86/oprofile/nmi_int.c 595 */;
	const char *cocci_id/* arch/x86/oprofile/nmi_int.c 595 */;
	enum __force_cpu_type{reserved=0, timer, arch_perfmon,} cocci_id/* arch/x86/oprofile/nmi_int.c 587 */;
	char **cocci_id/* arch/x86/oprofile/nmi_int.c 557 */;
	void __init cocci_id/* arch/x86/oprofile/nmi_int.c 540 */;
	struct syscore_ops cocci_id/* arch/x86/oprofile/nmi_int.c 535 */;
	u16 cocci_id/* arch/x86/oprofile/nmi_int.c 46 */;
	enum cpuhp_state cocci_id/* arch/x86/oprofile/nmi_int.c 443 */;
	struct op_counter_config *cocci_id/* arch/x86/oprofile/nmi_int.c 43 */;
	const struct op_x86_model_spec *cocci_id/* arch/x86/oprofile/nmi_int.c 42 */;
	char cocci_id/* arch/x86/oprofile/nmi_int.c 419 */[4];
	struct dentry *cocci_id/* arch/x86/oprofile/nmi_int.c 413 */;
	unsigned int cocci_id/* arch/x86/oprofile/nmi_int.c 402 */;
	struct op_counter_config cocci_id/* arch/x86/oprofile/nmi_int.c 38 */[OP_MAX_COUNTER];
	struct op_msr cocci_id/* arch/x86/oprofile/nmi_int.c 317 */;
	size_t cocci_id/* arch/x86/oprofile/nmi_int.c 317 */;
	int cocci_id/* arch/x86/oprofile/nmi_int.c 315 */;
	void cocci_id/* arch/x86/oprofile/nmi_int.c 315 */;
	struct op_x86_model_spec *cocci_id/* arch/x86/oprofile/nmi_int.c 30 */;
	struct oprofile_operations *cocci_id/* arch/x86/oprofile/nmi_int.c 274 */;
	struct op_msr *cocci_id/* arch/x86/oprofile/nmi_int.c 215 */;
	struct op_msrs *cocci_id/* arch/x86/oprofile/nmi_int.c 213 */;
	u64 cocci_id/* arch/x86/oprofile/nmi_int.c 191 */;
	const struct op_msrs *const cocci_id/* arch/x86/oprofile/nmi_int.c 181 */;
	__typeof__(struct op_msrs) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
	__typeof__(unsigned long) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
	__typeof__(int) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
