cocci_test_suite() {
	struct sh_machine_vector cocci_id/* arch/sh/boards/mach-se/7724/setup.c 981 */;
	void __init cocci_id/* arch/sh/boards/mach-se/7724/setup.c 959 */;
	struct smc91x_platdata cocci_id/* arch/sh/boards/mach-se/7724/setup.c 90 */;
	struct resource cocci_id/* arch/sh/boards/mach-se/7724/setup.c 76 */;
	struct clk *cocci_id/* arch/sh/boards/mach-se/7724/setup.c 680 */;
	u16 cocci_id/* arch/sh/boards/mach-se/7724/setup.c 679 */;
	int __init cocci_id/* arch/sh/boards/mach-se/7724/setup.c 668 */;
	void cocci_id/* arch/sh/boards/mach-se/7724/setup.c 668 */;
	char cocci_id/* arch/sh/boards/mach-se/7724/setup.c 664 */;
	int cocci_id/* arch/sh/boards/mach-se/7724/setup.c 628 */;
	struct i2c_board_info cocci_id/* arch/sh/boards/mach-se/7724/setup.c 600 */[];
	struct platform_device *cocci_id/* arch/sh/boards/mach-se/7724/setup.c 577 */[]__initdata;
	struct sh_vou_pdata cocci_id/* arch/sh/boards/mach-se/7724/setup.c 548 */;
	struct i2c_board_info cocci_id/* arch/sh/boards/mach-se/7724/setup.c 542 */;
	struct ak881x_pdata cocci_id/* arch/sh/boards/mach-se/7724/setup.c 538 */;
	void *cocci_id/* arch/sh/boards/mach-se/7724/setup.c 471 */;
	struct tmio_mmc_data cocci_id/* arch/sh/boards/mach-se/7724/setup.c 470 */;
	phys_addr_t cocci_id/* arch/sh/boards/mach-se/7724/setup.c 45 */;
	struct regulator_consumer_supply cocci_id/* arch/sh/boards/mach-se/7724/setup.c 449 */[];
	struct r8a66597_platdata cocci_id/* arch/sh/boards/mach-se/7724/setup.c 390 */;
	struct sh_eth_plat_data cocci_id/* arch/sh/boards/mach-se/7724/setup.c 375 */;
	struct sh_keysc_info cocci_id/* arch/sh/boards/mach-se/7724/setup.c 325 */;
	struct asoc_simple_card_info cocci_id/* arch/sh/boards/mach-se/7724/setup.c 302 */;
	struct platform_device cocci_id/* arch/sh/boards/mach-se/7724/setup.c 242 */;
	struct resource cocci_id/* arch/sh/boards/mach-se/7724/setup.c 229 */[];
	struct ceu_platform_data cocci_id/* arch/sh/boards/mach-se/7724/setup.c 225 */;
	struct sh_mobile_lcdc_info cocci_id/* arch/sh/boards/mach-se/7724/setup.c 189 */;
	const struct fb_videomode cocci_id/* arch/sh/boards/mach-se/7724/setup.c 159 */[];
	struct physmap_flash_data cocci_id/* arch/sh/boards/mach-se/7724/setup.c 134 */;
	struct mtd_partition cocci_id/* arch/sh/boards/mach-se/7724/setup.c 117 */[];
}
