cocci_test_suite() {
	struct page *cocci_id/* arch/arm64/kernel/insn.c 99 */;
	enum aarch64_insn_movewide_type cocci_id/* arch/arm64/kernel/insn.c 969 */;
	void __kprobes *cocci_id/* arch/arm64/kernel/insn.c 95 */;
	enum aarch64_insn_bitfield_type cocci_id/* arch/arm64/kernel/insn.c 915 */;
	enum aarch64_insn_adsb_type cocci_id/* arch/arm64/kernel/insn.c 853 */;
	enum aarch64_insn_prfm_policy cocci_id/* arch/arm64/kernel/insn.c 782 */;
	enum aarch64_insn_prfm_target cocci_id/* arch/arm64/kernel/insn.c 781 */;
	enum aarch64_insn_prfm_type cocci_id/* arch/arm64/kernel/insn.c 780 */;
	enum aarch64_insn_ldst_type cocci_id/* arch/arm64/kernel/insn.c 709 */;
	void cocci_id/* arch/arm64/kernel/insn.c 582 */;
	enum aarch64_insn_hint_op cocci_id/* arch/arm64/kernel/insn.c 577 */;
	enum aarch64_insn_condition cocci_id/* arch/arm64/kernel/insn.c 558 */;
	enum aarch64_insn_encoding_class __kprobes cocci_id/* arch/arm64/kernel/insn.c 49 */;
	long cocci_id/* arch/arm64/kernel/insn.c 489 */;
	enum aarch64_insn_branch_type cocci_id/* arch/arm64/kernel/insn.c 486 */;
	enum aarch64_insn_size_type cocci_id/* arch/arm64/kernel/insn.c 436 */;
	enum aarch64_insn_register cocci_id/* arch/arm64/kernel/insn.c 396 */;
	enum aarch64_insn_register_type cocci_id/* arch/arm64/kernel/insn.c 365 */;
	u32 __kprobes cocci_id/* arch/arm64/kernel/insn.c 331 */;
	const int cocci_id/* arch/arm64/kernel/insn.c 30 */[];
	u32 *cocci_id/* arch/arm64/kernel/insn.c 243 */;
	int *cocci_id/* arch/arm64/kernel/insn.c 243 */;
	enum aarch64_insn_imm_type cocci_id/* arch/arm64/kernel/insn.c 242 */;
	struct aarch64_insn_patch cocci_id/* arch/arm64/kernel/insn.c 228 */;
	u32 cocci_id/* arch/arm64/kernel/insn.c 226 */[];
	void *cocci_id/* arch/arm64/kernel/insn.c 226 */[];
	struct aarch64_insn_patch *cocci_id/* arch/arm64/kernel/insn.c 208 */;
	struct aarch64_insn_patch {
		void **text_addrs;
		u32 *new_insns;
		int insn_cnt;
		atomic_t cpu_count;
	} cocci_id/* arch/arm64/kernel/insn.c 198 */;
	uintptr_t cocci_id/* arch/arm64/kernel/insn.c 187 */;
	u8 cocci_id/* arch/arm64/kernel/insn.c 1664 */;
	enum aarch64_insn_logic_type cocci_id/* arch/arm64/kernel/insn.c 1629 */;
	unsigned int cocci_id/* arch/arm64/kernel/insn.c 1537 */;
	enum aarch64_insn_variant cocci_id/* arch/arm64/kernel/insn.c 1534 */;
	u64 cocci_id/* arch/arm64/kernel/insn.c 1533 */;
	pstate_check_t *const cocci_id/* arch/arm64/kernel/insn.c 1517 */[16];
	bool __kprobes cocci_id/* arch/arm64/kernel/insn.c 1508 */;
	u32 cocci_id/* arch/arm64/kernel/insn.c 1408 */;
	bool cocci_id/* arch/arm64/kernel/insn.c 1400 */;
	int cocci_id/* arch/arm64/kernel/insn.c 137 */;
	unsigned long cocci_id/* arch/arm64/kernel/insn.c 136 */;
	s32 cocci_id/* arch/arm64/kernel/insn.c 1332 */;
	__le32 cocci_id/* arch/arm64/kernel/insn.c 133 */;
	void *cocci_id/* arch/arm64/kernel/insn.c 133 */;
	int __kprobes cocci_id/* arch/arm64/kernel/insn.c 133 */;
	enum aarch64_insn_adr_type cocci_id/* arch/arm64/kernel/insn.c 1300 */;
	enum aarch64_insn_data3_type cocci_id/* arch/arm64/kernel/insn.c 1177 */;
	void __kprobes cocci_id/* arch/arm64/kernel/insn.c 113 */;
	enum aarch64_insn_data2_type cocci_id/* arch/arm64/kernel/insn.c 1126 */;
	enum aarch64_insn_data1_type cocci_id/* arch/arm64/kernel/insn.c 1082 */;
}
