cocci_test_suite() {
	int __init cocci_id/* arch/arm64/mm/mmu.c 934 */;
	phys_addr_t __init cocci_id/* arch/arm64/mm/mmu.c 90 */;
	const u64 cocci_id/* arch/arm64/mm/mmu.c 883 */;
	int *cocci_id/* arch/arm64/mm/mmu.c 881 */;
	void *__initcocci_id/* arch/arm64/mm/mmu.c 881 */;
	pte_t *cocci_id/* arch/arm64/mm/mmu.c 867 */;
	enum fixed_addresses cocci_id/* arch/arm64/mm/mmu.c 863 */;
	struct file *cocci_id/* arch/arm64/mm/mmu.c 79 */;
	int __meminit cocci_id/* arch/arm64/mm/mmu.c 729 */;
	long cocci_id/* arch/arm64/mm/mmu.c 697 */;
	struct vm_struct cocci_id/* arch/arm64/mm/mmu.c 616 */;
	char cocci_id/* arch/arm64/mm/mmu.c 599 */[];
	pud_t cocci_id/* arch/arm64/mm/mmu.c 59 */[PTRS_PER_PUD]__page_aligned_bss __maybe_unused;
	pmd_t cocci_id/* arch/arm64/mm/mmu.c 58 */[PTRS_PER_PMD]__page_aligned_bss __maybe_unused;
	pte_t cocci_id/* arch/arm64/mm/mmu.c 57 */[PTRS_PER_PTE]__page_aligned_bss;
	char *cocci_id/* arch/arm64/mm/mmu.c 564 */;
	struct vm_struct *cocci_id/* arch/arm64/mm/mmu.c 540 */;
	unsigned long cocci_id/* arch/arm64/mm/mmu.c 54 */[PAGE_SIZE / sizeof(unsigned long)]__page_aligned_bss;
	struct memblock_region *cocci_id/* arch/arm64/mm/mmu.c 462 */;
	void __init cocci_id/* arch/arm64/mm/mmu.c 441 */;
	bool cocci_id/* arch/arm64/mm/mmu.c 412 */;
	struct mm_struct *cocci_id/* arch/arm64/mm/mmu.c 410 */;
	void *cocci_id/* arch/arm64/mm/mmu.c 365 */;
	int cocci_id/* arch/arm64/mm/mmu.c 339 */;
	phys_addr_t (*cocci_id/* arch/arm64/mm/mmu.c 338 */)(int);
	pgprot_t cocci_id/* arch/arm64/mm/mmu.c 337 */;
	unsigned long cocci_id/* arch/arm64/mm/mmu.c 336 */;
	phys_addr_t cocci_id/* arch/arm64/mm/mmu.c 335 */;
	pgd_t *cocci_id/* arch/arm64/mm/mmu.c 335 */;
	void cocci_id/* arch/arm64/mm/mmu.c 335 */;
	pgd_t cocci_id/* arch/arm64/mm/mmu.c 292 */;
	pud_t cocci_id/* arch/arm64/mm/mmu.c 242 */;
	pud_t *cocci_id/* arch/arm64/mm/mmu.c 236 */;
	pmd_t cocci_id/* arch/arm64/mm/mmu.c 171 */;
	pmd_t *cocci_id/* arch/arm64/mm/mmu.c 164 */;
	pte_t cocci_id/* arch/arm64/mm/mmu.c 147 */;
	const pteval_t cocci_id/* arch/arm64/mm/mmu.c 123 */;
	struct zone *cocci_id/* arch/arm64/mm/mmu.c 1073 */;
	struct vmem_altmap *cocci_id/* arch/arm64/mm/mmu.c 1069 */;
	struct mhp_restrictions *cocci_id/* arch/arm64/mm/mmu.c 1053 */;
	u64 cocci_id/* arch/arm64/mm/mmu.c 1052 */;
	p4d_t *cocci_id/* arch/arm64/mm/mmu.c 1046 */;
}
