cocci_test_suite() {
	int cocci_id/* lib/lz4/lz4hc_compress.c 99 */;
	U16 cocci_id/* lib/lz4/lz4hc_compress.c 90 */;
	size_t cocci_id/* lib/lz4/lz4hc_compress.c 85 */;
	const U32 cocci_id/* lib/lz4/lz4hc_compress.c 80 */;
	U32 cocci_id/* lib/lz4/lz4hc_compress.c 80 */;
	const BYTE *constcocci_id/* lib/lz4/lz4hc_compress.c 79 */;
	U32 *constcocci_id/* lib/lz4/lz4hc_compress.c 78 */;
	U16 *constcocci_id/* lib/lz4/lz4hc_compress.c 77 */;
	const BYTE *cocci_id/* lib/lz4/lz4hc_compress.c 75 */;
	LZ4HC_CCtx_internal *cocci_id/* lib/lz4/lz4hc_compress.c 74 */;
	void cocci_id/* lib/lz4/lz4hc_compress.c 74 */;
	const char *cocci_id/* lib/lz4/lz4hc_compress.c 669 */;
	LZ4_streamHC_t *cocci_id/* lib/lz4/lz4hc_compress.c 668 */;
	void *cocci_id/* lib/lz4/lz4hc_compress.c 63 */;
	BYTE cocci_id/* lib/lz4/lz4hc_compress.c 570 */;
	char *cocci_id/* lib/lz4/lz4hc_compress.c 559 */;
	const void *cocci_id/* lib/lz4/lz4hc_compress.c 53 */;
	unsigned int cocci_id/* lib/lz4/lz4hc_compress.c 357 */;
	BYTE *constcocci_id/* lib/lz4/lz4hc_compress.c 355 */;
	BYTE *cocci_id/* lib/lz4/lz4hc_compress.c 354 */;
	limitedOutput_directive cocci_id/* lib/lz4/lz4hc_compress.c 345 */;
	char *constcocci_id/* lib/lz4/lz4hc_compress.c 341 */;
	const char *constcocci_id/* lib/lz4/lz4hc_compress.c 340 */;
	LZ4HC_CCtx_internal *constcocci_id/* lib/lz4/lz4hc_compress.c 339 */;
	BYTE **cocci_id/* lib/lz4/lz4hc_compress.c 264 */;
	const size_t cocci_id/* lib/lz4/lz4hc_compress.c 130 */;
	const int cocci_id/* lib/lz4/lz4hc_compress.c 104 */;
	const BYTE **cocci_id/* lib/lz4/lz4hc_compress.c 103 */;
}
