cocci_test_suite() {
	struct se_wwn cocci_id/* drivers/target/target_core_fabric_configfs.c 958 */;
	struct se_wwn *cocci_id/* drivers/target/target_core_fabric_configfs.c 957 */;
	struct target_fabric_configfs cocci_id/* drivers/target/target_core_fabric_configfs.c 928 */;
	struct se_portal_group cocci_id/* drivers/target/target_core_fabric_configfs.c 882 */;
	struct se_portal_group *cocci_id/* drivers/target/target_core_fabric_configfs.c 881 */;
	struct configfs_group_operations cocci_id/* drivers/target/target_core_fabric_configfs.c 789 */;
	bool cocci_id/* drivers/target/target_core_fabric_configfs.c 75 */;
	int cocci_id/* drivers/target/target_core_fabric_configfs.c 748 */;
	unsigned long long cocci_id/* drivers/target/target_core_fabric_configfs.c 747 */;
	struct se_dev_entry *cocci_id/* drivers/target/target_core_fabric_configfs.c 69 */;
	struct se_device cocci_id/* drivers/target/target_core_fabric_configfs.c 636 */;
	struct se_device *cocci_id/* drivers/target/target_core_fabric_configfs.c 627 */;
	struct configfs_attribute **cocci_id/* drivers/target/target_core_fabric_configfs.c 52 */;
	struct se_lun cocci_id/* drivers/target/target_core_fabric_configfs.c 514 */;
	struct se_lun *cocci_id/* drivers/target/target_core_fabric_configfs.c 512 */;
	struct config_item *cocci_id/* drivers/target/target_core_fabric_configfs.c 512 */;
	struct se_tpg_np *cocci_id/* drivers/target/target_core_fabric_configfs.c 473 */;
	struct se_tpg_np cocci_id/* drivers/target/target_core_fabric_configfs.c 449 */;
	struct se_node_acl cocci_id/* drivers/target/target_core_fabric_configfs.c 425 */;
	struct se_node_acl *cocci_id/* drivers/target/target_core_fabric_configfs.c 424 */;
	struct config_item_type *cocci_id/* drivers/target/target_core_fabric_configfs.c 39 */;
	struct target_fabric_configfs *cocci_id/* drivers/target/target_core_fabric_configfs.c 37 */;
	void cocci_id/* drivers/target/target_core_fabric_configfs.c 37 */;
	char *cocci_id/* drivers/target/target_core_fabric_configfs.c 273 */;
	const char *cocci_id/* drivers/target/target_core_fabric_configfs.c 236 */;
	struct config_group *cocci_id/* drivers/target/target_core_fabric_configfs.c 234 */;
	struct configfs_item_operations cocci_id/* drivers/target/target_core_fabric_configfs.c 221 */;
	struct configfs_attribute *cocci_id/* drivers/target/target_core_fabric_configfs.c 207 */[];
	unsigned long cocci_id/* drivers/target/target_core_fabric_configfs.c 183 */;
	size_t cocci_id/* drivers/target/target_core_fabric_configfs.c 178 */;
	ssize_t cocci_id/* drivers/target/target_core_fabric_configfs.c 159 */;
	struct se_lun_acl cocci_id/* drivers/target/target_core_fabric_configfs.c 155 */;
	struct se_lun_acl *cocci_id/* drivers/target/target_core_fabric_configfs.c 153 */;
}
