cocci_test_suite() {
	void __exit cocci_id/* drivers/target/target_core_file.c 951 */;
	int __init cocci_id/* drivers/target/target_core_file.c 946 */;
	struct inode *cocci_id/* drivers/target/target_core_file.c 93 */;
	const struct target_backend_ops cocci_id/* drivers/target/target_core_file.c 924 */;
	struct file *cocci_id/* drivers/target/target_core_file.c 92 */;
	struct sbc_ops cocci_id/* drivers/target/target_core_file.c 911 */;
	unsigned char *cocci_id/* drivers/target/target_core_file.c 874 */;
	char cocci_id/* drivers/target/target_core_file.c 841 */[FD_MAX_DEV_PROT_NAME];
	struct fd_host *cocci_id/* drivers/target/target_core_file.c 73 */;
	substring_t cocci_id/* drivers/target/target_core_file.c 719 */[MAX_OPT_ARGS];
	char *cocci_id/* drivers/target/target_core_file.c 718 */;
	match_table_t cocci_id/* drivers/target/target_core_file.c 706 */;
	enum{Opt_fd_dev_name, Opt_fd_dev_size, Opt_fd_buffered_io, Opt_fd_async_io, Opt_err,} cocci_id/* drivers/target/target_core_file.c 701 */;
	const char *cocci_id/* drivers/target/target_core_file.c 70 */;
	struct se_hba *cocci_id/* drivers/target/target_core_file.c 70 */;
	enum dma_data_direction cocci_id/* drivers/target/target_core_file.c 680 */;
	sense_reason_t cocci_id/* drivers/target/target_core_file.c 678 */;
	unsigned int cocci_id/* drivers/target/target_core_file.c 578 */;
	struct block_device *cocci_id/* drivers/target/target_core_file.c 562 */;
	unsigned long cocci_id/* drivers/target/target_core_file.c 538 */;
	struct se_cmd *cocci_id/* drivers/target/target_core_file.c 524 */;
	ssize_t cocci_id/* drivers/target/target_core_file.c 511 */;
	loff_t cocci_id/* drivers/target/target_core_file.c 500 */;
	void *cocci_id/* drivers/target/target_core_file.c 495 */;
	size_t cocci_id/* drivers/target/target_core_file.c 495 */;
	sector_t cocci_id/* drivers/target/target_core_file.c 494 */;
	struct fd_host cocci_id/* drivers/target/target_core_file.c 40 */;
	u32 cocci_id/* drivers/target/target_core_file.c 36 */;
	int cocci_id/* drivers/target/target_core_file.c 36 */;
	struct fd_dev cocci_id/* drivers/target/target_core_file.c 33 */;
	struct bio_vec cocci_id/* drivers/target/target_core_file.c 329 */;
	struct bio_vec *cocci_id/* drivers/target/target_core_file.c 324 */;
	struct iov_iter cocci_id/* drivers/target/target_core_file.c 323 */;
	struct scatterlist *cocci_id/* drivers/target/target_core_file.c 319 */;
	struct se_device *cocci_id/* drivers/target/target_core_file.c 31 */;
	struct fd_dev *cocci_id/* drivers/target/target_core_file.c 31 */;
	struct target_core_file_cmd cocci_id/* drivers/target/target_core_file.c 250 */;
	struct target_core_file_cmd *cocci_id/* drivers/target/target_core_file.c 248 */;
	struct kiocb *cocci_id/* drivers/target/target_core_file.c 246 */;
	long cocci_id/* drivers/target/target_core_file.c 246 */;
	void cocci_id/* drivers/target/target_core_file.c 246 */;
	struct target_core_file_cmd {
		unsigned long len;
		struct se_cmd *cmd;
		struct kiocb iocb;
	} cocci_id/* drivers/target/target_core_file.c 240 */;
	struct se_device cocci_id/* drivers/target/target_core_file.c 219 */;
	struct rcu_head *cocci_id/* drivers/target/target_core_file.c 217 */;
	unsigned long long cocci_id/* drivers/target/target_core_file.c 137 */;
	struct request_queue *cocci_id/* drivers/target/target_core_file.c 136 */;
}
