cocci_test_suite() {
	wait_queue_head_t cocci_id/* mm/filemap.c 998 */[PAGE_WAIT_TABLE_SIZE]__cacheline_aligned;
	void *cocci_id/* mm/filemap.c 859 */;
	struct mem_cgroup *cocci_id/* mm/filemap.c 857 */;
	void **cocci_id/* mm/filemap.c 853 */;
	pgoff_t cocci_id/* mm/filemap.c 852 */;
	gfp_t cocci_id/* mm/filemap.c 852 */;
	struct address_space *cocci_id/* mm/filemap.c 851 */;
	struct page *cocci_id/* mm/filemap.c 850 */;
	int cocci_id/* mm/filemap.c 850 */;
	errseq_t cocci_id/* mm/filemap.c 702 */;
	unsigned cocci_id/* mm/filemap.c 516 */;
	struct pagevec cocci_id/* mm/filemap.c 508 */;
	loff_t cocci_id/* mm/filemap.c 504 */;
	struct writeback_control cocci_id/* mm/filemap.c 409 */;
	struct address_space *const cocci_id/* mm/filemap.c 3498 */;
	struct pagevec *cocci_id/* mm/filemap.c 343 */;
	struct inode *cocci_id/* mm/filemap.c 3377 */;
	struct file *cocci_id/* mm/filemap.c 3375 */;
	struct kiocb *cocci_id/* mm/filemap.c 3373 */;
	struct iov_iter *cocci_id/* mm/filemap.c 3373 */;
	ssize_t cocci_id/* mm/filemap.c 3373 */;
	const struct address_space_operations *cocci_id/* mm/filemap.c 3272 */;
	size_t cocci_id/* mm/filemap.c 3172 */;
	char *cocci_id/* mm/filemap.c 3151 */;
	char cocci_id/* mm/filemap.c 3149 */[128];
	uint64_t cocci_id/* mm/filemap.c 3082 */;
	size_t *cocci_id/* mm/filemap.c 3078 */;
	int (*cocci_id/* mm/filemap.c 2758 */)(void *, struct page *);
	struct vm_area_struct *cocci_id/* mm/filemap.c 2705 */;
	const struct vm_operations_struct cocci_id/* mm/filemap.c 2697 */;
	vm_fault_t cocci_id/* mm/filemap.c 2476 */;
	void (*cocci_id/* mm/filemap.c 244 */)(struct page *);
	struct file_ra_state *cocci_id/* mm/filemap.c 2435 */;
	struct vm_fault *cocci_id/* mm/filemap.c 2431 */;
	struct file **cocci_id/* mm/filemap.c 2344 */;
	void cocci_id/* mm/filemap.c 231 */;
	loff_t *cocci_id/* mm/filemap.c 2016 */;
	xa_mark_t cocci_id/* mm/filemap.c 1914 */;
	pgoff_t *cocci_id/* mm/filemap.c 1726 */;
	struct page **cocci_id/* mm/filemap.c 1726 */;
	unsigned int cocci_id/* mm/filemap.c 1409 */;
	struct mm_struct *cocci_id/* mm/filemap.c 1408 */;
	wait_queue_head_t *cocci_id/* mm/filemap.c 1382 */;
	bool cocci_id/* mm/filemap.c 1287 */;
	volatile void *cocci_id/* mm/filemap.c 1287 */;
	long cocci_id/* mm/filemap.c 1287 */;
	unsigned long cocci_id/* mm/filemap.c 1264 */;
	wait_queue_entry_t *cocci_id/* mm/filemap.c 1261 */;
	struct wait_page_queue cocci_id/* mm/filemap.c 1134 */;
	enum behavior cocci_id/* mm/filemap.c 1132 */;
	enum behavior{EXCLUSIVE, SHARED, DROP,} cocci_id/* mm/filemap.c 1119 */;
	wait_queue_entry_t cocci_id/* mm/filemap.c 1060 */;
	struct wait_page_key cocci_id/* mm/filemap.c 1058 */;
	struct wait_page_queue *cocci_id/* mm/filemap.c 1031 */;
	struct wait_page_key *cocci_id/* mm/filemap.c 1030 */;
	struct wait_page_queue {
		struct page *page;
		int bit_nr;
		wait_queue_entry_t wait;
	} cocci_id/* mm/filemap.c 1022 */;
	struct wait_page_key {
		struct page *page;
		int bit_nr;
		int page_match;
	} cocci_id/* mm/filemap.c 1016 */;
	void __init cocci_id/* mm/filemap.c 1005 */;
}
