cocci_test_suite() {
	struct address_space *cocci_id/* mm/compaction.c 98 */;
	struct page *cocci_id/* mm/compaction.c 96 */;
	int cocci_id/* mm/compaction.c 96 */;
	struct lruvec *cocci_id/* mm/compaction.c 787 */;
	isolate_mode_t cocci_id/* mm/compaction.c 783 */;
	const unsigned int cocci_id/* mm/compaction.c 581 */;
	bool *cocci_id/* mm/compaction.c 513 */;
	spinlock_t *cocci_id/* mm/compaction.c 482 */;
	unsigned long *cocci_id/* mm/compaction.c 482 */;
	long cocci_id/* mm/compaction.c 34 */;
	enum vm_event_item cocci_id/* mm/compaction.c 29 */;
	int __init cocci_id/* mm/compaction.c 2716 */;
	const struct cpumask *cocci_id/* mm/compaction.c 2633 */;
	struct task_struct *cocci_id/* mm/compaction.c 2631 */;
	enum zone_type cocci_id/* mm/compaction.c 2504 */;
	struct node *cocci_id/* mm/compaction.c 2484 */;
	const char *cocci_id/* mm/compaction.c 2469 */;
	size_t cocci_id/* mm/compaction.c 2469 */;
	struct device_attribute *cocci_id/* mm/compaction.c 2468 */;
	struct device *cocci_id/* mm/compaction.c 2467 */;
	ssize_t cocci_id/* mm/compaction.c 2467 */;
	loff_t *cocci_id/* mm/compaction.c 2458 */;
	size_t *cocci_id/* mm/compaction.c 2458 */;
	void __user *cocci_id/* mm/compaction.c 2458 */;
	struct ctl_table *cocci_id/* mm/compaction.c 2457 */;
	struct compact_control cocci_id/* mm/compaction.c 2414 */;
	pg_data_t *cocci_id/* mm/compaction.c 2411 */;
	const struct alloc_context *cocci_id/* mm/compaction.c 2340 */;
	struct capture_control cocci_id/* mm/compaction.c 2308 */;
	struct page **cocci_id/* mm/compaction.c 2291 */;
	gfp_t cocci_id/* mm/compaction.c 2289 */;
	enum compact_priority cocci_id/* mm/compaction.c 2289 */;
	const bool cocci_id/* mm/compaction.c 2078 */;
	struct capture_control *cocci_id/* mm/compaction.c 2072 */;
	struct zoneref *cocci_id/* mm/compaction.c 2043 */;
	struct alloc_context *cocci_id/* mm/compaction.c 2039 */;
	struct zone *cocci_id/* mm/compaction.c 1958 */;
	bool cocci_id/* mm/compaction.c 1891 */;
	struct free_area *cocci_id/* mm/compaction.c 1890 */;
	const int cocci_id/* mm/compaction.c 1852 */;
	unsigned int cocci_id/* mm/compaction.c 1851 */;
	enum compact_result cocci_id/* mm/compaction.c 1849 */;
	struct compact_control *cocci_id/* mm/compaction.c 1849 */;
	const isolate_mode_t cocci_id/* mm/compaction.c 1747 */;
	isolate_migrate_t cocci_id/* mm/compaction.c 1741 */;
	struct list_head *cocci_id/* mm/compaction.c 1677 */;
	enum{ISOLATE_ABORT, ISOLATE_NONE, ISOLATE_SUCCESS,} cocci_id/* mm/compaction.c 1583 */;
	struct page cocci_id/* mm/compaction.c 1562 */;
	void *cocci_id/* mm/compaction.c 129 */;
	unsigned long cocci_id/* mm/compaction.c 129 */;
	void cocci_id/* mm/compaction.c 120 */;
	unsigned short cocci_id/* mm/compaction.c 1171 */;
}
