cocci_test_suite() {
	const size_t cocci_id/* security/tomoyo/gc.c 74 */;
	bool cocci_id/* security/tomoyo/gc.c 71 */;
	const char *cocci_id/* security/tomoyo/gc.c 71 */;
	const bool cocci_id/* security/tomoyo/gc.c 650 */;
	struct tomoyo_io_buffer *cocci_id/* security/tomoyo/gc.c 621 */;
	void *cocci_id/* security/tomoyo/gc.c 612 */;
	struct tomoyo_group *cocci_id/* security/tomoyo/gc.c 564 */;
	struct tomoyo_shared_acl_head *cocci_id/* security/tomoyo/gc.c 550 */;
	struct tomoyo_domain_info *cocci_id/* security/tomoyo/gc.c 532 */;
	struct tomoyo_policy_namespace *cocci_id/* security/tomoyo/gc.c 528 */;
	enum tomoyo_policy_id cocci_id/* security/tomoyo/gc.c 527 */;
	int cocci_id/* security/tomoyo/gc.c 526 */;
	struct tomoyo_acl_info *cocci_id/* security/tomoyo/gc.c 508 */;
	struct list_head *cocci_id/* security/tomoyo/gc.c 506 */;
	void cocci_id/* security/tomoyo/gc.c 506 */;
	struct tomoyo_acl_head *cocci_id/* security/tomoyo/gc.c 488 */;
	const enum tomoyo_policy_id cocci_id/* security/tomoyo/gc.c 485 */;
	typeof(struct tomoyo_domain_info) cocci_id/* security/tomoyo/gc.c 452 */;
	typeof(struct tomoyo_name) cocci_id/* security/tomoyo/gc.c 438 */;
	const struct list_head *cocci_id/* security/tomoyo/gc.c 40 */;
	typeof(*group) cocci_id/* security/tomoyo/gc.c 347 */;
	typeof(*member) cocci_id/* security/tomoyo/gc.c 332 */;
	struct tomoyo_path_group *cocci_id/* security/tomoyo/gc.c 331 */;
	const struct tomoyo_envp *cocci_id/* security/tomoyo/gc.c 295 */;
	const struct tomoyo_argv *cocci_id/* security/tomoyo/gc.c 293 */;
	struct tomoyo_name_union *cocci_id/* security/tomoyo/gc.c 291 */;
	struct tomoyo_number_union *cocci_id/* security/tomoyo/gc.c 289 */;
	const struct tomoyo_condition_element *cocci_id/* security/tomoyo/gc.c 287 */;
	unsigned int cocci_id/* security/tomoyo/gc.c 286 */;
	const u16 cocci_id/* security/tomoyo/gc.c 281 */;
	typeof(*cond) cocci_id/* security/tomoyo/gc.c 279 */;
	struct tomoyo_condition *cocci_id/* security/tomoyo/gc.c 279 */;
	typeof(*domain) cocci_id/* security/tomoyo/gc.c 254 */;
	struct tomoyo_task_acl *cocci_id/* security/tomoyo/gc.c 233 */;
	struct tomoyo_unix_acl *cocci_id/* security/tomoyo/gc.c 225 */;
	struct tomoyo_inet_acl *cocci_id/* security/tomoyo/gc.c 216 */;
	struct tomoyo_env_acl *cocci_id/* security/tomoyo/gc.c 208 */;
	struct tomoyo_mount_acl *cocci_id/* security/tomoyo/gc.c 198 */;
	struct tomoyo_mkdev_acl *cocci_id/* security/tomoyo/gc.c 188 */;
	struct tomoyo_path_number_acl *cocci_id/* security/tomoyo/gc.c 180 */;
	struct tomoyo_path2_acl *cocci_id/* security/tomoyo/gc.c 172 */;
	typeof(*entry) cocci_id/* security/tomoyo/gc.c 166 */;
	struct tomoyo_path_acl *cocci_id/* security/tomoyo/gc.c 165 */;
	typeof(*acl) cocci_id/* security/tomoyo/gc.c 159 */;
	struct tomoyo_manager *cocci_id/* security/tomoyo/gc.c 143 */;
	typeof(*ptr) cocci_id/* security/tomoyo/gc.c 128 */;
	struct tomoyo_aggregator *cocci_id/* security/tomoyo/gc.c 127 */;
	struct tomoyo_transition_control *cocci_id/* security/tomoyo/gc.c 111 */;
}
