cocci_test_suite() {
	bool __init cocci_id/* security/security.c 98 */;
	struct qstr *cocci_id/* security/security.c 961 */;
	const struct qstr *cocci_id/* security/security.c 952 */;
	struct rcu_head *cocci_id/* security/security.c 925 */;
	void **cocci_id/* security/security.c 895 */;
	unsigned long *cocci_id/* security/security.c 887 */;
	const struct super_block *cocci_id/* security/security.c 884 */;
	struct vfsmount *cocci_id/* security/security.c 863 */;
	struct seq_file *cocci_id/* security/security.c 847 */;
	struct fs_parameter *cocci_id/* security/security.c 805 */;
	struct fs_context *cocci_id/* security/security.c 800 */;
	struct linux_binprm *cocci_id/* security/security.c 780 */;
	struct mm_struct *cocci_id/* security/security.c 752 */;
	const struct timezone *cocci_id/* security/security.c 747 */;
	const struct timespec64 *cocci_id/* security/security.c 747 */;
	struct super_block *cocci_id/* security/security.c 732 */;
	struct user_namespace *cocci_id/* security/security.c 725 */;
	const struct cred *cocci_id/* security/security.c 724 */;
	const kernel_cap_t *cocci_id/* security/security.c 716 */;
	kernel_cap_t *cocci_id/* security/security.c 707 */;
	struct task_struct *cocci_id/* security/security.c 631 */;
	struct msg_msg *cocci_id/* security/security.c 612 */;
	struct kern_ipc_perm *cocci_id/* security/security.c 591 */;
	bool cocci_id/* security/security.c 57 */;
	struct inode *cocci_id/* security/security.c 549 */;
	struct file *cocci_id/* security/security.c 528 */;
	const char *const cocci_id/* security/security.c 51 */;
	gfp_t cocci_id/* security/security.c 493 */;
	struct cred *cocci_id/* security/security.c 493 */;
	struct notifier_block *cocci_id/* security/security.c 470 */;
	enum lsm_event cocci_id/* security/security.c 463 */;
	void *cocci_id/* security/security.c 463 */;
	int cocci_id/* security/security.c 463 */;
	struct lsm_blob_sizes cocci_id/* security/security.c 45 */;
	struct security_hook_list *cocci_id/* security/security.c 443 */;
	char **cocci_id/* security/security.c 414 */;
	struct kmem_cache *cocci_id/* security/security.c 41 */;
	char *cocci_id/* security/security.c 384 */;
	int __init cocci_id/* security/security.c 384 */;
	struct security_hook_heads cocci_id/* security/security.c 38 */;
	struct hlist_head cocci_id/* security/security.c 335 */;
	struct hlist_head *cocci_id/* security/security.c 332 */;
	void cocci_id/* security/security.c 329 */;
	int cocci_id/* security/security.c 281 */(const char *new,
						  char **result);
	void __init cocci_id/* security/security.c 279 */(struct task_struct *task);
	void __init cocci_id/* security/security.c 278 */(struct cred *cred);
	struct perf_event *cocci_id/* security/security.c 2414 */;
	struct perf_event_attr *cocci_id/* security/security.c 2409 */;
	enum lockdown_reason cocci_id/* security/security.c 2402 */;
	struct bpf_prog_aux *cocci_id/* security/security.c 2388 */;
	struct bpf_prog *cocci_id/* security/security.c 2380 */;
	fmode_t cocci_id/* security/security.c 2376 */;
	struct bpf_map *cocci_id/* security/security.c 2376 */;
	union bpf_attr *cocci_id/* security/security.c 2372 */;
	unsigned int cocci_id/* security/security.c 2372 */;
	struct audit_krule *cocci_id/* security/security.c 2355 */;
	u32 cocci_id/* security/security.c 2350 */;
	key_ref_t cocci_id/* security/security.c 2334 */;
	struct key *cocci_id/* security/security.c 2323 */;
	const struct flowi *cocci_id/* security/security.c 2283 */;
	struct xfrm_policy *cocci_id/* security/security.c 2282 */;
	struct xfrm_state *cocci_id/* security/security.c 2252 */;
	struct xfrm_sec_ctx *cocci_id/* security/security.c 2235 */;
	struct xfrm_user_sec_ctx *cocci_id/* security/security.c 2228 */;
	struct xfrm_sec_ctx **cocci_id/* security/security.c 2227 */;
	u8 cocci_id/* security/security.c 2206 */;
	u64 cocci_id/* security/security.c 2200 */;
	u16 cocci_id/* security/security.c 2200 */;
	struct sockaddr *cocci_id/* security/security.c 2182 */;
	struct sctp_endpoint *cocci_id/* security/security.c 2175 */;
	struct sk_buff *cocci_id/* security/security.c 2115 */;
	struct sock *cocci_id/* security/security.c 2114 */;
	const struct request_sock *cocci_id/* security/security.c 2109 */;
	struct request_sock *cocci_id/* security/security.c 2102 */;
	struct socket *cocci_id/* security/security.c 2095 */;
	struct flowi *cocci_id/* security/security.c 2089 */;
	const struct sock *cocci_id/* security/security.c 2077 */;
	int __user *cocci_id/* security/security.c 2054 */;
	struct msghdr *cocci_id/* security/security.c 2016 */;
	struct dentry *cocci_id/* security/security.c 1870 */;
	struct sembuf *cocci_id/* security/security.c 1864 */;
	char __user *cocci_id/* security/security.c 1830 */;
	long cocci_id/* security/security.c 1796 */;
	short cocci_id/* security/security.c 1730 */;
	struct kernel_siginfo *cocci_id/* security/security.c 1701 */;
	struct rlimit *cocci_id/* security/security.c 1681 */;
	struct rcu_head cocci_id/* security/security.c 168 */;
	pid_t cocci_id/* security/security.c 1637 */;
	enum kernel_load_data_id cocci_id/* security/security.c 1620 */;
	enum kernel_read_file_id cocci_id/* security/security.c 1609 */;
	loff_t cocci_id/* security/security.c 1608 */;
	u32 *cocci_id/* security/security.c 1570 */;
	struct lsm_blob_sizes *cocci_id/* security/security.c 156 */;
	struct fown_struct *cocci_id/* security/security.c 1483 */;
	struct vm_area_struct *cocci_id/* security/security.c 1461 */;
	int *cocci_id/* security/security.c 145 */;
	unsigned cocci_id/* security/security.c 1434 */;
	unsigned long cocci_id/* security/security.c 1412 */;
	struct kernfs_node *cocci_id/* security/security.c 1365 */;
	struct cred **cocci_id/* security/security.c 1353 */;
	size_t cocci_id/* security/security.c 1340 */;
	const void *cocci_id/* security/security.c 1250 */;
	const struct path *cocci_id/* security/security.c 1218 */;
	struct iattr *cocci_id/* security/security.c 1205 */;
	dev_t cocci_id/* security/security.c 1157 */;
	umode_t cocci_id/* security/security.c 1111 */;
	const char *cocci_id/* security/security.c 111 */;
	struct lsm_info *cocci_id/* security/security.c 111 */;
	void __init cocci_id/* security/security.c 111 */;
	kuid_t cocci_id/* security/security.c 1098 */;
	kgid_t cocci_id/* security/security.c 1098 */;
	size_t *cocci_id/* security/security.c 1006 */;
	const char **cocci_id/* security/security.c 1005 */;
	struct lsm_info **cocci_id/* security/security.c 100 */;
}
