cocci_test_suite() {
	struct iscsi_np *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 60 */;
	enum iscsit_transport_type cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 40 */;
	struct iscsi_tpg_np cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 256 */;
	char cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 164 */[MAX_PORTAL_LEN + 1];
	struct sockaddr_storage cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 162 */;
	struct iscsi_tpg_np *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 160 */;
	struct config_group *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 156 */;
	struct se_tpg_np *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 154 */;
	struct iscsi_node_acl cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1529 */;
	const struct target_core_fabric_ops cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1525 */;
	struct iscsi_node_acl *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1502 */;
	struct se_node_acl *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1500 */;
	struct iscsi_portal_group cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1414 */;
	struct se_portal_group *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1412 */;
	void cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1405 */;
	struct iscsi_conn *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1367 */;
	unsigned char *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1354 */;
	struct iscsi_session *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1347 */;
	struct se_session *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1345 */;
	struct iscsi_cmd cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1340 */;
	struct iscsi_cmd *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1340 */;
	struct se_cmd *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1338 */;
	struct configfs_attribute *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1324 */[];
	int cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1272 */;
	u32 cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1271 */;
	struct iscsi_portal_group *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1270 */;
	struct iscsi_param *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1269 */;
	const char *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1267 */;
	size_t cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1267 */;
	struct iscsi_node_auth *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1261 */;
	char *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1259 */;
	struct config_item *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1258 */;
	ssize_t cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1258 */;
	struct iscsi_tiqn cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1183 */;
	struct iscsi_tiqn *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1183 */;
	struct se_wwn *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1181 */;
	struct target_fabric_configfs *cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1165 */;
	u16 cocci_id/* drivers/target/iscsi/iscsi_target_configfs.c 1092 */;
}
