cocci_test_suite() {
	snd_pcm_uframes_t cocci_id/* sound/pci/cmipci.c 986 */;
	size_t cocci_id/* sound/pci/cmipci.c 930 */;
	struct cmipci_pcm *cocci_id/* sound/pci/cmipci.c 726 */;
	const struct snd_pcm_hw_constraint_list cocci_id/* sound/pci/cmipci.c 710 */;
	const unsigned int cocci_id/* sound/pci/cmipci.c 709 */[];
	struct snd_pcm_hw_params *cocci_id/* sound/pci/cmipci.c 670 */;
	int *cocci_id/* sound/pci/cmipci.c 609 */;
	unsigned int cocci_id/* sound/pci/cmipci.c 589 */[];
	bool cocci_id/* sound/pci/cmipci.c 56 */;
	unsigned short cocci_id/* sound/pci/cmipci.c 518 */;
	long cocci_id/* sound/pci/cmipci.c 46 */[SNDRV_CARDS];
	struct cmipci {
		struct snd_card *card;
		struct pci_dev *pci;
		unsigned int device;
		int irq;
		unsigned long iobase;
		unsigned int ctrl;
		struct snd_pcm *pcm;
		struct snd_pcm *pcm2;
		struct snd_pcm *pcm_spdif;
		int chip_version;
		int max_channels;
		unsigned int can_ac3_sw:1;
		unsigned int can_ac3_hw:1;
		unsigned int can_multi_ch:1;
		unsigned int can_96k:1;
		unsigned int do_soft_ac3:1;
		unsigned int spdif_playback_avail:1;
		unsigned int spdif_playback_enabled:1;
		int spdif_counter;
		unsigned int dig_status;
		unsigned int dig_pcm_status;
		struct snd_pcm_hardware *hw_info[3];
		int opened[2];
		struct mutex open_mutex;
		unsigned int mixer_insensitive:1;
		struct snd_kcontrol *mixer_res_ctl[CM_SAVED_MIXERS];
		int mixer_res_status[CM_SAVED_MIXERS];
		struct cmipci_pcm channel[2];
		struct snd_rawmidi *rmidi;
#ifdef SUPPORT_JOYSTICK
		struct gameport *gameport;
#endif
		spinlock_t reg_lock;
#ifdef CONFIG_PM_SLEEP
		unsigned int saved_regs[0x20];
		unsigned char saved_mixers[0x20];
#endif
	} cocci_id/* sound/pci/cmipci.c 445 */;
	bool cocci_id/* sound/pci/cmipci.c 44 */[SNDRV_CARDS];
	const struct cmipci_mixer_auto_switches cocci_id/* sound/pci/cmipci.c 436 */[];
	struct cmipci_mixer_auto_switches {
		const char *name;
		int toggle_on;
	} cocci_id/* sound/pci/cmipci.c 432 */;
	char *cocci_id/* sound/pci/cmipci.c 43 */[SNDRV_CARDS];
	int cocci_id/* sound/pci/cmipci.c 42 */[SNDRV_CARDS];
	struct cmipci_pcm {
		struct snd_pcm_substream *substream;
		u8 running;
		u8 fmt;
		u8 is_dac;
		u8 needs_silencing;
		unsigned int dma_size;
		unsigned int shift;
		unsigned int ch;
		unsigned int offset;
	} cocci_id/* sound/pci/cmipci.c 419 */;
	struct pci_driver cocci_id/* sound/pci/cmipci.c 3377 */;
	struct device *cocci_id/* sound/pci/cmipci.c 3349 */;
	unsigned char cocci_id/* sound/pci/cmipci.c 3319 */[];
	const struct pci_device_id *cocci_id/* sound/pci/cmipci.c 3249 */;
	const struct pci_device_id cocci_id/* sound/pci/cmipci.c 3008 */[];
	char cocci_id/* sound/pci/cmipci.c 3006 */[16];
	long cocci_id/* sound/pci/cmipci.c 3004 */;
	struct snd_device_ops cocci_id/* sound/pci/cmipci.c 3000 */;
	struct cmipci **cocci_id/* sound/pci/cmipci.c 2996 */;
	struct snd_card *cocci_id/* sound/pci/cmipci.c 2995 */;
	struct pci_dev *cocci_id/* sound/pci/cmipci.c 2995 */;
	struct snd_opl3 *cocci_id/* sound/pci/cmipci.c 2945 */;
	struct snd_device *cocci_id/* sound/pci/cmipci.c 2935 */;
	struct resource *cocci_id/* sound/pci/cmipci.c 2852 */;
	struct gameport *cocci_id/* sound/pci/cmipci.c 2851 */;
	int cocci_id/* sound/pci/cmipci.c 2850 */[];
	struct snd_info_buffer *cocci_id/* sound/pci/cmipci.c 2763 */;
	struct snd_info_entry *cocci_id/* sound/pci/cmipci.c 2762 */;
	struct snd_ctl_elem_id cocci_id/* sound/pci/cmipci.c 2744 */;
	struct snd_kcontrol_new *cocci_id/* sound/pci/cmipci.c 2656 */;
	struct snd_kcontrol_new cocci_id/* sound/pci/cmipci.c 2649 */;
	struct snd_kcontrol_new cocci_id/* sound/pci/cmipci.c 2607 */[];
	const char *constcocci_id/* sound/pci/cmipci.c 2558 */[2];
	const char *constcocci_id/* sound/pci/cmipci.c 2503 */[3];
	unsigned char cocci_id/* sound/pci/cmipci.c 2393 */;
	struct cmipci *cocci_id/* sound/pci/cmipci.c 2339 */;
	unsigned int cocci_id/* sound/pci/cmipci.c 2338 */;
	struct cmipci_switch_args *cocci_id/* sound/pci/cmipci.c 2336 */;
	struct snd_ctl_elem_value *cocci_id/* sound/pci/cmipci.c 2335 */;
	struct snd_kcontrol *cocci_id/* sound/pci/cmipci.c 2334 */;
	int cocci_id/* sound/pci/cmipci.c 2334 */;
	struct cmipci_switch_args {
		int reg;
		unsigned int mask;
		unsigned int mask_on;
		unsigned int is_byte:1;
		unsigned int ac3_sensitive:1;
	} cocci_id/* sound/pci/cmipci.c 2322 */;
	struct cmipci_sb_reg cocci_id/* sound/pci/cmipci.c 2121 */;
	struct snd_ctl_elem_info *cocci_id/* sound/pci/cmipci.c 2108 */;
	struct cmipci_sb_reg *cocci_id/* sound/pci/cmipci.c 2011 */;
	unsigned long cocci_id/* sound/pci/cmipci.c 2011 */;
	struct cmipci_sb_reg {
		unsigned int left_reg,right_reg;
		unsigned int left_shift,right_shift;
		unsigned int mask;
		unsigned int invert:1;
		unsigned int stereo:1;
	} cocci_id/* sound/pci/cmipci.c 1988 */;
	struct snd_pcm *cocci_id/* sound/pci/cmipci.c 1912 */;
	const struct snd_pcm_ops cocci_id/* sound/pci/cmipci.c 1839 */;
	struct snd_pcm_runtime *cocci_id/* sound/pci/cmipci.c 1680 */;
	void cocci_id/* sound/pci/cmipci.c 1625 */;
	struct snd_pcm_substream *cocci_id/* sound/pci/cmipci.c 1598 */;
	const struct snd_pcm_hardware cocci_id/* sound/pci/cmipci.c 1487 */;
	irqreturn_t cocci_id/* sound/pci/cmipci.c 1430 */;
	void *cocci_id/* sound/pci/cmipci.c 1430 */;
	const struct snd_kcontrol_new cocci_id/* sound/pci/cmipci.c 1035 */;
}
