cocci_test_suite() {
	unsigned char cocci_id/* sound/isa/es18xx.c 996 */[4];
	unsigned char cocci_id/* sound/isa/es18xx.c 979 */[8];
	const char *const cocci_id/* sound/isa/es18xx.c 956 */[8];
	const char *const cocci_id/* sound/isa/es18xx.c 953 */[5];
	struct snd_pcm_substream *cocci_id/* sound/isa/es18xx.c 922 */;
	struct snd_pcm_runtime *cocci_id/* sound/isa/es18xx.c 893 */;
	struct snd_es18xx {
		unsigned long port;
		unsigned long ctrl_port;
		struct resource *res_port;
		struct resource *res_mpu_port;
		struct resource *res_ctrl_port;
		int irq;
		int dma1;
		int dma2;
		unsigned short version;
		int caps;
		unsigned short audio2_vol;
		unsigned short active;
		unsigned int dma1_shift;
		unsigned int dma2_shift;
		struct snd_pcm *pcm;
		struct snd_pcm_substream *playback_a_substream;
		struct snd_pcm_substream *capture_a_substream;
		struct snd_pcm_substream *playback_b_substream;
		struct snd_rawmidi *rmidi;
		struct snd_kcontrol *hw_volume;
		struct snd_kcontrol *hw_switch;
		struct snd_kcontrol *master_volume;
		struct snd_kcontrol *master_switch;
		spinlock_t reg_lock;
		spinlock_t mixer_lock;
#ifdef CONFIG_PM
		unsigned char pm_reg;
#endif
#ifdef CONFIG_PNP
		struct pnp_dev *dev;
		struct pnp_dev *devc;
#endif
	} cocci_id/* sound/isa/es18xx.c 87 */;
	const struct snd_pcm_hardware cocci_id/* sound/isa/es18xx.c 846 */;
	unsigned int cocci_id/* sound/isa/es18xx.c 817 */;
	snd_pcm_uframes_t cocci_id/* sound/isa/es18xx.c 814 */;
	irqreturn_t cocci_id/* sound/isa/es18xx.c 725 */;
	struct snd_pcm_hw_params *cocci_id/* sound/isa/es18xx.c 543 */;
	const struct snd_pcm_hw_constraint_ratnums cocci_id/* sound/isa/es18xx.c 372 */;
	const struct snd_ratnum cocci_id/* sound/isa/es18xx.c 357 */[2];
	void __exit cocci_id/* sound/isa/es18xx.c 2411 */;
	void cocci_id/* sound/isa/es18xx.c 2411 */;
	int cocci_id/* sound/isa/es18xx.c 2390 */;
	int __init cocci_id/* sound/isa/es18xx.c 2388 */;
	struct pnp_card_driver cocci_id/* sound/isa/es18xx.c 2375 */;
	unsigned long cocci_id/* sound/isa/es18xx.c 235 */;
	struct pnp_driver cocci_id/* sound/isa/es18xx.c 2313 */;
	pm_message_t cocci_id/* sound/isa/es18xx.c 2303 */;
	unsigned char cocci_id/* sound/isa/es18xx.c 230 */;
	struct snd_card *cocci_id/* sound/isa/es18xx.c 2270 */;
	const struct pnp_device_id *cocci_id/* sound/isa/es18xx.c 2266 */;
	struct isa_driver cocci_id/* sound/isa/es18xx.c 2250 */;
	unsigned long cocci_id/* sound/isa/es18xx.c 2216 */[];
	int cocci_id/* sound/isa/es18xx.c 2191 */[];
	struct snd_opl3 *cocci_id/* sound/isa/es18xx.c 2112 */;
	struct snd_es18xx cocci_id/* sound/isa/es18xx.c 2106 */;
	struct snd_card **cocci_id/* sound/isa/es18xx.c 2103 */;
	struct device *cocci_id/* sound/isa/es18xx.c 2102 */;
	unsigned long long cocci_id/* sound/isa/es18xx.c 2088 */;
	const struct pnp_card_device_id *cocci_id/* sound/isa/es18xx.c 2072 */;
	struct pnp_card_link *cocci_id/* sound/isa/es18xx.c 2071 */;
	const struct pnp_card_device_id cocci_id/* sound/isa/es18xx.c 2049 */[];
	struct pnp_dev *cocci_id/* sound/isa/es18xx.c 2041 */;
	struct snd_es18xx *cocci_id/* sound/isa/es18xx.c 2040 */;
	const struct pnp_device_id cocci_id/* sound/isa/es18xx.c 2004 */[];
	long cocci_id/* sound/isa/es18xx.c 1986 */;
	bool cocci_id/* sound/isa/es18xx.c 1980 */;
	int cocci_id/* sound/isa/es18xx.c 1973 */[SNDRV_CARDS];
	long cocci_id/* sound/isa/es18xx.c 1971 */[SNDRV_CARDS];
	bool cocci_id/* sound/isa/es18xx.c 1961 */[SNDRV_CARDS];
	char *cocci_id/* sound/isa/es18xx.c 1960 */[SNDRV_CARDS];
	struct snd_device_ops cocci_id/* sound/isa/es18xx.c 1772 */;
	struct snd_device *cocci_id/* sound/isa/es18xx.c 1760 */;
	void *cocci_id/* sound/isa/es18xx.c 1748 */;
	char cocci_id/* sound/isa/es18xx.c 1680 */[16];
	struct snd_pcm *cocci_id/* sound/isa/es18xx.c 1679 */;
	const struct snd_pcm_ops cocci_id/* sound/isa/es18xx.c 1665 */;
	struct snd_kcontrol_new cocci_id/* sound/isa/es18xx.c 1330 */;
	struct snd_kcontrol_new cocci_id/* sound/isa/es18xx.c 1260 */[];
	struct snd_kcontrol *cocci_id/* sound/isa/es18xx.c 1194 */;
	struct snd_ctl_elem_value *cocci_id/* sound/isa/es18xx.c 1194 */;
	struct snd_ctl_elem_info *cocci_id/* sound/isa/es18xx.c 1183 */;
}
