cocci_test_suite() {
	struct snd_pcm_mmap_control cocci_id/* sound/core/pcm.c 954 */;
	struct snd_pcm_mmap_status cocci_id/* sound/core/pcm.c 946 */;
	int __user *cocci_id/* sound/core/pcm.c 92 */;
	size_t cocci_id/* sound/core/pcm.c 888 */;
	struct snd_pcm_runtime *cocci_id/* sound/core/pcm.c 885 */;
	struct snd_pcm_substream **cocci_id/* sound/core/pcm.c 881 */;
	struct file *cocci_id/* sound/core/pcm.c 880 */;
	unsigned long cocci_id/* sound/core/pcm.c 85 */;
	unsigned int cocci_id/* sound/core/pcm.c 85 */;
	struct snd_ctl_file *cocci_id/* sound/core/pcm.c 84 */;
	struct snd_pcm_oss_setup *cocci_id/* sound/core/pcm.c 822 */;
	struct snd_device_ops cocci_id/* sound/core/pcm.c 709 */;
	struct snd_pcm *cocci_id/* sound/core/pcm.c 707 */;
	struct snd_pcm **cocci_id/* sound/core/pcm.c 705 */;
	bool cocci_id/* sound/core/pcm.c 704 */;
	const char *cocci_id/* sound/core/pcm.c 703 */;
	struct snd_card *cocci_id/* sound/core/pcm.c 703 */;
	int cocci_id/* sound/core/pcm.c 703 */;
	const struct device_type cocci_id/* sound/core/pcm.c 618 */;
	const struct dev_pm_ops cocci_id/* sound/core/pcm.c 613 */;
	struct snd_pcm_str cocci_id/* sound/core/pcm.c 605 */;
	struct snd_pcm_str *cocci_id/* sound/core/pcm.c 605 */;
	struct device *cocci_id/* sound/core/pcm.c 603 */;
	const struct attribute_group *cocci_id/* sound/core/pcm.c 596 */[];
	void (*cocci_id/* sound/core/pcm.c 542 */)(struct snd_info_entry *,
						   struct snd_info_buffer *);
	struct snd_pcm_substream *cocci_id/* sound/core/pcm.c 540 */;
	struct snd_info_entry *cocci_id/* sound/core/pcm.c 539 */;
	char cocci_id/* sound/core/pcm.c 507 */[16];
	char cocci_id/* sound/core/pcm.c 497 */[64];
	struct snd_pcm_status cocci_id/* sound/core/pcm.c 446 */;
	int cocci_id/* sound/core/pcm.c 36 */(struct snd_device *device);
	struct snd_pcm_info *cocci_id/* sound/core/pcm.c 333 */;
	struct snd_info_buffer *cocci_id/* sound/core/pcm.c 331 */;
	int cocci_id/* sound/core/pcm.c 33 */(struct snd_pcm *pcm);
	snd_pcm_state_t cocci_id/* sound/core/pcm.c 293 */;
	snd_pcm_subformat_t cocci_id/* sound/core/pcm.c 283 */;
	snd_pcm_access_t cocci_id/* sound/core/pcm.c 278 */;
	char *cocci_id/* sound/core/pcm.c 256 */[];
	snd_pcm_format_t cocci_id/* sound/core/pcm.c 220 */;
	void __exit cocci_id/* sound/core/pcm.c 1222 */;
	void cocci_id/* sound/core/pcm.c 1222 */;
	int __init cocci_id/* sound/core/pcm.c 1214 */;
	struct snd_pcm_notify *cocci_id/* sound/core/pcm.c 1132 */;
	struct snd_device *cocci_id/* sound/core/pcm.c 1086 */;
	const struct attribute_group cocci_id/* sound/core/pcm.c 1031 */;
	struct snd_pcm_info __user *cocci_id/* sound/core/pcm.c 103 */;
	struct attribute *cocci_id/* sound/core/pcm.c 1026 */[];
	const char *cocci_id/* sound/core/pcm.c 1011 */[SNDRV_PCM_CLASS_LAST + 1];
	struct device_attribute *cocci_id/* sound/core/pcm.c 1006 */;
	char *cocci_id/* sound/core/pcm.c 1006 */;
	ssize_t cocci_id/* sound/core/pcm.c 1005 */;
}
