cocci_test_suite() {
	struct snd_ctl_elem_info *cocci_id/* sound/soc/codecs/wm_adsp.c 950 */;
	struct wm_coeff_ctl cocci_id/* sound/soc/codecs/wm_adsp.c 928 */;
	struct wm_coeff_ctl *cocci_id/* sound/soc/codecs/wm_adsp.c 926 */;
	struct soc_bytes_ext *cocci_id/* sound/soc/codecs/wm_adsp.c 926 */;
	unsigned int cocci_id/* sound/soc/codecs/wm_adsp.c 893 */[];
	unsigned int *cocci_id/* sound/soc/codecs/wm_adsp.c 877 */;
	const struct soc_enum cocci_id/* sound/soc/codecs/wm_adsp.c 818 */[];
	struct soc_enum *cocci_id/* sound/soc/codecs/wm_adsp.c 782 */;
	void cocci_id/* sound/soc/codecs/wm_adsp.c 748 */;
	struct dentry *cocci_id/* sound/soc/codecs/wm_adsp.c 731 */;
	const struct {
		const char *name;
		const struct file_operations fops;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 708 */[];
	loff_t *cocci_id/* sound/soc/codecs/wm_adsp.c 690 */;
	struct file *cocci_id/* sound/soc/codecs/wm_adsp.c 688 */;
	ssize_t cocci_id/* sound/soc/codecs/wm_adsp.c 688 */;
	struct wm_coeff_ctl {
		const char *name;
		const char *fw_name;
		const char *subname;
		unsigned int subname_len;
		struct wm_adsp_alg_region alg_region;
		struct wm_coeff_ctl_ops ops;
		struct wm_adsp *dsp;
		unsigned int enabled:1;
		struct list_head list;
		void *cache;
		unsigned int offset;
		size_t len;
		unsigned int set:1;
		struct soc_bytes_ext bytes_ext;
		unsigned int flags;
		unsigned int type;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 599 */;
	struct wm_coeff_ctl_ops {
		int (*xget)(struct snd_kcontrol *kcontrol,
			    struct snd_ctl_elem_value *ucontrol);
		int (*xput)(struct snd_kcontrol *kcontrol,
			    struct snd_ctl_elem_value *ucontrol);
	} cocci_id/* sound/soc/codecs/wm_adsp.c 592 */;
	const struct {
		const char *file;
		int compr_direction;
		int num_caps;
		const struct wm_adsp_fw_caps *caps;
		bool voice_trigger;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 561 */[WM_ADSP_NUM_FW];
	const struct wm_adsp_fw_caps cocci_id/* sound/soc/codecs/wm_adsp.c 529 */[];
	struct wm_adsp_fw_caps {
		u32 id;
		struct snd_codec_desc desc;
		int num_regions;
		const struct wm_adsp_buffer_region_def *region_defs;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 522 */;
	const struct wm_adsp_buffer_region_def cocci_id/* sound/soc/codecs/wm_adsp.c 504 */[];
	struct wm_adsp_buffer_region_def {
		unsigned int mem_type;
		unsigned int base_offset;
		unsigned int size_offset;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 498 */;
	struct wm_adsp_buffer_region {
		unsigned int offset;
		unsigned int cumulative_size;
		unsigned int mem_type;
		unsigned int base_addr;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 491 */;
	int cocci_id/* sound/soc/codecs/wm_adsp.c 489 */(struct wm_adsp *dsp);
	struct wm_adsp_alg_xm_struct cocci_id/* sound/soc/codecs/wm_adsp.c 481 */;
	__be32 cocci_id/* sound/soc/codecs/wm_adsp.c 478 */;
	struct wm_adsp_buffer cocci_id/* sound/soc/codecs/wm_adsp.c 478 */;
	struct wm_halo_system_config_xm_hdr cocci_id/* sound/soc/codecs/wm_adsp.c 4535 */;
	struct wm_adsp_compr {
		struct list_head list;
		struct wm_adsp *dsp;
		struct wm_adsp_compr_buf *buf;
		struct snd_compr_stream *stream;
		struct snd_compressed_buffer size;
		u32 *raw_buf;
		unsigned int copied_total;
		unsigned int sample_rate;
		const char *name;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 452 */;
	struct wm_adsp_system_config_xm_hdr cocci_id/* sound/soc/codecs/wm_adsp.c 4475 */;
	struct reg_sequence cocci_id/* sound/soc/codecs/wm_adsp.c 4399 */[];
	unsigned int cocci_id/* sound/soc/codecs/wm_adsp.c 4398 */[6];
	struct wm_adsp_compr_buf {
		struct list_head list;
		struct wm_adsp *dsp;
		struct wm_adsp_compr *compr;
		struct wm_adsp_buffer_region *regions;
		u32 host_buf_ptr;
		u32 error;
		u32 irq_count;
		int read_index;
		int avail;
		int host_buf_mem_type;
		char *name;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 435 */;
	struct regmap *cocci_id/* sound/soc/codecs/wm_adsp.c 4332 */;
	struct wm_adsp_compr cocci_id/* sound/soc/codecs/wm_adsp.c 433 */;
	irqreturn_t cocci_id/* sound/soc/codecs/wm_adsp.c 4328 */;
	char __user *cocci_id/* sound/soc/codecs/wm_adsp.c 4296 */;
	struct wm_adsp_compr *cocci_id/* sound/soc/codecs/wm_adsp.c 4198 */;
	struct snd_compr_tstamp *cocci_id/* sound/soc/codecs/wm_adsp.c 4139 */;
	struct wm_adsp_buffer {
		__be32 buf1_base;
		__be32 buf1_size;
		__be32 buf2_base;
		__be32 buf1_buf2_size;
		__be32 buf3_base;
		__be32 buf_total_size;
		__be32 high_water_mark;
		__be32 irq_count;
		__be32 irq_ack;
		__be32 next_write_index;
		__be32 next_read_index;
		__be32 error;
		__be32 oldest_block_index;
		__be32 requested_rewind;
		__be32 reserved_space;
		__be32 min_free;
		__be32 blocks_written[2];
		__be32 words_written[2];
	} cocci_id/* sound/soc/codecs/wm_adsp.c 412 */;
	struct wm_adsp_host_buf_coeff_v1 {
		__be32 host_buf_ptr;
		__be32 versions;
		__be32 name[4];
	} cocci_id/* sound/soc/codecs/wm_adsp.c 406 */;
	struct wm_adsp_alg_xm_struct {
		__be32 magic;
		__be32 smoothing;
		__be32 threshold;
		__be32 host_buf_ptr;
		__be32 start_seq;
		__be32 high_water_mark;
		__be32 low_water_mark;
		__be64 smoothed_power;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 395 */;
	char *cocci_id/* sound/soc/codecs/wm_adsp.c 3896 */;
	u32 *cocci_id/* sound/soc/codecs/wm_adsp.c 3891 */;
	struct wm_halo_system_config_xm_hdr {
		__be32 halo_heartbeat;
		__be32 build_job_name[3];
		__be32 build_job_number;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 389 */;
	struct wm_adsp_host_buf_coeff_v1 cocci_id/* sound/soc/codecs/wm_adsp.c 3827 */;
	struct wm_adsp_system_config_xm_hdr {
		__be32 sys_enable;
		__be32 fw_id;
		__be32 fw_rev;
		__be32 boot_status;
		__be32 watchdog;
		__be32 dma_buffer_size;
		__be32 rdma[6];
		__be32 wdma[8];
		__be32 build_job_name[3];
		__be32 build_job_number;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 376 */;
	struct wm_adsp_compr_buf *cocci_id/* sound/soc/codecs/wm_adsp.c 3754 */;
	struct wm_adsp_buffer_region *cocci_id/* sound/soc/codecs/wm_adsp.c 3711 */;
	const struct wm_adsp_fw_caps *cocci_id/* sound/soc/codecs/wm_adsp.c 3710 */;
	u8 *cocci_id/* sound/soc/codecs/wm_adsp.c 3695 */;
	const char *cocci_id/* sound/soc/codecs/wm_adsp.c 362 */[WM_ADSP_NUM_FW];
	struct snd_compr_caps *cocci_id/* sound/soc/codecs/wm_adsp.c 3610 */;
	const struct snd_codec_desc *cocci_id/* sound/soc/codecs/wm_adsp.c 3533 */;
	struct snd_compr_params *cocci_id/* sound/soc/codecs/wm_adsp.c 3528 */;
	struct snd_compr_stream *cocci_id/* sound/soc/codecs/wm_adsp.c 3527 */;
	struct snd_soc_pcm_runtime *cocci_id/* sound/soc/codecs/wm_adsp.c 3459 */;
	struct wm_adsp_buf cocci_id/* sound/soc/codecs/wm_adsp.c 340 */;
	char cocci_id/* sound/soc/codecs/wm_adsp.c 3325 */[32];
	struct list_head *cocci_id/* sound/soc/codecs/wm_adsp.c 316 */;
	const void *cocci_id/* sound/soc/codecs/wm_adsp.c 315 */;
	struct wm_adsp_buf *cocci_id/* sound/soc/codecs/wm_adsp.c 315 */;
	struct snd_soc_dapm_context *cocci_id/* sound/soc/codecs/wm_adsp.c 3115 */;
	struct soc_mixer_control *cocci_id/* sound/soc/codecs/wm_adsp.c 3100 */;
	struct wm_adsp_buf {
		struct list_head list;
		void *buf;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 310 */;
	struct snd_ctl_elem_value *cocci_id/* sound/soc/codecs/wm_adsp.c 3096 */;
	struct wm_adsp_ops cocci_id/* sound/soc/codecs/wm_adsp.c 307 */[];
	struct wm_adsp_ops cocci_id/* sound/soc/codecs/wm_adsp.c 306 */;
	struct wm_adsp cocci_id/* sound/soc/codecs/wm_adsp.c 2993 */;
	struct work_struct *cocci_id/* sound/soc/codecs/wm_adsp.c 2990 */;
	unsigned int cocci_id/* sound/soc/codecs/wm_adsp.c 2786 */;
	struct wm_adsp *cocci_id/* sound/soc/codecs/wm_adsp.c 2782 */;
	struct snd_soc_component *cocci_id/* sound/soc/codecs/wm_adsp.c 2781 */;
	struct snd_kcontrol *cocci_id/* sound/soc/codecs/wm_adsp.c 2778 */;
	struct snd_soc_dapm_widget *cocci_id/* sound/soc/codecs/wm_adsp.c 2777 */;
	int cocci_id/* sound/soc/codecs/wm_adsp.c 2777 */;
	struct wmfw_coeff_item *cocci_id/* sound/soc/codecs/wm_adsp.c 2539 */;
	struct wmfw_coeff_hdr *cocci_id/* sound/soc/codecs/wm_adsp.c 2538 */;
	struct wmfw_halo_alg_hdr *cocci_id/* sound/soc/codecs/wm_adsp.c 2477 */;
	struct wmfw_halo_id_hdr cocci_id/* sound/soc/codecs/wm_adsp.c 2476 */;
	__be32 cocci_id/* sound/soc/codecs/wm_adsp.c 2469 */[];
	int cocci_id/* sound/soc/codecs/wm_adsp.c 2465 */[];
	struct wmfw_adsp2_alg_hdr *cocci_id/* sound/soc/codecs/wm_adsp.c 2336 */;
	struct wmfw_adsp2_id_hdr cocci_id/* sound/soc/codecs/wm_adsp.c 2335 */;
	u32 cocci_id/* sound/soc/codecs/wm_adsp.c 2269 */;
	size_t cocci_id/* sound/soc/codecs/wm_adsp.c 2239 */;
	const struct wm_adsp_region *cocci_id/* sound/soc/codecs/wm_adsp.c 2237 */;
	struct wm_adsp_alg_region *cocci_id/* sound/soc/codecs/wm_adsp.c 2236 */;
	struct wmfw_adsp1_alg_hdr *cocci_id/* sound/soc/codecs/wm_adsp.c 2235 */;
	struct wmfw_adsp1_id_hdr cocci_id/* sound/soc/codecs/wm_adsp.c 2234 */;
	__be32 *cocci_id/* sound/soc/codecs/wm_adsp.c 2218 */;
	int *cocci_id/* sound/soc/codecs/wm_adsp.c 2218 */;
	struct wmfw_v3_id_hdr *cocci_id/* sound/soc/codecs/wm_adsp.c 2204 */;
	struct wmfw_id_hdr *cocci_id/* sound/soc/codecs/wm_adsp.c 2192 */;
	struct wm_adsp_alg_region cocci_id/* sound/soc/codecs/wm_adsp.c 2184 */;
	const struct wmfw_region *cocci_id/* sound/soc/codecs/wm_adsp.c 1821 */;
	const struct wmfw_footer *cocci_id/* sound/soc/codecs/wm_adsp.c 1820 */;
	const struct wmfw_header *cocci_id/* sound/soc/codecs/wm_adsp.c 1818 */;
	bool cocci_id/* sound/soc/codecs/wm_adsp.c 1788 */;
	const struct wmfw_adsp2_sizes *cocci_id/* sound/soc/codecs/wm_adsp.c 1777 */;
	void *cocci_id/* sound/soc/codecs/wm_adsp.c 1763 */;
	const struct wmfw_adsp1_sizes *cocci_id/* sound/soc/codecs/wm_adsp.c 1761 */;
	const struct firmware *cocci_id/* sound/soc/codecs/wm_adsp.c 1759 */;
	const char *constcocci_id/* sound/soc/codecs/wm_adsp.c 1757 */;
	const u8 *cocci_id/* sound/soc/codecs/wm_adsp.c 1691 */;
	struct wm_coeff_parsed_coeff cocci_id/* sound/soc/codecs/wm_adsp.c 1690 */;
	struct wm_coeff_parsed_alg cocci_id/* sound/soc/codecs/wm_adsp.c 1689 */;
	const struct wm_coeff_parsed_coeff *cocci_id/* sound/soc/codecs/wm_adsp.c 1671 */;
	const struct wmfw_adsp_coeff_data *cocci_id/* sound/soc/codecs/wm_adsp.c 1627 */;
	struct wm_coeff_parsed_coeff *cocci_id/* sound/soc/codecs/wm_adsp.c 1625 */;
	u8 cocci_id/* sound/soc/codecs/wm_adsp.c 1612 */;
	const struct wmfw_adsp_alg_data *cocci_id/* sound/soc/codecs/wm_adsp.c 1597 */;
	struct wm_coeff_parsed_alg *cocci_id/* sound/soc/codecs/wm_adsp.c 1595 */;
	const u8 **cocci_id/* sound/soc/codecs/wm_adsp.c 1594 */;
	__le32 *cocci_id/* sound/soc/codecs/wm_adsp.c 1583 */;
	__le16 *cocci_id/* sound/soc/codecs/wm_adsp.c 1580 */;
	struct wm_coeff_parsed_coeff {
		int offset;
		int mem_type;
		const u8 *name;
		int name_len;
		int ctl_type;
		int flags;
		int len;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 1541 */;
	struct wm_coeff_parsed_alg {
		int id;
		const u8 *name;
		int name_len;
		int ncoeff;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 1534 */;
	char cocci_id/* sound/soc/codecs/wm_adsp.c 1417 */[SNDRV_CTL_ELEM_ID_NAME_MAXLEN];
	struct wmfw_ctl_work *cocci_id/* sound/soc/codecs/wm_adsp.c 1416 */;
	const char *cocci_id/* sound/soc/codecs/wm_adsp.c 1412 */;
	const struct wm_adsp_alg_region *cocci_id/* sound/soc/codecs/wm_adsp.c 1410 */;
	struct wmfw_ctl_work cocci_id/* sound/soc/codecs/wm_adsp.c 1394 */;
	unsigned long cocci_id/* sound/soc/codecs/wm_adsp.c 1293 */;
	struct snd_kcontrol_new *cocci_id/* sound/soc/codecs/wm_adsp.c 1279 */;
	struct wmfw_ctl_work {
		struct wm_adsp *dsp;
		struct wm_coeff_ctl *ctl;
		struct work_struct work;
	} cocci_id/* sound/soc/codecs/wm_adsp.c 1240 */;
	unsigned int __user *cocci_id/* sound/soc/codecs/wm_adsp.c 1198 */;
	const unsigned int __user *cocci_id/* sound/soc/codecs/wm_adsp.c 1090 */;
}
