cocci_test_suite() {
	const struct snd_soc_dai_ops cocci_id/* sound/soc/codecs/rt286.c 994 */;
	bool cocci_id/* sound/soc/codecs/rt286.c 915 */;
	irqreturn_t cocci_id/* sound/soc/codecs/rt286.c 912 */;
	void *cocci_id/* sound/soc/codecs/rt286.c 912 */;
	enum snd_soc_bias_level cocci_id/* sound/soc/codecs/rt286.c 881 */;
	unsigned int cocci_id/* sound/soc/codecs/rt286.c 677 */;
	struct snd_soc_dai *cocci_id/* sound/soc/codecs/rt286.c 673 */;
	struct snd_pcm_hw_params *cocci_id/* sound/soc/codecs/rt286.c 672 */;
	struct snd_pcm_substream *cocci_id/* sound/soc/codecs/rt286.c 671 */;
	const struct snd_soc_dapm_route cocci_id/* sound/soc/codecs/rt286.c 603 */[];
	const struct snd_soc_dapm_widget cocci_id/* sound/soc/codecs/rt286.c 517 */[];
	const struct reg_default cocci_id/* sound/soc/codecs/rt286.c 49 */[];
	struct snd_kcontrol *cocci_id/* sound/soc/codecs/rt286.c 474 */;
	const int cocci_id/* sound/soc/codecs/rt286.c 397 */[];
	const char *const cocci_id/* sound/soc/codecs/rt286.c 393 */[];
	const struct snd_kcontrol_new cocci_id/* sound/soc/codecs/rt286.c 384 */;
	const struct snd_kcontrol_new cocci_id/* sound/soc/codecs/rt286.c 361 */[];
	struct rt286_priv {
		struct reg_default *index_cache;
		int index_cache_size;
		struct regmap *regmap;
		struct snd_soc_component *component;
		struct rt286_platform_data pdata;
		struct i2c_client *i2c;
		struct snd_soc_jack *jack;
		struct delayed_work jack_detect_work;
		int sys_clk;
		int clk_id;
	} cocci_id/* sound/soc/codecs/rt286.c 36 */;
	struct rt286_priv *cocci_id/* sound/soc/codecs/rt286.c 336 */;
	struct snd_soc_component *cocci_id/* sound/soc/codecs/rt286.c 335 */;
	struct snd_soc_dapm_widget *cocci_id/* sound/soc/codecs/rt286.c 332 */;
	int cocci_id/* sound/soc/codecs/rt286.c 332 */;
	struct snd_soc_jack *cocci_id/* sound/soc/codecs/rt286.c 306 */;
	struct rt286_priv cocci_id/* sound/soc/codecs/rt286.c 289 */;
	struct work_struct *cocci_id/* sound/soc/codecs/rt286.c 286 */;
	struct snd_soc_dapm_context *cocci_id/* sound/soc/codecs/rt286.c 214 */;
	bool *cocci_id/* sound/soc/codecs/rt286.c 212 */;
	int cocci_id/* sound/soc/codecs/rt286.c 199 */[];
	void cocci_id/* sound/soc/codecs/rt286.c 187 */;
	struct device *cocci_id/* sound/soc/codecs/rt286.c 131 */;
	struct i2c_driver cocci_id/* sound/soc/codecs/rt286.c 1260 */;
	struct rt286_platform_data *cocci_id/* sound/soc/codecs/rt286.c 1132 */;
	const struct i2c_device_id *cocci_id/* sound/soc/codecs/rt286.c 1130 */;
	struct i2c_client *cocci_id/* sound/soc/codecs/rt286.c 1129 */;
	const struct dmi_system_id cocci_id/* sound/soc/codecs/rt286.c 1118 */[];
	const struct acpi_device_id cocci_id/* sound/soc/codecs/rt286.c 1082 */[];
	const struct i2c_device_id cocci_id/* sound/soc/codecs/rt286.c 1075 */[];
	const struct regmap_config cocci_id/* sound/soc/codecs/rt286.c 1062 */;
	const struct snd_soc_component_driver cocci_id/* sound/soc/codecs/rt286.c 1045 */;
	struct snd_soc_dai_driver cocci_id/* sound/soc/codecs/rt286.c 1001 */[];
}
