cocci_test_suite() {
	struct tls12_crypto_info_aes_gcm_128 *cocci_id/* net/tls/tls_device.c 951 */;
	__be64 cocci_id/* net/tls/tls_device.c 921 */;
	struct tls_crypto_info *cocci_id/* net/tls/tls_device.c 917 */;
	u16 cocci_id/* net/tls/tls_device.c 912 */;
	struct tls_context *cocci_id/* net/tls/tls_device.c 894 */;
	char *cocci_id/* net/tls/tls_device.c 778 */;
	struct scatterlist cocci_id/* net/tls/tls_device.c 777 */[1];
	u8 cocci_id/* net/tls/tls_device.c 762 */[TLS_MAX_REC_SEQ_SIZE];
	struct tls_prot_info *cocci_id/* net/tls/tls_device.c 761 */;
	struct strp_msg *cocci_id/* net/tls/tls_device.c 729 */;
	struct sk_buff *cocci_id/* net/tls/tls_device.c 727 */;
	struct tls_offload_context_rx *cocci_id/* net/tls/tls_device.c 726 */;
	struct work_struct *cocci_id/* net/tls/tls_device.c 69 */;
	s64 cocci_id/* net/tls/tls_device.c 681 */;
	u32 cocci_id/* net/tls/tls_device.c 657 */;
	u8 *cocci_id/* net/tls/tls_device.c 657 */;
	gfp_t cocci_id/* net/tls/tls_device.c 644 */;
	struct iov_iter cocci_id/* net/tls/tls_device.c 635 */;
	struct tls_record_info cocci_id/* net/tls/tls_device.c 604 */;
	u64 cocci_id/* net/tls/tls_device.c 594 */;
	u64 *cocci_id/* net/tls/tls_device.c 592 */;
	struct kvec cocci_id/* net/tls/tls_device.c 564 */;
	struct page *cocci_id/* net/tls/tls_device.c 558 */;
	struct msghdr *cocci_id/* net/tls/tls_device.c 534 */;
	void cocci_id/* net/tls/tls_device.c 48 */(struct work_struct *work);
	long cocci_id/* net/tls/tls_device.c 428 */;
	bool cocci_id/* net/tls/tls_device.c 427 */;
	struct iov_iter *cocci_id/* net/tls/tls_device.c 387 */;
	size_t cocci_id/* net/tls/tls_device.c 335 */;
	unsigned char cocci_id/* net/tls/tls_device.c 305 */;
	struct tcp_sock *cocci_id/* net/tls/tls_device.c 274 */;
	skb_frag_t *cocci_id/* net/tls/tls_device.c 248 */;
	struct page_frag *cocci_id/* net/tls/tls_device.c 245 */;
	struct tls_record_info *cocci_id/* net/tls/tls_device.c 136 */;
	struct tls_offload_context_tx *cocci_id/* net/tls/tls_device.c 134 */;
	void cocci_id/* net/tls/tls_device.c 134 */;
	int cocci_id/* net/tls/tls_device.c 127 */;
	void __exit cocci_id/* net/tls/tls_device.c 1263 */;
	void __init cocci_id/* net/tls/tls_device.c 1258 */;
	struct notifier_block cocci_id/* net/tls/tls_device.c 1254 */;
	void *cocci_id/* net/tls/tls_device.c 1227 */;
	struct notifier_block *cocci_id/* net/tls/tls_device.c 1226 */;
	unsigned long cocci_id/* net/tls/tls_device.c 1226 */;
	struct dst_entry *cocci_id/* net/tls/tls_device.c 112 */;
	struct sock *cocci_id/* net/tls/tls_device.c 110 */;
	struct net_device *cocci_id/* net/tls/tls_device.c 110 */;
}
