cocci_test_suite() {
	struct dsa_mall_mirror_tc_entry *cocci_id/* net/dsa/slave.c 903 */;
	struct flow_action_entry *cocci_id/* net/dsa/slave.c 890 */;
	__be16 cocci_id/* net/dsa/slave.c 888 */;
	struct dsa_mall_tc_entry *cocci_id/* net/dsa/slave.c 887 */;
	struct tc_cls_matchall_offload *cocci_id/* net/dsa/slave.c 882 */;
	unsigned long cocci_id/* net/dsa/slave.c 869 */;
	char *cocci_id/* net/dsa/slave.c 851 */;
	size_t cocci_id/* net/dsa/slave.c 851 */;
	struct netpoll *cocci_id/* net/dsa/slave.c 835 */;
	struct netpoll_info *cocci_id/* net/dsa/slave.c 810 */;
	struct ethtool_pauseparam *cocci_id/* net/dsa/slave.c 793 */;
	const struct ethtool_link_ksettings *cocci_id/* net/dsa/slave.c 785 */;
	struct ethtool_link_ksettings *cocci_id/* net/dsa/slave.c 777 */;
	struct ethtool_eee *cocci_id/* net/dsa/slave.c 756 */;
	struct ethtool_wolinfo *cocci_id/* net/dsa/slave.c 711 */;
	u64 cocci_id/* net/dsa/slave.c 674 */;
	struct pcpu_sw_netstats *cocci_id/* net/dsa/slave.c 669 */;
	uint64_t *cocci_id/* net/dsa/slave.c 664 */;
	struct ethtool_stats *cocci_id/* net/dsa/slave.c 663 */;
	uint32_t cocci_id/* net/dsa/slave.c 644 */;
	uint8_t *cocci_id/* net/dsa/slave.c 644 */;
	u8 *cocci_id/* net/dsa/slave.c 620 */;
	struct ethtool_eeprom *cocci_id/* net/dsa/slave.c 620 */;
	struct ethtool_regs *cocci_id/* net/dsa/slave.c 589 */;
	struct ethtool_drvinfo *cocci_id/* net/dsa/slave.c 570 */;
	struct dsa_port cocci_id/* net/dsa/slave.c 556 */;
	struct work_struct *cocci_id/* net/dsa/slave.c 554 */;
	struct dsa_port *cocci_id/* net/dsa/slave.c 544 */;
	struct sk_buff *cocci_id/* net/dsa/slave.c 542 */;
	struct net_device *cocci_id/* net/dsa/slave.c 542 */;
	void *cocci_id/* net/dsa/slave.c 542 */;
	netdev_tx_t cocci_id/* net/dsa/slave.c 491 */;
	unsigned int cocci_id/* net/dsa/slave.c 470 */;
	struct dsa_slave_priv *cocci_id/* net/dsa/slave.c 465 */;
	struct dsa_switch_tree *cocci_id/* net/dsa/slave.c 436 */;
	struct netdev_phys_item_id *cocci_id/* net/dsa/slave.c 432 */;
	const struct switchdev_obj *cocci_id/* net/dsa/slave.c 349 */;
	struct switchdev_obj_port_vlan cocci_id/* net/dsa/slave.c 320 */;
	struct switchdev_trans *cocci_id/* net/dsa/slave.c 281 */;
	const struct switchdev_attr *cocci_id/* net/dsa/slave.c 280 */;
	struct mii_bus *cocci_id/* net/dsa/slave.c 28 */;
	struct ifreq *cocci_id/* net/dsa/slave.c 258 */;
	bool cocci_id/* net/dsa/slave.c 25 */(const struct net_device *dev);
	struct dsa_slave_dump_ctx cocci_id/* net/dsa/slave.c 244 */;
	int *cocci_id/* net/dsa/slave.c 241 */;
	struct netlink_callback *cocci_id/* net/dsa/slave.c 239 */;
	struct nlmsghdr *cocci_id/* net/dsa/slave.c 201 */;
	struct dsa_slave_dump_ctx *cocci_id/* net/dsa/slave.c 198 */;
	struct dsa_slave_dump_ctx {
		struct net_device *dev;
		struct sk_buff *skb;
		struct netlink_callback *cb;
		int idx;
	} cocci_id/* net/dsa/slave.c 187 */;
	struct notifier_block cocci_id/* net/dsa/slave.c 1724 */;
	struct dsa_switchdev_event_work *cocci_id/* net/dsa/slave.c 1655 */;
	const struct switchdev_notifier_fdb_info *cocci_id/* net/dsa/slave.c 1637 */;
	struct sockaddr *cocci_id/* net/dsa/slave.c 163 */;
	struct switchdev_notifier_fdb_info *cocci_id/* net/dsa/slave.c 1594 */;
	struct dsa_switchdev_event_work cocci_id/* net/dsa/slave.c 1592 */;
	struct dsa_switchdev_event_work {
		struct work_struct work;
		struct switchdev_notifier_fdb_info fdb_info;
		struct net_device *dev;
		unsigned long event;
	} cocci_id/* net/dsa/slave.c 1582 */;
	struct notifier_block *cocci_id/* net/dsa/slave.c 1567 */;
	struct netdev_notifier_changeupper_info *cocci_id/* net/dsa/slave.c 1517 */;
	const struct net_device *cocci_id/* net/dsa/slave.c 1511 */;
	struct pcpu_sw_netstats cocci_id/* net/dsa/slave.c 1451 */;
	struct dsa_slave_priv cocci_id/* net/dsa/slave.c 1425 */;
	const char *cocci_id/* net/dsa/slave.c 1417 */;
	struct dsa_notifier_register_info cocci_id/* net/dsa/slave.c 1402 */;
	u32 cocci_id/* net/dsa/slave.c 1317 */;
	phy_interface_t cocci_id/* net/dsa/slave.c 1316 */;
	struct device_node *cocci_id/* net/dsa/slave.c 1314 */;
	struct phylink_link_state *cocci_id/* net/dsa/slave.c 1285 */;
	const struct dsa_port *cocci_id/* net/dsa/slave.c 1278 */;
	bool cocci_id/* net/dsa/slave.c 1276 */;
	struct dsa_switch *cocci_id/* net/dsa/slave.c 1276 */;
	void cocci_id/* net/dsa/slave.c 1276 */;
	struct device_type cocci_id/* net/dsa/slave.c 1272 */;
	const struct net_device_ops cocci_id/* net/dsa/slave.c 1246 */;
	struct devlink_port *cocci_id/* net/dsa/slave.c 1239 */;
	struct netlink_ext_ack *cocci_id/* net/dsa/slave.c 1223 */;
	u16 cocci_id/* net/dsa/slave.c 1221 */;
	const unsigned char *cocci_id/* net/dsa/slave.c 1221 */;
	struct nlattr *cocci_id/* net/dsa/slave.c 1219 */[];
	struct ndmsg *cocci_id/* net/dsa/slave.c 1219 */;
	int cocci_id/* net/dsa/slave.c 1219 */;
	const struct ethtool_ops cocci_id/* net/dsa/slave.c 1193 */;
	struct bridge_vlan_info cocci_id/* net/dsa/slave.c 1134 */;
	struct ethtool_ts_info *cocci_id/* net/dsa/slave.c 1119 */;
	u32 *cocci_id/* net/dsa/slave.c 1095 */;
	struct ethtool_rxnfc *cocci_id/* net/dsa/slave.c 1095 */;
	struct rtnl_link_stats64 *cocci_id/* net/dsa/slave.c 1067 */;
	enum tc_setup_type cocci_id/* net/dsa/slave.c 1051 */;
	flow_setup_cb_t *cocci_id/* net/dsa/slave.c 1015 */;
	struct flow_block_cb *cocci_id/* net/dsa/slave.c 1014 */;
	struct flow_block_offload *cocci_id/* net/dsa/slave.c 1012 */;
}
