cocci_test_suite() {
	void __exit cocci_id/* net/sched/sch_gred.c 931 */;
	int __init cocci_id/* net/sched/sch_gred.c 926 */;
	struct gred_sched cocci_id/* net/sched/sch_gred.c 914 */;
	struct Qdisc_ops cocci_id/* net/sched/sch_gred.c 912 */;
	void cocci_id/* net/sched/sch_gred.c 900 */;
	unsigned long cocci_id/* net/sched/sch_gred.c 798 */;
	struct tc_gred_qopt cocci_id/* net/sched/sch_gred.c 797 */;
	struct tc_gred_sopt cocci_id/* net/sched/sch_gred.c 763 */;
	u32 cocci_id/* net/sched/sch_gred.c 762 */[MAX_DPs];
	u32 cocci_id/* net/sched/sch_gred.c 643 */;
	u8 *cocci_id/* net/sched/sch_gred.c 642 */;
	struct nlattr *cocci_id/* net/sched/sch_gred.c 640 */[TCA_GRED_MAX + 1];
	struct tc_gred_qopt *cocci_id/* net/sched/sch_gred.c 639 */;
	struct netlink_ext_ack *cocci_id/* net/sched/sch_gred.c 636 */;
	struct nlattr *cocci_id/* net/sched/sch_gred.c 635 */;
	int cocci_id/* net/sched/sch_gred.c 635 */;
	struct nlattr *cocci_id/* net/sched/sch_gred.c 533 */[TCA_GRED_VQ_MAX + 1];
	const struct nlattr *cocci_id/* net/sched/sch_gred.c 531 */;
	const struct nla_policy cocci_id/* net/sched/sch_gred.c 522 */[TCA_GRED_MAX + 1];
	struct gred_sched {
		struct gred_sched_data *tab[MAX_DPs];
		unsigned long flags;
		u32 red_flags;
		u32 DPs;
		u32 def;
		struct red_vars wred_set;
	} cocci_id/* net/sched/sch_gred.c 52 */;
	const struct nla_policy cocci_id/* net/sched/sch_gred.c 518 */[TCA_GRED_VQ_ENTRY_MAX + 1];
	const struct nla_policy cocci_id/* net/sched/sch_gred.c 513 */[TCA_GRED_VQ_MAX + 1];
	struct gred_sched_data **cocci_id/* net/sched/sch_gred.c 477 */;
	enum{GRED_WRED_MODE=1, GRED_RIO_MODE,} cocci_id/* net/sched/sch_gred.c 47 */;
	bool cocci_id/* net/sched/sch_gred.c 406 */;
	struct tc_gred_sopt *cocci_id/* net/sched/sch_gred.c 405 */;
	struct tc_gred_qopt_offload *cocci_id/* net/sched/sch_gred.c 355 */;
	struct gred_sched_data {
		u32 limit;
		u32 DP;
		u32 red_flags;
		u64 bytesin;
		u32 packetsin;
		u32 backlog;
		u8 prio;
		struct red_parms parms;
		struct red_vars vars;
		struct red_stats stats;
	} cocci_id/* net/sched/sch_gred.c 33 */;
	struct tc_gred_qopt_offload cocci_id/* net/sched/sch_gred.c 314 */;
	struct net_device *cocci_id/* net/sched/sch_gred.c 313 */;
	enum tc_gred_command cocci_id/* net/sched/sch_gred.c 310 */;
	struct gred_sched_data cocci_id/* net/sched/sch_gred.c 30 */;
	u16 cocci_id/* net/sched/sch_gred.c 269 */;
	struct sk_buff *cocci_id/* net/sched/sch_gred.c 260 */;
	struct sk_buff **cocci_id/* net/sched/sch_gred.c 165 */;
	const struct gred_sched *cocci_id/* net/sched/sch_gred.c 127 */;
	struct Qdisc *cocci_id/* net/sched/sch_gred.c 114 */;
	struct gred_sched_data *cocci_id/* net/sched/sch_gred.c 113 */;
	struct gred_sched *cocci_id/* net/sched/sch_gred.c 112 */;
	unsigned int cocci_id/* net/sched/sch_gred.c 112 */;
}
