cocci_test_suite() {
	u16 cocci_id/* net/sched/act_skbmod.c 95 */;
	struct tc_skbmod *cocci_id/* net/sched/act_skbmod.c 89 */;
	struct tcf_chain *cocci_id/* net/sched/act_skbmod.c 88 */;
	struct nlattr *cocci_id/* net/sched/act_skbmod.c 86 */[TCA_SKBMOD_MAX + 1];
	struct netlink_ext_ack *cocci_id/* net/sched/act_skbmod.c 83 */;
	u32 cocci_id/* net/sched/act_skbmod.c 82 */;
	struct tcf_proto *cocci_id/* net/sched/act_skbmod.c 82 */;
	bool cocci_id/* net/sched/act_skbmod.c 81 */;
	struct tc_action **cocci_id/* net/sched/act_skbmod.c 80 */;
	struct nlattr *cocci_id/* net/sched/act_skbmod.c 79 */;
	struct tc_skbmod cocci_id/* net/sched/act_skbmod.c 73 */;
	const struct nla_policy cocci_id/* net/sched/act_skbmod.c 72 */[TCA_SKBMOD_MAX + 1];
	u8 *cocci_id/* net/sched/act_skbmod.c 60 */;
	u16 cocci_id/* net/sched/act_skbmod.c 58 */[ETH_ALEN / 2];
	void __exit cocci_id/* net/sched/act_skbmod.c 314 */;
	void cocci_id/* net/sched/act_skbmod.c 314 */;
	int __init cocci_id/* net/sched/act_skbmod.c 309 */;
	struct tc_action_net cocci_id/* net/sched/act_skbmod.c 302 */;
	u64 cocci_id/* net/sched/act_skbmod.c 30 */;
	struct pernet_operations cocci_id/* net/sched/act_skbmod.c 298 */;
	struct list_head *cocci_id/* net/sched/act_skbmod.c 293 */;
	void __net_exit cocci_id/* net/sched/act_skbmod.c 293 */;
	struct tcf_skbmod_params *cocci_id/* net/sched/act_skbmod.c 29 */;
	struct tc_action_net *cocci_id/* net/sched/act_skbmod.c 288 */;
	struct net *cocci_id/* net/sched/act_skbmod.c 286 */;
	int cocci_id/* net/sched/act_skbmod.c 286 */;
	struct tcf_skbmod cocci_id/* net/sched/act_skbmod.c 283 */;
	struct tcf_skbmod *cocci_id/* net/sched/act_skbmod.c 27 */;
	const struct tc_action_ops *cocci_id/* net/sched/act_skbmod.c 258 */;
	struct netlink_callback *cocci_id/* net/sched/act_skbmod.c 257 */;
	struct tcf_result *cocci_id/* net/sched/act_skbmod.c 25 */;
	const struct tc_action *cocci_id/* net/sched/act_skbmod.c 24 */;
	struct sk_buff *cocci_id/* net/sched/act_skbmod.c 24 */;
	struct tcf_t cocci_id/* net/sched/act_skbmod.c 225 */;
	unsigned char *cocci_id/* net/sched/act_skbmod.c 218 */;
	struct tc_action_ops cocci_id/* net/sched/act_skbmod.c 21 */;
	struct tc_action *cocci_id/* net/sched/act_skbmod.c 204 */;
	unsigned int cocci_id/* net/sched/act_skbmod.c 20 */;
	struct tcf_skbmod_params cocci_id/* net/sched/act_skbmod.c 163 */;
}
