cocci_test_suite() {
	struct fib6_nh cocci_id/* net/ipv4/fib_semantics.c 995 */;
	struct fib6_config cocci_id/* net/ipv4/fib_semantics.c 989 */;
	char cocci_id/* net/ipv4/fib_semantics.c 964 */[TCP_CA_NAME_MAX];
	const struct fib_prop cocci_id/* net/ipv4/fib_semantics.c 95 */[RTN_MAX + 1];
	struct lwtunnel_state *cocci_id/* net/ipv4/fib_semantics.c 816 */;
	const struct fib_config *cocci_id/* net/ipv4/fib_semantics.c 813 */;
	const struct fib_nh *cocci_id/* net/ipv4/fib_semantics.c 812 */;
	u16 cocci_id/* net/ipv4/fib_semantics.c 810 */;
	u64 cocci_id/* net/ipv4/fib_semantics.c 788 */;
	struct fib_config cocci_id/* net/ipv4/fib_semantics.c 663 */;
	struct hlist_head cocci_id/* net/ipv4/fib_semantics.c 58 */[DEVINDEX_HASHSIZE];
	struct rtable __rcu *cocci_id/* net/ipv4/fib_semantics.c 572 */;
	gfp_t cocci_id/* net/ipv4/fib_semantics.c 567 */;
	struct neighbour *cocci_id/* net/ipv4/fib_semantics.c 537 */;
	struct fib_info **cocci_id/* net/ipv4/fib_semantics.c 533 */;
	int *cocci_id/* net/ipv4/fib_semantics.c 533 */;
	const struct nl_info *cocci_id/* net/ipv4/fib_semantics.c 504 */;
	struct rtnexthop cocci_id/* net/ipv4/fib_semantics.c 476 */;
	struct rtmsg cocci_id/* net/ipv4/fib_semantics.c 457 */;
	size_t cocci_id/* net/ipv4/fib_semantics.c 455 */;
	struct fib_info cocci_id/* net/ipv4/fib_semantics.c 233 */;
	struct rcu_head *cocci_id/* net/ipv4/fib_semantics.c 231 */;
	const struct sk_buff *cocci_id/* net/ipv4/fib_semantics.c 2191 */;
	struct flowi4 *cocci_id/* net/ipv4/fib_semantics.c 2191 */;
	struct fib_alias *cocci_id/* net/ipv4/fib_semantics.c 1996 */;
	const struct flowi4 *cocci_id/* net/ipv4/fib_semantics.c 1989 */;
	struct rtable __rcu *__percpu*cocci_id/* net/ipv4/fib_semantics.c 190 */;
	struct fib_nh_exception *cocci_id/* net/ipv4/fib_semantics.c 1884 */;
	struct fnhe_hash_bucket *cocci_id/* net/ipv4/fib_semantics.c 1876 */;
	struct fib_nh_notifier_info cocci_id/* net/ipv4/fib_semantics.c 1840 */;
	bool cocci_id/* net/ipv4/fib_semantics.c 1839 */;
	enum fib_event_type cocci_id/* net/ipv4/fib_semantics.c 1837 */;
	struct fib_nh *cocci_id/* net/ipv4/fib_semantics.c 1836 */;
	int cocci_id/* net/ipv4/fib_semantics.c 1836 */;
	struct fib_nh cocci_id/* net/ipv4/fib_semantics.c 1787 */;
	struct rtmsg *cocci_id/* net/ipv4/fib_semantics.c 1733 */;
	struct nlmsghdr *cocci_id/* net/ipv4/fib_semantics.c 1732 */;
	__be32 cocci_id/* net/ipv4/fib_semantics.c 1728 */;
	struct nlattr *cocci_id/* net/ipv4/fib_semantics.c 1689 */;
	struct sk_buff *cocci_id/* net/ipv4/fib_semantics.c 1687 */;
	struct fib_info *cocci_id/* net/ipv4/fib_semantics.c 1687 */;
	void *cocci_id/* net/ipv4/fib_semantics.c 1676 */;
	unsigned char cocci_id/* net/ipv4/fib_semantics.c 1661 */;
	struct rtnexthop *cocci_id/* net/ipv4/fib_semantics.c 1660 */;
	const struct net_device *cocci_id/* net/ipv4/fib_semantics.c 1659 */;
	u8 cocci_id/* net/ipv4/fib_semantics.c 1657 */;
	const struct fib_nh_common *cocci_id/* net/ipv4/fib_semantics.c 1656 */;
	struct rtvia *cocci_id/* net/ipv4/fib_semantics.c 1619 */;
	struct in6_addr cocci_id/* net/ipv4/fib_semantics.c 1617 */;
	unsigned char *cocci_id/* net/ipv4/fib_semantics.c 1585 */;
	struct rtable *cocci_id/* net/ipv4/fib_semantics.c 148 */;
	struct rtable __rcu **cocci_id/* net/ipv4/fib_semantics.c 146 */;
	struct hlist_head *cocci_id/* net/ipv4/fib_semantics.c 1390 */;
	struct nexthop *cocci_id/* net/ipv4/fib_semantics.c 1342 */;
	struct fib_config *cocci_id/* net/ipv4/fib_semantics.c 1337 */;
	struct fib_result *cocci_id/* net/ipv4/fib_semantics.c 1295 */;
	struct fib_nh_common *cocci_id/* net/ipv4/fib_semantics.c 1280 */;
	struct hlist_node *cocci_id/* net/ipv4/fib_semantics.c 1243 */;
	unsigned long cocci_id/* net/ipv4/fib_semantics.c 1225 */;
	void cocci_id/* net/ipv4/fib_semantics.c 1217 */;
	struct netlink_ext_ack *cocci_id/* net/ipv4/fib_semantics.c 1184 */;
	u32 cocci_id/* net/ipv4/fib_semantics.c 1183 */;
	struct net *cocci_id/* net/ipv4/fib_semantics.c 1183 */;
	struct in_device *cocci_id/* net/ipv4/fib_semantics.c 1151 */;
	struct flowi4 cocci_id/* net/ipv4/fib_semantics.c 1092 */;
	struct fib_table *cocci_id/* net/ipv4/fib_semantics.c 1091 */;
	unsigned int cocci_id/* net/ipv4/fib_semantics.c 1062 */;
	struct fib_result cocci_id/* net/ipv4/fib_semantics.c 1058 */;
	struct net_device *cocci_id/* net/ipv4/fib_semantics.c 1057 */;
	struct dn_fib_nh *cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 722 */;
	const struct dn_fib_nh *cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 719 */;
}
