cocci_test_suite() {
	bool cocci_id/* net/ipv4/ip_tunnel_core.c 92 */;
	__be16 cocci_id/* net/ipv4/ip_tunnel_core.c 92 */;
	struct sk_buff *cocci_id/* net/ipv4/ip_tunnel_core.c 91 */;
	int cocci_id/* net/ipv4/ip_tunnel_core.c 91 */;
	void __init cocci_id/* net/ipv4/ip_tunnel_core.c 821 */;
	const struct lwtunnel_encap_ops cocci_id/* net/ipv4/ip_tunnel_core.c 813 */;
	struct ip_tunnel_info *cocci_id/* net/ipv4/ip_tunnel_core.c 729 */;
	struct lwtunnel_state *cocci_id/* net/ipv4/ip_tunnel_core.c 728 */;
	struct nlattr *cocci_id/* net/ipv4/ip_tunnel_core.c 727 */[LWTUNNEL_IP6_MAX + 1];
	struct netlink_ext_ack *cocci_id/* net/ipv4/ip_tunnel_core.c 725 */;
	struct lwtunnel_state **cocci_id/* net/ipv4/ip_tunnel_core.c 724 */;
	const void *cocci_id/* net/ipv4/ip_tunnel_core.c 723 */;
	unsigned int cocci_id/* net/ipv4/ip_tunnel_core.c 723 */;
	struct nlattr *cocci_id/* net/ipv4/ip_tunnel_core.c 722 */;
	struct in6_addr cocci_id/* net/ipv4/ip_tunnel_core.c 714 */;
	const struct nla_policy cocci_id/* net/ipv4/ip_tunnel_core.c 711 */[LWTUNNEL_IP6_MAX + 1];
	struct iphdr cocci_id/* net/ipv4/ip_tunnel_core.c 66 */;
	struct erspan_metadata *cocci_id/* net/ipv4/ip_tunnel_core.c 564 */;
	struct iphdr *cocci_id/* net/ipv4/ip_tunnel_core.c 56 */;
	struct vxlan_metadata *cocci_id/* net/ipv4/ip_tunnel_core.c 544 */;
	struct net *cocci_id/* net/ipv4/ip_tunnel_core.c 54 */;
	struct geneve_opt *cocci_id/* net/ipv4/ip_tunnel_core.c 516 */;
	void cocci_id/* net/ipv4/ip_tunnel_core.c 504 */;
	__u8 cocci_id/* net/ipv4/ip_tunnel_core.c 50 */;
	__be32 cocci_id/* net/ipv4/ip_tunnel_core.c 50 */;
	struct sock *cocci_id/* net/ipv4/ip_tunnel_core.c 49 */;
	struct rtable *cocci_id/* net/ipv4/ip_tunnel_core.c 49 */;
	const struct ip6_tnl_encap_ops __rcu *cocci_id/* net/ipv4/ip_tunnel_core.c 45 */[MAX_IPTUN_ENCAP_OPS]__read_mostly;
	struct nlattr *cocci_id/* net/ipv4/ip_tunnel_core.c 440 */[LWTUNNEL_IP_MAX + 1];
	const struct ip_tunnel_encap_ops __rcu *cocci_id/* net/ipv4/ip_tunnel_core.c 41 */[MAX_IPTUN_ENCAP_OPS]__read_mostly;
	struct erspan_metadata cocci_id/* net/ipv4/ip_tunnel_core.c 364 */;
	u8 cocci_id/* net/ipv4/ip_tunnel_core.c 324 */;
	struct nlattr *cocci_id/* net/ipv4/ip_tunnel_core.c 322 */[LWTUNNEL_IP_OPT_ERSPAN_MAX + 1];
	struct vxlan_metadata cocci_id/* net/ipv4/ip_tunnel_core.c 315 */;
	struct nlattr *cocci_id/* net/ipv4/ip_tunnel_core.c 295 */[LWTUNNEL_IP_OPT_VXLAN_MAX + 1];
	struct geneve_opt cocci_id/* net/ipv4/ip_tunnel_core.c 288 */;
	struct nlattr *cocci_id/* net/ipv4/ip_tunnel_core.c 258 */[LWTUNNEL_IP_OPT_GENEVE_MAX + 1];
	const struct nla_policy cocci_id/* net/ipv4/ip_tunnel_core.c 246 */[LWTUNNEL_IP_OPT_ERSPAN_MAX + 1];
	const struct nla_policy cocci_id/* net/ipv4/ip_tunnel_core.c 241 */[LWTUNNEL_IP_OPT_VXLAN_MAX + 1];
	const struct nla_policy cocci_id/* net/ipv4/ip_tunnel_core.c 234 */[LWTUNNEL_IP_OPT_GENEVE_MAX + 1];
	const struct nla_policy cocci_id/* net/ipv4/ip_tunnel_core.c 228 */[LWTUNNEL_IP_OPTS_MAX + 1];
	const struct nla_policy cocci_id/* net/ipv4/ip_tunnel_core.c 217 */[LWTUNNEL_IP_MAX + 1];
	u64 cocci_id/* net/ipv4/ip_tunnel_core.c 198 */;
	const struct pcpu_sw_netstats *cocci_id/* net/ipv4/ip_tunnel_core.c 196 */;
	struct rtnl_link_stats64 *cocci_id/* net/ipv4/ip_tunnel_core.c 189 */;
	struct net_device *cocci_id/* net/ipv4/ip_tunnel_core.c 188 */;
	gfp_t cocci_id/* net/ipv4/ip_tunnel_core.c 125 */;
	struct metadata_dst *cocci_id/* net/ipv4/ip_tunnel_core.c 124 */;
	struct ethhdr *cocci_id/* net/ipv4/ip_tunnel_core.c 100 */;
}
