cocci_test_suite() {
	struct edmacc_param *cocci_id/* drivers/dma/ti/edma.c 960 */;
	enum dma_transfer_direction cocci_id/* drivers/dma/ti/edma.c 956 */;
	dma_addr_t cocci_id/* drivers/dma/ti/edma.c 954 */;
	struct edma_pset *cocci_id/* drivers/dma/ti/edma.c 953 */;
	struct dma_slave_config *cocci_id/* drivers/dma/ti/edma.c 906 */;
	struct edma_desc cocci_id/* drivers/dma/ti/edma.c 771 */;
	struct virt_dma_desc *cocci_id/* drivers/dma/ti/edma.c 769 */;
	struct edma_chan cocci_id/* drivers/dma/ti/edma.c 761 */;
	const struct edmacc_param *cocci_id/* drivers/dma/ti/edma.c 472 */;
	unsigned cocci_id/* drivers/dma/ti/edma.c 329 */;
	void cocci_id/* drivers/dma/ti/edma.c 329 */;
	const struct of_device_id cocci_id/* drivers/dma/ti/edma.c 290 */[];
	const u32 cocci_id/* drivers/dma/ti/edma.c 285 */[];
	const struct edmacc_param cocci_id/* drivers/dma/ti/edma.c 278 */;
	void __exit cocci_id/* drivers/dma/ti/edma.c 2655 */;
	unsigned *cocci_id/* drivers/dma/ti/edma.c 2633 */;
	struct platform_driver cocci_id/* drivers/dma/ti/edma.c 2603 */;
	const struct dev_pm_ops cocci_id/* drivers/dma/ti/edma.c 2599 */;
	struct dma_device *cocci_id/* drivers/dma/ti/edma.c 2518 */;
	struct of_phandle_args cocci_id/* drivers/dma/ti/edma.c 2423 */;
	struct edma_cc {
		struct device *dev;
		struct edma_soc_info *info;
		void __iomem *base;
		int id;
		bool legacy_mode;
		unsigned num_channels;
		unsigned num_qchannels;
		unsigned num_region;
		unsigned num_slots;
		unsigned num_tc;
		bool chmap_exist;
		enum dma_event_q default_queue;
		unsigned int ccint;
		unsigned int ccerrint;
		unsigned long *slot_inuse;
		unsigned long *channels_mask;
		struct dma_device dma_slave;
		struct dma_device *dma_memcpy;
		struct edma_chan *slave_chans;
		struct edma_tc *tc_list;
		int dummy_slot;
	} cocci_id/* drivers/dma/ti/edma.c 238 */;
	u32 *cocci_id/* drivers/dma/ti/edma.c 2279 */;
	const struct of_device_id *cocci_id/* drivers/dma/ti/edma.c 2276 */;
	struct device_node *cocci_id/* drivers/dma/ti/edma.c 2269 */;
	struct resource *cocci_id/* drivers/dma/ti/edma.c 2268 */;
	char *cocci_id/* drivers/dma/ti/edma.c 2267 */;
	const  cocci_id/* drivers/dma/ti/edma.c 2265 */(*reserved);
	struct edma_soc_info *cocci_id/* drivers/dma/ti/edma.c 2263 */;
	struct platform_device *cocci_id/* drivers/dma/ti/edma.c 2261 */;
	bool cocci_id/* drivers/dma/ti/edma.c 2259 */(struct dma_chan *chan,
						      void *param);
	struct edma_chan {
		struct virt_dma_chan vchan;
		struct list_head node;
		struct edma_desc *edesc;
		struct edma_cc *ecc;
		struct edma_tc *tc;
		int ch_num;
		bool alloced;
		bool hw_triggered;
		int slot[EDMA_MAX_SLOTS];
		int missed;
		struct dma_slave_config cfg;
	} cocci_id/* drivers/dma/ti/edma.c 224 */;
	struct of_dma *cocci_id/* drivers/dma/ti/edma.c 2209 */;
	struct of_phandle_args *cocci_id/* drivers/dma/ti/edma.c 2208 */;
	struct edma_tc {
		struct device_node *node;
		u16 id;
	} cocci_id/* drivers/dma/ti/edma.c 219 */;
	struct edma_cc cocci_id/* drivers/dma/ti/edma.c 217 */;
	s32 *cocci_id/* drivers/dma/ti/edma.c 1909 */;
	bool cocci_id/* drivers/dma/ti/edma.c 1905 */;
	struct dma_tx_state cocci_id/* drivers/dma/ti/edma.c 1843 */;
	struct dma_tx_state *cocci_id/* drivers/dma/ti/edma.c 1840 */;
	dma_cookie_t cocci_id/* drivers/dma/ti/edma.c 1839 */;
	enum dma_status cocci_id/* drivers/dma/ti/edma.c 1838 */;
	struct edma_desc {
		struct virt_dma_desc vdesc;
		struct list_head node;
		enum dma_transfer_direction direction;
		int cyclic;
		bool polled;
		int absync;
		int pset_nr;
		struct edma_chan *echan;
		int processed;
		int processed_stat;
		u32 sg_len;
		u32 residue;
		u32 residue_stat;
		struct edma_pset pset[0];
	} cocci_id/* drivers/dma/ti/edma.c 178 */;
	struct edma_pset {
		u32 len;
		dma_addr_t addr;
		struct edmacc_param param;
	} cocci_id/* drivers/dma/ti/edma.c 172 */;
	enum dma_event_q cocci_id/* drivers/dma/ti/edma.c 1653 */;
	struct device *cocci_id/* drivers/dma/ti/edma.c 1652 */;
	struct edma_chan *cocci_id/* drivers/dma/ti/edma.c 1650 */;
	struct dma_chan *cocci_id/* drivers/dma/ti/edma.c 1648 */;
	unsigned long cocci_id/* drivers/dma/ti/edma.c 1601 */;
	unsigned int cocci_id/* drivers/dma/ti/edma.c 1577 */;
	struct edma_cc *cocci_id/* drivers/dma/ti/edma.c 1574 */;
	irqreturn_t cocci_id/* drivers/dma/ti/edma.c 1572 */;
	void *cocci_id/* drivers/dma/ti/edma.c 1572 */;
	int cocci_id/* drivers/dma/ti/edma.c 1572 */;
	struct edmacc_param cocci_id/* drivers/dma/ti/edma.c 1522 */;
	struct edmacc_param {
		u32 opt;
		u32 src;
		u32 a_b_cnt;
		u32 dst;
		u32 src_dst_bidx;
		u32 link_bcntrld;
		u32 src_dst_cidx;
		u32 ccnt;
	}__packed cocci_id/* drivers/dma/ti/edma.c 148 */;
	u32 cocci_id/* drivers/dma/ti/edma.c 1477 */;
	struct edma_desc *cocci_id/* drivers/dma/ti/edma.c 1438 */;
	enum dma_slave_buswidth cocci_id/* drivers/dma/ti/edma.c 1287 */;
	size_t cocci_id/* drivers/dma/ti/edma.c 1279 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/ti/edma.c 1278 */;
	struct scatterlist *cocci_id/* drivers/dma/ti/edma.c 1067 */;
}
