cocci_test_suite() {
	struct ip_mreq_source cocci_id/* net/ipv4/ip_sockglue.c 968 */;
	struct ip_msfilter *cocci_id/* net/ipv4/ip_sockglue.c 934 */;
	struct ip_mreq cocci_id/* net/ipv4/ip_sockglue.c 860 */;
	struct ip_mreqn cocci_id/* net/ipv4/ip_sockglue.c 841 */;
	__be32 cocci_id/* net/ipv4/ip_sockglue.c 815 */;
	struct net_device *cocci_id/* net/ipv4/ip_sockglue.c 808 */;
	struct inet_connection_sock *cocci_id/* net/ipv4/ip_sockglue.c 661 */;
	unsigned char __user *cocci_id/* net/ipv4/ip_sockglue.c 629 */;
	char cocci_id/* net/ipv4/ip_sockglue.c 626 */;
	struct sock_extended_err cocci_id/* net/ipv4/ip_sockglue.c 540 */;
	__be32 *cocci_id/* net/ipv4/ip_sockglue.c 533 */;
	struct {
		struct sock_extended_err ee;
		struct sockaddr_in offender;
	} cocci_id/* net/ipv4/ip_sockglue.c 505 */;
	const struct sock *cocci_id/* net/ipv4/ip_sockglue.c 472 */;
	struct iphdr cocci_id/* net/ipv4/ip_sockglue.c 431 */;
	struct iphdr *cocci_id/* net/ipv4/ip_sockglue.c 409 */;
	struct sock_exterr_skb *cocci_id/* net/ipv4/ip_sockglue.c 395 */;
	__be16 cocci_id/* net/ipv4/ip_sockglue.c 393 */;
	struct ip_ra_chain __rcu **cocci_id/* net/ipv4/ip_sockglue.c 339 */;
	struct ip_ra_chain *cocci_id/* net/ipv4/ip_sockglue.c 338 */;
	void (*cocci_id/* net/ipv4/ip_sockglue.c 336 */)(struct sock *);
	struct ip_ra_chain cocci_id/* net/ipv4/ip_sockglue.c 329 */;
	struct rcu_head *cocci_id/* net/ipv4/ip_sockglue.c 327 */;
	u8 *cocci_id/* net/ipv4/ip_sockglue.c 311 */;
	u8 cocci_id/* net/ipv4/ip_sockglue.c 310 */;
	int *cocci_id/* net/ipv4/ip_sockglue.c 302 */;
	struct in_pktinfo *cocci_id/* net/ipv4/ip_sockglue.c 290 */;
	struct cmsghdr cocci_id/* net/ipv4/ip_sockglue.c 280 */;
	struct in6_pktinfo *cocci_id/* net/ipv4/ip_sockglue.c 256 */;
	struct cmsghdr *cocci_id/* net/ipv4/ip_sockglue.c 246 */;
	struct ipcm_cookie *cocci_id/* net/ipv4/ip_sockglue.c 242 */;
	int __user *cocci_id/* net/ipv4/ip_sockglue.c 1588 */;
	char __user *cocci_id/* net/ipv4/ip_sockglue.c 1588 */;
	struct sock *cocci_id/* net/ipv4/ip_sockglue.c 1587 */;
	int cocci_id/* net/ipv4/ip_sockglue.c 1587 */;
	unsigned char cocci_id/* net/ipv4/ip_sockglue.c 1534 */;
	struct sockaddr_in cocci_id/* net/ipv4/ip_sockglue.c 152 */;
	__be16 cocci_id/* net/ipv4/ip_sockglue.c 151 */[2];
	struct in_pktinfo cocci_id/* net/ipv4/ip_sockglue.c 1500 */;
	void *cocci_id/* net/ipv4/ip_sockglue.c 1495 */;
	struct msghdr cocci_id/* net/ipv4/ip_sockglue.c 1488 */;
	struct group_filter __user *cocci_id/* net/ipv4/ip_sockglue.c 1479 */;
	struct group_filter cocci_id/* net/ipv4/ip_sockglue.c 1468 */;
	struct ip_msfilter __user *cocci_id/* net/ipv4/ip_sockglue.c 1463 */;
	struct ip_msfilter cocci_id/* net/ipv4/ip_sockglue.c 1452 */;
	struct in_addr cocci_id/* net/ipv4/ip_sockglue.c 1439 */;
	__u32 cocci_id/* net/ipv4/ip_sockglue.c 1435 */;
	struct dst_entry *cocci_id/* net/ipv4/ip_sockglue.c 1412 */;
	struct net *cocci_id/* net/ipv4/ip_sockglue.c 1392 */;
	struct ip_options cocci_id/* net/ipv4/ip_sockglue.c 1344 */;
	u32 cocci_id/* net/ipv4/ip_sockglue.c 134 */;
	struct ip_options_rcu *cocci_id/* net/ipv4/ip_sockglue.c 1337 */;
	struct ip_options *cocci_id/* net/ipv4/ip_sockglue.c 1336 */;
	unsigned char cocci_id/* net/ipv4/ip_sockglue.c 1335 */[sizeof(struct ip_options) + 40];
	char *cocci_id/* net/ipv4/ip_sockglue.c 133 */;
	bool cocci_id/* net/ipv4/ip_sockglue.c 1313 */;
	struct inet_sock *cocci_id/* net/ipv4/ip_sockglue.c 1312 */;
	unsigned int cocci_id/* net/ipv4/ip_sockglue.c 1268 */;
	struct rtable *cocci_id/* net/ipv4/ip_sockglue.c 1224 */;
	__wsum cocci_id/* net/ipv4/ip_sockglue.c 118 */;
	struct sk_buff *cocci_id/* net/ipv4/ip_sockglue.c 115 */;
	struct msghdr *cocci_id/* net/ipv4/ip_sockglue.c 115 */;
	void cocci_id/* net/ipv4/ip_sockglue.c 115 */;
	struct group_filter *cocci_id/* net/ipv4/ip_sockglue.c 1084 */;
	struct group_source_req cocci_id/* net/ipv4/ip_sockglue.c 1031 */;
	struct sockaddr_in *cocci_id/* net/ipv4/ip_sockglue.c 1005 */;
	struct group_req cocci_id/* net/ipv4/ip_sockglue.c 1004 */;
}
