cocci_test_suite() {
	struct omap_desc {
		struct virt_dma_desc vd;
		bool using_ll;
		enum dma_transfer_direction dir;
		dma_addr_t dev_addr;
		bool polled;
		int32_t fi;
		int16_t ei;
		uint8_t es;
		uint32_t ccr;
		uint16_t clnk_ctrl;
		uint16_t cicr;
		uint32_t csdp;
		unsigned sglen;
		struct omap_sg sg[0];
	} cocci_id/* drivers/dma/ti/omap-dma.c 89 */;
	struct scatterlist *cocci_id/* drivers/dma/ti/omap-dma.c 886 */;
	dma_cookie_t cocci_id/* drivers/dma/ti/omap-dma.c 814 */;
	struct dma_tx_state *cocci_id/* drivers/dma/ti/omap-dma.c 814 */;
	enum dma_status cocci_id/* drivers/dma/ti/omap-dma.c 813 */;
	struct omap_sg {
		dma_addr_t addr;
		uint32_t en;
		uint32_t fn;
		int32_t fi;
		int16_t ei;
		struct omap_type2_desc *t2_desc;
		dma_addr_t t2_desc_paddr;
	} cocci_id/* drivers/dma/ti/omap-dma.c 77 */;
	uint32_t cocci_id/* drivers/dma/ti/omap-dma.c 749 */;
	dma_addr_t cocci_id/* drivers/dma/ti/omap-dma.c 728 */;
	size_t cocci_id/* drivers/dma/ti/omap-dma.c 717 */;
	unsigned cocci_id/* drivers/dma/ti/omap-dma.c 657 */;
	struct omap_type2_desc {
		uint32_t next_desc;
		uint32_t en;
		uint32_t addr;
		uint16_t fn;
		uint16_t cicr;
		int16_t cdei;
		int16_t csei;
		int32_t cdfi;
		int32_t csfi;
	}__packed cocci_id/* drivers/dma/ti/omap-dma.c 65 */;
	struct device *cocci_id/* drivers/dma/ti/omap-dma.c 640 */;
	struct omap_chan *cocci_id/* drivers/dma/ti/omap-dma.c 639 */;
	struct omap_dmadev *cocci_id/* drivers/dma/ti/omap-dma.c 638 */;
	struct dma_chan *cocci_id/* drivers/dma/ti/omap-dma.c 636 */;
	int cocci_id/* drivers/dma/ti/omap-dma.c 636 */;
	irqreturn_t cocci_id/* drivers/dma/ti/omap-dma.c 596 */;
	unsigned long cocci_id/* drivers/dma/ti/omap-dma.c 579 */;
	struct omap_desc *cocci_id/* drivers/dma/ti/omap-dma.c 578 */;
	u16 cocci_id/* drivers/dma/ti/omap-dma.c 575 */;
	void *cocci_id/* drivers/dma/ti/omap-dma.c 575 */;
	u32 cocci_id/* drivers/dma/ti/omap-dma.c 430 */;
	struct omap_chan {
		struct virt_dma_chan vc;
		void __iomem *channel_base;
		const struct omap_dma_reg *reg_map;
		uint32_t ccr;
		struct dma_slave_config cfg;
		unsigned dma_sig;
		bool cyclic;
		bool paused;
		bool running;
		int dma_ch;
		struct omap_desc *desc;
		unsigned sgidx;
	} cocci_id/* drivers/dma/ti/omap-dma.c 41 */;
	uint16_t cocci_id/* drivers/dma/ti/omap-dma.c 390 */;
	void cocci_id/* drivers/dma/ti/omap-dma.c 379 */;
	const struct omap_dma_reg *cocci_id/* drivers/dma/ti/omap-dma.c 356 */;
	void __iomem *cocci_id/* drivers/dma/ti/omap-dma.c 306 */;
	struct omap_dmadev {
		struct dma_device ddev;
		spinlock_t lock;
		void __iomem *base;
		const struct omap_dma_reg *reg_map;
		struct omap_system_dma_plat_info *plat;
		bool legacy;
		bool ll123_supported;
		struct dma_pool *desc_pool;
		unsigned dma_requests;
		spinlock_t irq_lock;
		uint32_t irq_enable_mask;
		struct omap_chan **lch_map;
	} cocci_id/* drivers/dma/ti/omap-dma.c 26 */;
	struct omap_type2_desc *cocci_id/* drivers/dma/ti/omap-dma.c 248 */;
	struct omap_sg *cocci_id/* drivers/dma/ti/omap-dma.c 247 */;
	bool cocci_id/* drivers/dma/ti/omap-dma.c 245 */;
	enum dma_transfer_direction cocci_id/* drivers/dma/ti/omap-dma.c 245 */;
	struct virt_dma_desc *cocci_id/* drivers/dma/ti/omap-dma.c 226 */;
	struct omap_desc cocci_id/* drivers/dma/ti/omap-dma.c 223 */;
	struct omap_dmadev cocci_id/* drivers/dma/ti/omap-dma.c 213 */;
	struct dma_device *cocci_id/* drivers/dma/ti/omap-dma.c 211 */;
	struct of_dma_filter_info cocci_id/* drivers/dma/ti/omap-dma.c 207 */;
	bool cocci_id/* drivers/dma/ti/omap-dma.c 206 */(struct dma_chan *chan,
							 void *param);
	const unsigned cocci_id/* drivers/dma/ti/omap-dma.c 200 */[];
	void __exit cocci_id/* drivers/dma/ti/omap-dma.c 1680 */;
	unsigned *cocci_id/* drivers/dma/ti/omap-dma.c 1664 */;
	struct platform_driver cocci_id/* drivers/dma/ti/omap-dma.c 1650 */;
	const struct of_device_id cocci_id/* drivers/dma/ti/omap-dma.c 1640 */[];
	struct omap_type2_desc cocci_id/* drivers/dma/ti/omap-dma.c 1576 */;
	struct resource *cocci_id/* drivers/dma/ti/omap-dma.c 1463 */;
	struct platform_device *cocci_id/* drivers/dma/ti/omap-dma.c 1460 */;
	struct omap_chan cocci_id/* drivers/dma/ti/omap-dma.c 1448 */;
	struct dma_slave_config *cocci_id/* drivers/dma/ti/omap-dma.c 1297 */;
	uint8_t cocci_id/* drivers/dma/ti/omap-dma.c 1221 */;
	struct dma_interleaved_template *cocci_id/* drivers/dma/ti/omap-dma.c 1215 */;
	enum{CAPS_0_SUPPORT_LL123=BIT(20), CAPS_0_SUPPORT_LL4=BIT(21), CCR_FS=BIT(5), CCR_READ_PRIORITY=BIT(6), CCR_ENABLE=BIT(7), CCR_AUTO_INIT=BIT(8), CCR_REPEAT=BIT(9), CCR_OMAP31_DISABLE=BIT(10), CCR_SUSPEND_SENSITIVE=BIT(8), CCR_RD_ACTIVE=BIT(9), CCR_WR_ACTIVE=BIT(10), CCR_SRC_AMODE_CONSTANT=0 << 12, CCR_SRC_AMODE_POSTINC=1 << 12, CCR_SRC_AMODE_SGLIDX=2 << 12, CCR_SRC_AMODE_DBLIDX=3 << 12, CCR_DST_AMODE_CONSTANT=0 << 14, CCR_DST_AMODE_POSTINC=1 << 14, CCR_DST_AMODE_SGLIDX=2 << 14, CCR_DST_AMODE_DBLIDX=3 << 14, CCR_CONSTANT_FILL=BIT(16), CCR_TRANSPARENT_COPY=BIT(17), CCR_BS=BIT(18), CCR_SUPERVISOR=BIT(22), CCR_PREFETCH=BIT(23), CCR_TRIGGER_SRC=BIT(24), CCR_BUFFERING_DISABLE=BIT(25), CCR_WRITE_PRIORITY=BIT(26), CCR_SYNC_ELEMENT=0, CCR_SYNC_FRAME=CCR_FS, CCR_SYNC_BLOCK=CCR_BS, CCR_SYNC_PACKET=CCR_BS | CCR_FS, CSDP_DATA_TYPE_8=0, CSDP_DATA_TYPE_16=1, CSDP_DATA_TYPE_32=2, CSDP_SRC_PORT_EMIFF=0 << 2, CSDP_SRC_PORT_EMIFS=1 << 2, CSDP_SRC_PORT_OCP_T1=2 << 2, CSDP_SRC_PORT_TIPB=3 << 2, CSDP_SRC_PORT_OCP_T2=4 << 2, CSDP_SRC_PORT_MPUI=5 << 2, CSDP_SRC_PACKED=BIT(6), CSDP_SRC_BURST_1=0 << 7, CSDP_SRC_BURST_16=1 << 7, CSDP_SRC_BURST_32=2 << 7, CSDP_SRC_BURST_64=3 << 7, CSDP_DST_PORT_EMIFF=0 << 9, CSDP_DST_PORT_EMIFS=1 << 9, CSDP_DST_PORT_OCP_T1=2 << 9, CSDP_DST_PORT_TIPB=3 << 9, CSDP_DST_PORT_OCP_T2=4 << 9, CSDP_DST_PORT_MPUI=5 << 9, CSDP_DST_PACKED=BIT(13), CSDP_DST_BURST_1=0 << 14, CSDP_DST_BURST_16=1 << 14, CSDP_DST_BURST_32=2 << 14, CSDP_DST_BURST_64=3 << 14, CSDP_WRITE_NON_POSTED=0 << 16, CSDP_WRITE_POSTED=1 << 16, CSDP_WRITE_LAST_NON_POSTED=2 << 16, CICR_TOUT_IE=BIT(0), CICR_DROP_IE=BIT(1), CICR_HALF_IE=BIT(2), CICR_FRAME_IE=BIT(3), CICR_LAST_IE=BIT(4), CICR_BLOCK_IE=BIT(5), CICR_PKT_IE=BIT(7), CICR_TRANS_ERR_IE=BIT(8), CICR_SUPERVISOR_ERR_IE=BIT(10), CICR_MISALIGNED_ERR_IE=BIT(11), CICR_DRAIN_IE=BIT(12), CICR_SUPER_BLOCK_IE=BIT(14), CLNK_CTRL_ENABLE_LNK=BIT(15), CDP_DST_VALID_INC=0 << 0, CDP_DST_VALID_RELOAD=1 << 0, CDP_DST_VALID_REUSE=2 << 0, CDP_SRC_VALID_INC=0 << 2, CDP_SRC_VALID_RELOAD=1 << 2, CDP_SRC_VALID_REUSE=2 << 2, CDP_NTYPE_TYPE1=1 << 4, CDP_NTYPE_TYPE2=2 << 4, CDP_NTYPE_TYPE3=3 << 4, CDP_TMODE_NORMAL=0 << 8, CDP_TMODE_LLIST=1 << 8, CDP_FAST=BIT(10),} cocci_id/* drivers/dma/ti/omap-dma.c 108 */;
	enum dma_slave_buswidth cocci_id/* drivers/dma/ti/omap-dma.c 1073 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/ti/omap-dma.c 1067 */;
}
