cocci_test_suite() {
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/ipu/ipu_idmac.c 926 */;
	struct idmac_tx_desc cocci_id/* drivers/dma/ipu/ipu_idmac.c 911 */;
	uint32_t cocci_id/* drivers/dma/ipu/ipu_idmac.c 88 */;
	enum pixel_fmt cocci_id/* drivers/dma/ipu/ipu_idmac.c 88 */;
	dma_addr_t cocci_id/* drivers/dma/ipu/ipu_idmac.c 847 */;
	struct idmac_video_param *cocci_id/* drivers/dma/ipu/ipu_idmac.c 842 */;
	union chan_param_mem cocci_id/* drivers/dma/ipu/ipu_idmac.c 660 */;
	enum ipu_channel cocci_id/* drivers/dma/ipu/ipu_idmac.c 575 */;
	union ipu_channel_param *cocci_id/* drivers/dma/ipu/ipu_idmac.c 509 */;
	void cocci_id/* drivers/dma/ipu/ipu_idmac.c 50 */;
	enum ipu_color_space cocci_id/* drivers/dma/ipu/ipu_idmac.c 494 */;
	uint32_t *cocci_id/* drivers/dma/ipu/ipu_idmac.c 453 */;
	enum ipu_rotate_mode cocci_id/* drivers/dma/ipu/ipu_idmac.c 430 */;
	u32 cocci_id/* drivers/dma/ipu/ipu_idmac.c 43 */;
	struct ipu *cocci_id/* drivers/dma/ipu/ipu_idmac.c 43 */;
	unsigned long cocci_id/* drivers/dma/ipu/ipu_idmac.c 43 */;
	union chan_param_mem *cocci_id/* drivers/dma/ipu/ipu_idmac.c 422 */;
	struct ipu cocci_id/* drivers/dma/ipu/ipu_idmac.c 39 */;
	int cocci_id/* drivers/dma/ipu/ipu_idmac.c 30 */(struct idmac *idmac,
							 struct idmac_channel *ichan,
							 bool wait_for_stop);
	uint16_t cocci_id/* drivers/dma/ipu/ipu_idmac.c 283 */;
	union chan_param_mem {
		struct chan_param_mem_planar pp;
		struct chan_param_mem_interleaved ip;
	} cocci_id/* drivers/dma/ipu/ipu_idmac.c 268 */;
	struct chan_param_mem_interleaved {
		u32 xv:10;
		u32 yv:10;
		u32 xb:12;
		u32 yb:12;
		u32 sce:1;
		u32 res1:1;
		u32 nsb:1;
		u32 lnpb:6;
		u32 sx:10;
		u32 sy_l:1;
		u32 sy_h:9;
		u32 ns:10;
		u32 sm:10;
		u32 sdx_l:3;
		u32 sdx_h:2;
		u32 sdy:5;
		u32 sdrx:1;
		u32 sdry:1;
		u32 sdr1:1;
		u32 res2:2;
		u32 fw:12;
		u32 fh_l:8;
		u32 fh_h:4;
		u32 res3:28;
		u32 eba0;
		u32 eba1;
		u32 bpp:3;
		u32 sl:14;
		u32 pfs:3;
		u32 bam:3;
		u32 res4:2;
		u32 npb:6;
		u32 res5:1;
		u32 sat:2;
		u32 scc:1;
		u32 ofs0:5;
		u32 ofs1:5;
		u32 ofs2:5;
		u32 ofs3:5;
		u32 wid0:3;
		u32 wid1:3;
		u32 wid2:3;
		u32 wid3:3;
		u32 dec_sel:1;
		u32 res6:28;
	}__attribute__((packed)) cocci_id/* drivers/dma/ipu/ipu_idmac.c 209 */;
	struct platform_driver cocci_id/* drivers/dma/ipu/ipu_idmac.c 1785 */;
	struct chan_param_mem_planar {
		u32 xv:10;
		u32 yv:10;
		u32 xb:12;
		u32 yb:12;
		u32 res1:2;
		u32 nsb:1;
		u32 lnpb:6;
		u32 ubo_l:11;
		u32 ubo_h:15;
		u32 vbo_l:17;
		u32 vbo_h:9;
		u32 res2:3;
		u32 fw:12;
		u32 fh_l:8;
		u32 fh_h:4;
		u32 res3:28;
		u32 eba0;
		u32 eba1;
		u32 bpp:3;
		u32 sl:14;
		u32 pfs:3;
		u32 bam:3;
		u32 res4:2;
		u32 npb:6;
		u32 res5:1;
		u32 sat:2;
		u32 res6:30;
	}__attribute__((packed)) cocci_id/* drivers/dma/ipu/ipu_idmac.c 169 */;
	struct resource *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1672 */;
	struct platform_device *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1670 */;
	struct dma_device *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1611 */;
	int __init cocci_id/* drivers/dma/ipu/ipu_idmac.c 1608 */;
	dma_cookie_t cocci_id/* drivers/dma/ipu/ipu_idmac.c 1603 */;
	struct dma_tx_state *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1603 */;
	enum dma_status cocci_id/* drivers/dma/ipu/ipu_idmac.c 1602 */;
	irqreturn_t cocci_id/* drivers/dma/ipu/ipu_idmac.c 1488 */;
	void *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1488 */;
	struct idmac_tx_desc *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1445 */;
	struct idmac *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1429 */;
	struct idmac_channel *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1428 */;
	struct dma_chan *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1426 */;
	int cocci_id/* drivers/dma/ipu/ipu_idmac.c 1426 */;
	struct list_head *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1402 */;
	enum dma_transfer_direction cocci_id/* drivers/dma/ipu/ipu_idmac.c 1335 */;
	struct scatterlist *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1334 */;
	u64 cocci_id/* drivers/dma/ipu/ipu_idmac.c 1233 */;
	struct dmaengine_desc_callback cocci_id/* drivers/dma/ipu/ipu_idmac.c 1164 */;
	bool cocci_id/* drivers/dma/ipu/ipu_idmac.c 1161 */;
	struct scatterlist **cocci_id/* drivers/dma/ipu/ipu_idmac.c 1158 */;
	unsigned int cocci_id/* drivers/dma/ipu/ipu_idmac.c 1157 */;
	struct device *cocci_id/* drivers/dma/ipu/ipu_idmac.c 1156 */;
	struct idmac_tx_desc **cocci_id/* drivers/dma/ipu/ipu_idmac.c 1124 */;
}
