cocci_test_suite() {
	struct net *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 994 */;
	struct rpc_clnt *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 993 */;
	struct gss_pipe *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 991 */;
	void cocci_id/* net/sunrpc/auth_gss/auth_gss.c 991 */;
	struct gss_alloc_pdo cocci_id/* net/sunrpc/auth_gss/auth_gss.c 975 */;
	struct gss_alloc_pdo *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 961 */;
	struct rpc_pipe_dir_object *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 958 */;
	void *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 958 */;
	struct gss_alloc_pdo {
		struct rpc_clnt *clnt;
		const char *name;
		const struct rpc_pipe_ops *upcall_ops;
	} cocci_id/* net/sunrpc/auth_gss/auth_gss.c 937 */;
	const struct rpc_pipe_ops *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 911 */;
	const struct rpc_pipe_ops cocci_id/* net/sunrpc/auth_gss/auth_gss.c 91 */;
	const struct rpc_pipe_dir_object_ops cocci_id/* net/sunrpc/auth_gss/auth_gss.c 904 */;
	void cocci_id/* net/sunrpc/auth_gss/auth_gss.c 90 */(struct gss_cl_ctx *);
	struct dentry *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 891 */;
	void cocci_id/* net/sunrpc/auth_gss/auth_gss.c 88 */(struct gss_auth *gss_auth);
	struct gss_upcall_msg cocci_id/* net/sunrpc/auth_gss/auth_gss.c 867 */;
	struct rpc_pipe_msg *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 865 */;
	struct rpc_wait_queue cocci_id/* net/sunrpc/auth_gss/auth_gss.c 86 */;
	struct inode *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 805 */;
	const char __user *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 716 */;
	struct file *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 716 */;
	ssize_t cocci_id/* net/sunrpc/auth_gss/auth_gss.c 715 */;
	struct gss_auth {
		struct kref kref;
		struct hlist_node hash;
		struct rpc_auth rpc_auth;
		struct gss_api_mech *mech;
		enum rpc_gss_svc service;
		struct rpc_clnt *client;
		struct net *net;
		struct gss_pipe *gss_pipe[2];
		const char *target_name;
	} cocci_id/* net/sunrpc/auth_gss/auth_gss.c 66 */;
	struct gss_pipe {
		struct rpc_pipe_dir_object pdo;
		struct rpc_pipe *pipe;
		struct rpc_clnt *clnt;
		const char *name;
		struct kref kref;
	} cocci_id/* net/sunrpc/auth_gss/auth_gss.c 58 */;
	const char *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 534 */;
	struct gss_auth *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 533 */;
	size_t cocci_id/* net/sunrpc/auth_gss/auth_gss.c 448 */;
	char *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 447 */;
	struct gss_api_mech *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 446 */;
	char __user *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 430 */;
	uid_t cocci_id/* net/sunrpc/auth_gss/auth_gss.c 420 */;
	struct user_namespace *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 418 */;
	const struct cred *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 416 */;
	unsigned int cocci_id/* net/sunrpc/auth_gss/auth_gss.c 41 */;
	const struct rpc_credops cocci_id/* net/sunrpc/auth_gss/auth_gss.c 37 */;
	const struct rpc_authops cocci_id/* net/sunrpc/auth_gss/auth_gss.c 35 */;
	kuid_t cocci_id/* net/sunrpc/auth_gss/auth_gss.c 325 */;
	const struct gss_auth *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 325 */;
	struct rpc_pipe *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 325 */;
	struct gss_upcall_msg *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 324 */;
	struct sunrpc_net *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 285 */;
	struct gss_upcall_msg {
		refcount_t count;
		kuid_t uid;
		const char *service_name;
		struct rpc_pipe_msg msg;
		struct list_head list;
		struct gss_auth *auth;
		struct rpc_pipe *pipe;
		struct rpc_wait_queue rpc_waitqueue;
		wait_queue_head_t waitqueue;
		struct gss_cl_ctx *ctx;
		char databuf[UPCALL_BUF_LEN];
	} cocci_id/* net/sunrpc/auth_gss/auth_gss.c 269 */;
	void __exit cocci_id/* net/sunrpc/auth_gss/auth_gss.c 2210 */;
	int __init cocci_id/* net/sunrpc/auth_gss/auth_gss.c 2187 */;
	struct pernet_operations cocci_id/* net/sunrpc/auth_gss/auth_gss.c 2179 */;
	bool cocci_id/* net/sunrpc/auth_gss/auth_gss.c 2036 */;
	struct kvec *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1991 */;
	u32 cocci_id/* net/sunrpc/auth_gss/auth_gss.c 193 */;
	const void *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 186 */;
	struct page **cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1827 */;
	struct page *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1801 */;
	struct xdr_buf *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1785 */;
	struct rpc_rqst *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1783 */;
	int cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1782 */;
	struct gss_cl_ctx *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 170 */;
	struct gss_cred cocci_id/* net/sunrpc/auth_gss/auth_gss.c 159 */;
	void **cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1580 */;
	u8 *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1567 */;
	struct xdr_buf cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1536 */;
	struct kvec cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1535 */;
	struct xdr_netobj cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1534 */;
	__be32 *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1532 */;
	struct xdr_stream *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1525 */;
	struct rpc_task *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1525 */;
	struct xdr_netobj *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1417 */;
	struct gss_cred *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1376 */;
	struct gss_auth cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1375 */;
	gfp_t cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1373 */;
	struct auth_cred *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1373 */;
	struct rpc_cred *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1372 */;
	struct rcu_head *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1327 */;
	struct gss_cl_ctx cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1310 */;
	struct auth_cred cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1248 */;
	struct rpc_xprt_switch *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1224 */;
	struct rpc_auth *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1220 */;
	unsigned long cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1169 */;
	const struct rpc_auth_create_args *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1164 */;
	rpc_authflavor_t cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1023 */;
	struct gss_pipe cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1005 */;
	struct kref *cocci_id/* net/sunrpc/auth_gss/auth_gss.c 1003 */;
}
