cocci_test_suite() {
	u64 *cocci_id/* net/can/bcm.c 98 */;
	u64 cocci_id/* net/can/bcm.c 96 */;
	struct list_head *cocci_id/* net/can/bcm.c 744 */;
	struct bcm_msg_head *cocci_id/* net/can/bcm.c 744 */;
	struct bcm_op cocci_id/* net/can/bcm.c 618 */;
	enum hrtimer_restart cocci_id/* net/can/bcm.c 616 */;
	struct hrtimer *cocci_id/* net/can/bcm.c 616 */;
	const struct canfd_frame *cocci_id/* net/can/bcm.c 503 */;
	unsigned int cocci_id/* net/can/bcm.c 502 */;
	struct bcm_msg_head cocci_id/* net/can/bcm.c 430 */;
	struct can_skb_priv cocci_id/* net/can/bcm.c 283 */;
	struct canfd_frame *cocci_id/* net/can/bcm.c 271 */;
	struct net_device *cocci_id/* net/can/bcm.c 270 */;
	struct sk_buff *cocci_id/* net/can/bcm.c 269 */;
	struct bcm_op *cocci_id/* net/can/bcm.c 267 */;
	void cocci_id/* net/can/bcm.c 267 */;
	long long cocci_id/* net/can/bcm.c 223 */;
	char cocci_id/* net/can/bcm.c 190 */[IFNAMSIZ];
	struct seq_file *cocci_id/* net/can/bcm.c 188 */;
	void __exit cocci_id/* net/can/bcm.c 1713 */;
	char *cocci_id/* net/can/bcm.c 170 */;
	int __init cocci_id/* net/can/bcm.c 1697 */;
	struct pernet_operations cocci_id/* net/can/bcm.c 1692 */;
	const struct can_proto cocci_id/* net/can/bcm.c 1666 */;
	struct proto cocci_id/* net/can/bcm.c 1659 */;
	const struct proto_ops cocci_id/* net/can/bcm.c 1638 */;
	struct sockaddr_can cocci_id/* net/can/bcm.c 1621 */;
	struct msghdr *cocci_id/* net/can/bcm.c 1594 */;
	size_t cocci_id/* net/can/bcm.c 1594 */;
	struct net *cocci_id/* net/can/bcm.c 1536 */;
	struct bcm_sock *cocci_id/* net/can/bcm.c 1535 */;
	struct sock *cocci_id/* net/can/bcm.c 1534 */;
	struct sockaddr_can *cocci_id/* net/can/bcm.c 1533 */;
	struct socket *cocci_id/* net/can/bcm.c 1530 */;
	struct sockaddr *cocci_id/* net/can/bcm.c 1530 */;
	int cocci_id/* net/can/bcm.c 1530 */;
	bool cocci_id/* net/can/bcm.c 147 */;
	ktime_t cocci_id/* net/can/bcm.c 141 */;
	struct bcm_timeval cocci_id/* net/can/bcm.c 141 */;
	struct bcm_sock cocci_id/* net/can/bcm.c 1385 */;
	void *cocci_id/* net/can/bcm.c 1382 */;
	struct notifier_block *cocci_id/* net/can/bcm.c 1381 */;
	unsigned long cocci_id/* net/can/bcm.c 1381 */;
	const struct sock *cocci_id/* net/can/bcm.c 136 */;
	u8 *cocci_id/* net/can/bcm.c 1283 */;
	struct bcm_sock {
		struct sock sk;
		int bound;
		int ifindex;
		struct notifier_block notifier;
		struct list_head rx_ops;
		struct list_head tx_ops;
		unsigned long dropped_usr_msgs;
		struct proc_dir_entry *bcm_proc_read;
		char procname[32];
	} cocci_id/* net/can/bcm.c 124 */;
	struct bcm_op {
		struct list_head list;
		int ifindex;
		canid_t can_id;
		u32 flags;
		unsigned long frames_abs,frames_filtered;
		struct bcm_timeval ival1,ival2;
		struct hrtimer timer,thrtimer;
		ktime_t rx_stamp,kt_ival1,kt_ival2,kt_lastmsg;
		int rx_ifindex;
		int cfsiz;
		u32 count;
		u32 nframes;
		u32 currframe;
		void *frames;
		void *last_frames;
		struct canfd_frame sframe;
		struct canfd_frame last_sframe;
		struct sock *sk;
		struct net_device *rx_reg_dev;
	} cocci_id/* net/can/bcm.c 101 */;
}
