cocci_test_suite() {
	u32 *cocci_id/* drivers/dma/mv_xor.c 988 */;
	dma_addr_t cocci_id/* drivers/dma/mv_xor.c 877 */[MV_XOR_NUM_SRC_TEST];
	struct page *cocci_id/* drivers/dma/mv_xor.c 876 */[MV_XOR_NUM_SRC_TEST];
	struct page *cocci_id/* drivers/dma/mv_xor.c 875 */;
	u8 cocci_id/* drivers/dma/mv_xor.c 784 */;
	u8 *cocci_id/* drivers/dma/mv_xor.c 784 */;
	struct dmaengine_unmap_data *cocci_id/* drivers/dma/mv_xor.c 769 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/mv_xor.c 768 */;
	dma_cookie_t cocci_id/* drivers/dma/mv_xor.c 767 */;
	struct dma_chan *cocci_id/* drivers/dma/mv_xor.c 766 */;
	dma_addr_t cocci_id/* drivers/dma/mv_xor.c 765 */;
	void *cocci_id/* drivers/dma/mv_xor.c 764 */;
	irqreturn_t cocci_id/* drivers/dma/mv_xor.c 730 */;
	struct dma_tx_state *cocci_id/* drivers/dma/mv_xor.c 676 */;
	enum dma_status cocci_id/* drivers/dma/mv_xor.c 674 */;
	size_t cocci_id/* drivers/dma/mv_xor.c 614 */;
	dma_addr_t *cocci_id/* drivers/dma/mv_xor.c 555 */;
	enum dma_ctrl_flags cocci_id/* drivers/dma/mv_xor.c 50 */;
	void __iomem *cocci_id/* drivers/dma/mv_xor.c 486 */;
	struct mv_xor_device *cocci_id/* drivers/dma/mv_xor.c 485 */;
	struct mv_xor_chan cocci_id/* drivers/dma/mv_xor.c 40 */;
	void cocci_id/* drivers/dma/mv_xor.c 37 */(struct dma_chan *chan);
	struct mv_xor_desc_slot cocci_id/* drivers/dma/mv_xor.c 357 */;
	struct mv_xor_desc_slot *cocci_id/* drivers/dma/mv_xor.c 348 */;
	enum mv_xor_mode{XOR_MODE_IN_REG, XOR_MODE_IN_DESC,} cocci_id/* drivers/dma/mv_xor.c 32 */;
	struct mv_xor_desc *cocci_id/* drivers/dma/mv_xor.c 270 */;
	enum mv_xor_type{XOR_ORION, XOR_ARMADA_38X, XOR_ARMADA_37XX,} cocci_id/* drivers/dma/mv_xor.c 26 */;
	int cocci_id/* drivers/dma/mv_xor.c 214 */;
	char cocci_id/* drivers/dma/mv_xor.c 164 */;
	struct mv_xor_chan *cocci_id/* drivers/dma/mv_xor.c 156 */;
	void cocci_id/* drivers/dma/mv_xor.c 156 */;
	struct platform_driver cocci_id/* drivers/dma/mv_xor.c 1453 */;
	struct mv_xor_channel_data *cocci_id/* drivers/dma/mv_xor.c 1413 */;
	struct device_node *cocci_id/* drivers/dma/mv_xor.c 1378 */;
	uintptr_t cocci_id/* drivers/dma/mv_xor.c 1337 */;
	const struct of_device_id *cocci_id/* drivers/dma/mv_xor.c 1333 */;
	struct resource *cocci_id/* drivers/dma/mv_xor.c 1296 */;
	struct mv_xor_platform_data *cocci_id/* drivers/dma/mv_xor.c 1295 */;
	unsigned int cocci_id/* drivers/dma/mv_xor.c 1289 */;
	const struct of_device_id cocci_id/* drivers/dma/mv_xor.c 1282 */[];
	u32 cocci_id/* drivers/dma/mv_xor.c 125 */;
	pm_message_t cocci_id/* drivers/dma/mv_xor.c 1232 */;
	const struct mbus_dram_window *cocci_id/* drivers/dma/mv_xor.c 1178 */;
	const struct mbus_dram_target_info *cocci_id/* drivers/dma/mv_xor.c 1164 */;
	unsigned long cocci_id/* drivers/dma/mv_xor.c 1100 */;
	struct dma_device *cocci_id/* drivers/dma/mv_xor.c 1040 */;
	dma_cap_mask_t cocci_id/* drivers/dma/mv_xor.c 1036 */;
	struct platform_device *cocci_id/* drivers/dma/mv_xor.c 1035 */;
	struct device *cocci_id/* drivers/dma/mv_xor.c 1012 */;
}
