cocci_test_suite() {
	u16 cocci_id/* net/ipv6/raw.c 783 */;
	struct ipcm6_cookie cocci_id/* net/ipv6/raw.c 780 */;
	struct flowi6 cocci_id/* net/ipv6/raw.c 779 */;
	struct raw6_frag_vec cocci_id/* net/ipv6/raw.c 778 */;
	struct dst_entry *cocci_id/* net/ipv6/raw.c 777 */;
	struct ip6_flowlabel *cocci_id/* net/ipv6/raw.c 776 */;
	struct in6_addr *cocci_id/* net/ipv6/raw.c 771 */;
	struct ipv6_txoptions cocci_id/* net/ipv6/raw.c 769 */;
	struct ipv6_txoptions *cocci_id/* net/ipv6/raw.c 768 */;
	struct raw6_frag_vec *cocci_id/* net/ipv6/raw.c 738 */;
	char *cocci_id/* net/ipv6/raw.c 735 */;
	void *cocci_id/* net/ipv6/raw.c 735 */;
	bool cocci_id/* net/ipv6/raw.c 73 */;
	struct flowi6 *cocci_id/* net/ipv6/raw.c 714 */;
	int cocci_id/* net/ipv6/raw.c 71 */;
	struct raw6_frag_vec {
		struct msghdr *msg;
		int hlen;
		char c[4];
	} cocci_id/* net/ipv6/raw.c 708 */;
	const struct in6_addr *cocci_id/* net/ipv6/raw.c 70 */;
	unsigned short cocci_id/* net/ipv6/raw.c 70 */;
	struct sock *cocci_id/* net/ipv6/raw.c 69 */;
	struct net *cocci_id/* net/ipv6/raw.c 69 */;
	struct raw_hashinfo cocci_id/* net/ipv6/raw.c 64 */;
	struct ipv6hdr cocci_id/* net/ipv6/raw.c 635 */;
	struct rt6_info *cocci_id/* net/ipv6/raw.c 627 */;
	struct ipv6hdr *cocci_id/* net/ipv6/raw.c 624 */;
	const struct sockcm_cookie *cocci_id/* net/ipv6/raw.c 620 */;
	struct dst_entry **cocci_id/* net/ipv6/raw.c 619 */;
	__sum16 cocci_id/* net/ipv6/raw.c 548 */;
	__wsum cocci_id/* net/ipv6/raw.c 547 */;
	int *cocci_id/* net/ipv6/raw.c 463 */;
	struct msghdr *cocci_id/* net/ipv6/raw.c 462 */;
	size_t cocci_id/* net/ipv6/raw.c 462 */;
	const struct ipv6hdr *cocci_id/* net/ipv6/raw.c 375 */;
	u8 cocci_id/* net/ipv6/raw.c 362 */;
	__be32 cocci_id/* net/ipv6/raw.c 362 */;
	u8 *cocci_id/* net/ipv6/raw.c 349 */;
	struct inet6_skb_parm *cocci_id/* net/ipv6/raw.c 323 */;
	struct sockaddr_in6 cocci_id/* net/ipv6/raw.c 275 */;
	struct net_device *cocci_id/* net/ipv6/raw.c 272 */;
	struct sockaddr_in6 *cocci_id/* net/ipv6/raw.c 246 */;
	struct ipv6_pinfo *cocci_id/* net/ipv6/raw.c 245 */;
	struct inet_sock *cocci_id/* net/ipv6/raw.c 244 */;
	struct sockaddr *cocci_id/* net/ipv6/raw.c 242 */;
	mh_filter_t *cocci_id/* net/ipv6/raw.c 199 */;
	__u8 cocci_id/* net/ipv6/raw.c 163 */;
	struct sk_buff *cocci_id/* net/ipv6/raw.c 157 */;
	struct inet_protosw cocci_id/* net/ipv6/raw.c 1385 */;
	const struct proto_ops cocci_id/* net/ipv6/raw.c 1359 */;
	int __init cocci_id/* net/ipv6/raw.c 1347 */;
	struct pernet_operations cocci_id/* net/ipv6/raw.c 1342 */;
	void __net_exit cocci_id/* net/ipv6/raw.c 1337 */;
	struct raw_iter_state cocci_id/* net/ipv6/raw.c 1331 */;
	mh_filter_t cocci_id/* net/ipv6/raw.c 133 */;
	int __net_init cocci_id/* net/ipv6/raw.c 1328 */;
	const struct seq_operations cocci_id/* net/ipv6/raw.c 1321 */;
	__u16 cocci_id/* net/ipv6/raw.c 1314 */;
	mh_filter_t __rcu *cocci_id/* net/ipv6/raw.c 131 */;
	struct seq_file *cocci_id/* net/ipv6/raw.c 1308 */;
	struct raw6_sock cocci_id/* net/ipv6/raw.c 1295 */;
	int cocci_id/* net/ipv6/raw.c 129 */(struct sock *sock,
					     struct sk_buff *skb);
	struct proto cocci_id/* net/ipv6/raw.c 1278 */;
	void cocci_id/* net/ipv6/raw.c 1250 */;
	long cocci_id/* net/ipv6/raw.c 1242 */;
	unsigned long cocci_id/* net/ipv6/raw.c 1226 */;
	unsigned int cocci_id/* net/ipv6/raw.c 1226 */;
	void __user *cocci_id/* net/ipv6/raw.c 1218 */;
	const __u32 *cocci_id/* net/ipv6/raw.c 120 */;
	int __user *cocci_id/* net/ipv6/raw.c 1174 */;
	char __user *cocci_id/* net/ipv6/raw.c 1174 */;
	const struct icmp6hdr *cocci_id/* net/ipv6/raw.c 112 */;
	struct raw6_sock *cocci_id/* net/ipv6/raw.c 1114 */;
	struct icmp6hdr cocci_id/* net/ipv6/raw.c 111 */;
	const struct sock *cocci_id/* net/ipv6/raw.c 109 */;
	const struct sk_buff *cocci_id/* net/ipv6/raw.c 109 */;
	struct icmp6_filter cocci_id/* net/ipv6/raw.c 1002 */;
}
