cocci_test_suite() {
	struct inet6_skb_parm cocci_id/* net/ipv6/af_inet6.c 976 */;
	struct list_head *cocci_id/* net/ipv6/af_inet6.c 973 */;
	int __init cocci_id/* net/ipv6/af_inet6.c 971 */;
	const struct ipv6_bpf_stub cocci_id/* net/ipv6/af_inet6.c 966 */;
	const struct ipv6_stub cocci_id/* net/ipv6/af_inet6.c 946 */;
	struct pernet_operations cocci_id/* net/ipv6/af_inet6.c 935 */;
	void __net_exit cocci_id/* net/ipv6/af_inet6.c 925 */;
	int __net_init cocci_id/* net/ipv6/af_inet6.c 869 */;
	struct icmpv6msg_mib cocci_id/* net/ipv6/af_inet6.c 843 */;
	struct icmpv6_mib cocci_id/* net/ipv6/af_inet6.c 840 */;
	struct ipstats_mib *cocci_id/* net/ipv6/af_inet6.c 834 */;
	struct ipstats_mib cocci_id/* net/ipv6/af_inet6.c 829 */;
	struct udp_mib cocci_id/* net/ipv6/af_inet6.c 823 */;
	struct packet_type cocci_id/* net/ipv6/af_inet6.c 802 */;
	struct ipv6hdr *cocci_id/* net/ipv6/af_inet6.c 790 */;
	const struct ipv6_pinfo *cocci_id/* net/ipv6/af_inet6.c 785 */;
	const struct inet6_skb_parm *cocci_id/* net/ipv6/af_inet6.c 783 */;
	const struct sock *cocci_id/* net/ipv6/af_inet6.c 782 */;
	const struct sk_buff *cocci_id/* net/ipv6/af_inet6.c 782 */;
	struct ipv6_params cocci_id/* net/ipv6/af_inet6.c 78 */;
	struct list_head cocci_id/* net/ipv6/af_inet6.c 75 */[SOCK_MAX];
	struct flowi6 cocci_id/* net/ipv6/af_inet6.c 749 */;
	struct in6_addr *cocci_id/* net/ipv6/af_inet6.c 748 */;
	struct dst_entry *cocci_id/* net/ipv6/af_inet6.c 742 */;
	struct inet_protosw cocci_id/* net/ipv6/af_inet6.c 686 */;
	const struct net_proto_family cocci_id/* net/ipv6/af_inet6.c 661 */;
	const struct proto_ops cocci_id/* net/ipv6/af_inet6.c 634 */;
	struct msghdr *cocci_id/* net/ipv6/af_inet6.c 582 */;
	size_t cocci_id/* net/ipv6/af_inet6.c 582 */;
	 cocci_id/* net/ipv6/af_inet6.c 580 */(int udpv6_recvmsg(struct sock *, struct msghdr *, size_t, int, int, int *));
	 cocci_id/* net/ipv6/af_inet6.c 567 */(int udpv6_sendmsg(struct sock *, struct msghdr *, size_t));
	void __user *cocci_id/* net/ipv6/af_inet6.c 549 */;
	unsigned long cocci_id/* net/ipv6/af_inet6.c 540 */;
	unsigned int cocci_id/* net/ipv6/af_inet6.c 540 */;
	struct ipv6_txoptions **cocci_id/* net/ipv6/af_inet6.c 493 */;
	struct ipv6_txoptions *cocci_id/* net/ipv6/af_inet6.c 478 */;
	struct sk_buff *cocci_id/* net/ipv6/af_inet6.c 477 */;
	void cocci_id/* net/ipv6/af_inet6.c 474 */;
	struct socket *cocci_id/* net/ipv6/af_inet6.c 434 */;
	struct sockaddr_in6 cocci_id/* net/ipv6/af_inet6.c 349 */;
	struct net_device *cocci_id/* net/ipv6/af_inet6.c 310 */;
	unsigned short cocci_id/* net/ipv6/af_inet6.c 282 */;
	__be32 cocci_id/* net/ipv6/af_inet6.c 281 */;
	struct net *cocci_id/* net/ipv6/af_inet6.c 280 */;
	struct ipv6_pinfo *cocci_id/* net/ipv6/af_inet6.c 279 */;
	struct inet_sock *cocci_id/* net/ipv6/af_inet6.c 278 */;
	struct sockaddr_in6 *cocci_id/* net/ipv6/af_inet6.c 277 */;
	bool cocci_id/* net/ipv6/af_inet6.c 275 */;
	struct sockaddr *cocci_id/* net/ipv6/af_inet6.c 274 */;
	struct sock *cocci_id/* net/ipv6/af_inet6.c 274 */;
	int cocci_id/* net/ipv6/af_inet6.c 274 */;
	unsigned char cocci_id/* net/ipv6/af_inet6.c 115 */;
	struct proto *cocci_id/* net/ipv6/af_inet6.c 114 */;
	struct inet_protosw *cocci_id/* net/ipv6/af_inet6.c 113 */;
	u8 *cocci_id/* net/ipv6/af_inet6.c 104 */;
	const int cocci_id/* net/ipv6/af_inet6.c 102 */;
	struct ipv6_pinfo cocci_id/* net/ipv6/af_inet6.c 102 */;
}
