cocci_test_suite() {
	struct inet6_ifaddr *cocci_id/* net/ipv6/ndisc.c 962 */;
	struct ndisc_options cocci_id/* net/ipv6/ndisc.c 959 */;
	struct nd_msg cocci_id/* net/ipv6/ndisc.c 958 */;
	void cocci_id/* net/ipv6/ndisc.c 83 */(struct sk_buff *skb);
	void cocci_id/* net/ipv6/ndisc.c 82 */(struct pneigh_entry *n);
	int cocci_id/* net/ipv6/ndisc.c 81 */(struct pneigh_entry *n);
	void cocci_id/* net/ipv6/ndisc.c 80 */(struct neighbour *neigh,
					       struct sk_buff *skb);
	u64 cocci_id/* net/ipv6/ndisc.c 783 */;
	int cocci_id/* net/ipv6/ndisc.c 78 */(struct neighbour *neigh);
	bool cocci_id/* net/ipv6/ndisc.c 76 */(const struct net_device *dev,
					       struct netlink_ext_ack *extack);
	bool cocci_id/* net/ipv6/ndisc.c 75 */(const struct neighbour *neigh,
					       const void *pkey);
	u32 cocci_id/* net/ipv6/ndisc.c 72 */(const void *pkey,
					      const struct net_device *dev,
					      __u32 *hash_rnd);
	struct rs_msg cocci_id/* net/ipv6/ndisc.c 688 */;
	unsigned cocci_id/* net/ipv6/ndisc.c 445 */;
	struct inet6_dev *cocci_id/* net/ipv6/ndisc.c 444 */;
	struct ipv6hdr *cocci_id/* net/ipv6/ndisc.c 443 */;
	const struct in6_addr *cocci_id/* net/ipv6/ndisc.c 439 */;
	struct ipv6hdr cocci_id/* net/ipv6/ndisc.c 417 */;
	struct sock *cocci_id/* net/ipv6/ndisc.c 414 */;
	struct net_device *cocci_id/* net/ipv6/ndisc.c 409 */;
	struct netlink_ext_ack *cocci_id/* net/ipv6/ndisc.c 397 */;
	bool cocci_id/* net/ipv6/ndisc.c 396 */;
	const struct net_device *cocci_id/* net/ipv6/ndisc.c 396 */;
	struct pneigh_entry *cocci_id/* net/ipv6/ndisc.c 370 */;
	struct neigh_parms *cocci_id/* net/ipv6/ndisc.c 327 */;
	struct in6_addr *cocci_id/* net/ipv6/ndisc.c 324 */;
	struct neighbour *cocci_id/* net/ipv6/ndisc.c 322 */;
	const struct neighbour *cocci_id/* net/ipv6/ndisc.c 317 */;
	__u32 *cocci_id/* net/ipv6/ndisc.c 312 */;
	u32 cocci_id/* net/ipv6/ndisc.c 310 */;
	const void *cocci_id/* net/ipv6/ndisc.c 310 */;
	char *cocci_id/* net/ipv6/ndisc.c 284 */;
	struct nd_opt_hdr cocci_id/* net/ipv6/ndisc.c 226 */;
	struct ndisc_options *cocci_id/* net/ipv6/ndisc.c 215 */;
	struct nd_opt_hdr *cocci_id/* net/ipv6/ndisc.c 195 */;
	int __init cocci_id/* net/ipv6/ndisc.c 1910 */;
	struct pernet_operations cocci_id/* net/ipv6/ndisc.c 1905 */;
	struct net *cocci_id/* net/ipv6/ndisc.c 1900 */;
	void __net_exit cocci_id/* net/ipv6/ndisc.c 1900 */;
	struct ipv6_pinfo *cocci_id/* net/ipv6/ndisc.c 1877 */;
	int __net_init cocci_id/* net/ipv6/ndisc.c 1875 */;
	loff_t *cocci_id/* net/ipv6/ndisc.c 1837 */;
	struct ctl_table *cocci_id/* net/ipv6/ndisc.c 1837 */;
	size_t *cocci_id/* net/ipv6/ndisc.c 1837 */;
	void __user *cocci_id/* net/ipv6/ndisc.c 1837 */;
	char cocci_id/* net/ipv6/ndisc.c 1825 */[TASK_COMM_LEN];
	const char *cocci_id/* net/ipv6/ndisc.c 1823 */;
	struct notifier_block cocci_id/* net/ipv6/ndisc.c 1816 */;
	struct netdev_notifier_change_info *cocci_id/* net/ipv6/ndisc.c 1777 */;
	struct notifier_block *cocci_id/* net/ipv6/ndisc.c 1774 */;
	unsigned long cocci_id/* net/ipv6/ndisc.c 1774 */;
	struct neighbour_cb cocci_id/* net/ipv6/ndisc.c 1750 */;
	const u8 *cocci_id/* net/ipv6/ndisc.c 175 */;
	struct nd_msg *cocci_id/* net/ipv6/ndisc.c 1724 */;
	u8 cocci_id/* net/ipv6/ndisc.c 166 */;
	u8 cocci_id/* net/ipv6/ndisc.c 1590 */[MAX_ADDR_LEN];
	struct flowi6 cocci_id/* net/ipv6/ndisc.c 1588 */;
	struct dst_entry *cocci_id/* net/ipv6/ndisc.c 1587 */;
	struct rt6_info *cocci_id/* net/ipv6/ndisc.c 1586 */;
	struct inet_peer *cocci_id/* net/ipv6/ndisc.c 1582 */;
	struct rd_msg cocci_id/* net/ipv6/ndisc.c 1526 */;
	struct rd_msg *cocci_id/* net/ipv6/ndisc.c 1524 */;
	__be32 cocci_id/* net/ipv6/ndisc.c 1486 */;
	u8 *cocci_id/* net/ipv6/ndisc.c 147 */;
	struct route_info *cocci_id/* net/ipv6/ndisc.c 1443 */;
	struct sk_buff *cocci_id/* net/ipv6/ndisc.c 143 */;
	void *cocci_id/* net/ipv6/ndisc.c 143 */;
	int cocci_id/* net/ipv6/ndisc.c 143 */;
	void cocci_id/* net/ipv6/ndisc.c 143 */;
	struct ra_msg cocci_id/* net/ipv6/ndisc.c 1184 */;
	__u8 *cocci_id/* net/ipv6/ndisc.c 1181 */;
	__u32 cocci_id/* net/ipv6/ndisc.c 1178 */;
	unsigned int cocci_id/* net/ipv6/ndisc.c 1177 */;
	struct fib6_info *cocci_id/* net/ipv6/ndisc.c 1172 */;
	struct ra_msg *cocci_id/* net/ipv6/ndisc.c 1169 */;
	size_t cocci_id/* net/ipv6/ndisc.c 1131 */;
	struct nduseroptmsg cocci_id/* net/ipv6/ndisc.c 1129 */;
	struct nduseroptmsg *cocci_id/* net/ipv6/ndisc.c 1126 */;
	struct nlmsghdr *cocci_id/* net/ipv6/ndisc.c 1125 */;
	struct icmp6hdr *cocci_id/* net/ipv6/ndisc.c 1123 */;
	struct in6_addr cocci_id/* net/ipv6/ndisc.c 110 */;
	struct neigh_table cocci_id/* net/ipv6/ndisc.c 108 */;
	struct rs_msg *cocci_id/* net/ipv6/ndisc.c 1067 */;
	const struct neigh_ops cocci_id/* net/ipv6/ndisc.c 102 */;
}
