cocci_test_suite() {
	struct ifinfomsg cocci_id/* net/bridge/br_netlink.c 921 */;
	bool cocci_id/* net/bridge/br_netlink.c 918 */;
	struct nlmsghdr *cocci_id/* net/bridge/br_netlink.c 913 */;
	size_t cocci_id/* net/bridge/br_netlink.c 91 */;
	struct nlattr *cocci_id/* net/bridge/br_netlink.c 858 */[IFLA_BRPORT_MAX + 1];
	unsigned long cocci_id/* net/bridge/br_netlink.c 704 */;
	const struct nla_policy cocci_id/* net/bridge/br_netlink.c 657 */[IFLA_BRPORT_MAX + 1];
	struct bridge_vlan_info cocci_id/* net/bridge/br_netlink.c 642 */;
	struct vtunnel_info cocci_id/* net/bridge/br_netlink.c 621 */;
	struct bridge_vlan_info *cocci_id/* net/bridge/br_netlink.c 618 */;
	struct netlink_ext_ack *cocci_id/* net/bridge/br_netlink.c 616 */;
	bool *cocci_id/* net/bridge/br_netlink.c 615 */;
	struct nlattr *cocci_id/* net/bridge/br_netlink.c 614 */;
	struct net_bridge_port *cocci_id/* net/bridge/br_netlink.c 613 */;
	struct net_bridge *cocci_id/* net/bridge/br_netlink.c 612 */;
	struct bridge_vlan_info **cocci_id/* net/bridge/br_netlink.c 567 */;
	const struct net_bridge *cocci_id/* net/bridge/br_netlink.c 466 */;
	void cocci_id/* net/bridge/br_netlink.c 466 */;
	struct ifinfomsg *cocci_id/* net/bridge/br_netlink.c 378 */;
	const struct net_device *cocci_id/* net/bridge/br_netlink.c 374 */;
	unsigned int cocci_id/* net/bridge/br_netlink.c 373 */;
	const struct net_bridge_port *cocci_id/* net/bridge/br_netlink.c 372 */;
	struct sk_buff *cocci_id/* net/bridge/br_netlink.c 371 */;
	u16 cocci_id/* net/bridge/br_netlink.c 25 */;
	struct net_bridge_vlan *cocci_id/* net/bridge/br_netlink.c 24 */;
	u32 cocci_id/* net/bridge/br_netlink.c 22 */;
	struct net_bridge_vlan_group *cocci_id/* net/bridge/br_netlink.c 21 */;
	int cocci_id/* net/bridge/br_netlink.c 21 */;
	int __init cocci_id/* net/bridge/br_netlink.c 1649 */;
	struct net_bridge cocci_id/* net/bridge/br_netlink.c 1629 */;
	struct rtnl_link_ops cocci_id/* net/bridge/br_netlink.c 1627 */;
	struct rtnl_af_ops cocci_id/* net/bridge/br_netlink.c 1622 */;
	struct br_mcast_stats cocci_id/* net/bridge/br_netlink.c 1603 */;
	struct br_vlan_stats cocci_id/* net/bridge/br_netlink.c 1580 */;
	struct bridge_vlan_xstats cocci_id/* net/bridge/br_netlink.c 1579 */;
	int *cocci_id/* net/bridge/br_netlink.c 1544 */;
	struct ifla_bridge_id cocci_id/* net/bridge/br_netlink.c 1423 */;
	struct br_boolopt_multi cocci_id/* net/bridge/br_netlink.c 1397 */;
	struct net *cocci_id/* net/bridge/br_netlink.c 1308 */;
	struct br_boolopt_multi *cocci_id/* net/bridge/br_netlink.c 1297 */;
	u64 cocci_id/* net/bridge/br_netlink.c 1214 */;
	u8 cocci_id/* net/bridge/br_netlink.c 1143 */[ETH_ALEN];
	__u8 cocci_id/* net/bridge/br_netlink.c 1118 */;
	__u16 cocci_id/* net/bridge/br_netlink.c 1110 */;
	__be16 cocci_id/* net/bridge/br_netlink.c 1102 */;
	u8 cocci_id/* net/bridge/br_netlink.c 1093 */;
	struct nlattr *cocci_id/* net/bridge/br_netlink.c 1046 */[];
	struct net_device *cocci_id/* net/bridge/br_netlink.c 1046 */;
	const struct nla_policy cocci_id/* net/bridge/br_netlink.c 1007 */[IFLA_BR_MAX + 1];
}
