cocci_test_suite() {
	struct tcphdr cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 71 */;
	const struct tcphdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 70 */;
	const struct net_device *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 65 */;
	struct net *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 63 */;
	void __exit cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 441 */;
	int __init cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 436 */;
	struct nft_reject cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 420 */;
	const struct nft_expr_ops cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 418 */;
	struct nft_expr_type cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 417 */;
	struct iphdr cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 41 */;
	const struct nft_reject *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 396 */;
	const struct nft_expr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 394 */;
	struct iphdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 38 */;
	const struct nlattr *const cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 363 */[];
	const struct nft_ctx *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 361 */;
	const struct nft_data **cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 355 */;
	const unsigned char *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 296 */;
	struct nft_reject *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 295 */;
	const struct nft_pktinfo *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 293 */;
	struct nft_regs *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 292 */;
	struct icmp6hdr cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 261 */;
	struct ethhdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 26 */;
	struct icmp6hdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 244 */;
	void cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 23 */;
	u8 *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 227 */;
	__be16 cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 216 */;
	const struct ipv6hdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 214 */;
	bool cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 212 */;
	struct ipv6hdr cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 164 */;
	u32 cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 162 */;
	struct ipv6hdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 161 */;
	struct sk_buff *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 159 */;
	int cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 159 */;
	void *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 148 */;
	struct icmphdr cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 132 */;
	__wsum cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 106 */;
	unsigned int cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 105 */;
	struct icmphdr *cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 104 */;
	u8 cocci_id/* net/bridge/netfilter/nft_reject_bridge.c 100 */;
}
