cocci_test_suite() {
	struct rxrpc_call cocci_id/* net/rxrpc/af_rxrpc.c 985 */;
	struct sk_buff cocci_id/* net/rxrpc/af_rxrpc.c 975 */;
	struct rxrpc_skb_priv cocci_id/* net/rxrpc/af_rxrpc.c 975 */;
	unsigned int cocci_id/* net/rxrpc/af_rxrpc.c 973 */;
	int cocci_id/* net/rxrpc/af_rxrpc.c 972 */;
	int __init cocci_id/* net/rxrpc/af_rxrpc.c 970 */;
	const struct net_proto_family cocci_id/* net/rxrpc/af_rxrpc.c 961 */;
	struct rxrpc_wire_header cocci_id/* net/rxrpc/af_rxrpc.c 958 */;
	struct rxrpc_sock cocci_id/* net/rxrpc/af_rxrpc.c 957 */;
	struct sockaddr_rxrpc cocci_id/* net/rxrpc/af_rxrpc.c 82 */;
	struct sock *cocci_id/* net/rxrpc/af_rxrpc.c 762 */;
	struct rxrpc_net *cocci_id/* net/rxrpc/af_rxrpc.c 760 */;
	struct net *cocci_id/* net/rxrpc/af_rxrpc.c 757 */;
	poll_table *cocci_id/* net/rxrpc/af_rxrpc.c 731 */;
	__poll_t cocci_id/* net/rxrpc/af_rxrpc.c 730 */;
	struct file *cocci_id/* net/rxrpc/af_rxrpc.c 730 */;
	int __user *cocci_id/* net/rxrpc/af_rxrpc.c 703 */;
	char __user *cocci_id/* net/rxrpc/af_rxrpc.c 703 */;
	unsigned int __user *cocci_id/* net/rxrpc/af_rxrpc.c 656 */;
	struct socket_wq *cocci_id/* net/rxrpc/af_rxrpc.c 64 */;
	u16 cocci_id/* net/rxrpc/af_rxrpc.c 608 */[2];
	struct sockaddr_in6 cocci_id/* net/rxrpc/af_rxrpc.c 559 */;
	struct sockaddr_in cocci_id/* net/rxrpc/af_rxrpc.c 555 */;
	struct msghdr *cocci_id/* net/rxrpc/af_rxrpc.c 525 */;
	size_t cocci_id/* net/rxrpc/af_rxrpc.c 525 */;
	void cocci_id/* net/rxrpc/af_rxrpc.c 46 */(struct sock *);
	struct workqueue_struct *cocci_id/* net/rxrpc/af_rxrpc.c 44 */;
	rxrpc_discard_new_call_t cocci_id/* net/rxrpc/af_rxrpc.c 436 */;
	rxrpc_notify_new_call_t cocci_id/* net/rxrpc/af_rxrpc.c 435 */;
	u32 cocci_id/* net/rxrpc/af_rxrpc.c 419 */;
	u32 *cocci_id/* net/rxrpc/af_rxrpc.c 385 */;
	const struct rxrpc_call *cocci_id/* net/rxrpc/af_rxrpc.c 384 */;
	const struct socket *cocci_id/* net/rxrpc/af_rxrpc.c 383 */;
	atomic_t cocci_id/* net/rxrpc/af_rxrpc.c 38 */;
	const struct proto_ops cocci_id/* net/rxrpc/af_rxrpc.c 35 */;
	struct proto cocci_id/* net/rxrpc/af_rxrpc.c 34 */;
	unsigned long cocci_id/* net/rxrpc/af_rxrpc.c 338 */;
	struct rxrpc_call *cocci_id/* net/rxrpc/af_rxrpc.c 337 */;
	struct rxrpc_call_params cocci_id/* net/rxrpc/af_rxrpc.c 291 */;
	struct rxrpc_conn_parameters cocci_id/* net/rxrpc/af_rxrpc.c 290 */;
	bool cocci_id/* net/rxrpc/af_rxrpc.c 286 */;
	rxrpc_notify_rx_t cocci_id/* net/rxrpc/af_rxrpc.c 285 */;
	gfp_t cocci_id/* net/rxrpc/af_rxrpc.c 284 */;
	s64 cocci_id/* net/rxrpc/af_rxrpc.c 283 */;
	struct key *cocci_id/* net/rxrpc/af_rxrpc.c 281 */;
	u16 cocci_id/* net/rxrpc/af_rxrpc.c 134 */;
	struct rxrpc_sock *cocci_id/* net/rxrpc/af_rxrpc.c 133 */;
	struct rxrpc_local *cocci_id/* net/rxrpc/af_rxrpc.c 132 */;
	struct sockaddr_rxrpc *cocci_id/* net/rxrpc/af_rxrpc.c 131 */;
	struct socket *cocci_id/* net/rxrpc/af_rxrpc.c 129 */;
	struct sockaddr *cocci_id/* net/rxrpc/af_rxrpc.c 129 */;
	void *cocci_id/* net/rxrpc/af_rxrpc.c 121 */;
	void __exit cocci_id/* net/rxrpc/af_rxrpc.c 1063 */;
	void cocci_id/* net/rxrpc/af_rxrpc.c 1063 */;
}
