cocci_test_suite() {
	struct smc_wr_buf *cocci_id/* net/smc/smc_cdc.c 91 */;
	struct smc_cdc_tx_pend cocci_id/* net/smc/smc_cdc.c 82 */;
	struct smc_cdc_msg cocci_id/* net/smc/smc_cdc.c 76 */;
	struct smc_cdc_tx_pend *cocci_id/* net/smc/smc_cdc.c 73 */;
	struct smc_connection *cocci_id/* net/smc/smc_cdc.c 72 */;
	void cocci_id/* net/smc/smc_cdc.c 72 */;
	struct smc_wr_tx_pend_priv **cocci_id/* net/smc/smc_cdc.c 65 */;
	struct smc_link *cocci_id/* net/smc/smc_cdc.c 60 */;
	struct smc_cdc_tx_pend **cocci_id/* net/smc/smc_cdc.c 58 */;
	struct smc_rdma_wr **cocci_id/* net/smc/smc_cdc.c 57 */;
	struct smc_wr_buf **cocci_id/* net/smc/smc_cdc.c 56 */;
	int cocci_id/* net/smc/smc_cdc.c 55 */;
	struct smc_wr_rx_handler *cocci_id/* net/smc/smc_cdc.c 397 */;
	int __init cocci_id/* net/smc/smc_cdc.c 395 */;
	struct smc_wr_rx_handler cocci_id/* net/smc/smc_cdc.c 385 */[];
	struct smc_sock cocci_id/* net/smc/smc_cdc.c 374 */;
	struct smc_link_group *cocci_id/* net/smc/smc_cdc.c 359 */;
	struct ib_wc *cocci_id/* net/smc/smc_cdc.c 354 */;
	void *cocci_id/* net/smc/smc_cdc.c 354 */;
	struct smcd_cdc_msg *cocci_id/* net/smc/smc_cdc.c 330 */;
	struct smc_cdc_msg *cocci_id/* net/smc/smc_cdc.c 312 */;
	enum ib_wc_status cocci_id/* net/smc/smc_cdc.c 27 */;
	union smc_host_cursor cocci_id/* net/smc/smc_cdc.c 245 */;
	char *cocci_id/* net/smc/smc_cdc.c 226 */;
	int *cocci_id/* net/smc/smc_cdc.c 223 */;
	struct smc_sock *cocci_id/* net/smc/smc_cdc.c 222 */;
	u16 cocci_id/* net/smc/smc_cdc.c 217 */;
	bool cocci_id/* net/smc/smc_cdc.c 217 */;
	struct smcd_cdc_msg cocci_id/* net/smc/smc_cdc.c 183 */;
	unsigned long cocci_id/* net/smc/smc_cdc.c 172 */;
	struct smc_wr_tx_pend_priv *cocci_id/* net/smc/smc_cdc.c 105 */;
}
