cocci_test_suite() {
	char *cocci_id/* net/bluetooth/sco.c 954 */;
	unsigned int cocci_id/* net/bluetooth/sco.c 953 */;
	u32 __user *cocci_id/* net/bluetooth/sco.c 945 */;
	struct bt_voice cocci_id/* net/bluetooth/sco.c 924 */;
	int __user *cocci_id/* net/bluetooth/sco.c 920 */;
	char __user *cocci_id/* net/bluetooth/sco.c 920 */;
	struct sco_conninfo cocci_id/* net/bluetooth/sco.c 863 */;
	struct sco_options cocci_id/* net/bluetooth/sco.c 862 */;
	u32 cocci_id/* net/bluetooth/sco.c 799 */;
	struct sco_pinfo *cocci_id/* net/bluetooth/sco.c 775 */;
	size_t cocci_id/* net/bluetooth/sco.c 772 */;
	struct timer_list *cocci_id/* net/bluetooth/sco.c 76 */;
	struct hci_cp_accept_sync_conn_req cocci_id/* net/bluetooth/sco.c 743 */;
	struct hci_cp_accept_conn_req cocci_id/* net/bluetooth/sco.c 736 */;
	u16 cocci_id/* net/bluetooth/sco.c 727 */;
	long cocci_id/* net/bluetooth/sco.c 633 */;
	struct sco_pinfo {
		struct bt_sock bt;
		bdaddr_t src;
		bdaddr_t dst;
		__u32 flags;
		__u16 setting;
		struct sco_conn *conn;
	} cocci_id/* net/bluetooth/sco.c 63 */;
	struct socket *cocci_id/* net/bluetooth/sco.c 628 */;
	void cocci_id/* net/bluetooth/sco.c 57 */(struct sock *sk);
	struct sockaddr_sco *cocci_id/* net/bluetooth/sco.c 522 */;
	struct sockaddr *cocci_id/* net/bluetooth/sco.c 519 */;
	gfp_t cocci_id/* net/bluetooth/sco.c 470 */;
	struct net *cocci_id/* net/bluetooth/sco.c 469 */;
	struct sco_pinfo cocci_id/* net/bluetooth/sco.c 466 */;
	struct proto cocci_id/* net/bluetooth/sco.c 463 */;
	struct sco_conn {
		struct hci_conn *hcon;
		spinlock_t lock;
		struct sock *sk;
		unsigned int mtu;
	} cocci_id/* net/bluetooth/sco.c 45 */;
	struct bt_sock_list cocci_id/* net/bluetooth/sco.c 40 */;
	const struct proto_ops cocci_id/* net/bluetooth/sco.c 38 */;
	bool cocci_id/* net/bluetooth/sco.c 36 */;
	bdaddr_t *cocci_id/* net/bluetooth/sco.c 325 */;
	struct sk_buff *cocci_id/* net/bluetooth/sco.c 301 */;
	struct msghdr *cocci_id/* net/bluetooth/sco.c 275 */;
	int cocci_id/* net/bluetooth/sco.c 199 */;
	struct sock *cocci_id/* net/bluetooth/sco.c 187 */;
	struct sco_conn *cocci_id/* net/bluetooth/sco.c 187 */;
	void cocci_id/* net/bluetooth/sco.c 187 */;
	struct sockaddr_sco cocci_id/* net/bluetooth/sco.c 1211 */;
	struct sockaddr cocci_id/* net/bluetooth/sco.c 1211 */;
	int __init cocci_id/* net/bluetooth/sco.c 1207 */;
	const struct net_proto_family cocci_id/* net/bluetooth/sco.c 1201 */;
	struct dentry *cocci_id/* net/bluetooth/sco.c 1178 */;
	struct seq_file *cocci_id/* net/bluetooth/sco.c 1160 */;
	void *cocci_id/* net/bluetooth/sco.c 1160 */;
	struct hci_cb cocci_id/* net/bluetooth/sco.c 1154 */;
	struct sco_conn cocci_id/* net/bluetooth/sco.c 112 */;
	__u8 cocci_id/* net/bluetooth/sco.c 1109 */;
	__u8 *cocci_id/* net/bluetooth/sco.c 1082 */;
	struct hci_dev *cocci_id/* net/bluetooth/sco.c 106 */;
	struct hci_conn *cocci_id/* net/bluetooth/sco.c 104 */;
}
