cocci_test_suite() {
	uint32_t cocci_id/* net/bluetooth/hci_request.c 991 */;
	hci_req_complete_skb_t cocci_id/* net/bluetooth/hci_request.c 97 */;
	struct hci_cp_le_set_ext_adv_enable cocci_id/* net/bluetooth/hci_request.c 943 */;
	hci_req_complete_t cocci_id/* net/bluetooth/hci_request.c 92 */;
	struct hci_cp_le_set_scan_param cocci_id/* net/bluetooth/hci_request.c 844 */;
	u8 cocci_id/* net/bluetooth/hci_request.c 798 */[sizeof(*ext_param_cp) + sizeof(*phy_params) * 2];
	struct hci_cp_le_scan_phy_params *cocci_id/* net/bluetooth/hci_request.c 797 */;
	struct hci_cp_le_set_ext_scan_params *cocci_id/* net/bluetooth/hci_request.c 795 */;
	struct hci_cp_le_del_from_white_list cocci_id/* net/bluetooth/hci_request.c 705 */;
	uint8_t cocci_id/* net/bluetooth/hci_request.c 689 */;
	struct hci_cp_le_add_to_white_list cocci_id/* net/bluetooth/hci_request.c 676 */;
	struct hci_conn_params *cocci_id/* net/bluetooth/hci_request.c 674 */;
	struct hci_cp_le_set_scan_enable cocci_id/* net/bluetooth/hci_request.c 665 */;
	struct hci_cp_le_set_ext_scan_enable cocci_id/* net/bluetooth/hci_request.c 658 */;
	struct hci_cp_write_eir cocci_id/* net/bluetooth/hci_request.c 627 */;
	struct bt_uuid *cocci_id/* net/bluetooth/hci_request.c 546 */;
	ptrdiff_t cocci_id/* net/bluetooth/hci_request.c 543 */;
	struct hci_cp_write_local_name cocci_id/* net/bluetooth/hci_request.c 459 */;
	struct hci_cp_write_page_scan_activity cocci_id/* net/bluetooth/hci_request.c 351 */;
	struct hci_command_hdr *cocci_id/* net/bluetooth/hci_request.c 289 */;
	struct adv_info cocci_id/* net/bluetooth/hci_request.c 2803 */;
	struct hci_cp_write_le_host_supported cocci_id/* net/bluetooth/hci_request.c 2757 */;
	struct inquiry_entry *cocci_id/* net/bluetooth/hci_request.c 2632 */;
	struct hci_cp_remote_name_req_cancel cocci_id/* net/bluetooth/hci_request.c 2631 */;
	struct discovery_state *cocci_id/* net/bluetooth/hci_request.c 2630 */;
	uint16_t cocci_id/* net/bluetooth/hci_request.c 2500 */;
	struct hci_cp_inquiry cocci_id/* net/bluetooth/hci_request.c 2336 */;
	struct hci_cp_reject_sync_conn_req cocci_id/* net/bluetooth/hci_request.c 2250 */;
	struct hci_cp_reject_conn_req cocci_id/* net/bluetooth/hci_request.c 2242 */;
	struct hci_cp_disconnect cocci_id/* net/bluetooth/hci_request.c 2217 */;
	struct hci_cp_disconn_phy_link cocci_id/* net/bluetooth/hci_request.c 2210 */;
	u8 cocci_id/* net/bluetooth/hci_request.c 2204 */;
	struct hci_request *cocci_id/* net/bluetooth/hci_request.c 2203 */;
	struct hci_conn *cocci_id/* net/bluetooth/hci_request.c 2203 */;
	void cocci_id/* net/bluetooth/hci_request.c 2203 */;
	struct hci_cp_write_current_iac_lap cocci_id/* net/bluetooth/hci_request.c 2133 */;
	u8 cocci_id/* net/bluetooth/hci_request.c 2104 */[3];
	struct bdaddr_list *cocci_id/* net/bluetooth/hci_request.c 1988 */;
	u8 *cocci_id/* net/bluetooth/hci_request.c 194 */;
	unsigned long cocci_id/* net/bluetooth/hci_request.c 194 */;
	int (*cocci_id/* net/bluetooth/hci_request.c 192 */)(struct hci_request *req,
							     unsigned long opt);
	const void *cocci_id/* net/bluetooth/hci_request.c 185 */;
	u32 cocci_id/* net/bluetooth/hci_request.c 184 */;
	u16 cocci_id/* net/bluetooth/hci_request.c 184 */;
	struct sk_buff *cocci_id/* net/bluetooth/hci_request.c 184 */;
	struct hci_dev *cocci_id/* net/bluetooth/hci_request.c 184 */;
	struct sock *cocci_id/* net/bluetooth/hci_request.c 1819 */;
	void *cocci_id/* net/bluetooth/hci_request.c 1686 */;
	struct adv_info *cocci_id/* net/bluetooth/hci_request.c 1676 */;
	u8 cocci_id/* net/bluetooth/hci_request.c 1675 */[sizeof(*cp) + sizeof(*adv_set) * 1];
	struct hci_cp_ext_adv_set *cocci_id/* net/bluetooth/hci_request.c 1674 */;
	struct hci_cp_le_set_ext_adv_enable *cocci_id/* net/bluetooth/hci_request.c 1673 */;
	struct hci_cp_le_set_adv_set_rand_addr cocci_id/* net/bluetooth/hci_request.c 1646 */;
	const u8 cocci_id/* net/bluetooth/hci_request.c 1570 */[3];
	bdaddr_t cocci_id/* net/bluetooth/hci_request.c 1564 */;
	struct hci_cp_le_set_ext_adv_params cocci_id/* net/bluetooth/hci_request.c 1560 */;
	bdaddr_t *cocci_id/* net/bluetooth/hci_request.c 1474 */;
	struct hci_dev cocci_id/* net/bluetooth/hci_request.c 1443 */;
	struct work_struct *cocci_id/* net/bluetooth/hci_request.c 1441 */;
	struct hci_cp_le_set_adv_data cocci_id/* net/bluetooth/hci_request.c 1380 */;
	struct hci_cp_le_set_ext_adv_data cocci_id/* net/bluetooth/hci_request.c 1359 */;
	s8 cocci_id/* net/bluetooth/hci_request.c 1325 */;
	int cocci_id/* net/bluetooth/hci_request.c 132 */;
	struct hci_request cocci_id/* net/bluetooth/hci_request.c 130 */;
	struct hci_cp_le_set_scan_rsp_data cocci_id/* net/bluetooth/hci_request.c 1238 */;
	struct hci_cp_le_set_ext_scan_rsp_data cocci_id/* net/bluetooth/hci_request.c 1213 */;
	u8 cocci_id/* net/bluetooth/hci_request.c 1148 */[HCI_MAX_SHORT_NAME_LENGTH + 1];
	size_t cocci_id/* net/bluetooth/hci_request.c 1125 */;
	bool cocci_id/* net/bluetooth/hci_request.c 1056 */;
	struct hci_cp_le_set_adv_param cocci_id/* net/bluetooth/hci_request.c 1054 */;
}
