cocci_test_suite() {
	struct tegra_dma_channel_regs *cocci_id/* drivers/dma/tegra20-apb-dma.c 994 */;
	enum dma_slave_buswidth *cocci_id/* drivers/dma/tegra20-apb-dma.c 967 */;
	unsigned int *cocci_id/* drivers/dma/tegra20-apb-dma.c 966 */;
	enum dma_transfer_direction cocci_id/* drivers/dma/tegra20-apb-dma.c 965 */;
	unsigned long *cocci_id/* drivers/dma/tegra20-apb-dma.c 965 */;
	u32 cocci_id/* drivers/dma/tegra20-apb-dma.c 935 */;
	enum dma_slave_buswidth cocci_id/* drivers/dma/tegra20-apb-dma.c 935 */;
	struct tegra_dma_channel *cocci_id/* drivers/dma/tegra20-apb-dma.c 934 */;
	int cocci_id/* drivers/dma/tegra20-apb-dma.c 934 */;
	dma_cookie_t cocci_id/* drivers/dma/tegra20-apb-dma.c 865 */;
	struct dma_tx_state *cocci_id/* drivers/dma/tegra20-apb-dma.c 865 */;
	enum dma_status cocci_id/* drivers/dma/tegra20-apb-dma.c 864 */;
	irqreturn_t cocci_id/* drivers/dma/tegra20-apb-dma.c 682 */;
	void *cocci_id/* drivers/dma/tegra20-apb-dma.c 682 */;
	struct dmaengine_desc_callback cocci_id/* drivers/dma/tegra20-apb-dma.c 659 */;
	typeof(*sgreq) cocci_id/* drivers/dma/tegra20-apb-dma.c 632 */;
	struct tegra_dma_desc *cocci_id/* drivers/dma/tegra20-apb-dma.c 629 */;
	bool cocci_id/* drivers/dma/tegra20-apb-dma.c 626 */;
	void cocci_id/* drivers/dma/tegra20-apb-dma.c 625 */;
	typeof(*hsgreq) cocci_id/* drivers/dma/tegra20-apb-dma.c 582 */;
	struct tegra_dma_sg_req *cocci_id/* drivers/dma/tegra20-apb-dma.c 537 */;
	unsigned long cocci_id/* drivers/dma/tegra20-apb-dma.c 537 */;
	typeof(*hnsgreq) cocci_id/* drivers/dma/tegra20-apb-dma.c 531 */;
	typeof(*sg_req) cocci_id/* drivers/dma/tegra20-apb-dma.c 513 */;
	struct dma_slave_config *cocci_id/* drivers/dma/tegra20-apb-dma.c 339 */;
	struct tegra_dma_sg_req cocci_id/* drivers/dma/tegra20-apb-dma.c 333 */;
	int cocci_id/* drivers/dma/tegra20-apb-dma.c 271 */(struct device *dev);
	dma_cookie_t cocci_id/* drivers/dma/tegra20-apb-dma.c 269 */(struct dma_async_tx_descriptor *tx);
	struct device *cocci_id/* drivers/dma/tegra20-apb-dma.c 264 */;
	struct tegra_dma_desc cocci_id/* drivers/dma/tegra20-apb-dma.c 261 */;
	struct tegra_dma *cocci_id/* drivers/dma/tegra20-apb-dma.c 237 */;
	struct tegra_dma {
		struct dma_device dma_dev;
		struct device *dev;
		struct clk *dma_clk;
		struct reset_control *rst;
		spinlock_t global_lock;
		void __iomem *base_addr;
		const struct tegra_dma_chip_data *chip_data;
		u32 global_pause_count;
		u32 reg_gen;
		struct tegra_dma_channel channels[0];
	} cocci_id/* drivers/dma/tegra20-apb-dma.c 209 */;
	struct tegra_dma_channel {
		struct dma_chan dma_chan;
		char name[12];
		bool config_init;
		int id;
		int irq;
		void __iomem *chan_addr;
		spinlock_t lock;
		bool busy;
		struct tegra_dma *tdma;
		bool cyclic;
		struct list_head free_sg_req;
		struct list_head pending_sg_req;
		struct list_head free_dma_desc;
		struct list_head cb_desc;
		dma_isr_handler isr_handler;
		struct tasklet_struct tasklet;
		unsigned int slave_id;
		struct dma_slave_config dma_sconfig;
		struct tegra_dma_channel_regs channel_reg;
	} cocci_id/* drivers/dma/tegra20-apb-dma.c 180 */;
	void (*cocci_id/* drivers/dma/tegra20-apb-dma.c 176 */)(struct tegra_dma_channel *tdc,
								bool to_terminate);
	struct tegra_dma_channel cocci_id/* drivers/dma/tegra20-apb-dma.c 174 */;
	struct platform_driver cocci_id/* drivers/dma/tegra20-apb-dma.c 1663 */;
	const struct of_device_id cocci_id/* drivers/dma/tegra20-apb-dma.c 1645 */[];
	struct tegra_dma_desc {
		struct dma_async_tx_descriptor txd;
		unsigned int bytes_requested;
		unsigned int bytes_transferred;
		enum dma_status dma_status;
		struct list_head node;
		struct list_head tx_list;
		struct list_head cb_node;
		int cb_count;
	} cocci_id/* drivers/dma/tegra20-apb-dma.c 163 */;
	struct tegra_dma_sg_req {
		struct tegra_dma_channel_regs ch_regs;
		unsigned int req_len;
		bool configured;
		bool last_sg;
		struct list_head node;
		struct tegra_dma_desc *dma_desc;
		unsigned int words_xferred;
	} cocci_id/* drivers/dma/tegra20-apb-dma.c 148 */;
	const struct tegra_dma_chip_data *cocci_id/* drivers/dma/tegra20-apb-dma.c 1387 */;
	struct resource *cocci_id/* drivers/dma/tegra20-apb-dma.c 1383 */;
	struct platform_device *cocci_id/* drivers/dma/tegra20-apb-dma.c 1381 */;
	const struct tegra_dma_chip_data cocci_id/* drivers/dma/tegra20-apb-dma.c 1364 */;
	struct of_dma *cocci_id/* drivers/dma/tegra20-apb-dma.c 1324 */;
	struct of_phandle_args *cocci_id/* drivers/dma/tegra20-apb-dma.c 1323 */;
	struct tegra_dma_channel_regs {
		unsigned long csr;
		unsigned long ahb_ptr;
		unsigned long apb_ptr;
		unsigned long ahb_seq;
		unsigned long apb_seq;
		unsigned long wcount;
	} cocci_id/* drivers/dma/tegra20-apb-dma.c 131 */;
	typeof(*dma_desc) cocci_id/* drivers/dma/tegra20-apb-dma.c 1308 */;
	struct list_head cocci_id/* drivers/dma/tegra20-apb-dma.c 1285 */;
	struct dma_chan *cocci_id/* drivers/dma/tegra20-apb-dma.c 1263 */;
	struct tegra_dma_chip_data {
		int nr_channels;
		int channel_reg_size;
		int max_dma_count;
		bool support_channel_pause;
		bool support_separate_wcount_reg;
	} cocci_id/* drivers/dma/tegra20-apb-dma.c 122 */;
	dma_addr_t cocci_id/* drivers/dma/tegra20-apb-dma.c 1128 */;
	size_t cocci_id/* drivers/dma/tegra20-apb-dma.c 1128 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/tegra20-apb-dma.c 1127 */;
	struct tegra_dma cocci_id/* drivers/dma/tegra20-apb-dma.c 112 */;
	struct scatterlist *cocci_id/* drivers/dma/tegra20-apb-dma.c 1005 */;
	unsigned int cocci_id/* drivers/dma/tegra20-apb-dma.c 1005 */;
}
