cocci_test_suite() {
	void __exit cocci_id/* drivers/dma/sh/shdmac.c 927 */;
	int __init cocci_id/* drivers/dma/sh/shdmac.c 916 */;
	struct platform_driver cocci_id/* drivers/dma/sh/shdmac.c 908 */;
	struct sh_dmae_device cocci_id/* drivers/dma/sh/shdmac.c 715 */;
	const struct sh_dmae_channel *cocci_id/* drivers/dma/sh/shdmac.c 71 */;
	struct resource *cocci_id/* drivers/dma/sh/shdmac.c 681 */;
	struct dma_device *cocci_id/* drivers/dma/sh/shdmac.c 680 */;
	void cocci_id/* drivers/dma/sh/shdmac.c 68 */;
	int cocci_id/* drivers/dma/sh/shdmac.c 676 */[SH_DMAE_MAX_CHANNELS];
	unsigned long cocci_id/* drivers/dma/sh/shdmac.c 675 */[SH_DMAE_MAX_CHANNELS];
	const enum dma_slave_buswidth cocci_id/* drivers/dma/sh/shdmac.c 670 */;
	const struct shdma_ops cocci_id/* drivers/dma/sh/shdmac.c 654 */;
	void *cocci_id/* drivers/dma/sh/shdmac.c 649 */;
	struct device *cocci_id/* drivers/dma/sh/shdmac.c 602 */;
	struct platform_device *cocci_id/* drivers/dma/sh/shdmac.c 522 */;
	struct shdma_dev *cocci_id/* drivers/dma/sh/shdmac.c 521 */;
	unsigned long cocci_id/* drivers/dma/sh/shdmac.c 518 */;
	struct notifier_block cocci_id/* drivers/dma/sh/shdmac.c 510 */;
	struct notifier_block *cocci_id/* drivers/dma/sh/shdmac.c 478 */;
	struct sh_dmae_desc cocci_id/* drivers/dma/sh/shdmac.c 459 */;
	struct sh_dmae_desc *cocci_id/* drivers/dma/sh/shdmac.c 458 */;
	struct shdma_desc *cocci_id/* drivers/dma/sh/shdmac.c 454 */;
	irqreturn_t cocci_id/* drivers/dma/sh/shdmac.c 442 */;
	size_t cocci_id/* drivers/dma/sh/shdmac.c 415 */;
	struct sh_dmae_chan cocci_id/* drivers/dma/sh/shdmac.c 403 */;
	struct shdma_chan *cocci_id/* drivers/dma/sh/shdmac.c 401 */;
	dma_addr_t cocci_id/* drivers/dma/sh/shdmac.c 379 */;
	size_t *cocci_id/* drivers/dma/sh/shdmac.c 379 */;
	const struct sh_dmae_slave_config *cocci_id/* drivers/dma/sh/shdmac.c 325 */;
	void __iomem *cocci_id/* drivers/dma/sh/shdmac.c 262 */;
	u16 cocci_id/* drivers/dma/sh/shdmac.c 257 */;
	struct sh_dmae_regs *cocci_id/* drivers/dma/sh/shdmac.c 215 */;
	int cocci_id/* drivers/dma/sh/shdmac.c 189 */;
	const struct sh_dmae_pdata *cocci_id/* drivers/dma/sh/shdmac.c 188 */;
	struct sh_dmae_device *cocci_id/* drivers/dma/sh/shdmac.c 187 */;
	u32 cocci_id/* drivers/dma/sh/shdmac.c 185 */;
	struct sh_dmae_chan *cocci_id/* drivers/dma/sh/shdmac.c 185 */;
	unsigned int cocci_id/* drivers/dma/sh/shdmac.c 185 */;
	bool cocci_id/* drivers/dma/sh/shdmac.c 175 */;
	unsigned short cocci_id/* drivers/dma/sh/shdmac.c 129 */;
}
