cocci_test_suite() {
	struct sock_fprog cocci_id/* net/core/sock.c 992 */;
	struct linger cocci_id/* net/core/sock.c 727 */;
	struct sock_txtime cocci_id/* net/core/sock.c 723 */;
	char cocci_id/* net/core/sock.c 653 */[IFNAMSIZ];
	struct net_device *cocci_id/* net/core/sock.c 625 */;
	u32 cocci_id/* net/core/sock.c 539 */;
	struct dst_entry *cocci_id/* net/core/sock.c 539 */;
	const int cocci_id/* net/core/sock.c 496 */;
	struct sk_buff_head *cocci_id/* net/core/sock.c 451 */;
	unsigned long cocci_id/* net/core/sock.c 450 */;
	char cocci_id/* net/core/sock.c 417 */[TASK_COMM_LEN];
	struct __kernel_sock_timeval *cocci_id/* net/core/sock.c 359 */;
	int __init cocci_id/* net/core/sock.c 3587 */;
	struct net *cocci_id/* net/core/sock.c 3576 */;
	struct seq_net_private cocci_id/* net/core/sock.c 3570 */;
	const struct seq_operations cocci_id/* net/core/sock.c 3560 */;
	struct proto cocci_id/* net/core/sock.c 3556 */;
	struct __kernel_old_timeval *cocci_id/* net/core/sock.c 355 */;
	struct __kernel_old_timeval cocci_id/* net/core/sock.c 352 */;
	const char *cocci_id/* net/core/sock.c 3502 */;
	const void *cocci_id/* net/core/sock.c 3493 */;
	char cocci_id/* net/core/sock.c 3493 */;
	loff_t *cocci_id/* net/core/sock.c 3482 */;
	struct seq_file *cocci_id/* net/core/sock.c 3482 */;
	struct old_timeval32 *cocci_id/* net/core/sock.c 347 */;
	struct old_timeval32 cocci_id/* net/core/sock.c 346 */;
	struct __kernel_sock_timeval cocci_id/* net/core/sock.c 335 */;
	const struct proto *cocci_id/* net/core/sock.c 3343 */;
	struct request_sock_ops *cocci_id/* net/core/sock.c 3333 */;
	struct pernet_operations cocci_id/* net/core/sock.c 3285 */;
	void __net_exit cocci_id/* net/core/sock.c 3279 */;
	struct prot_inuse cocci_id/* net/core/sock.c 3264 */;
	int __net_init cocci_id/* net/core/sock.c 3262 */;
	struct prot_inuse {
		int val[PROTO_INUSE_NR];
	} cocci_id/* net/core/sock.c 3221 */;
	unsigned int cocci_id/* net/core/sock.c 320 */;
	int cocci_id/* net/core/sock.c 317 */;
	size_t cocci_id/* net/core/sock.c 3126 */;
	int __user *cocci_id/* net/core/sock.c 3114 */;
	char __user *cocci_id/* net/core/sock.c 3114 */;
	struct socket *cocci_id/* net/core/sock.c 3113 */;
	struct sock_exterr_skb *cocci_id/* net/core/sock.c 3063 */;
	enum sock_flags cocci_id/* net/core/sock.c 3043 */;
	struct __kernel_old_timeval __user cocci_id/* net/core/sock.c 3030 */;
	ktime_t cocci_id/* net/core/sock.c 3015 */;
	struct timespec64 cocci_id/* net/core/sock.c 3008 */;
	void __user *cocci_id/* net/core/sock.c 3004 */;
	struct timer_list *cocci_id/* net/core/sock.c 2837 */;
	struct socket_wq *cocci_id/* net/core/sock.c 2779 */;
	char *cocci_id/* net/core/sock.c 2737 */;
	struct kvec cocci_id/* net/core/sock.c 2736 */;
	struct msghdr cocci_id/* net/core/sock.c 2735 */;
	struct page *cocci_id/* net/core/sock.c 2732 */;
	ssize_t cocci_id/* net/core/sock.c 2732 */;
	__u32 cocci_id/* net/core/sock.c 273 */;
	struct vm_area_struct *cocci_id/* net/core/sock.c 2725 */;
	struct file *cocci_id/* net/core/sock.c 2725 */;
	struct lock_class_key cocci_id/* net/core/sock.c 261 */[AF_MAX];
	u64 cocci_id/* net/core/sock.c 2536 */;
	bool cocci_id/* net/core/sock.c 2499 */;
	long cocci_id/* net/core/sock.c 2498 */;
	struct proto *cocci_id/* net/core/sock.c 2497 */;
	long *cocci_id/* net/core/sock.c 2472 */;
	struct sk_buff *cocci_id/* net/core/sock.c 2425 */;
	struct sock *cocci_id/* net/core/sock.c 2403 */;
	void cocci_id/* net/core/sock.c 2403 */;
	struct page_frag *cocci_id/* net/core/sock.c 2392 */;
	const char *const cocci_id/* net/core/sock.c 234 */[AF_MAX + 1];
	unsigned long *cocci_id/* net/core/sock.c 2337 */;
	u64 *cocci_id/* net/core/sock.c 2292 */;
	u32 *cocci_id/* net/core/sock.c 2274 */;
	struct sockcm_cookie *cocci_id/* net/core/sock.c 2264 */;
	struct msghdr *cocci_id/* net/core/sock.c 2263 */;
	struct cmsghdr *cocci_id/* net/core/sock.c 2263 */;
	int *cocci_id/* net/core/sock.c 2214 */;
	const bool cocci_id/* net/core/sock.c 2157 */;
	void *cocci_id/* net/core/sock.c 2156 */;
	kuid_t cocci_id/* net/core/sock.c 2063 */;
	const struct sk_buff *cocci_id/* net/core/sock.c 2003 */;
	const gfp_t cocci_id/* net/core/sock.c 1793 */;
	const struct sock *cocci_id/* net/core/sock.c 173 */;
	struct sk_filter *cocci_id/* net/core/sock.c 1692 */;
	struct sock cocci_id/* net/core/sock.c 1691 */;
	struct rcu_head *cocci_id/* net/core/sock.c 1689 */;
	gfp_t cocci_id/* net/core/sock.c 1652 */;
	struct module *cocci_id/* net/core/sock.c 1629 */;
	struct kmem_cache *cocci_id/* net/core/sock.c 1593 */;
	u32 cocci_id/* net/core/sock.c 1482 */[SK_MEMINFO_VARS];
	struct sock_filter __user *cocci_id/* net/core/sock.c 1442 */;
	void cocci_id/* net/core/sock.c 144 */(struct net *net, int val);
	struct sockaddr *cocci_id/* net/core/sock.c 1392 */;
	char cocci_id/* net/core/sock.c 1390 */[128];
	gid_t cocci_id/* net/core/sock.c 1375 */;
	struct ucred cocci_id/* net/core/sock.c 1358 */;
	union {
		int val;
		u64 val64;
		unsigned long ulval;
		struct linger ling;
		struct old_timeval32 tm32;
		struct __kernel_old_timeval tm;
		struct __kernel_sock_timeval stm;
		struct sock_txtime txtime;
	} cocci_id/* net/core/sock.c 1218 */;
	const struct group_info *cocci_id/* net/core/sock.c 1201 */;
	gid_t __user *cocci_id/* net/core/sock.c 1201 */;
	struct user_namespace *cocci_id/* net/core/sock.c 1194 */;
	struct ucred *cocci_id/* net/core/sock.c 1189 */;
	const struct cred *cocci_id/* net/core/sock.c 1188 */;
	struct pid *cocci_id/* net/core/sock.c 1188 */;
	unsigned long __user *cocci_id/* net/core/sock.c 1115 */;
}
