cocci_test_suite() {
	char *cocci_id/* net/core/pktgen.c 865 */;
	char cocci_id/* net/core/pktgen.c 863 */[16];
	bool *cocci_id/* net/core/pktgen.c 827 */;
	ssize_t cocci_id/* net/core/pktgen.c 798 */;
	unsigned long *cocci_id/* net/core/pktgen.c 757 */;
	long cocci_id/* net/core/pktgen.c 756 */;
	char cocci_id/* net/core/pktgen.c 737 */;
	const char __user *cocci_id/* net/core/pktgen.c 731 */;
	__u32 *cocci_id/* net/core/pktgen.c 711 */;
	unsigned long cocci_id/* net/core/pktgen.c 710 */;
	unsigned long long cocci_id/* net/core/pktgen.c 555 */;
	u64 cocci_id/* net/core/pktgen.c 551 */;
	ktime_t cocci_id/* net/core/pktgen.c 549 */;
	const struct file_operations cocci_id/* net/core/pktgen.c 538 */;
	struct inode *cocci_id/* net/core/pktgen.c 533 */;
	struct file *cocci_id/* net/core/pktgen.c 533 */;
	char cocci_id/* net/core/pktgen.c 501 */[128];
	loff_t *cocci_id/* net/core/pktgen.c 499 */;
	size_t cocci_id/* net/core/pktgen.c 499 */;
	struct seq_file *cocci_id/* net/core/pktgen.c 492 */;
	void *cocci_id/* net/core/pktgen.c 492 */;
	struct notifier_block cocci_id/* net/core/pktgen.c 483 */;
	void cocci_id/* net/core/pktgen.c 473 */(struct pktgen_dev *pkt_dev);
	void cocci_id/* net/core/pktgen.c 472 */(struct pktgen_thread *t);
	void cocci_id/* net/core/pktgen.c 469 */(struct pktgen_net *pn);
	int cocci_id/* net/core/pktgen.c 467 */(struct notifier_block *,
						unsigned long, void *);
	struct pktgen_dev *cocci_id/* net/core/pktgen.c 465 */(struct pktgen_thread *t,
							       const char *ifname,
							       bool exact);
	int cocci_id/* net/core/pktgen.c 464 */(struct pktgen_thread *t,
						const char *ifname);
	int cocci_id/* net/core/pktgen.c 463 */(struct pktgen_thread *t,
						struct pktgen_dev *i);
	const char cocci_id/* net/core/pktgen.c 459 */[];
	struct pktgen_thread {
		struct mutex if_lock;
		struct list_head if_list;
		struct list_head th_list;
		struct task_struct *tsk;
		char result[512];
		u32 control;
		int cpu;
		wait_queue_head_t queue;
		struct completion start_done;
		struct pktgen_net *net;
	} cocci_id/* net/core/pktgen.c 438 */;
	struct pktgen_net {
		struct net *net;
		struct proc_dir_entry *proc_dir;
		struct list_head pktgen_threads;
		bool pktgen_exiting;
	} cocci_id/* net/core/pktgen.c 431 */;
	struct pktgen_hdr {
		__be32 pgh_magic;
		__be32 seq_num;
		__be32 tv_sec;
		__be32 tv_usec;
	} cocci_id/* net/core/pktgen.c 421 */;
	void __exit cocci_id/* net/core/pktgen.c 3875 */;
	int __init cocci_id/* net/core/pktgen.c 3860 */;
	struct pktgen_net cocci_id/* net/core/pktgen.c 3857 */;
	struct pernet_operations cocci_id/* net/core/pktgen.c 3853 */;
	struct pktgen_thread cocci_id/* net/core/pktgen.c 3842 */;
	struct net *cocci_id/* net/core/pktgen.c 3827 */;
	void __net_exit cocci_id/* net/core/pktgen.c 3827 */;
	struct proc_dir_entry *cocci_id/* net/core/pktgen.c 3785 */;
	int __net_init cocci_id/* net/core/pktgen.c 3782 */;
	struct pktgen_dev cocci_id/* net/core/pktgen.c 3740 */;
	struct list_head *cocci_id/* net/core/pktgen.c 3735 */;
	void cocci_id/* net/core/pktgen.c 3732 */;
	struct task_struct *cocci_id/* net/core/pktgen.c 3680 */;
	struct flow_state cocci_id/* net/core/pktgen.c 3609 */;
	struct netdev_queue *cocci_id/* net/core/pktgen.c 3303 */;
	__u64 cocci_id/* net/core/pktgen.c 3144 */;
	const struct pktgen_thread *cocci_id/* net/core/pktgen.c 3044 */;
	struct sk_buff *cocci_id/* net/core/pktgen.c 2977 */;
	struct net_device *cocci_id/* net/core/pktgen.c 2977 */;
	struct ipv6hdr cocci_id/* net/core/pktgen.c 2910 */;
	struct ipv6hdr *cocci_id/* net/core/pktgen.c 2854 */;
	__wsum cocci_id/* net/core/pktgen.c 2829 */;
	struct pktgen_hdr cocci_id/* net/core/pktgen.c 2795 */;
	struct udphdr cocci_id/* net/core/pktgen.c 2785 */;
	struct iphdr cocci_id/* net/core/pktgen.c 2782 */;
	__u32 cocci_id/* net/core/pktgen.c 2758 */;
	u16 cocci_id/* net/core/pktgen.c 2733 */;
	__be16 *cocci_id/* net/core/pktgen.c 2729 */;
	__be32 *cocci_id/* net/core/pktgen.c 2728 */;
	struct iphdr *cocci_id/* net/core/pktgen.c 2726 */;
	struct udphdr *cocci_id/* net/core/pktgen.c 2724 */;
	__u8 *cocci_id/* net/core/pktgen.c 2723 */;
	struct pktgen_hdr *cocci_id/* net/core/pktgen.c 2617 */;
	struct timespec64 cocci_id/* net/core/pktgen.c 2616 */;
	__be16 cocci_id/* net/core/pktgen.c 2607 */;
	unsigned int cocci_id/* net/core/pktgen.c 2607 */;
	struct pktgen_dev {
		struct proc_dir_entry *entry;
		struct pktgen_thread *pg_thread;
		struct list_head list;
		struct rcu_head rcu;
		int running;
		__u32 flags;
		int xmit_mode;
		int min_pkt_size;
		int max_pkt_size;
		int pkt_overhead;
		int nfrags;
		int removal_mark;
		struct page *page;
		u64 delay;
		__u64 count;
		__u64 sofar;
		__u64 tx_bytes;
		__u64 errors;
		__u32 clone_count;
		int last_ok;
		ktime_t next_tx;
		ktime_t started_at;
		ktime_t stopped_at;
		u64 idle_acc;
		__u32 seq_num;
		int clone_skb;
		char dst_min[IP_NAME_SZ];
		char dst_max[IP_NAME_SZ];
		char src_min[IP_NAME_SZ];
		char src_max[IP_NAME_SZ];
		struct in6_addr in6_saddr;
		struct in6_addr in6_daddr;
		struct in6_addr cur_in6_daddr;
		struct in6_addr cur_in6_saddr;
		struct in6_addr min_in6_daddr;
		struct in6_addr max_in6_daddr;
		struct in6_addr min_in6_saddr;
		struct in6_addr max_in6_saddr;
		__be32 saddr_min;
		__be32 saddr_max;
		__be32 daddr_min;
		__be32 daddr_max;
		__u16 udp_src_min;
		__u16 udp_src_max;
		__u16 udp_dst_min;
		__u16 udp_dst_max;
		__u8 tos;
		__u8 traffic_class;
		unsigned int nr_labels;
		__be32 labels[MAX_MPLS_LABELS];
		__u8 vlan_p;
		__u8 vlan_cfi;
		__u16 vlan_id;
		__u8 svlan_p;
		__u8 svlan_cfi;
		__u16 svlan_id;
		__u32 src_mac_count;
		__u32 dst_mac_count;
		unsigned char dst_mac[ETH_ALEN];
		unsigned char src_mac[ETH_ALEN];
		__u32 cur_dst_mac_offset;
		__u32 cur_src_mac_offset;
		__be32 cur_saddr;
		__be32 cur_daddr;
		__u16 ip_id;
		__u16 cur_udp_dst;
		__u16 cur_udp_src;
		__u16 cur_queue_map;
		__u32 cur_pkt_size;
		__u32 last_pkt_size;
		__u8 hh[14];
		__u16 pad;
		struct sk_buff *skb;
		struct net_device *odev;
		char odevname[32];
		struct flow_state *flows;
		unsigned int cflows;
		unsigned int lflow;
		unsigned int nflows;
		unsigned int curfl;
		u16 queue_map_min;
		u16 queue_map_max;
		__u32 skb_priority;
		unsigned int burst;
		int node;
#ifdef CONFIG_XFRM
		__u8 ipsmode;
		__u8 ipsproto;
		__u32 spi;
		struct xfrm_dst xdst;
		struct dst_ops dstops;
#endif
		char result[512];
	} cocci_id/* net/core/pktgen.c 257 */;
	struct ethhdr *cocci_id/* net/core/pktgen.c 2558 */;
	struct xfrm_state *cocci_id/* net/core/pktgen.c 2542 */;
	u32 cocci_id/* net/core/pktgen.c 2492 */[RTAX_MAX + 1];
	struct flow_state {
		__be32 cur_daddr;
		int count;
#ifdef CONFIG_XFRM
		struct xfrm_state *x;
#endif
		__u32 flags;
	} cocci_id/* net/core/pktgen.c 245 */;
	__be32 cocci_id/* net/core/pktgen.c 2360 */;
	__u16 cocci_id/* net/core/pktgen.c 2273 */;
	xfrm_address_t *cocci_id/* net/core/pktgen.c 2251 */;
	struct pktgen_net *cocci_id/* net/core/pktgen.c 2240 */;
	const struct pktgen_dev *cocci_id/* net/core/pktgen.c 2200 */;
	u32 cocci_id/* net/core/pktgen.c 2195 */;
	struct hrtimer_sleeper cocci_id/* net/core/pktgen.c 2157 */;
	s64 cocci_id/* net/core/pktgen.c 2156 */;
	char *cocci_id/* net/core/pktgen.c 213 */[];
	const struct in_ifaddr *cocci_id/* net/core/pktgen.c 2121 */;
	struct in_device *cocci_id/* net/core/pktgen.c 2116 */;
	struct inet6_ifaddr *cocci_id/* net/core/pktgen.c 2087 */;
	const __u32 cocci_id/* net/core/pktgen.c 208 */;
	struct in6_addr cocci_id/* net/core/pktgen.c 2070 */;
	struct inet6_dev *cocci_id/* net/core/pktgen.c 2061 */;
	enum pkt_flags{PKT_FLAGS,} cocci_id/* net/core/pktgen.c 202 */;
	char cocci_id/* net/core/pktgen.c 1971 */[IFNAMSIZ + 5];
	struct notifier_block *cocci_id/* net/core/pktgen.c 1941 */;
	const int cocci_id/* net/core/pktgen.c 1882 */;
	bool cocci_id/* net/core/pktgen.c 1861 */;
	struct pktgen_thread *cocci_id/* net/core/pktgen.c 1859 */;
	const char *cocci_id/* net/core/pktgen.c 1857 */;
	int cocci_id/* net/core/pktgen.c 1857 */;
	const struct pktgen_net *cocci_id/* net/core/pktgen.c 1856 */;
	struct pktgen_dev *cocci_id/* net/core/pktgen.c 1856 */;
	char cocci_id/* net/core/pktgen.c 1755 */[40];
	char cocci_id/* net/core/pktgen.c 1172 */[32];
}
