cocci_test_suite() {
	struct nf_ct_gre_keymap *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 85 */;
	struct nf_gre_net *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 84 */;
	__be16 cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 82 */;
	struct nf_conntrack_tuple *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 82 */;
	const struct nf_conntrack_tuple *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 72 */;
	const struct nf_ct_gre_keymap *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 71 */;
	int cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 71 */;
	const unsigned int cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 45 */[GRE_CT_MAX];
	const struct nf_conntrack_l4proto cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 313 */;
	const struct nla_policy cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 295 */[CTA_TIMEOUT_GRE_MAX + 1];
	const unsigned int *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 282 */;
	const void *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 280 */;
	struct sk_buff *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 280 */;
	void *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 257 */;
	struct nlattr *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 256 */[];
	const struct nf_hook_state *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 219 */;
	enum ip_conntrack_info cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 218 */;
	struct net *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 209 */;
	unsigned int *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 209 */;
	struct seq_file *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 201 */;
	struct nf_conn *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 201 */;
	void cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 201 */;
	struct gre_base_hdr cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 171 */;
	const struct gre_base_hdr *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 170 */;
	struct pptp_gre_header cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 168 */;
	const struct pptp_gre_header *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 167 */;
	bool cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 164 */;
	const struct sk_buff *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 164 */;
	unsigned int cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 164 */;
	struct nf_ct_gre_keymap **cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 108 */;
	struct nf_ct_pptp_master *cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 107 */;
	enum ip_conntrack_dir cocci_id/* net/netfilter/nf_conntrack_proto_gre.c 102 */;
}
