cocci_test_suite() {
	struct sba_device cocci_id/* drivers/dma/bcm-sba-raid.c 96 */;
	unsigned int cocci_id/* drivers/dma/bcm-sba-raid.c 921 */;
	const u8 *cocci_id/* drivers/dma/bcm-sba-raid.c 917 */;
	dma_addr_t *cocci_id/* drivers/dma/bcm-sba-raid.c 916 */;
	size_t cocci_id/* drivers/dma/bcm-sba-raid.c 652 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/bcm-sba-raid.c 622 */;
	dma_addr_t cocci_id/* drivers/dma/bcm-sba-raid.c 569 */;
	struct brcm_message *cocci_id/* drivers/dma/bcm-sba-raid.c 565 */;
	struct brcm_sba_command *cocci_id/* drivers/dma/bcm-sba-raid.c 564 */;
	struct dma_tx_state *cocci_id/* drivers/dma/bcm-sba-raid.c 549 */;
	dma_cookie_t cocci_id/* drivers/dma/bcm-sba-raid.c 548 */;
	enum dma_status cocci_id/* drivers/dma/bcm-sba-raid.c 547 */;
	struct dma_chan *cocci_id/* drivers/dma/bcm-sba-raid.c 504 */;
	struct sba_request cocci_id/* drivers/dma/bcm-sba-raid.c 398 */;
	u32 cocci_id/* drivers/dma/bcm-sba-raid.c 390 */;
	int cocci_id/* drivers/dma/bcm-sba-raid.c 389 */;
	struct sba_request *cocci_id/* drivers/dma/bcm-sba-raid.c 272 */;
	struct sba_device *cocci_id/* drivers/dma/bcm-sba-raid.c 271 */;
	void cocci_id/* drivers/dma/bcm-sba-raid.c 271 */;
	bool cocci_id/* drivers/dma/bcm-sba-raid.c 254 */;
	unsigned long cocci_id/* drivers/dma/bcm-sba-raid.c 206 */;
	u32 __pure cocci_id/* drivers/dma/bcm-sba-raid.c 178 */;
	struct platform_driver cocci_id/* drivers/dma/bcm-sba-raid.c 1767 */;
	const struct of_device_id cocci_id/* drivers/dma/bcm-sba-raid.c 1760 */[];
	u64 __pure cocci_id/* drivers/dma/bcm-sba-raid.c 171 */;
	u64 cocci_id/* drivers/dma/bcm-sba-raid.c 171 */;
	struct of_phandle_args cocci_id/* drivers/dma/bcm-sba-raid.c 1626 */;
	struct platform_device *cocci_id/* drivers/dma/bcm-sba-raid.c 1621 */;
	struct dma_device *cocci_id/* drivers/dma/bcm-sba-raid.c 1554 */;
	struct seq_file *cocci_id/* drivers/dma/bcm-sba-raid.c 1459 */;
	void *cocci_id/* drivers/dma/bcm-sba-raid.c 1459 */;
	struct mbox_client *cocci_id/* drivers/dma/bcm-sba-raid.c 1442 */;
	struct sba_device {
		struct device *dev;
		enum sba_version ver;
		u32 max_req;
		u32 hw_buf_size;
		u32 hw_resp_size;
		u32 max_pq_coefs;
		u32 max_pq_srcs;
		u32 max_cmd_per_req;
		u32 max_xor_srcs;
		u32 max_resp_pool_size;
		u32 max_cmds_pool_size;
		struct mbox_client client;
		struct mbox_chan *mchan;
		struct device *mbox_dev;
		struct dma_device dma_dev;
		struct dma_chan dma_chan;
		void *resp_base;
		dma_addr_t resp_dma_base;
		void *cmds_base;
		dma_addr_t cmds_dma_base;
		spinlock_t reqs_lock;
		bool reqs_fence;
		struct list_head reqs_alloc_list;
		struct list_head reqs_pending_list;
		struct list_head reqs_active_list;
		struct list_head reqs_aborted_list;
		struct list_head reqs_free_list;
		struct dentry *root;
	} cocci_id/* drivers/dma/bcm-sba-raid.c 131 */;
	enum sba_version{SBA_VER_1=0, SBA_VER_2,} cocci_id/* drivers/dma/bcm-sba-raid.c 126 */;
	struct sba_request {
		struct list_head node;
		struct sba_device *sba;
		u32 flags;
		struct sba_request *first;
		struct list_head next;
		atomic_t next_pending_count;
		struct brcm_message msg;
		struct dma_async_tx_descriptor tx;
		struct brcm_sba_command cmds[0];
	} cocci_id/* drivers/dma/bcm-sba-raid.c 110 */;
	u8 cocci_id/* drivers/dma/bcm-sba-raid.c 1092 */;
	enum sba_request_flags{SBA_REQUEST_STATE_FREE=0x001, SBA_REQUEST_STATE_ALLOCED=0x002, SBA_REQUEST_STATE_PENDING=0x004, SBA_REQUEST_STATE_ACTIVE=0x008, SBA_REQUEST_STATE_ABORTED=0x010, SBA_REQUEST_STATE_MASK=0x0ff, SBA_REQUEST_FENCE=0x100,} cocci_id/* drivers/dma/bcm-sba-raid.c 100 */;
}
