cocci_test_suite() {
	__be16 *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 99 */;
	union nf_inet_addr *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 99 */;
	bool cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 98 */;
	char cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 98 */;
	const char *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 97 */;
	size_t cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 97 */;
	struct ip_vs_conn *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 86 */;
	struct tcphdr cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 70 */;
	struct tcphdr *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 68 */;
	struct sk_buff *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 66 */;
	struct ip_vs_iphdr *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 66 */;
	char *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 66 */;
	void __exit cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 630 */;
	int __init cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 621 */;
	struct pernet_operations cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 616 */;
	unsigned short cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 61 */[IP_VS_APP_MAX_PORTS];
	struct netns_ipvs *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 608 */;
	struct net *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 606 */;
	void cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 606 */;
	struct ip_vs_app *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 578 */;
	int cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 577 */;
	int __net_init cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 575 */;
	struct ip_vs_app cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 558 */;
	struct ip_vs_conn_param cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 530 */;
	enum{IP_VS_FTP_ACTIVE=0, IP_VS_FTP_PORT=0, IP_VS_FTP_PASV, IP_VS_FTP_EPRT, IP_VS_FTP_EPSV,} cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 48 */;
	void *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 451 */;
	__be16 cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 425 */;
	union nf_inet_addr cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 424 */;
	int *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 419 */;
	unsigned char *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 347 */;
	struct nf_conn *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 261 */;
	enum ip_conntrack_info cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 260 */;
	unsigned int cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 258 */;
	char cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 257 */[24];
	u8 *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 203 */;
	__be32 *cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 162 */;
	unsigned char cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 103 */[6];
	__u16 cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 100 */;
	char **cocci_id/* net/netfilter/ipvs/ip_vs_ftp.c 100 */;
}
