cocci_test_suite() {
	struct socket_wq *cocci_id/* net/atm/common.c 91 */;
	void __exit cocci_id/* net/atm/common.c 890 */;
	int __init cocci_id/* net/atm/common.c 850 */;
	struct notifier_block *cocci_id/* net/atm/common.c 838 */;
	struct sockaddr_atmpvc cocci_id/* net/atm/common.c 817 */;
	unsigned long __user *cocci_id/* net/atm/common.c 814 */;
	int __user *cocci_id/* net/atm/common.c 795 */;
	char __user *cocci_id/* net/atm/common.c 795 */;
	struct atm_qos cocci_id/* net/atm/common.c 761 */;
	unsigned int cocci_id/* net/atm/common.c 748 */;
	const struct atm_qos *cocci_id/* net/atm/common.c 730 */;
	const struct atm_trafprm *cocci_id/* net/atm/common.c 710 */;
	struct atm_qos *cocci_id/* net/atm/common.c 686 */;
	bool cocci_id/* net/atm/common.c 66 */;
	__poll_t cocci_id/* net/atm/common.c 651 */;
	poll_table *cocci_id/* net/atm/common.c 651 */;
	struct file *cocci_id/* net/atm/common.c 651 */;
	struct msghdr *cocci_id/* net/atm/common.c 522 */;
	size_t cocci_id/* net/atm/common.c 522 */;
	struct atm_dev cocci_id/* net/atm/common.c 503 */;
	struct socket *cocci_id/* net/atm/common.c 462 */;
	struct hlist_head *cocci_id/* net/atm/common.c 46 */;
	void cocci_id/* net/atm/common.c 43 */;
	struct sock *cocci_id/* net/atm/common.c 385 */;
	struct atm_vcc *cocci_id/* net/atm/common.c 382 */;
	struct atm_dev *cocci_id/* net/atm/common.c 382 */;
	int cocci_id/* net/atm/common.c 382 */;
	short cocci_id/* net/atm/common.c 382 */;
	struct hlist_head cocci_id/* net/atm/common.c 35 */[VCC_HTABLE_SIZE];
	int *cocci_id/* net/atm/common.c 338 */;
	short *cocci_id/* net/atm/common.c 338 */;
	const struct atm_vcc *cocci_id/* net/atm/common.c 313 */;
	struct atm_trafprm *cocci_id/* net/atm/common.c 285 */;
	unsigned char cocci_id/* net/atm/common.c 285 */;
	struct hlist_node *cocci_id/* net/atm/common.c 269 */;
	char cocci_id/* net/atm/common.c 245 */;
	unsigned long cocci_id/* net/atm/common.c 229 */;
	struct sk_buff_head cocci_id/* net/atm/common.c 227 */;
	struct sk_buff *cocci_id/* net/atm/common.c 176 */;
	struct sockaddr_atmsvc cocci_id/* net/atm/common.c 157 */;
	struct net *cocci_id/* net/atm/common.c 140 */;
	struct atm_vcc cocci_id/* net/atm/common.c 136 */;
	struct proto cocci_id/* net/atm/common.c 133 */;
}
