cocci_test_suite() {
	struct sockaddr_pppol2tpv3 cocci_id/* net/l2tp/l2tp_ppp.c 986 */;
	struct sockaddr_pppol2tpv3in6 cocci_id/* net/l2tp/l2tp_ppp.c 967 */;
	struct sockaddr_pppol2tpin6 cocci_id/* net/l2tp/l2tp_ppp.c 948 */;
	struct sockaddr_pppol2tp cocci_id/* net/l2tp/l2tp_ppp.c 930 */;
	struct inet_sock *cocci_id/* net/l2tp/l2tp_ppp.c 911 */;
	struct l2tp_session_cfg *cocci_id/* net/l2tp/l2tp_ppp.c 865 */;
	struct pppol2tp_session cocci_id/* net/l2tp/l2tp_ppp.c 778 */;
	struct l2tp_tunnel_cfg cocci_id/* net/l2tp/l2tp_ppp.c 708 */;
	bool cocci_id/* net/l2tp/l2tp_ppp.c 671 */;
	struct l2tp_session_cfg cocci_id/* net/l2tp/l2tp_ppp.c 670 */;
	struct pppol2tp_session *cocci_id/* net/l2tp/l2tp_ppp.c 669 */;
	struct l2tp_tunnel *cocci_id/* net/l2tp/l2tp_ppp.c 668 */;
	struct l2tp_connect_info cocci_id/* net/l2tp/l2tp_ppp.c 667 */;
	struct l2tp_session *cocci_id/* net/l2tp/l2tp_ppp.c 666 */;
	struct pppox_sock *cocci_id/* net/l2tp/l2tp_ppp.c 665 */;
	struct socket *cocci_id/* net/l2tp/l2tp_ppp.c 661 */;
	struct sockaddr *cocci_id/* net/l2tp/l2tp_ppp.c 661 */;
	const struct l2tp_tunnel *cocci_id/* net/l2tp/l2tp_ppp.c 648 */;
	const struct sockaddr_pppol2tpv3in6 *cocci_id/* net/l2tp/l2tp_ppp.c 622 */;
	const struct sockaddr_pppol2tpin6 *cocci_id/* net/l2tp/l2tp_ppp.c 606 */;
	const struct sockaddr_pppol2tpv3 *cocci_id/* net/l2tp/l2tp_ppp.c 590 */;
	const struct sockaddr_pppol2tp *cocci_id/* net/l2tp/l2tp_ppp.c 574 */;
	struct l2tp_connect_info *cocci_id/* net/l2tp/l2tp_ppp.c 569 */;
	const void *cocci_id/* net/l2tp/l2tp_ppp.c 568 */;
	struct l2tp_connect_info {
		u8 version;
		int fd;
		u32 tunnel_id;
		u32 peer_tunnel_id;
		u32 session_id;
		u32 peer_session_id;
	} cocci_id/* net/l2tp/l2tp_ppp.c 559 */;
	struct net *cocci_id/* net/l2tp/l2tp_ppp.c 505 */;
	struct sock *cocci_id/* net/l2tp/l2tp_ppp.c 492 */;
	struct sk_buff *cocci_id/* net/l2tp/l2tp_ppp.c 492 */;
	int cocci_id/* net/l2tp/l2tp_ppp.c 492 */;
	struct pppox_sock cocci_id/* net/l2tp/l2tp_ppp.c 489 */;
	struct proto cocci_id/* net/l2tp/l2tp_ppp.c 486 */;
	typeof(*ps) cocci_id/* net/l2tp/l2tp_ppp.c 407 */;
	struct rcu_head *cocci_id/* net/l2tp/l2tp_ppp.c 403 */;
	struct ppp_channel *cocci_id/* net/l2tp/l2tp_ppp.c 352 */;
	struct iphdr cocci_id/* net/l2tp/l2tp_ppp.c 298 */;
	struct udphdr cocci_id/* net/l2tp/l2tp_ppp.c 294 */;
	size_t cocci_id/* net/l2tp/l2tp_ppp.c 181 */;
	struct msghdr *cocci_id/* net/l2tp/l2tp_ppp.c 180 */;
	void __exit cocci_id/* net/l2tp/l2tp_ppp.c 1742 */;
	int __init cocci_id/* net/l2tp/l2tp_ppp.c 1704 */;
	const struct l2tp_nl_cmd_ops cocci_id/* net/l2tp/l2tp_ppp.c 1697 */;
	const struct pppox_proto cocci_id/* net/l2tp/l2tp_ppp.c 1689 */;
	struct pernet_operations cocci_id/* net/l2tp/l2tp_ppp.c 1656 */;
	struct pppol2tp_seq_data cocci_id/* net/l2tp/l2tp_ppp.c 1641 */;
	struct proc_dir_entry *cocci_id/* net/l2tp/l2tp_ppp.c 1637 */;
	const struct seq_operations cocci_id/* net/l2tp/l2tp_ppp.c 1623 */;
	u16 cocci_id/* net/l2tp/l2tp_ppp.c 1550 */;
	char cocci_id/* net/l2tp/l2tp_ppp.c 1547 */;
	unsigned char cocci_id/* net/l2tp/l2tp_ppp.c 1546 */;
	loff_t *cocci_id/* net/l2tp/l2tp_ppp.c 1498 */;
	struct seq_file *cocci_id/* net/l2tp/l2tp_ppp.c 1498 */;
	void *cocci_id/* net/l2tp/l2tp_ppp.c 1498 */;
	loff_t cocci_id/* net/l2tp/l2tp_ppp.c 1475 */;
	struct pppol2tp_seq_data *cocci_id/* net/l2tp/l2tp_ppp.c 1457 */;
	struct pppol2tp_seq_data {
		struct seq_net_private p;
		int tunnel_idx;
		int session_idx;
		struct l2tp_tunnel *tunnel;
		struct l2tp_session *session;
	} cocci_id/* net/l2tp/l2tp_ppp.c 1431 */;
	void __user *cocci_id/* net/l2tp/l2tp_ppp.c 1410 */;
	unsigned int cocci_id/* net/l2tp/l2tp_ppp.c 1378 */;
	int __user *cocci_id/* net/l2tp/l2tp_ppp.c 1364 */;
	char __user *cocci_id/* net/l2tp/l2tp_ppp.c 1364 */;
	const struct proto_ops cocci_id/* net/l2tp/l2tp_ppp.c 132 */;
	int *cocci_id/* net/l2tp/l2tp_ppp.c 1316 */;
	const struct ppp_channel_ops cocci_id/* net/l2tp/l2tp_ppp.c 128 */;
	int cocci_id/* net/l2tp/l2tp_ppp.c 126 */(struct ppp_channel *chan,
						  struct sk_buff *skb);
	struct pppol2tp_session {
		int owner;
		struct mutex sk_lock;
		struct sock __rcu *sk;
		struct sock *__sk;
		struct rcu_head rcu;
	} cocci_id/* net/l2tp/l2tp_ppp.c 116 */;
	u32 cocci_id/* net/l2tp/l2tp_ppp.c 1106 */;
	struct pppol2tp_ioc_stats cocci_id/* net/l2tp/l2tp_ppp.c 1067 */;
	unsigned long cocci_id/* net/l2tp/l2tp_ppp.c 1065 */;
	const struct l2tp_stats *cocci_id/* net/l2tp/l2tp_ppp.c 1022 */;
	struct pppol2tp_ioc_stats *cocci_id/* net/l2tp/l2tp_ppp.c 1021 */;
	void cocci_id/* net/l2tp/l2tp_ppp.c 1021 */;
}
