cocci_test_suite() {
	void cocci_id/* drivers/dma/dw/core.c 955 */;
	struct dma_tx_state *cocci_id/* drivers/dma/dw/core.c 919 */;
	enum dma_status cocci_id/* drivers/dma/dw/core.c 916 */;
	dma_cookie_t cocci_id/* drivers/dma/dw/core.c 880 */;
	dma_addr_t cocci_id/* drivers/dma/dw/core.c 84 */;
	struct dma_slave_config *cocci_id/* drivers/dma/dw/core.c 787 */;
	struct dw_dma_slave cocci_id/* drivers/dma/dw/core.c 781 */;
	struct dw_dma_slave *cocci_id/* drivers/dma/dw/core.c 775 */;
	void *cocci_id/* drivers/dma/dw/core.c 772 */;
	enum dma_transfer_direction cocci_id/* drivers/dma/dw/core.c 623 */;
	struct scatterlist *cocci_id/* drivers/dma/dw/core.c 622 */;
	size_t cocci_id/* drivers/dma/dw/core.c 546 */;
	u32 cocci_id/* drivers/dma/dw/core.c 502 */;
	irqreturn_t cocci_id/* drivers/dma/dw/core.c 499 */;
	struct dma_chan *cocci_id/* drivers/dma/dw/core.c 46 */;
	struct device *cocci_id/* drivers/dma/dw/core.c 46 */;
	struct list_head *cocci_id/* drivers/dma/dw/core.c 322 */;
	struct dw_desc *cocci_id/* drivers/dma/dw/core.c 269 */;
	struct dmaengine_desc_callback cocci_id/* drivers/dma/dw/core.c 246 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/dma/dw/core.c 243 */;
	u8 cocci_id/* drivers/dma/dw/core.c 182 */;
	void __iomem *cocci_id/* drivers/dma/dw/core.c 1168 */;
	struct dw_dma_chan *cocci_id/* drivers/dma/dw/core.c 1138 */;
	unsigned long cocci_id/* drivers/dma/dw/core.c 1129 */;
	struct dw_desc cocci_id/* drivers/dma/dw/core.c 1122 */;
	unsigned int cocci_id/* drivers/dma/dw/core.c 1057 */;
	bool cocci_id/* drivers/dma/dw/core.c 1056 */;
	struct dw_dma_platform_data *cocci_id/* drivers/dma/dw/core.c 1055 */;
	struct dw_dma *cocci_id/* drivers/dma/dw/core.c 1054 */;
	struct dw_dma_chip *cocci_id/* drivers/dma/dw/core.c 1052 */;
	int cocci_id/* drivers/dma/dw/core.c 1052 */;
}
