cocci_test_suite() {
	unsigned short cocci_id/* net/batman-adv/gateway_client.c 752 */;
	u8 cocci_id/* net/batman-adv/gateway_client.c 751 */;
	bool cocci_id/* net/batman-adv/gateway_client.c 740 */;
	struct batadv_gw_node cocci_id/* net/batman-adv/gateway_client.c 67 */;
	__be16 cocci_id/* net/batman-adv/gateway_client.c 631 */;
	struct kref *cocci_id/* net/batman-adv/gateway_client.c 63 */;
	struct vlan_ethhdr *cocci_id/* net/batman-adv/gateway_client.c 629 */;
	struct udphdr *cocci_id/* net/batman-adv/gateway_client.c 628 */;
	struct ipv6hdr *cocci_id/* net/batman-adv/gateway_client.c 627 */;
	struct iphdr *cocci_id/* net/batman-adv/gateway_client.c 626 */;
	struct ethhdr *cocci_id/* net/batman-adv/gateway_client.c 625 */;
	u8 *cocci_id/* net/batman-adv/gateway_client.c 622 */;
	struct sk_buff *cocci_id/* net/batman-adv/gateway_client.c 621 */;
	unsigned int *cocci_id/* net/batman-adv/gateway_client.c 621 */;
	enum batadv_dhcp_recipient cocci_id/* net/batman-adv/gateway_client.c 620 */;
	struct net *cocci_id/* net/batman-adv/gateway_client.c 562 */;
	struct netlink_callback *cocci_id/* net/batman-adv/gateway_client.c 559 */;
	struct batadv_hard_iface *cocci_id/* net/batman-adv/gateway_client.c 527 */;
	struct net_device *cocci_id/* net/batman-adv/gateway_client.c 525 */;
	struct seq_file *cocci_id/* net/batman-adv/gateway_client.c 523 */;
	void *cocci_id/* net/batman-adv/gateway_client.c 523 */;
	int cocci_id/* net/batman-adv/gateway_client.c 523 */;
	struct hlist_node *cocci_id/* net/batman-adv/gateway_client.c 502 */;
	struct batadv_tvlv_gateway_data cocci_id/* net/batman-adv/gateway_client.c 487 */;
	struct batadv_tvlv_gateway_data *cocci_id/* net/batman-adv/gateway_client.c 344 */;
	struct batadv_orig_node *cocci_id/* net/batman-adv/gateway_client.c 304 */;
	char cocci_id/* net/batman-adv/gateway_client.c 216 */[18];
	struct batadv_neigh_ifinfo *cocci_id/* net/batman-adv/gateway_client.c 215 */;
	struct batadv_neigh_node *cocci_id/* net/batman-adv/gateway_client.c 214 */;
	struct batadv_gw_node *cocci_id/* net/batman-adv/gateway_client.c 184 */;
	struct batadv_priv *cocci_id/* net/batman-adv/gateway_client.c 182 */;
	void cocci_id/* net/batman-adv/gateway_client.c 182 */;
}
