cocci_test_suite() {
	struct thin_disk_superblock {
		__le32 csum;
		__le32 flags;
		__le64 blocknr;
		__u8 uuid[16];
		__le64 magic;
		__le32 version;
		__le32 time;
		__le64 trans_id;
		__le64 held_root;
		__u8 data_space_map_root[SPACE_MAP_ROOT_SIZE];
		__u8 metadata_space_map_root[SPACE_MAP_ROOT_SIZE];
		__le64 data_mapping_root;
		__le64 device_details_root;
		__le32 data_block_size;
		__le32 metadata_block_size;
		__le64 metadata_nr_blocks;
		__le32 compat_flags;
		__le32 compat_ro_flags;
		__le32 incompat_flags;
	}__packed cocci_id/* drivers/md/dm-thin-metadata.c 98 */;
	struct dm_thin_device **cocci_id/* drivers/md/dm-thin-metadata.c 976 */;
	struct block_device *cocci_id/* drivers/md/dm-thin-metadata.c 892 */;
	struct thin_disk_superblock cocci_id/* drivers/md/dm-thin-metadata.c 833 */;
	struct dm_block *cocci_id/* drivers/md/dm-thin-metadata.c 766 */;
	struct thin_disk_superblock *cocci_id/* drivers/md/dm-thin-metadata.c 765 */;
	struct dm_pool_metadata *cocci_id/* drivers/md/dm-thin-metadata.c 762 */;
	int cocci_id/* drivers/md/dm-thin-metadata.c 762 */;
	bool cocci_id/* drivers/md/dm-thin-metadata.c 735 */;
	unsigned long long cocci_id/* drivers/md/dm-thin-metadata.c 672 */;
	unsigned long cocci_id/* drivers/md/dm-thin-metadata.c 633 */;
	uint32_t cocci_id/* drivers/md/dm-thin-metadata.c 628 */;
	sector_t cocci_id/* drivers/md/dm-thin-metadata.c 530 */;
	size_t cocci_id/* drivers/md/dm-thin-metadata.c 496 */;
	__le64 *cocci_id/* drivers/md/dm-thin-metadata.c 431 */;
	struct dm_block_manager *cocci_id/* drivers/md/dm-thin-metadata.c 426 */;
	int *cocci_id/* drivers/md/dm-thin-metadata.c 426 */;
	struct dm_block **cocci_id/* drivers/md/dm-thin-metadata.c 420 */;
	const void *cocci_id/* drivers/md/dm-thin-metadata.c 326 */;
	void *cocci_id/* drivers/md/dm-thin-metadata.c 326 */;
	uint32_t *cocci_id/* drivers/md/dm-thin-metadata.c 308 */;
	struct dm_block_validator cocci_id/* drivers/md/dm-thin-metadata.c 293 */;
	__le32 cocci_id/* drivers/md/dm-thin-metadata.c 265 */;
	struct dm_block_validator *cocci_id/* drivers/md/dm-thin-metadata.c 260 */;
	struct dm_thin_device {
		struct list_head list;
		struct dm_pool_metadata *pmd;
		dm_thin_id id;
		int open_count;
		bool changed:1;
		bool aborted_with_changes:1;
		uint64_t mapped_blocks;
		uint64_t transaction_id;
		uint32_t creation_time;
		uint32_t snapshotted_time;
	} cocci_id/* drivers/md/dm-thin-metadata.c 228 */;
	dm_pool_pre_commit_fn cocci_id/* drivers/md/dm-thin-metadata.c 2067 */;
	dm_sm_threshold_fn cocci_id/* drivers/md/dm-thin-metadata.c 2054 */;
	struct dm_space_map *cocci_id/* drivers/md/dm-thin-metadata.c 1991 */;
	dm_block_t cocci_id/* drivers/md/dm-thin-metadata.c 1662 */[1];
	unsigned cocci_id/* drivers/md/dm-thin-metadata.c 1660 */;
	struct dm_thin_lookup_result cocci_id/* drivers/md/dm-thin-metadata.c 1548 */;
	bool *cocci_id/* drivers/md/dm-thin-metadata.c 1544 */;
	dm_block_t *cocci_id/* drivers/md/dm-thin-metadata.c 1543 */;
	struct dm_btree_info *cocci_id/* drivers/md/dm-thin-metadata.c 1493 */;
	dm_block_t cocci_id/* drivers/md/dm-thin-metadata.c 1492 */[2];
	struct dm_thin_lookup_result *cocci_id/* drivers/md/dm-thin-metadata.c 1487 */;
	struct dm_pool_metadata {
		struct hlist_node hash;
		struct block_device *bdev;
		struct dm_block_manager *bm;
		struct dm_space_map *metadata_sm;
		struct dm_space_map *data_sm;
		struct dm_transaction_manager *tm;
		struct dm_transaction_manager *nb_tm;
		struct dm_btree_info info;
		struct dm_btree_info nb_info;
		struct dm_btree_info tl_info;
		struct dm_btree_info bl_info;
		struct dm_btree_info details_info;
		struct rw_semaphore root_lock;
		uint32_t time;
		dm_block_t root;
		dm_block_t details_root;
		struct list_head thin_devices;
		uint64_t trans_id;
		unsigned long flags;
		sector_t data_block_size;
		dm_pool_pre_commit_fn pre_commit_fn;
		void *pre_commit_context;
		dm_block_t metadata_reserve;
		bool fail_io:1;
		bool in_service:1;
		__u8 data_space_map_root[SPACE_MAP_ROOT_SIZE];
		__u8 metadata_space_map_root[SPACE_MAP_ROOT_SIZE];
	} cocci_id/* drivers/md/dm-thin-metadata.c 145 */;
	struct disk_device_details {
		__le64 mapped_blocks;
		__le64 transaction_id;
		__le32 creation_time;
		__le32 snapshotted_time;
	}__packed cocci_id/* drivers/md/dm-thin-metadata.c 138 */;
	uint64_t *cocci_id/* drivers/md/dm-thin-metadata.c 1258 */;
	__le64 cocci_id/* drivers/md/dm-thin-metadata.c 1127 */;
	struct disk_device_details cocci_id/* drivers/md/dm-thin-metadata.c 1126 */;
	uint64_t cocci_id/* drivers/md/dm-thin-metadata.c 1124 */;
	dm_block_t cocci_id/* drivers/md/dm-thin-metadata.c 1123 */;
	dm_thin_id cocci_id/* drivers/md/dm-thin-metadata.c 1120 */;
	struct dm_thin_device *cocci_id/* drivers/md/dm-thin-metadata.c 1037 */;
	void cocci_id/* drivers/md/dm-thin-metadata.c 1037 */;
}
