cocci_test_suite() {
	void *cocci_id/* net/batman-adv/bat_v.c 923 */;
	struct batadv_neigh_node *cocci_id/* net/batman-adv/bat_v.c 920 */;
	struct batadv_neigh_ifinfo *cocci_id/* net/batman-adv/bat_v.c 919 */;
	u32 cocci_id/* net/batman-adv/bat_v.c 914 */;
	struct seq_file *cocci_id/* net/batman-adv/bat_v.c 881 */;
	const struct batadv_gw_node *cocci_id/* net/batman-adv/bat_v.c 836 */;
	struct batadv_orig_node *cocci_id/* net/batman-adv/bat_v.c 785 */;
	bool cocci_id/* net/batman-adv/bat_v.c 784 */;
	u32 *cocci_id/* net/batman-adv/bat_v.c 704 */;
	char *cocci_id/* net/batman-adv/bat_v.c 688 */;
	ssize_t cocci_id/* net/batman-adv/bat_v.c 688 */;
	size_t cocci_id/* net/batman-adv/bat_v.c 670 */;
	struct hlist_head *cocci_id/* net/batman-adv/bat_v.c 582 */;
	struct batadv_hashtable *cocci_id/* net/batman-adv/bat_v.c 581 */;
	unsigned long cocci_id/* net/batman-adv/bat_v.c 356 */;
	int *cocci_id/* net/batman-adv/bat_v.c 269 */;
	unsigned int cocci_id/* net/batman-adv/bat_v.c 222 */;
	struct net_device *cocci_id/* net/batman-adv/bat_v.c 182 */;
	struct batadv_hardif_neigh_node *cocci_id/* net/batman-adv/bat_v.c 115 */;
	int __init cocci_id/* net/batman-adv/bat_v.c 1127 */;
	struct batadv_hard_iface *cocci_id/* net/batman-adv/bat_v.c 1078 */;
	struct batadv_algo_ops cocci_id/* net/batman-adv/bat_v.c 1036 */;
	struct batadv_gw_node *cocci_id/* net/batman-adv/bat_v.c 1011 */;
	int cocci_id/* net/batman-adv/bat_v.c 1010 */;
	struct batadv_priv *cocci_id/* net/batman-adv/bat_v.c 1008 */;
	struct sk_buff *cocci_id/* net/batman-adv/bat_v.c 1007 */;
	struct netlink_callback *cocci_id/* net/batman-adv/bat_v.c 1007 */;
	void cocci_id/* net/batman-adv/bat_v.c 1007 */;
}
