cocci_test_suite() {
	struct callchain_param *cocci_id/* tools/perf/builtin-report.c 981 */;
	struct perf_data *cocci_id/* tools/perf/builtin-report.c 881 */;
	struct evsel *cocci_id/* tools/perf/builtin-report.c 880 */;
	struct perf_session *cocci_id/* tools/perf/builtin-report.c 879 */;
	struct report *cocci_id/* tools/perf/builtin-report.c 876 */;
	int cocci_id/* tools/perf/builtin-report.c 876 */;
	struct thread cocci_id/* tools/perf/builtin-report.c 838 */;
	struct threads *cocci_id/* tools/perf/builtin-report.c 832 */;
	struct rb_node *cocci_id/* tools/perf/builtin-report.c 815 */;
	unsigned int cocci_id/* tools/perf/builtin-report.c 814 */;
	struct thread *cocci_id/* tools/perf/builtin-report.c 793 */;
	struct task *cocci_id/* tools/perf/builtin-report.c 791 */;
	struct map *cocci_id/* tools/perf/builtin-report.c 775 */;
	struct maps *cocci_id/* tools/perf/builtin-report.c 772 */;
	struct task {
		struct thread *thread;
		struct list_head list;
		struct list_head children;
	} cocci_id/* tools/perf/builtin-report.c 744 */;
	struct report {
		struct perf_tool tool;
		struct perf_session *session;
		struct evswitch evswitch;
		bool use_tui,use_gtk,use_stdio;
		bool show_full_info;
		bool show_threads;
		bool inverted_callchain;
		bool mem_mode;
		bool stats_mode;
		bool tasks_mode;
		bool mmaps_mode;
		bool header;
		bool header_only;
		bool nonany_branch_mode;
		bool group_set;
		int max_stack;
		struct perf_read_values show_threads_values;
		struct annotation_options annotation_opts;
		const char *pretty_printing_style;
		const char *cpu_list;
		const char *symbol_filter_str;
		const char *time_str;
		struct perf_time_interval *ptime_range;
		int range_size;
		int range_num;
		float min_percent;
		u64 nr_entries;
		u64 queue_size;
		u64 total_cycles;
		int socket_filter;
	DECLARE_BITMAP(cpu_bitmap,MAX_NR_CPUS)
		;
		struct branch_type_stat brtype_stat;
		bool symbol_ipc;
		bool total_cycles_mode;
		struct block_report *block_reports;
	} cocci_id/* tools/perf/builtin-report.c 71 */;
	void cocci_id/* tools/perf/builtin-report.c 701 */;
	struct symbol *cocci_id/* tools/perf/builtin-report.c 689 */;
	struct ui_progress cocci_id/* tools/perf/builtin-report.c 654 */;
	int (*cocci_id/* tools/perf/builtin-report.c 596 */)(struct evlist *evlist,
							     const char *help,
							     struct hist_browser_timer *timer,
							     float min_pcnt);
	struct kmap *cocci_id/* tools/perf/builtin-report.c 568 */;
	const struct report *cocci_id/* tools/perf/builtin-report.c 565 */;
	struct evlist *cocci_id/* tools/perf/builtin-report.c 514 */;
	const struct hists *cocci_id/* tools/perf/builtin-report.c 457 */;
	char cocci_id/* tools/perf/builtin-report.c 438 */[512];
	u64 cocci_id/* tools/perf/builtin-report.c 436 */;
	unsigned long cocci_id/* tools/perf/builtin-report.c 435 */;
	char cocci_id/* tools/perf/builtin-report.c 434 */;
	const char *cocci_id/* tools/perf/builtin-report.c 431 */;
	FILE *cocci_id/* tools/perf/builtin-report.c 431 */;
	struct hists *cocci_id/* tools/perf/builtin-report.c 430 */;
	size_t cocci_id/* tools/perf/builtin-report.c 430 */;
	struct machine *cocci_id/* tools/perf/builtin-report.c 315 */;
	struct perf_tool *cocci_id/* tools/perf/builtin-report.c 311 */;
	struct hist_entry_iter cocci_id/* tools/perf/builtin-report.c 248 */;
	struct addr_location cocci_id/* tools/perf/builtin-report.c 247 */;
	union perf_event *cocci_id/* tools/perf/builtin-report.c 218 */;
	struct perf_sample *cocci_id/* tools/perf/builtin-report.c 189 */;
	struct branch_info *cocci_id/* tools/perf/builtin-report.c 188 */;
	struct hist_entry *cocci_id/* tools/perf/builtin-report.c 186 */;
	void *cocci_id/* tools/perf/builtin-report.c 184 */;
	struct addr_location *cocci_id/* tools/perf/builtin-report.c 182 */;
	struct hist_entry_iter *cocci_id/* tools/perf/builtin-report.c 181 */;
	struct mem_info *cocci_id/* tools/perf/builtin-report.c 148 */;
	struct branch_type_stat cocci_id/* tools/perf/builtin-report.c 1358 */;
	char cocci_id/* tools/perf/builtin-report.c 1267 */[128];
	struct perf_data cocci_id/* tools/perf/builtin-report.c 1263 */;
	const struct option cocci_id/* tools/perf/builtin-report.c 1116 */[];
	struct report cocci_id/* tools/perf/builtin-report.c 1089 */;
	const char *const cocci_id/* tools/perf/builtin-report.c 1085 */[];
	char cocci_id/* tools/perf/builtin-report.c 1084 */[];
	const char cocci_id/* tools/perf/builtin-report.c 1081 */[];
	bool cocci_id/* tools/perf/builtin-report.c 1077 */;
	struct stat cocci_id/* tools/perf/builtin-report.c 1076 */;
	struct itrace_synth_opts cocci_id/* tools/perf/builtin-report.c 1075 */;
	const char **cocci_id/* tools/perf/builtin-report.c 1072 */;
	double cocci_id/* tools/perf/builtin-report.c 1065 */;
	int *cocci_id/* tools/perf/builtin-report.c 1054 */;
	const struct option *cocci_id/* tools/perf/builtin-report.c 1051 */;
	char cocci_id/* tools/perf/builtin-report.c 1039 */[BUFSIZ];
	char *cocci_id/* tools/perf/builtin-report.c 1001 */;
	unsigned long *cocci_id/* tools/perf/builtin-report.c 1000 */;
}
