cocci_test_suite() {
	const u8 *cocci_id/* tools/perf/util/build-id.c 94 */;
	char *cocci_id/* tools/perf/util/build-id.c 94 */;
	struct dso *cocci_id/* tools/perf/util/build-id.c 832 */;
	struct machine *cocci_id/* tools/perf/util/build-id.c 830 */;
	struct perf_tool cocci_id/* tools/perf/util/build-id.c 83 */;
	struct list_head *cocci_id/* tools/perf/util/build-id.c 829 */;
	int cocci_id/* tools/perf/util/build-id.c 829 */;
	char cocci_id/* tools/perf/util/build-id.c 757 */[SBUILD_ID_SIZE];
	bool cocci_id/* tools/perf/util/build-id.c 755 */;
	struct nsinfo *cocci_id/* tools/perf/util/build-id.c 754 */;
	const size_t cocci_id/* tools/perf/util/build-id.c 647 */;
	struct nscookie cocci_id/* tools/perf/util/build-id.c 596 */;
	struct probe_cache *cocci_id/* tools/perf/util/build-id.c 594 */;
	struct strlist **cocci_id/* tools/perf/util/build-id.c 572 */;
	struct str_node *cocci_id/* tools/perf/util/build-id.c 519 */;
	struct strlist *cocci_id/* tools/perf/util/build-id.c 518 */;
	struct thread *cocci_id/* tools/perf/util/build-id.c 46 */;
	struct addr_location cocci_id/* tools/perf/util/build-id.c 45 */;
	struct dirent *cocci_id/* tools/perf/util/build-id.c 424 */;
	struct evsel *cocci_id/* tools/perf/util/build-id.c 42 */;
	void cocci_id/* tools/perf/util/build-id.c 418 */;
	struct perf_sample *cocci_id/* tools/perf/util/build-id.c 41 */;
	struct machine cocci_id/* tools/perf/util/build-id.c 408 */;
	union perf_event *cocci_id/* tools/perf/util/build-id.c 40 */;
	struct rb_node *cocci_id/* tools/perf/util/build-id.c 399 */;
	struct perf_session *cocci_id/* tools/perf/util/build-id.c 397 */;
	struct perf_tool *cocci_id/* tools/perf/util/build-id.c 39 */;
	u16 cocci_id/* tools/perf/util/build-id.c 324 */;
	struct feat_fd *cocci_id/* tools/perf/util/build-id.c 320 */;
	struct perf_record_header_build_id cocci_id/* tools/perf/util/build-id.c 300 */;
	pid_t cocci_id/* tools/perf/util/build-id.c 297 */;
	u8 *cocci_id/* tools/perf/util/build-id.c 296 */;
	const struct dso *cocci_id/* tools/perf/util/build-id.c 258 */;
	ssize_t cocci_id/* tools/perf/util/build-id.c 198 */;
	char cocci_id/* tools/perf/util/build-id.c 195 */[PATH_MAX];
	unsigned int cocci_id/* tools/perf/util/build-id.c 186 */;
	va_list cocci_id/* tools/perf/util/build-id.c 144 */;
	const char *cocci_id/* tools/perf/util/build-id.c 142 */;
	char **cocci_id/* tools/perf/util/build-id.c 142 */;
	size_t cocci_id/* tools/perf/util/build-id.c 142 */;
	u8 cocci_id/* tools/perf/util/build-id.c 129 */[BUILD_ID_SIZE];
}
