cocci_test_suite() {
	int cocci_id/* tools/perf/util/cs-etm.c 99 */(struct cs_etm_auxtrace *etm,
						      pid_t tid);
	int cocci_id/* tools/perf/util/cs-etm.c 98 */(struct cs_etm_auxtrace *etm);
	struct branch_entry *cocci_id/* tools/perf/util/cs-etm.c 964 */;
	struct cs_etm_packet *cocci_id/* tools/perf/util/cs-etm.c 921 */;
	u8 cocci_id/* tools/perf/util/cs-etm.c 909 */[2];
	struct branch_entry cocci_id/* tools/perf/util/cs-etm.c 883 */;
	size_t cocci_id/* tools/perf/util/cs-etm.c 861 */;
	struct branch_stack *cocci_id/* tools/perf/util/cs-etm.c 859 */;
	struct cs_etm_queue {
		struct cs_etm_auxtrace *etm;
		struct cs_etm_decoder *decoder;
		struct auxtrace_buffer *buffer;
		unsigned int queue_nr;
		u8 pending_timestamp;
		u64 offset;
		const unsigned char *buf;
		size_t buf_len,buf_used;
		struct intlist *traceid_queues_list;
		struct cs_etm_traceid_queue **traceid_queues;
	} cocci_id/* tools/perf/util/cs-etm.c 83 */;
	u64 cocci_id/* tools/perf/util/cs-etm.c 722 */;
	struct cs_etm_traceid_queue {
		u8 trace_chan_id;
		pid_t pid,tid;
		u64 period_instructions;
		size_t last_branch_pos;
		union perf_event *event_buf;
		struct thread *thread;
		struct branch_stack *last_branch;
		struct branch_stack *last_branch_rb;
		struct cs_etm_packet *prev_packet;
		struct cs_etm_packet *packet;
		struct cs_etm_packet_queue packet_queue;
	} cocci_id/* tools/perf/util/cs-etm.c 69 */;
	struct cs_etm_trace_params *cocci_id/* tools/perf/util/cs-etm.c 687 */;
	struct cs_etm_decoder_params cocci_id/* tools/perf/util/cs-etm.c 686 */;
	struct cs_etm_queue *cocci_id/* tools/perf/util/cs-etm.c 684 */;
	struct cs_etm_auxtrace *cocci_id/* tools/perf/util/cs-etm.c 684 */;
	struct addr_location cocci_id/* tools/perf/util/cs-etm.c 646 */;
	struct thread *cocci_id/* tools/perf/util/cs-etm.c 644 */;
	struct machine *cocci_id/* tools/perf/util/cs-etm.c 619 */;
	u8 cocci_id/* tools/perf/util/cs-etm.c 617 */;
	struct auxtrace_queues *cocci_id/* tools/perf/util/cs-etm.c 583 */;
	unsigned int cocci_id/* tools/perf/util/cs-etm.c 579 */;
	uintptr_t cocci_id/* tools/perf/util/cs-etm.c 531 */;
	struct cs_etm_auxtrace cocci_id/* tools/perf/util/cs-etm.c 509 */;
	struct perf_session *cocci_id/* tools/perf/util/cs-etm.c 504 */;
	u8 *cocci_id/* tools/perf/util/cs-etm.c 490 */;
	struct cs_etm_decoder *cocci_id/* tools/perf/util/cs-etm.c 459 */;
	const char *cocci_id/* tools/perf/util/cs-etm.c 456 */;
	struct auxtrace_buffer *cocci_id/* tools/perf/util/cs-etm.c 453 */;
	enum cs_etm_decoder_operation cocci_id/* tools/perf/util/cs-etm.c 432 */;
	struct cs_etm_decoder_params *cocci_id/* tools/perf/util/cs-etm.c 430 */;
	struct cs_etm_auxtrace {
		struct auxtrace auxtrace;
		struct auxtrace_queues queues;
		struct auxtrace_heap heap;
		struct itrace_synth_opts synth_opts;
		struct perf_session *session;
		struct machine *machine;
		struct thread *unknown_thread;
		u8 timeless_decoding;
		u8 snapshot_mode;
		u8 data_queued;
		u8 sample_branches;
		u8 sample_instructions;
		int num_cpu;
		u32 auxtrace_type;
		u64 branches_sample_type;
		u64 branches_id;
		u64 instructions_sample_type;
		u64 instructions_sample_period;
		u64 instructions_id;
		u64 **metadata;
		u64 kernel_start;
		unsigned int pmu_type;
	} cocci_id/* tools/perf/util/cs-etm.c 42 */;
	struct branch_stack cocci_id/* tools/perf/util/cs-etm.c 254 */;
	struct cs_etm_packet cocci_id/* tools/perf/util/cs-etm.c 245 */;
	u64 **cocci_id/* tools/perf/util/cs-etm.c 2412 */;
	struct perf_event_header cocci_id/* tools/perf/util/cs-etm.c 2404 */;
	struct perf_record_auxtrace_info *cocci_id/* tools/perf/util/cs-etm.c 2400 */;
	__u64 *cocci_id/* tools/perf/util/cs-etm.c 2377 */;
	const char *const cocci_id/* tools/perf/util/cs-etm.c 2350 */[];
	struct evlist *cocci_id/* tools/perf/util/cs-etm.c 2335 */;
	struct evsel *cocci_id/* tools/perf/util/cs-etm.c 2334 */;
	off_t cocci_id/* tools/perf/util/cs-etm.c 2304 */;
	intptr_t cocci_id/* tools/perf/util/cs-etm.c 224 */;
	struct intlist *cocci_id/* tools/perf/util/cs-etm.c 221 */;
	struct cs_etm_traceid_queue *cocci_id/* tools/perf/util/cs-etm.c 220 */;
	struct int_node *cocci_id/* tools/perf/util/cs-etm.c 219 */;
	int cocci_id/* tools/perf/util/cs-etm.c 218 */;
	void cocci_id/* tools/perf/util/cs-etm.c 216 */;
	struct cs_etm_packet_queue *cocci_id/* tools/perf/util/cs-etm.c 192 */;
	u16 cocci_id/* tools/perf/util/cs-etm.c 1557 */;
	u64 *cocci_id/* tools/perf/util/cs-etm.c 145 */;
	int *cocci_id/* tools/perf/util/cs-etm.c 142 */;
	struct perf_event_attr cocci_id/* tools/perf/util/cs-etm.c 1264 */;
	struct perf_event_attr *cocci_id/* tools/perf/util/cs-etm.c 1248 */;
	struct cs_etm_synth cocci_id/* tools/perf/util/cs-etm.c 1241 */;
	struct cs_etm_synth *cocci_id/* tools/perf/util/cs-etm.c 1240 */;
	union perf_event *cocci_id/* tools/perf/util/cs-etm.c 1236 */;
	struct perf_tool *cocci_id/* tools/perf/util/cs-etm.c 1235 */;
	struct cs_etm_synth {
		struct perf_tool dummy_tool;
		struct perf_session *session;
	} cocci_id/* tools/perf/util/cs-etm.c 1230 */;
	struct dummy_branch_stack cocci_id/* tools/perf/util/cs-etm.c 1203 */;
	u32 cocci_id/* tools/perf/util/cs-etm.c 118 */;
	struct dummy_branch_stack {
		u64 nr;
		struct branch_entry entries;
	} cocci_id/* tools/perf/util/cs-etm.c 1173 */;
	struct perf_sample cocci_id/* tools/perf/util/cs-etm.c 1171 */;
	void *cocci_id/* tools/perf/util/cs-etm.c 1109 */;
	struct perf_sample *cocci_id/* tools/perf/util/cs-etm.c 1086 */;
	const struct cs_etm_packet *cocci_id/* tools/perf/util/cs-etm.c 1085 */;
	bool cocci_id/* tools/perf/util/cs-etm.c 1078 */;
	pid_t cocci_id/* tools/perf/util/cs-etm.c 1054 */;
	int cocci_id/* tools/perf/util/cs-etm.c 102 */(struct cs_etm_queue *etmq);
	struct auxtrace_queue *cocci_id/* tools/perf/util/cs-etm.c 1005 */;
}
