cocci_test_suite() {
	int cocci_id/* tools/perf/bench/numa.c 969 */[MAX_NR_NODES];
	unsigned int cocci_id/* tools/perf/bench/numa.c 967 */;
	double *cocci_id/* tools/perf/bench/numa.c 965 */;
	int *cocci_id/* tools/perf/bench/numa.c 936 */;
	char cocci_id/* tools/perf/bench/numa.c 877 */[MAX_NR_NODES];
	u32 cocci_id/* tools/perf/bench/numa.c 797 */;
	u64 *cocci_id/* tools/perf/bench/numa.c 750 */;
	const uint32_t cocci_id/* tools/perf/bench/numa.c 740 */;
	struct params {
		bool serialize_startup;
		int nr_proc;
		int nr_threads;
		const char *mb_global_str;
		const char *mb_proc_str;
		const char *mb_proc_locked_str;
		const char *mb_thread_str;
		double mb_global;
		double mb_proc;
		double mb_proc_locked;
		double mb_thread;
		bool data_reads;
		bool data_writes;
		bool data_backwards;
		bool data_zero_memset;
		bool data_rand_walk;
		u32 nr_loops;
		u32 nr_secs;
		u32 sleep_usecs;
		bool init_zero;
		bool init_random;
		bool init_cpu0;
		int show_details;
		int run_all;
		int thp;
		long bytes_global;
		long bytes_process;
		long bytes_process_locked;
		long bytes_thread;
		int nr_tasks;
		bool show_quiet;
		bool show_convergence;
		bool measure_convergence;
		int perturb_secs;
		int nr_cpus;
		int nr_nodes;
		char *cpu_list_str;
		char *node_list_str;
	} cocci_id/* tools/perf/bench/numa.c 74 */;
	uint32_t cocci_id/* tools/perf/bench/numa.c 738 */;
	const struct option *cocci_id/* tools/perf/bench/numa.c 610 */;
	struct thread_data {
		int curr_cpu;
		cpu_set_t bind_cpumask;
		int bind_node;
		u8 *process_data;
		int process_nr;
		int thread_nr;
		int task_nr;
		unsigned int loops_done;
		u64 val;
		u64 runtime_ns;
		u64 system_time_ns;
		u64 user_time_ns;
		double speed_gbs;
		pthread_mutex_t *process_lock;
	} cocci_id/* tools/perf/bench/numa.c 55 */;
	char *cocci_id/* tools/perf/bench/numa.c 494 */;
	pthread_mutexattr_t cocci_id/* tools/perf/bench/numa.c 475 */;
	pthread_mutex_t *cocci_id/* tools/perf/bench/numa.c 473 */;
	unsigned long cocci_id/* tools/perf/bench/numa.c 423 */;
	long cocci_id/* tools/perf/bench/numa.c 414 */;
	void *cocci_id/* tools/perf/bench/numa.c 388 */;
	cpu_set_t cocci_id/* tools/perf/bench/numa.c 370 */;
	u8 *cocci_id/* tools/perf/bench/numa.c 367 */;
	ssize_t cocci_id/* tools/perf/bench/numa.c 367 */;
	char cocci_id/* tools/perf/bench/numa.c 361 */[20];
	struct bitmask *cocci_id/* tools/perf/bench/numa.c 250 */;
	bool cocci_id/* tools/perf/bench/numa.c 248 */;
	const char *const cocci_id/* tools/perf/bench/numa.c 212 */[];
	const char **cocci_id/* tools/perf/bench/numa.c 1825 */;
	void cocci_id/* tools/perf/bench/numa.c 1807 */;
	const char *cocci_id/* tools/perf/bench/numa.c 1734 */[][MAX_ARGS];
	const struct option cocci_id/* tools/perf/bench/numa.c 168 */[];
	struct params *cocci_id/* tools/perf/bench/numa.c 1673 */;
	struct params cocci_id/* tools/perf/bench/numa.c 166 */;
	struct thread_data *cocci_id/* tools/perf/bench/numa.c 1634 */;
	char cocci_id/* tools/perf/bench/numa.c 1633 */[14 + 2 * 10 + 1];
	int cocci_id/* tools/perf/bench/numa.c 163 */(const struct option *opt,
						      const char *arg,
						      int unset);
	struct global_info *cocci_id/* tools/perf/bench/numa.c 161 */;
	double cocci_id/* tools/perf/bench/numa.c 1490 */;
	pid_t *cocci_id/* tools/perf/bench/numa.c 1489 */;
	u64 cocci_id/* tools/perf/bench/numa.c 1488 */;
	struct timeval cocci_id/* tools/perf/bench/numa.c 1487 */;
	const char *cocci_id/* tools/perf/bench/numa.c 1485 */;
	int cocci_id/* tools/perf/bench/numa.c 1485 */;
	struct global_info {
		u8 *data;
		pthread_mutex_t startup_mutex;
		int nr_tasks_started;
		pthread_mutex_t startup_done_mutex;
		pthread_mutex_t start_work_mutex;
		int nr_tasks_working;
		pthread_mutex_t stop_work_mutex;
		u64 bytes_done;
		struct thread_data *threads;
		bool all_converged;
		bool stop_work;
		int print_once;
		struct params p;
	} cocci_id/* tools/perf/bench/numa.c 136 */;
	pthread_t cocci_id/* tools/perf/bench/numa.c 1306 */;
	pthread_t *cocci_id/* tools/perf/bench/numa.c 1287 */;
	pthread_mutex_t cocci_id/* tools/perf/bench/numa.c 1285 */;
	struct rusage cocci_id/* tools/perf/bench/numa.c 1109 */;
}
