cocci_test_suite() {
	struct audit_entry cocci_id/* kernel/auditfilter.c 99 */;
	struct rcu_head *cocci_id/* kernel/auditfilter.c 97 */;
	struct list_head *cocci_id/* kernel/auditfilter.c 928 */;
	struct audit_tree *cocci_id/* kernel/auditfilter.c 927 */;
	struct audit_watch *cocci_id/* kernel/auditfilter.c 926 */;
	struct audit_entry *cocci_id/* kernel/auditfilter.c 923 */;
	int cocci_id/* kernel/auditfilter.c 923 */;
	u64 cocci_id/* kernel/auditfilter.c 920 */;
	struct list_head **cocci_id/* kernel/auditfilter.c 885 */;
	struct audit_field cocci_id/* kernel/auditfilter.c 836 */;
	struct audit_krule *cocci_id/* kernel/auditfilter.c 689 */;
	void cocci_id/* kernel/auditfilter.c 63 */;
	void **cocci_id/* kernel/auditfilter.c 520 */;
	struct audit_field *cocci_id/* kernel/auditfilter.c 458 */;
	struct audit_fsnotify_mark *cocci_id/* kernel/auditfilter.c 450 */;
	char *cocci_id/* kernel/auditfilter.c 449 */;
	struct audit_rule_data cocci_id/* kernel/auditfilter.c 447 */;
	void *cocci_id/* kernel/auditfilter.c 446 */;
	size_t cocci_id/* kernel/auditfilter.c 442 */;
	struct audit_rule_data *cocci_id/* kernel/auditfilter.c 441 */;
	struct list_head cocci_id/* kernel/auditfilter.c 39 */[AUDIT_NR_FILTERS];
	u32 cocci_id/* kernel/auditfilter.c 302 */[];
	u32 *cocci_id/* kernel/auditfilter.c 196 */;
	unsigned cocci_id/* kernel/auditfilter.c 186 */;
	__u32 cocci_id/* kernel/auditfilter.c 167 */;
	__u32 *cocci_id/* kernel/auditfilter.c 167 */;
	unsigned *cocci_id/* kernel/auditfilter.c 165 */;
	int __init cocci_id/* kernel/auditfilter.c 165 */;
	__u32 *cocci_id/* kernel/auditfilter.c 163 */[AUDIT_SYSCALL_CLASSES];
	pid_t cocci_id/* kernel/auditfilter.c 1326 */;
	unsigned int cocci_id/* kernel/auditfilter.c 1315 */;
	const struct qstr *cocci_id/* kernel/auditfilter.c 1296 */;
	const char *cocci_id/* kernel/auditfilter.c 1296 */;
	size_t *cocci_id/* kernel/auditfilter.c 125 */;
	kgid_t cocci_id/* kernel/auditfilter.c 1236 */;
	kuid_t cocci_id/* kernel/auditfilter.c 1214 */;
	u32 cocci_id/* kernel/auditfilter.c 1190 */;
	struct audit_netlink_list cocci_id/* kernel/auditfilter.c 1169 */;
	struct audit_netlink_list *cocci_id/* kernel/auditfilter.c 1160 */;
	struct task_struct *cocci_id/* kernel/auditfilter.c 1159 */;
	struct net *cocci_id/* kernel/auditfilter.c 1158 */;
	struct audit_buffer *cocci_id/* kernel/auditfilter.c 1093 */;
	struct sk_buff *cocci_id/* kernel/auditfilter.c 1064 */;
	struct sk_buff_head *cocci_id/* kernel/auditfilter.c 1062 */;
}
