cocci_test_suite() {
	const unsigned int cocci_id/* tools/bpf/bpftool/prog.c 918 */;
	struct bpf_prog_test_run_attr cocci_id/* tools/bpf/bpftool/prog.c 917 */;
	void **cocci_id/* tools/bpf/bpftool/prog.c 901 */;
	unsigned int cocci_id/* tools/bpf/bpftool/prog.c 901 */;
	int cocci_id/* tools/bpf/bpftool/prog.c 901 */;
	struct bpf_prog_info cocci_id/* tools/bpf/bpftool/prog.c 87 */;
	uint8_t *cocci_id/* tools/bpf/bpftool/prog.c 846 */;
	char cocci_id/* tools/bpf/bpftool/prog.c 838 */;
	void cocci_id/* tools/bpf/bpftool/prog.c 835 */;
	FILE *cocci_id/* tools/bpf/bpftool/prog.c 771 */;
	size_t cocci_id/* tools/bpf/bpftool/prog.c 767 */;
	unsigned int *cocci_id/* tools/bpf/bpftool/prog.c 765 */;
	char *cocci_id/* tools/bpf/bpftool/prog.c 754 */;
	enum bpf_attach_type cocci_id/* tools/bpf/bpftool/prog.c 712 */;
	char **cocci_id/* tools/bpf/bpftool/prog.c 710 */;
	enum bpf_attach_type *cocci_id/* tools/bpf/bpftool/prog.c 678 */;
	int *cocci_id/* tools/bpf/bpftool/prog.c 677 */;
	const struct map_replace *cocci_id/* tools/bpf/bpftool/prog.c 672 */;
	const void *cocci_id/* tools/bpf/bpftool/prog.c 670 */;
	struct map_replace {
		int idx;
		int fd;
		char *name;
	} cocci_id/* tools/bpf/bpftool/prog.c 664 */;
	__u32 *cocci_id/* tools/bpf/bpftool/prog.c 560 */;
	__u64 *cocci_id/* tools/bpf/bpftool/prog.c 559 */;
	char cocci_id/* tools/bpf/bpftool/prog.c 557 */[SYM_MAX_NAME];
	struct bpf_func_info *cocci_id/* tools/bpf/bpftool/prog.c 556 */;
	struct kernel_sym *cocci_id/* tools/bpf/bpftool/prog.c 555 */;
	struct tm cocci_id/* tools/bpf/bpftool/prog.c 53 */;
	time_t cocci_id/* tools/bpf/bpftool/prog.c 52 */;
	struct timespec cocci_id/* tools/bpf/bpftool/prog.c 51 */;
	ssize_t cocci_id/* tools/bpf/bpftool/prog.c 429 */;
	__u64 cocci_id/* tools/bpf/bpftool/prog.c 428 */;
	__u32 cocci_id/* tools/bpf/bpftool/prog.c 427 */;
	unsigned char *cocci_id/* tools/bpf/bpftool/prog.c 425 */;
	char cocci_id/* tools/bpf/bpftool/prog.c 424 */[1024];
	bool cocci_id/* tools/bpf/bpftool/prog.c 422 */;
	struct btf *cocci_id/* tools/bpf/bpftool/prog.c 420 */;
	void *cocci_id/* tools/bpf/bpftool/prog.c 419 */;
	struct dump_data cocci_id/* tools/bpf/bpftool/prog.c 418 */;
	struct bpf_prog_info *cocci_id/* tools/bpf/bpftool/prog.c 417 */;
	const char *cocci_id/* tools/bpf/bpftool/prog.c 416 */;
	enum{DUMP_JITED, DUMP_XLATED,} cocci_id/* tools/bpf/bpftool/prog.c 415 */;
	struct bpf_prog_linfo *cocci_id/* tools/bpf/bpftool/prog.c 414 */;
	struct bpf_prog_info_linear *cocci_id/* tools/bpf/bpftool/prog.c 413 */;
	const char *const cocci_id/* tools/bpf/bpftool/prog.c 28 */[];
	struct pinned_obj *cocci_id/* tools/bpf/bpftool/prog.c 257 */;
	char cocci_id/* tools/bpf/bpftool/prog.c 226 */[32];
	__u32 cocci_id/* tools/bpf/bpftool/prog.c 172 */[num_maps];
	u32 cocci_id/* tools/bpf/bpftool/prog.c 168 */;
	const struct cmd cocci_id/* tools/bpf/bpftool/prog.c 1436 */[];
	unsigned char cocci_id/* tools/bpf/bpftool/prog.c 140 */[BPF_TAG_SIZE];
	char ***cocci_id/* tools/bpf/bpftool/prog.c 118 */;
	struct bpf_map *cocci_id/* tools/bpf/bpftool/prog.c 1105 */;
	struct bpf_object *cocci_id/* tools/bpf/bpftool/prog.c 1104 */;
	struct bpf_program *cocci_id/* tools/bpf/bpftool/prog.c 1101 */;
	struct map_replace *cocci_id/* tools/bpf/bpftool/prog.c 1100 */;
	struct bpf_object_load_attr cocci_id/* tools/bpf/bpftool/prog.c 1098 */;
	enum bpf_prog_type cocci_id/* tools/bpf/bpftool/prog.c 1094 */;
}
