cocci_test_suite() {
	struct dma_buf *cocci_id/* samples/vfio-mdev/mbochs.c 994 */;
	struct mbochs_dmabuf cocci_id/* samples/vfio-mdev/mbochs.c 925 */;
	struct dma_buf_ops cocci_id/* samples/vfio-mdev/mbochs.c 908 */;
	enum dma_data_direction cocci_id/* samples/vfio-mdev/mbochs.c 835 */;
	struct sg_table *cocci_id/* samples/vfio-mdev/mbochs.c 834 */;
	struct dma_buf_attachment *cocci_id/* samples/vfio-mdev/mbochs.c 834 */;
	const char *cocci_id/* samples/vfio-mdev/mbochs.c 819 */;
	const struct vm_operations_struct cocci_id/* samples/vfio-mdev/mbochs.c 799 */;
	struct vm_area_struct *cocci_id/* samples/vfio-mdev/mbochs.c 788 */;
	vm_fault_t cocci_id/* samples/vfio-mdev/mbochs.c 786 */;
	struct vm_fault *cocci_id/* samples/vfio-mdev/mbochs.c 786 */;
	pgoff_t cocci_id/* samples/vfio-mdev/mbochs.c 701 */;
	struct page *cocci_id/* samples/vfio-mdev/mbochs.c 700 */;
	struct mdev_state *cocci_id/* samples/vfio-mdev/mbochs.c 700 */;
	const char __user *cocci_id/* samples/vfio-mdev/mbochs.c 643 */;
	u8 cocci_id/* samples/vfio-mdev/mbochs.c 618 */;
	loff_t *cocci_id/* samples/vfio-mdev/mbochs.c 585 */;
	size_t cocci_id/* samples/vfio-mdev/mbochs.c 585 */;
	char __user *cocci_id/* samples/vfio-mdev/mbochs.c 584 */;
	struct mdev_state cocci_id/* samples/vfio-mdev/mbochs.c 530 */;
	loff_t cocci_id/* samples/vfio-mdev/mbochs.c 439 */;
	u32 cocci_id/* samples/vfio-mdev/mbochs.c 428 */;
	bool cocci_id/* samples/vfio-mdev/mbochs.c 428 */;
	u16 cocci_id/* samples/vfio-mdev/mbochs.c 427 */;
	void cocci_id/* samples/vfio-mdev/mbochs.c 427 */;
	struct vfio_region_gfx_edid cocci_id/* samples/vfio-mdev/mbochs.c 414 */;
	void *cocci_id/* samples/vfio-mdev/mbochs.c 403 */;
	u16 *cocci_id/* samples/vfio-mdev/mbochs.c 389 */;
	struct vfio_region_gfx_edid *cocci_id/* samples/vfio-mdev/mbochs.c 367 */;
	u32 *cocci_id/* samples/vfio-mdev/mbochs.c 315 */;
	struct mbochs_mode cocci_id/* samples/vfio-mdev/mbochs.c 302 */;
	u64 cocci_id/* samples/vfio-mdev/mbochs.c 277 */;
	struct mbochs_mode *cocci_id/* samples/vfio-mdev/mbochs.c 248 */;
	struct page *cocci_id/* samples/vfio-mdev/mbochs.c 203 */(struct mdev_state *mdev_state,
								  pgoff_t pgoff);
	const char *cocci_id/* samples/vfio-mdev/mbochs.c 182 */[VBE_DISPI_INDEX_COUNT];
	struct mdev_state {
		u8 *vconfig;
		u64 bar_mask[3];
		u32 memory_bar_mask;
		struct mutex ops_lock;
		struct mdev_device *mdev;
		const struct mbochs_type *type;
		u16 vbe[VBE_DISPI_INDEX_COUNT];
		u64 memsize;
		struct page **pages;
		pgoff_t pagecount;
		struct vfio_region_gfx_edid edid_regs;
		u8 edid_blob[0x400];
		struct list_head dmabufs;
		u32 active_id;
		u32 next_id;
	} cocci_id/* samples/vfio-mdev/mbochs.c 162 */;
	struct mbochs_dmabuf {
		struct mbochs_mode mode;
		u32 id;
		struct page **pages;
		pgoff_t pagecount;
		struct dma_buf *buf;
		struct mdev_state *mdev_state;
		struct list_head next;
		bool unlinked;
	} cocci_id/* samples/vfio-mdev/mbochs.c 150 */;
	void __exit cocci_id/* samples/vfio-mdev/mbochs.c 1487 */;
	int __init cocci_id/* samples/vfio-mdev/mbochs.c 1444 */;
	const struct file_operations cocci_id/* samples/vfio-mdev/mbochs.c 1435 */;
	const struct mdev_parent_ops cocci_id/* samples/vfio-mdev/mbochs.c 1421 */;
	struct attribute_group *cocci_id/* samples/vfio-mdev/mbochs.c 1414 */[];
	struct attribute_group cocci_id/* samples/vfio-mdev/mbochs.c 1399 */;
	struct mbochs_mode {
		u32 drm_format;
		u32 bytepp;
		u32 width;
		u32 height;
		u32 stride;
		u32 __pad;
		u64 offset;
		u64 size;
	} cocci_id/* samples/vfio-mdev/mbochs.c 139 */;
	int cocci_id/* samples/vfio-mdev/mbochs.c 1378 */;
	const struct mbochs_type *cocci_id/* samples/vfio-mdev/mbochs.c 1377 */;
	struct kobject *cocci_id/* samples/vfio-mdev/mbochs.c 1375 */;
	struct device *cocci_id/* samples/vfio-mdev/mbochs.c 1375 */;
	char *cocci_id/* samples/vfio-mdev/mbochs.c 1375 */;
	ssize_t cocci_id/* samples/vfio-mdev/mbochs.c 1374 */;
	const struct attribute_group *cocci_id/* samples/vfio-mdev/mbochs.c 1352 */[];
	const struct attribute_group cocci_id/* samples/vfio-mdev/mbochs.c 1347 */;
	struct attribute *cocci_id/* samples/vfio-mdev/mbochs.c 1342 */[];
	struct vfio_region_info_ext {
		struct vfio_region_info base;
		struct vfio_region_info_cap_type type;
	} cocci_id/* samples/vfio-mdev/mbochs.c 134 */;
	struct device_attribute *cocci_id/* samples/vfio-mdev/mbochs.c 1332 */;
	struct mbochs_dmabuf *cocci_id/* samples/vfio-mdev/mbochs.c 1312 */;
	struct device cocci_id/* samples/vfio-mdev/mbochs.c 131 */;
	struct mdev_device *cocci_id/* samples/vfio-mdev/mbochs.c 1309 */;
	struct cdev cocci_id/* samples/vfio-mdev/mbochs.c 130 */;
	struct class *cocci_id/* samples/vfio-mdev/mbochs.c 129 */;
	__u32 __user *cocci_id/* samples/vfio-mdev/mbochs.c 1286 */;
	dev_t cocci_id/* samples/vfio-mdev/mbochs.c 128 */;
	struct vfio_device_gfx_plane_info cocci_id/* samples/vfio-mdev/mbochs.c 1261 */;
	struct vfio_irq_info cocci_id/* samples/vfio-mdev/mbochs.c 1238 */;
	typeof(info) cocci_id/* samples/vfio-mdev/mbochs.c 1215 */;
	struct vfio_region_info_ext cocci_id/* samples/vfio-mdev/mbochs.c 1213 */;
	void __user *cocci_id/* samples/vfio-mdev/mbochs.c 1196 */;
	struct vfio_device_info cocci_id/* samples/vfio-mdev/mbochs.c 1192 */;
	unsigned long cocci_id/* samples/vfio-mdev/mbochs.c 1184 */;
	unsigned int cocci_id/* samples/vfio-mdev/mbochs.c 1183 */;
	long cocci_id/* samples/vfio-mdev/mbochs.c 1183 */;
	struct vfio_device_gfx_plane_info *cocci_id/* samples/vfio-mdev/mbochs.c 1093 */;
	struct vfio_device_info *cocci_id/* samples/vfio-mdev/mbochs.c 1084 */;
	struct vfio_irq_info *cocci_id/* samples/vfio-mdev/mbochs.c 1077 */;
	typeof(*ext) cocci_id/* samples/vfio-mdev/mbochs.c 1060 */;
	const struct mbochs_type {
		const char *name;
		u32 mbytes;
		u32 max_x;
		u32 max_y;
	} cocci_id/* samples/vfio-mdev/mbochs.c 103 */[];
	struct vfio_region_info *cocci_id/* samples/vfio-mdev/mbochs.c 1023 */;
	struct vfio_region_info_ext *cocci_id/* samples/vfio-mdev/mbochs.c 1021 */;
}
