cocci_test_suite() {
	u32 cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 87 */;
	struct i2c_timings *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 86 */;
	struct dw_i2c_dev *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 85 */;
	struct platform_device *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 83 */;
	int cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 83 */;
	u16 cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 75 */;
	const union acpi_object *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 73 */;
	union acpi_object *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 63 */;
	acpi_handle cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 62 */;
	struct acpi_buffer cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 61 */;
	u32 *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 59 */;
	u16 *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 59 */;
	char cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 58 */[];
	void cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 58 */;
	void __exit cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 515 */;
	int __init cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 509 */;
	struct platform_driver cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 498 */;
	const struct dmi_system_id cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 47 */[];
	struct device *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 438 */;
	u64 cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 354 */;
	uintptr_t cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 315 */;
	struct dw_i2c_dev cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 268 */;
	const int cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 260 */[];
	struct i2c_adapter *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 254 */;
	struct dw_i2c_platform_data *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 253 */;
	void *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 177 */;
	const struct of_device_id cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 175 */[];
	struct resource *cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 159 */;
	const struct acpi_device_id cocci_id/* drivers/i2c/busses/i2c-designware-platdrv.c 120 */[];
}
