cocci_test_suite() {
	struct jfs_inode_info cocci_id/* fs/jfs/super.c 941 */;
	int __init cocci_id/* fs/jfs/super.c 935 */;
	struct jfs_inode_info *cocci_id/* fs/jfs/super.c 923 */;
	void *cocci_id/* fs/jfs/super.c 921 */;
	va_list cocci_id/* fs/jfs/super.c 86 */;
	struct va_format cocci_id/* fs/jfs/super.c 85 */;
	const struct path *cocci_id/* fs/jfs/super.c 841 */;
	struct dquot **cocci_id/* fs/jfs/super.c 835 */;
	struct buffer_head *cocci_id/* fs/jfs/super.c 745 */;
	struct buffer_head cocci_id/* fs/jfs/super.c 744 */;
	sector_t cocci_id/* fs/jfs/super.c 739 */;
	size_t cocci_id/* fs/jfs/super.c 736 */;
	ssize_t cocci_id/* fs/jfs/super.c 735 */;
	struct seq_file *cocci_id/* fs/jfs/super.c 697 */;
	const char *cocci_id/* fs/jfs/super.c 674 */;
	struct file_system_type *cocci_id/* fs/jfs/super.c 673 */;
	struct dentry *cocci_id/* fs/jfs/super.c 673 */;
	struct jfs_log *cocci_id/* fs/jfs/super.c 625 */;
	loff_t cocci_id/* fs/jfs/super.c 598 */;
	struct task_struct *cocci_id/* fs/jfs/super.c 53 */;
	struct task_struct *cocci_id/* fs/jfs/super.c 52 */[MAX_COMMIT_THREADS];
	char *cocci_id/* fs/jfs/super.c 516 */;
	struct jfs_sb_info cocci_id/* fs/jfs/super.c 500 */;
	s64 cocci_id/* fs/jfs/super.c 495 */;
	struct jfs_sb_info *cocci_id/* fs/jfs/super.c 492 */;
	int cocci_id/* fs/jfs/super.c 48 */;
	struct file_system_type cocci_id/* fs/jfs/super.c 45 */;
	const struct export_operations cocci_id/* fs/jfs/super.c 44 */;
	int *cocci_id/* fs/jfs/super.c 430 */;
	const struct super_operations cocci_id/* fs/jfs/super.c 43 */;
	struct kmem_cache *cocci_id/* fs/jfs/super.c 41 */;
	struct request_queue *cocci_id/* fs/jfs/super.c 377 */;
	gid_t cocci_id/* fs/jfs/super.c 350 */;
	uid_t cocci_id/* fs/jfs/super.c 336 */;
	substring_t cocci_id/* fs/jfs/super.c 246 */[MAX_OPT_ARGS];
	s64 *cocci_id/* fs/jfs/super.c 233 */;
	const match_table_t cocci_id/* fs/jfs/super.c 213 */;
	enum{Opt_integrity, Opt_nointegrity, Opt_iocharset, Opt_resize, Opt_resize_nosize, Opt_errors, Opt_ignore, Opt_err, Opt_quota, Opt_usrquota, Opt_grpquota, Opt_uid, Opt_gid, Opt_umask, Opt_discard, Opt_nodiscard, Opt_discard_minblk,} cocci_id/* fs/jfs/super.c 206 */;
	const struct quotactl_ops cocci_id/* fs/jfs/super.c 169 */;
	int cocci_id/* fs/jfs/super.c 158 */(struct super_block *sb, int type,
					     int format_id,
					     const struct path *path);
	int cocci_id/* fs/jfs/super.c 157 */(struct super_block *sb, int type);
	struct inomap *cocci_id/* fs/jfs/super.c 123 */;
	struct kstatfs *cocci_id/* fs/jfs/super.c 119 */;
	void __exit cocci_id/* fs/jfs/super.c 1024 */;
	void cocci_id/* fs/jfs/super.c 1024 */;
	struct super_block *cocci_id/* fs/jfs/super.c 101 */;
	struct inode *cocci_id/* fs/jfs/super.c 101 */;
}
