cocci_test_suite() {
	tid_t cocci_id/* fs/jfs/inode.c 76 */;
	struct inode *cocci_id/* fs/jfs/inode.c 73 */;
	int cocci_id/* fs/jfs/inode.c 73 */;
	ulong cocci_id/* fs/jfs/inode.c 416 */;
	const struct address_space_operations cocci_id/* fs/jfs/inode.c 359 */;
	loff_t cocci_id/* fs/jfs/inode.c 349 */;
	size_t cocci_id/* fs/jfs/inode.c 339 */;
	struct file *cocci_id/* fs/jfs/inode.c 336 */;
	struct kiocb *cocci_id/* fs/jfs/inode.c 334 */;
	struct iov_iter *cocci_id/* fs/jfs/inode.c 334 */;
	ssize_t cocci_id/* fs/jfs/inode.c 334 */;
	sector_t cocci_id/* fs/jfs/inode.c 329 */;
	struct address_space *cocci_id/* fs/jfs/inode.c 329 */;
	struct page **cocci_id/* fs/jfs/inode.c 317 */;
	void **cocci_id/* fs/jfs/inode.c 317 */;
	struct list_head *cocci_id/* fs/jfs/inode.c 300 */;
	unsigned cocci_id/* fs/jfs/inode.c 300 */;
	struct page *cocci_id/* fs/jfs/inode.c 294 */;
	struct super_block *cocci_id/* fs/jfs/inode.c 24 */;
	unsigned long cocci_id/* fs/jfs/inode.c 24 */;
	s32 cocci_id/* fs/jfs/inode.c 205 */;
	xad_t cocci_id/* fs/jfs/inode.c 202 */;
	s64 cocci_id/* fs/jfs/inode.c 200 */;
	struct buffer_head *cocci_id/* fs/jfs/inode.c 198 */;
	void cocci_id/* fs/jfs/inode.c 178 */;
	struct bmap *cocci_id/* fs/jfs/inode.c 171 */;
	struct jfs_inode_info *cocci_id/* fs/jfs/inode.c 141 */;
	struct writeback_control *cocci_id/* fs/jfs/inode.c 115 */;
}
