cocci_test_suite() {
	struct erofs_inode cocci_id/* fs/erofs/super.c 90 */;
	struct erofs_inode *cocci_id/* fs/erofs/super.c 83 */;
	struct inode *cocci_id/* fs/erofs/super.c 81 */;
	const struct super_operations cocci_id/* fs/erofs/super.c 629 */;
	int *cocci_id/* fs/erofs/super.c 606 */;
	struct seq_file *cocci_id/* fs/erofs/super.c 578 */;
	u32 cocci_id/* fs/erofs/super.c 573 */;
	u64 cocci_id/* fs/erofs/super.c 561 */;
	struct kstatfs *cocci_id/* fs/erofs/super.c 557 */;
	void __exit cocci_id/* fs/erofs/super.c 545 */;
	int __init cocci_id/* fs/erofs/super.c 506 */;
	struct file_system_type cocci_id/* fs/erofs/super.c 497 */;
	struct file_system_type *cocci_id/* fs/erofs/super.c 458 */;
	struct dentry *cocci_id/* fs/erofs/super.c 458 */;
	char *cocci_id/* fs/erofs/super.c 454 */;
	void *cocci_id/* fs/erofs/super.c 384 */;
	struct inode *const cocci_id/* fs/erofs/super.c 366 */;
	struct erofs_sb_info *const cocci_id/* fs/erofs/super.c 365 */;
	unsigned int cocci_id/* fs/erofs/super.c 343 */;
	struct page *cocci_id/* fs/erofs/super.c 342 */;
	struct address_space *const cocci_id/* fs/erofs/super.c 331 */;
	gfp_t cocci_id/* fs/erofs/super.c 328 */;
	const struct address_space_operations cocci_id/* fs/erofs/super.c 326 */;
	substring_t cocci_id/* fs/erofs/super.c 265 */[MAX_OPT_ARGS];
	match_table_t cocci_id/* fs/erofs/super.c 254 */;
	enum{Opt_user_xattr, Opt_nouser_xattr, Opt_acl, Opt_noacl, Opt_cache_strategy, Opt_err,} cocci_id/* fs/erofs/super.c 245 */;
	va_list cocci_id/* fs/erofs/super.c 24 */;
	struct va_format cocci_id/* fs/erofs/super.c 23 */;
	const char *cocci_id/* fs/erofs/super.c 20 */;
	struct super_block *cocci_id/* fs/erofs/super.c 20 */;
	void cocci_id/* fs/erofs/super.c 20 */;
	struct erofs_sb_info *cocci_id/* fs/erofs/super.c 199 */;
	substring_t *cocci_id/* fs/erofs/super.c 197 */;
	int cocci_id/* fs/erofs/super.c 196 */;
	struct kmem_cache *cocci_id/* fs/erofs/super.c 18 */;
	struct erofs_inode_compact cocci_id/* fs/erofs/super.c 172 */;
	const unsigned int cocci_id/* fs/erofs/super.c 109 */;
	struct erofs_super_block *cocci_id/* fs/erofs/super.c 107 */;
	bool cocci_id/* fs/erofs/super.c 106 */;
}
