cocci_test_suite() {
	loff_t cocci_id/* fs/nfs/dir.c 939 */;
	long long cocci_id/* fs/nfs/dir.c 842 */;
	nfs_readdir_descriptor_t cocci_id/* fs/nfs/dir.c 836 */;
	struct dir_context *cocci_id/* fs/nfs/dir.c 832 */;
	unsigned long long cocci_id/* fs/nfs/dir.c 775 */;
	struct nfs_cache_array_entry *cocci_id/* fs/nfs/dir.c 753 */;
	struct nfs_cache_array *cocci_id/* fs/nfs/dir.c 748 */;
	const struct cred *cocci_id/* fs/nfs/dir.c 71 */;
	struct nfs_open_dir_context *cocci_id/* fs/nfs/dir.c 71 */;
	struct page *cocci_id/* fs/nfs/dir.c 699 */;
	nfs_readdir_descriptor_t *cocci_id/* fs/nfs/dir.c 690 */;
	const struct address_space_operations cocci_id/* fs/nfs/dir.c 67 */;
	void *cocci_id/* fs/nfs/dir.c 667 */;
	struct nfs_cache_array cocci_id/* fs/nfs/dir.c 629 */;
	struct nfs_entry cocci_id/* fs/nfs/dir.c 607 */;
	struct page *cocci_id/* fs/nfs/dir.c 606 */[NFS_MAX_READDIR_PAGES];
	struct page **cocci_id/* fs/nfs/dir.c 586 */;
	const struct file_operations cocci_id/* fs/nfs/dir.c 58 */;
	void cocci_id/* fs/nfs/dir.c 56 */(struct page *);
	loff_t cocci_id/* fs/nfs/dir.c 55 */(struct file *, loff_t, int);
	int cocci_id/* fs/nfs/dir.c 54 */(struct file *, loff_t, loff_t, int);
	int cocci_id/* fs/nfs/dir.c 53 */(struct file *, struct dir_context *);
	struct xdr_buf cocci_id/* fs/nfs/dir.c 527 */;
	struct xdr_stream cocci_id/* fs/nfs/dir.c 526 */;
	int cocci_id/* fs/nfs/dir.c 52 */(struct inode *, struct file *);
	struct qstr cocci_id/* fs/nfs/dir.c 447 */;
	struct nfs_entry *cocci_id/* fs/nfs/dir.c 445 */;
	struct xdr_stream *cocci_id/* fs/nfs/dir.c 363 */;
	umode_t cocci_id/* fs/nfs/dir.c 2448 */;
	u32 cocci_id/* fs/nfs/dir.c 2448 */;
	struct rb_node **cocci_id/* fs/nfs/dir.c 2374 */;
	bool cocci_id/* fs/nfs/dir.c 2297 */;
	struct nfs_access_entry cocci_id/* fs/nfs/dir.c 2252 */;
	struct nfs_access_entry *cocci_id/* fs/nfs/dir.c 2248 */;
	struct rb_node *cocci_id/* fs/nfs/dir.c 2247 */;
	struct rb_root *cocci_id/* fs/nfs/dir.c 2246 */;
	struct nfs_inode *cocci_id/* fs/nfs/dir.c 2244 */;
	struct list_head *cocci_id/* fs/nfs/dir.c 2244 */;
	void cocci_id/* fs/nfs/dir.c 2244 */;
	long cocci_id/* fs/nfs/dir.c 2231 */;
	struct shrinker *cocci_id/* fs/nfs/dir.c 2223 */;
	struct shrink_control *cocci_id/* fs/nfs/dir.c 2223 */;
	unsigned long cocci_id/* fs/nfs/dir.c 2222 */;
	gfp_t cocci_id/* fs/nfs/dir.c 2214 */;
	atomic_long_t cocci_id/* fs/nfs/dir.c 2144 */;
	char *cocci_id/* fs/nfs/dir.c 212 */;
	struct nfs_renamedata *cocci_id/* fs/nfs/dir.c 2100 */;
	struct rpc_task *cocci_id/* fs/nfs/dir.c 2045 */;
	const char *cocci_id/* fs/nfs/dir.c 186 */;
	struct qstr *cocci_id/* fs/nfs/dir.c 186 */;
	dev_t cocci_id/* fs/nfs/dir.c 1764 */;
	struct nfs_server *cocci_id/* fs/nfs/dir.c 1692 */;
	struct nfs4_label *cocci_id/* fs/nfs/dir.c 1675 */;
	struct nfs_fattr *cocci_id/* fs/nfs/dir.c 1674 */;
	struct nfs_fh *cocci_id/* fs/nfs/dir.c 1673 */;
	struct iattr cocci_id/* fs/nfs/dir.c 1502 */;
	unsigned cocci_id/* fs/nfs/dir.c 1496 */;
	struct {
		struct file *file;
		struct page *page;
		struct dir_context *ctx;
		unsigned long page_index;
		u64 *dir_cookie;
		u64 last_cookie;
		loff_t current_index;
		decode_dirent_t decode;
		unsigned long timestamp;
		unsigned long gencount;
		unsigned int cache_entry_index;
		bool plus;
		bool eof;
	} cocci_id/* fs/nfs/dir.c 148 */;
	int (*cocci_id/* fs/nfs/dir.c 147 */)(struct xdr_stream *,
					      struct nfs_entry *, bool);
	struct nfs_open_context *cocci_id/* fs/nfs/dir.c 1467 */;
	struct file *cocci_id/* fs/nfs/dir.c 1467 */;
	fmode_t cocci_id/* fs/nfs/dir.c 1457 */;
	const struct dentry_operations cocci_id/* fs/nfs/dir.c 1447 */;
	int cocci_id/* fs/nfs/dir.c 1445 */(struct dentry *, unsigned int);
	struct nfs_cache_array {
		int size;
		int eof_index;
		u64 last_cookie;
		struct nfs_cache_array_entry array[0];
	} cocci_id/* fs/nfs/dir.c 140 */;
	struct nfs_cache_array_entry {
		u64 cookie;
		u64 ino;
		struct qstr string;
		unsigned char d_type;
	} cocci_id/* fs/nfs/dir.c 133 */;
	const struct dentry *cocci_id/* fs/nfs/dir.c 1303 */;
	struct inode *cocci_id/* fs/nfs/dir.c 1239 */;
	int (*cocci_id/* fs/nfs/dir.c 1236 */)(struct inode *,
					       struct dentry *, unsigned int);
	struct dentry *cocci_id/* fs/nfs/dir.c 1235 */;
	unsigned int cocci_id/* fs/nfs/dir.c 1235 */;
	int cocci_id/* fs/nfs/dir.c 1234 */;
}
