cocci_test_suite() {
	struct file_lock_context *cocci_id/* fs/nfs/pagelist.c 930 */;
	size_t cocci_id/* fs/nfs/pagelist.c 929 */;
	const struct nfs_lock_context *cocci_id/* fs/nfs/pagelist.c 907 */;
	struct nfs_pgio_header *cocci_id/* fs/nfs/pagelist.c 821 */;
	gfp_t cocci_id/* fs/nfs/pagelist.c 770 */;
	struct nfs_page_array *cocci_id/* fs/nfs/pagelist.c 768 */;
	struct nfs_commit_info cocci_id/* fs/nfs/pagelist.c 767 */;
	struct list_head *cocci_id/* fs/nfs/pagelist.c 766 */;
	struct page **cocci_id/* fs/nfs/pagelist.c 764 */;
	const struct nfs_rw_ops *cocci_id/* fs/nfs/pagelist.c 704 */;
	const struct nfs_pgio_completion_ops *cocci_id/* fs/nfs/pagelist.c 703 */;
	const struct nfs_pageio_ops *cocci_id/* fs/nfs/pagelist.c 702 */;
	loff_t cocci_id/* fs/nfs/pagelist.c 65 */;
	unsigned long long cocci_id/* fs/nfs/pagelist.c 639 */;
	struct rpc_task_setup cocci_id/* fs/nfs/pagelist.c 623 */;
	struct rpc_message cocci_id/* fs/nfs/pagelist.c 618 */;
	const struct rpc_call_ops *cocci_id/* fs/nfs/pagelist.c 615 */;
	const struct nfs_rpc_ops *cocci_id/* fs/nfs/pagelist.c 614 */;
	const struct cred *cocci_id/* fs/nfs/pagelist.c 614 */;
	struct rpc_clnt *cocci_id/* fs/nfs/pagelist.c 613 */;
	void *cocci_id/* fs/nfs/pagelist.c 604 */;
	struct nfs_commit_info *cocci_id/* fs/nfs/pagelist.c 564 */;
	void (*cocci_id/* fs/nfs/pagelist.c 44 */)(struct nfs_pgio_header *hdr);
	void cocci_id/* fs/nfs/pagelist.c 414 */;
	const struct rpc_call_ops cocci_id/* fs/nfs/pagelist.c 31 */;
	struct nfs_open_context *cocci_id/* fs/nfs/pagelist.c 305 */;
	unsigned int cocci_id/* fs/nfs/pagelist.c 301 */;
	struct page *cocci_id/* fs/nfs/pagelist.c 300 */;
	struct nfs_lock_context *cocci_id/* fs/nfs/pagelist.c 300 */;
	struct kmem_cache *cocci_id/* fs/nfs/pagelist.c 30 */;
	struct nfs_page *cocci_id/* fs/nfs/pagelist.c 299 */;
	struct kref *cocci_id/* fs/nfs/pagelist.c 275 */;
	const struct nfs_pageio_ops cocci_id/* fs/nfs/pagelist.c 1346 */;
	int __init cocci_id/* fs/nfs/pagelist.c 1323 */;
	pgoff_t cocci_id/* fs/nfs/pagelist.c 1305 */;
	struct inode *cocci_id/* fs/nfs/pagelist.c 118 */;
	u32 cocci_id/* fs/nfs/pagelist.c 1168 */;
	struct rpc_task *cocci_id/* fs/nfs/pagelist.c 116 */;
	bool cocci_id/* fs/nfs/pagelist.c 115 */;
	struct nfs_page cocci_id/* fs/nfs/pagelist.c 1119 */;
	struct nfs_pgio_mirror *cocci_id/* fs/nfs/pagelist.c 1045 */;
	struct nfs_pageio_descriptor *cocci_id/* fs/nfs/pagelist.c 1042 */;
	int cocci_id/* fs/nfs/pagelist.c 1042 */;
}
