cocci_test_suite() {
	struct xfs_name *cocci_id/* fs/xfs/xfs_iops.c 90 */;
	int cocci_id/* fs/xfs/xfs_iops.c 88 */;
	struct xfs_trans *cocci_id/* fs/xfs/xfs_iops.c 861 */;
	xfs_off_t cocci_id/* fs/xfs/xfs_iops.c 860 */;
	const struct qstr *cocci_id/* fs/xfs/xfs_iops.c 72 */;
	uint cocci_id/* fs/xfs/xfs_iops.c 671 */;
	struct xfs_dquot *cocci_id/* fs/xfs/xfs_iops.c 657 */;
	kgid_t cocci_id/* fs/xfs/xfs_iops.c 656 */;
	kuid_t cocci_id/* fs/xfs/xfs_iops.c 655 */;
	xfs_trans_t *cocci_id/* fs/xfs/xfs_iops.c 653 */;
	xfs_mount_t *cocci_id/* fs/xfs/xfs_iops.c 650 */;
	struct iattr *cocci_id/* fs/xfs/xfs_iops.c 594 */;
	u32 cocci_id/* fs/xfs/xfs_iops.c 529 */;
	struct kstat *cocci_id/* fs/xfs/xfs_iops.c 528 */;
	const struct path *cocci_id/* fs/xfs/xfs_iops.c 527 */;
	uint32_t cocci_id/* fs/xfs/xfs_iops.c 489 */;
	void *cocci_id/* fs/xfs/xfs_iops.c 46 */;
	const struct xattr *cocci_id/* fs/xfs/xfs_iops.c 45 */;
	char *cocci_id/* fs/xfs/xfs_iops.c 445 */;
	struct delayed_call *cocci_id/* fs/xfs/xfs_iops.c 443 */;
	const char *cocci_id/* fs/xfs/xfs_iops.c 439 */;
	struct lock_class_key cocci_id/* fs/xfs/xfs_iops.c 40 */;
	struct qstr cocci_id/* fs/xfs/xfs_iops.c 279 */;
	unsigned int cocci_id/* fs/xfs/xfs_iops.c 274 */;
	struct posix_acl *cocci_id/* fs/xfs/xfs_iops.c 132 */;
	gfp_t cocci_id/* fs/xfs/xfs_iops.c 1296 */;
	bool cocci_id/* fs/xfs/xfs_iops.c 128 */;
	dev_t cocci_id/* fs/xfs/xfs_iops.c 127 */;
	uint16_t cocci_id/* fs/xfs/xfs_iops.c 1266 */;
	struct xfs_inode *cocci_id/* fs/xfs/xfs_iops.c 1264 */;
	umode_t cocci_id/* fs/xfs/xfs_iops.c 126 */;
	struct xfs_mount *cocci_id/* fs/xfs/xfs_iops.c 1242 */;
	const struct inode_operations cocci_id/* fs/xfs/xfs_iops.c 1196 */;
	u64 cocci_id/* fs/xfs/xfs_iops.c 1133 */;
	struct fiemap_extent_info *cocci_id/* fs/xfs/xfs_iops.c 1132 */;
	struct xfs_name cocci_id/* fs/xfs/xfs_iops.c 110 */;
	struct timespec64 *cocci_id/* fs/xfs/xfs_iops.c 1092 */;
	struct dentry *cocci_id/* fs/xfs/xfs_iops.c 108 */;
	struct inode *cocci_id/* fs/xfs/xfs_iops.c 106 */;
	void cocci_id/* fs/xfs/xfs_iops.c 104 */;
}
