cocci_test_suite() {
	xfs_perag_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 943 */;
	xfs_mount_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 941 */;
	xfs_extlen_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 939 */;
	xfs_trans_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 932 */;
	long cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 905 */;
	uint16_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 627 */;
	struct xfs_alloc_arg cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 619 */;
	int *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 616 */;
	union xfs_btree_rec cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 58 */;
	void cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 484 */;
	uint64_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 451 */;
	struct xfs_inobt_rec_incore *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 448 */;
	bool cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 446 */;
	xfs_agblock_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 420 */;
	uint16_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 418 */;
	xfs_agino_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 417 */;
	xfs_lookup_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 38 */;
	uint cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 342 */;
	struct xfs_sb *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2819 */;
	struct xfs_ialloc_count_inodes cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2788 */;
	struct xfs_ialloc_count_inodes *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2772 */;
	xfs_daddr_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 277 */;
	void *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2769 */;
	union xfs_btree_rec *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2768 */;
	struct xfs_ialloc_count_inodes {
		xfs_agino_t count;
		xfs_agino_t freecount;
	} cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2759 */;
	struct xfs_dinode *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 273 */;
	bool *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2708 */;
	unsigned int cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 270 */;
	struct list_head *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 265 */;
	const struct xfs_buf_ops cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2612 */;
	struct xfs_buf_log_item *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2595 */;
	xfs_failaddr_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2578 */;
	struct xfs_mount *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2577 */;
	struct xfs_buf *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2575 */;
	int cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2527 */;
	struct xfs_agi *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2526 */;
	xfs_agi_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2492 */;
	const short cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2474 */[];
	xfs_buf_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2469 */;
	unsigned short cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2404 */;
	unsigned long cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2366 */;
	struct xfs_imap *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2328 */;
	xfs_agblock_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2267 */;
	xfs_inobt_rec_incore_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 224 */;
	unsigned long long cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2216 */;
	struct xfs_btree_cur *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 220 */;
	struct xfs_icluster *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 2190 */;
	xfs_btnum_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 177 */;
	struct xfs_ino_geometry *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1732 */;
	struct xfs_perag *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1731 */;
	xfs_agnumber_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1726 */;
	xfs_ino_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1722 */;
	struct xfs_buf **cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1721 */;
	umode_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1720 */;
	xfs_ino_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1719 */;
	struct xfs_trans *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1718 */;
	struct xfs_inobt_rec_incore cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1593 */;
	xfs_agino_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1589 */;
	int32_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 156 */;
	uint8_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 155 */;
	struct xfs_btree_cur **cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1405 */;
	xfs_inofree_t cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1110 */;
	xfs_inobt_rec_incore_t *cocci_id/* fs/xfs/libxfs/xfs_ialloc.c 1080 */;
}
