cocci_test_suite() {
	u8 *cocci_id/* fs/ecryptfs/crypto.c 999 */;
	u8 cocci_id/* fs/ecryptfs/crypto.c 998 */[ECRYPTFS_SIZE_AND_MARKER_BYTES];
	u8 cocci_id/* fs/ecryptfs/crypto.c 979 */;
	struct ecryptfs_cipher_code_str_map_elem *cocci_id/* fs/ecryptfs/crypto.c 948 */;
	struct ecryptfs_cipher_code_str_map_elem cocci_id/* fs/ecryptfs/crypto.c 925 */[];
	struct ecryptfs_cipher_code_str_map_elem {
		char cipher_str[16];
		u8 cipher_code;
	} cocci_id/* fs/ecryptfs/crypto.c 917 */;
	u32 cocci_id/* fs/ecryptfs/crypto.c 869 */;
	int *cocci_id/* fs/ecryptfs/crypto.c 866 */;
	struct ecryptfs_flag_map_elem cocci_id/* fs/ecryptfs/crypto.c 852 */[];
	struct ecryptfs_flag_map_elem {
		u32 file_flag;
		u32 local_flag;
	} cocci_id/* fs/ecryptfs/crypto.c 846 */;
	struct crypto_shash *cocci_id/* fs/ecryptfs/crypto.c 77 */;
	struct ecryptfs_global_auth_tok *cocci_id/* fs/ecryptfs/crypto.c 721 */;
	struct ecryptfs_mount_crypt_stat *cocci_id/* fs/ecryptfs/crypto.c 700 */;
	void cocci_id/* fs/ecryptfs/crypto.c 698 */;
	char cocci_id/* fs/ecryptfs/crypto.c 652 */[MD5_DIGEST_SIZE];
	struct inode *cocci_id/* fs/ecryptfs/crypto.c 521 */;
	char cocci_id/* fs/ecryptfs/crypto.c 42 */[3];
	unsigned long long cocci_id/* fs/ecryptfs/crypto.c 409 */;
	size_t cocci_id/* fs/ecryptfs/crypto.c 400 */;
	struct scatterlist cocci_id/* fs/ecryptfs/crypto.c 399 */;
	char cocci_id/* fs/ecryptfs/crypto.c 398 */[ECRYPTFS_MAX_IV_BYTES];
	loff_t cocci_id/* fs/ecryptfs/crypto.c 397 */;
	pgoff_t cocci_id/* fs/ecryptfs/crypto.c 396 */;
	unsigned long cocci_id/* fs/ecryptfs/crypto.c 394 */;
	struct page *cocci_id/* fs/ecryptfs/crypto.c 392 */;
	struct ecryptfs_crypt_stat *cocci_id/* fs/ecryptfs/crypto.c 391 */;
	int cocci_id/* fs/ecryptfs/crypto.c 391 */;
	struct extent_crypt_result *cocci_id/* fs/ecryptfs/crypto.c 355 */;
	struct extent_crypt_result cocci_id/* fs/ecryptfs/crypto.c 311 */;
	struct skcipher_request *cocci_id/* fs/ecryptfs/crypto.c 310 */;
	unsigned char *cocci_id/* fs/ecryptfs/crypto.c 308 */;
	struct scatterlist *cocci_id/* fs/ecryptfs/crypto.c 306 */;
	struct crypto_async_request *cocci_id/* fs/ecryptfs/crypto.c 283 */;
	struct extent_crypt_result {
		struct completion completion;
		int rc;
	} cocci_id/* fs/ecryptfs/crypto.c 278 */;
	const void *cocci_id/* fs/ecryptfs/crypto.c 247 */;
	struct ecryptfs_mount_crypt_stat cocci_id/* fs/ecryptfs/crypto.c 231 */;
	struct ecryptfs_crypt_stat cocci_id/* fs/ecryptfs/crypto.c 211 */;
	struct mutex *cocci_id/* fs/ecryptfs/crypto.c 2085 */;
	struct crypto_skcipher *cocci_id/* fs/ecryptfs/crypto.c 2084 */;
	long *cocci_id/* fs/ecryptfs/crypto.c 2081 */;
	long cocci_id/* fs/ecryptfs/crypto.c 2081 */;
	struct ecryptfs_key_sig *cocci_id/* fs/ecryptfs/crypto.c 202 */;
	struct super_block *cocci_id/* fs/ecryptfs/crypto.c 2018 */;
	bool cocci_id/* fs/ecryptfs/crypto.c 1994 */;
	struct ecryptfs_filename *cocci_id/* fs/ecryptfs/crypto.c 1919 */;
	unsigned char cocci_id/* fs/ecryptfs/crypto.c 1860 */;
	const unsigned char *cocci_id/* fs/ecryptfs/crypto.c 1849 */;
	unsigned char cocci_id/* fs/ecryptfs/crypto.c 1805 */[4];
	unsigned char cocci_id/* fs/ecryptfs/crypto.c 1778 */[3];
	const unsigned char cocci_id/* fs/ecryptfs/crypto.c 1746 */[256];
	struct mutex **cocci_id/* fs/ecryptfs/crypto.c 1713 */;
	struct crypto_skcipher **cocci_id/* fs/ecryptfs/crypto.c 1712 */;
	struct ecryptfs_key_tfm *cocci_id/* fs/ecryptfs/crypto.c 1639 */;
	struct ecryptfs_key_tfm **cocci_id/* fs/ecryptfs/crypto.c 1636 */;
	char *cocci_id/* fs/ecryptfs/crypto.c 1636 */;
	int __init cocci_id/* fs/ecryptfs/crypto.c 1608 */;
	struct mutex cocci_id/* fs/ecryptfs/crypto.c 1606 */;
	struct list_head cocci_id/* fs/ecryptfs/crypto.c 1605 */;
	char cocci_id/* fs/ecryptfs/crypto.c 1565 */[ECRYPTFS_MAX_KEY_BYTES];
	void *cocci_id/* fs/ecryptfs/crypto.c 1541 */;
	const char *cocci_id/* fs/ecryptfs/crypto.c 1532 */;
	char **cocci_id/* fs/ecryptfs/crypto.c 1531 */;
	size_t *cocci_id/* fs/ecryptfs/crypto.c 1531 */;
	struct dentry *cocci_id/* fs/ecryptfs/crypto.c 1365 */;
	ssize_t cocci_id/* fs/ecryptfs/crypto.c 1346 */;
	char cocci_id/* fs/ecryptfs/crypto.c 130 */[ECRYPTFS_MAX_IV_BYTES + 16];
	u64 cocci_id/* fs/ecryptfs/crypto.c 1259 */;
	unsigned int cocci_id/* fs/ecryptfs/crypto.c 1136 */;
	gfp_t cocci_id/* fs/ecryptfs/crypto.c 1135 */;
	struct kmem_cache *cocci_id/* fs/ecryptfs/crypto.c 1031 */;
	u16 cocci_id/* fs/ecryptfs/crypto.c 1020 */;
}
