cocci_test_suite() {
	struct wb_completion *cocci_id/* fs/fs-writeback.c 919 */;
	u64 cocci_id/* fs/fs-writeback.c 918 */;
	struct bdi_writeback cocci_id/* fs/fs-writeback.c 845 */;
	struct wb_lock_cookie cocci_id/* fs/fs-writeback.c 787 */;
	size_t cocci_id/* fs/fs-writeback.c 724 */;
	unsigned int cocci_id/* fs/fs-writeback.c 69 */;
	u16 cocci_id/* fs/fs-writeback.c 632 */;
	struct inode_switch_wbs_context *cocci_id/* fs/fs-writeback.c 493 */;
	struct inode_switch_wbs_context cocci_id/* fs/fs-writeback.c 474 */;
	struct rcu_head *cocci_id/* fs/fs-writeback.c 471 */;
	struct wb_writeback_work {
		long nr_pages;
		struct super_block *sb;
		unsigned long *older_than_this;
		enum writeback_sync_modes sync_mode;
		unsigned int tagged_writepages:1;
		unsigned int for_kupdate:1;
		unsigned int range_cyclic:1;
		unsigned int for_background:1;
		unsigned int for_sync:1;
		unsigned int auto_free:1;
		enum wb_reason reason;
		struct list_head list;
		struct wb_completion *done;
	} cocci_id/* fs/fs-writeback.c 42 */;
	struct work_struct *cocci_id/* fs/fs-writeback.c 351 */;
	struct inode_switch_wbs_context {
		struct inode *inode;
		struct bdi_writeback *new_wb;
		struct rcu_head rcu_head;
		struct work_struct work;
	} cocci_id/* fs/fs-writeback.c 333 */;
	struct writeback_control cocci_id/* fs/fs-writeback.c 2617 */;
	struct cgroup_subsys_state *cocci_id/* fs/fs-writeback.c 255 */;
	struct bdi_writeback *cocci_id/* fs/fs-writeback.c 252 */;
	struct backing_dev_info *cocci_id/* fs/fs-writeback.c 251 */;
	struct page *cocci_id/* fs/fs-writeback.c 249 */;
	struct inode *cocci_id/* fs/fs-writeback.c 249 */;
	void cocci_id/* fs/fs-writeback.c 249 */;
	struct workqueue_struct *cocci_id/* fs/fs-writeback.c 247 */;
	atomic_t cocci_id/* fs/fs-writeback.c 246 */;
	struct wb_writeback_work cocci_id/* fs/fs-writeback.c 2455 */;
	unsigned long cocci_id/* fs/fs-writeback.c 2450 */;
	struct inode cocci_id/* fs/fs-writeback.c 2398 */;
	bool cocci_id/* fs/fs-writeback.c 2317 */;
	struct list_head *cocci_id/* fs/fs-writeback.c 2316 */;
	const int cocci_id/* fs/fs-writeback.c 2283 */;
	struct super_block *cocci_id/* fs/fs-writeback.c 2245 */;
	int cocci_id/* fs/fs-writeback.c 2243 */;
	const char *cocci_id/* fs/fs-writeback.c 2199 */;
	struct dentry *cocci_id/* fs/fs-writeback.c 2198 */;
	loff_t *cocci_id/* fs/fs-writeback.c 2185 */;
	size_t *cocci_id/* fs/fs-writeback.c 2185 */;
	void __user *cocci_id/* fs/fs-writeback.c 2185 */;
	struct ctl_table *cocci_id/* fs/fs-writeback.c 2184 */;
	void cocci_id/* fs/fs-writeback.c 2158 */(struct work_struct *w);
	enum wb_reason cocci_id/* fs/fs-writeback.c 2105 */;
	struct blk_plug cocci_id/* fs/fs-writeback.c 1845 */;
	struct wb_writeback_work *cocci_id/* fs/fs-writeback.c 1767 */;
	long cocci_id/* fs/fs-writeback.c 1766 */;
	unsigned cocci_id/* fs/fs-writeback.c 1445 */;
	struct address_space *cocci_id/* fs/fs-writeback.c 1443 */;
	struct writeback_control *cocci_id/* fs/fs-writeback.c 1441 */;
	wait_queue_head_t *cocci_id/* fs/fs-writeback.c 1328 */;
	unsigned long *cocci_id/* fs/fs-writeback.c 1231 */;
	int __init cocci_id/* fs/fs-writeback.c 1012 */;
}
