cocci_test_suite() {
	struct ecryptfs_parse_tag_70_packet_silly_stack *cocci_id/* fs/ecryptfs/keystore.c 896 */;
	struct ecryptfs_parse_tag_70_packet_silly_stack {
		u8 cipher_code;
		size_t max_packet_size;
		size_t packet_size_len;
		size_t parsed_tag_70_packet_size;
		size_t block_aligned_filename_size;
		size_t block_size;
		size_t i;
		struct mutex *tfm_mutex;
		char *decrypted_filename;
		struct ecryptfs_auth_tok *auth_tok;
		struct scatterlist src_sg[2];
		struct scatterlist dst_sg[2];
		struct crypto_skcipher *skcipher_tfm;
		struct skcipher_request *skcipher_req;
		char fnek_sig_hex[ECRYPTFS_SIG_SIZE_HEX + 1];
		char iv[ECRYPTFS_MAX_IV_BYTES];
		char cipher_string[ECRYPTFS_MAX_CIPHER_NAME_SIZE + 1];
	} cocci_id/* fs/ecryptfs/keystore.c 855 */;
	unsigned char *cocci_id/* fs/ecryptfs/keystore.c 81 */;
	u8 *cocci_id/* fs/ecryptfs/keystore.c 760 */;
	struct ecryptfs_write_tag_70_packet_silly_stack *cocci_id/* fs/ecryptfs/keystore.c 623 */;
	struct ecryptfs_write_tag_70_packet_silly_stack {
		u8 cipher_code;
		size_t max_packet_size;
		size_t packet_size_len;
		size_t block_aligned_filename_size;
		size_t block_size;
		size_t i;
		size_t j;
		size_t num_rand_bytes;
		struct mutex *tfm_mutex;
		char *block_aligned_filename;
		struct ecryptfs_auth_tok *auth_tok;
		struct scatterlist src_sg[2];
		struct scatterlist dst_sg[2];
		struct crypto_skcipher *skcipher_tfm;
		struct skcipher_request *skcipher_req;
		char iv[ECRYPTFS_MAX_IV_BYTES];
		char hash[ECRYPTFS_TAG_70_DIGEST_SIZE];
		char tmp_hash[ECRYPTFS_TAG_70_DIGEST_SIZE];
		struct crypto_shash *hash_tfm;
		struct shash_desc *hash_desc;
	} cocci_id/* fs/ecryptfs/keystore.c 584 */;
	struct ecryptfs_auth_tok **cocci_id/* fs/ecryptfs/keystore.c 555 */;
	struct key **cocci_id/* fs/ecryptfs/keystore.c 554 */;
	unsigned char cocci_id/* fs/ecryptfs/keystore.c 420 */;
	u16 cocci_id/* fs/ecryptfs/keystore.c 417 */;
	long cocci_id/* fs/ecryptfs/keystore.c 29 */;
	struct ecryptfs_global_auth_tok *cocci_id/* fs/ecryptfs/keystore.c 2514 */;
	u32 cocci_id/* fs/ecryptfs/keystore.c 2512 */;
	struct ecryptfs_mount_crypt_stat *cocci_id/* fs/ecryptfs/keystore.c 2511 */;
	struct ecryptfs_key_sig *cocci_id/* fs/ecryptfs/keystore.c 2494 */;
	struct ecryptfs_key_record *cocci_id/* fs/ecryptfs/keystore.c 2409 */;
	struct key *cocci_id/* fs/ecryptfs/keystore.c 2404 */;
	struct dentry *cocci_id/* fs/ecryptfs/keystore.c 2400 */;
	size_t *cocci_id/* fs/ecryptfs/keystore.c 2400 */;
	char cocci_id/* fs/ecryptfs/keystore.c 2180 */[ECRYPTFS_MAX_KEY_BYTES];
	struct ecryptfs_session_key *cocci_id/* fs/ecryptfs/keystore.c 199 */;
	struct ecryptfs_password cocci_id/* fs/ecryptfs/keystore.c 1908 */;
	struct ecryptfs_private_key cocci_id/* fs/ecryptfs/keystore.c 1900 */;
	struct ecryptfs_auth_tok_list_item *cocci_id/* fs/ecryptfs/keystore.c 1766 */;
	unsigned char cocci_id/* fs/ecryptfs/keystore.c 1765 */[ECRYPTFS_SIG_SIZE];
	struct list_head cocci_id/* fs/ecryptfs/keystore.c 1759 */;
	struct skcipher_request *cocci_id/* fs/ecryptfs/keystore.c 1652 */;
	struct crypto_skcipher *cocci_id/* fs/ecryptfs/keystore.c 1651 */;
	struct mutex *cocci_id/* fs/ecryptfs/keystore.c 1650 */;
	struct scatterlist cocci_id/* fs/ecryptfs/keystore.c 1648 */[2];
	struct ecryptfs_crypt_stat *cocci_id/* fs/ecryptfs/keystore.c 1646 */;
	struct ecryptfs_auth_tok *cocci_id/* fs/ecryptfs/keystore.c 1645 */;
	int cocci_id/* fs/ecryptfs/keystore.c 1644 */;
	struct ecryptfs_auth_tok_list_item cocci_id/* fs/ecryptfs/keystore.c 1327 */;
	struct list_head *cocci_id/* fs/ecryptfs/keystore.c 1224 */;
	struct kmem_cache *cocci_id/* fs/ecryptfs/keystore.c 1203 */;
	void cocci_id/* fs/ecryptfs/keystore.c 1190 */;
	size_t cocci_id/* fs/ecryptfs/keystore.c 1133 */;
	char *cocci_id/* fs/ecryptfs/keystore.c 1131 */;
	struct ecryptfs_message *cocci_id/* fs/ecryptfs/keystore.c 1130 */;
	struct ecryptfs_msg_ctx *cocci_id/* fs/ecryptfs/keystore.c 1129 */;
	u8 cocci_id/* fs/ecryptfs/keystore.c 1128 */;
	char **cocci_id/* fs/ecryptfs/keystore.c 1097 */;
}
