cocci_test_suite() {
	const match_table_t cocci_id/* fs/ubifs/super.c 959 */;
	enum{Opt_fast_unmount, Opt_norm_unmount, Opt_bulk_read, Opt_no_bulk_read, Opt_chk_data_crc, Opt_no_chk_data_crc, Opt_override_compr, Opt_assert, Opt_auth_key, Opt_auth_hash_name, Opt_ignore, Opt_err,} cocci_id/* fs/ubifs/super.c 944 */;
	struct ubifs_ino_node *cocci_id/* fs/ubifs/super.c 93 */;
	union ubifs_key cocci_id/* fs/ubifs/super.c 92 */;
	unsigned long cocci_id/* fs/ubifs/super.c 89 */;
	struct ubifs_orphan cocci_id/* fs/ubifs/super.c 878 */;
	struct ubifs_orphan *cocci_id/* fs/ubifs/super.c 868 */;
	struct ubifs_jhead cocci_id/* fs/ubifs/super.c 807 */;
	int cocci_id/* fs/ubifs/super.c 803 */;
	long long cocci_id/* fs/ubifs/super.c 750 */;
	struct ubifs_zbranch cocci_id/* fs/ubifs/super.c 665 */;
	struct ubifs_znode cocci_id/* fs/ubifs/super.c 664 */;
	const struct ubifs_inode *cocci_id/* fs/ubifs/super.c 58 */;
	const struct inode *cocci_id/* fs/ubifs/super.c 55 */;
	struct seq_file *cocci_id/* fs/ubifs/super.c 418 */;
	__le32 *cocci_id/* fs/ubifs/super.c 395 */;
	unsigned long long cocci_id/* fs/ubifs/super.c 394 */;
	struct kstatfs *cocci_id/* fs/ubifs/super.c 391 */;
	struct shrinker cocci_id/* fs/ubifs/super.c 39 */;
	struct kmem_cache *cocci_id/* fs/ubifs/super.c 36 */;
	struct writeback_control *cocci_id/* fs/ubifs/super.c 277 */;
	struct ubifs_inode cocci_id/* fs/ubifs/super.c 258 */;
	struct inode cocci_id/* fs/ubifs/super.c 257 */;
	struct inode *cocci_id/* fs/ubifs/super.c 249 */;
	void __exit cocci_id/* fs/ubifs/super.c 2414 */;
	unsigned int cocci_id/* fs/ubifs/super.c 2373 */;
	struct ubifs_ch cocci_id/* fs/ubifs/super.c 2320 */;
	int __init cocci_id/* fs/ubifs/super.c 2316 */;
	struct ubifs_inode *cocci_id/* fs/ubifs/super.c 2312 */;
	void *cocci_id/* fs/ubifs/super.c 2310 */;
	struct file_system_type cocci_id/* fs/ubifs/super.c 2299 */;
	struct super_block *cocci_id/* fs/ubifs/super.c 2292 */;
	struct file_system_type *cocci_id/* fs/ubifs/super.c 2221 */;
	struct dentry *cocci_id/* fs/ubifs/super.c 2221 */;
	struct ubifs_info cocci_id/* fs/ubifs/super.c 2085 */;
	struct ubifs_info *cocci_id/* fs/ubifs/super.c 2081 */;
	struct ubi_volume_desc *cocci_id/* fs/ubifs/super.c 2081 */;
	char *cocci_id/* fs/ubifs/super.c 2039 */;
	const char *cocci_id/* fs/ubifs/super.c 2035 */;
	const struct super_operations cocci_id/* fs/ubifs/super.c 2002 */;
	union ubifs_dev_desc cocci_id/* fs/ubifs/super.c 197 */;
	int *cocci_id/* fs/ubifs/super.c 1952 */;
	union ubifs_dev_desc *cocci_id/* fs/ubifs/super.c 195 */;
	dev_t cocci_id/* fs/ubifs/super.c 194 */;
	struct ubifs_sb_node *cocci_id/* fs/ubifs/super.c 1714 */;
	int64_t cocci_id/* fs/ubifs/super.c 127 */;
	size_t cocci_id/* fs/ubifs/super.c 1214 */;
	void cocci_id/* fs/ubifs/super.c 1160 */;
	struct ubifs_bud cocci_id/* fs/ubifs/super.c 1146 */;
	struct ubifs_bud *cocci_id/* fs/ubifs/super.c 1144 */;
	struct ubifs_unclean_leb cocci_id/* fs/ubifs/super.c 1139 */;
	struct ubifs_unclean_leb *cocci_id/* fs/ubifs/super.c 1136 */;
	substring_t cocci_id/* fs/ubifs/super.c 1010 */[MAX_OPT_ARGS];
}
