cocci_test_suite() {
	struct nfs4_cb_conn *cocci_id/* fs/nfsd/nfs4callback.c 997 */;
	struct nfs4_client cocci_id/* fs/nfsd/nfs4callback.c 957 */;
	struct sockaddr *cocci_id/* fs/nfsd/nfs4callback.c 884 */;
	struct rpc_create_args cocci_id/* fs/nfsd/nfs4callback.c 882 */;
	struct rpc_timeout cocci_id/* fs/nfsd/nfs4callback.c 877 */;
	struct cred *cocci_id/* fs/nfsd/nfs4callback.c 862 */;
	enum nfs_cb_opnum4{OP_CB_GETATTR=3, OP_CB_RECALL=4, OP_CB_LAYOUTRECALL=5, OP_CB_NOTIFY=6, OP_CB_PUSH_DELEG=7, OP_CB_RECALL_ANY=8, OP_CB_RECALLABLE_OBJ_AVAIL=9, OP_CB_RECALL_SLOT=10, OP_CB_SEQUENCE=11, OP_CB_WANTS_CANCELLED=12, OP_CB_NOTIFY_LOCK=13, OP_CB_NOTIFY_DEVICEID=14, OP_CB_OFFLOAD=15, OP_CB_ILLEGAL=10044,} cocci_id/* fs/nfsd/nfs4callback.c 86 */;
	const struct cred *cocci_id/* fs/nfsd/nfs4callback.c 854 */;
	struct rpc_clnt *cocci_id/* fs/nfsd/nfs4callback.c 854 */;
	struct workqueue_struct *cocci_id/* fs/nfsd/nfs4callback.c 829 */;
	time_t cocci_id/* fs/nfsd/nfs4callback.c 826 */;
	struct nfsd_net *cocci_id/* fs/nfsd/nfs4callback.c 825 */;
	struct net *cocci_id/* fs/nfsd/nfs4callback.c 823 */;
	struct rpc_stat cocci_id/* fs/nfsd/nfs4callback.c 809 */;
	const struct rpc_program cocci_id/* fs/nfsd/nfs4callback.c 807 */;
	const struct rpc_version *cocci_id/* fs/nfsd/nfs4callback.c 803 */[2];
	const struct rpc_version cocci_id/* fs/nfsd/nfs4callback.c 789 */;
	unsigned int cocci_id/* fs/nfsd/nfs4callback.c 788 */[ARRAY_SIZE(nfs4_cb_procedures)];
	const struct rpc_procinfo cocci_id/* fs/nfsd/nfs4callback.c 778 */[];
	struct nfsd4_copy cocci_id/* fs/nfsd/nfs4callback.c 734 */;
	const struct nfsd4_copy *cocci_id/* fs/nfsd/nfs4callback.c 714 */;
	const struct knfsd_fh *cocci_id/* fs/nfsd/nfs4callback.c 713 */;
	__be32 cocci_id/* fs/nfsd/nfs4callback.c 712 */;
	struct nfs4_lockowner *cocci_id/* fs/nfsd/nfs4callback.c 629 */;
	struct nfsd4_blocked_lock cocci_id/* fs/nfsd/nfs4callback.c 628 */;
	const struct nfsd4_blocked_lock *cocci_id/* fs/nfsd/nfs4callback.c 627 */;
	struct nfs4_stateowner *cocci_id/* fs/nfsd/nfs4callback.c 613 */;
	struct nfs4_cb_compound_hdr cocci_id/* fs/nfsd/nfs4callback.c 598 */;
	void *cocci_id/* fs/nfsd/nfs4callback.c 595 */;
	struct rpc_rqst *cocci_id/* fs/nfsd/nfs4callback.c 593 */;
	struct nfs4_layout_stateid cocci_id/* fs/nfsd/nfs4callback.c 581 */;
	const void *cocci_id/* fs/nfsd/nfs4callback.c 577 */;
	const struct nfs4_layout_stateid *cocci_id/* fs/nfsd/nfs4callback.c 550 */;
	struct nfs4_cb_compound_hdr {
		u32 ident;
		u32 nops;
		__be32 *nops_p;
		u32 minorversion;
		int status;
	} cocci_id/* fs/nfsd/nfs4callback.c 53 */;
	void *__unused cocci_id/* fs/nfsd/nfs4callback.c 495 */;
	const void *__unused cocci_id/* fs/nfsd/nfs4callback.c 460 */;
	void cocci_id/* fs/nfsd/nfs4callback.c 46 */(struct nfs4_client *,
						     int reason);
	struct nfsd4_callback *cocci_id/* fs/nfsd/nfs4callback.c 433 */;
	const struct nfsd4_callback *cocci_id/* fs/nfsd/nfs4callback.c 343 */;
	const struct nfs4_delegation *cocci_id/* fs/nfsd/nfs4callback.c 314 */;
	__be32 *cocci_id/* fs/nfsd/nfs4callback.c 286 */;
	u32 cocci_id/* fs/nfsd/nfs4callback.c 285 */;
	struct nfs4_cb_compound_hdr *cocci_id/* fs/nfsd/nfs4callback.c 283 */;
	struct xdr_stream *cocci_id/* fs/nfsd/nfs4callback.c 282 */;
	int cocci_id/* fs/nfsd/nfs4callback.c 282 */;
	void cocci_id/* fs/nfsd/nfs4callback.c 250 */;
	enum nfs_cb_opnum4 cocci_id/* fs/nfsd/nfs4callback.c 219 */;
	int *cocci_id/* fs/nfsd/nfs4callback.c 219 */;
	const struct {
		int stat;
		int errno;
	} cocci_id/* fs/nfsd/nfs4callback.c 161 */[];
	const struct nfsd4_session *cocci_id/* fs/nfsd/nfs4callback.c 149 */;
	const stateid_t *cocci_id/* fs/nfsd/nfs4callback.c 134 */;
	enum nfsd4_cb_op cocci_id/* fs/nfsd/nfs4callback.c 1339 */;
	const struct nfsd4_callback_ops *cocci_id/* fs/nfsd/nfs4callback.c 1339 */;
	struct nfsd4_callback cocci_id/* fs/nfsd/nfs4callback.c 1303 */;
	struct work_struct *cocci_id/* fs/nfsd/nfs4callback.c 1300 */;
	struct nfsd4_session *cocci_id/* fs/nfsd/nfs4callback.c 1234 */;
	struct nfsd4_conn *cocci_id/* fs/nfsd/nfs4callback.c 1232 */;
	struct nfs4_client *cocci_id/* fs/nfsd/nfs4callback.c 1232 */;
	const struct rpc_call_ops cocci_id/* fs/nfsd/nfs4callback.c 1198 */;
	bool cocci_id/* fs/nfsd/nfs4callback.c 1010 */;
	struct rpc_task *cocci_id/* fs/nfsd/nfs4callback.c 1010 */;
	struct nfs4_cb_conn cocci_id/* fs/nfsd/nfs4callback.c 1001 */;
}
