cocci_test_suite() {
	long cocci_id/* fs/inode.c 98 */;
	struct file_system_type *cocci_id/* fs/inode.c 966 */;
	atomic_t cocci_id/* fs/inode.c 897 */;
	unsigned int *cocci_id/* fs/inode.c 892 */;
	unsigned int cocci_id/* fs/inode.c 890 */;
	void *cocci_id/* fs/inode.c 815 */;
	int (*cocci_id/* fs/inode.c 814 */)(struct inode *, void *);
	void cocci_id/* fs/inode.c 808 */(struct inode *inode);
	struct shrink_control *cocci_id/* fs/inode.c 797 */;
	struct kmem_cache *cocci_id/* fs/inode.c 78 */;
	spinlock_t *cocci_id/* fs/inode.c 732 */;
	struct list_lru_one *cocci_id/* fs/inode.c 732 */;
	enum lru_status cocci_id/* fs/inode.c 731 */;
	struct inodes_stat_t cocci_id/* fs/inode.c 73 */;
	const struct address_space_operations cocci_id/* fs/inode.c 66 */;
	struct inode cocci_id/* fs/inode.c 606 */;
	struct list_head *cocci_id/* fs/inode.c 601 */;
	struct hlist_head *cocci_id/* fs/inode.c 494 */;
	unsigned long cocci_id/* fs/inode.c 492 */;
	struct address_space *cocci_id/* fs/inode.c 366 */;
	void cocci_id/* fs/inode.c 366 */;
	struct inode *cocci_id/* fs/inode.c 251 */;
	struct fsxattr *cocci_id/* fs/inode.c 2267 */;
	const struct fsxattr *cocci_id/* fs/inode.c 2266 */;
	const struct super_operations *cocci_id/* fs/inode.c 226 */;
	struct super_block *cocci_id/* fs/inode.c 224 */;
	unsigned cocci_id/* fs/inode.c 2163 */;
	struct rcu_head *cocci_id/* fs/inode.c 215 */;
	wait_queue_head_t *cocci_id/* fs/inode.c 2097 */;
	struct user_namespace *cocci_id/* fs/inode.c 2080 */;
	const struct inode *cocci_id/* fs/inode.c 2051 */;
	umode_t cocci_id/* fs/inode.c 2025 */;
	dev_t cocci_id/* fs/inode.c 2025 */;
	struct hlist_head cocci_id/* fs/inode.c 2015 */;
	void __init cocci_id/* fs/inode.c 1999 */;
	char *cocci_id/* fs/inode.c 1967 */;
	int __init cocci_id/* fs/inode.c 1967 */;
	struct file *cocci_id/* fs/inode.c 1913 */;
	struct iattr cocci_id/* fs/inode.c 1822 */;
	struct dentry *cocci_id/* fs/inode.c 1820 */;
	int cocci_id/* fs/inode.c 1820 */;
	struct timespec64 cocci_id/* fs/inode.c 1705 */;
	struct vfsmount *cocci_id/* fs/inode.c 1704 */;
	bool cocci_id/* fs/inode.c 1702 */;
	const struct path *cocci_id/* fs/inode.c 1702 */;
	int (*cocci_id/* fs/inode.c 1685 */)(struct inode *,
					     struct timespec64 *, int);
	struct timespec64 *cocci_id/* fs/inode.c 1655 */;
	sector_t cocci_id/* fs/inode.c 1612 */;
	ino_t cocci_id/* fs/inode.c 1460 */;
	int (*cocci_id/* fs/inode.c 1432 */)(struct inode *, unsigned long,
					     void *);
	struct address_space *const cocci_id/* fs/inode.c 135 */;
	const struct file_operations cocci_id/* fs/inode.c 134 */;
	const struct inode_operations cocci_id/* fs/inode.c 133 */;
	loff_t *cocci_id/* fs/inode.c 110 */;
	size_t *cocci_id/* fs/inode.c 110 */;
	void __user *cocci_id/* fs/inode.c 110 */;
	struct ctl_table *cocci_id/* fs/inode.c 109 */;
	__typeof__(unsigned long) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
	__typeof__(unsigned int) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
