cocci_test_suite() {
	char **cocci_id/* fs/cifs/smb1ops.c 943 */;
	struct dfs_info3_param cocci_id/* fs/cifs/smb1ops.c 921 */;
	const struct nls_table *cocci_id/* fs/cifs/smb1ops.c 917 */;
	const unsigned char *cocci_id/* fs/cifs/smb1ops.c 916 */;
	__u8 cocci_id/* fs/cifs/smb1ops.c 911 */;
	struct kstatfs *cocci_id/* fs/cifs/smb1ops.c 875 */;
	struct cifs_fid *cocci_id/* fs/cifs/smb1ops.c 859 */;
	const unsigned int cocci_id/* fs/cifs/smb1ops.c 858 */;
	struct cifs_search_info *cocci_id/* fs/cifs/smb1ops.c 838 */;
	READ_RSP *cocci_id/* fs/cifs/smb1ops.c 80 */;
	struct tcon_link *cocci_id/* fs/cifs/smb1ops.c 764 */;
	FILE_BASIC_INFO *cocci_id/* fs/cifs/smb1ops.c 754 */;
	struct kvec *cocci_id/* fs/cifs/smb1ops.c 745 */;
	unsigned long cocci_id/* fs/cifs/smb1ops.c 745 */;
	struct cifs_io_parms *cocci_id/* fs/cifs/smb1ops.c 735 */;
	unsigned int *cocci_id/* fs/cifs/smb1ops.c 735 */;
	__u32 *cocci_id/* fs/cifs/smb1ops.c 697 */;
	struct cifs_open_parms *cocci_id/* fs/cifs/smb1ops.c 696 */;
	u32 cocci_id/* fs/cifs/smb1ops.c 682 */;
	FILE_BASIC_INFO cocci_id/* fs/cifs/smb1ops.c 680 */;
	struct cifsFileInfo *cocci_id/* fs/cifs/smb1ops.c 65 */;
	long long cocci_id/* fs/cifs/smb1ops.c 646 */;
	struct seq_file *cocci_id/* fs/cifs/smb1ops.c 640 */;
	struct cifs_tcon *cocci_id/* fs/cifs/smb1ops.c 614 */;
	u64 *cocci_id/* fs/cifs/smb1ops.c 588 */;
	FILE_ALL_INFO *cocci_id/* fs/cifs/smb1ops.c 588 */;
	const char *cocci_id/* fs/cifs/smb1ops.c 587 */;
	struct cifs_sb_info *cocci_id/* fs/cifs/smb1ops.c 587 */;
	FILE_ALL_INFO cocci_id/* fs/cifs/smb1ops.c 520 */;
	READ_RSP cocci_id/* fs/cifs/smb1ops.c 489 */;
	struct smb_vol *cocci_id/* fs/cifs/smb1ops.c 466 */;
	struct cifs_ses *cocci_id/* fs/cifs/smb1ops.c 416 */;
	struct mid_q_entry *cocci_id/* fs/cifs/smb1ops.c 379 */;
	bool *cocci_id/* fs/cifs/smb1ops.c 373 */;
	unsigned int cocci_id/* fs/cifs/smb1ops.c 373 */;
	__u32 cocci_id/* fs/cifs/smb1ops.c 372 */;
	struct cifsInodeInfo *cocci_id/* fs/cifs/smb1ops.c 372 */;
	struct smb_hdr cocci_id/* fs/cifs/smb1ops.c 34 */;
	struct smb_rqst *cocci_id/* fs/cifs/smb1ops.c 27 */;
	__u16 cocci_id/* fs/cifs/smb1ops.c 242 */;
	struct smb_t2_rsp *cocci_id/* fs/cifs/smb1ops.c 240 */;
	struct smb_hdr *cocci_id/* fs/cifs/smb1ops.c 239 */;
	char *cocci_id/* fs/cifs/smb1ops.c 237 */;
	int cocci_id/* fs/cifs/smb1ops.c 236 */;
	__u64 cocci_id/* fs/cifs/smb1ops.c 160 */;
	int *cocci_id/* fs/cifs/smb1ops.c 127 */;
	struct smb_version_values cocci_id/* fs/cifs/smb1ops.c 1233 */;
	struct smb_version_operations cocci_id/* fs/cifs/smb1ops.c 1149 */;
	struct win_dev cocci_id/* fs/cifs/smb1ops.c 1122 */;
	const int cocci_id/* fs/cifs/smb1ops.c 109 */;
	const struct cifs_credits *cocci_id/* fs/cifs/smb1ops.c 109 */;
	struct TCP_Server_Info *cocci_id/* fs/cifs/smb1ops.c 108 */;
	void cocci_id/* fs/cifs/smb1ops.c 107 */;
	struct cifs_unix_set_info_args cocci_id/* fs/cifs/smb1ops.c 1047 */;
	struct kvec cocci_id/* fs/cifs/smb1ops.c 1040 */[2];
	struct win_dev *cocci_id/* fs/cifs/smb1ops.c 1039 */;
	struct cifs_open_parms cocci_id/* fs/cifs/smb1ops.c 1037 */;
	struct cifs_fid cocci_id/* fs/cifs/smb1ops.c 1036 */;
	struct cifs_io_parms cocci_id/* fs/cifs/smb1ops.c 1034 */;
	umode_t cocci_id/* fs/cifs/smb1ops.c 1027 */;
	dev_t cocci_id/* fs/cifs/smb1ops.c 1027 */;
	struct dentry *cocci_id/* fs/cifs/smb1ops.c 1026 */;
	struct inode *cocci_id/* fs/cifs/smb1ops.c 1025 */;
	bool cocci_id/* fs/cifs/smb1ops.c 1015 */;
}
