cocci_test_suite() {
	struct cifsLockInfo **cocci_id/* fs/cifs/file.c 976 */;
	__u8 cocci_id/* fs/cifs/file.c 974 */;
	__u16 cocci_id/* fs/cifs/file.c 974 */;
	__u64 cocci_id/* fs/cifs/file.c 973 */;
	struct cifs_fid_locks *cocci_id/* fs/cifs/file.c 973 */;
	struct cifsLockInfo cocci_id/* fs/cifs/file.c 944 */;
	char *cocci_id/* fs/cifs/file.c 896 */;
	u32 cocci_id/* fs/cifs/file.c 66 */;
	int cocci_id/* fs/cifs/file.c 644 */(struct cifsFileInfo *cfile);
	struct cifs_unix_set_info_args cocci_id/* fs/cifs/file.c 624 */;
	unsigned int cocci_id/* fs/cifs/file.c 496 */;
	const struct address_space_operations cocci_id/* fs/cifs/file.c 4807 */;
	struct writeback_control cocci_id/* fs/cifs/file.c 4711 */;
	struct page *cocci_id/* fs/cifs/file.c 4697 */;
	gfp_t cocci_id/* fs/cifs/file.c 4689 */;
	long long cocci_id/* fs/cifs/file.c 4624 */;
	pgoff_t cocci_id/* fs/cifs/file.c 4617 */;
	void **cocci_id/* fs/cifs/file.c 4614 */;
	struct cifs_pending_open cocci_id/* fs/cifs/file.c 450 */;
	struct cifs_fid cocci_id/* fs/cifs/file.c 449 */;
	struct super_block *cocci_id/* fs/cifs/file.c 447 */;
	struct cifsInodeInfo *cocci_id/* fs/cifs/file.c 446 */;
	struct TCP_Server_Info *cocci_id/* fs/cifs/file.c 445 */;
	struct inode *cocci_id/* fs/cifs/file.c 443 */;
	void cocci_id/* fs/cifs/file.c 440 */;
	struct cifs_credits *cocci_id/* fs/cifs/file.c 4396 */;
	struct cifs_credits cocci_id/* fs/cifs/file.c 4395 */;
	pid_t cocci_id/* fs/cifs/file.c 4350 */;
	unsigned int *cocci_id/* fs/cifs/file.c 4286 */;
	u64 cocci_id/* fs/cifs/file.c 4189 */;
	struct vm_area_struct *cocci_id/* fs/cifs/file.c 4130 */;
	struct cifsFileInfo cocci_id/* fs/cifs/file.c 412 */;
	const struct vm_operations_struct cocci_id/* fs/cifs/file.c 4106 */;
	struct vm_fault *cocci_id/* fs/cifs/file.c 4098 */;
	vm_fault_t cocci_id/* fs/cifs/file.c 4097 */;
	struct work_struct *cocci_id/* fs/cifs/file.c 409 */;
	struct cifs_io_parms cocci_id/* fs/cifs/file.c 4016 */;
	loff_t *cocci_id/* fs/cifs/file.c 4003 */;
	struct cifsLockInfo *cocci_id/* fs/cifs/file.c 386 */;
	struct cifs_aio_ctx *cocci_id/* fs/cifs/file.c 3859 */;
	loff_t cocci_id/* fs/cifs/file.c 3858 */;
	struct cifs_tcon *cocci_id/* fs/cifs/file.c 3856 */;
	struct cifsFileInfo *cocci_id/* fs/cifs/file.c 3855 */;
	struct cifs_sb_info *cocci_id/* fs/cifs/file.c 3854 */;
	struct file *cocci_id/* fs/cifs/file.c 3853 */;
	size_t cocci_id/* fs/cifs/file.c 3852 */;
	bool cocci_id/* fs/cifs/file.c 3850 */;
	struct kiocb *cocci_id/* fs/cifs/file.c 3850 */;
	struct iov_iter *cocci_id/* fs/cifs/file.c 3850 */;
	ssize_t cocci_id/* fs/cifs/file.c 3849 */;
	const size_t cocci_id/* fs/cifs/file.c 3642 */;
	void cocci_id/* fs/cifs/file.c 3443 */(struct cifs_aio_ctx *ctx);
	void *cocci_id/* fs/cifs/file.c 3430 */;
	struct cifs_readdata *cocci_id/* fs/cifs/file.c 3369 */;
	struct cifs_readdata cocci_id/* fs/cifs/file.c 3354 */;
	struct kref *cocci_id/* fs/cifs/file.c 3351 */;
	struct page **cocci_id/* fs/cifs/file.c 3337 */;
	work_func_t cocci_id/* fs/cifs/file.c 3335 */;
	int cocci_id/* fs/cifs/file.c 3128 */;
	struct iov_iter cocci_id/* fs/cifs/file.c 3126 */;
	struct cifs_fid_locks cocci_id/* fs/cifs/file.c 309 */;
	struct dentry *cocci_id/* fs/cifs/file.c 297 */;
	struct tcon_link *cocci_id/* fs/cifs/file.c 295 */;
	struct cifs_fid *cocci_id/* fs/cifs/file.c 294 */;
	void cocci_id/* fs/cifs/file.c 291 */(struct work_struct *work);
	struct rw_semaphore *cocci_id/* fs/cifs/file.c 285 */;
	struct cifs_writedata *cocci_id/* fs/cifs/file.c 2798 */;
	unsigned long *cocci_id/* fs/cifs/file.c 2757 */;
	struct cifs_writedata cocci_id/* fs/cifs/file.c 2725 */;
	size_t *cocci_id/* fs/cifs/file.c 2706 */;
	unsigned long cocci_id/* fs/cifs/file.c 2680 */;
	fl_owner_t cocci_id/* fs/cifs/file.c 2666 */;
	struct writeback_control *cocci_id/* fs/cifs/file.c 2522 */;
	FILE_ALL_INFO cocci_id/* fs/cifs/file.c 221 */;
	pgoff_t *cocci_id/* fs/cifs/file.c 2196 */;
	struct address_space *cocci_id/* fs/cifs/file.c 2139 */;
	unsigned cocci_id/* fs/cifs/file.c 2137 */;
	struct cifsFileInfo **cocci_id/* fs/cifs/file.c 2103 */;
	const char *cocci_id/* fs/cifs/file.c 2102 */;
	struct kvec cocci_id/* fs/cifs/file.c 1878 */[2];
	struct cifs_open_parms cocci_id/* fs/cifs/file.c 186 */;
	FILE_ALL_INFO *cocci_id/* fs/cifs/file.c 184 */;
	__u32 *cocci_id/* fs/cifs/file.c 177 */;
	__u32 cocci_id/* fs/cifs/file.c 1744 */;
	struct file_lock *cocci_id/* fs/cifs/file.c 1735 */;
	struct list_head *cocci_id/* fs/cifs/file.c 1518 */;
	bool *cocci_id/* fs/cifs/file.c 1395 */;
	int *cocci_id/* fs/cifs/file.c 1394 */;
	struct lock_to_push cocci_id/* fs/cifs/file.c 1310 */;
	struct lock_to_push *cocci_id/* fs/cifs/file.c 1288 */;
	struct list_head cocci_id/* fs/cifs/file.c 1287 */;
	struct file_lock_context *cocci_id/* fs/cifs/file.c 1284 */;
	FILE_UNIX_BASIC_INFO cocci_id/* fs/cifs/file.c 128 */;
	struct lock_to_push {
		struct list_head llist;
		__u64 offset;
		__u64 length;
		__u32 pid;
		__u16 netfid;
		__u8 type;
	} cocci_id/* fs/cifs/file.c 1269 */;
	const void *cocci_id/* fs/cifs/file.c 1266 */;
	struct cifs_fattr cocci_id/* fs/cifs/file.c 122 */;
	LOCKING_ANDX_RANGE cocci_id/* fs/cifs/file.c 1209 */;
	struct smb_hdr cocci_id/* fs/cifs/file.c 1209 */;
	const int cocci_id/* fs/cifs/file.c 1195 */[];
	LOCKING_ANDX_RANGE *cocci_id/* fs/cifs/file.c 1194 */;
	FILE_UNIX_BASIC_INFO *cocci_id/* fs/cifs/file.c 119 */;
	__u16 *cocci_id/* fs/cifs/file.c 116 */;
	struct inode **cocci_id/* fs/cifs/file.c 114 */;
	unsigned char cocci_id/* fs/cifs/file.c 1136 */;
}
