cocci_test_suite() {
	irqreturn_t cocci_id/* drivers/i2c/busses/i2c-img-scb.c 914 */;
	void *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 914 */;
	unsigned long cocci_id/* drivers/i2c/busses/i2c-img-scb.c 835 */;
	struct timer_list *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 832 */;
	u8 cocci_id/* drivers/i2c/busses/i2c-img-scb.c 737 */;
	int cocci_id/* drivers/i2c/busses/i2c-img-scb.c 736 */;
	u32 cocci_id/* drivers/i2c/busses/i2c-img-scb.c 733 */;
	struct img_i2c *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 732 */;
	unsigned int cocci_id/* drivers/i2c/busses/i2c-img-scb.c 732 */;
	const unsigned int cocci_id/* drivers/i2c/busses/i2c-img-scb.c 656 */[];
	bool cocci_id/* drivers/i2c/busses/i2c-img-scb.c 530 */;
	void cocci_id/* drivers/i2c/busses/i2c-img-scb.c 472 */;
	const char *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 464 */;
	enum img_i2c_mode cocci_id/* drivers/i2c/busses/i2c-img-scb.c 444 */;
	int cocci_id/* drivers/i2c/busses/i2c-img-scb.c 412 */(struct device *dev);
	struct img_i2c {
		struct i2c_adapter adap;
		void __iomem *base;
		struct clk *scb_clk,*sys_clk;
		unsigned int bitrate;
		bool need_wr_rd_fence;
		struct completion msg_complete;
		spinlock_t lock;
		struct i2c_msg msg;
		bool last_msg;
		int msg_status;
		enum img_i2c_mode mode;
		u32 int_enable;
		u32 line_status;
		struct timer_list check_timer;
		bool t_halt;
		bool at_t_done;
		bool at_slave_event;
		int at_cur_cmd;
		u8 at_cur_data;
		u8 *seq;
		unsigned int raw_timeout;
	} cocci_id/* drivers/i2c/busses/i2c-img-scb.c 365 */;
	const char *constcocci_id/* drivers/i2c/busses/i2c-img-scb.c 354 */[];
	unsigned int cocci_id/* drivers/i2c/busses/i2c-img-scb.c 342 */[];
	u8 cocci_id/* drivers/i2c/busses/i2c-img-scb.c 331 */[];
	struct img_i2c_timings cocci_id/* drivers/i2c/busses/i2c-img-scb.c 303 */[];
	struct img_i2c_timings {
		const char *name;
		unsigned int max_bitrate;
		unsigned int tckh,tckl,tsdh,tsdl;
		unsigned int tp2s,tpl,tph;
	} cocci_id/* drivers/i2c/busses/i2c-img-scb.c 295 */;
	enum img_i2c_mode{MODE_INACTIVE, MODE_RAW, MODE_ATOMIC, MODE_AUTOMATIC, MODE_SEQUENCE, MODE_FATAL, MODE_WAITSTOP, MODE_SUSPEND,} cocci_id/* drivers/i2c/busses/i2c-img-scb.c 283 */;
	struct platform_driver cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1506 */;
	const struct of_device_id cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1500 */[];
	struct device *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1478 */;
	struct img_i2c cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1337 */;
	struct resource *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1333 */;
	struct device_node *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1331 */;
	struct platform_device *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1329 */;
	struct img_i2c_timings cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1157 */;
	const struct i2c_algorithm cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1148 */;
	struct i2c_adapter *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1143 */;
	struct i2c_msg *cocci_id/* drivers/i2c/busses/i2c-img-scb.c 1024 */;
}
