cocci_test_suite() {
	struct kiocb *cocci_id/* fs/fuse/file.c 984 */;
	struct fuse_fill_data cocci_id/* fs/fuse/file.c 956 */;
	struct list_head *cocci_id/* fs/fuse/file.c 952 */;
	struct fuse_fill_data *cocci_id/* fs/fuse/file.c 914 */;
	struct fuse_fill_data {
		struct fuse_io_args *ia;
		struct file *file;
		struct inode *inode;
		unsigned int nr_pages;
		unsigned int max_pages;
	} cocci_id/* fs/fuse/file.c 904 */;
	struct fuse_io_args cocci_id/* fs/fuse/file.c 787 */;
	struct fuse_page_desc cocci_id/* fs/fuse/file.c 786 */;
	struct page *cocci_id/* fs/fuse/file.c 781 */;
	u32 cocci_id/* fs/fuse/file.c 692 */;
	typeof(*ia) cocci_id/* fs/fuse/file.c 676 */;
	struct fuse_io_args *cocci_id/* fs/fuse/file.c 676 */;
	struct fuse_args *cocci_id/* fs/fuse/file.c 673 */;
	void cocci_id/* fs/fuse/file.c 615 */;
	struct kref *cocci_id/* fs/fuse/file.c 583 */;
	struct fuse_release_args {
		struct fuse_args args;
		struct fuse_release_in inarg;
		struct inode *inode;
	} cocci_id/* fs/fuse/file.c 56 */;
	struct fuse_fsync_in cocci_id/* fs/fuse/file.c 488 */;
	struct fuse_flush_in cocci_id/* fs/fuse/file.c 441 */;
	struct fuse_open_in cocci_id/* fs/fuse/file.c 37 */;
	struct fuse_writepage_args *cocci_id/* fs/fuse/file.c 366 */;
	struct fuse_writepage_args {
		struct fuse_io_args ia;
		struct list_head writepages_entry;
		struct list_head queue_entry;
		struct fuse_writepage_args *next;
		struct inode *inode;
	} cocci_id/* fs/fuse/file.c 358 */;
	struct fuse_open_out *cocci_id/* fs/fuse/file.c 35 */;
	u32 *cocci_id/* fs/fuse/file.c 342 */;
	const struct address_space_operations cocci_id/* fs/fuse/file.c 3357 */;
	const struct file_operations cocci_id/* fs/fuse/file.c 3337 */;
	bool cocci_id/* fs/fuse/file.c 3256 */;
	struct fuse_write_out cocci_id/* fs/fuse/file.c 3252 */;
	struct fuse_copy_file_range_in cocci_id/* fs/fuse/file.c 3243 */;
	struct fuse_conn *cocci_id/* fs/fuse/file.c 3241 */;
	struct fuse_inode *cocci_id/* fs/fuse/file.c 3240 */;
	struct inode *cocci_id/* fs/fuse/file.c 3238 */;
	struct fuse_file *cocci_id/* fs/fuse/file.c 3236 */;
	unsigned int cocci_id/* fs/fuse/file.c 3234 */;
	size_t cocci_id/* fs/fuse/file.c 3234 */;
	loff_t cocci_id/* fs/fuse/file.c 3232 */;
	struct file *cocci_id/* fs/fuse/file.c 3232 */;
	ssize_t cocci_id/* fs/fuse/file.c 3232 */;
	struct fuse_fallocate_in cocci_id/* fs/fuse/file.c 3159 */;
	struct fuse_io_priv cocci_id/* fs/fuse/file.c 3074 */;
	struct iattr cocci_id/* fs/fuse/file.c 3028 */;
	struct fuse_notify_poll_wakeup_out *cocci_id/* fs/fuse/file.c 3006 */;
	struct fuse_poll_out cocci_id/* fs/fuse/file.c 2962 */;
	struct fuse_poll_in cocci_id/* fs/fuse/file.c 2961 */;
	__poll_t cocci_id/* fs/fuse/file.c 2957 */;
	poll_table *cocci_id/* fs/fuse/file.c 2957 */;
	struct rb_node *cocci_id/* fs/fuse/file.c 2915 */;
	struct rb_node **cocci_id/* fs/fuse/file.c 2911 */;
	struct fuse_args_pages cocci_id/* fs/fuse/file.c 2712 */;
	struct iov_iter cocci_id/* fs/fuse/file.c 2711 */;
	struct fuse_ioctl_out cocci_id/* fs/fuse/file.c 2704 */;
	struct fuse_ioctl_in cocci_id/* fs/fuse/file.c 2698 */;
	long cocci_id/* fs/fuse/file.c 2693 */;
	struct fuse_release_in cocci_id/* fs/fuse/file.c 268 */;
	compat_size_t cocci_id/* fs/fuse/file.c 2638 */;
	void __user *cocci_id/* fs/fuse/file.c 2632 */;
	unsigned long cocci_id/* fs/fuse/file.c 2628 */;
	struct fuse_ioctl_iovec cocci_id/* fs/fuse/file.c 2623 */;
	struct fuse_ioctl_iovec *cocci_id/* fs/fuse/file.c 2616 */;
	void *cocci_id/* fs/fuse/file.c 2612 */;
	unsigned cocci_id/* fs/fuse/file.c 2612 */;
	struct iovec *cocci_id/* fs/fuse/file.c 2611 */;
	struct iovec cocci_id/* fs/fuse/file.c 2589 */;
	struct compat_iovec *cocci_id/* fs/fuse/file.c 2570 */;
	struct compat_iovec cocci_id/* fs/fuse/file.c 2569 */;
	struct fuse_release_args *cocci_id/* fs/fuse/file.c 250 */;
	struct fuse_lseek_out cocci_id/* fs/fuse/file.c 2494 */;
	struct fuse_lseek_in cocci_id/* fs/fuse/file.c 2489 */;
	struct fuse_bmap_out cocci_id/* fs/fuse/file.c 2459 */;
	struct fuse_bmap_in cocci_id/* fs/fuse/file.c 2458 */;
	sector_t cocci_id/* fs/fuse/file.c 2453 */;
	struct address_space *cocci_id/* fs/fuse/file.c 2453 */;
	struct pid *cocci_id/* fs/fuse/file.c 2388 */;
	struct fuse_lk_out cocci_id/* fs/fuse/file.c 2367 */;
	struct fuse_lk_in cocci_id/* fs/fuse/file.c 2366 */;
	struct fuse_lk_in *cocci_id/* fs/fuse/file.c 2339 */;
	pid_t cocci_id/* fs/fuse/file.c 2338 */;
	const struct file_lock *cocci_id/* fs/fuse/file.c 2338 */;
	struct file_lock *cocci_id/* fs/fuse/file.c 2306 */;
	const struct fuse_file_lock *cocci_id/* fs/fuse/file.c 2305 */;
	int cocci_id/* fs/fuse/file.c 2304 */;
	struct fuse_page_desc **cocci_id/* fs/fuse/file.c 23 */;
	struct vm_area_struct *cocci_id/* fs/fuse/file.c 2282 */;
	const struct vm_operations_struct cocci_id/* fs/fuse/file.c 2275 */;
	vm_fault_t cocci_id/* fs/fuse/file.c 2259 */;
	struct vm_fault *cocci_id/* fs/fuse/file.c 2259 */;
	gfp_t cocci_id/* fs/fuse/file.c 22 */;
	struct page **cocci_id/* fs/fuse/file.c 22 */;
	void **cocci_id/* fs/fuse/file.c 2152 */;
	struct fuse_fill_wb_data cocci_id/* fs/fuse/file.c 2113 */;
	struct fuse_fill_wb_data *cocci_id/* fs/fuse/file.c 1891 */;
	struct fuse_fill_wb_data {
		struct fuse_writepage_args *wpa;
		struct fuse_file *ff;
		struct inode *inode;
		struct page **orig_pages;
		unsigned int max_pages;
	} cocci_id/* fs/fuse/file.c 1883 */;
	struct writeback_control *cocci_id/* fs/fuse/file.c 1763 */;
	struct fuse_file cocci_id/* fs/fuse/file.c 1746 */;
	typeof(*wpa) cocci_id/* fs/fuse/file.c 1692 */;
	struct fuse_writepage_args cocci_id/* fs/fuse/file.c 1682 */;
	__u64 cocci_id/* fs/fuse/file.c 1619 */;
	struct backing_dev_info *cocci_id/* fs/fuse/file.c 1597 */;
	ssize_t cocci_id/* fs/fuse/file.c 1506 */(struct kiocb *iocb,
						  struct iov_iter *iter);
	loff_t *cocci_id/* fs/fuse/file.c 1494 */;
	struct iov_iter *cocci_id/* fs/fuse/file.c 1493 */;
	struct fuse_io_priv *cocci_id/* fs/fuse/file.c 1492 */;
	struct fuse_open_out cocci_id/* fs/fuse/file.c 146 */;
	fl_owner_t cocci_id/* fs/fuse/file.c 1443 */;
	pgoff_t cocci_id/* fs/fuse/file.c 1419 */;
	size_t *cocci_id/* fs/fuse/file.c 1352 */;
	const struct iov_iter *cocci_id/* fs/fuse/file.c 1345 */;
	struct fuse_page_desc *cocci_id/* fs/fuse/file.c 1330 */;
	u64 cocci_id/* fs/fuse/file.c 132 */;
	struct fuse_args_pages *cocci_id/* fs/fuse/file.c 1125 */;
	typeof(*ra) cocci_id/* fs/fuse/file.c 105 */;
	struct fuse_write_in *cocci_id/* fs/fuse/file.c 1046 */;
}
