cocci_test_suite() {
	size_t cocci_id/* fs/btrfs/file-item.c 959 */;
	u8 cocci_id/* fs/btrfs/file-item.c 948 */;
	const int cocci_id/* fs/btrfs/file-item.c 944 */;
	struct extent_map *cocci_id/* fs/btrfs/file-item.c 939 */;
	const bool cocci_id/* fs/btrfs/file-item.c 938 */;
	struct btrfs_file_extent_item *cocci_id/* fs/btrfs/file-item.c 937 */;
	const struct btrfs_path *cocci_id/* fs/btrfs/file-item.c 936 */;
	struct btrfs_inode *cocci_id/* fs/btrfs/file-item.c 935 */;
	void cocci_id/* fs/btrfs/file-item.c 935 */;
	unsigned char *cocci_id/* fs/btrfs/file-item.c 904 */;
	struct btrfs_item cocci_id/* fs/btrfs/file-item.c 852 */;
	char *cocci_id/* fs/btrfs/file-item.c 776 */;
	struct extent_buffer *cocci_id/* fs/btrfs/file-item.c 747 */;
	struct btrfs_ordered_sum *cocci_id/* fs/btrfs/file-item.c 739 */;
	struct btrfs_root *cocci_id/* fs/btrfs/file-item.c 738 */;
	struct btrfs_trans_handle *cocci_id/* fs/btrfs/file-item.c 737 */;
	struct btrfs_file_extent_item cocci_id/* fs/btrfs/file-item.c 62 */;
	struct btrfs_key *cocci_id/* fs/btrfs/file-item.c 544 */;
	const u16 cocci_id/* fs/btrfs/file-item.c 449 */;
	unsigned cocci_id/* fs/btrfs/file-item.c 448 */;
	struct btrfs_ordered_extent *cocci_id/* fs/btrfs/file-item.c 438 */;
	struct btrfs_ordered_sum cocci_id/* fs/btrfs/file-item.c 412 */;
	struct list_head *cocci_id/* fs/btrfs/file-item.c 303 */;
	unsigned long cocci_id/* fs/btrfs/file-item.c 271 */;
	struct btrfs_csum_item cocci_id/* fs/btrfs/file-item.c 259 */;
	struct btrfs_key cocci_id/* fs/btrfs/file-item.c 225 */;
	u16 cocci_id/* fs/btrfs/file-item.c 170 */;
	u32 cocci_id/* fs/btrfs/file-item.c 167 */;
	struct btrfs_path *cocci_id/* fs/btrfs/file-item.c 160 */;
	struct extent_io_tree *cocci_id/* fs/btrfs/file-item.c 159 */;
	struct btrfs_csum_item *cocci_id/* fs/btrfs/file-item.c 158 */;
	struct btrfs_io_bio *cocci_id/* fs/btrfs/file-item.c 157 */;
	struct bvec_iter cocci_id/* fs/btrfs/file-item.c 156 */;
	struct bio_vec cocci_id/* fs/btrfs/file-item.c 155 */;
	struct btrfs_fs_info *cocci_id/* fs/btrfs/file-item.c 154 */;
	u64 cocci_id/* fs/btrfs/file-item.c 152 */;
	u8 *cocci_id/* fs/btrfs/file-item.c 152 */;
	int cocci_id/* fs/btrfs/file-item.c 152 */;
	blk_status_t cocci_id/* fs/btrfs/file-item.c 151 */;
	struct inode *cocci_id/* fs/btrfs/file-item.c 151 */;
	struct bio *cocci_id/* fs/btrfs/file-item.c 151 */;
}
