cocci_test_suite() {
	struct btrfs_tree_block_info *cocci_id/* fs/btrfs/print-tree.c 69 */;
	struct btrfs_extent_item cocci_id/* fs/btrfs/print-tree.c 60 */;
	u64 cocci_id/* fs/btrfs/print-tree.c 51 */;
	unsigned long cocci_id/* fs/btrfs/print-tree.c 48 */;
	struct btrfs_disk_key cocci_id/* fs/btrfs/print-tree.c 47 */;
	struct btrfs_extent_inline_ref *cocci_id/* fs/btrfs/print-tree.c 44 */;
	struct btrfs_extent_item *cocci_id/* fs/btrfs/print-tree.c 43 */;
	bool cocci_id/* fs/btrfs/print-tree.c 324 */;
	struct btrfs_dev_extent cocci_id/* fs/btrfs/print-tree.c 283 */;
	struct btrfs_dev_item cocci_id/* fs/btrfs/print-tree.c 279 */;
	struct btrfs_chunk cocci_id/* fs/btrfs/print-tree.c 275 */;
	struct btrfs_block_group_item cocci_id/* fs/btrfs/print-tree.c 266 */;
	struct btrfs_file_extent_item cocci_id/* fs/btrfs/print-tree.c 245 */;
	struct btrfs_dev_item *cocci_id/* fs/btrfs/print-tree.c 24 */;
	struct btrfs_shared_data_ref cocci_id/* fs/btrfs/print-tree.c 239 */;
	struct btrfs_extent_data_ref cocci_id/* fs/btrfs/print-tree.c 234 */;
	struct btrfs_root_item cocci_id/* fs/btrfs/print-tree.c 217 */;
	struct btrfs_dir_item cocci_id/* fs/btrfs/print-tree.c 210 */;
	struct btrfs_inode_item cocci_id/* fs/btrfs/print-tree.c 203 */;
	struct btrfs_key cocci_id/* fs/btrfs/print-tree.c 180 */;
	struct btrfs_dev_extent *cocci_id/* fs/btrfs/print-tree.c 179 */;
	struct btrfs_shared_data_ref *cocci_id/* fs/btrfs/print-tree.c 178 */;
	struct btrfs_extent_data_ref *cocci_id/* fs/btrfs/print-tree.c 177 */;
	struct btrfs_file_extent_item *cocci_id/* fs/btrfs/print-tree.c 176 */;
	struct btrfs_block_group_item *cocci_id/* fs/btrfs/print-tree.c 175 */;
	struct btrfs_inode_item *cocci_id/* fs/btrfs/print-tree.c 174 */;
	struct btrfs_dir_item *cocci_id/* fs/btrfs/print-tree.c 173 */;
	struct btrfs_root_item *cocci_id/* fs/btrfs/print-tree.c 172 */;
	struct btrfs_item *cocci_id/* fs/btrfs/print-tree.c 171 */;
	u32 cocci_id/* fs/btrfs/print-tree.c 170 */;
	int cocci_id/* fs/btrfs/print-tree.c 169 */;
	struct btrfs_fs_info *cocci_id/* fs/btrfs/print-tree.c 168 */;
	struct extent_buffer *cocci_id/* fs/btrfs/print-tree.c 166 */;
	void cocci_id/* fs/btrfs/print-tree.c 166 */;
	__le64 cocci_id/* fs/btrfs/print-tree.c 137 */;
	unsigned long long cocci_id/* fs/btrfs/print-tree.c 100 */;
	struct btrfs_chunk *cocci_id/* fs/btrfs/print-tree.c 10 */;
}
