cocci_test_suite() {
	struct jffs2_mount_opts *cocci_id/* fs/jffs2/super.c 87 */;
	struct seq_file *cocci_id/* fs/jffs2/super.c 84 */;
	const char *cocci_id/* fs/jffs2/super.c 64 */;
	unsigned int cocci_id/* fs/jffs2/super.c 64 */;
	void *cocci_id/* fs/jffs2/super.c 56 */;
	void __exit cocci_id/* fs/jffs2/super.c 407 */;
	void cocci_id/* fs/jffs2/super.c 407 */;
	struct jffs2_inode_info *cocci_id/* fs/jffs2/super.c 40 */;
	struct super_block *cocci_id/* fs/jffs2/super.c 38 */;
	struct inode *cocci_id/* fs/jffs2/super.c 38 */;
	struct jffs2_inode_info cocci_id/* fs/jffs2/super.c 373 */;
	struct jffs2_raw_summary cocci_id/* fs/jffs2/super.c 361 */;
	struct jffs2_raw_inode cocci_id/* fs/jffs2/super.c 360 */;
	struct kmem_cache *cocci_id/* fs/jffs2/super.c 36 */;
	struct jffs2_raw_dirent cocci_id/* fs/jffs2/super.c 359 */;
	struct jffs2_unknown_node cocci_id/* fs/jffs2/super.c 358 */;
	int cocci_id/* fs/jffs2/super.c 349 */;
	int __init cocci_id/* fs/jffs2/super.c 347 */;
	void cocci_id/* fs/jffs2/super.c 34 */(struct super_block *);
	struct file_system_type cocci_id/* fs/jffs2/super.c 338 */;
	struct jffs2_sb_info cocci_id/* fs/jffs2/super.c 298 */;
	const struct fs_context_operations cocci_id/* fs/jffs2/super.c 287 */;
	struct jffs2_sb_info *cocci_id/* fs/jffs2/super.c 249 */;
	struct fs_context *cocci_id/* fs/jffs2/super.c 247 */;
	const struct super_operations cocci_id/* fs/jffs2/super.c 232 */;
	struct fs_parse_result cocci_id/* fs/jffs2/super.c 195 */;
	struct fs_parameter *cocci_id/* fs/jffs2/super.c 193 */;
	const struct fs_parameter_description cocci_id/* fs/jffs2/super.c 187 */;
	const struct fs_parameter_enum cocci_id/* fs/jffs2/super.c 176 */[];
	const struct fs_parameter_spec cocci_id/* fs/jffs2/super.c 170 */[];
	enum{Opt_override_compr, Opt_rp_size,} cocci_id/* fs/jffs2/super.c 165 */;
	const struct export_operations cocci_id/* fs/jffs2/super.c 152 */;
	uint32_t cocci_id/* fs/jffs2/super.c 138 */;
	struct fid *cocci_id/* fs/jffs2/super.c 121 */;
	struct dentry *cocci_id/* fs/jffs2/super.c 121 */;
	uint64_t cocci_id/* fs/jffs2/super.c 112 */;
}
