cocci_test_suite() {
	union jffs2_node_union cocci_id/* fs/jffs2/readinode.c 980 */;
	union jffs2_node_union *cocci_id/* fs/jffs2/readinode.c 970 */;
	int *cocci_id/* fs/jffs2/readinode.c 925 */;
	struct jffs2_unknown_node *cocci_id/* fs/jffs2/readinode.c 872 */;
	void **cocci_id/* fs/jffs2/readinode.c 67 */;
	struct jffs2_raw_dirent *cocci_id/* fs/jffs2/readinode.c 587 */;
	struct rb_root cocci_id/* fs/jffs2/readinode.c 456 */;
	struct jffs2_inode_info *cocci_id/* fs/jffs2/readinode.c 452 */;
	struct jffs2_raw_inode cocci_id/* fs/jffs2/readinode.c 43 */;
	struct rb_node **cocci_id/* fs/jffs2/readinode.c 405 */;
	struct rb_root *cocci_id/* fs/jffs2/readinode.c 402 */;
	struct rb_node *cocci_id/* fs/jffs2/readinode.c 402 */;
	void cocci_id/* fs/jffs2/readinode.c 402 */;
	size_t cocci_id/* fs/jffs2/readinode.c 38 */;
	uint32_t cocci_id/* fs/jffs2/readinode.c 37 */;
	unsigned char *cocci_id/* fs/jffs2/readinode.c 36 */;
	struct jffs2_eraseblock *cocci_id/* fs/jffs2/readinode.c 35 */;
	struct jffs2_tmp_dnode_info cocci_id/* fs/jffs2/readinode.c 344 */;
	struct jffs2_raw_node_ref *cocci_id/* fs/jffs2/readinode.c 33 */;
	struct jffs2_tmp_dnode_info *cocci_id/* fs/jffs2/readinode.c 31 */;
	struct jffs2_sb_info *cocci_id/* fs/jffs2/readinode.c 31 */;
	int cocci_id/* fs/jffs2/readinode.c 31 */;
	struct jffs2_readinode_info *cocci_id/* fs/jffs2/readinode.c 219 */;
	void *cocci_id/* fs/jffs2/readinode.c 1426 */;
	struct jffs2_full_dirent *cocci_id/* fs/jffs2/readinode.c 1399 */;
	struct jffs2_inode_cache *cocci_id/* fs/jffs2/readinode.c 1376 */;
	struct jffs2_inode_cache cocci_id/* fs/jffs2/readinode.c 1362 */;
	struct jffs2_raw_inode *cocci_id/* fs/jffs2/readinode.c 1313 */;
	char *cocci_id/* fs/jffs2/readinode.c 1262 */;
	struct jffs2_readinode_info cocci_id/* fs/jffs2/readinode.c 1133 */;
	struct jffs2_unknown_node cocci_id/* fs/jffs2/readinode.c 1095 */;
	struct jffs2_raw_dirent cocci_id/* fs/jffs2/readinode.c 1066 */;
}
