cocci_test_suite() {
	void cocci_id/* fs/jbd2/journal.c 99 */(journal_t *journal, int errno);
	loff_t *cocci_id/* fs/jbd2/journal.c 983 */;
	struct seq_file *cocci_id/* fs/jbd2/journal.c 983 */;
	struct jbd2_stats_proc_session {
		journal_t *journal;
		struct transaction_stats_s *stats;
		int start;
		int max;
	} cocci_id/* fs/jbd2/journal.c 971 */;
	unsigned long cocci_id/* fs/jbd2/journal.c 920 */;
	unsigned long *cocci_id/* fs/jbd2/journal.c 882 */;
	tid_t *cocci_id/* fs/jbd2/journal.c 881 */;
	struct jbd2_journal_block_tail cocci_id/* fs/jbd2/journal.c 865 */;
	__u32 cocci_id/* fs/jbd2/journal.c 859 */;
	struct jbd2_journal_block_tail *cocci_id/* fs/jbd2/journal.c 858 */;
	journal_header_t *cocci_id/* fs/jbd2/journal.c 832 */;
	unsigned long long cocci_id/* fs/jbd2/journal.c 797 */;
	unsigned long long *cocci_id/* fs/jbd2/journal.c 794 */;
	tid_t cocci_id/* fs/jbd2/journal.c 538 */;
	ushort cocci_id/* fs/jbd2/journal.c 52 */;
	unsigned int *cocci_id/* fs/jbd2/journal.c 443 */;
	__be32 *cocci_id/* fs/jbd2/journal.c 395 */;
	struct page *cocci_id/* fs/jbd2/journal.c 345 */;
	sector_t cocci_id/* fs/jbd2/journal.c 338 */;
	struct buffer_head **cocci_id/* fs/jbd2/journal.c 337 */;
	struct task_struct *cocci_id/* fs/jbd2/journal.c 275 */;
	struct journal_superblock_s cocci_id/* fs/jbd2/journal.c 2749 */;
	int __init cocci_id/* fs/jbd2/journal.c 2689 */;
	void __exit cocci_id/* fs/jbd2/journal.c 2663 */;
	void __init cocci_id/* fs/jbd2/journal.c 2658 */;
	wait_queue_head_t *cocci_id/* fs/jbd2/journal.c 2636 */;
	struct jbd2_inode *cocci_id/* fs/jbd2/journal.c 2611 */;
	struct journal_head *cocci_id/* fs/jbd2/journal.c 2557 */;
	struct buffer_head *cocci_id/* fs/jbd2/journal.c 2555 */;
	struct journal_head cocci_id/* fs/jbd2/journal.c 2412 */;
	atomic_t cocci_id/* fs/jbd2/journal.c 2405 */;
	gfp_t cocci_id/* fs/jbd2/journal.c 2374 */;
	void *cocci_id/* fs/jbd2/journal.c 2374 */;
	struct kmem_cache *cocci_id/* fs/jbd2/journal.c 2363 */;
	size_t cocci_id/* fs/jbd2/journal.c 2363 */;
	const char *cocci_id/* fs/jbd2/journal.c 2316 */[JBD2_MAX_SLABS];
	struct kmem_cache *cocci_id/* fs/jbd2/journal.c 2314 */[JBD2_MAX_SLABS];
	struct inode *cocci_id/* fs/jbd2/journal.c 2272 */;
	transaction_t *cocci_id/* fs/jbd2/journal.c 2116 */;
	journal_t *cocci_id/* fs/jbd2/journal.c 2114 */;
	journal_superblock_t *cocci_id/* fs/jbd2/journal.c 1819 */;
	struct timer_list *cocci_id/* fs/jbd2/journal.c 146 */;
	journal_superblock_t cocci_id/* fs/jbd2/journal.c 136 */;
	__be32 cocci_id/* fs/jbd2/journal.c 129 */;
	long long cocci_id/* fs/jbd2/journal.c 1258 */;
	char *cocci_id/* fs/jbd2/journal.c 1247 */;
	struct block_device *cocci_id/* fs/jbd2/journal.c 1219 */;
	struct lock_class_key cocci_id/* fs/jbd2/journal.c 1125 */;
	struct proc_dir_entry *cocci_id/* fs/jbd2/journal.c 1085 */;
	const struct file_operations cocci_id/* fs/jbd2/journal.c 1077 */;
	va_list cocci_id/* fs/jbd2/journal.c 107 */;
	struct va_format cocci_id/* fs/jbd2/journal.c 106 */;
	struct transaction_stats_s cocci_id/* fs/jbd2/journal.c 1045 */;
	unsigned int cocci_id/* fs/jbd2/journal.c 104 */;
	struct jbd2_stats_proc_session *cocci_id/* fs/jbd2/journal.c 1039 */;
	struct file *cocci_id/* fs/jbd2/journal.c 1036 */;
	const char *cocci_id/* fs/jbd2/journal.c 103 */;
	int cocci_id/* fs/jbd2/journal.c 103 */;
	void cocci_id/* fs/jbd2/journal.c 103 */;
	const struct seq_operations cocci_id/* fs/jbd2/journal.c 1029 */;
	int cocci_id/* fs/jbd2/journal.c 100 */(size_t slab_size);
}
