cocci_test_suite() {
	struct inode *cocci_id/* fs/romfs/super.c 97 */(struct super_block *sb,
							unsigned long pos);
	const unsigned char cocci_id/* fs/romfs/super.c 93 */[];
	const umode_t cocci_id/* fs/romfs/super.c 82 */[8];
	struct kmem_cache *cocci_id/* fs/romfs/super.c 80 */;
	void __exit cocci_id/* fs/romfs/super.c 652 */;
	void cocci_id/* fs/romfs/super.c 652 */;
	struct romfs_inode_info cocci_id/* fs/romfs/super.c 629 */;
	int cocci_id/* fs/romfs/super.c 623 */;
	int __init cocci_id/* fs/romfs/super.c 621 */;
	struct file_system_type cocci_id/* fs/romfs/super.c 599 */;
	const struct fs_context_operations cocci_id/* fs/romfs/super.c 566 */;
	unsigned cocci_id/* fs/romfs/super.c 524 */;
	void *cocci_id/* fs/romfs/super.c 494 */;
	size_t cocci_id/* fs/romfs/super.c 465 */;
	const char *cocci_id/* fs/romfs/super.c 464 */;
	unsigned long cocci_id/* fs/romfs/super.c 463 */;
	struct romfs_super_block *cocci_id/* fs/romfs/super.c 461 */;
	struct fs_context *cocci_id/* fs/romfs/super.c 459 */;
	const __be32 *cocci_id/* fs/romfs/super.c 444 */;
	__u32 cocci_id/* fs/romfs/super.c 442 */;
	const void *cocci_id/* fs/romfs/super.c 442 */;
	const struct super_operations cocci_id/* fs/romfs/super.c 433 */;
	u32 cocci_id/* fs/romfs/super.c 418 */;
	u64 cocci_id/* fs/romfs/super.c 395 */;
	struct kstatfs *cocci_id/* fs/romfs/super.c 392 */;
	struct romfs_inode_info *cocci_id/* fs/romfs/super.c 375 */;
	struct super_block *cocci_id/* fs/romfs/super.c 373 */;
	struct inode *cocci_id/* fs/romfs/super.c 373 */;
	umode_t cocci_id/* fs/romfs/super.c 286 */;
	struct romfs_inode cocci_id/* fs/romfs/super.c 281 */;
	const struct inode_operations cocci_id/* fs/romfs/super.c 270 */;
	const struct file_operations cocci_id/* fs/romfs/super.c 264 */;
	unsigned int cocci_id/* fs/romfs/super.c 213 */;
	struct dentry *cocci_id/* fs/romfs/super.c 212 */;
	char cocci_id/* fs/romfs/super.c 157 */[ROMFS_MAXFN];
	struct file *cocci_id/* fs/romfs/super.c 151 */;
	struct dir_context *cocci_id/* fs/romfs/super.c 151 */;
	const struct address_space_operations cocci_id/* fs/romfs/super.c 144 */;
	loff_t cocci_id/* fs/romfs/super.c 105 */;
	struct page *cocci_id/* fs/romfs/super.c 102 */;
}
