cocci_test_suite() {
	int cocci_id/* fs/gfs2/inode.c 842 */;
	struct gfs2_glock *cocci_id/* fs/gfs2/inode.c 841 */;
	struct gfs2_holder cocci_id/* fs/gfs2/inode.c 840 */;
	struct file *cocci_id/* fs/gfs2/inode.c 836 */;
	struct inode *cocci_id/* fs/gfs2/inode.c 835 */;
	struct dentry *cocci_id/* fs/gfs2/inode.c 835 */;
	struct gfs2_diradd cocci_id/* fs/gfs2/inode.c 592 */;
	struct gfs2_holder cocci_id/* fs/gfs2/inode.c 584 */[2];
	struct posix_acl *cocci_id/* fs/gfs2/inode.c 583 */;
	unsigned int cocci_id/* fs/gfs2/inode.c 580 */;
	dev_t cocci_id/* fs/gfs2/inode.c 579 */;
	const char *cocci_id/* fs/gfs2/inode.c 579 */;
	void *cocci_id/* fs/gfs2/inode.c 549 */;
	const struct xattr *cocci_id/* fs/gfs2/inode.c 548 */;
	struct super_block *cocci_id/* fs/gfs2/inode.c 54 */;
	struct gfs2_diradd *cocci_id/* fs/gfs2/inode.c 514 */;
	const struct gfs2_diradd *cocci_id/* fs/gfs2/inode.c 506 */;
	struct gfs2_meta_header cocci_id/* fs/gfs2/inode.c 439 */;
	struct gfs2_ea_header *cocci_id/* fs/gfs2/inode.c 434 */;
	struct gfs2_dirent *cocci_id/* fs/gfs2/inode.c 409 */;
	struct gfs2_dinode *cocci_id/* fs/gfs2/inode.c 408 */;
	const struct gfs2_inode *cocci_id/* fs/gfs2/inode.c 406 */;
	void cocci_id/* fs/gfs2/inode.c 405 */;
	struct gfs2_alloc_parms cocci_id/* fs/gfs2/inode.c 375 */;
	struct gfs2_sbd *cocci_id/* fs/gfs2/inode.c 374 */;
	u32 cocci_id/* fs/gfs2/inode.c 372 */;
	struct gfs2_inode *cocci_id/* fs/gfs2/inode.c 372 */;
	unsigned *cocci_id/* fs/gfs2/inode.c 372 */;
	umode_t cocci_id/* fs/gfs2/inode.c 330 */;
	const struct qstr *cocci_id/* fs/gfs2/inode.c 329 */;
	struct qstr cocci_id/* fs/gfs2/inode.c 246 */;
	u64 *cocci_id/* fs/gfs2/inode.c 216 */;
	const struct inode_operations cocci_id/* fs/gfs2/inode.c 2099 */;
	loff_t cocci_id/* fs/gfs2/inode.c 2051 */;
	u64 cocci_id/* fs/gfs2/inode.c 2030 */;
	struct fiemap_extent_info *cocci_id/* fs/gfs2/inode.c 2029 */;
	const struct path *cocci_id/* fs/gfs2/inode.c 1993 */;
	struct kstat *cocci_id/* fs/gfs2/inode.c 1993 */;
	s64 cocci_id/* fs/gfs2/inode.c 1914 */;
	kgid_t cocci_id/* fs/gfs2/inode.c 1869 */;
	kuid_t cocci_id/* fs/gfs2/inode.c 1868 */;
	struct iattr *cocci_id/* fs/gfs2/inode.c 1833 */;
	struct gfs2_dinode cocci_id/* fs/gfs2/inode.c 1785 */;
	char *cocci_id/* fs/gfs2/inode.c 1755 */;
	struct buffer_head *cocci_id/* fs/gfs2/inode.c 1753 */;
	struct delayed_call *cocci_id/* fs/gfs2/inode.c 1749 */;
	struct gfs2_holder cocci_id/* fs/gfs2/inode.c 1594 */[4];
	struct gfs2_rgrpd *cocci_id/* fs/gfs2/inode.c 1352 */;
	bool cocci_id/* fs/gfs2/inode.c 1237 */;
	unsigned cocci_id/* fs/gfs2/inode.c 1233 */;
	struct gfs2_holder cocci_id/* fs/gfs2/inode.c 1103 */[3];
	const struct dentry *cocci_id/* fs/gfs2/inode.c 1063 */;
}
