cocci_test_suite() {
	struct gfs2_statfs_change_host cocci_id/* fs/gfs2/super.c 955 */;
	struct kstatfs *cocci_id/* fs/gfs2/super.c 951 */;
	unsigned int cocci_id/* fs/gfs2/super.c 91 */;
	struct gfs2_holder *cocci_id/* fs/gfs2/super.c 849 */;
	struct list_head *cocci_id/* fs/gfs2/super.c 73 */;
	struct gfs2_sbd cocci_id/* fs/gfs2/super.c 723 */;
	struct work_struct *cocci_id/* fs/gfs2/super.c 719 */;
	struct gfs2_jdesc cocci_id/* fs/gfs2/super.c 65 */;
	struct list_head cocci_id/* fs/gfs2/super.c 55 */;
	struct buffer_head *cocci_id/* fs/gfs2/super.c 549 */;
	bool cocci_id/* fs/gfs2/super.c 509 */;
	struct backing_dev_info *cocci_id/* fs/gfs2/super.c 507 */;
	struct writeback_control *cocci_id/* fs/gfs2/super.c 502 */;
	struct gfs2_dinode *cocci_id/* fs/gfs2/super.c 459 */;
	const struct gfs2_inode *cocci_id/* fs/gfs2/super.c 457 */;
	void *cocci_id/* fs/gfs2/super.c 457 */;
	void cocci_id/* fs/gfs2/super.c 457 */;
	struct lfcc cocci_id/* fs/gfs2/super.c 412 */;
	struct gfs2_log_header_host cocci_id/* fs/gfs2/super.c 408 */;
	struct lfcc *cocci_id/* fs/gfs2/super.c 406 */;
	struct lfcc {
		struct list_head list;
		struct gfs2_holder gh;
	} cocci_id/* fs/gfs2/super.c 387 */;
	struct gfs2_statfs_change cocci_id/* fs/gfs2/super.c 326 */;
	struct gfs2_dinode cocci_id/* fs/gfs2/super.c 297 */;
	struct gfs2_statfs_change_host *cocci_id/* fs/gfs2/super.c 280 */;
	s64 cocci_id/* fs/gfs2/super.c 276 */;
	struct gfs2_statfs_change *cocci_id/* fs/gfs2/super.c 223 */;
	const struct gfs2_statfs_change_host *cocci_id/* fs/gfs2/super.c 221 */;
	const struct gfs2_statfs_change *cocci_id/* fs/gfs2/super.c 214 */;
	const void *cocci_id/* fs/gfs2/super.c 212 */;
	const struct super_operations cocci_id/* fs/gfs2/super.c 1415 */;
	struct gfs2_inode *cocci_id/* fs/gfs2/super.c 1397 */;
	struct super_block *cocci_id/* fs/gfs2/super.c 1395 */;
	struct inode *cocci_id/* fs/gfs2/super.c 1395 */;
	struct address_space *cocci_id/* fs/gfs2/super.c 1251 */;
	struct task_struct *cocci_id/* fs/gfs2/super.c 123 */;
	struct gfs2_holder cocci_id/* fs/gfs2/super.c 1163 */;
	struct gfs2_rgrpd *cocci_id/* fs/gfs2/super.c 1162 */;
	struct gfs2_sbd *cocci_id/* fs/gfs2/super.c 1161 */;
	int cocci_id/* fs/gfs2/super.c 1159 */;
	const char *cocci_id/* fs/gfs2/super.c 1119 */;
	char *cocci_id/* fs/gfs2/super.c 1069 */;
	u64 cocci_id/* fs/gfs2/super.c 106 */;
	struct gfs2_args *cocci_id/* fs/gfs2/super.c 1049 */;
	struct seq_file *cocci_id/* fs/gfs2/super.c 1046 */;
	struct dentry *cocci_id/* fs/gfs2/super.c 1046 */;
	const struct dentry *cocci_id/* fs/gfs2/super.c 1028 */;
	struct gfs2_jdesc *cocci_id/* fs/gfs2/super.c 102 */;
	struct gfs2_glock *cocci_id/* fs/gfs2/super.c 1004 */;
}
