cocci_test_suite() {
	const char *cocci_id/* fs/ntfs/attrib.c 856 */;
	ATTR_LIST_ENTRY *cocci_id/* fs/ntfs/attrib.c 850 */;
	ntfschar *cocci_id/* fs/ntfs/attrib.c 581 */;
	const u8 *cocci_id/* fs/ntfs/attrib.c 577 */;
	const u32 cocci_id/* fs/ntfs/attrib.c 576 */;
	const IGNORE_CASE_BOOL cocci_id/* fs/ntfs/attrib.c 576 */;
	const ntfschar *cocci_id/* fs/ntfs/attrib.c 575 */;
	const VCN cocci_id/* fs/ntfs/attrib.c 450 */;
	const bool cocci_id/* fs/ntfs/attrib.c 328 */;
	LCN cocci_id/* fs/ntfs/attrib.c 327 */;
	struct buffer_head *cocci_id/* fs/ntfs/attrib.c 2558 */;
	pgoff_t cocci_id/* fs/ntfs/attrib.c 2485 */;
	struct address_space *cocci_id/* fs/ntfs/attrib.c 2482 */;
	const u8 cocci_id/* fs/ntfs/attrib.c 2479 */;
	u8 *cocci_id/* fs/ntfs/attrib.c 2288 */;
	long long cocci_id/* fs/ntfs/attrib.c 2243 */;
	unsigned long long cocci_id/* fs/ntfs/attrib.c 1916 */;
	unsigned cocci_id/* fs/ntfs/attrib.c 1915 */;
	bool cocci_id/* fs/ntfs/attrib.c 1905 */;
	u32 cocci_id/* fs/ntfs/attrib.c 1904 */;
	unsigned long cocci_id/* fs/ntfs/attrib.c 1902 */;
	runlist_element *cocci_id/* fs/ntfs/attrib.c 1901 */;
	ntfs_attr_search_ctx *cocci_id/* fs/ntfs/attrib.c 1900 */;
	ATTR_RECORD *cocci_id/* fs/ntfs/attrib.c 1899 */;
	MFT_RECORD *cocci_id/* fs/ntfs/attrib.c 1898 */;
	ntfs_volume *cocci_id/* fs/ntfs/attrib.c 1896 */;
	struct inode *cocci_id/* fs/ntfs/attrib.c 1895 */;
	VCN cocci_id/* fs/ntfs/attrib.c 1893 */;
	const s64 cocci_id/* fs/ntfs/attrib.c 1891 */;
	s64 cocci_id/* fs/ntfs/attrib.c 1890 */;
	ntfs_inode *cocci_id/* fs/ntfs/attrib.c 1890 */;
	ATTR_RECORD cocci_id/* fs/ntfs/attrib.c 1745 */;
	ntfschar cocci_id/* fs/ntfs/attrib.c 1632 */;
	u8 cocci_id/* fs/ntfs/attrib.c 1536 */;
	struct page *cocci_id/* fs/ntfs/attrib.c 1530 */;
	ATTR_DEF *cocci_id/* fs/ntfs/attrib.c 1366 */;
	const ATTR_TYPE cocci_id/* fs/ntfs/attrib.c 1364 */;
	const ntfs_volume *cocci_id/* fs/ntfs/attrib.c 1364 */;
	int cocci_id/* fs/ntfs/attrib.c 1364 */;
	ntfs_attr_search_ctx cocci_id/* fs/ntfs/attrib.c 1206 */;
	void cocci_id/* fs/ntfs/attrib.c 1203 */;
}
