cocci_test_suite() {
	loff_t cocci_id/* fs/ntfs/file.c 98 */;
	s64 cocci_id/* fs/ntfs/file.c 97 */;
	const s64 cocci_id/* fs/ntfs/file.c 95 */;
	ntfs_inode *cocci_id/* fs/ntfs/file.c 95 */;
	struct {
		u8 runlist_merged:1;
		u8 mft_attr_mapped:1;
		u8 mp_rebuilt:1;
		u8 attr_switched:1;
	} cocci_id/* fs/ntfs/file.c 592 */;
	unsigned char cocci_id/* fs/ntfs/file.c 591 */;
	runlist_element *cocci_id/* fs/ntfs/file.c 581 */;
	sector_t cocci_id/* fs/ntfs/file.c 576 */;
	const unsigned cocci_id/* fs/ntfs/file.c 495 */;
	pgoff_t cocci_id/* fs/ntfs/file.c 495 */;
	struct page **cocci_id/* fs/ntfs/file.c 495 */;
	struct address_space *cocci_id/* fs/ntfs/file.c 494 */;
	int cocci_id/* fs/ntfs/file.c 494 */;
	u64 cocci_id/* fs/ntfs/file.c 382 */;
	const struct inode_operations cocci_id/* fs/ntfs/file.c 2026 */;
	const struct file_operations cocci_id/* fs/ntfs/file.c 2024 */;
	struct file *cocci_id/* fs/ntfs/file.c 1970 */;
	struct kiocb *cocci_id/* fs/ntfs/file.c 1925 */;
	ssize_t cocci_id/* fs/ntfs/file.c 1925 */;
	long cocci_id/* fs/ntfs/file.c 1912 */;
	LCN cocci_id/* fs/ntfs/file.c 1740 */;
	VCN cocci_id/* fs/ntfs/file.c 1739 */;
	struct page *cocci_id/* fs/ntfs/file.c 1737 */[NTFS_MAX_PAGES_PER_CLUSTER];
	ntfs_volume *cocci_id/* fs/ntfs/file.c 1736 */;
	struct iov_iter cocci_id/* fs/ntfs/file.c 1690 */;
	struct iov_iter *cocci_id/* fs/ntfs/file.c 1686 */;
	long long cocci_id/* fs/ntfs/file.c 1564 */;
	char *cocci_id/* fs/ntfs/file.c 1550 */;
	bool cocci_id/* fs/ntfs/file.c 1407 */;
	struct buffer_head *cocci_id/* fs/ntfs/file.c 1391 */;
	size_t cocci_id/* fs/ntfs/file.c 1386 */;
	void cocci_id/* fs/ntfs/file.c 1360 */;
	unsigned long long cocci_id/* fs/ntfs/file.c 121 */;
	unsigned cocci_id/* fs/ntfs/file.c 120 */;
	u32 cocci_id/* fs/ntfs/file.c 110 */;
	u8 *cocci_id/* fs/ntfs/file.c 108 */;
	struct page *cocci_id/* fs/ntfs/file.c 107 */;
	ntfs_attr_search_ctx *cocci_id/* fs/ntfs/file.c 105 */;
	ATTR_RECORD *cocci_id/* fs/ntfs/file.c 104 */;
	MFT_RECORD *cocci_id/* fs/ntfs/file.c 103 */;
	struct inode *cocci_id/* fs/ntfs/file.c 101 */;
	unsigned long cocci_id/* fs/ntfs/file.c 100 */;
}
