cocci_test_suite() {
	struct ocfs2_dquot *cocci_id/* fs/ocfs2/quota_global.c 995 */;
	unsigned long cocci_id/* fs/ocfs2/quota_global.c 910 */;
	struct kqid *cocci_id/* fs/ocfs2/quota_global.c 877 */;
	handle_t *cocci_id/* fs/ocfs2/quota_global.c 802 */;
	struct inode *cocci_id/* fs/ocfs2/quota_global.c 800 */;
	struct ocfs2_super *cocci_id/* fs/ocfs2/quota_global.c 797 */;
	struct mem_dqblk *cocci_id/* fs/ocfs2/quota_global.c 74 */;
	struct ocfs2_global_disk_dqblk *cocci_id/* fs/ocfs2/quota_global.c 73 */;
	void *cocci_id/* fs/ocfs2/quota_global.c 71 */;
	struct llist_node *cocci_id/* fs/ocfs2/quota_global.c 701 */;
	struct ocfs2_super cocci_id/* fs/ocfs2/quota_global.c 699 */;
	struct work_struct *cocci_id/* fs/ocfs2/quota_global.c 697 */;
	void cocci_id/* fs/ocfs2/quota_global.c 69 */(struct work_struct *work);
	struct ocfs2_mem_dqinfo cocci_id/* fs/ocfs2/quota_global.c 639 */;
	unsigned cocci_id/* fs/ocfs2/quota_global.c 570 */;
	long long cocci_id/* fs/ocfs2/quota_global.c 519 */;
	time64_t cocci_id/* fs/ocfs2/quota_global.c 492 */;
	s64 cocci_id/* fs/ocfs2/quota_global.c 491 */;
	struct ocfs2_global_disk_dqblk cocci_id/* fs/ocfs2/quota_global.c 490 */;
	struct dquot *cocci_id/* fs/ocfs2/quota_global.c 484 */;
	struct quota_info *cocci_id/* fs/ocfs2/quota_global.c 448 */;
	char *cocci_id/* fs/ocfs2/quota_global.c 433 */;
	ssize_t cocci_id/* fs/ocfs2/quota_global.c 422 */;
	struct ocfs2_global_disk_dqinfo cocci_id/* fs/ocfs2/quota_global.c 421 */;
	struct ocfs2_mem_dqinfo *cocci_id/* fs/ocfs2/quota_global.c 420 */;
	struct mem_dqinfo *cocci_id/* fs/ocfs2/quota_global.c 419 */;
	struct super_block *cocci_id/* fs/ocfs2/quota_global.c 417 */;
	int cocci_id/* fs/ocfs2/quota_global.c 417 */;
	u64 cocci_id/* fs/ocfs2/quota_global.c 346 */;
	unsigned int cocci_id/* fs/ocfs2/quota_global.c 341 */[OCFS2_MAXQUOTAS];
	struct buffer_head *cocci_id/* fs/ocfs2/quota_global.c 301 */;
	unsigned long long cocci_id/* fs/ocfs2/quota_global.c 232 */;
	const char *cocci_id/* fs/ocfs2/quota_global.c 217 */;
	sector_t cocci_id/* fs/ocfs2/quota_global.c 174 */;
	loff_t cocci_id/* fs/ocfs2/quota_global.c 168 */;
	size_t cocci_id/* fs/ocfs2/quota_global.c 168 */;
	struct buffer_head **cocci_id/* fs/ocfs2/quota_global.c 152 */;
	struct ocfs2_disk_dqtrailer *cocci_id/* fs/ocfs2/quota_global.c 136 */;
	const struct qtree_fmt_operations cocci_id/* fs/ocfs2/quota_global.c 128 */;
	const struct dquot_operations cocci_id/* fs/ocfs2/quota_global.c 1008 */;
	void cocci_id/* fs/ocfs2/quota_global.c 1003 */;
}
