cocci_test_suite() {
	struct aml_resource_uart_serialbus cocci_id/* drivers/acpi/acpica/utresrc.c 66 */;
	struct aml_resource_spi_serialbus cocci_id/* drivers/acpi/acpica/utresrc.c 65 */;
	struct aml_resource_i2c_serialbus cocci_id/* drivers/acpi/acpica/utresrc.c 64 */;
	const u8 cocci_id/* drivers/acpi/acpica/utresrc.c 62 */[];
	struct aml_resource_pin_group_config cocci_id/* drivers/acpi/acpica/utresrc.c 59 */;
	struct aml_resource_pin_group_function cocci_id/* drivers/acpi/acpica/utresrc.c 58 */;
	struct aml_resource_pin_group cocci_id/* drivers/acpi/acpica/utresrc.c 57 */;
	void **cocci_id/* drivers/acpi/acpica/utresrc.c 561 */;
	struct aml_resource_pin_config cocci_id/* drivers/acpi/acpica/utresrc.c 56 */;
	struct aml_resource_common_serialbus cocci_id/* drivers/acpi/acpica/utresrc.c 55 */;
	union acpi_operand_object *cocci_id/* drivers/acpi/acpica/utresrc.c 544 */;
	u8 **cocci_id/* drivers/acpi/acpica/utresrc.c 544 */;
	acpi_status cocci_id/* drivers/acpi/acpica/utresrc.c 543 */;
	struct aml_resource_pin_function cocci_id/* drivers/acpi/acpica/utresrc.c 54 */;
	struct aml_resource_gpio cocci_id/* drivers/acpi/acpica/utresrc.c 53 */;
	struct aml_resource_extended_address64 cocci_id/* drivers/acpi/acpica/utresrc.c 52 */;
	u32 cocci_id/* drivers/acpi/acpica/utresrc.c 517 */;
	void *cocci_id/* drivers/acpi/acpica/utresrc.c 517 */;
	struct aml_resource_address64 cocci_id/* drivers/acpi/acpica/utresrc.c 51 */;
	struct aml_resource_extended_irq cocci_id/* drivers/acpi/acpica/utresrc.c 50 */;
	struct aml_resource_small_header cocci_id/* drivers/acpi/acpica/utresrc.c 499 */;
	struct aml_resource_large_header cocci_id/* drivers/acpi/acpica/utresrc.c 497 */;
	u8 cocci_id/* drivers/acpi/acpica/utresrc.c 490 */;
	struct aml_resource_address16 cocci_id/* drivers/acpi/acpica/utresrc.c 49 */;
	struct aml_resource_address32 cocci_id/* drivers/acpi/acpica/utresrc.c 48 */;
	struct aml_resource_fixed_memory32 cocci_id/* drivers/acpi/acpica/utresrc.c 47 */;
	struct aml_resource_memory32 cocci_id/* drivers/acpi/acpica/utresrc.c 46 */;
	acpi_rs_length cocci_id/* drivers/acpi/acpica/utresrc.c 454 */;
	u16 cocci_id/* drivers/acpi/acpica/utresrc.c 452 */;
	struct aml_resource_vendor_large cocci_id/* drivers/acpi/acpica/utresrc.c 45 */;
	struct aml_resource_generic_register cocci_id/* drivers/acpi/acpica/utresrc.c 43 */;
	struct aml_resource_memory24 cocci_id/* drivers/acpi/acpica/utresrc.c 42 */;
	struct aml_resource_end_tag cocci_id/* drivers/acpi/acpica/utresrc.c 37 */;
	struct aml_resource_vendor_small cocci_id/* drivers/acpi/acpica/utresrc.c 36 */;
	union aml_resource cocci_id/* drivers/acpi/acpica/utresrc.c 357 */;
	struct aml_resource_fixed_dma cocci_id/* drivers/acpi/acpica/utresrc.c 32 */;
	struct aml_resource_fixed_io cocci_id/* drivers/acpi/acpica/utresrc.c 31 */;
	struct aml_resource_io cocci_id/* drivers/acpi/acpica/utresrc.c 30 */;
	struct aml_resource_end_dependent cocci_id/* drivers/acpi/acpica/utresrc.c 29 */;
	struct aml_resource_start_dependent cocci_id/* drivers/acpi/acpica/utresrc.c 28 */;
	struct aml_resource_dma cocci_id/* drivers/acpi/acpica/utresrc.c 27 */;
	union aml_resource *cocci_id/* drivers/acpi/acpica/utresrc.c 265 */;
	u8 *cocci_id/* drivers/acpi/acpica/utresrc.c 263 */;
	struct acpi_walk_state *cocci_id/* drivers/acpi/acpica/utresrc.c 262 */;
	struct aml_resource_irq cocci_id/* drivers/acpi/acpica/utresrc.c 26 */;
	void cocci_id/* drivers/acpi/acpica/utresrc.c 232 */;
	u8 cocci_id/* drivers/acpi/acpica/utresrc.c 147 */[2];
	acpi_walk_aml_callback cocci_id/* drivers/acpi/acpica/utresrc.c 140 */;
	acpi_size cocci_id/* drivers/acpi/acpica/utresrc.c 139 */;
}
