cocci_test_suite() {
	struct nd_cmd_clear_error *cocci_id/* drivers/acpi/nfit/core.c 93 */;
	struct acpi_nfit_header *cocci_id/* drivers/acpi/nfit/core.c 928 */;
	struct acpi_nfit_capabilities *cocci_id/* drivers/acpi/nfit/core.c 913 */;
	struct acpi_nfit_interleave *cocci_id/* drivers/acpi/nfit/core.c 842 */;
	struct nfit_bdw *cocci_id/* drivers/acpi/nfit/core.c 811 */;
	struct acpi_nfit_data_region *cocci_id/* drivers/acpi/nfit/core.c 808 */;
	u16 *cocci_id/* drivers/acpi/nfit/core.c 736 */;
	enum nfit_uuids cocci_id/* drivers/acpi/nfit/core.c 70 */;
	guid_t cocci_id/* drivers/acpi/nfit/core.c 68 */[NFIT_UUID_MAX];
	const char *cocci_id/* drivers/acpi/nfit/core.c 649 */[];
	struct nfit_table_prev {
		struct list_head spas;
		struct list_head memdevs;
		struct list_head dcrs;
		struct list_head bdws;
		struct list_head idts;
		struct list_head flushes;
	} cocci_id/* drivers/acpi/nfit/core.c 59 */;
	u32 *cocci_id/* drivers/acpi/nfit/core.c 588 */;
	struct workqueue_struct *cocci_id/* drivers/acpi/nfit/core.c 57 */;
	u8 cocci_id/* drivers/acpi/nfit/core.c 541 */;
	struct nd_cmd_set_config_hdr *cocci_id/* drivers/acpi/nfit/core.c 536 */;
	struct nd_cmd_get_config_data_hdr *cocci_id/* drivers/acpi/nfit/core.c 531 */;
	const char *cocci_id/* drivers/acpi/nfit/core.c 447 */;
	const struct nd_cmd_desc *cocci_id/* drivers/acpi/nfit/core.c 444 */;
	union acpi_object cocci_id/* drivers/acpi/nfit/core.c 443 */;
	int *cocci_id/* drivers/acpi/nfit/core.c 439 */;
	struct acpi_nfit_capabilities cocci_id/* drivers/acpi/nfit/core.c 3774 */;
	struct acpi_nfit_data_region cocci_id/* drivers/acpi/nfit/core.c 3773 */;
	struct acpi_nfit_control_region cocci_id/* drivers/acpi/nfit/core.c 3772 */;
	struct acpi_nfit_smbios cocci_id/* drivers/acpi/nfit/core.c 3771 */;
	struct acpi_nfit_interleave cocci_id/* drivers/acpi/nfit/core.c 3770 */;
	struct acpi_nfit_memory_map cocci_id/* drivers/acpi/nfit/core.c 3769 */;
	struct acpi_nfit_system_address cocci_id/* drivers/acpi/nfit/core.c 3768 */;
	struct acpi_driver cocci_id/* drivers/acpi/nfit/core.c 3753 */;
	const struct acpi_device_id cocci_id/* drivers/acpi/nfit/core.c 3747 */[];
	u32 cocci_id/* drivers/acpi/nfit/core.c 3725 */;
	acpi_handle cocci_id/* drivers/acpi/nfit/core.c 3725 */;
	struct device *cocci_id/* drivers/acpi/nfit/core.c 3725 */;
	void cocci_id/* drivers/acpi/nfit/core.c 3725 */;
	struct acpi_table_nfit cocci_id/* drivers/acpi/nfit/core.c 3656 */;
	const u8 cocci_id/* drivers/acpi/nfit/core.c 363 */[NVDIMM_FAMILY_MAX + 1][32];
	acpi_size cocci_id/* drivers/acpi/nfit/core.c 3612 */;
	struct acpi_table_header *cocci_id/* drivers/acpi/nfit/core.c 3610 */;
	unsigned cocci_id/* drivers/acpi/nfit/core.c 361 */;
	struct acpi_device *cocci_id/* drivers/acpi/nfit/core.c 3605 */;
	struct acpi_buffer cocci_id/* drivers/acpi/nfit/core.c 353 */;
	acpi_status cocci_id/* drivers/acpi/nfit/core.c 352 */;
	union acpi_object *cocci_id/* drivers/acpi/nfit/core.c 350 */;
	struct nd_cmd_pkg *cocci_id/* drivers/acpi/nfit/core.c 3489 */;
	struct acpi_nfit_desc *cocci_id/* drivers/acpi/nfit/core.c 3466 */;
	struct nvdimm *cocci_id/* drivers/acpi/nfit/core.c 3464 */;
	unsigned int cocci_id/* drivers/acpi/nfit/core.c 3464 */;
	struct nvdimm_bus_descriptor *cocci_id/* drivers/acpi/nfit/core.c 3463 */;
	int cocci_id/* drivers/acpi/nfit/core.c 3463 */;
	const void *cocci_id/* drivers/acpi/nfit/core.c 3369 */;
	struct nfit_table_prev cocci_id/* drivers/acpi/nfit/core.c 3368 */;
	struct kernfs_node *cocci_id/* drivers/acpi/nfit/core.c 3336 */;
	union acpi_object cocci_id/* drivers/acpi/nfit/core.c 332 */[];
	struct nfit_table_prev *cocci_id/* drivers/acpi/nfit/core.c 3317 */;
	struct acpi_object_list cocci_id/* drivers/acpi/nfit/core.c 330 */;
	struct nd_cmd_ars_cap cocci_id/* drivers/acpi/nfit/core.c 3248 */;
	typeof(*acpi_desc) cocci_id/* drivers/acpi/nfit/core.c 3231 */;
	struct work_struct *cocci_id/* drivers/acpi/nfit/core.c 3225 */;
	enum nfit_ars_state cocci_id/* drivers/acpi/nfit/core.c 3152 */;
	unsigned long long cocci_id/* drivers/acpi/nfit/core.c 3142 */;
	struct nfit_spa *cocci_id/* drivers/acpi/nfit/core.c 3125 */;
	void *cocci_id/* drivers/acpi/nfit/core.c 296 */;
	struct nd_blk_region_desc cocci_id/* drivers/acpi/nfit/core.c 2920 */;
	struct nd_mapping_desc cocci_id/* drivers/acpi/nfit/core.c 2918 */[ND_MAX_MAPPINGS];
	struct nd_blk_region_desc *cocci_id/* drivers/acpi/nfit/core.c 2854 */;
	struct nd_ars_record cocci_id/* drivers/acpi/nfit/core.c 2790 */;
	struct nd_cmd_ars_status *cocci_id/* drivers/acpi/nfit/core.c 2721 */;
	struct nd_cmd_ars_start cocci_id/* drivers/acpi/nfit/core.c 2689 */;
	struct nd_cmd_ars_cap *cocci_id/* drivers/acpi/nfit/core.c 2639 */;
	struct nvdimm_bus *cocci_id/* drivers/acpi/nfit/core.c 2540 */;
	struct nd_cmd_dimm_flags cocci_id/* drivers/acpi/nfit/core.c 2521 */;
	struct nfit_blk *cocci_id/* drivers/acpi/nfit/core.c 2519 */;
	struct nd_region *cocci_id/* drivers/acpi/nfit/core.c 2482 */;
	struct nfit_blk_mmio *cocci_id/* drivers/acpi/nfit/core.c 2481 */;
	u64 cocci_id/* drivers/acpi/nfit/core.c 2478 */;
	resource_size_t cocci_id/* drivers/acpi/nfit/core.c 2478 */;
	struct nd_blk_region *cocci_id/* drivers/acpi/nfit/core.c 2477 */;
	void __force *cocci_id/* drivers/acpi/nfit/core.c 2460 */;
	size_t cocci_id/* drivers/acpi/nfit/core.c 2429 */;
	enum{BCW_OFFSET_MASK=(1ULL << 48) - 1, BCW_LEN_SHIFT=48, BCW_LEN_MASK=(1ULL << 8) - 1, BCW_CMD_SHIFT=56,} cocci_id/* drivers/acpi/nfit/core.c 2405 */;
	const u32 cocci_id/* drivers/acpi/nfit/core.c 2391 */;
	struct nfit_set_info_map2 cocci_id/* drivers/acpi/nfit/core.c 2334 */;
	struct nfit_set_info_map cocci_id/* drivers/acpi/nfit/core.c 2329 */;
	struct acpi_nfit_memory_map *cocci_id/* drivers/acpi/nfit/core.c 2309 */;
	struct nfit_set_info_map2 *cocci_id/* drivers/acpi/nfit/core.c 2306 */;
	struct nfit_set_info_map *cocci_id/* drivers/acpi/nfit/core.c 2305 */;
	struct nd_mapping_desc *cocci_id/* drivers/acpi/nfit/core.c 2304 */;
	guid_t *cocci_id/* drivers/acpi/nfit/core.c 2293 */;
	struct nfit_set_info *cocci_id/* drivers/acpi/nfit/core.c 2287 */;
	struct nfit_set_info2 *cocci_id/* drivers/acpi/nfit/core.c 2286 */;
	struct nd_interleave_set *cocci_id/* drivers/acpi/nfit/core.c 2284 */;
	struct nd_region_desc *cocci_id/* drivers/acpi/nfit/core.c 2280 */;
	const struct nfit_set_info_map2 *cocci_id/* drivers/acpi/nfit/core.c 2256 */;
	const struct nfit_set_info_map *cocci_id/* drivers/acpi/nfit/core.c 2244 */;
	struct nfit_set_info2 cocci_id/* drivers/acpi/nfit/core.c 2229 */;
	struct nfit_set_info cocci_id/* drivers/acpi/nfit/core.c 2223 */;
	struct nfit_set_info2 {
		struct nfit_set_info_map2 {
			u64 region_offset;
			u32 serial_number;
			u16 vendor_id;
			u16 manufacturing_date;
			u8 manufacturing_location;
			u8 reserved[31];
		} mapping[0];
	} cocci_id/* drivers/acpi/nfit/core.c 2210 */;
	struct nfit_set_info {
		struct nfit_set_info_map {
			u64 region_offset;
			u32 serial_number;
			u32 pad;
		} mapping[0];
	} cocci_id/* drivers/acpi/nfit/core.c 2202 */;
	enum nfit_aux_cmds{NFIT_CMD_TRANSLATE_SPA=5, NFIT_CMD_ARS_INJECT_SET=7, NFIT_CMD_ARS_INJECT_CLEAR=8, NFIT_CMD_ARS_INJECT_GET=9,} cocci_id/* drivers/acpi/nfit/core.c 2136 */;
	const struct nvdimm_security_ops *cocci_id/* drivers/acpi/nfit/core.c 1999 */;
	struct acpi_nfit_control_region *cocci_id/* drivers/acpi/nfit/core.c 1831 */;
	const guid_t *cocci_id/* drivers/acpi/nfit/core.c 1828 */;
	unsigned long cocci_id/* drivers/acpi/nfit/core.c 1827 */;
	const u8 cocci_id/* drivers/acpi/nfit/core.c 1779 */;
	struct nd_intel_smart cocci_id/* drivers/acpi/nfit/core.c 1769 */;
	bool cocci_id/* drivers/acpi/nfit/core.c 1754 */;
	char *cocci_id/* drivers/acpi/nfit/core.c 1754 */;
	struct nfit_mem *cocci_id/* drivers/acpi/nfit/core.c 1718 */;
	struct device cocci_id/* drivers/acpi/nfit/core.c 1669 */;
	struct attribute *cocci_id/* drivers/acpi/nfit/core.c 1667 */;
	umode_t cocci_id/* drivers/acpi/nfit/core.c 1666 */;
	struct kobject *cocci_id/* drivers/acpi/nfit/core.c 1666 */;
	const struct attribute_group *cocci_id/* drivers/acpi/nfit/core.c 1406 */[];
	const struct attribute_group cocci_id/* drivers/acpi/nfit/core.c 1400 */;
	struct attribute *cocci_id/* drivers/acpi/nfit/core.c 1392 */[];
	const unsigned long cocci_id/* drivers/acpi/nfit/core.c 1376 */;
	long cocci_id/* drivers/acpi/nfit/core.c 1279 */;
	struct device_attribute cocci_id/* drivers/acpi/nfit/core.c 1243 */;
	struct device_attribute *cocci_id/* drivers/acpi/nfit/core.c 1236 */;
	ssize_t cocci_id/* drivers/acpi/nfit/core.c 1235 */;
	typeof(*b) cocci_id/* drivers/acpi/nfit/core.c 1189 */;
	typeof(*a) cocci_id/* drivers/acpi/nfit/core.c 1188 */;
	struct list_head *cocci_id/* drivers/acpi/nfit/core.c 1186 */;
	struct nfit_idt *cocci_id/* drivers/acpi/nfit/core.c 1158 */;
	struct resource *cocci_id/* drivers/acpi/nfit/core.c 1143 */;
	struct resource cocci_id/* drivers/acpi/nfit/core.c 1138 */;
	struct acpi_nfit_flush_address *cocci_id/* drivers/acpi/nfit/core.c 1129 */;
	u16 cocci_id/* drivers/acpi/nfit/core.c 1082 */;
	struct nfit_dcr *cocci_id/* drivers/acpi/nfit/core.c 1080 */;
	struct nfit_flush *cocci_id/* drivers/acpi/nfit/core.c 1079 */;
	struct nfit_memdev *cocci_id/* drivers/acpi/nfit/core.c 1059 */;
	struct acpi_nfit_system_address *cocci_id/* drivers/acpi/nfit/core.c 1056 */;
}
