cocci_test_suite() {
	struct acpi_table_header cocci_id/* drivers/acpi/utils.c 876 */;
	const struct acpi_platform_list *cocci_id/* drivers/acpi/utils.c 874 */;
	char *cocci_id/* drivers/acpi/utils.c 859 */;
	int __init cocci_id/* drivers/acpi/utils.c 859 */;
	char cocci_id/* drivers/acpi/utils.c 856 */[16];
	struct device *cocci_id/* drivers/acpi/utils.c 841 */;
	struct acpi_dev_match_info cocci_id/* drivers/acpi/utils.c 840 */;
	s64 cocci_id/* drivers/acpi/utils.c 838 */;
	struct acpi_device *cocci_id/* drivers/acpi/utils.c 837 */;
	acpi_status cocci_id/* drivers/acpi/utils.c 770 */;
	unsigned long long cocci_id/* drivers/acpi/utils.c 769 */;
	const struct acpi_dev_match_info *cocci_id/* drivers/acpi/utils.c 768 */;
	const void *cocci_id/* drivers/acpi/utils.c 765 */;
	struct acpi_dev_match_info {
		struct acpi_device_id hid[2];
		const char *uid;
		s64 hrv;
	} cocci_id/* drivers/acpi/utils.c 759 */;
	struct acpi_device_bus_id *cocci_id/* drivers/acpi/utils.c 744 */;
	char cocci_id/* drivers/acpi/utils.c 70 */;
	union acpi_object *cocci_id/* drivers/acpi/utils.c 676 */;
	int cocci_id/* drivers/acpi/utils.c 674 */;
	u64 cocci_id/* drivers/acpi/utils.c 672 */;
	bool cocci_id/* drivers/acpi/utils.c 672 */;
	const guid_t *cocci_id/* drivers/acpi/utils.c 672 */;
	u8 *cocci_id/* drivers/acpi/utils.c 636 */;
	struct acpi_object_list cocci_id/* drivers/acpi/utils.c 629 */;
	union acpi_object cocci_id/* drivers/acpi/utils.c 628 */[4];
	struct acpi_buffer cocci_id/* drivers/acpi/utils.c 627 */;
	va_list cocci_id/* drivers/acpi/utils.c 522 */;
	struct va_format cocci_id/* drivers/acpi/utils.c 521 */;
	const char *cocci_id/* drivers/acpi/utils.c 519 */;
	acpi_handle cocci_id/* drivers/acpi/utils.c 518 */;
	struct _ddebug *cocci_id/* drivers/acpi/utils.c 518 */;
	void cocci_id/* drivers/acpi/utils.c 517 */;
	union acpi_object cocci_id/* drivers/acpi/utils.c 435 */[3];
	struct acpi_buffer *cocci_id/* drivers/acpi/utils.c 433 */;
	u32 cocci_id/* drivers/acpi/utils.c 432 */;
	struct acpi_pld_info **cocci_id/* drivers/acpi/utils.c 388 */;
	char cocci_id/* drivers/acpi/utils.c 31 */[80];
	struct acpi_handle_list *cocci_id/* drivers/acpi/utils.c 307 */;
	union acpi_object cocci_id/* drivers/acpi/utils.c 275 */;
	struct acpi_object_list *cocci_id/* drivers/acpi/utils.c 272 */;
	unsigned long long *cocci_id/* drivers/acpi/utils.c 272 */;
	acpi_string cocci_id/* drivers/acpi/utils.c 271 */;
	void **cocci_id/* drivers/acpi/utils.c 247 */;
	u64 *cocci_id/* drivers/acpi/utils.c 196 */;
	u8 **cocci_id/* drivers/acpi/utils.c 188 */;
	void *cocci_id/* drivers/acpi/utils.c 138 */;
}
