cocci_test_suite() {
	cpumask_var_t cocci_id/* drivers/acpi/acpi_pad.c 88 */;
	int cocci_id/* drivers/acpi/acpi_pad.c 83 */[NR_CPUS];
	unsigned long cocci_id/* drivers/acpi/acpi_pad.c 82 */[NR_CPUS];
	void __exit cocci_id/* drivers/acpi/acpi_pad.c 489 */;
	void cocci_id/* drivers/acpi/acpi_pad.c 489 */;
	int __init cocci_id/* drivers/acpi/acpi_pad.c 476 */;
	struct acpi_driver cocci_id/* drivers/acpi/acpi_pad.c 466 */;
	const struct acpi_device_id cocci_id/* drivers/acpi/acpi_pad.c 460 */[];
	acpi_status cocci_id/* drivers/acpi/acpi_pad.c 430 */;
	struct acpi_device *cocci_id/* drivers/acpi/acpi_pad.c 428 */;
	int cocci_id/* drivers/acpi/acpi_pad.c 428 */;
	u32 cocci_id/* drivers/acpi/acpi_pad.c 411 */;
	void *cocci_id/* drivers/acpi/acpi_pad.c 396 */;
	struct acpi_buffer cocci_id/* drivers/acpi/acpi_pad.c 394 */;
	uint32_t cocci_id/* drivers/acpi/acpi_pad.c 393 */;
	acpi_handle cocci_id/* drivers/acpi/acpi_pad.c 390 */;
	union acpi_object *cocci_id/* drivers/acpi/acpi_pad.c 369 */;
	struct device_attribute *cocci_id/* drivers/acpi/acpi_pad.c 324 */;
	char *cocci_id/* drivers/acpi/acpi_pad.c 324 */;
	struct device *cocci_id/* drivers/acpi/acpi_pad.c 323 */;
	ssize_t cocci_id/* drivers/acpi/acpi_pad.c 323 */;
	unsigned long cocci_id/* drivers/acpi/acpi_pad.c 314 */;
	const char *cocci_id/* drivers/acpi/acpi_pad.c 312 */;
	size_t cocci_id/* drivers/acpi/acpi_pad.c 312 */;
	unsigned char cocci_id/* drivers/acpi/acpi_pad.c 31 */;
	unsigned int cocci_id/* drivers/acpi/acpi_pad.c 250 */;
	struct task_struct *cocci_id/* drivers/acpi/acpi_pad.c 207 */[NR_CPUS];
	u64 cocci_id/* drivers/acpi/acpi_pad.c 142 */;
	struct sched_param cocci_id/* drivers/acpi/acpi_pad.c 139 */;
	struct cpumask *cocci_id/* drivers/acpi/acpi_pad.c 130 */;
}
