cocci_test_suite() {
	const struct virtio_device_id cocci_id/* drivers/block/virtio_blk.c 986 */[];
	struct virtblk_req cocci_id/* drivers/block/virtio_blk.c 793 */;
	u16 cocci_id/* drivers/block/virtio_blk.c 731 */;
	u32 cocci_id/* drivers/block/virtio_blk.c 730 */;
	const struct blk_mq_ops cocci_id/* drivers/block/virtio_blk.c 710 */;
	blk_status_t cocci_id/* drivers/block/virtio_blk.c 69 */;
	struct blk_mq_tag_set *cocci_id/* drivers/block/virtio_blk.c 680 */;
	const struct attribute_group *cocci_id/* drivers/block/virtio_blk.c 675 */[];
	const struct attribute_group cocci_id/* drivers/block/virtio_blk.c 670 */;
	struct device cocci_id/* drivers/block/virtio_blk.c 658 */;
	struct attribute *cocci_id/* drivers/block/virtio_blk.c 656 */;
	umode_t cocci_id/* drivers/block/virtio_blk.c 655 */;
	struct kobject *cocci_id/* drivers/block/virtio_blk.c 655 */;
	struct attribute *cocci_id/* drivers/block/virtio_blk.c 649 */[];
	u8 cocci_id/* drivers/block/virtio_blk.c 641 */;
	struct virtio_blk *cocci_id/* drivers/block/virtio_blk.c 640 */;
	struct gendisk *cocci_id/* drivers/block/virtio_blk.c 639 */;
	struct device_attribute *cocci_id/* drivers/block/virtio_blk.c 637 */;
	struct device *cocci_id/* drivers/block/virtio_blk.c 637 */;
	char *cocci_id/* drivers/block/virtio_blk.c 637 */;
	ssize_t cocci_id/* drivers/block/virtio_blk.c 636 */;
	struct virtio_blk_config cocci_id/* drivers/block/virtio_blk.c 631 */;
	int cocci_id/* drivers/block/virtio_blk.c 624 */;
	struct virtio_device *cocci_id/* drivers/block/virtio_blk.c 623 */;
	const char *cocci_id/* drivers/block/virtio_blk.c 619 */;
	size_t cocci_id/* drivers/block/virtio_blk.c 619 */;
	const char *const cocci_id/* drivers/block/virtio_blk.c 613 */[];
	struct virtblk_req {
#ifdef CONFIG_VIRTIO_BLK_SCSI
		struct scsi_request sreq;
		u8 sense[SCSI_SENSE_BUFFERSIZE];
		struct virtio_scsi_inhdr in_hdr;
#endif
		struct virtio_blk_outhdr out_hdr;
		u8 status;
		struct scatterlist sg[];
	} cocci_id/* drivers/block/virtio_blk.c 58 */;
	const int cocci_id/* drivers/block/virtio_blk.c 563 */;
	unsigned int cocci_id/* drivers/block/virtio_blk.c 517 */;
	struct irq_affinity cocci_id/* drivers/block/virtio_blk.c 509 */;
	unsigned short cocci_id/* drivers/block/virtio_blk.c 507 */;
	struct virtqueue **cocci_id/* drivers/block/virtio_blk.c 506 */;
	const char **cocci_id/* drivers/block/virtio_blk.c 505 */;
	vq_callback_t **cocci_id/* drivers/block/virtio_blk.c 504 */;
	char *cocci_id/* drivers/block/virtio_blk.c 486 */[];
	struct virtio_blk cocci_id/* drivers/block/virtio_blk.c 485 */;
	struct work_struct *cocci_id/* drivers/block/virtio_blk.c 482 */;
	sector_t cocci_id/* drivers/block/virtio_blk.c 457 */;
	unsigned long long cocci_id/* drivers/block/virtio_blk.c 450 */;
	char cocci_id/* drivers/block/virtio_blk.c 449 */[10];
	const struct block_device_operations cocci_id/* drivers/block/virtio_blk.c 406 */;
	struct hd_geometry *cocci_id/* drivers/block/virtio_blk.c 385 */;
	struct block_device *cocci_id/* drivers/block/virtio_blk.c 385 */;
	struct request_queue *cocci_id/* drivers/block/virtio_blk.c 365 */;
	struct virtio_blk {
		struct virtio_device *vdev;
		struct gendisk *disk;
		struct blk_mq_tag_set tag_set;
		struct work_struct config_work;
		unsigned int sg_elems;
		int index;
		int num_vqs;
		struct virtio_blk_vq *vqs;
	} cocci_id/* drivers/block/virtio_blk.c 35 */;
	struct virtio_blk_vq {
		struct virtqueue *vq;
		spinlock_t lock;
		char name[VQ_NAME_LEN];
	}____cacheline_aligned_in_smp cocci_id/* drivers/block/virtio_blk.c 29 */;
	const struct blk_mq_queue_data *cocci_id/* drivers/block/virtio_blk.c 272 */;
	struct workqueue_struct *cocci_id/* drivers/block/virtio_blk.c 27 */;
	struct virtio_blk_vq *cocci_id/* drivers/block/virtio_blk.c 260 */;
	struct blk_mq_hw_ctx *cocci_id/* drivers/block/virtio_blk.c 257 */;
	struct request *cocci_id/* drivers/block/virtio_blk.c 242 */;
	unsigned long cocci_id/* drivers/block/virtio_blk.c 235 */;
	u64 cocci_id/* drivers/block/virtio_blk.c 193 */;
	struct bio *cocci_id/* drivers/block/virtio_blk.c 182 */;
	struct virtio_blk_discard_write_zeroes *cocci_id/* drivers/block/virtio_blk.c 181 */;
	struct scatterlist cocci_id/* drivers/block/virtio_blk.c 158 */;
	bool cocci_id/* drivers/block/virtio_blk.c 156 */;
	struct scatterlist *cocci_id/* drivers/block/virtio_blk.c 156 */;
	struct virtqueue *cocci_id/* drivers/block/virtio_blk.c 155 */;
	struct virtblk_req *cocci_id/* drivers/block/virtio_blk.c 155 */;
	void __user *cocci_id/* drivers/block/virtio_blk.c 140 */;
	fmode_t cocci_id/* drivers/block/virtio_blk.c 127 */;
	struct scsi_request *cocci_id/* drivers/block/virtio_blk.c 120 */;
	void __exit cocci_id/* drivers/block/virtio_blk.c 1051 */;
	void cocci_id/* drivers/block/virtio_blk.c 1051 */;
	int __init cocci_id/* drivers/block/virtio_blk.c 1025 */;
	struct virtio_driver cocci_id/* drivers/block/virtio_blk.c 1008 */;
	unsigned int cocci_id/* drivers/block/virtio_blk.c 1001 */[];
}
