cocci_test_suite() {
	const struct blk_mq_ops cocci_id/* drivers/block/xsysace.c 973 */;
	const struct block_device_operations cocci_id/* drivers/block/xsysace.c 964 */;
	struct hd_geometry *cocci_id/* drivers/block/xsysace.c 950 */;
	struct block_device *cocci_id/* drivers/block/xsysace.c 950 */;
	fmode_t cocci_id/* drivers/block/xsysace.c 913 */;
	struct gendisk *cocci_id/* drivers/block/xsysace.c 883 */;
	unsigned int cocci_id/* drivers/block/xsysace.c 883 */;
	const struct blk_mq_queue_data *cocci_id/* drivers/block/xsysace.c 865 */;
	blk_status_t cocci_id/* drivers/block/xsysace.c 864 */;
	struct blk_mq_hw_ctx *cocci_id/* drivers/block/xsysace.c 864 */;
	irqreturn_t cocci_id/* drivers/block/xsysace.c 822 */;
	struct timer_list *cocci_id/* drivers/block/xsysace.c 780 */;
	unsigned long cocci_id/* drivers/block/xsysace.c 765 */;
	unsigned long long cocci_id/* drivers/block/xsysace.c 665 */;
	u16 cocci_id/* drivers/block/xsysace.c 490 */;
	u32 cocci_id/* drivers/block/xsysace.c 489 */;
	struct request *cocci_id/* drivers/block/xsysace.c 488 */;
	struct request cocci_id/* drivers/block/xsysace.c 477 */;
	struct request_queue *cocci_id/* drivers/block/xsysace.c 472 */;
	bool cocci_id/* drivers/block/xsysace.c 464 */;
	const char *cocci_id/* drivers/block/xsysace.c 371 */;
	void *cocci_id/* drivers/block/xsysace.c 369 */;
	u16 *cocci_id/* drivers/block/xsysace.c 285 */;
	struct ace_reg_ops cocci_id/* drivers/block/xsysace.c 264 */;
	u8 *cocci_id/* drivers/block/xsysace.c 247 */;
	void __iomem *cocci_id/* drivers/block/xsysace.c 246 */;
	void cocci_id/* drivers/block/xsysace.c 244 */;
	struct ace_reg_ops {
		u16 (*in)(struct ace_device *ace, int reg);
		void (*out)(struct ace_device *ace, int reg, u16 val);
		void (*datain)(struct ace_device *ace);
		void (*dataout)(struct ace_device *ace);
	} cocci_id/* drivers/block/xsysace.c 223 */;
	struct ace_device {
		int id;
		int media_change;
		int users;
		struct list_head list;
		struct tasklet_struct fsm_tasklet;
		uint fsm_task;
		uint fsm_state;
		uint fsm_continue_flag;
		uint fsm_iter_num;
		struct timer_list stall_timer;
		struct request *req;
		void *data_ptr;
		int data_count;
		int data_result;
		int id_req_count;
		int id_result;
		struct completion id_completion;
		int in_irq;
		resource_size_t physaddr;
		void __iomem *baseaddr;
		int irq;
		int bus_width;
		struct ace_reg_ops *reg_ops;
		int lock_count;
		spinlock_t lock;
		struct device *dev;
		struct request_queue *queue;
		struct gendisk *gd;
		struct blk_mq_tag_set tag_set;
		struct list_head rq_list;
		u16 cf_id[ATA_ID_WORDS];
	} cocci_id/* drivers/block/xsysace.c 170 */;
	void __exit cocci_id/* drivers/block/xsysace.c 1270 */;
	int __init cocci_id/* drivers/block/xsysace.c 1245 */;
	struct platform_driver cocci_id/* drivers/block/xsysace.c 1233 */;
	const struct of_device_id cocci_id/* drivers/block/xsysace.c 1221 */[];
	struct platform_device *cocci_id/* drivers/block/xsysace.c 1183 */;
	struct ace_device cocci_id/* drivers/block/xsysace.c 1138 */;
	struct ace_device *cocci_id/* drivers/block/xsysace.c 1128 */;
	resource_size_t cocci_id/* drivers/block/xsysace.c 1125 */;
	struct device *cocci_id/* drivers/block/xsysace.c 1125 */;
	int cocci_id/* drivers/block/xsysace.c 1125 */;
}
