cocci_test_suite() {
	enum dds_flags cocci_id/* drivers/block/drbd/drbd_main.c 940 */;
	struct request_queue *cocci_id/* drivers/block/drbd/drbd_main.c 918 */;
	struct p_sizes *cocci_id/* drivers/block/drbd/drbd_main.c 917 */;
	struct p_rs_uuid *cocci_id/* drivers/block/drbd/drbd_main.c 893 */;
	u64 *cocci_id/* drivers/block/drbd/drbd_main.c 874 */;
	struct p_uuids *cocci_id/* drivers/block/drbd/drbd_main.c 831 */;
	struct net_conf *cocci_id/* drivers/block/drbd/drbd_main.c 776 */;
	struct p_protocol *cocci_id/* drivers/block/drbd/drbd_main.c 775 */;
	struct p_rs_param_95 cocci_id/* drivers/block/drbd/drbd_main.c 740 */;
	struct p_rs_param_89 cocci_id/* drivers/block/drbd/drbd_main.c 739 */;
	struct p_rs_param cocci_id/* drivers/block/drbd/drbd_main.c 736 */;
	struct disk_conf *cocci_id/* drivers/block/drbd/drbd_main.c 726 */;
	struct p_rs_param_95 *cocci_id/* drivers/block/drbd/drbd_main.c 721 */;
	enum drbd_packet cocci_id/* drivers/block/drbd/drbd_main.c 669 */;
	unsigned int cocci_id/* drivers/block/drbd/drbd_main.c 669 */;
	int cocci_id/* drivers/block/drbd/drbd_main.c 668 */;
	struct drbd_socket *cocci_id/* drivers/block/drbd/drbd_main.c 613 */;
	struct drbd_connection *cocci_id/* drivers/block/drbd/drbd_main.c 612 */;
	void *cocci_id/* drivers/block/drbd/drbd_main.c 612 */;
	struct p_header100 *cocci_id/* drivers/block/drbd/drbd_main.c 589 */;
	struct p_header95 *cocci_id/* drivers/block/drbd/drbd_main.c 581 */;
	struct p_header80 *cocci_id/* drivers/block/drbd/drbd_main.c 573 */;
	struct p_header95 cocci_id/* drivers/block/drbd/drbd_main.c 567 */;
	struct p_header80 cocci_id/* drivers/block/drbd/drbd_main.c 566 */;
	struct p_header100 cocci_id/* drivers/block/drbd/drbd_main.c 563 */;
	int cocci_id/* drivers/block/drbd/drbd_main.c 56 */(struct drbd_work *w,
							    int unused);
	void cocci_id/* drivers/block/drbd/drbd_main.c 55 */(struct timer_list *t);
	struct task_struct *cocci_id/* drivers/block/drbd/drbd_main.c 542 */;
	void cocci_id/* drivers/block/drbd/drbd_main.c 54 */(struct gendisk *gd,
							     fmode_t mode);
	int cocci_id/* drivers/block/drbd/drbd_main.c 53 */(struct block_device *bdev,
							    fmode_t mode);
	unsigned int *cocci_id/* drivers/block/drbd/drbd_main.c 502 */;
	cpumask_var_t *cocci_id/* drivers/block/drbd/drbd_main.c 500 */;
	enum drbd_thread_state cocci_id/* drivers/block/drbd/drbd_main.c 448 */;
	struct drbd_thread *cocci_id/* drivers/block/drbd/drbd_main.c 444 */;
	char cocci_id/* drivers/block/drbd/drbd_main.c 3908 */[38];
	struct fault_random_state cocci_id/* drivers/block/drbd/drbd_main.c 3884 */;
	char *cocci_id/* drivers/block/drbd/drbd_main.c 3865 */[];
	char *cocci_id/* drivers/block/drbd/drbd_main.c 3863 */;
	long cocci_id/* drivers/block/drbd/drbd_main.c 3852 */;
	struct fault_random_state *cocci_id/* drivers/block/drbd/drbd_main.c 3850 */;
	unsigned long cocci_id/* drivers/block/drbd/drbd_main.c 3849 */;
	struct fault_random_state {
		unsigned long state;
		unsigned long count;
	} cocci_id/* drivers/block/drbd/drbd_main.c 3836 */;
	int __maybe_unused cocci_id/* drivers/block/drbd/drbd_main.c 3815 */;
	struct drbd_interval *cocci_id/* drivers/block/drbd/drbd_main.c 3783 */;
	const char *cocci_id/* drivers/block/drbd/drbd_main.c 3708 */[];
	const char *cocci_id/* drivers/block/drbd/drbd_main.c 3703 */;
	struct timer_list *cocci_id/* drivers/block/drbd/drbd_main.c 3697 */;
	int (*cocci_id/* drivers/block/drbd/drbd_main.c 367 */)(struct drbd_thread *);
	const bool cocci_id/* drivers/block/drbd/drbd_main.c 3659 */;
	enum bm_flag cocci_id/* drivers/block/drbd/drbd_main.c 3656 */;
	int (*cocci_id/* drivers/block/drbd/drbd_main.c 3655 */)(struct drbd_device *);
	void (*cocci_id/* drivers/block/drbd/drbd_main.c 3617 */)(struct drbd_device *,
								  int);
	struct bm_io_work *cocci_id/* drivers/block/drbd/drbd_main.c 3570 */;
	struct drbd_work *cocci_id/* drivers/block/drbd/drbd_main.c 3566 */;
	u64 cocci_id/* drivers/block/drbd/drbd_main.c 3442 */;
	struct drbd_device *cocci_id/* drivers/block/drbd/drbd_main.c 3442 */;
	void cocci_id/* drivers/block/drbd/drbd_main.c 3442 */;
	unsigned long long cocci_id/* drivers/block/drbd/drbd_main.c 3290 */;
	s32 cocci_id/* drivers/block/drbd/drbd_main.c 3221 */;
	struct drbd_backing_dev *cocci_id/* drivers/block/drbd/drbd_main.c 3217 */;
	struct drbd_md *cocci_id/* drivers/block/drbd/drbd_main.c 3174 */;
	struct meta_data_on_disk *cocci_id/* drivers/block/drbd/drbd_main.c 3173 */;
	struct meta_data_on_disk cocci_id/* drivers/block/drbd/drbd_main.c 3145 */;
	struct meta_data_on_disk {
		u64 la_size_sect;
		u64 uuid[UI_SIZE];
		u64 device_uuid;
		u64 reserved_u64_1;
		u32 flags;
		u32 magic;
		u32 md_size_sect;
		u32 al_offset;
		u32 al_nr_extents;
		u32 bm_offset;
		u32 bm_bytes_per_bit;
		u32 la_peer_max_bio_size;
		u32 al_stripes;
		u32 al_stripe_size_4k;
		u8 reserved_u8[4096 - (7 * 8 + 10 * 4)];
	}__packed cocci_id/* drivers/block/drbd/drbd_main.c 3075 */;
	int __init cocci_id/* drivers/block/drbd/drbd_main.c 2956 */;
	struct drbd_peer_device cocci_id/* drivers/block/drbd/drbd_main.c 2865 */;
	struct drbd_device cocci_id/* drivers/block/drbd/drbd_main.c 2792 */;
	struct gendisk *cocci_id/* drivers/block/drbd/drbd_main.c 2781 */;
	enum drbd_ret_code cocci_id/* drivers/block/drbd/drbd_main.c 2775 */;
	struct drbd_config_context *cocci_id/* drivers/block/drbd/drbd_main.c 2775 */;
	struct kref *cocci_id/* drivers/block/drbd/drbd_main.c 2741 */;
	struct drbd_epoch cocci_id/* drivers/block/drbd/drbd_main.c 2684 */;
	struct drbd_request *cocci_id/* drivers/block/drbd/drbd_main.c 268 */;
	struct drbd_connection cocci_id/* drivers/block/drbd/drbd_main.c 2675 */;
	struct drbd_resource *cocci_id/* drivers/block/drbd/drbd_main.c 2672 */;
	struct res_opts *cocci_id/* drivers/block/drbd/drbd_main.c 2670 */;
	enum drbd_req_event cocci_id/* drivers/block/drbd/drbd_main.c 266 */;
	struct drbd_resource cocci_id/* drivers/block/drbd/drbd_main.c 2642 */;
	cpumask_var_t cocci_id/* drivers/block/drbd/drbd_main.c 2589 */;
	struct completion_work cocci_id/* drivers/block/drbd/drbd_main.c 2496 */;
	struct drbd_work_queue *cocci_id/* drivers/block/drbd/drbd_main.c 2494 */;
	struct completion_work *cocci_id/* drivers/block/drbd/drbd_main.c 2487 */;
	struct completion_work {
		struct drbd_work w;
		struct completion done;
	} cocci_id/* drivers/block/drbd/drbd_main.c 2480 */;
	char cocci_id/* drivers/block/drbd/drbd_main.c 2428 */;
	bool cocci_id/* drivers/block/drbd/drbd_main.c 2296 */;
	struct retry_worker cocci_id/* drivers/block/drbd/drbd_main.c 2284 */;
	struct retry_worker *cocci_id/* drivers/block/drbd/drbd_main.c 2284 */;
	struct work_struct *cocci_id/* drivers/block/drbd/drbd_main.c 2282 */;
	struct retry_worker {
		struct workqueue_struct *wq;
		struct work_struct worker;
		spinlock_t lock;
		struct list_head writes;
	} cocci_id/* drivers/block/drbd/drbd_main.c 2274 */;
	struct lc_element cocci_id/* drivers/block/drbd/drbd_main.c 2151 */;
	struct bm_extent cocci_id/* drivers/block/drbd/drbd_main.c 2146 */;
	struct drbd_peer_request cocci_id/* drivers/block/drbd/drbd_main.c 2141 */;
	struct drbd_request cocci_id/* drivers/block/drbd/drbd_main.c 2136 */;
	const int cocci_id/* drivers/block/drbd/drbd_main.c 2131 */;
	char cocci_id/* drivers/block/drbd/drbd_main.c 2040 */[10];
	loff_t cocci_id/* drivers/block/drbd/drbd_main.c 2035 */;
	sector_t cocci_id/* drivers/block/drbd/drbd_main.c 2031 */;
	union drbd_dev_state cocci_id/* drivers/block/drbd/drbd_main.c 1963 */;
	const unsigned cocci_id/* drivers/block/drbd/drbd_main.c 195 */;
	fmode_t cocci_id/* drivers/block/drbd/drbd_main.c 1912 */;
	struct block_device *cocci_id/* drivers/block/drbd/drbd_main.c 1912 */;
	struct msghdr cocci_id/* drivers/block/drbd/drbd_main.c 1845 */;
	struct kvec cocci_id/* drivers/block/drbd/drbd_main.c 1844 */;
	struct p_block_desc *cocci_id/* drivers/block/drbd/drbd_main.c 1814 */;
	unsigned char cocci_id/* drivers/block/drbd/drbd_main.c 1759 */[64];
	struct p_trim *cocci_id/* drivers/block/drbd/drbd_main.c 1710 */;
	struct p_wsame *cocci_id/* drivers/block/drbd/drbd_main.c 1677 */;
	struct drbd_peer_request *cocci_id/* drivers/block/drbd/drbd_main.c 1632 */;
	struct bvec_iter cocci_id/* drivers/block/drbd/drbd_main.c 1591 */;
	struct bio_vec cocci_id/* drivers/block/drbd/drbd_main.c 1590 */;
	struct bio *cocci_id/* drivers/block/drbd/drbd_main.c 1588 */;
	enum drbd_disk_state cocci_id/* drivers/block/drbd/drbd_main.c 157 */;
	struct socket *cocci_id/* drivers/block/drbd/drbd_main.c 1529 */;
	unsigned cocci_id/* drivers/block/drbd/drbd_main.c 1527 */;
	size_t cocci_id/* drivers/block/drbd/drbd_main.c 1527 */;
	struct page *cocci_id/* drivers/block/drbd/drbd_main.c 1526 */;
	struct drbd_peer_device *cocci_id/* drivers/block/drbd/drbd_main.c 1526 */;
	struct sock *cocci_id/* drivers/block/drbd/drbd_main.c 1500 */;
	gfp_t cocci_id/* drivers/block/drbd/drbd_main.c 140 */;
	struct p_block_req *cocci_id/* drivers/block/drbd/drbd_main.c 1375 */;
	struct p_data *cocci_id/* drivers/block/drbd/drbd_main.c 1366 */;
	struct p_block_ack *cocci_id/* drivers/block/drbd/drbd_main.c 1346 */;
	u32 cocci_id/* drivers/block/drbd/drbd_main.c 1343 */;
	const struct block_device_operations cocci_id/* drivers/block/drbd/drbd_main.c 134 */;
	struct p_barrier_ack *cocci_id/* drivers/block/drbd/drbd_main.c 1320 */;
	wait_queue_head_t cocci_id/* drivers/block/drbd/drbd_main.c 130 */;
	spinlock_t cocci_id/* drivers/block/drbd/drbd_main.c 128 */;
	struct bm_xfer_ctx cocci_id/* drivers/block/drbd/drbd_main.c 1270 */;
	unsigned long *cocci_id/* drivers/block/drbd/drbd_main.c 1239 */;
	struct bio_set cocci_id/* drivers/block/drbd/drbd_main.c 119 */;
	mempool_t cocci_id/* drivers/block/drbd/drbd_main.c 116 */;
	struct kmem_cache *cocci_id/* drivers/block/drbd/drbd_main.c 114 */;
	struct bitstream cocci_id/* drivers/block/drbd/drbd_main.c 1113 */;
	struct bm_xfer_ctx *cocci_id/* drivers/block/drbd/drbd_main.c 1111 */;
	enum drbd_bitmap_code cocci_id/* drivers/block/drbd/drbd_main.c 1091 */;
	struct p_compressed_bm *cocci_id/* drivers/block/drbd/drbd_main.c 1091 */;
	struct mutex cocci_id/* drivers/block/drbd/drbd_main.c 109 */;
	struct p_req_state_reply *cocci_id/* drivers/block/drbd/drbd_main.c 1080 */;
	struct list_head cocci_id/* drivers/block/drbd/drbd_main.c 108 */;
	enum drbd_state_rv cocci_id/* drivers/block/drbd/drbd_main.c 1077 */;
	struct idr cocci_id/* drivers/block/drbd/drbd_main.c 107 */;
	struct p_req_state *cocci_id/* drivers/block/drbd/drbd_main.c 1052 */;
	union drbd_state cocci_id/* drivers/block/drbd/drbd_main.c 1048 */;
	struct p_state *cocci_id/* drivers/block/drbd/drbd_main.c 1001 */;
	char cocci_id/* drivers/block/drbd/drbd_main.c 100 */[80];
}
