cocci_test_suite() {
	u8 cocci_id/* drivers/hwmon/lm63.c 971 */;
	struct i2c_adapter *cocci_id/* drivers/hwmon/lm63.c 970 */;
	struct i2c_board_info *cocci_id/* drivers/hwmon/lm63.c 968 */;
	struct i2c_client *cocci_id/* drivers/hwmon/lm63.c 967 */;
	const struct attribute_group cocci_id/* drivers/hwmon/lm63.c 945 */;
	struct device cocci_id/* drivers/hwmon/lm63.c 934 */;
	struct attribute *cocci_id/* drivers/hwmon/lm63.c 932 */;
	int cocci_id/* drivers/hwmon/lm63.c 932 */;
	umode_t cocci_id/* drivers/hwmon/lm63.c 931 */;
	struct kobject *cocci_id/* drivers/hwmon/lm63.c 931 */;
	struct attribute *cocci_id/* drivers/hwmon/lm63.c 848 */[];
	struct lm63_data *cocci_id/* drivers/hwmon/lm63.c 726 */;
	char *cocci_id/* drivers/hwmon/lm63.c 724 */;
	struct device_attribute *cocci_id/* drivers/hwmon/lm63.c 723 */;
	struct device *cocci_id/* drivers/hwmon/lm63.c 723 */;
	ssize_t cocci_id/* drivers/hwmon/lm63.c 723 */;
	unsigned int cocci_id/* drivers/hwmon/lm63.c 641 */;
	const u8 cocci_id/* drivers/hwmon/lm63.c 553 */[6];
	u16 cocci_id/* drivers/hwmon/lm63.c 543 */;
	const unsigned short cocci_id/* drivers/hwmon/lm63.c 48 */[];
	const char *cocci_id/* drivers/hwmon/lm63.c 417 */;
	size_t cocci_id/* drivers/hwmon/lm63.c 417 */;
	struct sensor_device_attribute *cocci_id/* drivers/hwmon/lm63.c 382 */;
	unsigned long cocci_id/* drivers/hwmon/lm63.c 228 */;
	long cocci_id/* drivers/hwmon/lm63.c 190 */;
	struct lm63_data {
		struct i2c_client *client;
		struct mutex update_lock;
		const struct attribute_group *groups[5];
		char valid;
		char lut_valid;
		unsigned long last_updated;
		unsigned long lut_last_updated;
		enum chips kind;
		int temp2_offset;
		int update_interval;
		int max_convrate_hz;
		int lut_size;
		u8 config,config_fan;
		u16 fan[2];
		u8 pwm1_freq;
		u8 pwm1[13];
		s8 temp8[15];
		s16 temp11[4];
		u16 temp11u;
		u8 temp2_crit_hyst;
		u8 lut_temp_hyst;
		u8 alarms;
		bool pwm_highres;
		bool lut_temp_highres;
		bool remote_unsigned;
		bool trutherm;
	} cocci_id/* drivers/hwmon/lm63.c 138 */;
	enum chips{lm63, lm64, lm96163,} cocci_id/* drivers/hwmon/lm63.c 132 */;
	struct i2c_driver cocci_id/* drivers/hwmon/lm63.c 1160 */;
	void *cocci_id/* drivers/hwmon/lm63.c 1146 */;
	const struct of_device_id __maybe_unused cocci_id/* drivers/hwmon/lm63.c 1143 */[];
	const struct i2c_device_id cocci_id/* drivers/hwmon/lm63.c 1135 */[];
	enum chips cocci_id/* drivers/hwmon/lm63.c 1107 */;
	struct lm63_data cocci_id/* drivers/hwmon/lm63.c 1098 */;
	const struct i2c_device_id *cocci_id/* drivers/hwmon/lm63.c 1091 */;
	void cocci_id/* drivers/hwmon/lm63.c 1014 */;
}
