cocci_test_suite() {
	char *cocci_id/* kernel/fork.c 963 */;
	int __init cocci_id/* kernel/fork.c 963 */;
	int __weak cocci_id/* kernel/fork.c 844 */;
	void __init cocci_id/* kernel/fork.c 803 */;
	void __init __weak cocci_id/* kernel/fork.c 755 */;
	struct mm_struct cocci_id/* kernel/fork.c 706 */;
	struct work_struct *cocci_id/* kernel/fork.c 702 */;
	struct mm_struct *cocci_id/* kernel/fork.c 688 */;
	struct address_space *cocci_id/* kernel/fork.c 566 */;
	struct inode *cocci_id/* kernel/fork.c 565 */;
	struct rb_node **cocci_id/* kernel/fork.c 485 */;
	struct vm_area_struct *cocci_id/* kernel/fork.c 484 */;
	struct page *cocci_id/* kernel/fork.c 395 */;
	struct vm_struct *cocci_id/* kernel/fork.c 376 */;
	void *cocci_id/* kernel/fork.c 375 */;
	struct kmem_cache *cocci_id/* kernel/fork.c 336 */;
	struct ctl_table cocci_id/* kernel/fork.c 3033 */;
	loff_t *cocci_id/* kernel/fork.c 3031 */;
	size_t *cocci_id/* kernel/fork.c 3031 */;
	struct ctl_table *cocci_id/* kernel/fork.c 3030 */;
	struct nsproxy *cocci_id/* kernel/fork.c 2890 */;
	struct cred *cocci_id/* kernel/fork.c 2889 */;
	struct files_struct **cocci_id/* kernel/fork.c 2862 */;
	struct fs_struct **cocci_id/* kernel/fork.c 2841 */;
	unsigned long cocci_id/* kernel/fork.c 2809 */;
	struct fs_struct cocci_id/* kernel/fork.c 2784 */;
	struct files_struct cocci_id/* kernel/fork.c 2780 */;
	struct signal_struct cocci_id/* kernel/fork.c 2776 */;
	struct sighand_struct cocci_id/* kernel/fork.c 2772 */;
	proc_visitor cocci_id/* kernel/fork.c 2723 */;
	pid_t cocci_id/* kernel/fork.c 2708 */[MAX_PID_NS_LEVEL];
	struct clone_args *cocci_id/* kernel/fork.c 2703 */;
	size_t cocci_id/* kernel/fork.c 2703 */;
	bool cocci_id/* kernel/fork.c 2665 */;
	void __user *cocci_id/* kernel/fork.c 2654 */;
	pid_t cocci_id/* kernel/fork.c 2629 */;
	pid_t *cocci_id/* kernel/fork.c 2587 */;
	struct clone_args cocci_id/* kernel/fork.c 2586 */;
	struct clone_args __user *cocci_id/* kernel/fork.c 2582 */;
	int *cocci_id/* kernel/fork.c 2542 */;
	vfork cocci_id/* kernel/fork.c 2528 */;
	struct kernel_clone_args cocci_id/* kernel/fork.c 2515 */;
	fork cocci_id/* kernel/fork.c 2512 */;
	int (*cocci_id/* kernel/fork.c 2499 */)(void *);
	int __user *cocci_id/* kernel/fork.c 2476 */;
	const struct kernel_clone_args *cocci_id/* kernel/fork.c 2460 */;
	int cocci_id/* kernel/fork.c 2400 */;
	struct pid *cocci_id/* kernel/fork.c 2398 */;
	struct completion cocci_id/* kernel/fork.c 2397 */;
	u64 cocci_id/* kernel/fork.c 2396 */;
	struct kernel_clone_args *cocci_id/* kernel/fork.c 2394 */;
	long cocci_id/* kernel/fork.c 2394 */;
	enum pid_type cocci_id/* kernel/fork.c 2357 */;
	unsigned long *cocci_id/* kernel/fork.c 213 */;
	struct vm_struct **cocci_id/* kernel/fork.c 196 */;
	unsigned int cocci_id/* kernel/fork.c 194 */;
	struct file *cocci_id/* kernel/fork.c 1833 */;
	struct multiprocess_signals cocci_id/* kernel/fork.c 1832 */;
	struct task_struct cocci_id/* kernel/fork.c 1803 */;
	struct task_struct *cocci_id/* kernel/fork.c 1803 */;
	struct rcu_head *cocci_id/* kernel/fork.c 1801 */;
	const struct file_operations cocci_id/* kernel/fork.c 1793 */;
	__poll_t cocci_id/* kernel/fork.c 1771 */;
	struct poll_table_struct *cocci_id/* kernel/fork.c 1771 */;
	struct pid_namespace *cocci_id/* kernel/fork.c 1740 */;
	struct seq_file *cocci_id/* kernel/fork.c 1737 */;
	const struct file *cocci_id/* kernel/fork.c 1684 */;
	void __weak cocci_id/* kernel/fork.c 160 */;
	struct list_head cocci_id/* kernel/fork.c 1568 */;
	struct signal_struct *cocci_id/* kernel/fork.c 1553 */;
	struct posix_cputimers *cocci_id/* kernel/fork.c 1544 */;
	struct sighand_struct *cocci_id/* kernel/fork.c 1527 */;
	void cocci_id/* kernel/fork.c 1527 */;
	struct io_context *cocci_id/* kernel/fork.c 1479 */;
	struct files_struct *cocci_id/* kernel/fork.c 1451 */;
	struct fs_struct *cocci_id/* kernel/fork.c 1431 */;
	const char *const cocci_id/* kernel/fork.c 130 */[];
	struct completion *cocci_id/* kernel/fork.c 1244 */;
	struct user_namespace *cocci_id/* kernel/fork.c 1007 */;
	
}
