cocci_test_suite() {
	unsigned cocci_id/* drivers/mmc/host/sdhci-tegra.c 953 */;
	unsigned long cocci_id/* drivers/mmc/host/sdhci-tegra.c 731 */;
	struct sdhci_tegra_autocal_offsets *cocci_id/* drivers/mmc/host/sdhci-tegra.c 578 */;
	struct sdhci_tegra_autocal_offsets cocci_id/* drivers/mmc/host/sdhci-tegra.c 516 */;
	struct pinctrl_state *cocci_id/* drivers/mmc/host/sdhci-tegra.c 449 */;
	u8 cocci_id/* drivers/mmc/host/sdhci-tegra.c 243 */;
	u16 cocci_id/* drivers/mmc/host/sdhci-tegra.c 239 */;
	struct platform_driver cocci_id/* drivers/mmc/host/sdhci-tegra.c 1686 */;
	struct device *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1653 */;
	int __maybe_unused cocci_id/* drivers/mmc/host/sdhci-tegra.c 1653 */;
	struct clk *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1511 */;
	const struct sdhci_tegra_soc_data *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1507 */;
	const struct of_device_id *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1506 */;
	struct platform_device *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1504 */;
	bool cocci_id/* drivers/mmc/host/sdhci-tegra.c 1461 */;
	struct cqhci_host *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1460 */;
	struct sdhci_tegra *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1459 */;
	struct sdhci_pltfm_host *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1458 */;
	struct sdhci_host *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1456 */;
	int cocci_id/* drivers/mmc/host/sdhci-tegra.c 1456 */;
	const struct of_device_id cocci_id/* drivers/mmc/host/sdhci-tegra.c 1444 */[];
	const struct sdhci_tegra_soc_data cocci_id/* drivers/mmc/host/sdhci-tegra.c 1336 */;
	const struct sdhci_pltfm_data cocci_id/* drivers/mmc/host/sdhci-tegra.c 1325 */;
	const struct sdhci_ops cocci_id/* drivers/mmc/host/sdhci-tegra.c 1310 */;
	struct sdhci_tegra {
		const struct sdhci_tegra_soc_data *soc_data;
		struct gpio_desc *power_gpio;
		bool ddr_signaling;
		bool pad_calib_required;
		bool pad_control_available;
		struct reset_control *rst;
		struct pinctrl *pinctrl_sdmmc;
		struct pinctrl_state *pinctrl_state_3v3;
		struct pinctrl_state *pinctrl_state_1v8;
		struct pinctrl_state *pinctrl_state_3v3_drv;
		struct pinctrl_state *pinctrl_state_1v8_drv;
		struct sdhci_tegra_autocal_offsets autocal_offsets;
		ktime_t last_calib;
		u32 default_tap;
		u32 default_trim;
		u32 dqs_trim;
		bool enable_hwcq;
		unsigned long curr_clk_rate;
		u8 tuned_tap_delay;
	} cocci_id/* drivers/mmc/host/sdhci-tegra.c 130 */;
	const struct cqhci_host_ops cocci_id/* drivers/mmc/host/sdhci-tegra.c 1230 */;
	u32 cocci_id/* drivers/mmc/host/sdhci-tegra.c 1182 */;
	struct mmc_host *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1179 */;
	void cocci_id/* drivers/mmc/host/sdhci-tegra.c 1179 */;
	u64 *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1168 */;
	struct mmc_request *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1168 */;
	struct sdhci_tegra_autocal_offsets {
		u32 pull_up_3v3;
		u32 pull_down_3v3;
		u32 pull_up_3v3_timeout;
		u32 pull_down_3v3_timeout;
		u32 pull_up_1v8;
		u32 pull_down_1v8;
		u32 pull_up_1v8_timeout;
		u32 pull_down_1v8_timeout;
		u32 pull_up_sdr104;
		u32 pull_down_sdr104;
		u32 pull_up_hs400;
		u32 pull_down_hs400;
	} cocci_id/* drivers/mmc/host/sdhci-tegra.c 115 */;
	ktime_t cocci_id/* drivers/mmc/host/sdhci-tegra.c 1134 */;
	struct sdhci_tegra_soc_data {
		const struct sdhci_pltfm_data *pdata;
		u64 dma_mask;
		u32 nvquirks;
		u8 min_tap_delay;
		u8 max_tap_delay;
	} cocci_id/* drivers/mmc/host/sdhci-tegra.c 106 */;
	struct mmc_ios *cocci_id/* drivers/mmc/host/sdhci-tegra.c 1050 */;
	unsigned int cocci_id/* drivers/mmc/host/sdhci-tegra.c 1017 */;
}
