cocci_test_suite() {
	struct crypto4xx_ctx *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 999 */;
	struct crypto_aead *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 997 */;
	struct crypto4xx_aead_reqctx cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 993 */;
	struct crypto4xx_alg cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 989 */;
	struct crypto4xx_alg *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 981 */;
	struct aead_alg *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 979 */;
	struct skcipher_alg *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 946 */;
	struct ce_sd *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 884 */;
	dma_addr_t cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 828 */;
	u32 *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 825 */;
	bool cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 703 */;
	unsigned int cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 699 */;
	struct ce_gd *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 691 */;
	struct dynamic_sa_ctl *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 690 */;
	const struct dynamic_sa_ctl *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 684 */;
	const u32 cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 683 */;
	const __le32 *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 683 */;
	const unsigned int cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 682 */;
	struct crypto_async_request *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 678 */;
	int cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 580 */;
	u32 cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 579 */[AES_BLOCK_SIZE];
	size_t cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 577 */;
	struct scatterlist *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 576 */;
	struct aead_request cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 575 */;
	struct aead_request *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 574 */;
	struct ce_pd *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 572 */;
	struct pd_uinfo *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 571 */;
	struct crypto4xx_device *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 570 */;
	void cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 570 */;
	union ce_pe_dma_cfg cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 57 */;
	struct ahash_request *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 556 */;
	union ce_io_threshold cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 55 */;
	union ce_part_ring_size cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 54 */;
	struct crypto_skcipher *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 538 */;
	union ce_ring_control cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 53 */;
	struct skcipher_request *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 522 */;
	union ce_ring_size cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 52 */;
	struct ce_sd cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 359 */;
	dma_addr_t *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 341 */;
	struct ce_gd cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 279 */;
	struct sa_state_record cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 193 */;
	union shadow_sa_buf cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 186 */;
	struct pd_uinfo cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 176 */;
	struct ce_pd cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 171 */;
	struct platform_driver cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1531 */;
	const struct of_device_id cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1525 */[];
	struct crypto4xx_device cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1416 */;
	struct crypto4xx_core_device cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1410 */;
	struct resource cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1377 */;
	struct platform_device *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1374 */;
	u32 cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 135 */;
	struct crypto4xx_ctx cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1201 */;
	struct crypto4xx_alg_common cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1191 */[];
	struct rng_alg *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1167 */;
	u8 *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1165 */;
	const u8 *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1164 */;
	struct crypto_rng *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1163 */;
	u32 cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1129 */[2];
	irqreturn_t cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1114 */;
	void *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1114 */;
	struct crypto4xx_core_device *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1077 */;
	struct device *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1076 */;
	unsigned long cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1074 */;
	struct crypto4xx_alg_common *cocci_id/* drivers/crypto/amcc/crypto4xx_core.c 1006 */;
}
