cocci_test_suite() {
	const struct sha1_state *cocci_id/* drivers/crypto/marvell/hash.c 955 */;
	struct sha1_state *cocci_id/* drivers/crypto/marvell/hash.c 947 */;
	struct mv_cesa_hash_ctx cocci_id/* drivers/crypto/marvell/hash.c 920 */;
	const struct md5_state *cocci_id/* drivers/crypto/marvell/hash.c 885 */;
	struct md5_state *cocci_id/* drivers/crypto/marvell/hash.c 877 */;
	u64 cocci_id/* drivers/crypto/marvell/hash.c 825 */;
	const void *cocci_id/* drivers/crypto/marvell/hash.c 824 */;
	struct crypto_ahash *cocci_id/* drivers/crypto/marvell/hash.c 809 */;
	u64 *cocci_id/* drivers/crypto/marvell/hash.c 807 */;
	bool *cocci_id/* drivers/crypto/marvell/hash.c 727 */;
	u32 cocci_id/* drivers/crypto/marvell/hash.c 605 */;
	struct mv_cesa_ahash_dma_iter cocci_id/* drivers/crypto/marvell/hash.c 600 */;
	struct mv_cesa_ahash_dma_iter *cocci_id/* drivers/crypto/marvell/hash.c 513 */;
	struct mv_cesa_op_ctx *cocci_id/* drivers/crypto/marvell/hash.c 511 */;
	struct mv_cesa_ahash_dma_req *cocci_id/* drivers/crypto/marvell/hash.c 491 */;
	gfp_t cocci_id/* drivers/crypto/marvell/hash.c 489 */;
	struct mv_cesa_tdma_chain *cocci_id/* drivers/crypto/marvell/hash.c 487 */;
	struct mv_cesa_ahash_req *cocci_id/* drivers/crypto/marvell/hash.c 439 */;
	bool cocci_id/* drivers/crypto/marvell/hash.c 437 */;
	struct ahash_request *cocci_id/* drivers/crypto/marvell/hash.c 437 */;
	struct mv_cesa_ahash_req cocci_id/* drivers/crypto/marvell/hash.c 433 */;
	struct mv_cesa_hash_ctx *cocci_id/* drivers/crypto/marvell/hash.c 428 */;
	struct crypto_tfm *cocci_id/* drivers/crypto/marvell/hash.c 426 */;
	const struct mv_cesa_req_ops cocci_id/* drivers/crypto/marvell/hash.c 401 */;
	__be32 *cocci_id/* drivers/crypto/marvell/hash.c 359 */;
	void *cocci_id/* drivers/crypto/marvell/hash.c 354 */;
	__le32 *cocci_id/* drivers/crypto/marvell/hash.c 333 */;
	int cocci_id/* drivers/crypto/marvell/hash.c 327 */;
	unsigned int cocci_id/* drivers/crypto/marvell/hash.c 326 */;
	struct mv_cesa_engine *cocci_id/* drivers/crypto/marvell/hash.c 325 */;
	struct crypto_async_request *cocci_id/* drivers/crypto/marvell/hash.c 321 */;
	struct mv_cesa_ahash_std_req *cocci_id/* drivers/crypto/marvell/hash.c 275 */;
	struct mv_cesa_req *cocci_id/* drivers/crypto/marvell/hash.c 267 */;
	struct mv_cesa_ahash_dma_iter {
		struct mv_cesa_dma_iter base;
		struct mv_cesa_sg_dma_iter src;
	} cocci_id/* drivers/crypto/marvell/hash.c 18 */;
	size_t cocci_id/* drivers/crypto/marvell/hash.c 161 */;
	__be64 cocci_id/* drivers/crypto/marvell/hash.c 146 */;
	__le64 cocci_id/* drivers/crypto/marvell/hash.c 143 */;
	struct sha256_state cocci_id/* drivers/crypto/marvell/hash.c 1429 */;
	struct sha1_state cocci_id/* drivers/crypto/marvell/hash.c 1359 */;
	u8 *cocci_id/* drivers/crypto/marvell/hash.c 133 */;
	struct mv_cesa_hmac_ctx cocci_id/* drivers/crypto/marvell/hash.c 1297 */;
	struct md5_state cocci_id/* drivers/crypto/marvell/hash.c 1289 */;
	struct ahash_alg cocci_id/* drivers/crypto/marvell/hash.c 1278 */;
	const u8 *cocci_id/* drivers/crypto/marvell/hash.c 1247 */;
	struct mv_cesa_op_ctx cocci_id/* drivers/crypto/marvell/hash.c 1237 */;
	struct mv_cesa_hmac_ctx *cocci_id/* drivers/crypto/marvell/hash.c 1225 */;
	const char *cocci_id/* drivers/crypto/marvell/hash.c 1170 */;
	struct scatterlist cocci_id/* drivers/crypto/marvell/hash.c 1091 */;
	struct mv_cesa_ahash_result cocci_id/* drivers/crypto/marvell/hash.c 1090 */;
	struct mv_cesa_ahash_result *cocci_id/* drivers/crypto/marvell/hash.c 1078 */;
	struct mv_cesa_ahash_result {
		struct completion completion;
		int error;
	} cocci_id/* drivers/crypto/marvell/hash.c 1070 */;
	void cocci_id/* drivers/crypto/marvell/hash.c 107 */;
	const struct sha256_state *cocci_id/* drivers/crypto/marvell/hash.c 1039 */;
	struct sha256_state *cocci_id/* drivers/crypto/marvell/hash.c 1031 */;
}
