cocci_test_suite() {
	union nps_pkt_in_instr_ctl cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 95 */;
	union nps_pkt_in_done_cnts cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 67 */;
	unsigned char cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 612 */[IFNAMSIZ * 2];
	union fus_dat1 cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 611 */;
	union rst_boot cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 610 */;
	union emu_fuse_map cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 609 */;
	u8 cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 568 */;
	const char *cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 568 */;
	union nps_core_gbl_vfcfg cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 560 */;
	enum vf_mode cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 558 */;
	struct nitrox_device *cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 558 */;
	void cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 558 */;
	union lbc_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 533 */;
	union lbc_inval_status cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 512 */;
	union lbc_inval_ctl cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 511 */;
	union bmo_ctl2 cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 499 */;
	union bmi_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 477 */;
	union bmi_ctl cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 476 */;
	union efl_core_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 456 */;
	union efl_rnm_ctl_status cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 441 */;
	union pom_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 422 */;
	union emu_ge_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 42 */;
	union emu_wd_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 41 */;
	union aqmq_cmp_thr cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 359 */;
	union aqmq_qsz cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 358 */;
	union aqmq_drbl cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 357 */;
	struct nitrox_cmdq *cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 356 */;
	union aqmq_en cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 341 */;
	union aqmq_cmp_cnt cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 312 */;
	union aqmq_activity_stat cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 311 */;
	union nps_core_int_ena_w1s cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 251 */;
	u64 cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 220 */;
	union nps_pkt_slc_int_levels cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 219 */;
	int cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 217 */;
	union nps_pkt_slc_ctl cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 192 */;
	union emu_ae_enable cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 17 */;
	union nps_pkt_slc_cnts cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 163 */;
	union emu_se_enable cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 16 */;
	union nps_pkt_in_instr_baoff_dbell cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 126 */;
	union nps_pkt_in_instr_rsize cocci_id/* drivers/crypto/cavium/nitrox/nitrox_hal.c 125 */;
}
