cocci_test_suite() {
	struct rsa_key cocci_id/* drivers/crypto/caam/caampkc.c 981 */;
	const void *cocci_id/* drivers/crypto/caam/caampkc.c 977 */;
	struct rsa_key *cocci_id/* drivers/crypto/caam/caampkc.c 920 */;
	unsigned int cocci_id/* drivers/crypto/caam/caampkc.c 868 */;
	struct rsa_priv_f2_pdb *cocci_id/* drivers/crypto/caam/caampkc.c 86 */;
	const u8 *cocci_id/* drivers/crypto/caam/caampkc.c 858 */;
	u8 *cocci_id/* drivers/crypto/caam/caampkc.c 858 */;
	size_t *cocci_id/* drivers/crypto/caam/caampkc.c 858 */;
	size_t cocci_id/* drivers/crypto/caam/caampkc.c 832 */;
	const u8 **cocci_id/* drivers/crypto/caam/caampkc.c 813 */;
	struct caam_rsa_key *cocci_id/* drivers/crypto/caam/caampkc.c 776 */;
	struct caam_rsa_ctx *cocci_id/* drivers/crypto/caam/caampkc.c 775 */;
	struct crypto_akcipher *cocci_id/* drivers/crypto/caam/caampkc.c 774 */;
	struct akcipher_request *cocci_id/* drivers/crypto/caam/caampkc.c 772 */;
	struct rsa_priv_f1_pdb *cocci_id/* drivers/crypto/caam/caampkc.c 74 */;
	struct rsa_edesc *cocci_id/* drivers/crypto/caam/caampkc.c 678 */;
	struct rsa_pub_pdb *cocci_id/* drivers/crypto/caam/caampkc.c 62 */;
	struct caam_akcipher_alg {
		struct akcipher_alg akcipher;
		bool registered;
	} cocci_id/* drivers/crypto/caam/caampkc.c 38 */;
	bool cocci_id/* drivers/crypto/caam/caampkc.c 36 */;
	void *cocci_id/* drivers/crypto/caam/caampkc.c 320 */;
	struct sec4_sg_entry cocci_id/* drivers/crypto/caam/caampkc.c 312 */;
	gfp_t cocci_id/* drivers/crypto/caam/caampkc.c 252 */;
	struct caam_rsa_req_ctx *cocci_id/* drivers/crypto/caam/caampkc.c 249 */;
	struct sg_mapping_iter cocci_id/* drivers/crypto/caam/caampkc.c 203 */;
	struct scatterlist *cocci_id/* drivers/crypto/caam/caampkc.c 199 */;
	struct rsa_edesc cocci_id/* drivers/crypto/caam/caampkc.c 145 */;
	u32 *cocci_id/* drivers/crypto/caam/caampkc.c 135 */;
	void cocci_id/* drivers/crypto/caam/caampkc.c 1132 */;
	u32 cocci_id/* drivers/crypto/caam/caampkc.c 1096 */;
	struct caam_drv_private *cocci_id/* drivers/crypto/caam/caampkc.c 1095 */;
	struct device *cocci_id/* drivers/crypto/caam/caampkc.c 1093 */;
	int cocci_id/* drivers/crypto/caam/caampkc.c 1093 */;
	struct caam_rsa_ctx cocci_id/* drivers/crypto/caam/caampkc.c 1087 */;
	struct caam_rsa_req_ctx cocci_id/* drivers/crypto/caam/caampkc.c 1081 */;
	struct caam_akcipher_alg cocci_id/* drivers/crypto/caam/caampkc.c 1072 */;
	struct rsa_priv_f3_pdb *cocci_id/* drivers/crypto/caam/caampkc.c 103 */;
}
