cocci_test_suite() {
	struct sk_buff *cocci_id/* drivers/vhost/net.c 976 */;
	struct sock *cocci_id/* drivers/vhost/net.c 974 */;
	struct ubuf_info *cocci_id/* drivers/vhost/net.c 895 */;
	struct vhost_net_ubuf_ref {
		atomic_t refcount;
		wait_queue_head_t wait;
		struct vhost_virtqueue *vq;
	} cocci_id/* drivers/vhost/net.c 89 */;
	struct vhost_net_ubuf_ref *cocci_id/* drivers/vhost/net.c 862 */;
	struct tun_msg_ctl cocci_id/* drivers/vhost/net.c 859 */;
	enum{VHOST_NET_VQ_RX=0, VHOST_NET_VQ_TX=1, VHOST_NET_VQ_MAX=2,} cocci_id/* drivers/vhost/net.c 83 */;
	enum{VHOST_NET_BACKEND_FEATURES=(1ULL << VHOST_BACKEND_F_IOTLB_MSG_V2),} cocci_id/* drivers/vhost/net.c 79 */;
	enum{VHOST_NET_FEATURES=VHOST_FEATURES | (1ULL << VHOST_NET_F_VIRTIO_NET_HDR) | (1ULL << VIRTIO_NET_F_MRG_RXBUF) | (1ULL << VIRTIO_F_IOMMU_PLATFORM),} cocci_id/* drivers/vhost/net.c 72 */;
	struct tun_xdp_hdr cocci_id/* drivers/vhost/net.c 717 */;
	char *cocci_id/* drivers/vhost/net.c 714 */;
	u64 cocci_id/* drivers/vhost/net.c 709 */;
	struct skb_shared_info cocci_id/* drivers/vhost/net.c 695 */;
	struct tun_xdp_hdr *cocci_id/* drivers/vhost/net.c 692 */;
	struct xdp_buff *cocci_id/* drivers/vhost/net.c 691 */;
	struct virtio_net_hdr *cocci_id/* drivers/vhost/net.c 690 */;
	struct page_frag *cocci_id/* drivers/vhost/net.c 689 */;
	gfp_t cocci_id/* drivers/vhost/net.c 646 */;
	__virtio32 cocci_id/* drivers/vhost/net.c 62 */;
	bool *cocci_id/* drivers/vhost/net.c 610 */;
	size_t *cocci_id/* drivers/vhost/net.c 610 */;
	unsigned int *cocci_id/* drivers/vhost/net.c 609 */;
	struct msghdr *cocci_id/* drivers/vhost/net.c 608 */;
	struct vhost_net_virtqueue *cocci_id/* drivers/vhost/net.c 607 */;
	struct vhost_net *cocci_id/* drivers/vhost/net.c 606 */;
	struct iov_iter *cocci_id/* drivers/vhost/net.c 594 */;
	struct vhost_poll *cocci_id/* drivers/vhost/net.c 426 */;
	struct vhost_net_virtqueue cocci_id/* drivers/vhost/net.c 425 */;
	unsigned long cocci_id/* drivers/vhost/net.c 410 */;
	void cocci_id/* drivers/vhost/net.c 410 */;
	int cocci_id/* drivers/vhost/net.c 38 */;
	struct xdp_frame *cocci_id/* drivers/vhost/net.c 201 */;
	struct miscdevice cocci_id/* drivers/vhost/net.c 1794 */;
	const struct file_operations cocci_id/* drivers/vhost/net.c 1782 */;
	struct vhost_dev *cocci_id/* drivers/vhost/net.c 1777 */;
	__poll_t cocci_id/* drivers/vhost/net.c 1774 */;
	poll_table *cocci_id/* drivers/vhost/net.c 1774 */;
	struct kiocb *cocci_id/* drivers/vhost/net.c 1754 */;
	ssize_t cocci_id/* drivers/vhost/net.c 1754 */;
	struct vhost_vring_file cocci_id/* drivers/vhost/net.c 1707 */;
	u64 __user *cocci_id/* drivers/vhost/net.c 1706 */;
	void __user *cocci_id/* drivers/vhost/net.c 1705 */;
	long cocci_id/* drivers/vhost/net.c 1701 */;
	struct vhost_net_buf *cocci_id/* drivers/vhost/net.c 169 */;
	void *cocci_id/* drivers/vhost/net.c 169 */;
	struct virtio_net_hdr_mrg_rxbuf cocci_id/* drivers/vhost/net.c 1644 */;
	struct vhost_umem *cocci_id/* drivers/vhost/net.c 1597 */;
	struct file *cocci_id/* drivers/vhost/net.c 1450 */;
	struct ptr_ring *cocci_id/* drivers/vhost/net.c 1447 */;
	struct sockaddr *cocci_id/* drivers/vhost/net.c 1433 */;
	struct {
		struct sockaddr_ll sa;
		char buf[MAX_ADDR_LEN];
	} cocci_id/* drivers/vhost/net.c 1417 */;
	struct socket *cocci_id/* drivers/vhost/net.c 1415 */;
	struct socket **cocci_id/* drivers/vhost/net.c 1356 */;
	struct vhost_net {
		struct vhost_dev dev;
		struct vhost_net_virtqueue vqs[VHOST_NET_VQ_MAX];
		struct vhost_poll poll[VHOST_NET_VQ_MAX];
		unsigned tx_packets;
		unsigned tx_zcopy_err;
		bool tx_flush;
		struct page_frag page_frag;
		int refcnt_bias;
	} cocci_id/* drivers/vhost/net.c 131 */;
	void **cocci_id/* drivers/vhost/net.c 1278 */;
	struct vhost_virtqueue **cocci_id/* drivers/vhost/net.c 1277 */;
	struct inode *cocci_id/* drivers/vhost/net.c 1273 */;
	struct vhost_net cocci_id/* drivers/vhost/net.c 1254 */;
	struct vhost_virtqueue cocci_id/* drivers/vhost/net.c 1252 */;
	struct vhost_work *cocci_id/* drivers/vhost/net.c 1250 */;
	__virtio16 cocci_id/* drivers/vhost/net.c 1120 */;
	struct iov_iter cocci_id/* drivers/vhost/net.c 1119 */;
	bool cocci_id/* drivers/vhost/net.c 1117 */;
	s16 cocci_id/* drivers/vhost/net.c 1114 */;
	size_t cocci_id/* drivers/vhost/net.c 1112 */;
	struct virtio_net_hdr cocci_id/* drivers/vhost/net.c 1108 */;
	struct msghdr cocci_id/* drivers/vhost/net.c 1101 */;
	struct vhost_net_virtqueue {
		struct vhost_virtqueue vq;
		size_t vhost_hlen;
		size_t sock_hlen;
		int upend_idx;
		int done_idx;
		int batched_xdp;
		struct ubuf_info *ubuf_info;
		struct vhost_net_ubuf_ref *ubufs;
		struct ptr_ring *rx_ring;
		struct vhost_net_buf rxq;
		struct xdp_buff *xdp;
	} cocci_id/* drivers/vhost/net.c 107 */;
	u32 cocci_id/* drivers/vhost/net.c 1042 */;
	unsigned cocci_id/* drivers/vhost/net.c 1037 */;
	unsigned int cocci_id/* drivers/vhost/net.c 1032 */;
	struct vhost_log *cocci_id/* drivers/vhost/net.c 1030 */;
	unsigned *cocci_id/* drivers/vhost/net.c 1029 */;
	struct vring_used_elem *cocci_id/* drivers/vhost/net.c 1027 */;
	struct vhost_virtqueue *cocci_id/* drivers/vhost/net.c 1026 */;
	struct vhost_net_buf {
		void **queue;
		int tail;
		int head;
	} cocci_id/* drivers/vhost/net.c 101 */;
}
