cocci_test_suite() {
	bool cocci_id/* drivers/devfreq/rk3399_dmc.c 82 */;
	unsigned long cocci_id/* drivers/devfreq/rk3399_dmc.c 79 */;
	struct rk3399_dmcfreq {
		struct device *dev;
		struct devfreq *devfreq;
		struct devfreq_simple_ondemand_data ondemand_data;
		struct clk *dmc_clk;
		struct devfreq_event_dev *edev;
		struct mutex lock;
		struct dram_timing timing;
		struct regulator *vdd_center;
		struct regmap *regmap_pmu;
		unsigned long rate,target_rate;
		unsigned long volt,target_volt;
		unsigned int odt_dis_freq;
		int odt_pd_arg0,odt_pd_arg1;
	} cocci_id/* drivers/devfreq/rk3399_dmc.c 58 */;
	struct platform_driver cocci_id/* drivers/devfreq/rk3399_dmc.c 490 */;
	const struct of_device_id cocci_id/* drivers/devfreq/rk3399_dmc.c 484 */[];
	struct dram_timing cocci_id/* drivers/devfreq/rk3399_dmc.c 359 */;
	struct rk3399_dmcfreq cocci_id/* drivers/devfreq/rk3399_dmc.c 318 */;
	u32 cocci_id/* drivers/devfreq/rk3399_dmc.c 315 */;
	struct dev_pm_opp *cocci_id/* drivers/devfreq/rk3399_dmc.c 314 */;
	uint32_t *cocci_id/* drivers/devfreq/rk3399_dmc.c 313 */;
	struct arm_smccc_res cocci_id/* drivers/devfreq/rk3399_dmc.c 308 */;
	struct platform_device *cocci_id/* drivers/devfreq/rk3399_dmc.c 306 */;
	struct dram_timing {
		unsigned int ddr3_speed_bin;
		unsigned int pd_idle;
		unsigned int sr_idle;
		unsigned int sr_mc_gate_idle;
		unsigned int srpd_lite_idle;
		unsigned int standby_idle;
		unsigned int auto_pd_dis_freq;
		unsigned int dram_dll_dis_freq;
		unsigned int phy_dll_dis_freq;
		unsigned int ddr3_odt_dis_freq;
		unsigned int ddr3_drv;
		unsigned int ddr3_odt;
		unsigned int phy_ddr3_ca_drv;
		unsigned int phy_ddr3_dq_drv;
		unsigned int phy_ddr3_odt;
		unsigned int lpddr3_odt_dis_freq;
		unsigned int lpddr3_drv;
		unsigned int lpddr3_odt;
		unsigned int phy_lpddr3_ca_drv;
		unsigned int phy_lpddr3_dq_drv;
		unsigned int phy_lpddr3_odt;
		unsigned int lpddr4_odt_dis_freq;
		unsigned int lpddr4_drv;
		unsigned int lpddr4_dq_odt;
		unsigned int lpddr4_ca_odt;
		unsigned int phy_lpddr4_ca_drv;
		unsigned int phy_lpddr4_ck_cs_drv;
		unsigned int phy_lpddr4_dq_drv;
		unsigned int phy_lpddr4_odt;
	} cocci_id/* drivers/devfreq/rk3399_dmc.c 26 */;
	struct device_node *cocci_id/* drivers/devfreq/rk3399_dmc.c 240 */;
	struct dram_timing *cocci_id/* drivers/devfreq/rk3399_dmc.c 239 */;
	int cocci_id/* drivers/devfreq/rk3399_dmc.c 239 */;
	struct devfreq_dev_profile cocci_id/* drivers/devfreq/rk3399_dmc.c 190 */;
	struct rk3399_dmcfreq *cocci_id/* drivers/devfreq/rk3399_dmc.c 183 */;
	struct device *cocci_id/* drivers/devfreq/rk3399_dmc.c 181 */;
	unsigned long *cocci_id/* drivers/devfreq/rk3399_dmc.c 181 */;
	struct devfreq_event_data cocci_id/* drivers/devfreq/rk3399_dmc.c 167 */;
	struct devfreq_dev_status *cocci_id/* drivers/devfreq/rk3399_dmc.c 164 */;
}
