cocci_test_suite() {
	struct platform_driver cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 793 */;
	const struct of_device_id cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 785 */[];
	struct phy_provider *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 715 */;
	struct platform_device *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 711 */;
	struct clk_init_data cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 683 */;
	const char *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 682 */;
	struct clk *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 681 */;
	struct device *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 680 */;
	const struct clk_ops cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 672 */;
	unsigned long cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 663 */;
	int cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 641 */;
	unsigned long *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 628 */;
	long cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 626 */;
	u64 cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 584 */;
	u8 *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 559 */;
	u16 *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 559 */;
	const struct phy_ops cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 549 */;
	enum phy_mode cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 532 */;
	struct phy *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 505 */;
	u16 cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 433 */;
	u8 cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 432 */;
	void cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 430 */;
	unsigned int cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 295 */;
	u32 cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 291 */;
	const struct {
		unsigned long rate;
		u8 hs_prepare;
		u8 clk_lane_hs_zero;
		u8 data_lane_hs_zero;
		u8 hs_trail;
	} cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 272 */[];
	struct mipi_dphy_timing cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 271 */;
	struct mipi_dphy_timing *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 241 */;
	struct inno_dsidphy cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 226 */;
	struct inno_dsidphy *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 224 */;
	struct clk_hw *cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 224 */;
	enum{REGISTER_PART_ANALOG, REGISTER_PART_DIGITAL, REGISTER_PART_CLOCK_LANE, REGISTER_PART_DATA0_LANE, REGISTER_PART_DATA1_LANE, REGISTER_PART_DATA2_LANE, REGISTER_PART_DATA3_LANE, REGISTER_PART_LVDS,} cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 213 */;
	struct inno_dsidphy {
		struct device *dev;
		struct clk *ref_clk;
		struct clk *pclk_phy;
		struct clk *pclk_host;
		void __iomem *phy_base;
		void __iomem *host_base;
		struct reset_control *rst;
		enum phy_mode mode;
		struct {
			struct clk_hw hw;
			u8 prediv;
			u16 fbdiv;
			unsigned long rate;
		} pll;
	} cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 195 */;
	struct mipi_dphy_timing {
		unsigned int clkmiss;
		unsigned int clkpost;
		unsigned int clkpre;
		unsigned int clkprepare;
		unsigned int clksettle;
		unsigned int clktermen;
		unsigned int clktrail;
		unsigned int clkzero;
		unsigned int dtermen;
		unsigned int eot;
		unsigned int hsexit;
		unsigned int hsprepare;
		unsigned int hszero;
		unsigned int hssettle;
		unsigned int hsskip;
		unsigned int hstrail;
		unsigned int init;
		unsigned int lpx;
		unsigned int taget;
		unsigned int tago;
		unsigned int tasure;
		unsigned int wakeup;
	} cocci_id/* drivers/phy/rockchip/phy-rockchip-inno-dsidphy.c 170 */;
}
