cocci_test_suite() {
	struct serdes_am654 {
		struct regmap *regmap;
		struct regmap_field *cmu_master_cdn_o;
		struct regmap_field *config_version;
		struct regmap_field *l1_master_cdn_o;
		struct regmap_field *cmu_ok_i_0;
		struct regmap_field *por_en;
		struct regmap_field *tx0_enable;
		struct regmap_field *rx0_enable;
		struct regmap_field *pll_enable;
		struct regmap_field *pll_ok;
		struct device *dev;
		struct mux_control *control;
		bool busy;
		u32 type;
		struct device_node *of_node;
		struct clk_onecell_data clk_data;
		struct clk *clks[SERDES_NUM_CLOCKS];
	} cocci_id/* drivers/phy/ti/phy-am654-serdes.c 92 */;
	const struct reg_field cocci_id/* drivers/phy/ti/phy-am654-serdes.c 82 */;
	struct regmap_config cocci_id/* drivers/phy/ti/phy-am654-serdes.c 75 */;
	struct serdes_am654_clk_mux cocci_id/* drivers/phy/ti/phy-am654-serdes.c 73 */;
	struct platform_driver cocci_id/* drivers/phy/ti/phy-am654-serdes.c 657 */;
	struct serdes_am654_clk_mux {
		struct clk_hw hw;
		struct regmap *regmap;
		unsigned int reg;
		int clk_id;
		struct clk_init_data clk_data;
	} cocci_id/* drivers/phy/ti/phy-am654-serdes.c 64 */;
	void __iomem *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 565 */;
	struct mux_control *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 562 */;
	struct clk_onecell_data *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 560 */;
	struct phy_provider *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 557 */;
	struct platform_device *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 555 */;
	const struct of_device_id cocci_id/* drivers/phy/ti/phy-am654-serdes.c 478 */[];
	char *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 437 */;
	struct clk *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 407 */;
	const __be32 *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 405 */;
	struct clk_init_data *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 402 */;
	const char **cocci_id/* drivers/phy/ti/phy-am654-serdes.c 401 */;
	struct device *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 398 */;
	struct device_node *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 397 */;
	struct serdes_am654 *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 394 */;
	const struct clk_ops cocci_id/* drivers/phy/ti/phy-am654-serdes.c 389 */;
	u32 cocci_id/* drivers/phy/ti/phy-am654-serdes.c 343 */;
	const int *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 342 */;
	int cocci_id/* drivers/phy/ti/phy-am654-serdes.c 341 */[SERDES_NUM_CLOCKS];
	const char *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 338 */;
	int cocci_id/* drivers/phy/ti/phy-am654-serdes.c 334 */;
	unsigned int cocci_id/* drivers/phy/ti/phy-am654-serdes.c 324 */;
	struct regmap *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 323 */;
	struct serdes_am654_clk_mux *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 322 */;
	u8 cocci_id/* drivers/phy/ti/phy-am654-serdes.c 320 */;
	struct clk_hw *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 320 */;
	const int cocci_id/* drivers/phy/ti/phy-am654-serdes.c 292 */[SERDES_NUM_MUX_COMBINATIONS][SERDES_NUM_CLOCKS];
	const struct phy_ops cocci_id/* drivers/phy/ti/phy-am654-serdes.c 277 */;
	struct of_phandle_args *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 251 */;
	struct phy *cocci_id/* drivers/phy/ti/phy-am654-serdes.c 203 */;
	void cocci_id/* drivers/phy/ti/phy-am654-serdes.c 126 */;
}
