cocci_test_suite() {
	struct cpcap_usb_ints_state {
		bool id_ground;
		bool id_float;
		bool chrg_det;
		bool rvrs_chrg;
		bool vbusov;
		bool chrg_se1b;
		bool se0conn;
		bool rvrs_mode;
		bool chrgcurr1;
		bool vbusvld;
		bool sessvld;
		bool sessend;
		bool se1;
		bool battdetb;
		bool dm;
		bool dp;
	} cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 94 */;
	struct platform_driver cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 664 */;
	const struct of_device_id *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 569 */;
	struct usb_otg *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 568 */;
	struct phy_provider *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 567 */;
	struct phy *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 566 */;
	const struct of_device_id cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 551 */[];
	enum iio_chan_type cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 518 */;
	enum cpcap_gpio_mode cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 364 */;
	struct platform_device *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 343 */;
	const char *const cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 332 */[];
	const char *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 310 */;
	irqreturn_t cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 296 */;
	void *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 296 */;
	struct cpcap_phy_ddata cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 217 */;
	bool cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 214 */;
	struct cpcap_usb_ints_state cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 213 */;
	struct work_struct *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 210 */;
	void cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 210 */;
	int cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 207 */(struct cpcap_phy_ddata *ddata);
	struct cpcap_usb_ints_state *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 176 */;
	struct cpcap_phy_ddata *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 175 */;
	int cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 175 */;
	const struct phy_ops cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 171 */;
	struct usb_gadget *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 162 */;
	struct usb_bus *cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 152 */;
	struct cpcap_phy_ddata {
		struct regmap *reg;
		struct device *dev;
		struct clk *refclk;
		struct usb_phy phy;
		struct delayed_work detect_work;
		struct pinctrl *pins;
		struct pinctrl_state *pins_ulpi;
		struct pinctrl_state *pins_utmi;
		struct pinctrl_state *pins_uart;
		struct gpio_desc *gpio[2];
		struct iio_channel *vbus;
		struct iio_channel *id;
		struct regulator *vusb;
		atomic_t active;
	} cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 122 */;
	enum cpcap_gpio_mode{CPCAP_DM_DP, CPCAP_MDM_RX_TX, CPCAP_UNKNOWN, CPCAP_OTG_DM_DP,} cocci_id/* drivers/phy/motorola/phy-cpcap-usb.c 115 */;
}
