cocci_test_suite() {
	struct crb_priv {
		u32 sm;
		const char *hid;
		struct crb_regs_head __iomem *regs_h;
		struct crb_regs_tail __iomem *regs_t;
		u8 __iomem *cmd;
		u8 __iomem *rsp;
		u32 cmd_size;
		u32 smc_func_id;
	} cocci_id/* drivers/char/tpm/tpm_crb.c 92 */;
	enum crb_status{CRB_DRV_STS_COMPLETE=BIT(0),} cocci_id/* drivers/char/tpm/tpm_crb.c 88 */;
	struct crb_regs_tail {
		u32 ctrl_req;
		u32 ctrl_sts;
		u32 ctrl_cancel;
		u32 ctrl_start;
		u32 ctrl_int_enable;
		u32 ctrl_int_sts;
		u32 ctrl_cmd_size;
		u32 ctrl_cmd_pa_low;
		u32 ctrl_cmd_pa_high;
		u32 ctrl_rsp_size;
		u64 ctrl_rsp_pa;
	}__packed cocci_id/* drivers/char/tpm/tpm_crb.c 74 */;
	struct acpi_driver cocci_id/* drivers/char/tpm/tpm_crb.c 736 */;
	const struct acpi_device_id cocci_id/* drivers/char/tpm/tpm_crb.c 730 */[];
	const struct dev_pm_ops cocci_id/* drivers/char/tpm/tpm_crb.c 726 */;
	struct tpm2_crb_smc cocci_id/* drivers/char/tpm/tpm_crb.c 694 */;
	struct crb_priv cocci_id/* drivers/char/tpm/tpm_crb.c 682 */;
	struct acpi_table_header **cocci_id/* drivers/char/tpm/tpm_crb.c 671 */;
	acpi_status cocci_id/* drivers/char/tpm/tpm_crb.c 666 */;
	struct tpm2_crb_smc *cocci_id/* drivers/char/tpm/tpm_crb.c 665 */;
	struct tpm_chip *cocci_id/* drivers/char/tpm/tpm_crb.c 663 */;
	struct acpi_table_tpm2 *cocci_id/* drivers/char/tpm/tpm_crb.c 661 */;
	struct acpi_device *cocci_id/* drivers/char/tpm/tpm_crb.c 659 */;
	struct crb_regs_head {
		u32 loc_state;
		u32 reserved1;
		u32 loc_ctrl;
		u32 loc_sts;
		u8 reserved2[32];
		u64 intf_id;
		u64 ctrl_ext;
	}__packed cocci_id/* drivers/char/tpm/tpm_crb.c 64 */;
	enum crb_cancel{CRB_CANCEL_INVOKE=BIT(0),} cocci_id/* drivers/char/tpm/tpm_crb.c 60 */;
	enum crb_start{CRB_START_INVOKE=BIT(0),} cocci_id/* drivers/char/tpm/tpm_crb.c 56 */;
	struct crb_regs_tail cocci_id/* drivers/char/tpm/tpm_crb.c 542 */;
	__le64 cocci_id/* drivers/char/tpm/tpm_crb.c 515 */;
	void __iomem **cocci_id/* drivers/char/tpm/tpm_crb.c 510 */;
	enum crb_ctrl_sts{CRB_CTRL_STS_ERROR=BIT(0), CRB_CTRL_STS_TPM_IDLE=BIT(1),} cocci_id/* drivers/char/tpm/tpm_crb.c 51 */;
	void __iomem *cocci_id/* drivers/char/tpm/tpm_crb.c 507 */[TPM_CRB_MAX_RESOURCES];
	struct resource cocci_id/* drivers/char/tpm/tpm_crb.c 506 */[TPM_CRB_MAX_RESOURCES + 1];
	struct list_head cocci_id/* drivers/char/tpm/tpm_crb.c 505 */;
	u64 cocci_id/* drivers/char/tpm/tpm_crb.c 486 */;
	enum crb_ctrl_req{CRB_CTRL_REQ_CMD_READY=BIT(0), CRB_CTRL_REQ_GO_IDLE=BIT(1),} cocci_id/* drivers/char/tpm/tpm_crb.c 46 */;
	struct resource cocci_id/* drivers/char/tpm/tpm_crb.c 459 */;
	void __iomem *cocci_id/* drivers/char/tpm/tpm_crb.c 456 */;
	struct resource_win cocci_id/* drivers/char/tpm/tpm_crb.c 438 */;
	struct resource *cocci_id/* drivers/char/tpm/tpm_crb.c 437 */;
	struct acpi_resource *cocci_id/* drivers/char/tpm/tpm_crb.c 435 */;
	void *cocci_id/* drivers/char/tpm/tpm_crb.c 435 */;
	const struct tpm_class_ops cocci_id/* drivers/char/tpm/tpm_crb.c 420 */;
	u8 cocci_id/* drivers/char/tpm/tpm_crb.c 412 */;
	bool cocci_id/* drivers/char/tpm/tpm_crb.c 412 */;
	enum crb_loc_state{CRB_LOC_STATE_LOC_ASSIGNED=BIT(1), CRB_LOC_STATE_TPM_REG_VALID_STS=BIT(7),} cocci_id/* drivers/char/tpm/tpm_crb.c 41 */;
	void cocci_id/* drivers/char/tpm/tpm_crb.c 400 */;
	enum crb_loc_ctrl{CRB_LOC_CTRL_REQUEST_ACCESS=BIT(0), CRB_LOC_CTRL_RELINQUISH=BIT(1),} cocci_id/* drivers/char/tpm/tpm_crb.c 36 */;
	struct arm_smccc_res cocci_id/* drivers/char/tpm/tpm_crb.c 338 */;
	union acpi_object *cocci_id/* drivers/char/tpm/tpm_crb.c 315 */;
	enum crb_defaults{CRB_ACPI_START_REVISION_ID=1, CRB_ACPI_START_INDEX=1,} cocci_id/* drivers/char/tpm/tpm_crb.c 31 */;
	__be32 *cocci_id/* drivers/char/tpm/tpm_crb.c 304 */;
	unsigned int cocci_id/* drivers/char/tpm/tpm_crb.c 284 */;
	u8 *cocci_id/* drivers/char/tpm/tpm_crb.c 281 */;
	size_t cocci_id/* drivers/char/tpm/tpm_crb.c 281 */;
	const guid_t cocci_id/* drivers/char/tpm/tpm_crb.c 27 */;
	u32 cocci_id/* drivers/char/tpm/tpm_crb.c 245 */;
	struct device *cocci_id/* drivers/char/tpm/tpm_crb.c 189 */;
	struct crb_priv *cocci_id/* drivers/char/tpm/tpm_crb.c 189 */;
	int cocci_id/* drivers/char/tpm/tpm_crb.c 189 */;
	ktime_t cocci_id/* drivers/char/tpm/tpm_crb.c 114 */;
	unsigned long cocci_id/* drivers/char/tpm/tpm_crb.c 112 */;
	u32 __iomem *cocci_id/* drivers/char/tpm/tpm_crb.c 111 */;
	struct tpm2_crb_smc {
		u32 interrupt;
		u8 interrupt_flags;
		u8 op_flags;
		u16 reserved2;
		u32 smc_func_id;
	} cocci_id/* drivers/char/tpm/tpm_crb.c 103 */;
}
