cocci_test_suite() {
	dev_t cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 883 */;
	void __exit cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 881 */;
	void cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 881 */;
	int __init cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 854 */;
	struct platform_driver cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 845 */;
	const char *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 797 */;
	const struct config_registers *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 796 */;
	struct resource *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 795 */;
	const struct of_device_id *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 794 */;
	struct platform_device *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 792 */;
	const struct of_device_id cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 791 */[];
	const unsigned int *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 750 */;
	struct resource cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 749 */;
	const struct hwicap_driver_config *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 747 */;
	struct device *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 724 */;
	struct hwicap_driver_config cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 710 */;
	unsigned long long cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 657 */;
	void *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 642 */;
	const struct resource *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 603 */;
	const struct file_operations cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 593 */;
	struct hwicap_drvdata cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 535 */;
	struct inode *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 529 */;
	struct file *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 529 */;
	char *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 482 */;
	const char __user *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 441 */;
	unsigned long cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 418 */;
	loff_t *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 356 */;
	char __user *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 356 */;
	size_t cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 356 */;
	ssize_t cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 355 */;
	u32 cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 268 */[6];
	u32 *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 265 */;
	u32 cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 233 */;
	u32 cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 232 */[4];
	struct hwicap_drvdata *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 230 */;
	int cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 230 */;
	const struct config_registers cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 120 */;
	struct class *cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 116 */;
	struct mutex cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 114 */;
	bool cocci_id/* drivers/char/xilinx_hwicap/xilinx_hwicap.c 113 */[HWICAP_DEVICES];
}
