cocci_test_suite() {
	struct rb_node *cocci_id/* block/bfq-iosched.c 890 */;
	struct bfq_sched_data *cocci_id/* block/bfq-iosched.c 821 */;
	struct rb_root_cached *cocci_id/* block/bfq-iosched.c 794 */;
	struct bfq_weight_counter *cocci_id/* block/bfq-iosched.c 741 */;
	void __exit cocci_id/* block/bfq-iosched.c 6843 */;
	struct bfq_weight_counter cocci_id/* block/bfq-iosched.c 681 */;
	int __init cocci_id/* block/bfq-iosched.c 6798 */;
	struct elevator_type cocci_id/* block/bfq-iosched.c 6767 */;
	struct elv_fs_entry cocci_id/* block/bfq-iosched.c 6753 */[];
	const char *cocci_id/* block/bfq-iosched.c 6731 */;
	size_t cocci_id/* block/bfq-iosched.c 6731 */;
	ssize_t cocci_id/* block/bfq-iosched.c 6730 */;
	char *cocci_id/* block/bfq-iosched.c 6554 */;
	struct elevator_type *cocci_id/* block/bfq-iosched.c 6409 */;
	struct elevator_queue *cocci_id/* block/bfq-iosched.c 6364 */;
	struct blk_mq_tags *cocci_id/* block/bfq-iosched.c 6351 */;
	struct sbitmap_queue *cocci_id/* block/bfq-iosched.c 6306 */;
	struct bfq_queue **cocci_id/* block/bfq-iosched.c 6269 */;
	struct bfq_data cocci_id/* block/bfq-iosched.c 6250 */;
	enum hrtimer_restart cocci_id/* block/bfq-iosched.c 6248 */;
	struct hrtimer *cocci_id/* block/bfq-iosched.c 6248 */;
	struct rb_node **cocci_id/* block/bfq-iosched.c 609 */;
	void __cold cocci_id/* block/bfq-iosched.c 606 */;
	unsigned long long cocci_id/* block/bfq-iosched.c 585 */;
	struct bfq_queue cocci_id/* block/bfq-iosched.c 564 */;
	struct list_head *cocci_id/* block/bfq-iosched.c 5538 */;
	struct rb_node ***cocci_id/* block/bfq-iosched.c 553 */;
	struct rb_root *cocci_id/* block/bfq-iosched.c 551 */;
	struct blk_mq_alloc_data *cocci_id/* block/bfq-iosched.c 535 */;
	struct bfq_ttime *cocci_id/* block/bfq-iosched.c 5182 */;
	struct bfq_group *cocci_id/* block/bfq-iosched.c 5096 */;
	pid_t cocci_id/* block/bfq-iosched.c 5036 */;
	struct bfq_queue *cocci_id/* block/bfq-iosched.c 5004 */(struct bfq_data *bfqd,
								 struct bio *bio,
								 bool is_sync,
								 struct bfq_io_cq *bic);
	struct task_struct *cocci_id/* block/bfq-iosched.c 4960 */;
	struct io_cq *cocci_id/* block/bfq-iosched.c 4945 */;
	struct request cocci_id/* block/bfq-iosched.c 4644 */;
	struct blk_mq_hw_ctx *cocci_id/* block/bfq-iosched.c 4637 */;
	sector_t cocci_id/* block/bfq-iosched.c 442 */;
	struct io_context *cocci_id/* block/bfq-iosched.c 400 */;
	struct bfq_io_cq cocci_id/* block/bfq-iosched.c 390 */;
	ktime_t cocci_id/* block/bfq-iosched.c 3719 */;
	unsigned long *cocci_id/* block/bfq-iosched.c 3717 */;
	unsigned long cocci_id/* block/bfq-iosched.c 3676 */;
	int cocci_id/* block/bfq-iosched.c 3528 */;
	struct request *cocci_id/* block/bfq-iosched.c 3527 */;
	void cocci_id/* block/bfq-iosched.c 3523 */;
	enum bfqq_expiration cocci_id/* block/bfq-iosched.c 3456 */;
	bool cocci_id/* block/bfq-iosched.c 3455 */;
	struct bfq_queue *cocci_id/* block/bfq-iosched.c 3455 */;
	struct bfq_data *cocci_id/* block/bfq-iosched.c 3455 */;
	int cocci_id/* block/bfq-iosched.c 303 */[2];
	u64 cocci_id/* block/bfq-iosched.c 2976 */;
	u32 cocci_id/* block/bfq-iosched.c 2954 */;
	struct bio *cocci_id/* block/bfq-iosched.c 2812 */;
	struct request_queue *cocci_id/* block/bfq-iosched.c 2811 */;
	void *cocci_id/* block/bfq-iosched.c 2391 */;
	enum elv_merge cocci_id/* block/bfq-iosched.c 2260 */;
	struct bfq_queue *cocci_id/* block/bfq-iosched.c 2257 */(struct request *rq);
	struct request **cocci_id/* block/bfq-iosched.c 2242 */;
	struct kmem_cache *cocci_id/* block/bfq-iosched.c 219 */;
	const unsigned long cocci_id/* block/bfq-iosched.c 217 */;
	const int cocci_id/* block/bfq-iosched.c 200 */;
	unsigned int cocci_id/* block/bfq-iosched.c 1865 */;
	bool *cocci_id/* block/bfq-iosched.c 1650 */;
	const u64 cocci_id/* block/bfq-iosched.c 164 */[2];
	struct bfq_entity *cocci_id/* block/bfq-iosched.c 1307 */;
	struct hlist_node *cocci_id/* block/bfq-iosched.c 1094 */;
	struct bfq_io_cq *cocci_id/* block/bfq-iosched.c 1008 */;
}
