cocci_test_suite() {
	u8 *cocci_id/* drivers/misc/mic/scif/scif_dma.c 868 */;
	struct scif_dma_comp_cb *cocci_id/* drivers/misc/mic/scif/scif_dma.c 847 */;
	size_t *cocci_id/* drivers/misc/mic/scif/scif_dma.c 748 */;
	void __iomem __force *cocci_id/* drivers/misc/mic/scif/scif_dma.c 718 */;
	const char *cocci_id/* drivers/misc/mic/scif/scif_dma.c 713 */;
	char *cocci_id/* drivers/misc/mic/scif/scif_dma.c 713 */;
	struct scif_window_iter *cocci_id/* drivers/misc/mic/scif/scif_dma.c 663 */;
	struct scif_dev *cocci_id/* drivers/misc/mic/scif/scif_dma.c 662 */;
	struct page **cocci_id/* drivers/misc/mic/scif/scif_dma.c 653 */;
	int cocci_id/* drivers/misc/mic/scif/scif_dma.c 648 */;
	off_t cocci_id/* drivers/misc/mic/scif/scif_dma.c 646 */;
	void *cocci_id/* drivers/misc/mic/scif/scif_dma.c 646 */;
	size_t cocci_id/* drivers/misc/mic/scif/scif_dma.c 646 */;
	struct scif_copy_work {
		s64 src_offset;
		s64 dst_offset;
		struct scif_window *src_window;
		struct scif_window *dst_window;
		int loopback;
		size_t len;
		struct scif_dma_comp_cb *comp_cb;
		struct scif_dev *remote_dev;
		int fence_type;
		bool ordered;
	} cocci_id/* drivers/misc/mic/scif/scif_dma.c 55 */;
	enum dma_status cocci_id/* drivers/misc/mic/scif/scif_dma.c 483 */;
	enum dma_ctrl_flags cocci_id/* drivers/misc/mic/scif/scif_dma.c 480 */;
	struct scif_hw_dev *cocci_id/* drivers/misc/mic/scif/scif_dma.c 475 */;
	struct completion *cocci_id/* drivers/misc/mic/scif/scif_dma.c 458 */;
	s64 *cocci_id/* drivers/misc/mic/scif/scif_dma.c 362 */;
	scif_pinned_pages_t cocci_id/* drivers/misc/mic/scif/scif_dma.c 347 */;
	off_t *cocci_id/* drivers/misc/mic/scif/scif_dma.c 343 */;
	struct scif_window **cocci_id/* drivers/misc/mic/scif/scif_dma.c 343 */;
	unsigned long cocci_id/* drivers/misc/mic/scif/scif_dma.c 342 */;
	bool cocci_id/* drivers/misc/mic/scif/scif_dma.c 297 */;
	struct scif_endpt cocci_id/* drivers/misc/mic/scif/scif_dma.c 287 */;
	struct work_struct *cocci_id/* drivers/misc/mic/scif/scif_dma.c 279 */;
	struct scif_dma_comp_cb {
		void (*dma_completion_func)(void *cookie);
		void *cb_cookie;
		u8 *temp_buf;
		u8 *temp_buf_to_free;
		bool is_cache;
		s64 dst_offset;
		struct scif_window *dst_window;
		size_t len;
		dma_addr_t temp_phys;
		struct scif_dev *sdev;
		int header_padding;
	} cocci_id/* drivers/misc/mic/scif/scif_dma.c 27 */;
	struct mm_struct *cocci_id/* drivers/misc/mic/scif/scif_dma.c 258 */;
	struct scif_endpt_rma_info *cocci_id/* drivers/misc/mic/scif/scif_dma.c 222 */;
	const struct mmu_notifier_ops cocci_id/* drivers/misc/mic/scif/scif_dma.c 214 */;
	const struct mmu_notifier_range *cocci_id/* drivers/misc/mic/scif/scif_dma.c 206 */;
	struct mmu_notifier *cocci_id/* drivers/misc/mic/scif/scif_dma.c 205 */;
	off_t __force cocci_id/* drivers/misc/mic/scif/scif_dma.c 1887 */;
	scif_epd_t cocci_id/* drivers/misc/mic/scif/scif_dma.c 1823 */;
	struct device *cocci_id/* drivers/misc/mic/scif/scif_dma.c 1649 */;
	struct scif_copy_work cocci_id/* drivers/misc/mic/scif/scif_dma.c 1643 */;
	struct scif_rma_req cocci_id/* drivers/misc/mic/scif/scif_dma.c 1639 */;
	enum scif_rma_dir cocci_id/* drivers/misc/mic/scif/scif_dma.c 1636 */;
	struct scif_mmu_notif cocci_id/* drivers/misc/mic/scif/scif_dma.c 160 */;
	struct scif_endpt *cocci_id/* drivers/misc/mic/scif/scif_dma.c 153 */;
	struct scif_window cocci_id/* drivers/misc/mic/scif/scif_dma.c 120 */;
	struct scif_window *cocci_id/* drivers/misc/mic/scif/scif_dma.c 112 */;
	struct list_head *cocci_id/* drivers/misc/mic/scif/scif_dma.c 111 */;
	dma_cookie_t cocci_id/* drivers/misc/mic/scif/scif_dma.c 1103 */;
	struct dma_device *cocci_id/* drivers/misc/mic/scif/scif_dma.c 1102 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/misc/mic/scif/scif_dma.c 1101 */;
	s64 cocci_id/* drivers/misc/mic/scif/scif_dma.c 1096 */;
	struct scif_window_iter cocci_id/* drivers/misc/mic/scif/scif_dma.c 1094 */;
	dma_addr_t cocci_id/* drivers/misc/mic/scif/scif_dma.c 1091 */;
	u64 cocci_id/* drivers/misc/mic/scif/scif_dma.c 109 */;
	struct dma_chan *cocci_id/* drivers/misc/mic/scif/scif_dma.c 1089 */;
	struct scif_copy_work *cocci_id/* drivers/misc/mic/scif/scif_dma.c 1088 */;
	struct scif_mmu_notif *cocci_id/* drivers/misc/mic/scif/scif_dma.c 108 */;
	void cocci_id/* drivers/misc/mic/scif/scif_dma.c 108 */;
}
