cocci_test_suite() {
	struct dispatch_rq_data *cocci_id/* block/blk-mq.c 982 */;
	struct sbitmap *cocci_id/* block/blk-mq.c 979 */;
	struct dispatch_rq_data {
		struct blk_mq_hw_ctx *hctx;
		struct request *rq;
	} cocci_id/* block/blk-mq.c 974 */;
	struct flush_busy_ctx_data cocci_id/* block/blk-mq.c 965 */;
	struct flush_busy_ctx_data *cocci_id/* block/blk-mq.c 947 */;
	struct flush_busy_ctx_data {
		struct blk_mq_hw_ctx *hctx;
		struct list_head *list;
	} cocci_id/* block/blk-mq.c 940 */;
	struct mq_inflight {
		struct hd_struct *part;
		unsigned int inflight[2];
	} cocci_id/* block/blk-mq.c 94 */;
	unsigned long *cocci_id/* block/blk-mq.c 858 */;
	enum blk_eh_timer_return cocci_id/* block/blk-mq.c 824 */;
	bool *cocci_id/* block/blk-mq.c 802 */;
	struct request_queue cocci_id/* block/blk-mq.c 710 */;
	struct work_struct *cocci_id/* block/blk-mq.c 707 */;
	int *cocci_id/* block/blk-mq.c 616 */;
	struct request_queue *cocci_id/* block/blk-mq.c 563 */;
	struct blk_mq_ctx *cocci_id/* block/blk-mq.c 562 */;
	struct request *cocci_id/* block/blk-mq.c 560 */;
	void cocci_id/* block/blk-mq.c 560 */;
	void *cocci_id/* block/blk-mq.c 552 */;
	u64 cocci_id/* block/blk-mq.c 520 */;
	blk_status_t cocci_id/* block/blk-mq.c 518 */;
	struct elevator_queue *cocci_id/* block/blk-mq.c 490 */;
	const int cocci_id/* block/blk-mq.c 475 */;
	const struct request *cocci_id/* block/blk-mq.c 46 */;
	void cocci_id/* block/blk-mq.c 44 */(struct blk_stat_callback *cb);
	void cocci_id/* block/blk-mq.c 43 */(struct request_queue *q);
	struct blk_mq_alloc_data cocci_id/* block/blk-mq.c 403 */;
	blk_mq_req_flags_t cocci_id/* block/blk-mq.c 401 */;
	unsigned int cocci_id/* block/blk-mq.c 400 */;
	int __init cocci_id/* block/blk-mq.c 3526 */;
	long cocci_id/* block/blk-mq.c 3469 */;
	ktime_t cocci_id/* block/blk-mq.c 3382 */;
	enum hrtimer_mode cocci_id/* block/blk-mq.c 3380 */;
	struct hrtimer_sleeper cocci_id/* block/blk-mq.c 3379 */;
	struct blk_mq_alloc_data *cocci_id/* block/blk-mq.c 336 */;
	struct blk_stat_callback *cocci_id/* block/blk-mq.c 3331 */;
	struct elevator_type *cocci_id/* block/blk-mq.c 3217 */;
	struct blk_mq_qe_pair *cocci_id/* block/blk-mq.c 3216 */;
	struct blk_mq_qe_pair {
		struct list_head node;
		struct request_queue *q;
		struct elevator_type *type;
	} cocci_id/* block/blk-mq.c 3171 */;
	struct blk_mq_tags **cocci_id/* block/blk-mq.c 2994 */;
	req_flags_t cocci_id/* block/blk-mq.c 277 */;
	struct blk_mq_hw_ctx **cocci_id/* block/blk-mq.c 2751 */;
	const struct blk_mq_ops *cocci_id/* block/blk-mq.c 2684 */;
	struct blk_mq_ctx cocci_id/* block/blk-mq.c 2612 */;
	struct blk_mq_ctxs *cocci_id/* block/blk-mq.c 2605 */;
	bool cocci_id/* block/blk-mq.c 2403 */;
	struct blk_mq_tag_set *cocci_id/* block/blk-mq.c 2403 */;
	int cocci_id/* block/blk-mq.c 2403 */;
	gfp_t cocci_id/* block/blk-mq.c 2310 */;
	struct srcu_struct cocci_id/* block/blk-mq.c 2273 */;
	struct hlist_node *cocci_id/* block/blk-mq.c 2194 */;
	struct page *cocci_id/* block/blk-mq.c 2135 */;
	size_t cocci_id/* block/blk-mq.c 2116 */;
	struct blk_mq_tags *cocci_id/* block/blk-mq.c 2055 */;
	struct page cocci_id/* block/blk-mq.c 2034 */;
	struct request cocci_id/* block/blk-mq.c 1901 */;
	struct blk_plug *cocci_id/* block/blk-mq.c 1894 */;
	blk_qc_t cocci_id/* block/blk-mq.c 1760 */;
	struct blk_mq_queue_data cocci_id/* block/blk-mq.c 1756 */;
	blk_qc_t *cocci_id/* block/blk-mq.c 1753 */;
	struct bio *cocci_id/* block/blk-mq.c 1738 */;
	enum hctx_type cocci_id/* block/blk-mq.c 1605 */;
	unsigned long cocci_id/* block/blk-mq.c 1428 */;
	struct blk_mq_hw_ctx *cocci_id/* block/blk-mq.c 1427 */;
	unsigned int cocci_id/* block/blk-mq.c 121 */[2];
	struct list_head *cocci_id/* block/blk-mq.c 1176 */;
	struct mq_inflight cocci_id/* block/blk-mq.c 113 */;
	struct hd_struct *cocci_id/* block/blk-mq.c 111 */;
	struct wait_queue_head *cocci_id/* block/blk-mq.c 1082 */;
	struct sbitmap_queue *cocci_id/* block/blk-mq.c 1060 */;
	struct blk_mq_hw_ctx cocci_id/* block/blk-mq.c 1056 */;
	wait_queue_entry_t *cocci_id/* block/blk-mq.c 1051 */;
	struct mq_inflight *cocci_id/* block/blk-mq.c 103 */;
	struct dispatch_rq_data cocci_id/* block/blk-mq.c 1003 */;
	unsigned cocci_id/* block/blk-mq.c 1002 */;
}
