cocci_test_suite() {
	struct siw_mem *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 923 */;
	struct siw_device *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 922 */;
	uintptr_t cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 921 */;
	struct ib_mr *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 921 */;
	struct siw_sqe *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 919 */;
	enum siw_opcode cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 855 */;
	enum rdmap_ecode cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 786 */;
	enum ib_access_flags cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 752 */;
	struct siw_wqe *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 751 */;
	struct ib_pd *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 751 */;
	u8 *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 732 */;
	struct siw_iwarp_tx *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 695 */;
	struct siw_qp *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 693 */;
	void cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 693 */;
	struct tcp_sock *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 663 */;
	const void *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 60 */;
	u32 cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 44 */;
	struct page *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 429 */[MAX_ARRAY];
	struct kvec cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 428 */[MAX_ARRAY];
	struct siw_sge *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 370 */;
	unsigned int cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 370 */;
	struct socket *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 369 */;
	struct page **cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 369 */;
	int cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 369 */;
	struct sock *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 327 */;
	size_t cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 325 */;
	struct kvec cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 297 */;
	struct msghdr cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 296 */;
	dma_addr_t cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 29 */;
	struct siw_pbl *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 27 */;
	u64 cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 25 */;
	struct page *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 25 */;
	int *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 25 */;
	u32 *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 249 */;
	struct siw_rreq_pkt cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 22 */;
	struct iwarp_rdma_rresp cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 214 */;
	struct iwarp_rdma_write cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 199 */;
	struct iwarp_send_inv cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 187 */;
	struct iwarp_send cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 164 */;
	struct iwarp_rdma_rreq cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 144 */;
	struct iwarp_ctrl cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 130 */;
	struct siw_qp cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1224 */;
	char *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 122 */;
	struct tx_task_t *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1196 */;
	struct llist_node *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1194 */;
	const int cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1193 */;
	long cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1193 */;
	void *cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1191 */;
	struct tx_task_t {
		struct llist_head active;
		wait_queue_head_t waiting;
	} cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1178 */;
	unsigned long cocci_id/* drivers/infiniband/sw/siw/siw_qp_tx.c 1009 */;
	__typeof__(struct tx_task_t) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
