cocci_test_suite() {
	const bool cocci_id/* block/bio.c 936 */;
	struct bio_slab cocci_id/* block/bio.c 92 */;
	unsigned cocci_id/* block/bio.c 879 */;
	ssize_t cocci_id/* block/bio.c 878 */;
	bool cocci_id/* block/bio.c 877 */;
	struct page **cocci_id/* block/bio.c 876 */;
	unsigned short cocci_id/* block/bio.c 873 */;
	size_t cocci_id/* block/bio.c 845 */;
	const struct bio_vec *cocci_id/* block/bio.c 843 */;
	struct iov_iter *cocci_id/* block/bio.c 841 */;
	struct bio_vec *cocci_id/* block/bio.c 785 */;
	unsigned int cocci_id/* block/bio.c 783 */;
	struct page *cocci_id/* block/bio.c 782 */;
	struct bio *cocci_id/* block/bio.c 782 */;
	void cocci_id/* block/bio.c 782 */;
	bool *cocci_id/* block/bio.c 686 */;
	struct request_queue *cocci_id/* block/bio.c 684 */;
	int cocci_id/* block/bio.c 684 */;
	struct bio_slab *cocci_id/* block/bio.c 66 */;
	phys_addr_t cocci_id/* block/bio.c 658 */;
	struct kmem_cache *cocci_id/* block/bio.c 62 */;
	struct bio_slab {
		struct kmem_cache *slab;
		unsigned int slab_ref;
		unsigned int slab_size;
		char name[8];
	} cocci_id/* block/bio.c 52 */;
	unsigned long cocci_id/* block/bio.c 498 */;
	struct bio_vec cocci_id/* block/bio.c 444 */;
	struct bio cocci_id/* block/bio.c 443 */;
	void *cocci_id/* block/bio.c 437 */;
	struct bio_set *cocci_id/* block/bio.c 430 */;
	gfp_t cocci_id/* block/bio.c 429 */;
	struct biovec_slab cocci_id/* block/bio.c 37 */[BVEC_POOL_NR]__read_mostly;
	struct bio_list cocci_id/* block/bio.c 359 */;
	struct bio_set cocci_id/* block/bio.c 342 */;
	struct work_struct *cocci_id/* block/bio.c 340 */;
	int __init cocci_id/* block/bio.c 2156 */;
	void __init cocci_id/* block/bio.c 2137 */;
	struct cgroup_subsys_state *cocci_id/* block/bio.c 2105 */;
	struct blkcg_gq *cocci_id/* block/bio.c 2033 */;
	struct biovec_slab *cocci_id/* block/bio.c 1898 */;
	mempool_t *cocci_id/* block/bio.c 1896 */;
	struct hd_struct *cocci_id/* block/bio.c 1739 */;
	unsigned long *cocci_id/* block/bio.c 169 */;
	struct bvec_iter_all cocci_id/* block/bio.c 1688 */;
	void cocci_id/* block/bio.c 1658 */(struct work_struct *work);
	char *cocci_id/* block/bio.c 1527 */;
	const int cocci_id/* block/bio.c 1474 */;
	struct rq_map_data *cocci_id/* block/bio.c 1225 */;
	struct iov_iter cocci_id/* block/bio.c 1150 */;
	struct iovec cocci_id/* block/bio.c 1105 */;
	struct bio_map_data *cocci_id/* block/bio.c 1095 */;
	struct bio_map_data {
		int is_our_pages;
		struct iov_iter iter;
		struct iovec iov[];
	} cocci_id/* block/bio.c 1089 */;
	struct bvec_iter cocci_id/* block/bio.c 1045 */;
	struct bvec_iter *cocci_id/* block/bio.c 1004 */;
}
