cocci_test_suite() {
	typeof(*mem) cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 96 */;
	struct rxe_pool_entry *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 94 */;
	u64 *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 592 */;
	struct rxe_dev *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 572 */;
	enum lookup_type cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 569 */;
	u32 cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 568 */;
	struct rxe_sge *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 531 */;
	struct rxe_dma_info *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 529 */;
	unsigned int cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 529 */;
	int cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 529 */;
	u64 cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 449 */;
	struct rxe_mem *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 448 */;
	u32 *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 442 */;
	enum copy_direction cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 441 */;
	void *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 439 */;
	struct rxe_pd *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 436 */;
	u8 cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 40 */;
	struct rxe_phys_buf *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 351 */;
	u8 *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 349 */;
	uintptr_t cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 316 */;
	size_t cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 305 */;
	size_t *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 268 */;
	int *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 266 */;
	void cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 263 */;
	struct sg_page_iter cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 167 */;
	struct ib_umem *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 166 */;
	struct ib_udata *cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 161 */;
	struct rxe_map **cocci_id/* drivers/infiniband/sw/rxe/rxe_mr.c 113 */;
}
