cocci_test_suite() {
	struct rxe_mem *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 981 */;
	struct rxe_pd *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 980 */;
	struct ib_udata *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 977 */;
	enum ib_mr_type cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 976 */;
	struct ib_pd *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 976 */;
	struct ib_mr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 976 */;
	u64 cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 930 */;
	enum ib_cq_notify_flags cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 880 */;
	struct rxe_cqe *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 855 */;
	struct ib_wc *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 851 */;
	u16 *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 84 */;
	struct rxe_resize_cq_resp __user *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 829 */;
	struct rxe_create_cq_resp __user *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 792 */;
	struct rxe_cq *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 791 */;
	struct ib_device *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 789 */;
	const struct ib_cq_init_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 785 */;
	struct ib_cq *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 785 */;
	const struct ib_recv_wr **cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 746 */;
	const struct ib_send_wr **cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 723 */;
	unsigned long cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 644 */;
	struct rxe_sq *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 642 */;
	struct ib_sge cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 622 */;
	uintptr_t cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 611 */;
	void *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 611 */;
	u8 *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 597 */;
	struct ib_sge *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 595 */;
	struct rxe_send_wqe *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 592 */;
	unsigned int cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 591 */;
	const struct ib_send_wr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 590 */;
	struct rxe_qp *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 590 */;
	int cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 590 */;
	struct ib_port_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 56 */;
	struct rxe_send_wr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 534 */;
	void cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 534 */;
	struct ib_qp_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 465 */;
	struct ib_device_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 43 */;
	struct rxe_create_qp_resp __user *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 423 */;
	struct ib_qp_init_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 416 */;
	struct rxe_modify_srq_cmd cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 342 */;
	enum ib_srq_attr_mask cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 336 */;
	struct ib_srq_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 335 */;
	struct rxe_create_srq_resp __user *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 303 */;
	struct rxe_srq *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 302 */;
	struct ib_srq_init_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 296 */;
	struct ib_srq *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 296 */;
	struct rxe_recv_wqe *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 254 */;
	u32 cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 253 */;
	const struct ib_recv_wr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 249 */;
	struct rxe_rq *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 249 */;
	struct rxe_ah *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 204 */;
	struct rdma_ah_attr *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 198 */;
	struct ib_ah *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 198 */;
	struct ib_port_attr cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 168 */;
	struct ib_port_immutable *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 165 */;
	struct rxe_ucontext *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 152 */;
	struct ib_ucontext *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 149 */;
	u8 cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 142 */;
	enum rdma_link_layer cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 141 */;
	struct rxe_port *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 128 */;
	struct ib_port_modify *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 125 */;
	struct device_dma_parameters cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1179 */;
	unsigned char *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1175 */;
	struct crypto_shash *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1166 */;
	const char *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1162 */;
	const struct ib_device_ops cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1105 */;
	const struct attribute_group cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1092 */;
	struct attribute *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1087 */[];
	struct rxe_dev cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1080 */;
	struct rxe_dev *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1079 */;
	struct device_attribute *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1077 */;
	char *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1077 */;
	struct device *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1076 */;
	ssize_t cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1076 */;
	struct rxe_mc_grp *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1055 */;
	u16 cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1050 */;
	union ib_gid *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1050 */;
	struct ib_qp *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1050 */;
	struct ib_device_modify *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 105 */;
	unsigned int *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1031 */;
	struct scatterlist *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1030 */;
	struct rxe_phys_buf *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1015 */;
	struct rxe_map *cocci_id/* drivers/infiniband/sw/rxe/rxe_verbs.c 1014 */;
}
