cocci_test_suite() {
	struct ib_recv_wr cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 989 */;
	struct iser_login_desc *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 988 */;
	struct iser_comp *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 97 */;
	void *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 946 */;
	struct sockaddr *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 927 */;
	struct rdma_cm_event *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 848 */;
	bool cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 834 */;
	u8 *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 808 */;
	struct ib_qp_init_attr cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 797 */;
	struct ib_qp_attr cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 796 */;
	const void *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 793 */;
	struct iser_cm_hdr cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 755 */;
	struct rdma_conn_param cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 753 */;
	int cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 708 */;
	struct ib_conn *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 707 */;
	struct iser_conn *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 706 */;
	struct iser_device *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 705 */;
	struct rdma_cm_id *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 703 */;
	void cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 703 */;
	struct ib_device *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 70 */;
	u32 cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 667 */;
	unsigned short cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 665 */;
	struct ib_device_attr *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 664 */;
	struct ib_event *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 54 */;
	struct ib_event_handler *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 53 */;
	struct iser_conn cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 519 */;
	struct work_struct *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 515 */;
	enum iser_conn_state cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 503 */;
	struct iser_fr_desc *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 314 */;
	struct iser_fr_pool *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 313 */;
	unsigned int cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 310 */;
	unsigned cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 309 */;
	struct iser_reg_resources *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 289 */;
	enum ib_mr_type cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 248 */;
	struct ib_pd *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 242 */;
	struct iser_fr_desc cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 229 */;
	u64 *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 184 */;
	u64 cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 177 */;
	struct ib_fmr_pool_param cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 167 */;
	struct ib_fmr_pool *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 166 */;
	struct iser_page_vec *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 164 */;
	const char *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1133 */;
	struct ib_wc *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1133 */;
	unsigned long long cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1115 */;
	sector_t cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1107 */;
	struct ib_mr_status cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1092 */;
	unsigned long cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1091 */;
	struct iser_mem_reg *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1089 */;
	enum iser_data_dir cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1087 */;
	sector_t *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1087 */;
	u8 cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1086 */;
	struct iscsi_iser_task *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1086 */;
	struct ib_send_wr *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1056 */;
	struct iser_tx_desc *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1053 */;
	struct ib_recv_wr *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1017 */;
	struct iser_rx_desc *cocci_id/* drivers/infiniband/ulp/iser/iser_verbs.c 1016 */;
}
