cocci_test_suite() {
	int __init cocci_id/* block/scsi_ioctl.c 839 */;
	void cocci_id/* block/scsi_ioctl.c 839 */;
	struct block_device *cocci_id/* block/scsi_ioctl.c 811 */;
	struct cdrom_generic_command __user *cocci_id/* block/scsi_ioctl.c 756 */;
	struct request_sense cocci_id/* block/scsi_ioctl.c 754 */;
	struct cdrom_generic_command cocci_id/* block/scsi_ioctl.c 720 */;
	struct sg_io_hdr cocci_id/* block/scsi_ioctl.c 633 */;
	struct compat_sg_io_hdr cocci_id/* block/scsi_ioctl.c 627 */;
	const void __user *cocci_id/* block/scsi_ioctl.c 624 */;
	uintptr_t cocci_id/* block/scsi_ioctl.c 592 */;
	const struct sg_io_hdr *cocci_id/* block/scsi_ioctl.c 581 */;
	void __user *cocci_id/* block/scsi_ioctl.c 581 */;
	struct compat_sg_io_hdr {
		compat_int_t interface_id;
		compat_int_t dxfer_direction;
		unsigned char cmd_len;
		unsigned char mx_sb_len;
		unsigned short iovec_count;
		compat_uint_t dxfer_len;
		compat_uint_t dxferp;
		compat_uptr_t cmdp;
		compat_uptr_t sbp;
		compat_uint_t timeout;
		compat_uint_t flags;
		compat_int_t pack_id;
		compat_uptr_t usr_ptr;
		unsigned char status;
		unsigned char masked_status;
		unsigned char msg_status;
		unsigned char sb_len_wr;
		unsigned short host_status;
		unsigned short driver_status;
		compat_int_t resid;
		compat_uint_t duration;
		compat_uint_t info;
	} cocci_id/* block/scsi_ioctl.c 554 */;
	struct request *cocci_id/* block/scsi_ioctl.c 530 */;
	struct request_queue *cocci_id/* block/scsi_ioctl.c 527 */;
	struct gendisk *cocci_id/* block/scsi_ioctl.c 527 */;
	int cocci_id/* block/scsi_ioctl.c 527 */;
	int __user *cocci_id/* block/scsi_ioctl.c 52 */;
	const int cocci_id/* block/scsi_ioctl.c 43 */;
	char *cocci_id/* block/scsi_ioctl.c 420 */;
	enum{OMAX_SB_LEN=16,} cocci_id/* block/scsi_ioctl.c 415 */;
	struct scsi_ioctl_command __user *cocci_id/* block/scsi_ioctl.c 413 */;
	struct iovec *cocci_id/* block/scsi_ioctl.c 329 */;
	struct iov_iter cocci_id/* block/scsi_ioctl.c 328 */;
	const unsigned char cocci_id/* block/scsi_ioctl.c 32 */[8];
	struct blk_cmd_filter cocci_id/* block/scsi_ioctl.c 29 */;
	ssize_t cocci_id/* block/scsi_ioctl.c 283 */;
	unsigned long cocci_id/* block/scsi_ioctl.c 282 */;
	unsigned int cocci_id/* block/scsi_ioctl.c 264 */;
	struct scsi_request *cocci_id/* block/scsi_ioctl.c 246 */;
	struct bio *cocci_id/* block/scsi_ioctl.c 244 */;
	struct sg_io_hdr *cocci_id/* block/scsi_ioctl.c 243 */;
	struct blk_cmd_filter {
		unsigned long read_ok[BLK_SCSI_CMD_PER_LONG];
		unsigned long write_ok[BLK_SCSI_CMD_PER_LONG];
	} cocci_id/* block/scsi_ioctl.c 24 */;
	fmode_t cocci_id/* block/scsi_ioctl.c 218 */;
	unsigned char *cocci_id/* block/scsi_ioctl.c 197 */;
	struct blk_cmd_filter *cocci_id/* block/scsi_ioctl.c 111 */;
}
