cocci_test_suite() {
	struct ib_cq_init_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 994 */;
	struct ib_uverbs_ex_create_cq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 993 */;
	struct ib_cq *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 991 */;
	struct ib_uverbs_ex_create_cq *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 987 */;
	struct ib_ucq_object *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 986 */;
	struct ib_uverbs_create_comp_channel_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 957 */;
	struct ib_uverbs_create_comp_channel cocci_id/* drivers/infiniband/core/uverbs_cmd.c 956 */;
	struct ib_uverbs_dealloc_mw cocci_id/* drivers/infiniband/core/uverbs_cmd.c 944 */;
	struct ib_mw *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 886 */;
	struct ib_uverbs_alloc_mw_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 883 */;
	struct ib_uverbs_alloc_mw cocci_id/* drivers/infiniband/core/uverbs_cmd.c 882 */;
	struct ib_uverbs_dereg_mr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 870 */;
	struct ib_uverbs_rereg_mr_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 793 */;
	struct ib_uverbs_rereg_mr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 792 */;
	struct ib_mr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 712 */;
	struct ib_uverbs_reg_mr_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 709 */;
	struct ib_uverbs_reg_mr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 708 */;
	enum rdma_remove_reason cocci_id/* drivers/infiniband/core/uverbs_cmd.c 682 */;
	struct ib_uverbs_close_xrcd cocci_id/* drivers/infiniband/core/uverbs_cmd.c 671 */;
	struct fd cocci_id/* drivers/infiniband/core/uverbs_cmd.c 565 */;
	struct ib_uxrcd_object *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 563 */;
	struct ib_uverbs_open_xrcd_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 562 */;
	struct ib_uverbs_open_xrcd cocci_id/* drivers/infiniband/core/uverbs_cmd.c 561 */;
	struct xrcd_table_entry *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 536 */;
	struct inode *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 534 */;
	struct ib_uverbs_device *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 534 */;
	struct xrcd_table_entry cocci_id/* drivers/infiniband/core/uverbs_cmd.c 496 */;
	struct rb_node *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 485 */;
	struct rb_node **cocci_id/* drivers/infiniband/core/uverbs_cmd.c 484 */;
	struct xrcd_table_entry {
		struct rb_node node;
		struct ib_xrcd *xrcd;
		struct inode *inode;
	} cocci_id/* drivers/infiniband/core/uverbs_cmd.c 473 */;
	struct ib_uverbs_dealloc_pd cocci_id/* drivers/infiniband/core/uverbs_cmd.c 463 */;
	struct ib_uverbs_alloc_pd_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 410 */;
	struct ib_uverbs_alloc_pd cocci_id/* drivers/infiniband/core/uverbs_cmd.c 409 */;
	struct ib_uverbs_modify_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3949 */;
	struct ib_port_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 383 */;
	struct ib_uverbs_query_port_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 382 */;
	struct ib_uverbs_query_port cocci_id/* drivers/infiniband/core/uverbs_cmd.c 381 */;
	struct ib_uverbs_create_cq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3789 */;
	const struct uapi_definition cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3759 */[];
	struct ib_uverbs_ex_modify_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3689 */;
	struct ib_device_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3627 */;
	struct ib_uverbs_ex_query_device cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3626 */;
	struct ib_uverbs_ex_query_device_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3625 */;
	struct ib_uevent_object cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3614 */;
	struct ib_uverbs_query_device_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 361 */;
	struct ib_uevent_object *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3603 */;
	struct ib_uverbs_destroy_srq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3601 */;
	struct ib_uverbs_destroy_srq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3600 */;
	struct ib_uverbs_query_device cocci_id/* drivers/infiniband/core/uverbs_cmd.c 360 */;
	struct ib_uverbs_query_srq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3569 */;
	struct ib_uverbs_query_srq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3568 */;
	struct ib_srq_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3544 */;
	struct ib_uverbs_modify_srq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3542 */;
	struct ib_uverbs_create_xsrq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3509 */;
	struct ib_uverbs_create_srq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3508 */;
	struct ib_uxrcd_object cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3400 */;
	struct ib_xrcd *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3394 */;
	struct ib_device *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3376 */;
	struct ib_srq_init_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3374 */;
	struct ib_uobject *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3373 */;
	struct ib_srq *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3372 */;
	struct ib_pd *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3371 */;
	struct ib_usrq_object *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3370 */;
	struct ib_uverbs_create_srq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3369 */;
	struct ib_udata *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3367 */;
	struct ib_uverbs_create_xsrq *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3366 */;
	struct uverbs_attr_bundle *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3365 */;
	int cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3365 */;
	struct ib_uverbs_destroy_flow cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3352 */;
	union ib_flow_spec *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3299 */;
	struct ib_uverbs_flow_spec *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3293 */;
	struct ib_uverbs_flow_spec cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3224 */;
	struct uverbs_req_iter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3196 */;
	struct ib_uverbs_flow_spec_hdr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3195 */;
	struct ib_flow_attr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3192 */;
	struct ib_uverbs_flow_attr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3191 */;
	struct ib_flow *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3190 */;
	struct ib_uverbs_create_flow_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3188 */;
	struct ib_uverbs_create_flow cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3187 */;
	struct ib_uverbs_ex_destroy_rwq_ind_table cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3171 */;
	struct ib_device_attr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 312 */;
	struct ib_uverbs_query_device_resp *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 311 */;
	struct ib_ucontext *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 310 */;
	u32 cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3067 */;
	struct ib_wq *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3065 */;
	u32 *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3064 */;
	struct ib_wq **cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3063 */;
	struct ib_rwq_ind_table_init_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3061 */;
	struct ib_uverbs_ex_create_rwq_ind_table_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3058 */;
	struct ib_uverbs_ex_create_rwq_ind_table cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3057 */;
	struct ib_wq_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3026 */;
	struct ib_uverbs_ex_modify_wq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3024 */;
	struct ib_uwq_object cocci_id/* drivers/infiniband/core/uverbs_cmd.c 3014 */;
	struct ib_uverbs_ex_destroy_wq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2997 */;
	struct ib_uverbs_ex_destroy_wq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2996 */;
	struct ib_wq_init_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2912 */;
	struct ib_uwq_object *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2907 */;
	struct ib_uverbs_ex_create_wq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2906 */;
	struct ib_uverbs_ex_create_wq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2905 */;
	struct ib_flow_spec_mpls cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2859 */;
	struct ib_flow_mpls_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2853 */;
	struct ib_flow_spec_gre cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2848 */;
	struct ib_flow_gre_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2842 */;
	struct ib_flow_spec_esp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2837 */;
	struct ib_flow_esp_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2831 */;
	struct ib_flow_spec_tunnel cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2822 */;
	struct ib_flow_tunnel_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2816 */;
	struct ib_flow_spec_tcp_udp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2811 */;
	struct ib_flow_tcp_udp_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2805 */;
	struct ib_flow_spec_ipv6 cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2795 */;
	struct ib_flow_ipv6_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2789 */;
	struct ib_flow_spec_ipv4 cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2784 */;
	struct ib_flow_ipv4_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2778 */;
	struct ib_flow_spec_eth cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2773 */;
	struct ib_flow_eth_filter cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2767 */;
	ssize_t cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2753 */;
	const void *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2748 */;
	u16 cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2729 */;
	struct ib_uverbs_flow_spec_hdr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2726 */;
	const struct ib_uverbs_flow_spec_hdr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2723 */;
	struct ib_flow_spec_action_count cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2711 */;
	struct ib_uverbs_flow_spec_action_count cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2701 */;
	struct ib_flow_spec_action_handle cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2693 */;
	struct ib_uverbs_flow_spec_action_handle cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2684 */;
	struct ib_flow_spec_action_drop cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2680 */;
	struct ib_uverbs_flow_spec_action_drop cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2677 */;
	struct ib_flow_spec_action_tag cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2672 */;
	struct ib_uverbs_flow_spec_action_tag cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2669 */;
	struct ib_counters *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2648 */;
	struct ib_flow_action *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2643 */;
	enum ib_flow_spec_type cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2636 */;
	struct ib_uflow_resources *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2635 */;
	unsigned int cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2618 */;
	union ib_gid *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2576 */;
	struct ib_uverbs_detach_mcast cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2544 */;
	struct ib_uqp_object cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2510 */;
	struct ib_uverbs_mcast_entry *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2499 */;
	struct ib_uverbs_attach_mcast cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2496 */;
	struct ib_uverbs_destroy_ah cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2484 */;
	struct rdma_ah_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2410 */;
	struct ib_ah *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2409 */;
	struct ib_uverbs_create_ah_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2406 */;
	struct ib_uverbs_create_ah cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2405 */;
	struct ib_uverbs_post_srq_recv_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2355 */;
	struct ib_uverbs_post_srq_recv cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2354 */;
	const struct ib_recv_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2307 */;
	struct ib_recv_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2306 */;
	struct ib_uverbs_post_recv_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2305 */;
	struct ib_uverbs_post_recv cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2304 */;
	struct ib_uverbs_recv_wr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2216 */;
	struct ib_uverbs_recv_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2208 */;
	struct uverbs_req_iter *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2205 */;
	__be32 __force cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2143 */;
	struct ib_rdmacg_object cocci_id/* drivers/infiniband/core/uverbs_cmd.c 213 */;
	struct file *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 212 */;
	struct ib_atomic_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2111 */;
	struct ib_uverbs_get_context_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 210 */;
	struct ib_rdma_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2096 */;
	struct ib_uverbs_get_context cocci_id/* drivers/infiniband/core/uverbs_cmd.c 209 */;
	struct ib_uverbs_file *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 208 */;
	struct ib_ud_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2067 */;
	struct ib_uverbs_sge cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2034 */;
	const void __user *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2024 */;
	const struct ib_sge __user *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2023 */;
	const struct ib_send_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2017 */;
	struct ib_send_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2016 */;
	struct ib_uverbs_send_wr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2015 */;
	struct ib_uverbs_post_send_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2014 */;
	struct ib_uverbs_post_send cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2013 */;
	struct ib_sge cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2003 */;
	__u32 cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2001 */;
	size_t cocci_id/* drivers/infiniband/core/uverbs_cmd.c 2001 */;
	struct ib_uverbs_completion_event_file cocci_id/* drivers/infiniband/core/uverbs_cmd.c 200 */;
	struct ib_uverbs_destroy_qp_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1979 */;
	struct ib_uverbs_destroy_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1978 */;
	struct ib_uverbs_ex_modify_qp_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1950 */;
	void *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 195 */;
	struct ib_uverbs_ex_modify_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1949 */;
	s32 cocci_id/* drivers/infiniband/core/uverbs_cmd.c 189 */;
	struct ib_uverbs_completion_event_file *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 188 */;
	struct ib_udata cocci_id/* drivers/infiniband/core/uverbs_cmd.c 184 */;
	struct ib_uverbs_ex_modify_qp *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1773 */;
	struct ib_uverbs_qp_dest *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1751 */;
	struct rdma_ah_attr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1750 */;
	void cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1749 */;
	enum ib_qp_type cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1736 */;
	struct ib_qp_init_attr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1665 */;
	struct ib_qp_attr *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1664 */;
	struct ib_uverbs_query_qp_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1662 */;
	struct ib_uverbs_query_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1661 */;
	void __force __user *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 165 */;
	const struct ib_global_route *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1640 */;
	struct ib_qp_open_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1570 */;
	struct ib_uverbs_create_qp_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1565 */;
	struct ib_uverbs_open_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1564 */;
	struct ib_uverbs_ex_create_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1519 */;
	struct ib_uverbs_create_qp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1518 */;
	bool cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1286 */;
	struct ib_rwq_ind_table *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1285 */;
	struct ib_uverbs_ex_create_qp_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1283 */;
	struct ib_qp_init_attr cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1282 */;
	struct ib_qp *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1281 */;
	struct ib_uqp_object *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1274 */;
	struct ib_uverbs_ex_create_qp *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1272 */;
	struct ib_ucq_object cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1261 */;
	struct uverbs_req_iter {
		const void __user *cur;
		const void __user *end;
	} cocci_id/* drivers/infiniband/core/uverbs_cmd.c 125 */;
	struct ib_uverbs_destroy_cq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1248 */;
	struct ib_uverbs_destroy_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1247 */;
	struct ib_uverbs_req_notify_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1225 */;
	struct ib_wc cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1178 */;
	u8 __user *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1175 */;
	struct ib_uverbs_poll_cq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1174 */;
	struct ib_uverbs_poll_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1173 */;
	struct ib_uverbs_wc cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1144 */;
	struct ib_wc *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1142 */;
	void __user *cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1141 */;
	struct ib_uverbs_resize_cq_resp cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1116 */;
	struct ib_uverbs_resize_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1115 */;
	struct ib_uverbs_ex_create_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1075 */;
	struct ib_uverbs_create_cq cocci_id/* drivers/infiniband/core/uverbs_cmd.c 1074 */;
}
