cocci_test_suite() {
	struct mlx4_ib_qp **cocci_id/* drivers/infiniband/hw/mlx4/qp.c 992 */;
	enum{MLX4_RAW_QP_MTU=7, MLX4_RAW_QP_MSGMAX=31,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 96 */;
	enum{MLX4_IB_MIN_SQ_STRIDE=6, MLX4_IB_CACHE_LINE_SIZE=64,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 91 */;
	struct mlx4_ib_create_wq cocci_id/* drivers/infiniband/hw/mlx4/qp.c 869 */;
	struct mlx4_ib_sqp {
		struct mlx4_ib_qp qp;
		int pkey_index;
		u32 qkey;
		u32 send_psn;
		struct ib_ud_header ud_header;
		u8 header_buf[MLX4_IB_UD_HEADER_SIZE];
		struct ib_qp *roce_v2_gsi;
	} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 81 */;
	struct mlx4_wqn_range cocci_id/* drivers/infiniband/hw/mlx4/qp.c 790 */;
	struct mlx4_wqn_range *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 784 */;
	int *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 781 */;
	typeof(ucmd) cocci_id/* drivers/infiniband/hw/mlx4/qp.c 716 */;
	size_t cocci_id/* drivers/infiniband/hw/mlx4/qp.c 705 */;
	struct mlx4_ib_create_qp_rss cocci_id/* drivers/infiniband/hw/mlx4/qp.c 704 */;
	enum{MLX4_IB_UD_HEADER_SIZE=82, MLX4_IB_LSO_HEADER_SPARE=128,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 70 */;
	struct mlx4_ib_create_qp_rss *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 643 */;
	enum{MLX4_IB_DEFAULT_SCHED_QUEUE=0x83, MLX4_IB_DEFAULT_QP0_SCHED_QUEUE=0x3f, MLX4_IB_LINK_TYPE_IB=0, MLX4_IB_LINK_TYPE_ETH=1,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 63 */;
	enum{MLX4_IB_ACK_REQ_FREQ=8,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 59 */;
	int cocci_id/* drivers/infiniband/hw/mlx4/qp.c 56 */(struct ib_wq *ibwq,
							     enum ib_wq_state new_state,
							     struct ib_udata *udata);
	struct mlx4_ib_rss *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 539 */;
	void cocci_id/* drivers/infiniband/hw/mlx4/qp.c 52 */(struct mlx4_ib_cq *send_cq,
							      struct mlx4_ib_cq *recv_cq);
	struct mlx4_ib_buf cocci_id/* drivers/infiniband/hw/mlx4/qp.c 462 */;
	struct ib_device *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 457 */;
	struct ib_recv_wr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4508 */;
	struct ib_rdma_wr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4474 */;
	struct mlx4_dev *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4423 */;
	struct mlx4_ib_drain_cqe *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4420 */;
	struct ib_cq *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4419 */;
	struct mlx4_ib_drain_cqe cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4412 */;
	struct ib_wc *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4409 */;
	struct mlx4_ib_drain_cqe {
		struct ib_cqe cqe;
		struct completion done;
	} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4404 */;
	struct mlx4_ib_create_qp *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 439 */;
	typeof(resp) cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4352 */;
	unsigned int cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4341 */;
	struct mlx4_ib_create_rwq_ind_tbl_resp cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4340 */;
	struct ib_rwq_ind_table_init_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4336 */;
	struct mlx4_ib_modify_wq cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4264 */;
	struct ib_wq_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4260 */;
	struct ib_qp_attr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4223 */;
	enum ib_wq_state cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4204 */;
	struct ib_qp_init_attr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4125 */;
	struct ib_wq_init_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 4121 */;
	struct rdma_ah_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3980 */;
	enum ib_mig_state cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3955 */;
	enum mlx4_qp_state cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3940 */;
	struct mlx4_ib_proxy_sqp_hdr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3891 */;
	unsigned long cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3851 */;
	bool cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3847 */;
	const struct ib_recv_wr **cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3847 */;
	const struct ib_recv_wr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3846 */;
	struct mlx4_wqe_data_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3766 */;
	struct ib_qp_cap *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 372 */;
	struct mlx4_wqe_datagram_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3687 */;
	struct mlx4_wqe_fmr_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3661 */;
	struct mlx4_wqe_local_inval_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3653 */;
	struct mlx4_wqe_masked_atomic_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3633 */;
	struct mlx4_wqe_atomic_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3620 */;
	struct mlx4_wqe_raddr_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3617 */;
	union ib_gid cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3550 */;
	struct mlx4_ib_ah *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3548 */;
	struct mlx4_ib_sqp *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3545 */;
	__be32 *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3538 */;
	__be32 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3537 */;
	unsigned cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3534 */;
	const struct ib_send_wr **cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3525 */;
	const struct ib_send_wr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3524 */;
	struct mlx4_wqe_inline_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3519 */;
	unsigned *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3484 */;
	const struct ib_ud_wr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3483 */;
	struct mlx4_wqe_lso_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3482 */;
	struct mlx4_wqe_data_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3475 */;
	struct ib_sge *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3475 */;
	void cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3475 */;
	u32 *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3439 */;
	union mlx4_ext_av *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3379 */;
	struct mlx4_av cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3367 */;
	struct mlx4_wqe_datagram_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3364 */;
	struct mlx4_wqe_masked_atomic_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3355 */;
	const struct ib_atomic_wr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3340 */;
	struct mlx4_wqe_atomic_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3339 */;
	struct mlx4_wqe_raddr_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3331 */;
	struct mlx4_wqe_local_inval_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3325 */;
	struct mlx4_ib_mr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3312 */;
	const struct ib_reg_wr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3310 */;
	struct mlx4_wqe_fmr_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3309 */;
	struct mlx4_ib_wq *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3280 */;
	struct mlx4_wqe_inline_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3276 */;
	struct in6_addr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3178 */;
	struct in6_addr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3075 */;
	struct mlx4_wqe_mlx_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3033 */;
	struct mlx4_port_gid_table *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3013 */;
	struct mlx4_ib_iboe *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3012 */;
	enum ib_gid_type *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3010 */;
	union ib_gid *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 3009 */;
	union sl2vl_tbl_to_u64 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2994 */;
	struct mlx4_wqe_ctrl_seg cocci_id/* drivers/infiniband/hw/mlx4/qp.c 291 */;
	struct mlx4_ib_tunnel_header cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2906 */;
	struct ib_qp_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2717 */;
	enum{MLX4_IB_MODIFY_QP_RSS_SUP_ATTR_MSK=(IB_QP_STATE | IB_QP_PORT),} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2712 */;
	struct mlx4_wqe_ctrl_seg *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2538 */;
	u8 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2317 */[ETH_ALEN];
	u16 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2316 */;
	struct ib_event cocci_id/* drivers/infiniband/hw/mlx4/qp.c 231 */;
	u8 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2300 */;
	enum ib_gid_type cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2298 */;
	enum mlx4_event cocci_id/* drivers/infiniband/hw/mlx4/qp.c 229 */;
	struct mlx4_qp *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 229 */;
	u32 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2246 */;
	struct ib_qp *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2160 */;
	struct ib_wq *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2154 */;
	enum mlx4_qp_optpar cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2147 */;
	struct mlx4_qp_context *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2146 */;
	struct mlx4_ib_ucontext cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2145 */;
	struct mlx4_ib_ucontext *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2144 */;
	struct mlx4_ib_cq *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2143 */;
	struct mlx4_ib_pd *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2142 */;
	struct mlx4_ib_qp *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2141 */;
	struct mlx4_ib_dev *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2140 */;
	enum ib_qp_type cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2139 */;
	struct ib_rwq_ind_table *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2138 */;
	const struct ib_gid_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2137 */;
	struct ib_srq *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2136 */;
	struct ib_udata *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2134 */;
	enum ib_qp_state cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2132 */;
	const struct ib_qp_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2131 */;
	enum mlx4_ib_source_type cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2130 */;
	void *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2130 */;
	int cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2130 */;
	struct mlx4_qp_context cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2114 */;
	struct mlx4_rss_context *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2112 */;
	enum{MLX4_QPC_ROCE_MODE_1=0, MLX4_QPC_ROCE_MODE_2=2, MLX4_QPC_ROCE_MODE_UNDEFINED=0xff,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 2006 */;
	struct counter_index *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1974 */;
	enum ib_qp_attr_mask cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1926 */;
	u8 *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1916 */;
	const struct ib_global_route *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1815 */;
	struct mlx4_roce_smac_vlan_info *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1797 */;
	u64 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1796 */;
	struct mlx4_qp_path *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1796 */;
	const struct rdma_ah_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1795 */;
	struct ib_qp_init_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1532 */;
	struct ib_pd *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1531 */;
	struct mlx4_ib_cq **cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1365 */;
	struct mlx4_ib_gid_entry *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1348 */;
	enum mlx4_ib_source_type{MLX4_IB_QP_SRC=0, MLX4_IB_RWQ_SRC=1,} cocci_id/* drivers/infiniband/hw/mlx4/qp.c 121 */;
	struct mlx4_ib_create_qp cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1077 */;
	struct mlx4_ib_qp cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1055 */;
	struct mlx4_ib_sqp cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1050 */;
	const __be32 cocci_id/* drivers/infiniband/hw/mlx4/qp.c 105 */[];
	struct mlx4_ib_qp_tunnel_init_attr cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1026 */;
	struct mlx4_ib_qp_tunnel_init_attr *cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1024 */;
	enum mlx4_ib_qp_type cocci_id/* drivers/infiniband/hw/mlx4/qp.c 1001 */;
}
