cocci_test_suite() {
	u16 cocci_id/* drivers/infiniband/hw/mlx4/cq.c 93 */;
	u8 cocci_id/* drivers/infiniband/hw/mlx4/cq.c 924 */;
	struct mlx4_cqe *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 923 */;
	int cocci_id/* drivers/infiniband/hw/mlx4/cq.c 922 */;
	u32 cocci_id/* drivers/infiniband/hw/mlx4/cq.c 919 */;
	struct mlx4_ib_srq *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 919 */;
	struct mlx4_ib_cq *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 919 */;
	void cocci_id/* drivers/infiniband/hw/mlx4/cq.c 919 */;
	enum ib_cq_notify_flags cocci_id/* drivers/infiniband/hw/mlx4/cq.c 908 */;
	struct ib_cq *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 908 */;
	struct mlx4_ib_qp *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 884 */;
	struct mlx4_ib_cq_buf *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 69 */;
	unsigned cocci_id/* drivers/infiniband/hw/mlx4/cq.c 675 */;
	struct mlx4_srq *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 669 */;
	struct mlx4_ib_wq *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 667 */;
	struct mlx4_qp *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 666 */;
	struct mlx4_ib_qp **cocci_id/* drivers/infiniband/hw/mlx4/cq.c 662 */;
	int *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 637 */;
	char *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 603 */;
	struct mlx4_ib_proxy_sqp_hdr cocci_id/* drivers/infiniband/hw/mlx4/cq.c 592 */;
	struct mlx4_ib_proxy_sqp_hdr *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 588 */;
	__be16 cocci_id/* drivers/infiniband/hw/mlx4/cq.c 571 */;
	struct ib_wc *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 511 */;
	struct mlx4_err_cqe *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 510 */;
	struct ib_event cocci_id/* drivers/infiniband/hw/mlx4/cq.c 51 */;
	__be32 *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 502 */;
	void *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 500 */;
	enum mlx4_event cocci_id/* drivers/infiniband/hw/mlx4/cq.c 49 */;
	struct mlx4_ib_cq_buf cocci_id/* drivers/infiniband/hw/mlx4/cq.c 439 */;
	struct mlx4_cq *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 43 */;
	struct mlx4_mtt cocci_id/* drivers/infiniband/hw/mlx4/cq.c 384 */;
	struct mlx4_ib_resize_cq cocci_id/* drivers/infiniband/hw/mlx4/cq.c 318 */;
	struct ib_udata *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 316 */;
	struct mlx4_ib_dev *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 291 */;
	unsigned long cocci_id/* drivers/infiniband/hw/mlx4/cq.c 213 */;
	struct mlx4_ib_create_cq cocci_id/* drivers/infiniband/hw/mlx4/cq.c 206 */;
	struct mlx4_ib_ucontext cocci_id/* drivers/infiniband/hw/mlx4/cq.c 187 */;
	struct mlx4_ib_ucontext *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 186 */;
	struct mlx4_uar *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 183 */;
	struct ib_device *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 178 */;
	const struct ib_cq_init_attr *cocci_id/* drivers/infiniband/hw/mlx4/cq.c 175 */;
	u64 cocci_id/* drivers/infiniband/hw/mlx4/cq.c 140 */;
	struct ib_umem **cocci_id/* drivers/infiniband/hw/mlx4/cq.c 140 */;
}
