cocci_test_suite() {
	const struct attribute_group cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 96 */;
	u64 cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 916 */;
	struct attribute *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 89 */[];
	struct device_attribute *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 83 */;
	char *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 83 */;
	struct device *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 82 */;
	ssize_t cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 82 */;
	unsigned long long cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 818 */;
	dma_addr_t cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 787 */;
	const struct pci_device_id *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 780 */;
	struct pvrdma_netdevice_work *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 765 */;
	struct net_device *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 764 */;
	struct notifier_block *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 761 */;
	struct pvrdma_netdevice_work cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 744 */;
	struct work_struct *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 739 */;
	struct pvrdma_cmd_destroy_bind *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 655 */;
	int cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 65 */(const struct ib_gid_attr *attr,
									    void **context);
	const struct ib_gid_attr *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 642 */;
	void **cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 642 */;
	int cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 642 */;
	struct workqueue_struct *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 63 */;
	struct pvrdma_cmd_create_bind *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 617 */;
	union pvrdma_cmd_req cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 616 */;
	u8 cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 612 */;
	const union ib_gid *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 611 */;
	struct pci_dev *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 555 */;
	struct pvrdma_cqne cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 495 */;
	unsigned int cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 490 */;
	struct pvrdma_dev *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 489 */;
	struct pvrdma_cqne *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 489 */;
	struct pvrdma_ring *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 425 */;
	struct pvrdma_eqe cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 419 */;
	struct pvrdma_eqe *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 414 */;
	enum ib_event_type cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 393 */;
	struct ib_srq *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 378 */;
	struct ib_event cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 350 */;
	struct ib_cq *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 349 */;
	unsigned long cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 340 */;
	struct pvrdma_cq *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 339 */;
	u32 cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 337 */;
	struct ib_qp *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 323 */;
	struct pvrdma_qp *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 313 */;
	irqreturn_t cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 291 */;
	void *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 291 */;
	struct pvrdma_srq *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 262 */;
	const struct ib_device_ops cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 146 */;
	struct ib_port_attr cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 128 */;
	struct ib_port_immutable *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 125 */;
	void __exit cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 1174 */;
	void cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 1174 */;
	int __init cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 1159 */;
	struct pci_driver cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 1152 */;
	const struct pci_device_id cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 1145 */[];
	struct pvrdma_dev cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 103 */;
	union ib_gid cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 1011 */;
	struct ib_device *cocci_id/* drivers/infiniband/hw/vmw_pvrdma/pvrdma_main.c 100 */;
}
