cocci_test_suite() {
	u32 cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 85 */;
	struct creq_query_func_resp_sb *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 83 */;
	struct bnxt_qplib_rcfw_sbuf *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 82 */;
	struct creq_query_func_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 81 */;
	struct cmdq_query_func cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 80 */;
	struct creq_query_roce_stats_resp_sb *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 794 */;
	struct creq_query_roce_stats_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 792 */;
	struct cmdq_query_roce_stats cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 791 */;
	struct bnxt_qplib_roce_stats *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 789 */;
	struct bnxt_qplib_dev_attr *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 78 */;
	struct creq_map_tc_to_cos_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 777 */;
	struct cmdq_map_tc_to_cos cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 776 */;
	struct bnxt_qplib_frpl *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 742 */;
	dma_addr_t **cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 663 */;
	struct creq_register_mr_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 660 */;
	struct cmdq_register_mr cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 659 */;
	u64 *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 656 */;
	struct creq_deregister_mr_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 633 */;
	struct cmdq_deregister_mr cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 632 */;
	struct creq_query_version_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 61 */;
	struct cmdq_query_version cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 60 */;
	unsigned long cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 599 */;
	struct creq_allocate_mrw_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 597 */;
	struct cmdq_allocate_mrw cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 596 */;
	struct bnxt_qplib_mrw *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 593 */;
	char *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 58 */;
	struct creq_deallocate_key_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 561 */;
	struct cmdq_deallocate_key cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 560 */;
	struct creq_destroy_ah_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 544 */;
	struct cmdq_destroy_ah cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 543 */;
	void cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 539 */;
	const struct bnxt_qplib_gid cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 52 */;
	struct bnxt_qplib_gid cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 509 */;
	u16 cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 504 */[3];
	u32 cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 503 */[4];
	struct creq_create_ah_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 501 */;
	struct cmdq_create_ah cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 500 */;
	struct bnxt_qplib_ah *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 496 */;
	bool cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 461 */;
	u16 *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 460 */;
	struct bnxt_qplib_pkey_tbl *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 460 */;
	struct bnxt_qplib_res *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 459 */;
	int cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 459 */;
	struct cmdq_modify_gid cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 380 */;
	struct creq_modify_gid_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 379 */;
	void *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 349 */;
	struct creq_add_gid_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 320 */;
	struct cmdq_add_gid cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 319 */;
	struct bnxt_qplib_rcfw *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 287 */;
	struct bnxt_qplib_res cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 285 */;
	u32 *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 282 */;
	u16 cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 281 */;
	u8 *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 281 */;
	struct bnxt_qplib_gid *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 281 */;
	struct bnxt_qplib_sgid_tbl *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 280 */;
	struct creq_delete_gid_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 250 */;
	struct cmdq_delete_gid cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 249 */;
	struct creq_set_func_resources_resp cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 179 */;
	struct cmdq_set_func_resources cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 178 */;
	struct bnxt_qplib_ctx *cocci_id/* drivers/infiniband/hw/bnxt_re/qplib_sp.c 176 */;
}
