cocci_test_suite() {
	dma_addr_t *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 995 */;
	struct bnxt_re_dev *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 992 */;
	void cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 925 */;
	u32 cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 917 */;
	u16 cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 917 */;
	struct bnxt_re_cq cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 899 */;
	struct bnxt_re_cq *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 899 */;
	struct bnxt_qplib_cq *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 897 */;
	struct bnxt_qplib_nq *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 896 */;
	struct bnxt_re_srq cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 869 */;
	struct bnxt_re_srq *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 869 */;
	struct bnxt_qplib_srq *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 867 */;
	struct creq_base *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 854 */;
	u8 cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 851 */;
	struct creq_func_event *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 850 */;
	struct creq_qp_event *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 849 */;
	void *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 847 */;
	struct bnxt_qplib_rcfw *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 846 */;
	int cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 846 */;
	struct bnxt_re_qp cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 839 */;
	struct bnxt_qplib_qp *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 838 */;
	void cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 81 */(struct bnxt_re_dev *rdev);
	unsigned int cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 806 */;
	struct workqueue_struct *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 80 */;
	struct list_head cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 77 */;
	struct bnxt_en_dev *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 738 */;
	struct net_device *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 737 */;
	char cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 69 */[];
	const struct ib_device_ops cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 616 */;
	const struct attribute_group cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 607 */;
	struct attribute *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 601 */[];
	struct device_attribute *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 592 */;
	char *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 592 */;
	struct device *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 591 */;
	ssize_t cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 591 */;
	struct pci_dev *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 551 */;
	struct bnxt *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 549 */;
	struct ethtool_drvinfo cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 512 */;
	struct ctx_hw_stats_ext cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 497 */;
	struct hwrm_stat_ctx_alloc_input cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 482 */;
	struct hwrm_stat_ctx_alloc_output cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 481 */;
	u32 *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 479 */;
	dma_addr_t cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 478 */;
	struct hwrm_stat_ctx_free_input cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 456 */;
	struct bnxt_fw_msg cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 422 */;
	struct hwrm_ring_alloc_output cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 421 */;
	struct hwrm_ring_alloc_input cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 420 */;
	u16 *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 417 */;
	struct hwrm_ring_free_output cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 394 */;
	struct hwrm_ring_free_input cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 393 */;
	struct bnxt_fw_msg *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 378 */;
	struct input *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 370 */;
	struct bnxt_ulp_ops cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 279 */;
	struct bnxt_msix_entry *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 243 */;
	struct bnxt_qplib_vf_res cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 185 */;
	void __exit cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1727 */;
	int __init cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1701 */;
	struct notifier_block cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1697 */;
	struct bnxt_re_work *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1633 */;
	unsigned long cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1630 */;
	struct notifier_block *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1629 */;
	struct bnxt_re_work cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1567 */;
	struct work_struct *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1561 */;
	struct bnxt_re_dev **cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1530 */;
	struct bnxt_qplib_vf_res *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 147 */;
	bool cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1361 */;
	struct bnxt_re_dev cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1349 */;
	u64 cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1294 */;
	struct hwrm_ver_get_input cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1275 */;
	struct hwrm_ver_get_output cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1274 */;
	struct bnxt_qplib_ctx *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 125 */;
	struct bnxt_qplib_dev_attr *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 124 */;
	u8 *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1214 */;
	struct dcb_app cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1196 */;
	struct bnxt_qplib_gid cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1159 */;
	struct bnxt_qplib_sgid_tbl *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1158 */;
	struct bnxt_re_qp *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1135 */;
	struct ib_qp_attr cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1134 */;
	struct hwrm_queue_pri2cos_qcfg_output cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1087 */;
	struct hwrm_queue_pri2cos_qcfg_input cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1085 */;
	u64 *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1083 */;
	struct ib_event cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1065 */;
	enum ib_event_type cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1063 */;
	struct ib_qp *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1062 */;
	struct ib_device *cocci_id/* drivers/infiniband/hw/bnxt_re/main.c 1062 */;
}
