cocci_test_suite() {
	enum ib_wc_opcode cocci_id/* drivers/infiniband/hw/mlx5/cq.c 98 */;
	struct mlx5_ib_wq *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 98 */;
	unsigned int cocci_id/* drivers/infiniband/hw/mlx5/cq.c 900 */;
	u32 *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 897 */;
	u32 cocci_id/* drivers/infiniband/hw/mlx5/cq.c 894 */[MLX5_ST_SZ_DW(create_cq_out)];
	struct ib_device *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 889 */;
	const struct ib_cq_init_attr *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 886 */;
	struct work_struct *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 878 */;
	__be64 *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 825 */;
	u32 **cocci_id/* drivers/infiniband/hw/mlx5/cq.c 823 */;
	int *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 823 */;
	struct mlx5_ib_ucontext cocci_id/* drivers/infiniband/hw/mlx5/cq.c 693 */;
	struct mlx5_ib_ucontext *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 692 */;
	size_t cocci_id/* drivers/infiniband/hw/mlx5/cq.c 685 */;
	struct mlx5_ib_create_cq cocci_id/* drivers/infiniband/hw/mlx5/cq.c 684 */;
	struct ib_udata *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 680 */;
	enum{MLX5_CQE_RES_FORMAT_HASH=0, MLX5_CQE_RES_FORMAT_CSUM=1, MLX5_CQE_RES_FORMAT_CSUM_STRIDX=3,} cocci_id/* drivers/infiniband/hw/mlx5/cq.c 658 */;
	struct mlx5_frag_buf *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 638 */;
	struct mlx5_ib_cq_buf *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 634 */;
	struct mlx5_ib_dev *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 633 */;
	unsigned long cocci_id/* drivers/infiniband/hw/mlx5/cq.c 614 */;
	void __iomem *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 613 */;
	struct mlx5_core_dev *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 611 */;
	enum ib_cq_notify_flags cocci_id/* drivers/infiniband/hw/mlx5/cq.c 609 */;
	struct ib_cq *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 609 */;
	struct mlx5_core_sig_ctx *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 522 */;
	struct ib_event cocci_id/* drivers/infiniband/hw/mlx5/cq.c 52 */;
	struct mlx5_ib_cq cocci_id/* drivers/infiniband/hw/mlx5/cq.c 49 */;
	enum mlx5_event cocci_id/* drivers/infiniband/hw/mlx5/cq.c 47 */;
	uint32_t cocci_id/* drivers/infiniband/hw/mlx5/cq.c 427 */;
	uint8_t cocci_id/* drivers/infiniband/hw/mlx5/cq.c 426 */;
	struct mlx5_core_qp *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 424 */;
	struct mlx5_ib_qp **cocci_id/* drivers/infiniband/hw/mlx5/cq.c 418 */;
	struct mlx5_eqe *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 40 */;
	struct mlx5_core_cq *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 40 */;
	u16 cocci_id/* drivers/infiniband/hw/mlx5/cq.c 341 */;
	struct ib_sig_err *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 339 */;
	struct mlx5_sig_err_cqe *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 338 */;
	struct mlx5_err_cqe *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 268 */;
	struct mlx5_core_srq *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 178 */;
	bool cocci_id/* drivers/infiniband/hw/mlx5/cq.c 174 */;
	enum rdma_link_layer cocci_id/* drivers/infiniband/hw/mlx5/cq.c 168 */;
	struct mlx5_ib_qp *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 166 */;
	enum{MLX5_GRH_IN_BUFFER=1, MLX5_GRH_IN_CQE=2,} cocci_id/* drivers/infiniband/hw/mlx5/cq.c 160 */;
	struct mlx5_ib_wc *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1354 */;
	struct mlx5_ib_cq_buf cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1302 */;
	struct ib_wc *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 116 */;
	struct ib_umem *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1096 */;
	struct mlx5_ib_resize_cq cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1095 */;
	u8 cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1016 */;
	int cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1015 */;
	void *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1013 */;
	struct mlx5_cqe64 *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1012 */;
	u32 cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1010 */;
	struct mlx5_ib_srq *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1010 */;
	struct mlx5_ib_cq *cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1010 */;
	void cocci_id/* drivers/infiniband/hw/mlx5/cq.c 1010 */;
}
