cocci_test_suite() {
	struct usnic_ib_vf *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 83 */;
	void __exit cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 710 */;
	const char cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 68 */[];
	unsigned int cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 66 */;
	int __init cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 659 */;
	struct pci_driver cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 650 */;
	enum usnic_vnic_res_type cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 555 */;
	const struct pci_device_id *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 550 */;
	const struct pci_device_id cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 544 */[];
	struct usnic_vnic *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 503 */;
	bool cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 482 */;
	struct kref *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 478 */;
	const struct in_ifaddr *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 441 */;
	int cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 374 */;
	struct net_device *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 373 */;
	struct in_device *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 372 */;
	union ib_gid cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 371 */;
	struct pci_dev *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 368 */;
	void *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 368 */;
	const struct ib_device_ops cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 337 */;
	struct ethtool_drvinfo cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 328 */;
	struct usnic_ib_dev cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 327 */;
	struct usnic_ib_dev *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 326 */;
	struct ib_device *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 324 */;
	char *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 324 */;
	void cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 324 */;
	struct ib_port_attr cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 309 */;
	struct ib_port_immutable *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 307 */;
	u8 cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 306 */;
	struct notifier_block cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 301 */;
	struct notifier_block *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 284 */;
	struct ib_event cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 249 */;
	struct in_ifaddr *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 248 */;
	unsigned long cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 246 */;
	enum ib_qp_state cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 108 */;
	struct usnic_ib_qp_grp *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 107 */;
	struct usnic_ib_ucontext *cocci_id/* drivers/infiniband/hw/usnic/usnic_ib_main.c 106 */;
}
