cocci_test_suite() {
	struct hfi1_vnic_rx_queue *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 839 */;
	struct opa_vnic_rdma_netdev cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 816 */;
	struct rdma_netdev *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 804 */;
	void (*cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 799 */)(struct net_device *);
	unsigned char cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 798 */;
	const char *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 797 */;
	enum rdma_netdev_t cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 796 */;
	struct ib_device *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 794 */;
	const struct net_device_ops cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 777 */;
	bool cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 755 */;
	unsigned int cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 67 */;
	struct hfi1_vnic_vport_info *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 654 */;
	struct net_device *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 652 */;
	unsigned long cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 544 */;
	struct hfi1_packet *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 524 */;
	struct hfi1_vnic_rx_queue cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 510 */;
	struct napi_struct *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 507 */;
	int *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 476 */;
	unsigned char *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 459 */;
	struct sdma_engine *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 430 */;
	u16 cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 424 */;
	struct opa_vnic_skb_mdata *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 366 */;
	u8 cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 364 */;
	netdev_tx_t cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 360 */;
	struct sk_buff *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 360 */;
	u64 cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 336 */;
	u32 cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 336 */;
	struct opa_vnic_stats *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 330 */;
	struct rtnl_link_stats64 *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 328 */;
	struct opa_vnic_grp_stats *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 303 */;
	struct ethhdr *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 301 */;
	u64 *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 174 */;
	void cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 132 */;
	struct hfi1_ctxtdata *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 104 */;
	struct hfi1_ctxtdata **cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 102 */;
	struct hfi1_devdata *cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 101 */;
	int cocci_id/* drivers/infiniband/hw/hfi1/vnic_main.c 101 */;
}
