cocci_test_suite() {
	struct acpi_gpio_event *cocci_id/* drivers/gpio/gpiolib-acpi.c 971 */;
	struct acpi_gpio_connection *cocci_id/* drivers/gpio/gpiolib-acpi.c 949 */;
	struct acpi_resource_gpio *cocci_id/* drivers/gpio/gpiolib-acpi.c 921 */;
	struct acpi_gpio_chip *cocci_id/* drivers/gpio/gpiolib-acpi.c 919 */;
	u64 *cocci_id/* drivers/gpio/gpiolib-acpi.c 916 */;
	u32 cocci_id/* drivers/gpio/gpiolib-acpi.c 915 */;
	acpi_physical_address cocci_id/* drivers/gpio/gpiolib-acpi.c 915 */;
	char cocci_id/* drivers/gpio/gpiolib-acpi.c 883 */[32];
	unsigned long cocci_id/* drivers/gpio/gpiolib-acpi.c 882 */;
	struct gpio_desc *cocci_id/* drivers/gpio/gpiolib-acpi.c 873 */;
	struct acpi_gpio_info cocci_id/* drivers/gpio/gpiolib-acpi.c 872 */;
	unsigned int cocci_id/* drivers/gpio/gpiolib-acpi.c 868 */;
	unsigned long *cocci_id/* drivers/gpio/gpiolib-acpi.c 761 */;
	struct device *cocci_id/* drivers/gpio/gpiolib-acpi.c 757 */;
	const char *cocci_id/* drivers/gpio/gpiolib-acpi.c 748 */;
	bool cocci_id/* drivers/gpio/gpiolib-acpi.c 747 */;
	struct acpi_device *cocci_id/* drivers/gpio/gpiolib-acpi.c 747 */;
	struct acpi_gpio_lookup cocci_id/* drivers/gpio/gpiolib-acpi.c 718 */;
	struct acpi_gpio_info *cocci_id/* drivers/gpio/gpiolib-acpi.c 716 */;
	struct fwnode_reference_args cocci_id/* drivers/gpio/gpiolib-acpi.c 656 */;
	struct acpi_gpio_lookup *cocci_id/* drivers/gpio/gpiolib-acpi.c 654 */;
	struct fwnode_handle *cocci_id/* drivers/gpio/gpiolib-acpi.c 652 */;
	struct acpi_gpio_chip {
		struct acpi_connection_info conn_info;
		struct list_head conns;
		struct mutex conn_lock;
		struct gpio_chip *chip;
		struct list_head events;
		struct list_head deferred_req_irqs_list_entry;
	} cocci_id/* drivers/gpio/gpiolib-acpi.c 60 */;
	struct acpi_gpio_lookup {
		struct acpi_gpio_info info;
		int index;
		int pin_index;
		bool active_low;
		struct gpio_desc *desc;
		int n;
	} cocci_id/* drivers/gpio/gpiolib-acpi.c 571 */;
	struct acpi_gpio_connection {
		struct list_head node;
		unsigned int pin;
		struct gpio_desc *desc;
	} cocci_id/* drivers/gpio/gpiolib-acpi.c 54 */;
	const enum gpiod_flags cocci_id/* drivers/gpio/gpiolib-acpi.c 503 */;
	enum gpiod_flags cocci_id/* drivers/gpio/gpiolib-acpi.c 501 */;
	enum gpiod_flags *cocci_id/* drivers/gpio/gpiolib-acpi.c 501 */;
	int cocci_id/* drivers/gpio/gpiolib-acpi.c 500 */;
	const struct acpi_resource_gpio *cocci_id/* drivers/gpio/gpiolib-acpi.c 468 */;
	const struct acpi_gpio_params *cocci_id/* drivers/gpio/gpiolib-acpi.c 452 */;
	struct fwnode_reference_args *cocci_id/* drivers/gpio/gpiolib-acpi.c 442 */;
	struct acpi_gpio_event {
		struct list_head node;
		acpi_handle handle;
		irq_handler_t handler;
		unsigned int pin;
		unsigned int irq;
		unsigned long irqflags;
		bool irq_is_wake;
		bool irq_requested;
		struct gpio_desc *desc;
	} cocci_id/* drivers/gpio/gpiolib-acpi.c 42 */;
	void cocci_id/* drivers/gpio/gpiolib-acpi.c 402 */;
	const struct acpi_gpio_mapping *cocci_id/* drivers/gpio/gpiolib-acpi.c 392 */;
	void **cocci_id/* drivers/gpio/gpiolib-acpi.c 366 */;
	char cocci_id/* drivers/gpio/gpiolib-acpi.c 217 */[5];
	irq_handler_t cocci_id/* drivers/gpio/gpiolib-acpi.c 206 */;
	struct acpi_resource_gpio **cocci_id/* drivers/gpio/gpiolib-acpi.c 144 */;
	const struct dmi_system_id cocci_id/* drivers/gpio/gpiolib-acpi.c 1312 */[];
	struct list_head cocci_id/* drivers/gpio/gpiolib-acpi.c 1277 */;
	const union acpi_object *cocci_id/* drivers/gpio/gpiolib-acpi.c 1241 */;
	unsigned int *cocci_id/* drivers/gpio/gpiolib-acpi.c 1221 */;
	struct acpi_resource *cocci_id/* drivers/gpio/gpiolib-acpi.c 1219 */;
	void *cocci_id/* drivers/gpio/gpiolib-acpi.c 1219 */;
	irqreturn_t cocci_id/* drivers/gpio/gpiolib-acpi.c 120 */;
	acpi_status cocci_id/* drivers/gpio/gpiolib-acpi.c 107 */;
	u32 cocci_id/* drivers/gpio/gpiolib-acpi.c 1069 */[2];
	const char **cocci_id/* drivers/gpio/gpiolib-acpi.c 1063 */;
	acpi_handle cocci_id/* drivers/gpio/gpiolib-acpi.c 106 */;
	struct gpio_chip *cocci_id/* drivers/gpio/gpiolib-acpi.c 105 */;
	char *cocci_id/* drivers/gpio/gpiolib-acpi.c 103 */;
	u64 cocci_id/* drivers/gpio/gpiolib-acpi.c 1014 */;
}
