cocci_test_suite() {
	unsigned char *cocci_id/* drivers/ata/libata-sff.c 783 */;
	struct page *cocci_id/* drivers/ata/libata-sff.c 782 */;
	struct scatterlist *cocci_id/* drivers/ata/libata-sff.c 781 */;
	struct ata_eh_info *cocci_id/* drivers/ata/libata-sff.c 780 */;
	struct ata_device *cocci_id/* drivers/ata/libata-sff.c 779 */;
	unsigned char cocci_id/* drivers/ata/libata-sff.c 617 */[4];
	unsigned char cocci_id/* drivers/ata/libata-sff.c 557 */[2];
	const struct ata_taskfile *cocci_id/* drivers/ata/libata-sff.c 499 */;
	struct ata_taskfile *cocci_id/* drivers/ata/libata-sff.c 460 */;
	int __init cocci_id/* drivers/ata/libata-sff.c 3266 */;
	struct scsi_host_template *cocci_id/* drivers/ata/libata-sff.c 3239 */;
	const struct ata_port_info *const*cocci_id/* drivers/ata/libata-sff.c 3238 */;
	struct ata_host **cocci_id/* drivers/ata/libata-sff.c 3207 */;
	unsigned long long cocci_id/* drivers/ata/libata-sff.c 3185 */;
	struct device *cocci_id/* drivers/ata/libata-sff.c 3144 */;
	const char *cocci_id/* drivers/ata/libata-sff.c 3121 */;
	struct pci_dev *cocci_id/* drivers/ata/libata-sff.c 3104 */;
	void __iomem *cocci_id/* drivers/ata/libata-sff.c 2932 */;
	void cocci_id/* drivers/ata/libata-sff.c 2852 */;
	struct workqueue_struct *cocci_id/* drivers/ata/libata-sff.c 28 */;
	struct ata_link *cocci_id/* drivers/ata/libata-sff.c 2730 */;
	enum ata_completion_errors cocci_id/* drivers/ata/libata-sff.c 2702 */;
	u32 cocci_id/* drivers/ata/libata-sff.c 2584 */;
	struct ata_bmdma_prd *cocci_id/* drivers/ata/libata-sff.c 2578 */;
	const struct ata_port_operations cocci_id/* drivers/ata/libata-sff.c 2556 */;
	const struct ata_port_info *cocci_id/* drivers/ata/libata-sff.c 2451 */;
	irq_handler_t cocci_id/* drivers/ata/libata-sff.c 2349 */;
	void __iomem *const*cocci_id/* drivers/ata/libata-sff.c 2237 */;
	ata_reset_fn_t cocci_id/* drivers/ata/libata-sff.c 2132 */;
	unsigned int *cocci_id/* drivers/ata/libata-sff.c 2060 */;
	const unsigned long *cocci_id/* drivers/ata/libata-sff.c 2034 */;
	struct ata_ioports *cocci_id/* drivers/ata/libata-sff.c 1942 */;
	struct ata_taskfile cocci_id/* drivers/ata/libata-sff.c 1816 */;
	u8 *cocci_id/* drivers/ata/libata-sff.c 1813 */;
	struct ata_eh_context *cocci_id/* drivers/ata/libata-sff.c 1723 */;
	struct ata_queued_cmd *cocci_id/* drivers/ata/libata-sff.c 1544 */;
	struct ata_port *cocci_id/* drivers/ata/libata-sff.c 1543 */;
	unsigned long cocci_id/* drivers/ata/libata-sff.c 1535 */;
	unsigned int cocci_id/* drivers/ata/libata-sff.c 1533 */;
	bool cocci_id/* drivers/ata/libata-sff.c 1532 */;
	struct ata_host *cocci_id/* drivers/ata/libata-sff.c 1531 */;
	unsigned int (*cocci_id/* drivers/ata/libata-sff.c 1529 */)(struct ata_port *,
								    struct ata_queued_cmd *);
	irqreturn_t cocci_id/* drivers/ata/libata-sff.c 1528 */;
	void *cocci_id/* drivers/ata/libata-sff.c 1528 */;
	int cocci_id/* drivers/ata/libata-sff.c 1528 */;
	u8 cocci_id/* drivers/ata/libata-sff.c 1464 */;
	struct ata_port cocci_id/* drivers/ata/libata-sff.c 1275 */;
	struct work_struct *cocci_id/* drivers/ata/libata-sff.c 1272 */;
	struct delayed_work *cocci_id/* drivers/ata/libata-sff.c 1229 */;
}
