cocci_test_suite() {
	struct module *cocci_id/* drivers/spi/spi-mem.c 777 */;
	struct spi_mem_driver *cocci_id/* drivers/spi/spi-mem.c 776 */;
	struct spi_device *cocci_id/* drivers/spi/spi-mem.c 721 */;
	struct spi_mem_driver cocci_id/* drivers/spi/spi-mem.c 718 */;
	struct device_driver *cocci_id/* drivers/spi/spi-mem.c 716 */;
	const void *cocci_id/* drivers/spi/spi-mem.c 687 */;
	u64 cocci_id/* drivers/spi/spi-mem.c 641 */;
	ssize_t cocci_id/* drivers/spi/spi-mem.c 640 */;
	void cocci_id/* drivers/spi/spi-mem.c 616 */;
	void *cocci_id/* drivers/spi/spi-mem.c 597 */;
	int cocci_id/* drivers/spi/spi-mem.c 597 */;
	struct spi_mem_dirmap_desc **cocci_id/* drivers/spi/spi-mem.c 578 */;
	const struct spi_mem_dirmap_info *cocci_id/* drivers/spi/spi-mem.c 576 */;
	struct spi_mem *cocci_id/* drivers/spi/spi-mem.c 575 */;
	struct device *cocci_id/* drivers/spi/spi-mem.c 575 */;
	struct spi_mem_dirmap_desc *cocci_id/* drivers/spi/spi-mem.c 574 */;
	struct spi_mem_op cocci_id/* drivers/spi/spi-mem.c 445 */;
	size_t cocci_id/* drivers/spi/spi-mem.c 419 */;
	struct spi_mem_op *cocci_id/* drivers/spi/spi-mem.c 416 */;
	const char *cocci_id/* drivers/spi/spi-mem.c 395 */;
	struct sg_table *cocci_id/* drivers/spi/spi-mem.c 36 */;
	const struct spi_mem_op *cocci_id/* drivers/spi/spi-mem.c 35 */;
	struct spi_controller *cocci_id/* drivers/spi/spi-mem.c 34 */;
	u8 *cocci_id/* drivers/spi/spi-mem.c 279 */;
	struct spi_message cocci_id/* drivers/spi/spi-mem.c 278 */;
	struct spi_transfer cocci_id/* drivers/spi/spi-mem.c 277 */[4];
	unsigned int cocci_id/* drivers/spi/spi-mem.c 275 */;
	u32 cocci_id/* drivers/spi/spi-mem.c 104 */;
	u8 cocci_id/* drivers/spi/spi-mem.c 102 */;
	bool cocci_id/* drivers/spi/spi-mem.c 102 */;
}
