cocci_test_suite() {
	struct spi_message *cocci_id/* drivers/spi/spidev.c 91 */;
	void __exit cocci_id/* drivers/spi/spidev.c 846 */;
	void cocci_id/* drivers/spi/spidev.c 846 */;
	unsigned cocci_id/* drivers/spi/spidev.c 84 */;
	int __init cocci_id/* drivers/spi/spidev.c 818 */;
	struct spi_driver cocci_id/* drivers/spi/spidev.c 800 */;
	struct device *cocci_id/* drivers/spi/spidev.c 752 */;
	const struct acpi_device_id *cocci_id/* drivers/spi/spidev.c 699 */;
	const struct acpi_device_id cocci_id/* drivers/spi/spidev.c 683 */[];
	struct spidev_data {
		dev_t devt;
		spinlock_t spi_lock;
		struct spi_device *spi;
		struct list_head device_entry;
		struct mutex buf_lock;
		unsigned users;
		u8 *tx_buffer;
		u8 *rx_buffer;
		u32 speed_hz;
	} cocci_id/* drivers/spi/spidev.c 67 */;
	const struct of_device_id cocci_id/* drivers/spi/spidev.c 665 */[];
	struct class *cocci_id/* drivers/spi/spidev.c 662 */;
	const struct file_operations cocci_id/* drivers/spi/spidev.c 640 */;
	struct inode *cocci_id/* drivers/spi/spidev.c 550 */;
	uintptr_t cocci_id/* drivers/spi/spidev.c 522 */;
	struct spi_ioc_transfer *cocci_id/* drivers/spi/spidev.c 493 */;
	struct spi_device *cocci_id/* drivers/spi/spidev.c 491 */;
	struct spidev_data *cocci_id/* drivers/spi/spidev.c 490 */;
	int cocci_id/* drivers/spi/spidev.c 489 */;
	struct spi_ioc_transfer __user *cocci_id/* drivers/spi/spidev.c 488 */;
	unsigned long cocci_id/* drivers/spi/spidev.c 486 */;
	struct file *cocci_id/* drivers/spi/spidev.c 485 */;
	unsigned int cocci_id/* drivers/spi/spidev.c 485 */;
	long cocci_id/* drivers/spi/spidev.c 484 */;
	u8 cocci_id/* drivers/spi/spidev.c 435 */;
	u16 cocci_id/* drivers/spi/spidev.c 407 */;
	u32 __user *cocci_id/* drivers/spi/spidev.c 397 */;
	u8 __user *cocci_id/* drivers/spi/spidev.c 395 */;
	__u32 __user *cocci_id/* drivers/spi/spidev.c 378 */;
	__u8 __user *cocci_id/* drivers/spi/spidev.c 374 */;
	struct spi_ioc_transfer cocci_id/* drivers/spi/spidev.c 327 */;
	u32 cocci_id/* drivers/spi/spidev.c 318 */;
	unsigned *cocci_id/* drivers/spi/spidev.c 316 */;
	const u8 __user *cocci_id/* drivers/spi/spidev.c 257 */;
	u8 *cocci_id/* drivers/spi/spidev.c 206 */;
	struct spi_transfer *cocci_id/* drivers/spi/spidev.c 202 */;
	struct spi_message cocci_id/* drivers/spi/spidev.c 201 */;
	const char __user *cocci_id/* drivers/spi/spidev.c 174 */;
	loff_t *cocci_id/* drivers/spi/spidev.c 145 */;
	char __user *cocci_id/* drivers/spi/spidev.c 145 */;
	size_t cocci_id/* drivers/spi/spidev.c 145 */;
	ssize_t cocci_id/* drivers/spi/spidev.c 144 */;
	struct spi_transfer cocci_id/* drivers/spi/spidev.c 129 */;
}
