cocci_test_suite() {
	unsigned long cocci_id/* crypto/af_alg.c 897 */;
	long cocci_id/* crypto/af_alg.c 821 */;
	struct af_alg_control cocci_id/* crypto/af_alg.c 820 */;
	struct socket_wq *cocci_id/* crypto/af_alg.c 782 */;
	unsigned cocci_id/* crypto/af_alg.c 741 */;
	struct af_alg_rsgl *cocci_id/* crypto/af_alg.c 653 */;
	struct alg_type_list *cocci_id/* crypto/af_alg.c 60 */;
	struct page *cocci_id/* crypto/af_alg.c 597 */;
	const struct scatterlist *cocci_id/* crypto/af_alg.c 537 */;
	const struct af_alg_tsgl *cocci_id/* crypto/af_alg.c 529 */;
	const struct af_alg_ctx *cocci_id/* crypto/af_alg.c 528 */;
	const struct alg_sock *cocci_id/* crypto/af_alg.c 527 */;
	size_t cocci_id/* crypto/af_alg.c 525 */;
	struct af_alg_tsgl cocci_id/* crypto/af_alg.c 491 */;
	struct scatterlist *cocci_id/* crypto/af_alg.c 489 */;
	struct af_alg_tsgl *cocci_id/* crypto/af_alg.c 488 */;
	struct af_alg_ctx *cocci_id/* crypto/af_alg.c 487 */;
	u32 *cocci_id/* crypto/af_alg.c 461 */;
	u32 cocci_id/* crypto/af_alg.c 459 */;
	void *cocci_id/* crypto/af_alg.c 452 */;
	struct cmsghdr *cocci_id/* crypto/af_alg.c 440 */;
	struct msghdr *cocci_id/* crypto/af_alg.c 438 */;
	struct af_alg_control *cocci_id/* crypto/af_alg.c 438 */;
	struct af_alg_sgl *cocci_id/* crypto/af_alg.c 429 */;
	ssize_t cocci_id/* crypto/af_alg.c 394 */;
	struct iov_iter *cocci_id/* crypto/af_alg.c 391 */;
	const char *cocci_id/* crypto/af_alg.c 39 */;
	const struct net_proto_family cocci_id/* crypto/af_alg.c 385 */;
	struct net *cocci_id/* crypto/af_alg.c 359 */;
	const struct proto_ops cocci_id/* crypto/af_alg.c 330 */;
	struct alg_sock cocci_id/* crypto/af_alg.c 33 */;
	struct proto cocci_id/* crypto/af_alg.c 29 */;
	unsigned int cocci_id/* crypto/af_alg.c 274 */;
	const struct af_alg_type *cocci_id/* crypto/af_alg.c 272 */;
	struct alg_sock *cocci_id/* crypto/af_alg.c 271 */;
	atomic_long_t cocci_id/* crypto/af_alg.c 27 */;
	bool cocci_id/* crypto/af_alg.c 269 */;
	struct socket *cocci_id/* crypto/af_alg.c 269 */;
	struct sock *cocci_id/* crypto/af_alg.c 269 */;
	int cocci_id/* crypto/af_alg.c 269 */;
	struct alg_type_list {
		const struct af_alg_type *type;
		struct list_head list;
	} cocci_id/* crypto/af_alg.c 22 */;
	u8 *cocci_id/* crypto/af_alg.c 209 */;
	char __user *cocci_id/* crypto/af_alg.c 204 */;
	struct sockaddr_alg *cocci_id/* crypto/af_alg.c 153 */;
	const u32 cocci_id/* crypto/af_alg.c 150 */;
	struct sockaddr *cocci_id/* crypto/af_alg.c 148 */;
	void __exit cocci_id/* crypto/af_alg.c 1185 */;
	int __init cocci_id/* crypto/af_alg.c 1166 */;
	size_t *cocci_id/* crypto/af_alg.c 1114 */;
	struct af_alg_async_req *cocci_id/* crypto/af_alg.c 1081 */;
	poll_table *cocci_id/* crypto/af_alg.c 1054 */;
	__poll_t cocci_id/* crypto/af_alg.c 1053 */;
	struct file *cocci_id/* crypto/af_alg.c 1053 */;
	struct kiocb *cocci_id/* crypto/af_alg.c 1037 */;
	struct crypto_async_request *cocci_id/* crypto/af_alg.c 1033 */;
	void cocci_id/* crypto/af_alg.c 1033 */;
}
