cocci_test_suite() {
	const struct dev_pm_ops cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 910 */;
	struct device *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 903 */;
	int __maybe_unused cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 903 */;
	struct pinctrl_map cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 88 */;
	struct regmap *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 795 */;
	struct pinctrl_desc *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 792 */;
	struct regmap_config cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 790 */;
	struct platform_device *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 787 */;
	bool cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 696 */;
	struct group_desc cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 673 */;
	char *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 666 */;
	struct function_desc *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 648 */;
	struct imx_pin *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 64 */;
	struct imx_pin cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 621 */;
	const struct group_desc *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 61 */;
	const struct imx_pinctrl_soc_info *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 60 */;
	struct imx_pinctrl *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 59 */;
	const __be32 *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 575 */;
	struct pinctrl_map **cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 57 */;
	unsigned *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 57 */;
	struct device_node *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 56 */;
	int cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 55 */;
	struct imx_pin_reg *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 521 */;
	struct imx_pin_mmio *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 520 */;
	const __be32 **cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 516 */;
	unsigned int *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 515 */;
	const struct pinconf_ops cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 490 */;
	struct seq_file *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 49 */;
	const char *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 468 */;
	struct group_desc *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 466 */;
	unsigned long cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 439 */;
	const struct imx_pin_reg *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 438 */;
	enum pin_config_param cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 299 */;
	const struct imx_cfg_params_decode *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 298 */;
	unsigned int cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 295 */;
	u32 cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 293 */;
	struct pinmux_ops cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 285 */;
	u8 cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 209 */;
	const struct pinctrl_ops cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 153 */;
	struct pinctrl_map *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 148 */;
	unsigned cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 148 */;
	struct pinctrl_dev *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 147 */;
	void cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 147 */;
	unsigned long *cocci_id/* drivers/pinctrl/freescale/pinctrl-imx.c 130 */;
}
