cocci_test_suite() {
	const unsigned *cocci_id/* drivers/perf/arm_pmu.c 95 */[PERF_COUNT_HW_MAX];
	void cocci_id/* drivers/perf/arm_pmu.c 883 */;
	struct pmu_hw_events *cocci_id/* drivers/perf/arm_pmu.c 823 */;
	struct pmu cocci_id/* drivers/perf/arm_pmu.c 798 */;
	struct pmu_hw_events cocci_id/* drivers/perf/arm_pmu.c 792 */;
	int cocci_id/* drivers/perf/arm_pmu.c 784 */;
	gfp_t cocci_id/* drivers/perf/arm_pmu.c 781 */;
	struct arm_pmu *cocci_id/* drivers/perf/arm_pmu.c 781 */;
	struct notifier_block *cocci_id/* drivers/perf/arm_pmu.c 700 */;
	struct arm_pmu cocci_id/* drivers/perf/arm_pmu.c 617 */;
	struct hlist_node *cocci_id/* drivers/perf/arm_pmu.c 615 */;
	unsigned int cocci_id/* drivers/perf/arm_pmu.c 615 */;
	struct pmu_hw_events __percpu *cocci_id/* drivers/perf/arm_pmu.c 605 */;
	const irq_handler_t cocci_id/* drivers/perf/arm_pmu.c 565 */;
	const int cocci_id/* drivers/perf/arm_pmu.c 535 */;
	const char *cocci_id/* drivers/perf/arm_pmu.c 515 */;
	struct attribute_group cocci_id/* drivers/perf/arm_pmu.c 504 */;
	struct attribute *cocci_id/* drivers/perf/arm_pmu.c 499 */[];
	struct device_attribute *cocci_id/* drivers/perf/arm_pmu.c 491 */;
	char *cocci_id/* drivers/perf/arm_pmu.c 491 */;
	struct device *cocci_id/* drivers/perf/arm_pmu.c 490 */;
	ssize_t cocci_id/* drivers/perf/arm_pmu.c 490 */;
	struct pmu *cocci_id/* drivers/perf/arm_pmu.c 461 */;
	const unsigned *cocci_id/* drivers/perf/arm_pmu.c 41 */[PERF_COUNT_HW_CACHE_MAX][PERF_COUNT_HW_CACHE_OP_MAX][PERF_COUNT_HW_CACHE_RESULT_MAX];
	unsigned long cocci_id/* drivers/perf/arm_pmu.c 400 */;
	struct hw_perf_event *cocci_id/* drivers/perf/arm_pmu.c 364 */;
	struct perf_event *cocci_id/* drivers/perf/arm_pmu.c 361 */;
	void **cocci_id/* drivers/perf/arm_pmu.c 348 */;
	irqreturn_t cocci_id/* drivers/perf/arm_pmu.c 336 */;
	void *cocci_id/* drivers/perf/arm_pmu.c 336 */;
	u64 cocci_id/* drivers/perf/arm_pmu.c 32 */;
	s64 cocci_id/* drivers/perf/arm_pmu.c 124 */;
	u32 cocci_id/* drivers/perf/arm_pmu.c 100 */;
	__typeof__(struct arm_pmu *) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
	__typeof__(int) cocci_id/* /home/jaskaran/lkmp/coccinelle/standard.h 437 */;
}
