cocci_test_suite() {
	u32 cocci_id/* drivers/scsi/mvumi.c 924 */;
	u8 cocci_id/* drivers/scsi/mvumi.c 890 */;
	unsigned long *cocci_id/* drivers/scsi/mvumi.c 883 */;
	u64 cocci_id/* drivers/scsi/mvumi.c 836 */;
	struct mvumi_hs_page3 *cocci_id/* drivers/scsi/mvumi.c 835 */;
	struct mvumi_hs_page4 *cocci_id/* drivers/scsi/mvumi.c 834 */;
	struct mvumi_hs_page2 *cocci_id/* drivers/scsi/mvumi.c 833 */;
	unsigned char *cocci_id/* drivers/scsi/mvumi.c 818 */;
	struct mvumi_hs_header *cocci_id/* drivers/scsi/mvumi.c 815 */;
	bool cocci_id/* drivers/scsi/mvumi.c 66 */;
	unsigned char cocci_id/* drivers/scsi/mvumi.c 632 */;
	void cocci_id/* drivers/scsi/mvumi.c 630 */;
	unsigned char cocci_id/* drivers/scsi/mvumi.c 592 */(struct mvumi_hba *mhba);
	struct mvumi_tag *cocci_id/* drivers/scsi/mvumi.c 53 */;
	unsigned int *cocci_id/* drivers/scsi/mvumi.c 490 */;
	struct mvumi_rsp_frame *cocci_id/* drivers/scsi/mvumi.c 463 */;
	char cocci_id/* drivers/scsi/mvumi.c 462 */;
	struct mvumi_dyn_list_entry cocci_id/* drivers/scsi/mvumi.c 449 */;
	void **cocci_id/* drivers/scsi/mvumi.c 435 */;
	struct mvumi_cmd cocci_id/* drivers/scsi/mvumi.c 392 */;
	struct mvumi_cmd *cocci_id/* drivers/scsi/mvumi.c 368 */;
	struct mvumi_hba *cocci_id/* drivers/scsi/mvumi.c 365 */;
	int cocci_id/* drivers/scsi/mvumi.c 365 */;
	const struct pci_device_id cocci_id/* drivers/scsi/mvumi.c 36 */[];
	dma_addr_t cocci_id/* drivers/scsi/mvumi.c 291 */;
	struct mvumi_sgl *cocci_id/* drivers/scsi/mvumi.c 289 */;
	struct pci_driver cocci_id/* drivers/scsi/mvumi.c 2650 */;
	int __maybe_unused cocci_id/* drivers/scsi/mvumi.c 2589 */;
	pm_message_t cocci_id/* drivers/scsi/mvumi.c 2570 */;
	struct Scsi_Host *cocci_id/* drivers/scsi/mvumi.c 2537 */;
	struct pci_dev *cocci_id/* drivers/scsi/mvumi.c 2535 */;
	const struct pci_device_id *cocci_id/* drivers/scsi/mvumi.c 2455 */;
	struct mvumi_sgl cocci_id/* drivers/scsi/mvumi.c 2394 */;
	struct mvumi_msg_frame cocci_id/* drivers/scsi/mvumi.c 2394 */;
	struct mvumi_hw_regs *cocci_id/* drivers/scsi/mvumi.c 2190 */;
	void *cocci_id/* drivers/scsi/mvumi.c 2189 */;
	struct scsi_host_template cocci_id/* drivers/scsi/mvumi.c 2174 */;
	unsigned long cocci_id/* drivers/scsi/mvumi.c 2152 */;
	sector_t cocci_id/* drivers/scsi/mvumi.c 2148 */;
	int cocci_id/* drivers/scsi/mvumi.c 2148 */[];
	struct scsi_device *cocci_id/* drivers/scsi/mvumi.c 2147 */;
	struct block_device *cocci_id/* drivers/scsi/mvumi.c 2147 */;
	enum blk_eh_timer_return cocci_id/* drivers/scsi/mvumi.c 2115 */;
	char *cocci_id/* drivers/scsi/mvumi.c 2103 */;
	unsigned short cocci_id/* drivers/scsi/mvumi.c 2033 */;
	struct mvumi_msg_frame *cocci_id/* drivers/scsi/mvumi.c 2028 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/mvumi.c 2026 */;
	struct mvumi_instance_template cocci_id/* drivers/scsi/mvumi.c 1981 */;
	struct scatterlist *cocci_id/* drivers/scsi/mvumi.c 192 */;
	enum mvumi_qc_result cocci_id/* drivers/scsi/mvumi.c 1864 */;
	struct mvumi_dyn_list_entry *cocci_id/* drivers/scsi/mvumi.c 1847 */;
	irqreturn_t cocci_id/* drivers/scsi/mvumi.c 1790 */;
	struct mvumi_ob_data cocci_id/* drivers/scsi/mvumi.c 1772 */;
	struct mvumi_ob_data *cocci_id/* drivers/scsi/mvumi.c 1768 */;
	struct mvumi_events_wq *cocci_id/* drivers/scsi/mvumi.c 1742 */;
	struct mvumi_events_wq cocci_id/* drivers/scsi/mvumi.c 1734 */;
	struct work_struct *cocci_id/* drivers/scsi/mvumi.c 1731 */;
	struct mvumi_event_req cocci_id/* drivers/scsi/mvumi.c 1715 */;
	struct mvumi_event_req *cocci_id/* drivers/scsi/mvumi.c 1682 */;
	struct mvumi_driver_event *cocci_id/* drivers/scsi/mvumi.c 1681 */;
	const unsigned long *cocci_id/* drivers/scsi/mvumi.c 1649 */;
	struct mvumi_hotplug_event *cocci_id/* drivers/scsi/mvumi.c 1646 */;
	struct mvumi_device cocci_id/* drivers/scsi/mvumi.c 1575 */;
	struct mvumi_device *cocci_id/* drivers/scsi/mvumi.c 1463 */;
	u16 cocci_id/* drivers/scsi/mvumi.c 1379 */;
	struct mvumi_sense_data cocci_id/* drivers/scsi/mvumi.c 1318 */;
	struct mvumi_hs_page1 *cocci_id/* drivers/scsi/mvumi.c 1137 */;
	enum resource_type cocci_id/* drivers/scsi/mvumi.c 107 */;
	unsigned int cocci_id/* drivers/scsi/mvumi.c 107 */;
	struct mvumi_res *cocci_id/* drivers/scsi/mvumi.c 106 */;
}
