cocci_test_suite() {
	void __iomem *cocci_id/* drivers/scsi/isci/request.c 792 */;
	const char *const cocci_id/* drivers/scsi/isci/request.c 68 */[];
	enum dma_data_direction cocci_id/* drivers/scsi/isci/request.c 668 */;
	const char *cocci_id/* drivers/scsi/isci/request.c 66 */;
	char *cocci_id/* drivers/scsi/isci/request.c 550 */;
	struct ssp_cmd_iu cocci_id/* drivers/scsi/isci/request.c 431 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/isci/request.c 424 */;
	unsigned long cocci_id/* drivers/scsi/isci/request.c 3449 */;
	int cocci_id/* drivers/scsi/isci/request.c 3444 */;
	struct isci_tmf *cocci_id/* drivers/scsi/isci/request.c 3432 */;
	struct isci_host *cocci_id/* drivers/scsi/isci/request.c 3340 */;
	struct isci_port *cocci_id/* drivers/scsi/isci/request.c 3191 */;
	struct scu_task_context *cocci_id/* drivers/scsi/isci/request.c 3190 */;
	struct host_to_dev_fis cocci_id/* drivers/scsi/isci/request.c 3164 */;
	struct ata_queued_cmd *cocci_id/* drivers/scsi/isci/request.c 3156 */;
	struct host_to_dev_fis *cocci_id/* drivers/scsi/isci/request.c 3155 */;
	struct scu_task_context cocci_id/* drivers/scsi/isci/request.c 3109 */;
	struct domain_device *cocci_id/* drivers/scsi/isci/request.c 3091 */;
	const struct sci_base_state cocci_id/* drivers/scsi/isci/request.c 3035 */[];
	typeof(*ireq) cocci_id/* drivers/scsi/isci/request.c 3015 */;
	struct sci_base_state_machine *cocci_id/* drivers/scsi/isci/request.c 3013 */;
	struct smp_req *cocci_id/* drivers/scsi/isci/request.c 2921 */;
	struct scsi_device *cocci_id/* drivers/scsi/isci/request.c 278 */;
	enum exec_status cocci_id/* drivers/scsi/isci/request.c 2744 */;
	enum service_response cocci_id/* drivers/scsi/isci/request.c 2743 */;
	struct ssp_response_iu *cocci_id/* drivers/scsi/isci/request.c 2740 */;
	enum sci_io_status cocci_id/* drivers/scsi/isci/request.c 2737 */;
	struct ata_task_resp *cocci_id/* drivers/scsi/isci/request.c 2720 */;
	void *cocci_id/* drivers/scsi/isci/request.c 2720 */;
	struct task_status_struct *cocci_id/* drivers/scsi/isci/request.c 2719 */;
	unsigned int cocci_id/* drivers/scsi/isci/request.c 2531 */;
	enum exec_status *cocci_id/* drivers/scsi/isci/request.c 2529 */;
	enum service_response *cocci_id/* drivers/scsi/isci/request.c 2528 */;
	enum sas_open_rej_reason cocci_id/* drivers/scsi/isci/request.c 2506 */;
	struct device *cocci_id/* drivers/scsi/isci/request.c 2470 */;
	u16 cocci_id/* drivers/scsi/isci/request.c 2193 */;
	struct dev_to_host_fis *cocci_id/* drivers/scsi/isci/request.c 2184 */;
	struct isci_remote_device *cocci_id/* drivers/scsi/isci/request.c 2183 */;
	enum sci_base_request_states cocci_id/* drivers/scsi/isci/request.c 2155 */;
	struct sata_fis_data *cocci_id/* drivers/scsi/isci/request.c 1997 */;
	struct ssp_task_iu cocci_id/* drivers/scsi/isci/request.c 199 */;
	struct ssp_task_iu *cocci_id/* drivers/scsi/isci/request.c 193 */;
	u8 *cocci_id/* drivers/scsi/isci/request.c 1775 */;
	struct ssp_cmd_iu *cocci_id/* drivers/scsi/isci/request.c 173 */;
	struct ssp_frame_hdr cocci_id/* drivers/scsi/isci/request.c 1718 */;
	struct ata_device *cocci_id/* drivers/scsi/isci/request.c 1668 */;
	struct stp_task_context cocci_id/* drivers/scsi/isci/request.c 1661 */;
	struct sas_task *cocci_id/* drivers/scsi/isci/request.c 1622 */;
	u32 cocci_id/* drivers/scsi/isci/request.c 1620 */;
	enum sci_status cocci_id/* drivers/scsi/isci/request.c 1619 */;
	struct isci_request *cocci_id/* drivers/scsi/isci/request.c 1619 */;
	void **cocci_id/* drivers/scsi/isci/request.c 1593 */;
	u32 *cocci_id/* drivers/scsi/isci/request.c 1589 */;
	struct isci_stp_request *cocci_id/* drivers/scsi/isci/request.c 1512 */;
	bool cocci_id/* drivers/scsi/isci/request.c 1511 */;
	struct page *cocci_id/* drivers/scsi/isci/request.c 1427 */;
	struct isci_stp_pio_sgl *cocci_id/* drivers/scsi/isci/request.c 1264 */;
	struct scu_sgl_element_pair *cocci_id/* drivers/scsi/isci/request.c 1262 */;
	dma_addr_t cocci_id/* drivers/scsi/isci/request.c 118 */;
	struct scu_sgl_element *cocci_id/* drivers/scsi/isci/request.c 105 */;
	struct scatterlist *cocci_id/* drivers/scsi/isci/request.c 105 */;
	void cocci_id/* drivers/scsi/isci/request.c 105 */;
	ssize_t cocci_id/* drivers/scsi/isci/request.c 1020 */;
	u8 cocci_id/* drivers/scsi/isci/request.c 1001 */;
}
