cocci_test_suite() {
	const struct file_operations cocci_id/* drivers/scsi/ch.c 993 */;
	struct scsi_driver cocci_id/* drivers/scsi/ch.c 984 */;
	struct scsi_device *cocci_id/* drivers/scsi/ch.c 912 */;
	struct device *cocci_id/* drivers/scsi/ch.c 910 */;
	struct changer_element_status32 cocci_id/* drivers/scsi/ch.c 889 */;
	struct changer_element_status32 {
		int ces_type;
		compat_uptr_t ces_data;
	} cocci_id/* drivers/scsi/ch.c 865 */;
	struct changer_set_voltag cocci_id/* drivers/scsi/ch.c 837 */;
	const char *cocci_id/* drivers/scsi/ch.c 83 */[CH_TYPES - 4];
	int cocci_id/* drivers/scsi/ch.c 79 */[CH_TYPES - 4];
	u_char *cocci_id/* drivers/scsi/ch.c 753 */;
	struct changer_get_element cocci_id/* drivers/scsi/ch.c 751 */;
	struct changer_element_status cocci_id/* drivers/scsi/ch.c 739 */;
	int cocci_id/* drivers/scsi/ch.c 72 */[CH_DT_MAX];
	struct changer_exchange cocci_id/* drivers/scsi/ch.c 714 */;
	struct changer_move cocci_id/* drivers/scsi/ch.c 692 */;
	struct changer_position cocci_id/* drivers/scsi/ch.c 673 */;
	struct changer_vendor_params cocci_id/* drivers/scsi/ch.c 647 */;
	struct changer_params cocci_id/* drivers/scsi/ch.c 633 */;
	void __user *cocci_id/* drivers/scsi/ch.c 623 */;
	unsigned long cocci_id/* drivers/scsi/ch.c 619 */;
	struct file *cocci_id/* drivers/scsi/ch.c 618 */;
	long cocci_id/* drivers/scsi/ch.c 618 */;
	scsi_changer *cocci_id/* drivers/scsi/ch.c 611 */;
	unsigned int cocci_id/* drivers/scsi/ch.c 611 */;
	struct inode *cocci_id/* drivers/scsi/ch.c 588 */;
	scsi_changer cocci_id/* drivers/scsi/ch.c 570 */;
	struct kref *cocci_id/* drivers/scsi/ch.c 568 */;
	u_char cocci_id/* drivers/scsi/ch.c 542 */[16];
	unsigned char __user *cocci_id/* drivers/scsi/ch.c 539 */;
	int cocci_id/* drivers/scsi/ch.c 490 */;
	char *cocci_id/* drivers/scsi/ch.c 488 */;
	void cocci_id/* drivers/scsi/ch.c 487 */;
	u_char cocci_id/* drivers/scsi/ch.c 465 */[12];
	u_char cocci_id/* drivers/scsi/ch.c 424 */[10];
	u_char cocci_id/* drivers/scsi/ch.c 281 */[6];
	u_int cocci_id/* drivers/scsi/ch.c 222 */;
	struct scsi_sense_hdr cocci_id/* drivers/scsi/ch.c 192 */;
	enum dma_data_direction cocci_id/* drivers/scsi/ch.c 189 */;
	void *cocci_id/* drivers/scsi/ch.c 188 */;
	unsigned cocci_id/* drivers/scsi/ch.c 188 */;
	unsigned char *cocci_id/* drivers/scsi/ch.c 187 */;
	struct scsi_sense_hdr *cocci_id/* drivers/scsi/ch.c 165 */;
	const struct {
		unsigned char sense;
		unsigned char asc;
		unsigned char ascq;
		int errno;
	} cocci_id/* drivers/scsi/ch.c 125 */[];
	struct {
		struct kref ref;
		struct list_head list;
		int minor;
		char name[8];
		struct scsi_device *device;
		struct scsi_device **dt;
		u_int firsts[CH_TYPES];
		u_int counts[CH_TYPES];
		u_int unit_attention;
		u_int voltags;
		struct mutex lock;
	} cocci_id/* drivers/scsi/ch.c 108 */;
	struct class *cocci_id/* drivers/scsi/ch.c 106 */;
	void __exit cocci_id/* drivers/scsi/ch.c 1032 */;
	int __init cocci_id/* drivers/scsi/ch.c 1004 */;
}
