cocci_test_suite() {
	struct fcoe_crc_eof *cocci_id/* drivers/scsi/qedf/qedf_main.c 994 */;
	struct sk_buff *cocci_id/* drivers/scsi/qedf/qedf_main.c 933 */;
	struct scsi_host_template cocci_id/* drivers/scsi/qedf/qedf_main.c 914 */;
	struct scsi_device *cocci_id/* drivers/scsi/qedf/qedf_main.c 905 */;
	struct qed_link_output cocci_id/* drivers/scsi/qedf/qedf_main.c 844 */;
	struct fc_rport_libfc_priv *cocci_id/* drivers/scsi/qedf/qedf_main.c 654 */;
	struct qedf_ioreq *cocci_id/* drivers/scsi/qedf/qedf_main.c 653 */;
	struct fc_rport *cocci_id/* drivers/scsi/qedf/qedf_main.c 650 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/qedf/qedf_main.c 648 */;
	struct scsi_transport_template *cocci_id/* drivers/scsi/qedf/qedf_main.c 642 */;
	struct qed_fcoe_cb_ops cocci_id/* drivers/scsi/qedf/qedf_main.c 629 */;
	u8 cocci_id/* drivers/scsi/qedf/qedf_main.c 573 */;
	u32 cocci_id/* drivers/scsi/qedf/qedf_main.c 570 */;
	struct qed_dcbx_get *cocci_id/* drivers/scsi/qedf/qedf_main.c 570 */;
	struct qed_link_output *cocci_id/* drivers/scsi/qedf/qedf_main.c 506 */;
	uint cocci_id/* drivers/scsi/qedf/qedf_main.c 40 */;
	void __exit cocci_id/* drivers/scsi/qedf/qedf_main.c 3887 */;
	int __init cocci_id/* drivers/scsi/qedf/qedf_main.c 3798 */;
	struct qed_generic_tlvs cocci_id/* drivers/scsi/qedf/qedf_main.c 3790 */;
	struct qed_generic_tlvs *cocci_id/* drivers/scsi/qedf/qedf_main.c 3779 */;
	struct fc_host_attrs *cocci_id/* drivers/scsi/qedf/qedf_main.c 3700 */;
	struct qed_mfw_tlv_fcoe *cocci_id/* drivers/scsi/qedf/qedf_main.c 3697 */;
	struct list_head cocci_id/* drivers/scsi/qedf/qedf_main.c 359 */;
	void cocci_id/* drivers/scsi/qedf/qedf_main.c 3557 */;
	const struct pci_device_id *cocci_id/* drivers/scsi/qedf/qedf_main.c 3552 */;
	unsigned int cocci_id/* drivers/scsi/qedf/qedf_main.c 35 */;
	struct fc_els_flogi cocci_id/* drivers/scsi/qedf/qedf_main.c 329 */;
	struct qedf_ctx cocci_id/* drivers/scsi/qedf/qedf_main.c 3182 */;
	u16 cocci_id/* drivers/scsi/qedf/qedf_main.c 3174 */;
	struct qed_probe_params cocci_id/* drivers/scsi/qedf/qedf_main.c 3173 */;
	struct qed_slowpath_params cocci_id/* drivers/scsi/qedf/qedf_main.c 3172 */;
	void *cocci_id/* drivers/scsi/qedf/qedf_main.c 3171 */;
	struct qed_link_params cocci_id/* drivers/scsi/qedf/qedf_main.c 3169 */;
	char cocci_id/* drivers/scsi/qedf/qedf_main.c 3168 */[20];
	struct qed_ll2_params cocci_id/* drivers/scsi/qedf/qedf_main.c 3167 */;
	bool cocci_id/* drivers/scsi/qedf/qedf_main.c 3166 */;
	struct Scsi_Host *cocci_id/* drivers/scsi/qedf/qedf_main.c 3165 */;
	struct qedf_ctx *cocci_id/* drivers/scsi/qedf/qedf_main.c 3164 */;
	struct fc_lport *cocci_id/* drivers/scsi/qedf/qedf_main.c 3163 */;
	struct pci_dev *cocci_id/* drivers/scsi/qedf/qedf_main.c 3160 */;
	int cocci_id/* drivers/scsi/qedf/qedf_main.c 3160 */;
	struct pci_driver cocci_id/* drivers/scsi/qedf/qedf_main.c 3152 */;
	const struct pci_device_id cocci_id/* drivers/scsi/qedf/qedf_main.c 3145 */[];
	struct qedf_glbl_q_params cocci_id/* drivers/scsi/qedf/qedf_main.c 3131 */;
	size_t cocci_id/* drivers/scsi/qedf/qedf_main.c 3128 */;
	u64 cocci_id/* drivers/scsi/qedf/qedf_main.c 3090 */;
	void (*cocci_id/* drivers/scsi/qedf/qedf_main.c 297 */)(struct fc_seq *,
								struct fc_frame *,
								void *);
	struct fcoe_cqe cocci_id/* drivers/scsi/qedf/qedf_main.c 2961 */;
	struct fc_frame *cocci_id/* drivers/scsi/qedf/qedf_main.c 296 */;
	struct global_queue cocci_id/* drivers/scsi/qedf/qedf_main.c 2951 */;
	struct fc_seq *cocci_id/* drivers/scsi/qedf/qedf_main.c 295 */;
	struct global_queue *cocci_id/* drivers/scsi/qedf/qedf_main.c 2932 */;
	u32 *cocci_id/* drivers/scsi/qedf/qedf_main.c 2905 */;
	void cocci_id/* drivers/scsi/qedf/qedf_main.c 29 */(struct pci_dev *pdev);
	struct scsi_bd cocci_id/* drivers/scsi/qedf/qedf_main.c 2847 */;
	u64 *cocci_id/* drivers/scsi/qedf/qedf_main.c 2831 */;
	struct scsi_bd *cocci_id/* drivers/scsi/qedf/qedf_main.c 2830 */;
	struct global_queue **cocci_id/* drivers/scsi/qedf/qedf_main.c 2808 */;
	int cocci_id/* drivers/scsi/qedf/qedf_main.c 28 */(struct pci_dev *pdev,
							   const struct pci_device_id *id);
	struct qedf_fastpath cocci_id/* drivers/scsi/qedf/qedf_main.c 2647 */;
	struct qedf_fastpath *cocci_id/* drivers/scsi/qedf/qedf_main.c 2628 */;
	struct fc_exch *cocci_id/* drivers/scsi/qedf/qedf_main.c 260 */;
	const struct qed_fcoe_ops *cocci_id/* drivers/scsi/qedf/qedf_main.c 26 */;
	struct status_block_e4 cocci_id/* drivers/scsi/qedf/qedf_main.c 2596 */;
	dma_addr_t cocci_id/* drivers/scsi/qedf/qedf_main.c 2592 */;
	struct status_block_e4 *cocci_id/* drivers/scsi/qedf/qedf_main.c 2591 */;
	struct qed_sb_info *cocci_id/* drivers/scsi/qedf/qedf_main.c 2589 */;
	struct qedf_io_work cocci_id/* drivers/scsi/qedf/qedf_main.c 2569 */;
	struct qedf_io_work *cocci_id/* drivers/scsi/qedf/qedf_main.c 2568 */;
	struct work_struct *cocci_id/* drivers/scsi/qedf/qedf_main.c 2566 */;
	struct qed_ll2_cb_ops cocci_id/* drivers/scsi/qedf/qedf_main.c 2560 */;
	u8 *cocci_id/* drivers/scsi/qedf/qedf_main.c 2504 */;
	struct ethhdr *cocci_id/* drivers/scsi/qedf/qedf_main.c 2493 */;
	struct qedf_skb_work cocci_id/* drivers/scsi/qedf/qedf_main.c 2490 */;
	struct qedf_skb_work *cocci_id/* drivers/scsi/qedf/qedf_main.c 2489 */;
	struct fcoe_hdr cocci_id/* drivers/scsi/qedf/qedf_main.c 2367 */;
	struct fcoe_hdr *cocci_id/* drivers/scsi/qedf/qedf_main.c 2347 */;
	struct fcoe_crc_eof cocci_id/* drivers/scsi/qedf/qedf_main.c 2343 */;
	struct fc_frame_header *cocci_id/* drivers/scsi/qedf/qedf_main.c 2342 */;
	u8 cocci_id/* drivers/scsi/qedf/qedf_main.c 220 */[3];
	irqreturn_t cocci_id/* drivers/scsi/qedf/qedf_main.c 2196 */;
	struct fcoe_cqe *cocci_id/* drivers/scsi/qedf/qedf_main.c 2103 */;
	struct qedf_rport cocci_id/* drivers/scsi/qedf/qedf_main.c 2021 */;
	struct fc_rport_libfc_priv cocci_id/* drivers/scsi/qedf/qedf_main.c 2020 */;
	struct fc_function_template cocci_id/* drivers/scsi/qedf/qedf_main.c 1998 */;
	struct qed_fcoe_stats cocci_id/* drivers/scsi/qedf/qedf_main.c 1950 */;
	struct qed_fcoe_stats *cocci_id/* drivers/scsi/qedf/qedf_main.c 1942 */;
	struct fc_host_statistics *cocci_id/* drivers/scsi/qedf/qedf_main.c 1936 */;
	char cocci_id/* drivers/scsi/qedf/qedf_main.c 1724 */[32];
	struct fc_vport *cocci_id/* drivers/scsi/qedf/qedf_main.c 1716 */;
	u8 cocci_id/* drivers/scsi/qedf/qedf_main.c 1580 */[8];
	struct libfc_function_template cocci_id/* drivers/scsi/qedf/qedf_main.c 1559 */;
	unsigned long cocci_id/* drivers/scsi/qedf/qedf_main.c 1396 */;
	enum fc_rport_event cocci_id/* drivers/scsi/qedf/qedf_main.c 1388 */;
	struct fc_rport_priv *cocci_id/* drivers/scsi/qedf/qedf_main.c 1365 */;
	uint16_t cocci_id/* drivers/scsi/qedf/qedf_main.c 1246 */;
	struct qed_fcoe_params_offload cocci_id/* drivers/scsi/qedf/qedf_main.c 1243 */;
	struct fcoe_wqe cocci_id/* drivers/scsi/qedf/qedf_main.c 1185 */;
	struct qedf_rport *cocci_id/* drivers/scsi/qedf/qedf_main.c 1177 */;
	struct kmem_cache *cocci_id/* drivers/scsi/qedf/qedf_main.c 110 */;
	skb_frag_t *cocci_id/* drivers/scsi/qedf/qedf_main.c 1097 */;
	struct ethhdr cocci_id/* drivers/scsi/qedf/qedf_main.c 1087 */;
	struct fcoe_percpu_s cocci_id/* drivers/scsi/qedf/qedf_main.c 107 */;
	struct workqueue_struct *cocci_id/* drivers/scsi/qedf/qedf_main.c 105 */;
	struct fc_stats *cocci_id/* drivers/scsi/qedf/qedf_main.c 1002 */;
}
