cocci_test_suite() {
	struct hisi_sas_itct *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 982 */;
	u64 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 981 */;
	u32 *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 896 */;
	struct sas_identify_frame cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 895 */;
	void cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 893 */;
	struct hisi_sas_dq *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 862 */;
	unsigned long cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 846 */;
	int cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 844 */;
	struct hisi_hba *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 842 */;
	struct domain_device *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 840 */;
	struct hisi_sas_device *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 839 */;
	int *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 821 */;
	void __iomem *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 761 */;
	void cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 727 */(struct timer_list *t);
	enum{TRANS_TX_FAIL_BASE=0x0, TRANS_RX_FAIL_BASE=0x20, DMA_TX_ERR_BASE=0x40, SIPC_RX_ERR_BASE=0x50, DMA_RX_ERR_BASE=0x60, TRANS_TX_OPEN_FAIL_WITH_IT_NEXUS_LOSS=TRANS_TX_FAIL_BASE, TRANS_TX_ERR_PHY_NOT_ENABLE, TRANS_TX_OPEN_CNX_ERR_WRONG_DESTINATION, TRANS_TX_OPEN_CNX_ERR_ZONE_VIOLATION, TRANS_TX_OPEN_CNX_ERR_BY_OTHER, RESERVED0, TRANS_TX_OPEN_CNX_ERR_AIP_TIMEOUT, TRANS_TX_OPEN_CNX_ERR_STP_RESOURCES_BUSY, TRANS_TX_OPEN_CNX_ERR_PROTOCOL_NOT_SUPPORTED, TRANS_TX_OPEN_CNX_ERR_CONNECTION_RATE_NOT_SUPPORTED, TRANS_TX_OPEN_CNX_ERR_BAD_DESTINATION, TRANS_TX_OPEN_CNX_ERR_BREAK_RCVD, TRANS_TX_OPEN_CNX_ERR_LOW_PHY_POWER, TRANS_TX_OPEN_CNX_ERR_PATHWAY_BLOCKED, TRANS_TX_OPEN_CNX_ERR_OPEN_TIMEOUT, TRANS_TX_OPEN_CNX_ERR_NO_DESTINATION, TRANS_TX_OPEN_RETRY_ERR_THRESHOLD_REACHED, TRANS_TX_ERR_FRAME_TXED, TRANS_TX_ERR_WITH_BREAK_TIMEOUT, TRANS_TX_ERR_WITH_BREAK_REQUEST, TRANS_TX_ERR_WITH_BREAK_RECEVIED, TRANS_TX_ERR_WITH_CLOSE_TIMEOUT, TRANS_TX_ERR_WITH_CLOSE_NORMAL, TRANS_TX_ERR_WITH_CLOSE_PHYDISALE, TRANS_TX_ERR_WITH_CLOSE_DWS_TIMEOUT, TRANS_TX_ERR_WITH_CLOSE_COMINIT, TRANS_TX_ERR_WITH_NAK_RECEVIED, TRANS_TX_ERR_WITH_ACK_NAK_TIMEOUT, TRANS_TX_ERR_WITH_CREDIT_TIMEOUT, TRANS_TX_ERR_WITH_IPTT_CONFLICT, TRANS_TX_ERR_WITH_OPEN_BY_DES_OR_OTHERS, TRANS_TX_ERR_WITH_WAIT_RECV_TIMEOUT, TRANS_RX_ERR_WITH_RXFRAME_CRC_ERR=TRANS_RX_FAIL_BASE, TRANS_RX_ERR_WITH_RXFIS_8B10B_DISP_ERR, TRANS_RX_ERR_WITH_RXFRAME_HAVE_ERRPRM, TRANS_RX_ERR_WITH_RXFIS_DECODE_ERROR, TRANS_RX_ERR_WITH_RXFIS_CRC_ERR, TRANS_RX_ERR_WITH_RXFRAME_LENGTH_OVERRUN, TRANS_RX_ERR_WITH_RXFIS_RX_SYNCP, TRANS_RX_ERR_WITH_LINK_BUF_OVERRUN, TRANS_RX_ERR_WITH_BREAK_TIMEOUT, TRANS_RX_ERR_WITH_BREAK_REQUEST, TRANS_RX_ERR_WITH_BREAK_RECEVIED, RESERVED1, TRANS_RX_ERR_WITH_CLOSE_NORMAL, TRANS_RX_ERR_WITH_CLOSE_PHY_DISABLE, TRANS_RX_ERR_WITH_CLOSE_DWS_TIMEOUT, TRANS_RX_ERR_WITH_CLOSE_COMINIT, TRANS_RX_ERR_WITH_DATA_LEN0, TRANS_RX_ERR_WITH_BAD_HASH, TRANS_RX_XRDY_WLEN_ZERO_ERR, TRANS_RX_SSP_FRM_LEN_ERR, RESERVED2, RESERVED3, RESERVED4, RESERVED5, TRANS_RX_ERR_WITH_BAD_FRM_TYPE, TRANS_RX_SMP_FRM_LEN_ERR, TRANS_RX_SMP_RESP_TIMEOUT_ERR, RESERVED6, RESERVED7, RESERVED8, RESERVED9, TRANS_RX_R_ERR, DMA_TX_DIF_CRC_ERR=DMA_TX_ERR_BASE, DMA_TX_DIF_APP_ERR, DMA_TX_DIF_RPP_ERR, DMA_TX_DATA_SGL_OVERFLOW, DMA_TX_DIF_SGL_OVERFLOW, DMA_TX_UNEXP_XFER_ERR, DMA_TX_UNEXP_RETRANS_ERR, DMA_TX_XFER_LEN_OVERFLOW, DMA_TX_XFER_OFFSET_ERR, DMA_TX_RAM_ECC_ERR, DMA_TX_DIF_LEN_ALIGN_ERR, DMA_TX_MAX_ERR_CODE, SIPC_RX_FIS_STATUS_ERR_BIT_VLD=SIPC_RX_ERR_BASE, SIPC_RX_PIO_WRSETUP_STATUS_DRQ_ERR, SIPC_RX_FIS_STATUS_BSY_BIT_ERR, SIPC_RX_WRSETUP_LEN_ODD_ERR, SIPC_RX_WRSETUP_LEN_ZERO_ERR, SIPC_RX_WRDATA_LEN_NOT_MATCH_ERR, SIPC_RX_NCQ_WRSETUP_OFFSET_ERR, SIPC_RX_NCQ_WRSETUP_AUTO_ACTIVE_ERR, SIPC_RX_SATA_UNEXP_FIS_ERR, SIPC_RX_WRSETUP_ESTATUS_ERR, SIPC_RX_DATA_UNDERFLOW_ERR, SIPC_RX_MAX_ERR_CODE, DMA_RX_DIF_CRC_ERR=DMA_RX_ERR_BASE, DMA_RX_DIF_APP_ERR, DMA_RX_DIF_RPP_ERR, DMA_RX_DATA_SGL_OVERFLOW, DMA_RX_DIF_SGL_OVERFLOW, DMA_RX_DATA_LEN_OVERFLOW, DMA_RX_DATA_LEN_UNDERFLOW, DMA_RX_DATA_OFFSET_ERR, RESERVED10, DMA_RX_SATA_FRAME_TYPE_ERR, DMA_RX_RESP_BUF_OVERFLOW, DMA_RX_UNEXP_RETRANS_RESP_ERR, DMA_RX_UNEXP_NORM_RESP_ERR, DMA_RX_UNEXP_RDFRAME_ERR, DMA_RX_PIO_DATA_LEN_ERR, DMA_RX_RDSETUP_STATUS_ERR, DMA_RX_RDSETUP_STATUS_DRQ_ERR, DMA_RX_RDSETUP_STATUS_BSY_ERR, DMA_RX_RDSETUP_LEN_ODD_ERR, DMA_RX_RDSETUP_LEN_ZERO_ERR, DMA_RX_RDSETUP_LEN_OVER_ERR, DMA_RX_RDSETUP_OFFSET_ERR, DMA_RX_RDSETUP_ACTIVE_ERR, DMA_RX_RDSETUP_ESTATUS_ERR, DMA_RX_RAM_ECC_ERR, DMA_RX_UNKNOWN_FRM_ERR, DMA_RX_MAX_ERR_CODE,} cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 572 */;
	enum{HISI_SAS_PHY_PHY_UPDOWN, HISI_SAS_PHY_CHNL_INT, HISI_SAS_PHY_INT_NR,} cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 566 */;
	struct sig_atten_lu_s {
		const struct signal_attenuation_s *att;
		u32 sas_phy_ctrl;
	} cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 415 */;
	struct signal_attenuation_s {
		u32 de_emphasis;
		u32 preshoot;
		u32 boost;
	} cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 409 */;
	struct hisi_sas_err_record_v2 {
		__le32 trans_tx_fail_type;
		__le32 trans_rx_fail_type;
		__le16 dma_tx_err_type;
		__le16 sipc_rx_err_type;
		__le32 dma_rx_err_type;
	} cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 394 */;
	struct hisi_sas_complete_v2_hdr {
		__le32 dw0;
		__le32 dw1;
		__le32 act;
		__le32 dw3;
	} cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 387 */;
	struct platform_driver cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3628 */;
	const struct acpi_device_id cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3621 */[];
	const struct of_device_id cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3614 */[];
	struct sas_ha_struct *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3606 */;
	struct platform_device *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3587 */;
	struct hisi_sas_complete_v2_hdr cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3579 */;
	const struct hisi_sas_hw cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3558 */;
	struct scsi_host_template cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3537 */;
	struct device_attribute *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3532 */[];
	struct tasklet_struct *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3363 */;
	irq_handler_t cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3304 */[HISI_SAS_FATAL_INT_NR];
	irq_handler_t cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3299 */[HISI_SAS_PHY_INT_NR];
	struct dev_to_host_fis cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3275 */;
	u8 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3209 */[SAS_ADDR_SIZE];
	struct dev_to_host_fis *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3206 */;
	struct hisi_sas_initial_fis *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3205 */;
	struct hisi_sas_cq *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3188 */;
	irqreturn_t cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3186 */;
	void *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3186 */;
	__le64 *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3150 */;
	struct hisi_sas_complete_v2_hdr *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3120 */;
	struct hisi_sas_slot *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3118 */;
	const struct hisi_sas_hw_error *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3065 */;
	const struct hisi_sas_hw_error cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 3006 */[];
	struct sas_identify_frame *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2647 */;
	struct hisi_sas_cmd_hdr *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2615 */;
	struct sas_task *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2613 */;
	struct hisi_sas_phy *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2589 */;
	struct asd_sas_phy *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2580 */;
	struct asd_sas_port *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2579 */;
	struct hisi_sas_port *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2578 */;
	struct timer_list *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2575 */;
	struct host_to_dev_fis cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2572 */;
	u8 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2548 */;
	struct ata_queued_cmd *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2545 */;
	u8 *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2500 */;
	struct hisi_sas_tmf_task *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2499 */;
	struct hisi_sas_err_record cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2437 */;
	struct ssp_response_iu *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2420 */;
	struct hisi_sas_status_buffer *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2418 */;
	enum exec_status cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2332 */;
	struct task_status_struct *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2329 */;
	u16 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2028 */;
	struct hisi_sas_err_record_v2 *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 2024 */;
	const u8 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1979 */[];
	struct ssp_frame_hdr cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1782 */;
	struct ssp_command_iu cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1782 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1746 */;
	struct sas_ssp_task *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1745 */;
	unsigned int cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1708 */;
	dma_addr_t cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1707 */;
	struct hisi_sas_sge *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1685 */;
	struct hisi_sas_sge_page *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1680 */;
	struct scatterlist *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1677 */;
	struct sas_phy_linkrates *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1614 */;
	struct sas_phy *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1565 */;
	bool cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1477 */;
	u32 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1432 */;
	struct device *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1431 */;
	enum sas_linkrate cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1240 */;
	const struct signal_attenuation_s *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1217 */;
	const struct sig_atten_lu_s *cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1216 */;
	u32 cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1168 */[3];
	const struct sig_atten_lu_s cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1160 */[];
	const struct signal_attenuation_s cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1159 */;
	acpi_status cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1079 */;
	struct hisi_sas_itct cocci_id/* drivers/scsi/hisi_sas/hisi_sas_v2_hw.c 1004 */;
}
