cocci_test_suite() {
	u16 cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 81 */;
	void **cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 81 */;
	unsigned int cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 81 */;
	struct nvme_fc_local_port *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 80 */;
	struct nvme_fc_port_info cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 680 */;
	struct nvme_fc_port_template *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 678 */;
	struct qla_nvme_rport cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 627 */;
	uint8_t cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 504 */;
	cont_a64_entry_t *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 474 */;
	struct nvme_fc_cmd_iu *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 401 */;
	struct nvmefc_fcp_req *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 369 */;
	struct scatterlist *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 368 */;
	struct srb_iocb *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 367 */;
	struct qla_qpair *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 366 */;
	struct qla_hw_data *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 365 */;
	struct scsi_qla_host *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 364 */;
	struct req_que *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 363 */;
	struct dsd64 *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 362 */;
	uint16_t cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 358 */;
	struct cmd_nvme *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 357 */;
	uint32_t cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 356 */;
	uint32_t *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 355 */;
	unsigned long cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 354 */;
	srb_t *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 352 */;
	int cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 352 */;
	struct nvme_fc_remote_port *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 331 */;
	void *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 331 */;
	struct qla_nvme_rport *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 270 */;
	struct nvmefc_ls_req *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 246 */;
	fc_port_t *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 214 */;
	struct nvme_private cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 212 */;
	struct nvme_private *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 211 */;
	struct work_struct *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 209 */;
	void cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 209 */;
	struct fc_port *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 15 */;
	struct nvme_fc_port_template cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 13 */;
	struct srb cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 125 */;
	struct srb *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 125 */;
	struct kref *cocci_id/* drivers/scsi/qla2xxx/qla_nvme.c 123 */;
}
