cocci_test_suite() {
	unsigned long long cocci_id/* drivers/nvdimm/pmem.c 87 */;
	sector_t cocci_id/* drivers/nvdimm/pmem.c 74 */;
	blk_status_t cocci_id/* drivers/nvdimm/pmem.c 70 */;
	struct nd_device_driver cocci_id/* drivers/nvdimm/pmem.c 623 */;
	struct nd_pfn_sb *cocci_id/* drivers/nvdimm/pmem.c 600 */;
	struct nd_pfn *cocci_id/* drivers/nvdimm/pmem.c 599 */;
	struct nd_btt *cocci_id/* drivers/nvdimm/pmem.c 584 */;
	struct page *cocci_id/* drivers/nvdimm/pmem.c 58 */;
	struct kernfs_node *cocci_id/* drivers/nvdimm/pmem.c 578 */;
	struct badblocks *cocci_id/* drivers/nvdimm/pmem.c 577 */;
	struct resource cocci_id/* drivers/nvdimm/pmem.c 576 */;
	struct nd_namespace_io *cocci_id/* drivers/nvdimm/pmem.c 575 */;
	struct nd_namespace_common *cocci_id/* drivers/nvdimm/pmem.c 574 */;
	struct nd_region *cocci_id/* drivers/nvdimm/pmem.c 572 */;
	enum nvdimm_event cocci_id/* drivers/nvdimm/pmem.c 570 */;
	struct device *cocci_id/* drivers/nvdimm/pmem.c 570 */;
	int cocci_id/* drivers/nvdimm/pmem.c 494 */;
	unsigned long cocci_id/* drivers/nvdimm/pmem.c 49 */;
	phys_addr_t cocci_id/* drivers/nvdimm/pmem.c 47 */;
	unsigned int cocci_id/* drivers/nvdimm/pmem.c 47 */;
	void cocci_id/* drivers/nvdimm/pmem.c 46 */;
	void *cocci_id/* drivers/nvdimm/pmem.c 366 */;
	struct gendisk *cocci_id/* drivers/nvdimm/pmem.c 365 */;
	struct request_queue *cocci_id/* drivers/nvdimm/pmem.c 363 */;
	struct dax_device *cocci_id/* drivers/nvdimm/pmem.c 360 */;
	struct resource *cocci_id/* drivers/nvdimm/pmem.c 357 */;
	const struct dev_pagemap_ops cocci_id/* drivers/nvdimm/pmem.c 345 */;
	struct request_queue cocci_id/* drivers/nvdimm/pmem.c 312 */;
	struct dev_pagemap *cocci_id/* drivers/nvdimm/pmem.c 309 */;
	const struct attribute_group *cocci_id/* drivers/nvdimm/pmem.c 304 */[];
	const struct dax_operations cocci_id/* drivers/nvdimm/pmem.c 297 */;
	struct iov_iter *cocci_id/* drivers/nvdimm/pmem.c 286 */;
	size_t cocci_id/* drivers/nvdimm/pmem.c 285 */;
	const struct block_device_operations cocci_id/* drivers/nvdimm/pmem.c 265 */;
	resource_size_t cocci_id/* drivers/nvdimm/pmem.c 245 */;
	pfn_t *cocci_id/* drivers/nvdimm/pmem.c 243 */;
	void **cocci_id/* drivers/nvdimm/pmem.c 243 */;
	pgoff_t cocci_id/* drivers/nvdimm/pmem.c 242 */;
	struct pmem_device *cocci_id/* drivers/nvdimm/pmem.c 242 */;
	long cocci_id/* drivers/nvdimm/pmem.c 242 */;
	struct block_device *cocci_id/* drivers/nvdimm/pmem.c 220 */;
	struct bvec_iter cocci_id/* drivers/nvdimm/pmem.c 191 */;
	struct bio_vec cocci_id/* drivers/nvdimm/pmem.c 190 */;
	blk_qc_t cocci_id/* drivers/nvdimm/pmem.c 184 */;
	struct bio *cocci_id/* drivers/nvdimm/pmem.c 184 */;
	bool cocci_id/* drivers/nvdimm/pmem.c 144 */;
}
