cocci_test_suite() {
	uint64_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 95 */;
	enum csio_scsi_ev cocci_id/* drivers/scsi/csiostor/csio_scsi.c 888 */;
	void cocci_id/* drivers/scsi/csiostor/csio_scsi.c 71 */(struct csio_ioreq *,
								enum csio_scsi_ev);
	uint8_t *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 688 */;
	struct fw_scsi_abrt_cls_wr cocci_id/* drivers/scsi/csiostor/csio_scsi.c 678 */;
	struct csio_wr_pair cocci_id/* drivers/scsi/csiostor/csio_scsi.c 676 */;
	int cocci_id/* drivers/scsi/csiostor/csio_scsi.c 65 */(struct csio_hw *,
							       struct csio_ioreq *,
							       bool);
	uint32_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 60 */;
	struct fw_scsi_write_wr cocci_id/* drivers/scsi/csiostor/csio_scsi.c 447 */;
	struct fw_scsi_write_wr *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 417 */;
	struct fw_scsi_read_wr cocci_id/* drivers/scsi/csiostor/csio_scsi.c 394 */;
	struct ulptx_sgl *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 365 */;
	struct ulptx_sge_pair *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 293 */;
	struct csio_sm cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2509 */;
	struct csio_sm *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2506 */;
	struct csio_ioreq cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2431 */;
	struct fcp_cmnd cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2421 */;
	struct fw_scsi_cmd_wr cocci_id/* drivers/scsi/csiostor/csio_scsi.c 237 */;
	struct csio_dma_buf cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2337 */;
	struct csio_dma_buf *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2320 */;
	struct scsi_host_template cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2265 */;
	struct csio_lnode **cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2229 */;
	struct scsi_device *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2222 */;
	unsigned char *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2123 */;
	struct csio_scsi_level_data cocci_id/* drivers/scsi/csiostor/csio_scsi.c 2070 */;
	struct fw_scsi_cmd_wr *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 205 */;
	uint64_t *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1934 */;
	struct csio_rnode *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1918 */;
	unsigned long cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1916 */;
	struct csio_scsi_qset *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1889 */;
	void *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1836 */;
	struct fc_rport *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1787 */;
	struct Scsi_Host *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1775 */;
	uint8_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1740 */;
	struct fcp_cmnd *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 165 */;
	struct fcp_resp_rsp_info *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1563 */;
	struct fcp_resp_with_ext *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1562 */;
	struct scatterlist *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1492 */;
	struct device_attribute *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1463 */[];
	char *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1429 */;
	uint16_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 142 */;
	bool cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1407 */;
	const char *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1377 */;
	struct device_attribute *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1377 */;
	size_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1377 */;
	struct device *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1376 */;
	ssize_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1375 */;
	struct list_head *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1233 */;
	struct csio_scsim *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1197 */;
	int cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1196 */;
	struct csio_hw *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1195 */;
	struct csio_lnode *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1194 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1192 */;
	struct csio_ioreq *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1192 */;
	void cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1191 */;
	struct csio_scsi_level_data *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 119 */;
	struct fw_scsi_abrt_cls_wr *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1139 */;
	struct fw_scsi_read_wr *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1129 */;
	uintptr_t cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1112 */;
	struct cpl_fw6_msg *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1106 */;
	struct csio_fl_dma_buf *cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1103 */;
	uint8_t **cocci_id/* drivers/scsi/csiostor/csio_scsi.c 1103 */;
}
