cocci_test_suite() {
	bool cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 99 */;
	struct scsi_info *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 99 */;
	u64 *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 771 */;
	u64 cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 767 */;
	struct srp_rsp *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 58 */;
	void cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 55 */(struct scsi_info *vscsi);
	long cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 52 */(struct scsi_info *vscsi,
								       struct viosrp_crq *crq);
	char cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 45 */[PARTITION_NAMELEN];
	char cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 44 */[SYS_ID_NAME_LEN];
	void __exit cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4145 */;
	int __init cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4107 */;
	struct scsi_info cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 410 */;
	struct vio_driver cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4092 */;
	const struct vio_device_id cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4086 */[];
	struct class cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4080 */;
	struct work_struct *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 408 */;
	struct attribute *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4073 */[];
	struct device_attribute cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4067 */;
	struct device *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4062 */;
	const struct target_core_fabric_ops cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4028 */;
	struct configfs_attribute *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 4023 */[];
	size_t cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3978 */;
	struct config_item *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3966 */;
	ssize_t cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3966 */;
	struct ibmvscsis_tport cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3938 */;
	struct se_wwn *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3899 */;
	struct config_group *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3881 */;
	struct target_fabric_configfs *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3880 */;
	struct ibmvscsis_cmd cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3872 */;
	struct ibmvscsis_cmd *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3872 */;
	struct se_cmd *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3870 */;
	void cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3870 */;
	struct se_node_acl *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3784 */;
	struct se_portal_group *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3717 */;
	const uint *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3656 */;
	const char *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3655 */;
	struct device_node *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3654 */;
	struct device_attribute *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3639 */;
	uint *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 357 */;
	char cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3442 */[24];
	const struct vio_device_id *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3437 */;
	volatile u8 cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3340 */;
	ulong cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3211 */;
	struct srp_target *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3207 */;
	unsigned int cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3204 */;
	struct srp_direct_buf *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3203 */;
	struct scatterlist *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3202 */;
	u32 *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3097 */;
	struct scsi_sense_hdr cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3063 */;
	struct srp_cmd *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3062 */;
	u8 cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3057 */;
	unsigned long cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3032 */;
	struct vio_dev *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 3014 */;
	irqreturn_t cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2960 */;
	void *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2960 */;
	struct timer_cb *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2936 */;
	struct timer_cb cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2921 */;
	enum hrtimer_restart cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2919 */;
	struct hrtimer *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2919 */;
	struct srp_tsk_mgmt *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2766 */;
	enum dma_data_direction cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2674 */;
	const __be32 *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2595 */;
	struct srp_i_logout *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2356 */;
	struct port_id *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2291 */;
	struct port_id {
		__be64 id_extension;
		__be64 io_guid;
	} *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2283 */;
	struct srp_login_req *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2282 */;
	struct ibmvscsis_nexus *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2248 */;
	struct se_session *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2247 */;
	struct ibmvscsis_tport *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2245 */;
	struct srp_login_rej *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2167 */;
	struct srp_login_rsp cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2112 */;
	struct format_code *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2108 */;
	struct srp_login_rsp *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2107 */;
	struct mad_common *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 2032 */;
	struct mad_common cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1994 */;
	ktime_t cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1771 */;
	struct viosrp_empty_iu *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1729 */;
	char *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1683 */;
	struct capabilities cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1628 */;
	u32 cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1619 */;
	u16 cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1618 */;
	struct mad_capability_common *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1616 */;
	struct capabilities *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1615 */;
	struct viosrp_capabilities *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1614 */;
	dma_addr_t cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1506 */;
	uint cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1505 */;
	struct mad_adapter_info_data *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1504 */;
	struct viosrp_adapter_info *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1503 */;
	struct iu_entry *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1501 */;
	int cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 1313 */;
	long cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 103 */;
	u64 cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 102 */[2];
	struct viosrp_crq *cocci_id/* drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c 101 */;
}
