cocci_test_suite() {
	void __exit cocci_id/* drivers/scsi/mvsas/mv_init.c 779 */;
	void cocci_id/* drivers/scsi/mvsas/mv_init.c 779 */;
	struct asd_sas_phy *cocci_id/* drivers/scsi/mvsas/mv_init.c 77 */;
	int __init cocci_id/* drivers/scsi/mvsas/mv_init.c 761 */;
	struct task_struct *cocci_id/* drivers/scsi/mvsas/mv_init.c 760 */;
	struct mvs_phy *cocci_id/* drivers/scsi/mvsas/mv_init.c 76 */;
	const char *cocci_id/* drivers/scsi/mvsas/mv_init.c 710 */;
	size_t cocci_id/* drivers/scsi/mvsas/mv_init.c 710 */;
	struct device_attribute *cocci_id/* drivers/scsi/mvsas/mv_init.c 697 */;
	char *cocci_id/* drivers/scsi/mvsas/mv_init.c 697 */;
	struct device *cocci_id/* drivers/scsi/mvsas/mv_init.c 696 */;
	ssize_t cocci_id/* drivers/scsi/mvsas/mv_init.c 695 */;
	struct pci_driver cocci_id/* drivers/scsi/mvsas/mv_init.c 688 */;
	struct pci_device_id cocci_id/* drivers/scsi/mvsas/mv_init.c 629 */[];
	unsigned short cocci_id/* drivers/scsi/mvsas/mv_init.c 601 */;
	struct hba_info_page cocci_id/* drivers/scsi/mvsas/mv_init.c 549 */;
	struct sas_domain_function_template cocci_id/* drivers/scsi/mvsas/mv_init.c 54 */;
	struct sas_ha_struct cocci_id/* drivers/scsi/mvsas/mv_init.c 525 */;
	const struct mvs_chip_info *cocci_id/* drivers/scsi/mvsas/mv_init.c 499 */;
	irq_handler_t cocci_id/* drivers/scsi/mvsas/mv_init.c 497 */;
	u64 *cocci_id/* drivers/scsi/mvsas/mv_init.c 486 */;
	u8 cocci_id/* drivers/scsi/mvsas/mv_init.c 482 */;
	u16 cocci_id/* drivers/scsi/mvsas/mv_init.c 474 */;
	struct mvs_prv_info cocci_id/* drivers/scsi/mvsas/mv_init.c 424 */;
	struct asd_sas_port **cocci_id/* drivers/scsi/mvsas/mv_init.c 407 */;
	struct asd_sas_phy **cocci_id/* drivers/scsi/mvsas/mv_init.c 406 */;
	struct mvs_slot_info cocci_id/* drivers/scsi/mvsas/mv_init.c 355 */;
	unsigned int cocci_id/* drivers/scsi/mvsas/mv_init.c 348 */;
	const struct pci_device_id *cocci_id/* drivers/scsi/mvsas/mv_init.c 347 */;
	void __iomem *cocci_id/* drivers/scsi/mvsas/mv_init.c 341 */;
	struct scsi_host_template cocci_id/* drivers/scsi/mvsas/mv_init.c 32 */;
	struct pci_dev *cocci_id/* drivers/scsi/mvsas/mv_init.c 299 */;
	unsigned long cocci_id/* drivers/scsi/mvsas/mv_init.c 298 */;
	struct device_attribute *cocci_id/* drivers/scsi/mvsas/mv_init.c 28 */[];
	char cocci_id/* drivers/scsi/mvsas/mv_init.c 215 */[32];
	struct mvs_info *cocci_id/* drivers/scsi/mvsas/mv_init.c 212 */;
	struct Scsi_Host *cocci_id/* drivers/scsi/mvsas/mv_init.c 212 */;
	struct mvs_prv_info *cocci_id/* drivers/scsi/mvsas/mv_init.c 184 */;
	struct sas_ha_struct *cocci_id/* drivers/scsi/mvsas/mv_init.c 179 */;
	u32 cocci_id/* drivers/scsi/mvsas/mv_init.c 176 */;
	irqreturn_t cocci_id/* drivers/scsi/mvsas/mv_init.c 174 */;
	void *cocci_id/* drivers/scsi/mvsas/mv_init.c 174 */;
	const struct mvs_chip_info cocci_id/* drivers/scsi/mvsas/mv_init.c 16 */[];
	struct scsi_transport_template *cocci_id/* drivers/scsi/mvsas/mv_init.c 15 */;
	int cocci_id/* drivers/scsi/mvsas/mv_init.c 13 */;
	struct mvs_wq *cocci_id/* drivers/scsi/mvsas/mv_init.c 100 */;
}
