cocci_test_suite() {
	struct aac_fib_xporthdr cocci_id/* drivers/scsi/aacraid/commsup.c 92 */;
	struct aac_fibhdr cocci_id/* drivers/scsi/aacraid/commsup.c 914 */;
	unsigned short cocci_id/* drivers/scsi/aacraid/commsup.c 870 */;
	size_t cocci_id/* drivers/scsi/aacraid/commsup.c 84 */;
	struct aac_queue *cocci_id/* drivers/scsi/aacraid/commsup.c 831 */;
	struct aac_entry **cocci_id/* drivers/scsi/aacraid/commsup.c 799 */;
	struct aac_hba_cmd_req *cocci_id/* drivers/scsi/aacraid/commsup.c 713 */;
	ulong cocci_id/* drivers/scsi/aacraid/commsup.c 576 */;
	struct aac_query_mount *cocci_id/* drivers/scsi/aacraid/commsup.c 573 */;
	fib_callback cocci_id/* drivers/scsi/aacraid/commsup.c 483 */;
	u16 cocci_id/* drivers/scsi/aacraid/commsup.c 482 */;
	struct aac_entry *cocci_id/* drivers/scsi/aacraid/commsup.c 422 */;
	u32 *cocci_id/* drivers/scsi/aacraid/commsup.c 358 */;
	unsigned long *cocci_id/* drivers/scsi/aacraid/commsup.c 358 */;
	struct timespec64 cocci_id/* drivers/scsi/aacraid/commsup.c 2498 */;
	unsigned cocci_id/* drivers/scsi/aacraid/commsup.c 2490 */;
	long cocci_id/* drivers/scsi/aacraid/commsup.c 2464 */;
	void *cocci_id/* drivers/scsi/aacraid/commsup.c 2458 */;
	struct timespec64 *cocci_id/* drivers/scsi/aacraid/commsup.c 2414 */;
	time64_t cocci_id/* drivers/scsi/aacraid/commsup.c 2390 */;
	char cocci_id/* drivers/scsi/aacraid/commsup.c 2388 */[];
	struct tm cocci_id/* drivers/scsi/aacraid/commsup.c 2387 */;
	struct aac_srb cocci_id/* drivers/scsi/aacraid/commsup.c 2359 */;
	struct sgmap64 *cocci_id/* drivers/scsi/aacraid/commsup.c 2315 */;
	struct aac_srb *cocci_id/* drivers/scsi/aacraid/commsup.c 2314 */;
	struct fib **cocci_id/* drivers/scsi/aacraid/commsup.c 2202 */;
	struct hw_fib **cocci_id/* drivers/scsi/aacraid/commsup.c 2201 */;
	unsigned int cocci_id/* drivers/scsi/aacraid/commsup.c 2200 */;
	spinlock_t *cocci_id/* drivers/scsi/aacraid/commsup.c 2192 */;
	struct aac_dev cocci_id/* drivers/scsi/aacraid/commsup.c 1974 */;
	struct work_struct *cocci_id/* drivers/scsi/aacraid/commsup.c 1971 */;
	struct aac_native_hba cocci_id/* drivers/scsi/aacraid/commsup.c 190 */;
	struct aac_hba_cmd_req cocci_id/* drivers/scsi/aacraid/commsup.c 184 */;
	struct fib cocci_id/* drivers/scsi/aacraid/commsup.c 1799 */;
	struct hw_fib cocci_id/* drivers/scsi/aacraid/commsup.c 1798 */;
	u32 cocci_id/* drivers/scsi/aacraid/commsup.c 1782 */;
	struct hw_fib *cocci_id/* drivers/scsi/aacraid/commsup.c 1770 */;
	struct aac_fib_context cocci_id/* drivers/scsi/aacraid/commsup.c 1769 */;
	struct aac_fib_context *cocci_id/* drivers/scsi/aacraid/commsup.c 1769 */;
	struct list_head *cocci_id/* drivers/scsi/aacraid/commsup.c 1734 */;
	struct aac_pause cocci_id/* drivers/scsi/aacraid/commsup.c 1713 */;
	struct aac_pause *cocci_id/* drivers/scsi/aacraid/commsup.c 1697 */;
	struct scatterlist *cocci_id/* drivers/scsi/aacraid/commsup.c 1616 */;
	void cocci_id/* drivers/scsi/aacraid/commsup.c 1595 */;
	unsigned char *cocci_id/* drivers/scsi/aacraid/commsup.c 156 */;
	unsigned long cocci_id/* drivers/scsi/aacraid/commsup.c 1535 */;
	bool cocci_id/* drivers/scsi/aacraid/commsup.c 1527 */;
	__le32 cocci_id/* drivers/scsi/aacraid/commsup.c 1526 */;
	struct fib *cocci_id/* drivers/scsi/aacraid/commsup.c 1525 */;
	u64 cocci_id/* drivers/scsi/aacraid/commsup.c 1485 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/aacraid/commsup.c 1481 */;
	struct scsi_device *cocci_id/* drivers/scsi/aacraid/commsup.c 1480 */;
	struct Scsi_Host *cocci_id/* drivers/scsi/aacraid/commsup.c 1479 */;
	u8 cocci_id/* drivers/scsi/aacraid/commsup.c 1475 */;
	struct aac_dev *cocci_id/* drivers/scsi/aacraid/commsup.c 1475 */;
	int cocci_id/* drivers/scsi/aacraid/commsup.c 1475 */;
	dma_addr_t cocci_id/* drivers/scsi/aacraid/commsup.c 136 */;
	enum{NOTHING, DELETE, ADD, CHANGE,} cocci_id/* drivers/scsi/aacraid/commsup.c 1068 */;
	__le32 *cocci_id/* drivers/scsi/aacraid/commsup.c 1028 */;
	uint32_t cocci_id/* drivers/scsi/aacraid/commsup.c 1026 */;
	struct aac_aifcmd *cocci_id/* drivers/scsi/aacraid/commsup.c 1026 */;
	char *cocci_id/* drivers/scsi/aacraid/commsup.c 1004 */;
}
