cocci_test_suite() {
	u8 cocci_id/* drivers/scsi/aacraid/linit.c 903 */;
	struct aac_native_hba *cocci_id/* drivers/scsi/aacraid/linit.c 863 */;
	struct aac_hba_resp *cocci_id/* drivers/scsi/aacraid/linit.c 862 */;
	struct aac_hba_reset_req *cocci_id/* drivers/scsi/aacraid/linit.c 843 */;
	struct scsi_lun *cocci_id/* drivers/scsi/aacraid/linit.c 827 */;
	const struct pci_device_id cocci_id/* drivers/scsi/aacraid/linit.c 79 */[];
	void *cocci_id/* drivers/scsi/aacraid/linit.c 733 */;
	fib_callback cocci_id/* drivers/scsi/aacraid/linit.c 732 */;
	char cocci_id/* drivers/scsi/aacraid/linit.c 71 */[];
	u8 *cocci_id/* drivers/scsi/aacraid/linit.c 702 */;
	u64 cocci_id/* drivers/scsi/aacraid/linit.c 693 */;
	struct aac_hba_tm_req *cocci_id/* drivers/scsi/aacraid/linit.c 691 */;
	struct scsi_cmnd *cocci_id/* drivers/scsi/aacraid/linit.c 675 */;
	unsigned char cocci_id/* drivers/scsi/aacraid/linit.c 581 */[16];
	struct Scsi_Host *cocci_id/* drivers/scsi/aacraid/linit.c 530 */;
	unsigned char cocci_id/* drivers/scsi/aacraid/linit.c 336 */;
	struct partition *cocci_id/* drivers/scsi/aacraid/linit.c 332 */;
	__le16 *cocci_id/* drivers/scsi/aacraid/linit.c 331 */;
	unsigned char *cocci_id/* drivers/scsi/aacraid/linit.c 300 */;
	struct diskparm *cocci_id/* drivers/scsi/aacraid/linit.c 299 */;
	sector_t cocci_id/* drivers/scsi/aacraid/linit.c 297 */;
	int *cocci_id/* drivers/scsi/aacraid/linit.c 297 */;
	struct scsi_device *cocci_id/* drivers/scsi/aacraid/linit.c 296 */;
	struct block_device *cocci_id/* drivers/scsi/aacraid/linit.c 296 */;
	struct aac_driver_ident *cocci_id/* drivers/scsi/aacraid/linit.c 269 */;
	const char *cocci_id/* drivers/scsi/aacraid/linit.c 256 */;
	void __exit cocci_id/* drivers/scsi/aacraid/linit.c 2141 */;
	int __init cocci_id/* drivers/scsi/aacraid/linit.c 2124 */;
	struct pci_driver cocci_id/* drivers/scsi/aacraid/linit.c 2111 */;
	struct pci_error_handlers cocci_id/* drivers/scsi/aacraid/linit.c 2104 */;
	enum pci_channel_state cocci_id/* drivers/scsi/aacraid/linit.c 2001 */;
	pci_ers_result_t cocci_id/* drivers/scsi/aacraid/linit.c 2000 */;
	struct pci_dev *cocci_id/* drivers/scsi/aacraid/linit.c 2000 */;
	pm_message_t cocci_id/* drivers/scsi/aacraid/linit.c 1891 */;
	unsigned long cocci_id/* drivers/scsi/aacraid/linit.c 1847 */;
	struct fib cocci_id/* drivers/scsi/aacraid/linit.c 1696 */;
	struct aac_dev cocci_id/* drivers/scsi/aacraid/linit.c 1671 */;
	struct list_head *cocci_id/* drivers/scsi/aacraid/linit.c 1614 */;
	const struct pci_device_id *cocci_id/* drivers/scsi/aacraid/linit.c 1609 */;
	struct aac_driver_ident cocci_id/* drivers/scsi/aacraid/linit.c 159 */[];
	struct fib *cocci_id/* drivers/scsi/aacraid/linit.c 1557 */;
	int cocci_id/* drivers/scsi/aacraid/linit.c 1547 */;
	struct aac_dev *cocci_id/* drivers/scsi/aacraid/linit.c 1545 */;
	void cocci_id/* drivers/scsi/aacraid/linit.c 1545 */;
	struct scsi_host_template cocci_id/* drivers/scsi/aacraid/linit.c 1512 */;
	const struct file_operations cocci_id/* drivers/scsi/aacraid/linit.c 1502 */;
	struct device *cocci_id/* drivers/scsi/aacraid/linit.c 1497 */;
	char *cocci_id/* drivers/scsi/aacraid/linit.c 1497 */;
	ssize_t cocci_id/* drivers/scsi/aacraid/linit.c 1497 */;
	struct device_attribute *cocci_id/* drivers/scsi/aacraid/linit.c 1482 */[];
	struct device_attribute cocci_id/* drivers/scsi/aacraid/linit.c 1438 */;
	size_t cocci_id/* drivers/scsi/aacraid/linit.c 1374 */;
	struct device_attribute *cocci_id/* drivers/scsi/aacraid/linit.c 1318 */;
	struct aac_supplement_adapter_info *cocci_id/* drivers/scsi/aacraid/linit.c 1246 */;
	u32 cocci_id/* drivers/scsi/aacraid/linit.c 1192 */;
	struct fib_ioctl cocci_id/* drivers/scsi/aacraid/linit.c 1192 */;
	struct fib_ioctl __user *cocci_id/* drivers/scsi/aacraid/linit.c 1186 */;
	void __user *cocci_id/* drivers/scsi/aacraid/linit.c 1163 */;
	unsigned int cocci_id/* drivers/scsi/aacraid/linit.c 1156 */;
	struct file *cocci_id/* drivers/scsi/aacraid/linit.c 1155 */;
	long cocci_id/* drivers/scsi/aacraid/linit.c 1155 */;
	unsigned cocci_id/* drivers/scsi/aacraid/linit.c 1125 */;
	struct inode *cocci_id/* drivers/scsi/aacraid/linit.c 1122 */;
	bool cocci_id/* drivers/scsi/aacraid/linit.c 1069 */;
	__le32 cocci_id/* drivers/scsi/aacraid/linit.c 1068 */;
	struct aac_hba_map_info *cocci_id/* drivers/scsi/aacraid/linit.c 1027 */;
}
