cocci_test_suite() {
	u32 cocci_id/* drivers/memstick/core/ms_block.c 997 */;
	struct sg_mapping_iter cocci_id/* drivers/memstick/core/ms_block.c 862 */;
	int cocci_id/* drivers/memstick/core/ms_block.c 718 */(struct msb_data *msb);
	unsigned char *cocci_id/* drivers/memstick/core/ms_block.c 697 */;
	struct ms_register cocci_id/* drivers/memstick/core/ms_block.c 695 */;
	struct memstick_host *cocci_id/* drivers/memstick/core/ms_block.c 681 */;
	struct memstick_request *cocci_id/* drivers/memstick/core/ms_block.c 680 */;
	struct msb_data *cocci_id/* drivers/memstick/core/ms_block.c 679 */;
	struct ms_extra_data_register *cocci_id/* drivers/memstick/core/ms_block.c 419 */;
	struct ms_extra_data_register cocci_id/* drivers/memstick/core/ms_block.c 411 */;
	struct ms_status_register *cocci_id/* drivers/memstick/core/ms_block.c 404 */;
	struct ms_status_register cocci_id/* drivers/memstick/core/ms_block.c 397 */;
	struct ms_param_register cocci_id/* drivers/memstick/core/ms_block.c 355 */;
	u8 cocci_id/* drivers/memstick/core/ms_block.c 341 */;
	struct scatterlist cocci_id/* drivers/memstick/core/ms_block.c 340 */[2];
	struct memstick_request **cocci_id/* drivers/memstick/core/ms_block.c 325 */;
	struct memstick_dev *cocci_id/* drivers/memstick/core/ms_block.c 324 */;
	void *cocci_id/* drivers/memstick/core/ms_block.c 303 */;
	int cocci_id/* drivers/memstick/core/ms_block.c 29 */;
	long cocci_id/* drivers/memstick/core/ms_block.c 255 */;
	void __exit cocci_id/* drivers/memstick/core/ms_block.c 2342 */;
	int __init cocci_id/* drivers/memstick/core/ms_block.c 2333 */;
	struct memstick_driver cocci_id/* drivers/memstick/core/ms_block.c 2321 */;
	struct memstick_device_id cocci_id/* drivers/memstick/core/ms_block.c 2301 */[];
	pm_message_t cocci_id/* drivers/memstick/core/ms_block.c 2230 */;
	int (*cocci_id/* drivers/memstick/core/ms_block.c 217 */)(struct memstick_dev *card,
								  struct memstick_request **req);
	unsigned long cocci_id/* drivers/memstick/core/ms_block.c 2104 */;
	struct ms_id_register cocci_id/* drivers/memstick/core/ms_block.c 210 */;
	const struct blk_mq_ops cocci_id/* drivers/memstick/core/ms_block.c 2095 */;
	const struct block_device_operations cocci_id/* drivers/memstick/core/ms_block.c 2088 */;
	const struct blk_mq_queue_data *cocci_id/* drivers/memstick/core/ms_block.c 1998 */;
	struct blk_mq_hw_ctx *cocci_id/* drivers/memstick/core/ms_block.c 1997 */;
	struct hd_geometry *cocci_id/* drivers/memstick/core/ms_block.c 1990 */;
	struct block_device *cocci_id/* drivers/memstick/core/ms_block.c 1989 */;
	void cocci_id/* drivers/memstick/core/ms_block.c 1984 */;
	struct gendisk *cocci_id/* drivers/memstick/core/ms_block.c 1939 */;
	fmode_t cocci_id/* drivers/memstick/core/ms_block.c 1937 */;
	blk_status_t cocci_id/* drivers/memstick/core/ms_block.c 1920 */;
	struct request *cocci_id/* drivers/memstick/core/ms_block.c 1873 */;
	sector_t cocci_id/* drivers/memstick/core/ms_block.c 1871 */;
	struct msb_data cocci_id/* drivers/memstick/core/ms_block.c 1869 */;
	struct work_struct *cocci_id/* drivers/memstick/core/ms_block.c 1867 */;
	int *cocci_id/* drivers/memstick/core/ms_block.c 1843 */;
	off_t cocci_id/* drivers/memstick/core/ms_block.c 1806 */;
	size_t cocci_id/* drivers/memstick/core/ms_block.c 1803 */;
	struct ms_boot_page cocci_id/* drivers/memstick/core/ms_block.c 1714 */;
	const struct chs_entry cocci_id/* drivers/memstick/core/ms_block.c 1678 */[];
	struct scatterlist cocci_id/* drivers/memstick/core/ms_block.c 1644 */[10];
	struct scatterlist *cocci_id/* drivers/memstick/core/ms_block.c 1641 */;
	bool cocci_id/* drivers/memstick/core/ms_block.c 1600 */;
	u16 cocci_id/* drivers/memstick/core/ms_block.c 1531 */;
	struct scatterlist cocci_id/* drivers/memstick/core/ms_block.c 1528 */;
	struct timer_list *cocci_id/* drivers/memstick/core/ms_block.c 1493 */;
	u8 *cocci_id/* drivers/memstick/core/ms_block.c 1371 */;
	u16 *cocci_id/* drivers/memstick/core/ms_block.c 1253 */;
	struct ms_boot_page *cocci_id/* drivers/memstick/core/ms_block.c 1160 */;
}
