cocci_test_suite() {
	resource_size_t cocci_id/* drivers/pci/pci-sysfs.c 990 */;
	enum pci_mmap_api cocci_id/* drivers/pci/pci-sysfs.c 987 */;
	struct vm_area_struct *cocci_id/* drivers/pci/pci-sysfs.c 986 */;
	struct bin_attribute cocci_id/* drivers/pci/pci-sysfs.c 934 */;
	void cocci_id/* drivers/pci/pci-sysfs.c 930 */;
	enum pci_mmap_state cocci_id/* drivers/pci/pci-sysfs.c 915 */;
	void __weak cocci_id/* drivers/pci/pci-sysfs.c 914 */;
	struct file *cocci_id/* drivers/pci/pci-sysfs.c 898 */;
	u32 *cocci_id/* drivers/pci/pci-sysfs.c 839 */;
	bool cocci_id/* drivers/pci/pci-sysfs.c 78 */;
	u32 cocci_id/* drivers/pci/pci-sysfs.c 718 */;
	u8 *cocci_id/* drivers/pci/pci-sysfs.c 681 */;
	unsigned int cocci_id/* drivers/pci/pci-sysfs.c 679 */;
	loff_t cocci_id/* drivers/pci/pci-sysfs.c 676 */;
	unsigned long cocci_id/* drivers/pci/pci-sysfs.c 67 */;
	const char *cocci_id/* drivers/pci/pci-sysfs.c 64 */;
	size_t cocci_id/* drivers/pci/pci-sysfs.c 64 */;
	struct attribute *cocci_id/* drivers/pci/pci-sysfs.c 629 */[];
	struct device_node *cocci_id/* drivers/pci/pci-sysfs.c 542 */;
	struct pci_bus *cocci_id/* drivers/pci/pci-sysfs.c 489 */;
	const struct attribute_group *cocci_id/* drivers/pci/pci-sysfs.c 445 */[];
	struct bus_type *cocci_id/* drivers/pci/pci-sysfs.c 418 */;
	u8 cocci_id/* drivers/pci/pci-sysfs.c 274 */;
	struct pci_dev *cocci_id/* drivers/pci/pci-sysfs.c 260 */;
	char *cocci_id/* drivers/pci/pci-sysfs.c 258 */;
	struct device_attribute *cocci_id/* drivers/pci/pci-sysfs.c 257 */;
	struct device *cocci_id/* drivers/pci/pci-sysfs.c 256 */;
	ssize_t cocci_id/* drivers/pci/pci-sysfs.c 256 */;
	int cocci_id/* drivers/pci/pci-sysfs.c 177 */;
	u16 cocci_id/* drivers/pci/pci-sysfs.c 176 */;
	const struct device_type cocci_id/* drivers/pci/pci-sysfs.c 1576 */;
	const struct attribute_group cocci_id/* drivers/pci/pci-sysfs.c 1549 */;
	struct attribute *cocci_id/* drivers/pci/pci-sysfs.c 1507 */;
	umode_t cocci_id/* drivers/pci/pci-sysfs.c 1506 */;
	struct kobject *cocci_id/* drivers/pci/pci-sysfs.c 1506 */;
	unsigned long long cocci_id/* drivers/pci/pci-sysfs.c 146 */;
	int __init cocci_id/* drivers/pci/pci-sysfs.c 1452 */;
	int __must_check cocci_id/* drivers/pci/pci-sysfs.c 1346 */;
	const struct bin_attribute cocci_id/* drivers/pci/pci-sysfs.c 1284 */;
	void __iomem *cocci_id/* drivers/pci/pci-sysfs.c 1261 */;
	int __weak cocci_id/* drivers/pci/pci-sysfs.c 1215 */;
	void *cocci_id/* drivers/pci/pci-sysfs.c 1176 */;
	struct bin_attribute *cocci_id/* drivers/pci/pci-sysfs.c 1146 */;
	const struct cpumask *cocci_id/* drivers/pci/pci-sysfs.c 112 */;
	u16 *cocci_id/* drivers/pci/pci-sysfs.c 1080 */;
	struct resource *cocci_id/* drivers/pci/pci-sysfs.c 1023 */;
}
