cocci_test_suite() {
	__le16 *cocci_id/* drivers/ide/ide-proc.c 93 */;
	u8 *cocci_id/* drivers/ide/ide-proc.c 82 */;
	ide_hwif_t *cocci_id/* drivers/ide/ide-proc.c 73 */;
	struct device_driver *cocci_id/* drivers/ide/ide-proc.c 597 */;
	char cocci_id/* drivers/ide/ide-proc.c 538 */[64];
	ide_proc_entry_t *cocci_id/* drivers/ide/ide-proc.c 474 */;
	struct proc_dir_entry *cocci_id/* drivers/ide/ide-proc.c 474 */;
	void *cocci_id/* drivers/ide/ide-proc.c 474 */;
	void cocci_id/* drivers/ide/ide-proc.c 474 */;
	ide_proc_entry_t cocci_id/* drivers/ide/ide-proc.c 466 */[];
	const struct file_operations cocci_id/* drivers/ide/ide-proc.c 458 */;
	struct inode *cocci_id/* drivers/ide/ide-proc.c 453 */;
	struct file *cocci_id/* drivers/ide/ide-proc.c 453 */;
	struct ide_driver *cocci_id/* drivers/ide/ide-proc.c 425 */;
	struct device *cocci_id/* drivers/ide/ide-proc.c 424 */;
	char *cocci_id/* drivers/ide/ide-proc.c 415 */;
	ide_drive_t *cocci_id/* drivers/ide/ide-proc.c 414 */;
	long long cocci_id/* drivers/ide/ide-proc.c 395 */;
	struct seq_file *cocci_id/* drivers/ide/ide-proc.c 393 */;
	int cocci_id/* drivers/ide/ide-proc.c 393 */;
	const char *cocci_id/* drivers/ide/ide-proc.c 38 */;
	unsigned cocci_id/* drivers/ide/ide-proc.c 327 */;
	unsigned long cocci_id/* drivers/ide/ide-proc.c 288 */;
	char cocci_id/* drivers/ide/ide-proc.c 286 */[MAX_LEN + 1];
	loff_t *cocci_id/* drivers/ide/ide-proc.c 283 */;
	size_t cocci_id/* drivers/ide/ide-proc.c 283 */;
	const char __user *cocci_id/* drivers/ide/ide-proc.c 282 */;
	ssize_t cocci_id/* drivers/ide/ide-proc.c 282 */;
	const struct ide_proc_devset cocci_id/* drivers/ide/ide-proc.c 211 */[];
	u8 cocci_id/* drivers/ide/ide-proc.c 198 */;
	struct ide_cmd cocci_id/* drivers/ide/ide-proc.c 190 */;
	const struct ide_devset *cocci_id/* drivers/ide/ide-proc.c 144 */;
	const struct ide_proc_devset *cocci_id/* drivers/ide/ide-proc.c 117 */;
}
