cocci_test_suite() {
	struct platform_driver cocci_id/* drivers/video/fbdev/metronomefb.c 767 */;
	void __force *cocci_id/* drivers/video/fbdev/metronomefb.c 759 */;
	char __force __iomem *cocci_id/* drivers/video/fbdev/metronomefb.c 637 */;
	struct metronomefb_par cocci_id/* drivers/video/fbdev/metronomefb.c 597 */;
	const struct firmware *cocci_id/* drivers/video/fbdev/metronomefb.c 582 */;
	struct metronome_board *cocci_id/* drivers/video/fbdev/metronomefb.c 577 */;
	struct platform_device *cocci_id/* drivers/video/fbdev/metronomefb.c 574 */;
	struct fb_deferred_io cocci_id/* drivers/video/fbdev/metronomefb.c 569 */;
	struct fb_ops cocci_id/* drivers/video/fbdev/metronomefb.c 561 */;
	struct epd_frame cocci_id/* drivers/video/fbdev/metronomefb.c 56 */[];
	void *cocci_id/* drivers/video/fbdev/metronomefb.c 524 */;
	unsigned long cocci_id/* drivers/video/fbdev/metronomefb.c 523 */;
	loff_t *cocci_id/* drivers/video/fbdev/metronomefb.c 520 */;
	const char __user *cocci_id/* drivers/video/fbdev/metronomefb.c 519 */;
	ssize_t cocci_id/* drivers/video/fbdev/metronomefb.c 519 */;
	const struct fb_image *cocci_id/* drivers/video/fbdev/metronomefb.c 507 */;
	const struct fb_copyarea *cocci_id/* drivers/video/fbdev/metronomefb.c 498 */;
	struct fb_info *cocci_id/* drivers/video/fbdev/metronomefb.c 497 */;
	void cocci_id/* drivers/video/fbdev/metronomefb.c 497 */;
	struct epd_frame {
		int fw;
		int fh;
		u16 config[4];
		int wfm_size;
	} cocci_id/* drivers/video/fbdev/metronomefb.c 49 */;
	const struct fb_fillrect *cocci_id/* drivers/video/fbdev/metronomefb.c 489 */;
	struct fb_deferred_io *cocci_id/* drivers/video/fbdev/metronomefb.c 473 */;
	struct page *cocci_id/* drivers/video/fbdev/metronomefb.c 472 */;
	struct list_head *cocci_id/* drivers/video/fbdev/metronomefb.c 469 */;
	u16 __force *cocci_id/* drivers/video/fbdev/metronomefb.c 456 */;
	unsigned char __force *cocci_id/* drivers/video/fbdev/metronomefb.c 441 */;
	unsigned char *cocci_id/* drivers/video/fbdev/metronomefb.c 441 */;
	struct device *cocci_id/* drivers/video/fbdev/metronomefb.c 184 */;
	struct waveform_hdr *cocci_id/* drivers/video/fbdev/metronomefb.c 182 */;
	unsigned char cocci_id/* drivers/video/fbdev/metronomefb.c 177 */;
	struct metronomefb_par *cocci_id/* drivers/video/fbdev/metronomefb.c 171 */;
	size_t cocci_id/* drivers/video/fbdev/metronomefb.c 170 */;
	u16 cocci_id/* drivers/video/fbdev/metronomefb.c 159 */;
	u16 *cocci_id/* drivers/video/fbdev/metronomefb.c 159 */;
	u8 cocci_id/* drivers/video/fbdev/metronomefb.c 148 */;
	u8 *cocci_id/* drivers/video/fbdev/metronomefb.c 148 */;
	int cocci_id/* drivers/video/fbdev/metronomefb.c 148 */;
	struct waveform_hdr {
		u8 stuff[32];
		u8 wmta[3];
		u8 fvsn;
		u8 luts;
		u8 mc;
		u8 trc;
		u8 stuff3;
		u8 endb;
		u8 swtb;
		u8 stuff2a[2];
		u8 stuff2b[3];
		u8 wfm_cs;
	}__attribute__((packed)) cocci_id/* drivers/video/fbdev/metronomefb.c 128 */;
	struct fb_var_screeninfo cocci_id/* drivers/video/fbdev/metronomefb.c 113 */;
	struct fb_fix_screeninfo cocci_id/* drivers/video/fbdev/metronomefb.c 102 */;
}
