cocci_test_suite() {
	struct omap_overlay_info cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 967 */;
	struct omap_overlay *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 931 */;
	const short cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 92 */;
	u32 __iomem *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 83 */;
	const struct fb_fix_screeninfo *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 761 */;
	const struct fb_var_screeninfo *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 760 */;
	unsigned cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 760 */;
	u8 __iomem *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 76 */;
	struct omap_video_timings cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 711 */;
	u16 __iomem *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 67 */;
	enum omap_color_mode cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 658 */;
	struct omap_dss_device *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 657 */;
	struct omapfb_info *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 656 */;
	char __iomem *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 600 */;
	const unsigned cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 59 */;
	void __iomem *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 58 */;
	struct fb_fix_screeninfo *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 57 */;
	int cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 50 */(struct omapfb2_device *fbdev,
									    struct omap_dss_device *dssdev);
	struct vrfb *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 494 */;
	int cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 49 */(struct omapfb2_device *fbdev,
									    struct fb_info *fbi);
	unsigned long cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 446 */;
	const struct omapfb_info *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 443 */;
	unsigned int cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 38 */;
	bool cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 37 */;
	char *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 32 */;
	enum omap_color_mode *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 300 */;
	struct omapfb_colormode *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 289 */;
	void cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 288 */;
	struct fb_bitfield *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 265 */;
	struct platform_driver cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2622 */;
	struct omapfb2_device cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2473 */;
	struct platform_device *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2454 */;
	const char *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2408 */;
	struct omap_overlay_manager *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2361 */;
	u8 *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2237 */;
	struct fb_monspecs *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2236 */;
	struct omap_video_timings *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2205 */;
	struct fb_videomode *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2203 */;
	u8 cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2107 */;
	struct omapfb_colormode cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 204 */[];
	struct fb_ops *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 2008 */;
	struct omapfb_info cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1882 */;
	struct omapfb2_device *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1811 */;
	struct workqueue_struct *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1696 */;
	struct omapfb_display_data cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1667 */;
	struct omapfb_display_data *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1662 */;
	struct omap_dss_driver *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1661 */;
	struct work_struct *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1658 */;
	const struct fb_fillrect cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1572 */;
	unsigned long cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1529 */[10];
	const struct vrfb *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 152 */;
	unsigned long *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1468 */;
	u16 cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1446 */;
	dma_addr_t cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1364 */;
	void *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1362 */;
	struct fb_ops cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1283 */;
	u16 *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1194 */;
	struct fb_cmap *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1191 */;
	u32 *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1174 */;
	u32 cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1168 */;
	enum omapfb_color_format cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1139 */;
	struct fb_var_screeninfo *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1136 */;
	u_int cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1131 */;
	struct fb_info *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1131 */;
	int cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1131 */;
	const struct vm_operations_struct cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1084 */;
	struct omapfb2_mem_region *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1077 */;
	struct vm_area_struct *cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1075 */;
	struct fb_var_screeninfo cocci_id/* drivers/video/fbdev/omap2/omapfb/omapfb-main.c 1042 */;
}
