cocci_test_suite() {
	struct uvesafb_pal_entry cocci_id/* drivers/video/fbdev/uvesafb.c 991 */;
	unsigned cocci_id/* drivers/video/fbdev/uvesafb.c 987 */;
	struct fb_modelist cocci_id/* drivers/video/fbdev/uvesafb.c 867 */;
	struct fb_modelist *cocci_id/* drivers/video/fbdev/uvesafb.c 828 */;
	struct list_head *cocci_id/* drivers/video/fbdev/uvesafb.c 827 */;
	struct uvesafb_task *cocci_id/* drivers/video/fbdev/uvesafb.c 74 */;
	struct fb_videomode cocci_id/* drivers/video/fbdev/uvesafb.c 724 */;
	struct fb_var_screeninfo cocci_id/* drivers/video/fbdev/uvesafb.c 722 */;
	struct netlink_skb_parms *cocci_id/* drivers/video/fbdev/uvesafb.c 72 */;
	struct cn_msg *cocci_id/* drivers/video/fbdev/uvesafb.c 72 */;
	struct uvesafb_ktask *cocci_id/* drivers/video/fbdev/uvesafb.c 62 */[UVESAFB_TASKS_MAX];
	u8 cocci_id/* drivers/video/fbdev/uvesafb.c 60 */;
	struct fb_videomode *cocci_id/* drivers/video/fbdev/uvesafb.c 597 */;
	char *cocci_id/* drivers/video/fbdev/uvesafb.c 59 */;
	u16 cocci_id/* drivers/video/fbdev/uvesafb.c 55 */;
	struct vbe_mode_ib cocci_id/* drivers/video/fbdev/uvesafb.c 491 */;
	bool cocci_id/* drivers/video/fbdev/uvesafb.c 48 */;
	u16 *cocci_id/* drivers/video/fbdev/uvesafb.c 479 */;
	int cocci_id/* drivers/video/fbdev/uvesafb.c 47 */;
	struct vbe_ib cocci_id/* drivers/video/fbdev/uvesafb.c 424 */;
	const struct fb_fix_screeninfo cocci_id/* drivers/video/fbdev/uvesafb.c 40 */;
	char cocci_id/* drivers/video/fbdev/uvesafb.c 38 */;
	char cocci_id/* drivers/video/fbdev/uvesafb.c 37 */[PATH_MAX];
	struct cb_id cocci_id/* drivers/video/fbdev/uvesafb.c 33 */;
	unsigned char cocci_id/* drivers/video/fbdev/uvesafb.c 316 */;
	struct completion *cocci_id/* drivers/video/fbdev/uvesafb.c 248 */;
	void cocci_id/* drivers/video/fbdev/uvesafb.c 1961 */;
	const struct kernel_param_ops cocci_id/* drivers/video/fbdev/uvesafb.c 1958 */;
	const struct kernel_param *cocci_id/* drivers/video/fbdev/uvesafb.c 1943 */;
	const char *cocci_id/* drivers/video/fbdev/uvesafb.c 1943 */;
	struct device_driver *cocci_id/* drivers/video/fbdev/uvesafb.c 1866 */;
	struct platform_device *cocci_id/* drivers/video/fbdev/uvesafb.c 1807 */;
	struct platform_driver cocci_id/* drivers/video/fbdev/uvesafb.c 1799 */;
	u8 *cocci_id/* drivers/video/fbdev/uvesafb.c 176 */;
	u32 cocci_id/* drivers/video/fbdev/uvesafb.c 1684 */;
	const struct attribute_group cocci_id/* drivers/video/fbdev/uvesafb.c 1672 */;
	struct attribute *cocci_id/* drivers/video/fbdev/uvesafb.c 1661 */[];
	size_t cocci_id/* drivers/video/fbdev/uvesafb.c 1644 */;
	struct device_attribute *cocci_id/* drivers/video/fbdev/uvesafb.c 1635 */;
	struct device *cocci_id/* drivers/video/fbdev/uvesafb.c 1634 */;
	ssize_t cocci_id/* drivers/video/fbdev/uvesafb.c 1634 */;
	struct uvesafb_par cocci_id/* drivers/video/fbdev/uvesafb.c 1436 */;
	unsigned int cocci_id/* drivers/video/fbdev/uvesafb.c 1430 */;
	struct fb_ops cocci_id/* drivers/video/fbdev/uvesafb.c 1413 */;
	struct vbe_mode_ib *cocci_id/* drivers/video/fbdev/uvesafb.c 1367 */;
	const struct fb_videomode *cocci_id/* drivers/video/fbdev/uvesafb.c 1330 */;
	struct fb_var_screeninfo *cocci_id/* drivers/video/fbdev/uvesafb.c 1327 */;
	struct vbe_crtc_ib cocci_id/* drivers/video/fbdev/uvesafb.c 1244 */;
	struct vbe_crtc_ib *cocci_id/* drivers/video/fbdev/uvesafb.c 1218 */;
	char *cocci_id/* drivers/video/fbdev/uvesafb.c 114 */[];
	struct uvesafb_par *cocci_id/* drivers/video/fbdev/uvesafb.c 1109 */;
	struct uvesafb_ktask *cocci_id/* drivers/video/fbdev/uvesafb.c 1106 */;
	struct fb_info *cocci_id/* drivers/video/fbdev/uvesafb.c 1104 */;
	struct uvesafb_pal_entry *cocci_id/* drivers/video/fbdev/uvesafb.c 1040 */;
	struct fb_cmap *cocci_id/* drivers/video/fbdev/uvesafb.c 1038 */;
	u32 *cocci_id/* drivers/video/fbdev/uvesafb.c 1010 */;
}
