cocci_test_suite() {
	irqreturn_t cocci_id/* drivers/video/fbdev/da8xx-fb.c 883 */;
	struct fb_videomode *cocci_id/* drivers/video/fbdev/da8xx-fb.c 750 */;
	unsigned *cocci_id/* drivers/video/fbdev/da8xx-fb.c 726 */;
	unsigned cocci_id/* drivers/video/fbdev/da8xx-fb.c 725 */;
	unsigned int cocci_id/* drivers/video/fbdev/da8xx-fb.c 724 */;
	u32 *cocci_id/* drivers/video/fbdev/da8xx-fb.c 667 */;
	u32 cocci_id/* drivers/video/fbdev/da8xx-fb.c 658 */;
	u_short cocci_id/* drivers/video/fbdev/da8xx-fb.c 598 */;
	unsigned short *cocci_id/* drivers/video/fbdev/da8xx-fb.c 597 */;
	const struct lcd_ctrl_config *cocci_id/* drivers/video/fbdev/da8xx-fb.c 443 */;
	enum da8xx_frame_complete cocci_id/* drivers/video/fbdev/da8xx-fb.c 276 */;
	bool cocci_id/* drivers/video/fbdev/da8xx-fb.c 248 */;
	void cocci_id/* drivers/video/fbdev/da8xx-fb.c 248 */;
	struct fb_videomode cocci_id/* drivers/video/fbdev/da8xx-fb.c 187 */[];
	struct fb_fix_screeninfo cocci_id/* drivers/video/fbdev/da8xx-fb.c 176 */;
	struct fb_var_screeninfo cocci_id/* drivers/video/fbdev/da8xx-fb.c 174 */;
	struct platform_driver cocci_id/* drivers/video/fbdev/da8xx-fb.c 1655 */;
	struct device *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1627 */;
	struct lcdc_context {
		u32 clk_enable;
		u32 ctrl;
		u32 dma_ctrl;
		u32 raster_timing_0;
		u32 raster_timing_1;
		u32 raster_timing_2;
		u32 int_enable_set;
		u32 dma_frm_buf_base_addr_0;
		u32 dma_frm_buf_ceiling_addr_0;
		u32 dma_frm_buf_base_addr_1;
		u32 dma_frm_buf_ceiling_addr_1;
		u32 raster_ctrl;
	} cocci_id/* drivers/video/fbdev/da8xx-fb.c 1543 */;
	char __iomem *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1437 */;
	struct da8xx_fb_par {
		struct device *dev;
		dma_addr_t p_palette_base;
		unsigned char *v_palette_base;
		dma_addr_t vram_phys;
		unsigned long vram_size;
		void *vram_virt;
		unsigned int dma_start;
		unsigned int dma_end;
		struct clk *lcdc_clk;
		int irq;
		unsigned int palette_sz;
		int blank;
		wait_queue_head_t vsync_wait;
		int vsync_flag;
		int vsync_timeout;
		spinlock_t lock_for_chan_update;
		unsigned int which_dma_channel_done;
#ifdef CONFIG_CPU_FREQ
		struct notifier_block freq_transition;
#endif
		unsigned int lcdc_clk_rate;
		struct regulator *lcd_supply;
		u32 pseudo_palette[16];
		struct fb_videomode mode;
		struct lcd_ctrl_config cfg;
	} cocci_id/* drivers/video/fbdev/da8xx-fb.c 141 */;
	struct da8xx_fb_par cocci_id/* drivers/video/fbdev/da8xx-fb.c 1389 */;
	struct clk *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1339 */;
	struct lcd_ctrl_config *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1335 */;
	struct da8xx_lcdc_platform_data *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1312 */;
	struct platform_device *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1310 */;
	struct fb_ops cocci_id/* drivers/video/fbdev/da8xx-fb.c 1297 */;
	wait_queue_head_t cocci_id/* drivers/video/fbdev/da8xx-fb.c 128 */;
	irq_handler_t cocci_id/* drivers/video/fbdev/da8xx-fb.c 127 */;
	void __iomem *cocci_id/* drivers/video/fbdev/da8xx-fb.c 125 */;
	unsigned long cocci_id/* drivers/video/fbdev/da8xx-fb.c 1218 */;
	struct fb_fix_screeninfo *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1215 */;
	struct fb_var_screeninfo *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1209 */;
	struct da8xx_fb_par *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1169 */;
	struct fb_info *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1167 */;
	int cocci_id/* drivers/video/fbdev/da8xx-fb.c 1167 */;
	char *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1144 */;
	struct lcd_sync_arg cocci_id/* drivers/video/fbdev/da8xx-fb.c 1133 */;
	void *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1034 */;
	struct notifier_block *cocci_id/* drivers/video/fbdev/da8xx-fb.c 1033 */;
}
