cocci_test_suite() {
	struct perf_thread *cocci_id/* drivers/ntb/test/ntb_perf.c 969 */;
	dma_cap_mask_t cocci_id/* drivers/ntb/test/ntb_perf.c 867 */;
	bool cocci_id/* drivers/ntb/test/ntb_perf.c 854 */;
	struct dma_chan *cocci_id/* drivers/ntb/test/ntb_perf.c 854 */;
	struct device *cocci_id/* drivers/ntb/test/ntb_perf.c 783 */;
	struct dmaengine_unmap_data *cocci_id/* drivers/ntb/test/ntb_perf.c 782 */;
	struct dma_async_tx_descriptor *cocci_id/* drivers/ntb/test/ntb_perf.c 781 */;
	void __iomem *cocci_id/* drivers/ntb/test/ntb_perf.c 779 */;
	void *cocci_id/* drivers/ntb/test/ntb_perf.c 779 */;
	size_t cocci_id/* drivers/ntb/test/ntb_perf.c 779 */;
	struct work_struct *cocci_id/* drivers/ntb/test/ntb_perf.c 622 */;
	resource_size_t cocci_id/* drivers/ntb/test/ntb_perf.c 566 */;
	const struct ntb_ctx_ops cocci_id/* drivers/ntb/test/ntb_perf.c 523 */;
	u64 cocci_id/* drivers/ntb/test/ntb_perf.c 457 */;
	enum perf_cmd cocci_id/* drivers/ntb/test/ntb_perf.c 429 */;
	struct perf_peer *cocci_id/* drivers/ntb/test/ntb_perf.c 429 */;
	int cocci_id/* drivers/ntb/test/ntb_perf.c 429 */;
	u32 cocci_id/* drivers/ntb/test/ntb_perf.c 394 */;
	u64 *cocci_id/* drivers/ntb/test/ntb_perf.c 391 */;
	enum perf_cmd *cocci_id/* drivers/ntb/test/ntb_perf.c 391 */;
	int *cocci_id/* drivers/ntb/test/ntb_perf.c 390 */;
	void cocci_id/* drivers/ntb/test/ntb_perf.c 244 */(struct perf_ctx *perf);
	struct workqueue_struct *cocci_id/* drivers/ntb/test/ntb_perf.c 237 */;
	struct dentry *cocci_id/* drivers/ntb/test/ntb_perf.c 235 */;
	struct perf_ctx {
		struct ntb_dev *ntb;
		int gidx;
		int pcnt;
		struct perf_peer *peers;
		unsigned long busy_flag;
		wait_queue_head_t twait;
		atomic_t tsync;
		u8 tcnt;
		struct perf_peer *test_peer;
		struct perf_thread threads[MAX_THREADS_CNT];
		int (*cmd_send)(struct perf_peer *peer, enum perf_cmd cmd,
				u64 data);
		int (*cmd_recv)(struct perf_ctx *perf, int *pidx,
				enum perf_cmd *cmd, u64 *data);
		struct dentry *dbgfs_dir;
	} cocci_id/* drivers/ntb/test/ntb_perf.c 184 */;
	struct perf_thread cocci_id/* drivers/ntb/test/ntb_perf.c 182 */;
	struct perf_thread {
		struct perf_ctx *perf;
		int tidx;
		atomic_t dma_sync;
		wait_queue_head_t dma_wait;
		struct dma_chan *dma_chan;
		void *src;
		u64 copied;
		ktime_t duration;
		int status;
		struct work_struct work;
	} cocci_id/* drivers/ntb/test/ntb_perf.c 165 */;
	struct perf_peer cocci_id/* drivers/ntb/test/ntb_perf.c 163 */;
	void __exit cocci_id/* drivers/ntb/test/ntb_perf.c 1513 */;
	int __init cocci_id/* drivers/ntb/test/ntb_perf.c 1482 */;
	struct ntb_client cocci_id/* drivers/ntb/test/ntb_perf.c 1475 */;
	struct ntb_client *cocci_id/* drivers/ntb/test/ntb_perf.c 1436 */;
	struct perf_peer {
		struct perf_ctx *perf;
		int pidx;
		int gidx;
		u64 outbuf_xlat;
		resource_size_t outbuf_size;
		void __iomem *outbuf;
		dma_addr_t inbuf_xlat;
		resource_size_t inbuf_size;
		void *inbuf;
		struct work_struct service;
		unsigned long sts;
	} cocci_id/* drivers/ntb/test/ntb_perf.c 143 */;
	struct perf_ctx cocci_id/* drivers/ntb/test/ntb_perf.c 141 */;
	phys_addr_t cocci_id/* drivers/ntb/test/ntb_perf.c 1377 */;
	struct ntb_dev *cocci_id/* drivers/ntb/test/ntb_perf.c 1355 */;
	struct perf_ctx *cocci_id/* drivers/ntb/test/ntb_perf.c 1345 */;
	void cocci_id/* drivers/ntb/test/ntb_perf.c 1345 */;
	struct pci_dev *cocci_id/* drivers/ntb/test/ntb_perf.c 1320 */;
	enum perf_cmd{PERF_CMD_INVAL=-1, PERF_CMD_SSIZE=0, PERF_CMD_RSIZE=1, PERF_CMD_SXLAT=2, PERF_CMD_RXLAT=3, PERF_CMD_CLEAR=4, PERF_STS_DONE=5, PERF_STS_LNKUP=6,} cocci_id/* drivers/ntb/test/ntb_perf.c 130 */;
	u8 cocci_id/* drivers/ntb/test/ntb_perf.c 1299 */;
	char cocci_id/* drivers/ntb/test/ntb_perf.c 1285 */[8];
	const char __user *cocci_id/* drivers/ntb/test/ntb_perf.c 1252 */;
	const struct file_operations cocci_id/* drivers/ntb/test/ntb_perf.c 1225 */;
	char *cocci_id/* drivers/ntb/test/ntb_perf.c 1158 */;
	loff_t *cocci_id/* drivers/ntb/test/ntb_perf.c 1151 */;
	struct file *cocci_id/* drivers/ntb/test/ntb_perf.c 1150 */;
	char __user *cocci_id/* drivers/ntb/test/ntb_perf.c 1150 */;
	ssize_t cocci_id/* drivers/ntb/test/ntb_perf.c 1150 */;
	unsigned char cocci_id/* drivers/ntb/test/ntb_perf.c 113 */;
	unsigned long cocci_id/* drivers/ntb/test/ntb_perf.c 109 */;
	ssize_t *cocci_id/* drivers/ntb/test/ntb_perf.c 1086 */;
}
