cocci_test_suite() {
	struct mvebu_pcie_port {
		char *name;
		void __iomem *base;
		u32 port;
		u32 lane;
		int devfn;
		unsigned int mem_target;
		unsigned int mem_attr;
		unsigned int io_target;
		unsigned int io_attr;
		struct clk *clk;
		struct gpio_desc *reset_gpio;
		char *reset_name;
		struct pci_bridge_emul bridge;
		struct device_node *dn;
		struct mvebu_pcie *pcie;
		struct mvebu_pcie_window memwin;
		struct mvebu_pcie_window iowin;
		u32 saved_pcie_stat;
	} cocci_id/* drivers/pci/controller/pci-mvebu.c 89 */;
	struct mvebu_pcie_window {
		phys_addr_t base;
		phys_addr_t remap;
		size_t size;
	} cocci_id/* drivers/pci/controller/pci-mvebu.c 82 */;
	enum of_gpio_flags cocci_id/* drivers/pci/controller/pci-mvebu.c 812 */;
	struct device *cocci_id/* drivers/pci/controller/pci-mvebu.c 811 */;
	void *cocci_id/* drivers/pci/controller/pci-mvebu.c 801 */;
	u64 cocci_id/* drivers/pci/controller/pci-mvebu.c 750 */;
	u32 cocci_id/* drivers/pci/controller/pci-mvebu.c 748 */;
	__be32 cocci_id/* drivers/pci/controller/pci-mvebu.c 745 */;
	const __be32 *cocci_id/* drivers/pci/controller/pci-mvebu.c 733 */;
	const int cocci_id/* drivers/pci/controller/pci-mvebu.c 732 */;
	unsigned int *cocci_id/* drivers/pci/controller/pci-mvebu.c 729 */;
	unsigned long cocci_id/* drivers/pci/controller/pci-mvebu.c 728 */;
	struct device_node *cocci_id/* drivers/pci/controller/pci-mvebu.c 727 */;
	int cocci_id/* drivers/pci/controller/pci-mvebu.c 727 */;
	struct resource cocci_id/* drivers/pci/controller/pci-mvebu.c 711 */;
	struct platform_device *cocci_id/* drivers/pci/controller/pci-mvebu.c 707 */;
	struct mvebu_pcie {
		struct platform_device *pdev;
		struct mvebu_pcie_port *ports;
		struct msi_controller *msi;
		struct list_head resources;
		struct resource io;
		struct resource realio;
		struct resource mem;
		struct resource busn;
		int nports;
	} cocci_id/* drivers/pci/controller/pci-mvebu.c 70 */;
	const struct resource *cocci_id/* drivers/pci/controller/pci-mvebu.c 678 */;
	resource_size_t cocci_id/* drivers/pci/controller/pci-mvebu.c 677 */;
	struct pci_dev *cocci_id/* drivers/pci/controller/pci-mvebu.c 677 */;
	struct pci_ops cocci_id/* drivers/pci/controller/pci-mvebu.c 672 */;
	struct mvebu_pcie_port cocci_id/* drivers/pci/controller/pci-mvebu.c 67 */;
	struct pci_sys_data *cocci_id/* drivers/pci/controller/pci-mvebu.c 589 */;
	struct pci_bridge_emul_ops cocci_id/* drivers/pci/controller/pci-mvebu.c 557 */;
	struct pci_bridge_emul_conf *cocci_id/* drivers/pci/controller/pci-mvebu.c 477 */;
	struct pci_bridge_emul *cocci_id/* drivers/pci/controller/pci-mvebu.c 473 */;
	void cocci_id/* drivers/pci/controller/pci-mvebu.c 472 */;
	u32 *cocci_id/* drivers/pci/controller/pci-mvebu.c 429 */;
	pci_bridge_emul_read_status_t cocci_id/* drivers/pci/controller/pci-mvebu.c 427 */;
	struct mvebu_pcie_window cocci_id/* drivers/pci/controller/pci-mvebu.c 363 */;
	struct mvebu_pcie_window *cocci_id/* drivers/pci/controller/pci-mvebu.c 335 */;
	const struct mvebu_pcie_window *cocci_id/* drivers/pci/controller/pci-mvebu.c 334 */;
	phys_addr_t cocci_id/* drivers/pci/controller/pci-mvebu.c 302 */;
	size_t cocci_id/* drivers/pci/controller/pci-mvebu.c 302 */;
	void __iomem *cocci_id/* drivers/pci/controller/pci-mvebu.c 232 */;
	const struct mbus_dram_window *cocci_id/* drivers/pci/controller/pci-mvebu.c 183 */;
	const struct mbus_dram_target_info *cocci_id/* drivers/pci/controller/pci-mvebu.c 157 */;
	bool cocci_id/* drivers/pci/controller/pci-mvebu.c 120 */;
	struct mvebu_pcie_port *cocci_id/* drivers/pci/controller/pci-mvebu.c 120 */;
	struct platform_driver cocci_id/* drivers/pci/controller/pci-mvebu.c 1146 */;
	const struct dev_pm_ops cocci_id/* drivers/pci/controller/pci-mvebu.c 1142 */;
	const struct of_device_id cocci_id/* drivers/pci/controller/pci-mvebu.c 1134 */[];
	struct mvebu_pcie cocci_id/* drivers/pci/controller/pci-mvebu.c 1060 */;
	unsigned int cocci_id/* drivers/pci/controller/pci-mvebu.c 1024 */;
	struct pci_bus *cocci_id/* drivers/pci/controller/pci-mvebu.c 1013 */;
	struct mvebu_pcie *cocci_id/* drivers/pci/controller/pci-mvebu.c 1012 */;
	struct pci_host_bridge *cocci_id/* drivers/pci/controller/pci-mvebu.c 1010 */;
}
