cocci_test_suite() {
	const char *cocci_id/* drivers/net/phy/sfp.c 95 */;
	unsigned short cocci_id/* drivers/net/phy/sfp.c 95 */;
	const char *constcocci_id/* drivers/net/phy/sfp.c 89 */[];
	u8 cocci_id/* drivers/net/phy/sfp.c 857 */;
	u32 cocci_id/* drivers/net/phy/sfp.c 855 */;
	long *cocci_id/* drivers/net/phy/sfp.c 855 */;
	int cocci_id/* drivers/net/phy/sfp.c 855 */;
	__be16 cocci_id/* drivers/net/phy/sfp.c 598 */;
	const struct sfp *cocci_id/* drivers/net/phy/sfp.c 503 */;
	enum hwmon_sensor_types cocci_id/* drivers/net/phy/sfp.c 500 */;
	umode_t cocci_id/* drivers/net/phy/sfp.c 499 */;
	const void *cocci_id/* drivers/net/phy/sfp.c 499 */;
	u8 *cocci_id/* drivers/net/phy/sfp.c 489 */;
	void *cocci_id/* drivers/net/phy/sfp.c 487 */;
	size_t cocci_id/* drivers/net/phy/sfp.c 487 */;
	struct mii_bus *cocci_id/* drivers/net/phy/sfp.c 372 */;
	struct i2c_adapter *cocci_id/* drivers/net/phy/sfp.c 370 */;
	struct i2c_msg cocci_id/* drivers/net/phy/sfp.c 346 */[1];
	struct i2c_msg cocci_id/* drivers/net/phy/sfp.c 307 */[2];
	struct sfp *cocci_id/* drivers/net/phy/sfp.c 280 */;
	unsigned int cocci_id/* drivers/net/phy/sfp.c 280 */;
	unsigned long cocci_id/* drivers/net/phy/sfp.c 262 */;
	const struct of_device_id cocci_id/* drivers/net/phy/sfp.c 255 */[];
	const struct sff_data cocci_id/* drivers/net/phy/sfp.c 238 */;
	bool cocci_id/* drivers/net/phy/sfp.c 232 */;
	const struct sfp_eeprom_id *cocci_id/* drivers/net/phy/sfp.c 232 */;
	struct platform_driver cocci_id/* drivers/net/phy/sfp.c 2315 */;
	enum{GPIO_MODDEF0, GPIO_LOS, GPIO_TX_FAULT, GPIO_TX_DISABLE, GPIO_RATE_SELECT, GPIO_MAX, SFP_F_PRESENT=BIT(GPIO_MODDEF0), SFP_F_LOS=BIT(GPIO_LOS), SFP_F_TX_FAULT=BIT(GPIO_TX_FAULT), SFP_F_TX_DISABLE=BIT(GPIO_TX_DISABLE), SFP_F_RATE_SELECT=BIT(GPIO_RATE_SELECT), SFP_E_INSERT=0, SFP_E_REMOVE, SFP_E_DEV_ATTACH, SFP_E_DEV_DETACH, SFP_E_DEV_DOWN, SFP_E_DEV_UP, SFP_E_TX_FAULT, SFP_E_TX_CLEAR, SFP_E_LOS_HIGH, SFP_E_LOS_LOW, SFP_E_TIMEOUT, SFP_MOD_EMPTY=0, SFP_MOD_ERROR, SFP_MOD_PROBE, SFP_MOD_WAITDEV, SFP_MOD_HPOWER, SFP_MOD_WAITPWR, SFP_MOD_PRESENT, SFP_DEV_DETACHED=0, SFP_DEV_DOWN, SFP_DEV_UP, SFP_S_DOWN=0, SFP_S_WAIT, SFP_S_INIT, SFP_S_INIT_TX_FAULT, SFP_S_WAIT_LOS, SFP_S_LINK_UP, SFP_S_TX_FAULT, SFP_S_REINIT, SFP_S_TX_DISABLE,} cocci_id/* drivers/net/phy/sfp.c 23 */;
	struct acpi_handle *cocci_id/* drivers/net/phy/sfp.c 2182 */;
	struct fwnode_reference_args cocci_id/* drivers/net/phy/sfp.c 2181 */;
	struct fwnode_handle *cocci_id/* drivers/net/phy/sfp.c 2180 */;
	struct acpi_device *cocci_id/* drivers/net/phy/sfp.c 2179 */;
	const struct of_device_id *cocci_id/* drivers/net/phy/sfp.c 2161 */;
	struct device_node *cocci_id/* drivers/net/phy/sfp.c 2160 */;
	const struct sff_data *cocci_id/* drivers/net/phy/sfp.c 2142 */;
	struct platform_device *cocci_id/* drivers/net/phy/sfp.c 2140 */;
	struct device *cocci_id/* drivers/net/phy/sfp.c 2103 */;
	irqreturn_t cocci_id/* drivers/net/phy/sfp.c 2083 */;
	const struct sfp_socket_ops cocci_id/* drivers/net/phy/sfp.c 2032 */;
	struct ethtool_eeprom *cocci_id/* drivers/net/phy/sfp.c 1998 */;
	struct ethtool_modinfo *cocci_id/* drivers/net/phy/sfp.c 1983 */;
	void cocci_id/* drivers/net/phy/sfp.c 1963 */;
	struct sff_data {
		unsigned int gpios;
		bool (*module_supported)(const struct sfp_eeprom_id *id);
	} cocci_id/* drivers/net/phy/sfp.c 182 */;
	struct sfp_eeprom_id cocci_id/* drivers/net/phy/sfp.c 1575 */;
	const enum gpiod_flags cocci_id/* drivers/net/phy/sfp.c 150 */[];
	const char *cocci_id/* drivers/net/phy/sfp.c 142 */[];
	struct phy_device *cocci_id/* drivers/net/phy/sfp.c 1395 */;
	struct sfp cocci_id/* drivers/net/phy/sfp.c 1235 */;
	struct work_struct *cocci_id/* drivers/net/phy/sfp.c 1233 */;
	const struct hwmon_chip_info cocci_id/* drivers/net/phy/sfp.c 1228 */;
	const struct hwmon_channel_info *cocci_id/* drivers/net/phy/sfp.c 1219 */[];
	const struct hwmon_channel_info cocci_id/* drivers/net/phy/sfp.c 1191 */;
	u32 cocci_id/* drivers/net/phy/sfp.c 1181 */[];
	const struct hwmon_ops cocci_id/* drivers/net/phy/sfp.c 1135 */;
	const char **cocci_id/* drivers/net/phy/sfp.c 1089 */;
	struct sfp {
		struct device *dev;
		struct i2c_adapter *i2c;
		struct mii_bus *i2c_mii;
		struct sfp_bus *sfp_bus;
		struct phy_device *mod_phy;
		const struct sff_data *type;
		u32 max_power_mW;
		unsigned int (*get_state)(struct sfp *);
		void (*set_state)(struct sfp *, unsigned int);
		int (*read)(struct sfp *, bool, u8, void *, size_t);
		int (*write)(struct sfp *, bool, u8, void *, size_t);
		struct gpio_desc *gpio[GPIO_MAX];
		int gpio_irq[GPIO_MAX];
		bool need_poll;
		struct mutex st_mutex;
		unsigned int state_soft_mask;
		unsigned int state;
		struct delayed_work poll;
		struct delayed_work timeout;
		struct mutex sm_mutex;
		unsigned char sm_mod_state;
		unsigned char sm_mod_tries_init;
		unsigned char sm_mod_tries;
		unsigned char sm_dev_state;
		unsigned short sm_state;
		unsigned int sm_retries;
		struct sfp_eeprom_id id;
		unsigned int module_power_mW;
#if IS_ENABLED(CONFIG_HWMON)
		struct sfp_diag diag;
		struct delayed_work hwmon_probe;
		unsigned int hwmon_tries;
		struct device *hwmon_dev;
		char *hwmon_name;
#endif
	} cocci_id/*  1 */;
}
