cocci_test_suite() {
	void __exit cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 956 */;
	struct device *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 939 */;
	int __init cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 926 */;
	struct usb_driver cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 919 */;
	const u16 cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 881 */;
	const struct usb_device_id *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 878 */;
	char cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 854 */[IFNAMSIZ];
	struct peak_usb_device cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 740 */;
	u16 cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 738 */;
	struct net_device *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 736 */;
	struct peak_usb_device *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 735 */;
	struct usb_device *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 733 */;
	struct usb_interface *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 731 */;
	const struct peak_usb_adapter *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 730 */;
	const struct net_device_ops cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 719 */;
	struct peak_time_ref cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 70 */;
	struct can_bittiming *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 684 */;
	enum can_mode cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 655 */;
	struct urb *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 603 */;
	char *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 55 */;
	void *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 55 */;
	int cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 55 */;
	void cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 55 */;
	const struct peak_usb_adapter *const cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 42 */[];
	size_t cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 291 */;
	struct usb_device_id cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 29 */[];
	u8 *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 289 */;
	struct canfd_frame *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 287 */;
	struct net_device_stats *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 286 */;
	struct peak_tx_urb_context *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 285 */;
	netdev_tx_t cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 281 */;
	struct sk_buff *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 281 */;
	struct skb_shared_hwtstamps *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 155 */;
	u64 cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 132 */;
	u32 cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 128 */;
	ktime_t *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 128 */;
	struct peak_time_ref *cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 128 */;
	ktime_t cocci_id/* drivers/net/can/usb/peak_usb/pcan_usb_core.c 109 */;
}
