cocci_test_suite() {
	struct sk_buff *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 922 */;
	struct can_frame *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 921 */;
	struct net_device_stats *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 920 */;
	u32 *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 600 */;
	struct canfd_frame *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 594 */;
	void __iomem *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 582 */;
	u32 __iomem *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 558 */;
	const struct can_bittiming_const cocci_id/* drivers/net/can/rcar/rcar_canfd.c 545 */;
	struct rcar_canfd_global {
		struct rcar_canfd_channel *ch[RCANFD_NUM_CHANNELS];
		void __iomem *base;
		struct platform_device *pdev;
		struct clk *clkp;
		struct clk *can_clk;
		enum rcar_canfd_fcanclk fcan;
		unsigned long channels_mask;
		bool fdmode;
	} cocci_id/* drivers/net/can/rcar/rcar_canfd.c 507 */;
	struct rcar_canfd_channel {
		struct can_priv can;
		struct net_device *ndev;
		struct rcar_canfd_global *gpriv;
		void __iomem *base;
		struct napi_struct napi;
		u8 tx_len[RCANFD_FIFO_DEPTH];
		u32 tx_head;
		u32 tx_tail;
		u32 channel;
		spinlock_t tx_lock;
	} cocci_id/* drivers/net/can/rcar/rcar_canfd.c 493 */;
	struct rcar_canfd_global cocci_id/* drivers/net/can/rcar/rcar_canfd.c 490 */;
	enum rcar_canfd_fcanclk{RCANFD_CANFDCLK=0, RCANFD_EXTCLK,} cocci_id/* drivers/net/can/rcar/rcar_canfd.c 485 */;
	struct platform_driver cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1836 */;
	const struct of_device_id cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1829 */[];
	struct device *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1821 */;
	int __maybe_unused cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1821 */;
	bool cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1639 */;
	unsigned long cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1637 */;
	struct device_node *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1636 */;
	void cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1620 */;
	struct platform_device *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1559 */;
	const struct net_device_ops cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1549 */;
	struct can_berr_counter *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1537 */;
	const struct net_device *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1536 */;
	enum can_mode cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1520 */;
	struct rcar_canfd_channel cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1489 */;
	struct napi_struct *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1486 */;
	struct can_frame **cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1430 */;
	netdev_tx_t cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1338 */;
	const struct can_bittiming *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1180 */;
	u16 cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1148 */;
	u32 cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1147 */;
	struct rcar_canfd_channel *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1146 */;
	struct net_device *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1145 */;
	struct rcar_canfd_global *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1144 */;
	irqreturn_t cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1142 */;
	void *cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1142 */;
	int cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1142 */;
	enum can_state cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1114 */;
	u8 cocci_id/* drivers/net/can/rcar/rcar_canfd.c 1041 */;
}
