cocci_test_suite() {
	struct ican3_fast_desc *cocci_id/* drivers/net/can/janz-ican3.c 943 */;
	struct can_frame *cocci_id/* drivers/net/can/janz-ican3.c 942 */;
	struct ican3_dev *cocci_id/* drivers/net/can/janz-ican3.c 941 */;
	void cocci_id/* drivers/net/can/janz-ican3.c 941 */;
	struct can_bittiming *cocci_id/* drivers/net/can/janz-ican3.c 778 */;
	struct ican3_msg cocci_id/* drivers/net/can/janz-ican3.c 658 */;
	void __iomem *cocci_id/* drivers/net/can/janz-ican3.c 474 */;
	unsigned long cocci_id/* drivers/net/can/janz-ican3.c 472 */;
	struct ican3_fast_desc cocci_id/* drivers/net/can/janz-ican3.c 471 */;
	struct ican3_new_desc cocci_id/* drivers/net/can/janz-ican3.c 392 */;
	struct ican3_fast_desc {
		u8 control;
		u8 command;
		u8 data[14];
	} cocci_id/* drivers/net/can/janz-ican3.c 284 */;
	struct ican3_new_desc {
		u8 control;
		u8 pointer;
	} cocci_id/* drivers/net/can/janz-ican3.c 279 */;
	struct ican3_msg {
		u8 control;
		u8 spec;
		__le16 len;
		u8 data[252];
	} cocci_id/* drivers/net/can/janz-ican3.c 272 */;
	struct ican3_dev {
		struct can_priv can;
		struct net_device *ndev;
		struct napi_struct napi;
		unsigned int num;
		struct janz_cmodio_onboard_regs __iomem *ctrl;
		struct ican3_dpm_control __iomem *dpmctrl;
		void __iomem *dpm;
		int irq;
		struct completion termination_comp;
		bool termination_enabled;
		struct completion buserror_comp;
		struct can_berr_counter bec;
		enum ican3_fwtype fwtype;
		char fwinfo[32];
		unsigned int iftype;
		struct sk_buff_head echoq;
		spinlock_t lock;
		unsigned int rx_int;
		unsigned int rx_num;
		unsigned int tx_num;
		unsigned int fastrx_start;
		unsigned int fastrx_num;
		unsigned int fasttx_start;
		unsigned int fasttx_num;
		unsigned int free_page;
	} cocci_id/* drivers/net/can/janz-ican3.c 213 */;
	struct platform_driver cocci_id/* drivers/net/can/janz-ican3.c 2040 */;
	struct ican3_dpm_control {
		u8 window_address;
		u8 unused1;
		u8 interrupt;
		u8 unused2;
		u8 hwreset;
		u8 unused3;
		u8 tpuinterrupt;
	} cocci_id/* drivers/net/can/janz-ican3.c 193 */;
	struct device *cocci_id/* drivers/net/can/janz-ican3.c 1888 */;
	struct resource *cocci_id/* drivers/net/can/janz-ican3.c 1887 */;
	struct janz_platform_data *cocci_id/* drivers/net/can/janz-ican3.c 1884 */;
	struct platform_device *cocci_id/* drivers/net/can/janz-ican3.c 1882 */;
	const struct attribute_group cocci_id/* drivers/net/can/janz-ican3.c 1874 */;
	struct attribute *cocci_id/* drivers/net/can/janz-ican3.c 1868 */[];
	char *cocci_id/* drivers/net/can/janz-ican3.c 1857 */;
	enum ican3_fwtype{ICAN3_FWTYPE_ICANOS, ICAN3_FWTYPE_CAL_CANOPEN,} cocci_id/* drivers/net/can/janz-ican3.c 184 */;
	const char *cocci_id/* drivers/net/can/janz-ican3.c 1839 */;
	size_t cocci_id/* drivers/net/can/janz-ican3.c 1839 */;
	struct device_attribute *cocci_id/* drivers/net/can/janz-ican3.c 1838 */;
	ssize_t cocci_id/* drivers/net/can/janz-ican3.c 1837 */;
	struct can_berr_counter *cocci_id/* drivers/net/can/janz-ican3.c 1795 */;
	const struct net_device *cocci_id/* drivers/net/can/janz-ican3.c 1794 */;
	int cocci_id/* drivers/net/can/janz-ican3.c 1794 */;
	enum can_mode cocci_id/* drivers/net/can/janz-ican3.c 1770 */;
	const struct can_bittiming_const cocci_id/* drivers/net/can/janz-ican3.c 1758 */;
	const struct net_device_ops cocci_id/* drivers/net/can/janz-ican3.c 1746 */;
	netdev_tx_t cocci_id/* drivers/net/can/janz-ican3.c 1683 */;
	irqreturn_t cocci_id/* drivers/net/can/janz-ican3.c 1489 */;
	void *cocci_id/* drivers/net/can/janz-ican3.c 1489 */;
	struct ican3_dev cocci_id/* drivers/net/can/janz-ican3.c 1447 */;
	struct napi_struct *cocci_id/* drivers/net/can/janz-ican3.c 1445 */;
	struct ican3_fast_desc __iomem *cocci_id/* drivers/net/can/janz-ican3.c 1348 */;
	bool cocci_id/* drivers/net/can/janz-ican3.c 1322 */;
	struct sk_buff *cocci_id/* drivers/net/can/janz-ican3.c 1322 */;
	u8 cocci_id/* drivers/net/can/janz-ican3.c 1288 */;
	unsigned int cocci_id/* drivers/net/can/janz-ican3.c 1284 */;
	u16 cocci_id/* drivers/net/can/janz-ican3.c 1200 */;
	enum can_state cocci_id/* drivers/net/can/janz-ican3.c 1036 */;
	struct net_device_stats *cocci_id/* drivers/net/can/janz-ican3.c 1035 */;
	struct net_device *cocci_id/* drivers/net/can/janz-ican3.c 1034 */;
	struct ican3_msg *cocci_id/* drivers/net/can/janz-ican3.c 1032 */;
}
