cocci_test_suite() {
	irqreturn_t cocci_id/* drivers/net/ethernet/smsc/smc911x.c 998 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 874 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 505 */;
	netdev_tx_t cocci_id/* drivers/net/ethernet/smsc/smc911x.c 504 */;
	char *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 459 */;
	unsigned char *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 447 */;
	unsigned int cocci_id/* drivers/net/ethernet/smsc/smc911x.c 337 */;
	unsigned long cocci_id/* drivers/net/ethernet/smsc/smc911x.c 261 */;
	unsigned cocci_id/* drivers/net/ethernet/smsc/smc911x.c 260 */;
	struct platform_driver cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2180 */;
	pm_message_t cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2142 */;
	struct smc911x_platdata *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2076 */;
	unsigned char cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2070 */;
	struct smc911x_local cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2063 */;
	void __iomem *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2044 */;
	struct resource *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2042 */;
	struct platform_device *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 2039 */;
	dma_cap_mask_t cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1786 */;
	struct dma_slave_config cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1785 */;
	const char *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1782 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1741 */;
	const char cocci_id/* drivers/net/ethernet/smsc/smc911x.c 17 */[];
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1679 */;
	u8 cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1640 */[SMC911X_EEPROM_LEN];
	u8 *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1638 */;
	struct ethtool_eeprom *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1638 */;
	u8 cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1626 */;
	u32 *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1555 */;
	struct ethtool_regs *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1550 */;
	void *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1550 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1507 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1479 */;
	u32 cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1444 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1439 */;
	struct smc911x_local *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1408 */;
	struct net_device *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1406 */;
	struct netdev_hw_addr *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1326 */;
	unsigned int cocci_id/* drivers/net/ethernet/smsc/smc911x.c 1288 */[2];
	u_char cocci_id/* drivers/net/ethernet/smsc/smc911x.c 123 */;
	u_char *cocci_id/* drivers/net/ethernet/smsc/smc911x.c 110 */;
	int cocci_id/* drivers/net/ethernet/smsc/smc911x.c 110 */;
	void cocci_id/* drivers/net/ethernet/smsc/smc911x.c 110 */;
}
