cocci_test_suite() {
	irqreturn_t cocci_id/* drivers/net/ethernet/sun/sungem.c 934 */;
	struct netdev_queue *cocci_id/* drivers/net/ethernet/sun/sungem.c 894 */;
	struct gem cocci_id/* drivers/net/ethernet/sun/sungem.c 886 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/sun/sungem.c 884 */;
	const struct pci_device_id cocci_id/* drivers/net/ethernet/sun/sungem.c 87 */[];
	__sum16 cocci_id/* drivers/net/ethernet/sun/sungem.c 857 */;
	char cocci_id/* drivers/net/ethernet/sun/sungem.c 78 */[];
	unsigned long cocci_id/* drivers/net/ethernet/sun/sungem.c 751 */;
	gfp_t cocci_id/* drivers/net/ethernet/sun/sungem.c 746 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/sun/sungem.c 745 */;
	struct pci_driver cocci_id/* drivers/net/ethernet/sun/sungem.c 3035 */;
	struct gem_init_block cocci_id/* drivers/net/ethernet/sun/sungem.c 2968 */;
	const struct pci_device_id *cocci_id/* drivers/net/ethernet/sun/sungem.c 2843 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/sun/sungem.c 2827 */;
	const unsigned char *cocci_id/* drivers/net/ethernet/sun/sungem.c 2785 */;
	size_t cocci_id/* drivers/net/ethernet/sun/sungem.c 2759 */;
	unsigned char *cocci_id/* drivers/net/ethernet/sun/sungem.c 2731 */;
	void __iomem *cocci_id/* drivers/net/ethernet/sun/sungem.c 2731 */;
	struct mii_ioctl_data *cocci_id/* drivers/net/ethernet/sun/sungem.c 2701 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/sun/sungem.c 2698 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/sun/sungem.c 2686 */;
	struct ethtool_wolinfo *cocci_id/* drivers/net/ethernet/sun/sungem.c 2662 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/sun/sungem.c 2528 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/sun/sungem.c 2518 */;
	struct sockaddr *cocci_id/* drivers/net/ethernet/sun/sungem.c 2430 */;
	struct net_device_stats *cocci_id/* drivers/net/ethernet/sun/sungem.c 2392 */;
	pm_message_t cocci_id/* drivers/net/ethernet/sun/sungem.c 2320 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/sun/sungem.c 2254 */;
	void *cocci_id/* drivers/net/ethernet/sun/sungem.c 2175 */;
	const char *cocci_id/* drivers/net/ethernet/sun/sungem.c 2008 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/sun/sungem.c 1948 */;
	struct netdev_hw_addr *cocci_id/* drivers/net/ethernet/sun/sungem.c 1803 */;
	u16 cocci_id/* drivers/net/ethernet/sun/sungem.c 1801 */[16];
	struct gem_txd cocci_id/* drivers/net/ethernet/sun/sungem.c 1761 */;
	u64 cocci_id/* drivers/net/ethernet/sun/sungem.c 1753 */;
	unsigned cocci_id/* drivers/net/ethernet/sun/sungem.c 1637 */;
	struct gem_txd *cocci_id/* drivers/net/ethernet/sun/sungem.c 1602 */;
	struct gem_rxd *cocci_id/* drivers/net/ethernet/sun/sungem.c 1583 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/sun/sungem.c 1580 */;
	struct gem_init_block *cocci_id/* drivers/net/ethernet/sun/sungem.c 1577 */;
	void cocci_id/* drivers/net/ethernet/sun/sungem.c 154 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/sun/sungem.c 1502 */;
	struct net_device *cocci_id/* drivers/net/ethernet/sun/sungem.c 143 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/sun/sungem.c 1257 */;
	u32 cocci_id/* drivers/net/ethernet/sun/sungem.c 119 */;
	u16 cocci_id/* drivers/net/ethernet/sun/sungem.c 117 */;
	struct gem *cocci_id/* drivers/net/ethernet/sun/sungem.c 117 */;
	int cocci_id/* drivers/net/ethernet/sun/sungem.c 117 */;
	const skb_frag_t *cocci_id/* drivers/net/ethernet/sun/sungem.c 1067 */;
	const u64 cocci_id/* drivers/net/ethernet/sun/sungem.c 1009 */;
	netdev_tx_t cocci_id/* drivers/net/ethernet/sun/sungem.c 1000 */;
}
