cocci_test_suite() {
	enum chain_status{desc_filled, desc_empty,} cocci_id/* drivers/net/ethernet/korina.c 96 */;
	struct dma_desc cocci_id/* drivers/net/ethernet/korina.c 91 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/korina.c 887 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/korina.c 745 */;
	int cocci_id/* drivers/net/ethernet/korina.c 742 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/korina.c 735 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/korina.c 715 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/korina.c 703 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/korina.c 693 */;
	struct mii_ioctl_data *cocci_id/* drivers/net/ethernet/korina.c 678 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/korina.c 675 */;
	struct mii_if_info *cocci_id/* drivers/net/ethernet/korina.c 665 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/korina.c 656 */;
	u16 cocci_id/* drivers/net/ethernet/korina.c 500 */[4];
	struct netdev_hw_addr *cocci_id/* drivers/net/ethernet/korina.c 487 */;
	unsigned long cocci_id/* drivers/net/ethernet/korina.c 486 */;
	struct korina_private cocci_id/* drivers/net/ethernet/korina.c 465 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/korina.c 462 */;
	u8 *cocci_id/* drivers/net/ethernet/korina.c 356 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/korina.c 325 */;
	void *cocci_id/* drivers/net/ethernet/korina.c 325 */;
	struct dma_desc *cocci_id/* drivers/net/ethernet/korina.c 193 */;
	struct korina_private *cocci_id/* drivers/net/ethernet/korina.c 181 */;
	u32 cocci_id/* drivers/net/ethernet/korina.c 167 */;
	struct dma_reg *cocci_id/* drivers/net/ethernet/korina.c 152 */;
	struct net_device *cocci_id/* drivers/net/ethernet/korina.c 151 */;
	void cocci_id/* drivers/net/ethernet/korina.c 151 */;
	unsigned int cocci_id/* drivers/net/ethernet/korina.c 143 */;
	struct platform_driver cocci_id/* drivers/net/ethernet/korina.c 1143 */;
	struct korina_private {
		struct eth_regs *eth_regs;
		struct dma_reg *rx_dma_regs;
		struct dma_reg *tx_dma_regs;
		struct dma_desc *td_ring;
		struct dma_desc *rd_ring;
		struct sk_buff *tx_skb[KORINA_NUM_TDS];
		struct sk_buff *rx_skb[KORINA_NUM_RDS];
		int rx_next_done;
		int rx_chain_head;
		int rx_chain_tail;
		enum chain_status rx_chain_status;
		int tx_next_done;
		int tx_chain_head;
		int tx_chain_tail;
		enum chain_status tx_chain_status;
		int tx_count;
		int tx_full;
		int rx_irq;
		int tx_irq;
		spinlock_t lock;
		int dma_halt_cnt;
		int dma_run_cnt;
		struct napi_struct napi;
		struct timer_list media_check_timer;
		struct mii_if_info mii_if;
		struct work_struct restart_task;
		struct net_device *dev;
		int phy_addr;
	} cocci_id/* drivers/net/ethernet/korina.c 106 */;
	struct resource *cocci_id/* drivers/net/ethernet/korina.c 1028 */;
	struct korina_device *cocci_id/* drivers/net/ethernet/korina.c 1025 */;
	struct platform_device *cocci_id/* drivers/net/ethernet/korina.c 1023 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/korina.c 1009 */;
}
