cocci_test_suite() {
	struct lio_version cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 998 */;
	struct liquidio_if_cfg_resp cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 997 */;
	struct lio_version *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 992 */;
	union oct_nic_if_cfg cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 991 */;
	struct octeon_soft_command *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 990 */;
	struct liquidio_if_cfg_resp *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 989 */;
	struct lio *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 985 */;
	struct ethtool_ringparam *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 951 */;
	enum ethtool_phys_id_state cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 830 */;
	struct oct_mdio_cmd_resp cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 772 */;
	struct oct_mdio_cmd cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 771 */;
	struct oct_mdio_cmd *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 766 */;
	struct oct_mdio_cmd_resp *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 765 */;
	int *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 761 */;
	struct octeon_board_info *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 689 */;
	u8 *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 685 */;
	struct ethtool_eeprom *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 684 */;
	u8 cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 669 */[192];
	struct msix_entry *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 543 */;
	uint32_t cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 541 */;
	enum{INTERFACE_MODE_DISABLED, INTERFACE_MODE_RGMII, INTERFACE_MODE_GMII, INTERFACE_MODE_SPI, INTERFACE_MODE_PCIE, INTERFACE_MODE_XAUI, INTERFACE_MODE_SGMII, INTERFACE_MODE_PICMG, INTERFACE_MODE_NPI, INTERFACE_MODE_LOOP, INTERFACE_MODE_SRIO, INTERFACE_MODE_ILK, INTERFACE_MODE_RXAUI, INTERFACE_MODE_QSGMII, INTERFACE_MODE_AGL, INTERFACE_MODE_XLAUI, INTERFACE_MODE_XFI, INTERFACE_MODE_10G_KR, INTERFACE_MODE_40G_KR4, INTERFACE_MODE_MIXED,} cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 51 */;
	struct octeon_config *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 506 */;
	struct ethtool_channels *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 498 */;
	struct net_device *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 497 */;
	void cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 496 */;
	struct octnic_ctrl_pkt cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 473 */;
	struct ethtool_drvinfo cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 443 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 435 */;
	struct oct_mdio_cmd_resp {
		u64 rh;
		struct oct_mdio_cmd resp;
		u64 status;
	} cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 42 */;
	const int cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 396 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 394 */;
	struct oct_intrmod_resp {
		u64 rh;
		struct oct_intrmod_cfg intrmod;
		u64 status;
	} cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 36 */;
	int cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 34 */(struct net_device *netdev,
										uint32_t num_qs);
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 3102 */;
	struct ethtool_fecparam *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 3054 */;
	bool cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 3046 */;
	struct ethtool_regs *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 3007 */;
	void *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 3007 */;
	u64 cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2553 */;
	u8 cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2540 */;
	u32 cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2539 */;
	struct octeon_device *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2537 */;
	char *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2537 */;
	int cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2537 */;
	struct ethtool_ts_info *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2490 */;
	void __iomem *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2377 */;
	struct oct_link_info *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 219 */;
	struct oct_intrmod_cfg *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2186 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 215 */;
	struct octeon_cn6xxx *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2137 */;
	struct oct_intrmod_cfg cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2117 */;
	struct octeon_instr_queue *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2116 */;
	struct ethtool_coalesce *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2112 */;
	struct oct_intrmod_resp cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 2007 */;
	struct oct_intrmod_resp *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1999 */;
	const char cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 192 */[][ETH_GSTRING_LEN];
	struct rtnl_link_stats64 cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1431 */;
	struct ethtool_stats *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1426 */;
	struct ethtool_pauseparam *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1347 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1087 */;
	struct liquidio_if_cfg_info cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1053 */;
	u64 *cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1052 */;
	u16 cocci_id/* drivers/net/ethernet/cavium/liquidio/lio_ethtool.c 1011 */;
}
