cocci_test_suite() {
	struct work_struct *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 988 */;
	const struct pci_device_id cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 85 */[];
	int cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 82 */(struct lmac *lmac);
	struct bgx *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 79 */[MAX_BGX_THUNDER];
	struct bgx {
		u8 bgx_id;
		struct lmac lmac[MAX_LMAC_PER_BGX];
		u8 lmac_count;
		u8 max_lmac;
		u8 acpi_lmac_idx;
		void __iomem *reg_base;
		struct pci_dev *pdev;
		bool is_dlm;
		bool is_rgx;
	} cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 67 */;
	struct lmac cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 584 */;
	struct net_device *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 582 */;
	struct pfc *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 455 */;
	u64 cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 429 */;
	struct lmac *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 428 */;
	bool cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 425 */;
	struct lmac {
		struct bgx *bgx;
		u8 dmacs_cfg;
		u8 dmacs_count;
		struct dmac_map *dmacs;
		u8 mac[ETH_ALEN];
		u8 lmac_type;
		u8 lane_to_sds;
		bool use_training;
		bool autoneg;
		bool link_up;
		int lmacid;
		int lmacid_bd;
		struct net_device netdev;
		struct phy_device *phydev;
		unsigned int last_duplex;
		unsigned int last_link;
		unsigned int last_speed;
		bool is_sgmii;
		struct delayed_work dwork;
		struct workqueue_struct *check_link;
	} cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 42 */;
	struct dmac_map {
		u64 vf_map;
		u64 dmac;
	} cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 37 */;
	enum MCAST_MODE{MCAST_MODE_REJECT=0x0, MCAST_MODE_ACCEPT=0x1, MCAST_MODE_CAM_FILTER=0x2, RSVD=0x3,} cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 25 */;
	u8 cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 248 */;
	const u8 *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 223 */;
	struct bgx_link_status *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 207 */;
	unsigned cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 177 */;
	void __exit cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1660 */;
	void cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1660 */;
	int __init cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1653 */;
	struct pci_driver cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1646 */;
	u16 cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1544 */;
	const struct pci_device_id *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1538 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1538 */;
	const char *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1468 */;
	struct phy_device *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1466 */;
	struct device_node *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1462 */;
	struct fwnode_handle *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1461 */;
	char cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1424 */[5];
	struct bgx *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1423 */;
	struct acpi_buffer cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1422 */;
	void **cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1420 */;
	void *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1420 */;
	u32 cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1419 */;
	acpi_status cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1419 */;
	acpi_handle cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1419 */;
	u8 cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1383 */[ETH_ALEN];
	u8 *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1381 */;
	struct device *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1380 */;
	struct acpi_device *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1380 */;
	int cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1380 */;
	char *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1242 */;
	void __iomem *cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 123 */;
	char cocci_id/* drivers/net/ethernet/cavium/thunder/thunder_bgx.c 1229 */[27];
}
