cocci_test_suite() {
	struct netdev_queue *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 985 */;
	const skb_frag_t *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 979 */;
	unsigned char *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 929 */;
	struct metadata_dst *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 928 */;
	u64 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 926 */;
	struct nfp_net_tls_offload_ctx *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 830 */;
	u64 *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 827 */;
	int *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 827 */;
	struct iphdr *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 779 */;
	struct ipv6hdr *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 778 */;
	const struct nfp_net_dp *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 73 */;
	struct msix_entry *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 622 */;
	irq_handler_t cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 620 */;
	const char *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 619 */;
	char *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 619 */;
	size_t cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 619 */;
	struct nfp_net_fw_version *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 56 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 485 */;
	void *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 485 */;
	struct nfp_net cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3825 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3816 */;
	void __iomem *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3816 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3732 */;
	struct sockaddr *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3714 */;
	struct netdev_bpf *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3693 */;
	struct udp_tunnel_info *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3612 */;
	struct net_device *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3611 */;
	__be16 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3597 */;
	struct vxlanhdr cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3536 */;
	struct udphdr cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3536 */;
	netdev_features_t cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3493 */;
	u64 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3377 */[3];
	struct rtnl_link_stats64 *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3369 */;
	const u32 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3323 */;
	struct netlink_ext_ack *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3207 */;
	struct nfp_net_dp cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 3150 */;
	u32 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 277 */;
	int cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 277 */;
	const u8 *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2727 */;
	u8 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2695 */;
	struct nfp_net_dp *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2276 */;
	struct nfp_net_rx_ring *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2274 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2204 */;
	struct nfp_net_rx_desc *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2203 */;
	struct nfp_net_rx_buf *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2202 */;
	unsigned int cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2180 */;
	void cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2170 */;
	struct nfp_net_r_vector *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2153 */;
	bool cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2151 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2151 */;
	struct nfp_net *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2151 */;
	struct nfp_net_tx_desc *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2074 */;
	struct nfp_net_tx_buf *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2073 */;
	struct nfp_net_tx_ring *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2072 */;
	struct nfp_net_r_vector cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2049 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 2046 */;
	struct nfp_meta_parsed cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1826 */;
	struct xdp_buff cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1813 */;
	struct bpf_prog *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1808 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 176 */;
	bool *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1741 */;
	__wsum cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1699 */;
	__be32 *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1685 */;
	struct nfp_meta_parsed *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1671 */;
	struct nfp_net_rx_hash *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1661 */;
	u16 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1571 */;
	unsigned long cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 143 */;
	struct page *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1412 */;
	dma_addr_t *cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1403 */;
	struct skb_shared_info cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1353 */;
	__le64 cocci_id/* drivers/net/ethernet/netronome/nfp/nfp_net_common.c 1058 */;
}
