cocci_test_suite() {
	struct device *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 50 */;
	ionic_desc_cb cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 498 */;
	struct ionic_dev_bar *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 47 */;
	struct ionic *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 45 */;
	struct ionic_desc_info *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 436 */;
	const char *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 432 */;
	ionic_cq_done_cb cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 407 */;
	ionic_cq_cb cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 407 */;
	struct ionic_queue *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 401 */;
	struct ionic_cq *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 401 */;
	void cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 401 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 389 */;
	void *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 389 */;
	struct ionic_cq_info *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 355 */;
	unsigned int cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 353 */;
	size_t cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 353 */;
	struct ionic_intr_info *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 352 */;
	struct ionic_lif *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 351 */;
	int cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 351 */;
	union ionic_dev_cmd cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 329 */;
	u16 cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 324 */;
	struct ionic_qcq *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 323 */;
	struct ionic_dev *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 323 */;
	u32 cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 241 */;
	u8 cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 168 */;
	union ionic_dev_cmd *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 160 */;
	union ionic_dev_cmd_comp *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 155 */;
	bool cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 150 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 14 */;
	unsigned long cocci_id/* drivers/net/ethernet/pensando/ionic/ionic_dev.c 105 */;
}
