cocci_test_suite() {
	unsigned long cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 970 */;
	bool cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 969 */;
	struct phy_device *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 968 */;
	struct ravb_private *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 967 */;
	struct net_device *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 965 */;
	void cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 965 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 906 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 896 */;
	void *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 896 */;
	int cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 896 */;
	u32 cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 692 */;
	struct skb_shared_hwtstamps *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 590 */;
	u8 cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 544 */;
	int *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 533 */;
	enum ravb_reg cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 53 */;
	__sum16 cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 524 */;
	u64 cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 494 */;
	u16 cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 486 */;
	struct timespec64 cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 485 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 484 */;
	struct skb_shared_hwtstamps cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 483 */;
	const char *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 48 */[NUM_TX_QUEUE];
	const char *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 43 */[NUM_RX_QUEUE];
	dma_addr_t cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 283 */;
	struct ravb_desc *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 279 */;
	struct ravb_tx_desc *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 278 */;
	struct ravb_ex_rx_desc *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 277 */;
	struct ravb_tx_desc cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 246 */;
	struct ravb_ex_rx_desc cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 236 */;
	struct platform_driver cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 2340 */;
	int __maybe_unused cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 2276 */;
	struct ravb_desc cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 2117 */;
	struct resource *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1991 */;
	enum ravb_chip_id cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1988 */;
	uint64_t cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1922 */;
	const struct of_device_id cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1907 */[];
	struct platform_device *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1865 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1847 */;
	netdev_features_t cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1835 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1779 */;
	struct hwtstamp_config cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1717 */;
	struct ravb_tstamp_skb *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1662 */;
	struct device_node *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1660 */;
	struct mdiobb_ops cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 165 */;
	struct ravb_private cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 158 */;
	struct mdiobb_ctrl *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 156 */;
	netdev_tx_t cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1472 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1442 */;
	char *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1326 */;
	const char *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1324 */;
	struct device *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1323 */;
	irq_handler_t cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1322 */;
	unsigned int cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1322 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1305 */;
	struct ethtool_wolinfo *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1283 */;
	struct ethtool_ts_info *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1262 */;
	struct ethtool_ringparam *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1193 */;
	u8 *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1183 */;
	struct net_device_stats *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1163 */;
	u64 *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1155 */;
	struct ethtool_stats *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1155 */;
	const u8 *cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 112 */;
	const char cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1108 */[][ETH_GSTRING_LEN];
	const struct soc_device_attribute cocci_id/* drivers/net/ethernet/renesas/ravb_main.c 1005 */[];
}
