cocci_test_suite() {
	const char cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 94 */[][ETH_GSTRING_LEN];
	u32 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 931 */;
	__be16 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 877 */;
	struct igc_q_vector *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 862 */;
	enum igc_diagnostics_results{TEST_REG=0, TEST_EEP, TEST_IRQ, TEST_LOOP, TEST_LINK,} cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 86 */;
	struct ethtool_coalesce *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 780 */;
	const struct igc_stats cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 74 */[];
	u64 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 739 */;
	char *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 731 */;
	struct igc_ring *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 729 */;
	unsigned int cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 728 */;
	struct rtnl_link_stats64 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 727 */;
	u64 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 724 */;
	struct ethtool_stats *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 724 */;
	struct rtnl_link_stats64 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 70 */;
	struct ethtool_pauseparam *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 600 */;
	struct igc_ring cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 523 */;
	struct ethtool_ringparam *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 474 */;
	u16 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 364 */;
	u8 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 359 */;
	struct ethtool_eeprom *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 359 */;
	struct igc_mac_info *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 337 */;
	struct igc_adapter cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 19 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1825 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1757 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1650 */;
	struct ethtool_channels *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1554 */;
	const u8 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1520 */;
	const u8 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1520 */;
	const u32 *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1519 */;
	struct ethtool_regs *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 147 */;
	void *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 147 */;
	struct igc_nfc_filter *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1354 */;
	struct ethtool_rx_flow_spec *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1352 */;
	struct net_device *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1351 */;
	struct ethtool_rxnfc *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1349 */;
	struct igc_adapter *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1348 */;
	int cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1348 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 127 */;
	u8 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1265 */;
	u32 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1250 */;
	u16 cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1247 */;
	void cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1246 */;
	struct igc_hw *cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 1205 */;
	struct igc_stats {
		char stat_string[ETH_GSTRING_LEN];
		int sizeof_stat;
		int stat_offset;
	} cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 11 */;
	struct igc_rx_queue_stats cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 109 */;
	struct igc_stats cocci_id/* drivers/net/ethernet/intel/igc/igc_ethtool.c 105 */;
}
