cocci_test_suite() {
	u32 cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 925 */;
	struct e1000_hw *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 924 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 894 */;
	void *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 894 */;
	u16 cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 86 */;
	union e1000_adv_tx_desc *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 775 */;
	enum latency_range cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 688 */;
	struct igbvf_buffer cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 592 */;
	const struct igbvf_info *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 59 */[];
	unsigned long cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 552 */;
	struct igbvf_info cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 52 */;
	void cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 41 */(struct igbvf_adapter *);
	int cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 40 */(struct napi_struct *napi,
								       int budget);
	int cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 36 */;
	const char cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 32 */[];
	void __exit cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 3005 */;
	int __init cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2986 */;
	struct pci_driver cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2966 */;
	const struct pci_device_id cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2958 */[];
	const struct pci_error_handlers cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2952 */;
	char cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 28 */[];
	struct igbvf_adapter cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2742 */;
	const struct igbvf_info *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2713 */;
	const struct pci_device_id *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2708 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2679 */;
	netdev_features_t cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2648 */;
	pci_channel_state_t cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2553 */;
	pci_ers_result_t cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2552 */;
	pm_message_t cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2462 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2454 */;
	int *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 243 */;
	bool cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 242 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2387 */;
	netdev_tx_t cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2358 */;
	u8 cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2229 */;
	const skb_frag_t *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2177 */;
	struct sctphdr cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2099 */;
	struct udphdr cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2097 */;
	struct tcphdr cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2094 */;
	__be16 cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2081 */;
	unsigned char *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2031 */;
	union {
		struct tcphdr *tcp;
		unsigned char *hdr;
	} cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2006 */;
	union {
		struct iphdr *v4;
		struct ipv6hdr *v6;
		unsigned char *hdr;
	} cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 2001 */;
	struct e1000_adv_tx_context_desc *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1975 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1898 */;
	s32 cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1872 */;
	struct sockaddr *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1796 */;
	struct e1000_mac_info *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1511 */;
	unsigned int cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 142 */;
	u8 *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1413 */;
	struct netdev_hw_addr *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1412 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 141 */;
	struct igbvf_buffer *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 140 */;
	union e1000_adv_rx_desc *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 139 */;
	union e1000_adv_rx_desc cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1381 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 138 */;
	u64 cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1366 */;
	struct igbvf_ring *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 133 */;
	void cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 133 */;
	union e1000_adv_tx_desc cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1295 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1180 */;
	struct igbvf_ring cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1098 */;
	struct net_device *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1096 */;
	struct igbvf_adapter *cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1094 */;
	struct msix_entry cocci_id/* drivers/net/ethernet/intel/igbvf/netdev.c 1021 */;
}
