cocci_test_suite() {
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 970 */;
	__u32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 95 */;
	u8 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 898 */;
	struct ethtool_rxnfc *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 868 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 85 */;
	u16 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 821 */;
	struct ixgbevf_q_vector *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 819 */;
	struct ethtool_coalesce *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 792 */;
	int cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 791 */;
	bool cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 730 */;
	struct ixgbevf_adapter *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 729 */;
	u64 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 727 */;
	struct ethtool_test *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 727 */;
	struct net_device *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 726 */;
	void cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 726 */;
	const char cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 70 */[][ETH_GSTRING_LEN];
	const struct ixgbevf_reg_test *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 661 */;
	struct ixgbevf_stats cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 66 */;
	const u32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 604 */[];
	const struct ixgbevf_reg_test cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 591 */[];
	struct ixgbevf_reg_test {
		u16 reg;
		u8 array_len;
		u8 test_type;
		u32 mask;
		u32 write;
	} cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 565 */;
	u64 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 450 */;
	u32 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 450 */;
	struct ixgbe_stats cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 45 */[];
	char *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 430 */;
	struct ixgbevf_ring *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 428 */;
	unsigned int cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 427 */;
	const struct rtnl_link_stats64 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 426 */;
	struct rtnl_link_stats64 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 425 */;
	struct ethtool_stats *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 422 */;
	struct net_device_stats cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 41 */;
	struct ixgbevf_adapter cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 34 */;
	struct ixgbe_stats {
		char stat_string[ETH_GSTRING_LEN];
		int type;
		int sizeof_stat;
		int stat_offset;
	} cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 24 */;
	struct ethtool_ringparam *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 230 */;
	enum{NETDEV_STATS, IXGBEVF_STATS,} cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 22 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 216 */;
	u8 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 149 */;
	struct ixgbe_hw *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 146 */;
	void *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 143 */;
	struct ethtool_regs *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 142 */;
	u32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ethtool.c 119 */;
}
