cocci_test_suite() {
	const char cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 9 */[];
	u32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 71 */[2];
	struct ixgbe_hw *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 70 */;
	struct tx_sa cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 630 */;
	struct rx_sa cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 625 */;
	size_t cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 611 */;
	struct ixgbevf_ipsec *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 610 */;
	struct ixgbevf_adapter *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 608 */;
	void cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 608 */;
	struct ip_esp_hdr *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 580 */;
	struct ip_auth_hdr *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 576 */;
	struct ipv6hdr cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 569 */;
	u8 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 554 */;
	void *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 552 */;
	struct sec_path *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 551 */;
	struct iphdr *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 550 */;
	struct ipv6hdr *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 549 */;
	struct xfrm_offload *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 547 */;
	__le16 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 543 */;
	union ixgbe_adv_rx_desc *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 539 */;
	struct ixgbevf_ring *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 538 */;
	const int cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 511 */;
	struct ixgbevf_ipsec_tx_data *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 448 */;
	struct ixgbevf_tx_buffer *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 447 */;
	const struct xfrmdev_ops cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 434 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 419 */;
	u32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 333 */;
	u16 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 266 */;
	struct net_device *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 263 */;
	struct xfrm_state *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 261 */;
	int cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 261 */;
	struct sa_mbx_msg *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 23 */;
	char *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 216 */;
	unsigned char *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 215 */;
	u32 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 212 */;
	u32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 21 */[IXGBE_VFMAILBOX_SIZE];
	struct rx_sa *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 183 */;
	__be32 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 180 */;
	u8 cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 179 */;
	__be32 *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 179 */;
	bool cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 140 */;
	struct tx_sa *cocci_id/* drivers/net/ethernet/intel/ixgbevf/ipsec.c 113 */;
}
