cocci_test_suite() {
	struct protocol_dcb_data *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 973 */;
	struct pf_update_ramrod_data *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 971 */;
	void *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 882 */;
	struct qed_common_cb_ops *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 881 */;
	u32 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 879 */;
	struct dcbx_mib cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 812 */;
	struct lldp_status_params_s cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 794 */;
	struct lldp_config_params_s cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 776 */;
	struct lldp_status_params_s *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 728 */;
	struct lldp_config_params_s *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 714 */;
	const struct qed_dcbx_app_metadata cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 67 */[];
	struct qed_dcbx_operational_params *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 658 */;
	struct dcbx_features *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 633 */;
	struct dcbx_ets_feature *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 622 */;
	u32 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 576 */[2];
	struct dcbx_app_priority_entry *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 483 */;
	struct dcbx_app_priority_feature *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 482 */;
	struct qed_dcbx_app_prio *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 442 */;
	struct qed_dcbx_mib_meta_data *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 399 */;
	struct qed_hw_info *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 359 */;
	struct qed_dcbx_results cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 357 */;
	enum dcbx_protocol_type *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 249 */;
	const struct qed_eth_dcbnl_ops cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2402 */;
	struct qed_ptt *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2335 */;
	struct qed_dcbx_set cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2333 */;
	struct dcb_app *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2278 */;
	struct qed_dcbx_params *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2154 */;
	bool cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2150 */;
	struct ieee_ets *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2150 */;
	struct ieee_pfc *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2060 */;
	struct cee_pg *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2037 */;
	struct qed_dcbx_get *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2018 */;
	struct qed_hwfn *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2017 */;
	struct qed_dev *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2015 */;
	struct cee_pfc *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2015 */;
	int cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 2015 */;
	u16 *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1972 */;
	struct dcb_peer_app_info *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1971 */;
	enum qed_pci_personality cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 196 */;
	struct qed_app_entry *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1756 */;
	u8 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1752 */;
	u16 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1752 */;
	enum dcbx_protocol_type cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 174 */;
	struct qed_dcbx_results *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 172 */;
	u8 *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1484 */;
	void cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1432 */;
	enum qed_mib_read_type cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1309 */;
	struct qed_dcbx_admin_params cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1298 */;
	struct public_port cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1251 */;
	struct qed_dcbx_mib_meta_data cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1234 */;
	struct dcbx_local_params cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1233 */;
	struct qed_dcbx_set *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1231 */;
	struct dcbx_local_params *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1197 */;
	u32 *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_dcbx.c 1128 */;
}
