cocci_test_suite() {
	struct qed_consq *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 994 */;
	u32 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 92 */;
	struct qed_spq_comp_done *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 91 */;
	bool cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 89 */;
	u8 *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 89 */;
	struct qed_spq_entry *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 88 */;
	struct qed_hwfn *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 87 */;
	int cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 87 */;
	__le16 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 810 */;
	u8 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 75 */;
	union event_ring_data *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 75 */;
	struct list_head *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 749 */;
	struct qed_spq_entry cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 697 */;
	struct qed_spq *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 684 */;
	enum spq_priority cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 682 */;
	void cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 653 */;
	struct qed_spq_entry **cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 621 */;
	u8 __iomem *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 604 */;
	void __iomem *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 597 */;
	struct slow_path_element cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 570 */;
	struct qed_spq cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 560 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 556 */;
	enum protocol_type cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 457 */;
	struct eth_slow_path_rx_cqe *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 456 */;
	union event_ring_element cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 420 */;
	struct qed_eq *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 407 */;
	u16 cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 405 */;
	struct qed_chain *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 349 */;
	void *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 346 */;
	qed_spq_async_comp_cb cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 296 */;
	struct event_ring_entry *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 294 */;
	u32 *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 274 */;
	struct slow_path_element *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 257 */;
	struct core_db_data *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 255 */;
	struct qed_cxt_info cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 215 */;
	struct e4_core_conn_context *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 214 */;
	struct qed_ptt *cocci_id/* drivers/net/ethernet/qlogic/qed/qed_spq.c 120 */;
}
