cocci_test_suite() {
	void cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 847 */;
	__le32 *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 762 */;
	char *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 762 */;
	struct netxen_ring_ctx cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 749 */;
	struct net_device *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 742 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 741 */;
	struct nx_host_tx_ring *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 739 */;
	struct nx_host_sds_ring *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 738 */;
	struct nx_host_rds_ring *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 737 */;
	struct netxen_recv_context *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 736 */;
	void *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 733 */;
	struct netxen_adapter *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 731 */;
	int cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 731 */;
	struct netxen_ring_ctx *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 686 */;
	struct netxen_recv_crb cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 574 */[];
	u64 cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 560 */[][3];
	nx_cardrsp_tx_ctx_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 437 */;
	nx_hostrq_tx_ctx_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 431 */;
	nx_cardrsp_tx_ctx_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 420 */;
	nx_hostrq_cds_ring_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 419 */;
	nx_hostrq_tx_ctx_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 418 */;
	struct netxen_cmd_args *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 33 */;
	nx_hostrq_rds_ring_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 317 */;
	nx_cardrsp_rx_ctx_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 282 */;
	nx_hostrq_rx_ctx_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 280 */;
	size_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 269 */;
	nx_cardrsp_sds_ring_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 260 */;
	nx_cardrsp_rds_ring_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 259 */;
	nx_hostrq_sds_ring_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 258 */;
	nx_hostrq_rds_ring_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 257 */;
	nx_cardrsp_rx_ctx_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 256 */;
	nx_hostrq_rx_ctx_t *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 255 */;
	u32 *cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 144 */;
	u64 cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 143 */;
	u32 cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 140 */;
	struct _cdrp_cmd cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 123 */;
	struct netxen_cmd_args cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 107 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c 104 */;
}
