cocci_test_suite() {
	struct net_device *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 987 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 985 */;
	void *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 985 */;
	int cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 985 */;
	struct netdev_queue *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 970 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 964 */;
	struct rx_status_t *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 899 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 897 */;
	unsigned int cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 845 */;
	bool cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 722 */;
	u16 cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 693 */;
	struct mii_bus *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 670 */;
	u32 cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 600 */;
	struct netdata_local *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 598 */;
	void cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 598 */;
	struct rx_status_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 552 */;
	struct txrx_desc_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 537 */;
	struct txrx_desc_t *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 530 */;
	u32 *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 527 */;
	void __iomem *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 519 */;
	phys_addr_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 503 */;
	u8 *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 437 */;
	struct netdata_local {
		struct platform_device *pdev;
		struct net_device *ndev;
		struct device_node *phy_node;
		spinlock_t lock;
		void __iomem *net_base;
		u32 msg_enable;
		unsigned int skblen[ENET_TX_DESC];
		unsigned int last_tx_idx;
		unsigned int num_used_tx_buffs;
		struct mii_bus *mii_bus;
		struct clk *clk;
		dma_addr_t dma_buff_base_p;
		void *dma_buff_base_v;
		size_t dma_buff_size;
		struct txrx_desc_t *tx_desc_v;
		u32 *tx_stat_v;
		void *tx_buff_v;
		struct txrx_desc_t *rx_desc_v;
		struct rx_status_t *rx_stat_v;
		void *rx_buff_v;
		int link;
		int speed;
		int duplex;
		struct napi_struct napi;
	} cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 392 */;
	struct rx_status_t {
		__le32 statusinfo;
		__le32 statushashcrc;
	} cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 384 */;
	struct txrx_desc_t {
		__le32 packet;
		__le32 control;
	} cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 380 */;
	phy_interface_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 315 */;
	struct platform_driver cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1512 */;
	const struct of_device_id cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1506 */[];
	pm_message_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1454 */;
	const char *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1362 */;
	size_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1346 */;
	struct netdata_local cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1260 */;
	struct resource *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1244 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1243 */;
	struct device_node *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1240 */;
	struct device *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1239 */;
	struct platform_device *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1237 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1227 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1218 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1196 */;
	struct phy_device *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1154 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1152 */;
	struct netdev_hw_addr *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1109 */;
	struct netdev_hw_addr_list *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1108 */;
	struct sockaddr *cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1087 */;
	unsigned long cocci_id/* drivers/net/ethernet/nxp/lpc_eth.c 1008 */;
}
