cocci_test_suite() {
	const struct phylink_mac_ops cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 966 */;
	phy_interface_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 942 */;
	struct phylink_config *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 936 */;
	const u32 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 89 */;
	const struct phylink_link_state *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 878 */;
	struct phylink_link_state *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 872 */;
	struct hwtstamp_config *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 742 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 739 */;
	struct timespec64 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 513 */;
	struct hwtstamp_config cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 512 */;
	void __exit cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 5024 */;
	char *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4967 */;
	int __init cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4967 */;
	struct skb_shared_hwtstamps cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 491 */;
	u64 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 478 */;
	struct skb_shared_hwtstamps *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 476 */;
	unsigned long cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4547 */;
	struct stmmac_priv cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4532 */;
	struct stmmac_resources *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4525 */;
	struct plat_stmmacenet_data *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4524 */;
	struct device *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4523 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4405 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4363 */;
	unsigned char cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4286 */;
	__le16 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4283 */;
	struct seq_file *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4194 */;
	struct dma_extended_desc *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4124 */;
	struct dentry *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4118 */;
	enum tc_setup_type cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 4067 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3921 */;
	netdev_features_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3856 */;
	bool cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 383 */;
	struct stmmac_channel cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3745 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3742 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 367 */;
	enum pkt_hash_types cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3561 */;
	u16 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3381 */;
	__be16 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3380 */;
	struct vlan_ethhdr *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3379 */;
	const skb_frag_t *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 3015 */;
	struct udphdr cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 2933 */;
	netdev_tx_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 2913 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 2851 */;
	unsigned char *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 285 */;
	struct stmmac_extra_stats cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 2668 */;
	struct stmmac_counters cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 2138 */;
	int cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 2091 */[max_t(u32,
										       MTL_MAX_TX_QUEUES,
										       MTL_MAX_RX_QUEUES)];
	u8 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1815 */;
	struct stmmac_priv *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1667 */;
	int cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1667 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1629 */;
	struct stmmac_tx_queue *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1617 */;
	struct dma_desc cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1585 */;
	struct dma_extended_desc cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1577 */;
	unsigned int cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1550 */;
	struct page_pool_params cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1549 */;
	struct stmmac_rx_queue *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1548 */;
	u32 cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1542 */;
	struct stmmac_channel *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 148 */;
	void cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1448 */;
	gfp_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1424 */;
	struct net_device *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1424 */;
	struct dma_desc *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1315 */;
	struct stmmac_rx_buffer *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1243 */;
	void cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 110 */(struct net_device *dev);
	irqreturn_t cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 106 */(int irq,
											void *dev_id);
	void *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1059 */;
	struct phylink *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1042 */;
	struct fwnode_handle *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1040 */;
	struct phy_device *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1024 */;
	struct device_node *cocci_id/* drivers/net/ethernet/stmicro/stmmac/stmmac_main.c 1011 */;
}
