cocci_test_suite() {
	unsigned int cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 978 */;
	struct net_device *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 974 */;
	void cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 974 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 935 */;
	const struct pasemi_mac_rxring *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 908 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 906 */;
	void *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 906 */;
	int cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 825 */[TX_CLEAN_BATCHSIZE];
	dma_addr_t cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 824 */[TX_CLEAN_BATCHSIZE][MAX_SKB_FRAGS + 1];
	struct sk_buff *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 823 */[TX_CLEAN_BATCHSIZE];
	unsigned long cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 822 */;
	struct pasemi_dmachan *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 816 */;
	struct pasemi_mac_txring *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 814 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 705 */;
	u64 cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 704 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 702 */;
	struct pasemi_mac_buffer *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 701 */;
	const struct pasemi_dmachan *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 696 */;
	const int cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 694 */;
	struct pasemi_mac_rxring *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 693 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 67 */;
	const u64 cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 658 */;
	int cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 63 */;
	u64 *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 590 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 512 */[MAX_SKB_FRAGS + 1];
	struct pasemi_mac_txring cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 453 */;
	struct pasemi_mac_buffer cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 383 */;
	struct pasemi_mac_rxring cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 370 */;
	const struct net_device *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 363 */;
	struct pasemi_mac_csring *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 353 */;
	struct pasemi_mac_csring cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 272 */;
	const skb_frag_t *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 253 */;
	struct sockaddr *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 218 */;
	void __exit cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1825 */;
	struct pci_driver cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1818 */;
	const struct pci_device_id cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1810 */[];
	u8 cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 176 */[ETH_ALEN];
	const u8 *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 175 */;
	struct device_node *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 173 */;
	const struct pci_device_id *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1672 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1658 */;
	const struct pasemi_mac *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1581 */;
	struct pasemi_mac cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1558 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1556 */;
	skb_frag_t *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1450 */;
	unsigned int cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1430 */[MAX_SKB_FRAGS + 1];
	struct pasemi_mac_txring *const cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1425 */;
	struct pasemi_mac *const cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1424 */;
	const unsigned int *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1338 */;
	const dma_addr_t *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1337 */;
	const struct sk_buff *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1336 */;
	u32 cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 127 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 126 */;
	struct pasemi_mac *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 124 */;
	const void *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 116 */;
	struct phy_device *cocci_id/* drivers/net/ethernet/pasemi/pasemi_mac.c 1041 */;
}
