cocci_test_suite() {
	struct hclgevf_desc cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 999 */;
	struct hclge_mbx_vf_to_pf_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 998 */;
	struct hnae3_ring_chain_node *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 994 */;
	struct hclgevf_rss_input_tuple_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 960 */;
	struct hclgevf_dev cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 91 */;
	struct ethtool_rxnfc *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 797 */;
	const u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 754 */;
	const u8 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 754 */;
	const u32 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 753 */;
	struct hclgevf_rss_cfg *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 711 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 675 */[HCLGEVF_RSS_MBX_RESP_LEN];
	u16 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 633 */[HCLGEVF_MAX_TC_NUM];
	struct hclgevf_rss_tc_mode_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 632 */;
	struct hclgevf_rss_indirection_table_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 602 */;
	struct hclgevf_rss_config_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 552 */;
	struct hnae3_vector_info *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 505 */;
	struct hnae3_queue *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 404 */;
	unsigned int cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 387 */;
	const u32 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 36 */[];
	struct hclgevf_tqp cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 359 */;
	struct hclgevf_tqp *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 355 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 335 */[2];
	u16 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 328 */;
	const struct hnae3_ae_ops cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 3150 */;
	u16 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 315 */;
	void *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 3079 */;
	unsigned long *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 3050 */;
	unsigned long cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 3042 */;
	bool cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 3035 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 296 */[HCLGEVF_TQPS_DEPTH_INFO_LEN];
	struct ethtool_channels *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2891 */;
	struct hnae3_knic_private_info *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2874 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 273 */[HCLGEVF_TQPS_RSS_INFO_LEN];
	const u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 26 */[];
	struct hclgevf_query_res_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2598 */;
	struct hclgevf_hw *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2544 */;
	struct hnae3_client *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2470 */;
	struct device *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2413 */;
	u64 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 225 */;
	void cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2220 */;
	char *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 219 */;
	struct hclgevf_cfg_gro_status_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2114 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2075 */;
	struct hnae3_ae_dev *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2073 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2018 */;
	struct hclgevf_misc_vector *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 2013 */;
	u32 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1966 */;
	u32 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1964 */;
	enum hclgevf_evt_cause cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1963 */;
	struct net_device_stats *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 194 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1913 */;
	struct timer_list *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1904 */;
	const struct pci_device_id cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 19 */[];
	struct hnae3_ae_algo cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 17 */;
	enum hnae3_reset_type cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1665 */;
	int cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 16 */(struct hclgevf_dev *hdev);
	enum hnae3_reset_notify_type cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1386 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1291 */[HCLGEVF_VLAN_MBX_MSG_LEN];
	__be16 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1286 */;
	struct hclgevf_dev *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1268 */;
	const unsigned char *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1266 */;
	struct hnae3_handle *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1265 */;
	int cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1265 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1226 */[ETH_ALEN * 2];
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1189 */[ETH_ALEN];
	u8 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1187 */;
	struct hclgevf_cfg_com_tqp_queue_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1154 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3vf/hclgevf_main.c 1002 */;
}
