cocci_test_suite() {
	struct hclge_get_m7_bd_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 982 */;
	enum hclge_opcode_type cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 98 */;
	struct hclge_desc *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 96 */;
	struct hclge_dev *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 95 */;
	int cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 95 */;
	u32 *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 897 */;
	struct hclge_desc cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 895 */[3];
	struct hclge_fd_tcam_config_3_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 894 */;
	struct hclge_fd_tcam_config_2_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 893 */;
	struct hclge_fd_tcam_config_1_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 892 */;
	struct hclge_desc cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 828 */;
	char cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 827 */[HCLGE_DBG_BUF_LEN];
	struct hclge_mac_ethertype_idx_rd_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 826 */;
	struct hclge_desc cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 78 */[HCLGE_GET_DFX_REG_TYPE_CNT];
	struct hclge_rx_com_thrd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 707 */;
	struct hclge_rx_com_wl *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 706 */;
	struct hclge_rx_priv_wl_buf *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 705 */;
	struct hclge_rx_priv_buff_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 704 */;
	struct hclge_tx_buff_alloc_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 703 */;
	struct hclge_qos_pri_map_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 675 */;
	struct hclge_cfg_pause_param_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 652 */;
	u32 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 571 */[32];
	struct hclge_tqp_tx_queue_tc_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 567 */;
	struct hclge_bp_to_qs_map_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 564 */;
	struct hclge_qs_weight_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 455 */;
	struct hclge_pg_weight_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 454 */;
	struct hclge_pri_shapping_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 453 */;
	struct hclge_nq_to_qs_link_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 452 */;
	struct hclge_qs_to_pri_link_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 451 */;
	struct hclge_pg_to_pri_link_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 450 */;
	struct hclge_priority_weight_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 449 */;
	struct hclge_pg_shapping_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 357 */;
	struct hclge_port_shapping_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 355 */;
	struct hclge_ets_tc_weight_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 324 */;
	char *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 311 */;
	bool cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 287 */;
	struct hclge_dbg_reg_type_info *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 286 */;
	struct hclge_desc cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 186 */[2];
	struct hclge_dbg_bitmap_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 183 */;
	struct device *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 182 */;
	const char *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 180 */;
	void cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 180 */;
	struct hclge_dbg_reg_common_msg *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 127 */;
	struct hclge_dbg_dfx_message *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 126 */;
	struct hnae3_handle *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1202 */;
	u16 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1184 */;
	struct hclge_vport *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1162 */;
	struct hnae3_knic_private_info *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1161 */;
	u32 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1131 */;
	u8 cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1129 */;
	struct hclge_qs_shapping_cmd *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1128 */;
	unsigned long cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1114 */;
	struct hclge_mac_tnl_stats cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1113 */;
	struct hclge_dbg_reg_type_info cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 11 */[];
	struct hclge_desc cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1071 */[HCLGE_CMD_NCL_CONFIG_BD_NUM];
	int *cocci_id/* drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c 1037 */;
}
