cocci_test_suite() {
	const struct port_info *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 979 */;
	struct mngt_pktsched_wr *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 946 */;
	const struct pci_device_id cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 88 */[];
	const struct attribute_group cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 796 */;
	struct attribute *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 789 */[];
	struct device_attribute *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 751 */;
	unsigned int cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 699 */;
	ssize_t (*cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 698 */)(struct net_device *,
										     unsigned int);
	const char *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 697 */;
	size_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 697 */;
	ssize_t (*cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 685 */)(struct net_device *,
										     char *);
	struct device *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 684 */;
	char *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 684 */;
	ssize_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 684 */;
	enum{MAX_TXQ_ENTRIES=16384, MAX_CTRL_TXQ_ENTRIES=1024, MAX_RSPQ_ENTRIES=16384, MAX_RX_BUFFERS=16384, MAX_RX_JUMBO_BUFFERS=16384, MIN_TXQ_ENTRIES=4, MIN_CTRL_TXQ_ENTRIES=4, MIN_RSPQ_ENTRIES=32, MIN_FL_ENTRIES=32,} cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 65 */;
	u16 cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 575 */[RSS_TABLE_SIZE + 1];
	u8 cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 574 */[SGE_QSETS + 1];
	struct cpl_rte_write_req *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 511 */;
	struct cpl_l2t_write_req *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 489 */;
	struct cpl_smt_write_req *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 466 */;
	struct cpl_set_tcb_field *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 460 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 459 */;
	unsigned long cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 443 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 373 */;
	void __exit cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3470 */;
	int __init cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3460 */;
	struct pci_driver cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3452 */;
	struct port_info cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3297 */;
	struct cpl_set_tcb_field cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3261 */;
	const struct net_device *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 321 */;
	const struct adapter_info *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3207 */;
	resource_size_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3206 */;
	const struct pci_device_id *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3203 */;
	struct pci_dev *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3203 */;
	const struct net_device_ops cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3175 */;
	char cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3144 */[80];
	const char *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3139 */[];
	struct msix_entry cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3117 */[SGE_QSETS + 1];
	const struct pci_error_handlers cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3073 */;
	pci_channel_state_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3025 */;
	pci_ers_result_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 3024 */;
	unsigned int cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2995 */[4];
	unsigned short cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2816 */;
	struct adapter cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2813 */;
	struct work_struct *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2811 */;
	const struct adapter_params *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2721 */;
	struct cmac *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2702 */;
	void cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2653 */;
	void *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2622 */;
	netdev_features_t cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2588 */;
	struct sockaddr *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2576 */;
	struct mii_ioctl_data *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2531 */;
	struct ifreq *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2529 */;
	const struct trace_params *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2501 */;
	struct ch_trace cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2500 */;
	u64 cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2447 */[32];
	struct mc7 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2446 */;
	struct ch_pm cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2395 */;
	struct tp_params *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2394 */;
	struct ch_mtus cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2366 */;
	struct ch_mem_range cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2346 */;
	u8 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2345 */;
	struct ch_reg cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2301 */;
	struct sge_qset *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2219 */;
	struct ch_qset_params cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2153 */;
	struct qset_params *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2152 */;
	u32 cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2143 */;
	void __user *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2139 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2108 */;
	struct ethtool_wolinfo *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2101 */;
	__le32 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2045 */;
	struct ethtool_eeprom *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2032 */;
	struct ethtool_coalesce *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 2022 */;
	const struct qset_params *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1957 */;
	struct ethtool_ringparam *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1953 */;
	struct ethtool_pauseparam *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1916 */;
	struct link_config *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1871 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1868 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1805 */;
	enum ethtool_phys_id_state cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1782 */;
	struct ethtool_regs *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1738 */;
	u32 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1732 */;
	u64 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1665 */;
	struct ethtool_stats *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1664 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1619 */;
	const char cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1543 */[][ETH_GSTRING_LEN];
	const struct mac_stats *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1493 */;
	struct net_device_stats *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1488 */;
	struct workqueue_struct *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 148 */;
	struct adapter *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1453 */;
	struct port_info *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1452 */;
	struct net_device *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1450 */;
	int cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1450 */;
	struct t3c_data *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1394 */;
	struct t3cdev *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1391 */;
	struct sge_rspq *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1173 */;
	char cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1119 */[64];
	char cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1100 */;
	u16 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1034 */;
	const __be32 *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1033 */;
	const struct firmware *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1030 */;
	struct cphy *cocci_id/* drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c 1027 */;
}
