cocci_test_suite() {
	enum mlx5_res_type cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 724 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 713 */[MLX5_ST_SZ_DW(query_q_counter_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 701 */[MLX5_ST_SZ_DW(dealloc_q_counter_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 700 */[MLX5_ST_SZ_DW(dealloc_q_counter_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 686 */[MLX5_ST_SZ_DW(alloc_q_counter_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 685 */[MLX5_ST_SZ_DW(alloc_q_counter_in)];
	u16 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 683 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 642 */[MLX5_ST_SZ_DW(destroy_sq_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 641 */[MLX5_ST_SZ_DW(destroy_sq_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 598 */[MLX5_ST_SZ_DW(destroy_rq_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 597 */[MLX5_ST_SZ_DW(destroy_rq_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 595 */;
	u16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 595 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 587 */[MLX5_ST_SZ_DW(dealloc_xrcd_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 586 */[MLX5_ST_SZ_DW(dealloc_xrcd_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 573 */[MLX5_ST_SZ_DW(alloc_xrcd_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 572 */[MLX5_ST_SZ_DW(alloc_xrcd_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 559 */[MLX5_ST_SZ_DW(query_dct_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 548 */[MLX5_ST_SZ_DW(query_qp_in)];
	struct mbox_info cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 510 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 43 */(struct mlx5_core_dev *dev,
									  struct mlx5_core_dct *dct);
	struct mbox_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 402 */;
	struct mbox_info {
		u32 *in;
		u32 *out;
		int inlen;
		int outlen;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 395 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 385 */[MLX5_ST_SZ_DW(set_delay_drop_params_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 384 */[MLX5_ST_SZ_DW(set_delay_drop_params_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 341 */[MLX5_ST_SZ_DW(drain_dct_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 340 */[MLX5_ST_SZ_DW(drain_dct_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 300 */[MLX5_ST_SZ_DW(destroy_qp_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 299 */[MLX5_ST_SZ_DW(destroy_qp_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 298 */[MLX5_ST_SZ_DW(create_qp_out)];
	u32 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 266 */;
	void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 259 */;
	struct mlx5_core_qp *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 238 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 237 */[MLX5_ST_SZ_DW(destroy_dct_in)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 236 */[MLX5_ST_SZ_DW(destroy_dct_out)];
	bool cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 234 */;
	struct mlx5_core_dct *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 234 */;
	struct mlx5_core_dev *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 233 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 233 */;
	struct mlx5_core_rsc_common *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 229 */;
	unsigned long cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 223 */;
	struct mlx5_qp_table *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 200 */;
	struct mlx5_core_dev cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 159 */;
	struct mlx5_priv cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 158 */;
	struct mlx5_qp_table cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 157 */;
	struct mlx5_eqe *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 132 */;
	struct mlx5_priv *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 131 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 129 */;
	struct notifier_block *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 122 */;
	u64 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 100 */;
	void cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/qp.c 100 */;
}
