cocci_test_suite() {
	struct mlx5dr_match_spec cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 998 */;
	void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 995 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 992 */[MLX5_ST_SZ_BYTES(fte_match_set_lyr_2_4)];
	struct mlx5dr_match_parameters *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 990 */;
	enum dr_ste_action_type{DR_STE_ACTION_TYPE_PUSH_VLAN=1, DR_STE_ACTION_TYPE_ENCAP_L3=3, DR_STE_ACTION_TYPE_ENCAP=4,} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 99 */;
	enum dr_ste_tunl_action{DR_STE_TUNL_ACTION_NONE=0, DR_STE_TUNL_ACTION_ENABLE=1, DR_STE_TUNL_ACTION_DECAP=2, DR_STE_TUNL_ACTION_L3_DECAP=3, DR_STE_TUNL_ACTION_POP_VLAN=4,} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 91 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 872 */[4];
	char *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 819 */;
	struct mlx5dr_domain_rx_tx *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 744 */;
	struct mlx5dr_matcher *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 739 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 725 */;
	struct mlx5dr_icm_pool *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 670 */;
	struct mlx5dr_ste_htbl_ctrl *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 657 */;
	struct mlx5dr_htbl_connect_info cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 615 */;
	enum mlx5dr_icm_chunk_size cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 610 */;
	struct mlx5dr_htbl_connect_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 592 */;
	struct mlx5dr_ste_send_info cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 463 */;
	u64 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 367 */;
	struct mlx5dr_ste cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 366 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 365 */[DR_STE_SIZE];
	struct list_head *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 362 */;
	struct mlx5dr_ste_send_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 361 */;
	struct mlx5dr_matcher_rx_tx *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 360 */;
	struct dr_hw_ste_format *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 323 */;
	u8 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 317 */;
	struct mlx5dr_icm_chunk *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 316 */;
	struct mlx5dr_ste_htbl *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 314 */;
	struct mlx5dr_ste *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 313 */;
	void cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 313 */;
	struct mlx5dr_domain *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 2308 */;
	struct mlx5dr_cmd_vport_cap *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 2307 */;
	struct mlx5dr_match_misc3 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 2039 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1842 */;
	struct mlx5dr_cmd_caps *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1837 */;
	struct mlx5dr_match_misc2 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1754 */;
	struct mlx5dr_ste_build *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1650 */;
	struct mlx5dr_match_param *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1649 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1649 */;
	u16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 145 */;
	struct mlx5dr_match_spec *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1434 */;
	bool cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1432 */;
	struct mlx5dr_match_misc *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1285 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 121 */[DR_STE_SIZE_TAG];
	const void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 111 */;
	size_t cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 111 */;
	struct mlx5dr_match_misc3 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1050 */;
	struct dr_hw_ste_format {
		u8 ctrl[DR_STE_SIZE_CTRL];
		u8 tag[DR_STE_SIZE_TAG];
		u8 mask[DR_STE_SIZE_MASK];
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 105 */;
	struct mlx5dr_match_misc2 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1036 */;
	struct mlx5dr_match_misc cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_ste.c 1010 */;
}
