cocci_test_suite() {
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 952 */[DR_STE_SIZE];
	struct dr_qp_init_attr cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 851 */;
	struct mlx5dr_mr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 841 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 809 */;
	struct device *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 808 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 786 */[MLX5_ST_SZ_DW(create_mkey_in)];
	struct mlx5_core_mkey *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 784 */;
	struct mlx5_cqe64 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 74 */;
	u64 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 727 */;
	struct mlx5dr_cq *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 72 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 704 */;
	__be64 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 702 */;
	unsigned int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 700 */;
	struct mlx5_wq_param cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 696 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 695 */[MLX5_ST_SZ_DW(create_cq_out)];
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 694 */[MLX5_ST_SZ_DW(cqc)];
	size_t cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 692 */;
	struct mlx5_uars_page *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 691 */;
	enum mlx5_event cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 685 */;
	struct mlx5_core_cq *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 684 */;
	u16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 647 */;
	enum ib_mtu cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 646 */;
	struct dr_qp_rtr_attr cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 645 */;
	struct dr_qp_rts_attr cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 644 */;
	void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 614 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 613 */[MLX5_ST_SZ_DW(init2rtr_qp_in)];
	struct dr_qp_rtr_attr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 611 */;
	struct mlx5dr_qp *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 610 */;
	struct mlx5_core_dev *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 609 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 609 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 594 */[MLX5_ST_SZ_DW(rtr2rts_qp_in)];
	struct dr_qp_rts_attr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 592 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 576 */[MLX5_ST_SZ_DW(rst2init_qp_in)];
	struct postsend_info cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 556 */;
	struct mlx5dr_action *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 554 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 52 */;
	struct dr_qp_init_attr {
		u32 cqn;
		u32 pdn;
		u32 max_send_wr;
		struct mlx5_uars_page *uar;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 42 */;
	int *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 387 */;
	u32 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 386 */;
	u8 **cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 385 */;
	struct mlx5dr_ste_htbl *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 384 */;
	struct mlx5dr_domain *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 383 */;
	struct dr_qp_rts_attr {
		u8 timeout;
		u8 retry_cnt;
		u8 rnr_retry;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 36 */;
	uintptr_t cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 344 */;
	struct postsend_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 334 */;
	struct mlx5dr_send_ring *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 333 */;
	bool cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 311 */;
	struct list_head *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 287 */;
	struct mlx5dr_ste_send_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 286 */;
	u8 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 285 */;
	struct mlx5dr_ste *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 284 */;
	struct dr_qp_rtr_attr {
		struct mlx5dr_cmd_gid_attr dgid_attr;
		enum ib_mtu mtu;
		u32 qp_num;
		u16 port_num;
		u8 min_rnr_timer;
		u8 sgid_index;
		u16 udp_src_port;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 26 */;
	struct mlx5_wqe_data_seg *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 229 */;
	struct mlx5_wqe_ctrl_seg *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 228 */;
	struct mlx5_wqe_raddr_seg *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 227 */;
	struct dr_data_seg *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 224 */;
	void cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 212 */;
	struct postsend_info {
		struct dr_data_seg write;
		struct dr_data_seg read;
		u64 remote_addr;
		u32 rkey;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 19 */;
	struct dr_data_seg {
		u64 addr;
		u32 length;
		u32 lkey;
		unsigned int send_flags;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 12 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 110 */[MLX5_ST_SZ_DW(qpc)];
	struct dr_qp_init_attr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 108 */;
	struct mlx5_core_qp *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 102 */;
	enum{CQ_OK=0, CQ_EMPTY=-1, CQ_POLL_ERR=-2,} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/steering/dr_send.c 10 */;
}
