cocci_test_suite() {
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 889 */[MLX5_ST_SZ_DW(ptys_reg)];
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 833 */[MLX5E_CONNECTOR_TYPE_NUMBER];
	unsigned long *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 824 */;
	struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 821 */;
	void cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 820 */;
	struct mlx5e_priv *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 791 */;
	struct net_device *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 787 */;
	const unsigned int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 75 */[];
	struct ptys2ethtool_config cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 70 */[MLX5E_EXT_LINK_MODES_NUMBER];
	u8 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 687 */;
	struct ptys2ethtool_config cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 68 */[MLX5E_LINK_MODES_NUMBER];
	struct mlx5_core_dev *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 678 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 678 */;
	u_long cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 667 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 667 */;
	unsigned long cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 651 */;
	const u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 645 */[];
	struct ptys2ethtool_config *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 631 */;
	struct ptys2ethtool_config {
		__ETHTOOL_DECLARE_LINK_MODE_MASK(supported);
		__ETHTOOL_DECLARE_LINK_MODE_MASK(advertised);
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 62 */;
	struct mlx5e_channel *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 527 */;
	struct dim_cq_moder *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 490 */;
	struct ethtool_coalesce *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 488 */;
	struct mlx5e_channels cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 418 */;
	unsigned int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 417 */;
	struct mlx5e_params *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 416 */;
	struct ethtool_channels *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 390 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 39 */;
	struct ethtool_ringparam *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 306 */;
	u64 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 284 */;
	struct ethtool_stats *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 284 */;
	const struct pflag_desc cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 217 */[MLX5E_NUM_PFLAGS];
	struct pflag_desc {
		char name[ETH_GSTRING_LEN];
		mlx5e_pflag_handler handler;
	} cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 212 */;
	int (*cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 210 */)(struct net_device *netdev,
										      bool enable);
	u32 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 201 */;
	struct ptys2ethtool_config **cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 200 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1976 */;
	struct ethtool_rxnfc *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1954 */;
	enum mlx5e_priv_flag cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1904 */;
	struct mlx5e_channels *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1851 */;
	const struct firmware *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1691 */;
	struct ethtool_flash *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1687 */;
	struct ethtool_eeprom *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1651 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1614 */[4];
	struct ethtool_modinfo *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1609 */;
	enum ethtool_phys_id_state cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1585 */;
	struct ethtool_fecparam *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1523 */;
	struct ethtool_wolinfo *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1484 */;
	__u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1399 */;
	struct ethtool_ts_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1368 */;
	struct ethtool_pauseparam *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1315 */;
	const void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1294 */;
	void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1276 */;
	const struct ethtool_tunable *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1275 */;
	u16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1245 */;
	u16 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1232 */;
	struct mlx5e_redirect_rqt_param cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1193 */;
	const u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1163 */;
	const u8 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1163 */;
	const u32 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1162 */;
	struct mlx5e_rss_params *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1146 */;
	u32 (*cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1055 */)(const unsigned long *adver);
	struct mlx5e_port_eth_proto cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1041 */;
	const struct ethtool_link_ksettings *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1038 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1030 */;
	bool cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1030 */;
	const unsigned long *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1030 */;
	unsigned long cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_ethtool.c 1004 */[2];
}
