cocci_test_suite() {
	struct net_device *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 982 */;
	struct mlx5e_rq_stats *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 981 */;
	struct mlx5_cqe64 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 975 */;
	__sum16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 945 */;
	struct mlx5_cqwq *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 87 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 848 */[MAX_PADDING];
	struct ipv6hdr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 827 */;
	struct iphdr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 826 */;
	void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 824 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 822 */;
	__be16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 822 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 822 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 822 */;
	struct ipv6hdr cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 800 */;
	struct iphdr cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 797 */;
	struct ethhdr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 793 */;
	__be16 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 791 */;
	bool cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 790 */;
	int *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 790 */;
	unsigned char *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 751 */;
	__wsum cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 732 */;
	struct tcphdr *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 730 */;
	struct mlx5_cqe64 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 63 */;
	struct mlx5e_icosq cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 590 */;
	struct mlx5e_cq *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 588 */;
	struct hwtstamp_config *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 53 */;
	struct mlx5e_umr_wqe cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 510 */;
	struct mlx5e_umr_wqe *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 490 */;
	struct mlx5_wq_cyc *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 489 */;
	struct mlx5e_icosq *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 488 */;
	struct mlx5e_mpw_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 486 */;
	struct mlx5e_sq_wqe_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 473 */;
	long cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 427 */;
	const void *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 425 */;
	struct device *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 421 */;
	unsigned int cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 410 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 409 */;
	struct mlx5e_dma_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 409 */;
	void cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 407 */;
	struct mlx5e_rx_wqe_cyc *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 335 */;
	u16 cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 330 */;
	struct mlx5e_wqe_frag_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 330 */;
	struct mlx5e_rq *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 330 */;
	struct mlx5e_page_cache *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 217 */;
	struct page *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 187 */;
	u8 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1447 */;
	char *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1445 */;
	struct mlx5e_rq cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1381 */;
	struct mlx5_wq_ll *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1337 */;
	struct mlx5e_rx_wqe_ll *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1336 */;
	struct mlx5_eswitch_rep *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1193 */;
	struct mlx5e_rep_priv *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1192 */;
	struct mlx5e_priv *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1191 */;
	struct mlx5_mini_cqe8 *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 116 */;
	struct mlx5e_cq_decomp *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 115 */;
	struct mlx5_err_cqe *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1138 */;
	struct mlx5e_rq_frag_info *cocci_id/* drivers/net/ethernet/mellanox/mlx5/core/en_rx.c 1096 */;
}
