cocci_test_suite() {
	int *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 927 */;
	size_t cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 915 */;
	u32 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 839 */;
	char cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 820 */[MLXSW_REG_SBIB_LEN];
	enum mlxsw_reg_mpar_i_e cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 808 */;
	char cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 803 */[MLXSW_REG_MPAR_LEN];
	bool cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 784 */;
	struct mlxsw_sp_port *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 783 */;
	enum mlxsw_sp_span_type cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 782 */;
	struct mlxsw_sp_span_entry *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 781 */;
	struct mlxsw_sp_span_inspected_port *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 780 */;
	const struct mlxsw_sp *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 751 */;
	const struct mlxsw_sp_span_entry_ops *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 641 */;
	struct devlink *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 62 */;
	struct mlxsw_sp_span_parms cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 614 */;
	struct mlxsw_sp *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 612 */;
	void cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 611 */;
	const struct mlxsw_sp_span_entry_ops *const cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 574 */[];
	struct __ip6_tnl_parm cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 456 */;
	struct rt6_info cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 441 */;
	struct rt6_info *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 428 */;
	struct dst_entry *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 427 */;
	struct flowi6 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 425 */;
	struct ip6_tnl *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 424 */;
	struct in6_addr *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 421 */;
	struct mlxsw_sp_span_entry cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 42 */;
	const struct mlxsw_sp_span_entry_ops cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 410 */;
	union mlxsw_sp_l3addr cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 356 */;
	struct ip_tunnel_parm cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 355 */;
	struct mlxsw_sp_span_parms *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 353 */;
	struct flowi4 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 322 */;
	struct rtable *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 321 */;
	struct ip_tunnel *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 318 */;
	__be32 *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 316 */;
	__u8 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 261 */;
	struct list_head *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 245 */;
	u8 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 208 */;
	enum mlxsw_reg_spms_state cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 205 */;
	struct mlxsw_sp_bridge_port *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 204 */;
	u16 *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 202 */;
	const struct net_device *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 200 */;
	unsigned char *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 194 */;
	u16 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 170 */;
	u64 cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 17 */;
	void *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 17 */;
	struct bridge_vlan_info cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 168 */;
	struct neighbour *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 134 */;
	unsigned char cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 132 */[ETH_ALEN];
	struct net_device *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 131 */;
	const void *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 130 */;
	struct neigh_table *cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 129 */;
	int cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 129 */;
	char cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 107 */[MLXSW_REG_MPAT_LEN];
	enum mlxsw_reg_mpat_span_type cocci_id/* drivers/net/ethernet/mellanox/mlxsw/spectrum_span.c 102 */;
}
