cocci_test_suite() {
	char cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 987 */;
	struct sk_buff **cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 985 */;
	u16 cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 94 */;
	const char *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 929 */;
	const u8 *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 928 */;
	struct clk *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 926 */;
	const u32 *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 925 */;
	struct fs_platform_info *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 924 */;
	const struct of_device_id *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 921 */;
	struct platform_device *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 919 */;
	const struct of_device_id cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 918 */[];
	const struct net_device_ops cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 904 */;
	int cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 893 */(struct net_device *dev);
	struct ifreq *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 885 */;
	struct fs_enet_private cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 88 */;
	const struct ethtool_ops cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 870 */;
	struct napi_struct *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 86 */;
	const void *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 852 */;
	u32 *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 841 */;
	const struct ethtool_tunable *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 833 */;
	struct ethtool_regs *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 803 */;
	struct ethtool_drvinfo *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 790 */;
	phy_interface_t cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 710 */;
	struct phy_device *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 709 */;
	unsigned long cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 694 */;
	struct fs_enet_private *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 693 */;
	struct net_device *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 691 */;
	void cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 691 */;
	void cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 67 */(struct net_device *dev);
	struct work_struct *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 617 */;
	skb_frag_t *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 492 */;
	netdev_tx_t cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 484 */;
	int cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 416 */;
	cbd_t __iomem *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 415 */;
	struct sk_buff *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 414 */;
	u32 cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 323 */;
	const struct fs_platform_info *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 322 */;
	void *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 318 */;
	irqreturn_t cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 317 */;
	dma_addr_t cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 257 */;
	struct platform_driver cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 1124 */;
	char *cocci_id/* drivers/net/ethernet/freescale/fs_enet/fs_enet-main.c 1010 */;
}
