cocci_test_suite() {
	struct mwifiex_adapter *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 869 */;
	struct mwifiex_ds_tx_ba_stream_tbl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 753 */;
	struct mwifiex_ds_rx_reorder_tbl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 718 */;
	uint16_t cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 705 */;
	struct host_cmd_ds_11n_delba *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 703 */;
	u8 *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 701 */;
	struct mwifiex_rx_reorder_tbl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 682 */;
	struct mwifiex_private *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 680 */;
	int cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 680 */;
	void cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 680 */;
	struct host_cmd_ds_11n_delba cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 655 */;
	struct mwifiex_sta_node *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 606 */;
	u32 cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 593 */;
	struct host_cmd_ds_11n_addba_req cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 592 */;
	struct mwifiex_tx_ba_stream_tbl cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 564 */;
	struct mwifiex_ra_list_tbl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 560 */;
	enum mwifiex_ba_status cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 557 */;
	struct mwifiex_tx_ba_stream_tbl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 516 */;
	struct mwifiex_ie_types_extcap cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 451 */;
	void *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 449 */;
	struct ieee_types_header cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 441 */;
	struct mwifiex_ie_types_2040bssco cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 433 */;
	struct mwifiex_ie_types_chan_list_param_set cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 408 */;
	struct ieee80211_ht_operation cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 388 */;
	struct mwifiex_ie_types_htinfo cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 383 */;
	struct ieee80211_ht_cap *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 38 */;
	struct ieee80211_channel *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 350 */;
	struct mwifiex_ie_types_header cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 337 */;
	struct ieee80211_ht_cap cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 336 */;
	struct mwifiex_ie_types_htcap cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 333 */;
	u8 cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 323 */;
	struct ieee_types_header *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 322 */;
	struct ieee80211_supported_band *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 321 */;
	struct mwifiex_ie_types_extcap *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 319 */;
	struct mwifiex_ie_types_2040bssco *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 318 */;
	struct mwifiex_ie_types_chan_list_param_set *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 317 */;
	struct mwifiex_ie_types_htinfo *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 316 */;
	struct mwifiex_ie_types_htcap *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 315 */;
	u8 **cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 313 */;
	struct mwifiex_bssdescriptor *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 312 */;
	struct host_cmd_ds_11n_cfg cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 287 */;
	struct host_cmd_ds_11n_cfg *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 284 */;
	struct mwifiex_ds_11n_tx_cfg *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 282 */;
	u16 cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 281 */;
	struct host_cmd_ds_command *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 281 */;
	struct host_cmd_ds_amsdu_aggr_ctrl cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 256 */;
	struct host_cmd_ds_amsdu_aggr_ctrl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 251 */;
	struct mwifiex_ds_11n_amsdu_aggr_ctrl *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 249 */;
	struct host_cmd_ds_txbuf_cfg cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 223 */;
	struct host_cmd_ds_txbuf_cfg *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 218 */;
	u16 *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 216 */;
	struct host_cmd_ds_11n_addba_rsp *cocci_id/* drivers/net/wireless/marvell/mwifiex/11n.c 158 */;
}
