cocci_test_suite() {
	struct cmd_ctrl_node *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 989 */;
	struct lbs_private *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 988 */;
	void cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 988 */;
	struct cmd_ds_get_hw_spec cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 91 */;
	struct cmd_ds_reg_access cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 825 */;
	u32 *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 823 */;
	struct ieee80211_country_ie_triplet cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 792 */;
	size_t cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 710 */;
	struct ieee80211_channel *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 705 */;
	enum nl80211_band cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 704 */;
	struct ieee80211_country_ie_triplet *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 703 */;
	struct mrvl_ie_domain_param_set *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 702 */;
	struct cmd_ds_802_11d_domain_info cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 701 */;
	struct ieee80211_supported_band **cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 700 */;
	struct wiphy *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 699 */;
	u8 cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 68 */;
	u16 cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 68 */;
	struct cmd_ds_802_11_rssi cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 669 */;
	s8 *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 667 */;
	uint8_t cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 650 */;
	struct cmd_ds_802_11_rf_channel cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 593 */;
	struct cmd_ds_802_11_monitor_mode cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 564 */;
	s16 cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 536 */;
	struct cmd_ds_802_11_rf_tx_power cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 509 */;
	s16 *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 506 */;
	__le16 *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 484 */;
	struct cmd_ds_802_11_snmp_mib cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 467 */;
	u16 *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 465 */;
	struct cmd_header cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 362 */;
	void *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 34 */;
	struct cmd_ds_802_11_sleep_params cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 266 */;
	struct sleep_params *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 264 */;
	struct cmd_ds_802_11_ps_mode cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 233 */;
	bool cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 231 */;
	struct wol_config cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 201 */;
	uint8_t *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 200 */;
	struct cmd_ds_host_sleep cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 183 */;
	struct wol_config *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 181 */;
	uint32_t cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 180 */;
	unsigned long cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1564 */;
	int (*cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1563 */)(struct lbs_private *,
									      unsigned long,
									      struct cmd_header *);
	struct cmd_header *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1562 */;
	uint16_t cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1561 */;
	int cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1561 */;
	struct cmd_ds_802_11_pa_cfg cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1482 */;
	int8_t cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1479 */;
	struct cmd_ds_802_11_tpc_cfg cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1450 */;
	u8 *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1367 */;
	struct cmd_ds_802_11_ps_mode *cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1306 */;
	unsigned int cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1160 */;
	struct cmd_ctrl_node cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1122 */;
	u32 cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1117 */;
	struct cmd_ds_mac_control cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1084 */;
	struct cmd_ds_802_11_radio_control cocci_id/* drivers/net/wireless/marvell/libertas/cmd.c 1044 */;
}
