cocci_test_suite() {
	u16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 867 */;
	struct swchnlcmd cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 799 */[MAX_RFDEPENDCMD_CNT];
	struct swchnlcmd cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 797 */[MAX_POSTCMD_CNT];
	struct swchnlcmd cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 795 */[MAX_PRECMD_CNT];
	enum swchnlcmd_id cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 768 */;
	struct swchnlcmd *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 766 */;
	struct bb_reg_def *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 76 */;
	enum nl80211_channel_type cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 665 */;
	long cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 610 */;
	enum wireless_mode cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 609 */;
	enum radio_path cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 56 */;
	struct rtl_phy *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 552 */;
	struct rtl_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 551 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 548 */;
	u8 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 548 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 547 */;
	void cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 547 */;
	struct rtl_efuse *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 527 */;
	long *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 495 */;
	struct dig_t *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1562 */;
	enum io_type cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1519 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 146 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1375 */[10];
	long cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1369 */[4][8];
	struct rtl_hal *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1339 */;
	s8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1332 */;
	bool cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1332 */;
	const u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1222 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1219 */[IQK_MAC_REG_NUM];
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1213 */[IQK_ADDA_REG_NUM];
	long cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1207 */[][8];
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1153 */[2];
	u32 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192c/phy_common.c 1118 */;
}
