cocci_test_suite() {
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 79 */;
	struct rtl_ps_ctl *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 75 */;
	struct phy_sts_cck_8192s_t *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 74 */;
	struct rtl_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 73 */;
	struct rtl8192_tx_ring *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 711 */;
	struct rtl_pci *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 710 */;
	bool cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 69 */;
	struct rx_fwinfo_92c *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 68 */;
	__le32 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 672 */;
	struct rx_desc_92c *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 67 */;
	u64 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 668 */;
	struct rtl_stats *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 66 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 65 */;
	void cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 65 */;
	u32 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 638 */;
	dma_addr_t cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 571 */;
	struct ieee80211_key_conf *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 491 */;
	struct tx_desc_92c cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 430 */;
	struct rtl_tcb_desc *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 387 */;
	struct ieee80211_sta *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 385 */;
	struct ieee80211_tx_info *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 384 */;
	struct ieee80211_rx_status *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 298 */;
	u16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 264 */;
	u8 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 261 */;
	struct ieee80211_hdr *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 260 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 26 */;
	s8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 26 */;
	struct rtl_efuse *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 258 */;
	struct rtl_mac *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 257 */;
	long cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 201 */;
	__le16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 16 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192ce/trx.c 14 */;
}
