cocci_test_suite() {
	void *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 639 */;
	u8 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 603 */;
	struct ieee80211_key_conf *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 549 */;
	struct rtl_ps_ctl *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 477 */;
	struct rtl_mac *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 476 */;
	struct rtl_tcb_desc *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 473 */;
	struct ieee80211_sta *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 470 */;
	struct ieee80211_tx_info *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 469 */;
	__le16 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 456 */;
	__le32 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 444 */;
	void cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 444 */;
	struct sk_buff_head *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 437 */;
	struct urb *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 430 */;
	struct rx_desc_92c *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 394 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 361 */;
	struct ieee80211_hdr *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 351 */;
	struct rx_fwinfo_92c *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 348 */;
	struct rtl_stats cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 344 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 341 */;
	struct ieee80211_rx_status *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 339 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 337 */;
	struct rtl_stats *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 283 */;
	struct rtl_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 238 */;
	u16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 235 */;
	__le16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 235 */;
	enum rtl_desc_qsel cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 234 */;
	struct rtl_ep_map *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 153 */;
	struct rtl_usb *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 152 */;
	struct rtl_usb_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 151 */;
	struct rtl_hal *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 150 */;
	bool cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 149 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 146 */;
	int cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/trx.c 146 */;
}
