cocci_test_suite() {
	__le16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 760 */;
	struct ieee80211_hdr *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 757 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 750 */;
	long cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 713 */;
	__le32 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 625 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 622 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 620 */;
	s8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 619 */;
	struct phy_sts_cck_8192s_t *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 618 */;
	struct rtl_phy *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 617 */;
	struct rtl_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 616 */;
	bool cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 612 */;
	struct rx_fwinfo_92c *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 611 */;
	struct rx_desc_92c *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 610 */;
	struct rtl_stats *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 609 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 608 */;
	void cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 608 */;
	u16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 420 */;
	enum nl80211_iftype cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 378 */;
	int cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 378 */;
	struct rtl_usb *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 335 */;
	struct rtl_pci *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 334 */;
	const char *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 33 */;
	enum version_8192c cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 32 */;
	struct rtl_hal *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 31 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 209 */[];
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 203 */[4][6];
	struct rtl_efuse *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 199 */;
	struct rtl_mac *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 198 */;
	u8 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192cu/mac.c 194 */;
}
