cocci_test_suite() {
	struct rtl_efuse *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 895 */;
	struct rtl_phy *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 894 */;
	struct rtl_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 893 */;
	bool cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 891 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 891 */;
	u16 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 801 */;
	u32 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 799 */;
	int cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 798 */;
	struct bb_reg_def *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 78 */;
	struct rtl_hal *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 637 */;
	enum radio_path cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 635 */;
	struct rtl8192_tx_ring *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 519 */;
	struct rtl_ps_ctl *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 516 */;
	struct rtl_pci_priv *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 514 */;
	enum rf_pwrstate cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 511 */;
	struct swchnlcmd cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 334 */[MAX_RFDEPENDCMD_CNT];
	struct swchnlcmd cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 332 */[MAX_POSTCMD_CNT];
	struct swchnlcmd cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 330 */[MAX_PRECMD_CNT];
	enum swchnlcmd_id cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 303 */;
	struct swchnlcmd *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 302 */;
	struct rtl_mac *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 239 */;
	enum nl80211_channel_type cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 234 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 17 */;
	struct dig_t *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 1340 */;
	enum fwcmd_iotype cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 1337 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 1152 */[2];
	u8 cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 1138 */;
	u8 *cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 1138 */;
	void cocci_id/* drivers/net/wireless/realtek/rtlwifi/rtl8192se/phy.c 1137 */;
}
