cocci_test_suite() {
	struct rtw_fifo_conf *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 933 */;
	int cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 871 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 789 */;
	struct rtw_chip_info *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 785 */;
	u32 *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 782 */;
	u8 *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 781 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 721 */[2];
	struct rtw_rsvd_page *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 686 */;
	bool cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 684 */;
	enum rtw_rsvd_packet_type cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 683 */;
	struct rtw_dev *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 683 */;
	void cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 683 */;
	unsigned int cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 665 */;
	struct rtw_tx_pkt_info cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 654 */;
	struct rtw_sta_info *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 62 */;
	struct rtw_fw_iter_ra_data *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 61 */;
	struct rtw_lps_pg_info_hdr *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 593 */;
	struct ieee80211_sta *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 59 */;
	void *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 59 */;
	struct rtw_lps_pg_dpk_hdr *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 567 */;
	struct rtw_dpk_info *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 566 */;
	struct ieee80211_vif *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 544 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 544 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 543 */;
	struct rtw_fw_iter_ra_data {
		struct rtw_dev *rtwdev;
		u8 *payload;
	} cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 54 */;
	struct rtw_lps_conf *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 501 */;
	u8 cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 372 */[H2C_PKT_SIZE];
	struct rtw_coex_info_req *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 343 */;
	u32 cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 32 */;
	u16 cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 32 */;
	struct rtw_iqk_para *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 305 */;
	struct rtw_efuse *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 283 */;
	struct rtw_hal *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 282 */;
	struct rtw_c2h_cmd *cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 128 */;
	struct rtw_fw_iter_ra_data cocci_id/* drivers/net/wireless/realtek/rtw88/fw.c 115 */;
}
