cocci_test_suite() {
	s8 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 997 */;
	__le16 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 882 */;
	u16 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 879 */;
	struct pktq *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 829 */;
	struct brcmf_fws_hanger_item *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 828 */;
	bool (*cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 825 */)(struct sk_buff *,
											      void *);
	enum brcmf_fws_hanger_item_state cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 687 */;
	struct brcmf_fws_hanger *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 684 */;
	struct sk_buff **cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 622 */;
	int *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 569 */;
	enum brcmf_fws_tlv_type cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 542 */;
	const int cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 518 */[];
	struct brcmf_fws_info {
		struct brcmf_pub *drvr;
		spinlock_t spinlock;
		ulong flags;
		struct brcmf_fws_stats stats;
		struct brcmf_fws_hanger hanger;
		enum brcmf_fws_fcmode fcmode;
		bool fw_signals;
		bool bcmc_credit_check;
		struct brcmf_fws_macdesc_table desc;
		struct workqueue_struct *fws_wq;
		struct work_struct fws_dequeue_work;
		u32 fifo_enqpkt[BRCMF_FWS_FIFO_COUNT];
		int fifo_credit[BRCMF_FWS_FIFO_COUNT];
		int init_fifo_credit[BRCMF_FWS_FIFO_COUNT];
		int credits_borrowed[BRCMF_FWS_FIFO_AC_VO + 1];
		int deq_node_pos[BRCMF_FWS_FIFO_COUNT];
		u32 fifo_credit_map;
		u32 fifo_delay_map;
		unsigned long borrow_defer_timestamp;
		bool bus_flow_blocked;
		bool creditmap_received;
		u8 mode;
		bool avoid_queueing;
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 489 */;
	struct brcmf_fws_stats {
		u32 tlv_parse_failed;
		u32 tlv_invalid_type;
		u32 header_only_pkt;
		u32 header_pulls;
		u32 pkt2bus;
		u32 send_pkts[5];
		u32 requested_sent[5];
		u32 generic_error;
		u32 mac_update_failed;
		u32 mac_ps_update_failed;
		u32 if_update_failed;
		u32 packet_request_failed;
		u32 credit_request_failed;
		u32 rollback_success;
		u32 rollback_failed;
		u32 delayq_full_error;
		u32 supprq_full_error;
		u32 txs_indicate;
		u32 txs_discard;
		u32 txs_supp_core;
		u32 txs_supp_ps;
		u32 txs_tossed;
		u32 txs_host_tossed;
		u32 bus_flow_block;
		u32 fws_flow_block;
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 461 */;
	struct brcmf_fws_macdesc_table {
		struct brcmf_fws_mac_descriptor nodes[BRCMF_FWS_MAC_DESC_TABLE_SIZE];
		struct brcmf_fws_mac_descriptor iface[BRCMF_MAX_IFS];
		struct brcmf_fws_mac_descriptor other;
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 455 */;
	struct brcmf_fws_hanger {
		u32 pushed;
		u32 popped;
		u32 failed_to_push;
		u32 failed_to_pop;
		u32 failed_slotfind;
		u32 slot_pos;
		struct brcmf_fws_hanger_item items[BRCMF_FWS_HANGER_MAXITEMS];
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 445 */;
	struct brcmf_fws_hanger_item {
		enum brcmf_fws_hanger_item_state state;
		struct sk_buff *pkt;
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 429 */;
	enum brcmf_fws_hanger_item_state{BRCMF_FWS_HANGER_ITEM_STATE_FREE=1, BRCMF_FWS_HANGER_ITEM_STATE_INUSE, BRCMF_FWS_HANGER_ITEM_STATE_INUSE_SUPPRESSED,} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 416 */;
	struct brcmf_fws_mac_descriptor {
		char name[16];
		u8 occupied;
		u8 mac_handle;
		u8 interface_id;
		u8 state;
		bool suppressed;
		u8 generation;
		u8 ac_bitmap;
		u8 requested_credit;
		u8 requested_packet;
		u8 ea[ETH_ALEN];
		u8 seq[BRCMF_FWS_FIFO_COUNT];
		struct pktq psq;
		int transit_count;
		int suppr_transit_count;
		bool send_tim_signal;
		u8 traffic_pending_bmp;
		u8 traffic_lastreported_bmp;
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 386 */;
	enum brcmf_fws_mac_desc_state{BRCMF_FWS_STATE_OPEN=1, BRCMF_FWS_STATE_CLOSE,} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 365 */;
	enum brcmf_fws_fcmode{BRCMF_FWS_FCMODE_NONE, BRCMF_FWS_FCMODE_IMPLIED_CREDIT, BRCMF_FWS_FCMODE_EXPLICIT_CREDIT,} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 359 */;
	enum brcmf_fws_txstatus{BRCMF_FWS_TXSTATUS_DISCARD, BRCMF_FWS_TXSTATUS_CORE_SUPPRESS, BRCMF_FWS_TXSTATUS_FW_PS_SUPPRESS, BRCMF_FWS_TXSTATUS_FW_TOSSED, BRCMF_FWS_TXSTATUS_HOST_TOSSED,} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 351 */;
	enum brcmf_fws_fifo{BRCMF_FWS_FIFO_FIRST, BRCMF_FWS_FIFO_AC_BK=BRCMF_FWS_FIFO_FIRST, BRCMF_FWS_FIFO_AC_BE, BRCMF_FWS_FIFO_AC_VI, BRCMF_FWS_FIFO_AC_VO, BRCMF_FWS_FIFO_BCMC, BRCMF_FWS_FIFO_ATIM, BRCMF_FWS_FIFO_COUNT,} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 326 */;
	bool cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2491 */;
	u32 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2344 */;
	struct brcmf_pub *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2340 */;
	struct brcmf_fws_stats *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2275 */;
	struct brcmf_bus *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2274 */;
	struct seq_file *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2272 */;
	void *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2272 */;
	int cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2272 */;
	struct brcmf_fws_info cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2213 */;
	struct work_struct *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2203 */;
	struct brcmf_fws_mac_descriptor *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2171 */;
	struct brcmf_fws_info *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2170 */;
	struct brcmf_if *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2168 */;
	void cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2168 */;
	struct ethhdr *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2122 */;
	struct brcmf_skbuff_cb *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2100 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2097 */;
	u8 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 2060 */;
	struct brcmf_skbuff_cb {
		u16 bus_flags;
		u16 if_flags;
		u32 htod;
		u16 htod_seq;
		enum brcmf_fws_skb_state state;
		struct brcmf_fws_mac_descriptor *mac;
	} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 199 */;
	s32 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1860 */;
	struct brcmf_skb_reorder_data *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1853 */;
	s16 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1851 */;
	enum brcmf_fws_skb_state{BRCMF_FWS_SKBSTATE_NEW, BRCMF_FWS_SKBSTATE_DELAYED, BRCMF_FWS_SKBSTATE_SUPPRESSED, BRCMF_FWS_SKBSTATE_TIM,} cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 179 */;
	struct sk_buff_head cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1684 */;
	struct brcmf_ampdu_rx_reorder *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1683 */;
	const struct brcmf_event_msg *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1641 */;
	__le32 cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1598 */;
	u8 *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1596 */;
	struct brcmf_fws_mac_descriptor cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1354 */;
	struct sk_buff_head *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1256 */;
	u32 *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1253 */;
	enum brcmf_fws_skb_state cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 1248 */;
	const char *cocci_id/* drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.c 113 */;
}
