cocci_test_suite() {
	unsigned long long cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 991 */;
	unsigned int cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 988 */;
	u64 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 975 */;
	const char *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 967 */;
	void cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 966 */;
	typeof(a) cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 955 */;
	struct b43_dmadesc32 *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 90 */;
	struct b43_dmadesc_meta cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 849 */;
	struct b43_dmadesc32 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 744 */;
	struct b43_dmadesc_meta **cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 74 */;
	struct b43_dmadesc64 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 729 */;
	struct b43_dmadesc_meta *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 640 */;
	struct b43_dmadesc_generic *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 639 */;
	struct b43_dmaring *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 636 */;
	int cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 636 */;
	gfp_t cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 594 */;
	struct b43_plcp_hdr6 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 587 */;
	unsigned char *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 580 */;
	struct b43_rxhdr_fw4 *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 579 */;
	size_t cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 540 */;
	u16 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 418 */;
	enum b43_addrtype cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 38 */;
	u32 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 37 */;
	dma_addr_t cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 37 */;
	struct b43_dma *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 37 */;
	const u16 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 319 */[];
	struct b43_dmadesc64 *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 182 */;
	enum b43_dmatype cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1764 */;
	bool cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1762 */;
	struct b43_wldev *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1761 */;
	s32 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1627 */;
	int *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1582 */;
	const struct b43_dma_ops cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 152 */;
	struct ieee80211_tx_info *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1499 */;
	struct b43_private_tx_info *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1486 */;
	u8 cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1425 */;
	const struct b43_txstatus cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1420 */;
	const struct b43_dma_ops *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1417 */;
	const struct b43_txstatus *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1415 */;
	struct ieee80211_hdr *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1343 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1340 */;
	unsigned long cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1294 */;
	u8 *cocci_id/* drivers/net/wireless/broadcom/b43/dma.c 1195 */;
}
