cocci_test_suite() {
	const __be16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 910 */;
	const u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 836 */[];
	enum nvm_offsets{SUBSYSTEM_ID=0x0A, HW_ADDR=0x15, NVM_SW_SECTION=0x1C0, NVM_VERSION=0, RADIO_CFG=1, SKU=2, N_HW_ADDRS=3, NVM_CHANNELS=0x1E0 - NVM_SW_SECTION, NVM_CALIB_SECTION=0x2B8, XTAL_CALIB=0x316 - NVM_CALIB_SECTION, NVM_CHANNELS_SDP=0,} cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 83 */;
	const u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 788 */;
	__le32 cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 786 */;
	u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 786 */;
	void cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 786 */;
	__le32 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 760 */;
	const __le16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 753 */;
	const void *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 682 */;
	struct ieee80211_supported_band *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 659 */;
	struct ieee80211_sband_iftype_data cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 494 */[];
	unsigned int cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 411 */;
	struct ieee80211_sta_vht_cap *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 405 */;
	__le16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 340 */;
	const u16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 318 */;
	struct ieee80211_channel *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 315 */;
	const void *constcocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 310 */;
	struct device *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 308 */;
	const struct iwl_cfg *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 259 */;
	u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 258 */;
	u32 cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 258 */;
	enum nl80211_band cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 258 */;
	int cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 258 */;
	enum iwl_nvm_channel_flags{NVM_CHANNEL_VALID=BIT(0), NVM_CHANNEL_IBSS=BIT(1), NVM_CHANNEL_ACTIVE=BIT(3), NVM_CHANNEL_RADAR=BIT(4), NVM_CHANNEL_INDOOR_ONLY=BIT(5), NVM_CHANNEL_GO_CONCURRENT=BIT(6), NVM_CHANNEL_UNIFORM=BIT(7), NVM_CHANNEL_20MHZ=BIT(8), NVM_CHANNEL_40MHZ=BIT(9), NVM_CHANNEL_80MHZ=BIT(10), NVM_CHANNEL_160MHZ=BIT(11), NVM_CHANNEL_DC_HIGH=BIT(12),} cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 212 */;
	struct ieee80211_rate cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 174 */[];
	void *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1425 */;
	size_t cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1424 */;
	struct iwl_nvm_get_info_rsp_v3 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1421 */;
	struct iwl_nvm_get_info_rsp *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1420 */;
	const u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 142 */[];
	bool cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1408 */;
	struct iwl_host_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1401 */;
	struct iwl_nvm_get_info cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1399 */;
	const struct iwl_fw *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1397 */;
	struct iwl_trans *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1396 */;
	struct iwl_nvm_data *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1396 */;
	const __le32 *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1254 */;
	const struct {
		__le16 word1;
		__le16 word2;
		u8 data[];
	} *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1246 */;
	const struct firmware *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1245 */;
	struct iwl_nvm_section *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1241 */;
	const char *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1240 */;
	enum nvm_sku_bits{NVM_SKU_CAP_BAND_24GHZ=BIT(0), NVM_SKU_CAP_BAND_52GHZ=BIT(1), NVM_SKU_CAP_11N_ENABLE=BIT(2), NVM_SKU_CAP_11AC_ENABLE=BIT(3), NVM_SKU_CAP_MIMO_DISABLE=BIT(5),} cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 122 */;
	struct ieee80211_reg_rule *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1092 */;
	struct ieee80211_regdomain *cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1082 */;
	u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 1040 */;
	enum ext_nvm_offsets{MAC_ADDRESS_OVERRIDE_EXT_NVM=1, NVM_VERSION_EXT_NVM=0, RADIO_CFG_FAMILY_EXT_NVM=0, SKU_FAMILY_8000=2, N_HW_ADDRS_FAMILY_8000=3, NVM_CHANNELS_EXTENDED=0, NVM_LAR_OFFSET_OLD=0x4C7, NVM_LAR_OFFSET=0x507, NVM_LAR_ENABLED=0x7,} cocci_id/* drivers/net/wireless/intel/iwlwifi/iwl-nvm-parse.c 104 */;
}
