cocci_test_suite() {
	struct ieee80211_key_conf *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 996 */;
	struct iwl_wep_key cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 957 */;
	struct iwl_wep_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 948 */;
	size_t cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 948 */;
	struct iwl_wep_cmd *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 947 */;
	u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 945 */[sizeof(struct iwl_wep_cmd) + sizeof(struct iwl_wep_key) * WEP_KEYS_MAX];
	struct iwl_host_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 91 */;
	struct iwl_addsta_cmd *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 88 */;
	struct iwl_rx_packet *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 82 */;
	struct iwl_rx_cmd_buffer *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 80 */;
	void cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 80 */;
	int cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 791 */;
	struct iwl_link_quality_cmd *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 789 */;
	struct iwl_rxon_context *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 788 */;
	bool cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 787 */;
	struct iwl_priv *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 787 */;
	struct iwl_link_quality_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 651 */;
	const struct iwl_link_quality_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 650 */;
	const u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 518 */;
	struct iwl_add_sta_resp *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 51 */;
	struct iwl_rem_sta_resp *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 412 */;
	struct iwl_rem_sta_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 411 */;
	struct iwl_station_entry cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 401 */;
	struct iwl_addsta_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 335 */;
	u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 334 */;
	u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 331 */;
	struct ieee80211_sta *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 331 */;
	const u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 330 */;
	void *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 309 */;
	struct iwl_station_priv *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 307 */;
	struct iwl_station_entry *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 245 */;
	__le32 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 228 */;
	const u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 20 */[ETH_ALEN];
	u32 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 189 */;
	struct ieee80211_sta_ht_cap *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 155 */;
	__le32 *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 153 */;
	u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1365 */;
	u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1209 */[5];
	struct ieee80211_key_seq cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1208 */;
	__le16 cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1162 */;
	u16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1138 */;
	struct ieee80211_vif *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1136 */;
	struct iwl_vif_priv *cocci_id/* drivers/net/wireless/intel/iwlwifi/dvm/sta.c 1066 */;
}
