cocci_test_suite() {
	__le16 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 99 */;
	struct iwl_gen3_bc_tbl *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 95 */;
	struct iwlagn_scd_bc_tbl *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 93 */;
	const char *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 920 */;
	const void *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 869 */;
	struct iwl_cmd_header_wide cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 698 */;
	u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 695 */[IWL_MAX_CMD_TBS_PER_TFD];
	const u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 694 */[IWL_MAX_CMD_TBS_PER_TFD];
	unsigned long cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 687 */;
	struct iwl_host_cmd *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 681 */;
	struct iwl_tx_cmd_gen3 *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 639 */;
	struct iwl_device_cmd **cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 606 */;
	struct iwl_tx_cmd_gen3 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 559 */;
	struct iwl_tx_cmd_gen2 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 552 */;
	bool cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 549 */;
	struct iwl_cmd_meta *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 543 */;
	struct iwl_txq *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 540 */;
	struct iwl_cmd_header cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 486 */;
	const skb_frag_t *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 431 */;
	__be16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 317 */;
	dma_addr_t cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 302 */;
	struct ethhdr cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 270 */;
	struct tso_t cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 258 */;
	struct page **cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 257 */;
	struct iwl_tso_hdr_page *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 256 */;
	u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 255 */;
	u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 254 */;
	unsigned int cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 252 */;
	struct ieee80211_hdr *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 251 */;
	struct iwl_tx_cmd_gen2 *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 250 */;
	void *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 250 */;
	struct iwl_trans_pcie *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 249 */;
	u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 246 */;
	struct iwl_device_cmd *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 246 */;
	struct iwl_tfh_tfd *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 245 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 244 */;
	struct iwl_trans *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 243 */;
	int cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 243 */;
	struct iwl_tfh_tb *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 222 */;
	void cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 187 */;
	struct iwl_host_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1230 */;
	struct iwl_tx_queue_cfg_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1225 */;
	u32 cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1176 */;
	struct iwl_tx_queue_cfg_rsp *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1174 */;
	struct iwlagn_scd_bc_tbl cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1141 */;
	struct iwl_gen3_bc_tbl cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1140 */;
	struct iwl_txq **cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1128 */;
	struct device *cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 1076 */;
	struct iwl_tfh_tb cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 105 */;
	struct iwl_tfh_tfd cocci_id/* drivers/net/wireless/intel/iwlwifi/pcie/tx-gen2.c 104 */;
}
