cocci_test_suite() {
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 766 */[100];
	struct dentry *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 764 */;
	struct ieee80211_vif cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 742 */;
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 733 */[10];
	u16 cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 703 */;
	struct iwl_dbgfs_pm *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 70 */;
	int *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 692 */;
	u8 *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 688 */;
	void *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 688 */;
	void cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 688 */;
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 679 */[8];
	u16 *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 660 */;
	struct iwl_mvm_phy_ctxt *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 641 */;
	bool cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 626 */;
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 613 */[20];
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 592 */[sizeof(format) + 1];
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 585 */[];
	u8 cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 552 */;
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 513 */[64];
	s64 cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 512 */;
	u64 cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 511 */;
	u32 cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 510 */;
	struct iwl_beacon_filter_cmd cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 456 */;
	const size_t cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 455 */;
	int cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 454 */;
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 453 */[256];
	struct iwl_mvm_vif *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 452 */;
	struct ieee80211_vif *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 451 */;
	loff_t *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 449 */;
	size_t cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 449 */;
	char __user *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 448 */;
	struct file *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 447 */;
	ssize_t cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 447 */;
	enum iwl_dbgfs_bf_mask cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 355 */;
	struct iwl_mvm *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 354 */;
	char *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 350 */;
	struct iwl_dbgfs_bf *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 309 */;
	struct iwl_mvm_sta *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 280 */;
	char cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 230 */[512];
	struct ieee80211_chanctx_conf *cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 229 */;
	enum iwl_dbgfs_pm_mask cocci_id/* drivers/net/wireless/intel/iwlwifi/mvm/debugfs-vif.c 132 */;
}
