cocci_test_suite() {
	struct fft_sample_tlv cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 85 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 72 */;
	u32 cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 71 */;
	u16 cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 70 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 69 */[sizeof(*fft_sample) + SPECTRAL_ATH10K_MAX_NUM_BINS];
	struct fft_sample_ath10k *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 68 */;
	u64 cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 66 */;
	const struct phyerr_fft_report *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 65 */;
	struct wmi_phyerr_ev_arg *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 64 */;
	void cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 554 */;
	int cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 529 */;
	struct rchan_callbacks cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 500 */;
	int *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 480 */;
	size_t cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 48 */;
	struct rchan_buf *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 479 */;
	umode_t cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 478 */;
	const char *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 476 */;
	struct dentry *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 476 */;
	unsigned long cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 442 */;
	unsigned int cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 422 */;
	char cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 421 */[32];
	const struct file_operations cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 356 */;
	const char __user *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 302 */;
	char *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 277 */;
	loff_t *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 274 */;
	struct file *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 273 */;
	char __user *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 273 */;
	ssize_t cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 273 */;
	uint8_t cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 24 */;
	s8 cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 24 */;
	struct wmi_vdev_spectral_conf_arg cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 213 */;
	enum ath10k_spectral_mode cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 211 */;
	typeof(*arvif) cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 176 */;
	struct ath10k_vif *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 161 */;
	struct ath10k *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 161 */;
	u8 *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 136 */;
	const struct fft_sample_tlv *cocci_id/* drivers/net/wireless/ath/ath10k/spectral.c 12 */;
}
