cocci_test_suite() {
	bool *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 947 */;
	struct ath10k_sdio_irq_proc_regs *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 888 */;
	u32 cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 692 */[ATH10K_SDIO_MAX_RX_MSGS];
	u32 cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 525 */[];
	size_t *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 491 */;
	struct ath10k_htc_hdr *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 489 */;
	struct ath10k_sdio_rx_data *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 488 */;
	int *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 377 */;
	size_t cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 30 */;
	void __exit cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 2147 */;
	int __init cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 2136 */;
	struct sdio_driver cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 2125 */;
	const struct sdio_device_id cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 2115 */[];
	struct ath10k_sdio_irq_enable_regs cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 2024 */;
	struct ath10k_sdio_irq_proc_regs cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 2016 */;
	struct ath10k_bus_params cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1990 */;
	enum ath10k_hw_rev cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1988 */;
	const struct sdio_device_id *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1984 */;
	struct device *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1967 */;
	const struct ath10k_hif_ops cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1938 */;
	u8 *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1916 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1867 */;
	bool cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1845 */;
	enum ath10k_htc_ep_id cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1844 */;
	struct ath10k_htc *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1842 */;
	u16 cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1838 */;
	struct completion cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1738 */;
	const void *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1627 */;
	__le32 *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1607 */;
	struct ath10k_hif_sg_item *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1472 */;
	enum ath10k_firmware_mode cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1400 */;
	struct ath10k_sdio_irq_enable_regs *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1383 */;
	struct ath10k_sdio_irq_data *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1382 */;
	struct completion *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1317 */;
	unsigned char cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 131 */;
	struct sdio_func *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 130 */;
	struct ath10k_sdio cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1298 */;
	struct work_struct *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1296 */;
	int cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1278 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1277 */;
	struct ath10k_htc_ep *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1276 */;
	struct ath10k_sdio_bus_request *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1274 */;
	struct ath10k *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1273 */;
	void cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1273 */;
	struct ath10k_sdio_bus_request cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1253 */;
	struct ath10k_sdio *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1242 */;
	u32 *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1146 */;
	void *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1145 */;
	struct mmc_command cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 112 */;
	unsigned char *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 110 */;
	unsigned int cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 109 */;
	struct mmc_card *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 108 */;
	unsigned long cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1078 */;
	u32 cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1077 */;
	struct ath10k_mbox_info *cocci_id/* drivers/net/wireless/ath/ath10k/sdio.c 1032 */;
}
