cocci_test_suite() {
	struct ieee80211_supported_band *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 939 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 913 */;
	struct amsdu_subframe_hdr {
		u8 dst[ETH_ALEN];
		u8 src[ETH_ALEN];
		__be16 len;
	}__packed cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 905 */;
	enum htt_rx_mpdu_encrypt_type cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 881 */;
	void *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 86 */;
	struct timer_list *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 750 */;
	struct htt_rx_in_ord_ind *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 622 */;
	struct htt_rx_in_ord_msdu_desc_ext *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 555 */;
	struct htt_rx_in_ord_msdu_desc_ext **cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 548 */;
	struct htt_rx_in_ord_msdu_desc *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 479 */;
	struct htt_rx_in_ord_msdu_desc **cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 472 */;
	unsigned int cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 463 */;
	struct hlist_node *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 43 */;
	const struct ath10k_htt_rx_ops cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 4034 */;
	struct htt_resp cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3862 */;
	struct htt_peer_unmap_event cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3773 */;
	struct htt_peer_map_event cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3764 */;
	enum htt_t2h_msg_type cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3730 */;
	struct htt_security_indication *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3694 */;
	u32 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3633 */;
	u16 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3632 */;
	struct ath10k_peer *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3631 */;
	struct ieee80211_sta *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3630 */;
	struct ath10k_10_2_peer_tx_stats *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3629 */;
	struct ath10k_pktlog_hdr *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3627 */;
	u8 *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3625 */;
	struct htt_rx_desc cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 360 */;
	struct htt_resp_hdr cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3583 */;
	__le32 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3581 */;
	struct htt_per_peer_tx_stats_ind *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3574 */;
	struct htt_resp *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3572 */;
	struct rate_info cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3460 */;
	struct ath10k_htt_tx_stats *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3335 */;
	struct rate_info *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3334 */;
	s8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3332 */;
	struct ath10k_per_peer_tx_stats *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3331 */;
	struct ath10k_sta *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3330 */;
	struct ath10k *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3329 */;
	void cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3328 */;
	const u8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3315 */[];
	bool cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3304 */;
	enum htt_tx_mode_switch_mode cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3209 */;
	struct ath10k_txq *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3206 */;
	const struct htt_tx_mode_switch_record *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3204 */;
	const struct htt_resp *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3175 */;
	const __le32 *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3050 */;
	struct htt_tx_fetch_record *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3044 */;
	struct ieee80211_txq *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 3042 */;
	struct htt_rx_offload_msdu *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2881 */;
	struct htt_rx_delba *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2787 */;
	struct ath10k_vif *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2749 */;
	struct htt_rx_addba *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2747 */;
	struct htt_data_tx_ppdu_dur *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2717 */;
	u64 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 27 */;
	struct htt_data_tx_compl_ppdu_dur *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2631 */;
	struct htt_tx_done cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2625 */;
	struct htt_rx_indication *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2592 */;
	struct htt_rx_indication_mpdu_range cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2480 */;
	enum htt_rx_tkip_demic_type cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2443 */;
	struct htt_rx_fragment_indication *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2439 */;
	int cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 24 */(struct sk_buff *skb);
	__le16 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2341 */;
	__le64 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2290 */;
	struct fw_rx_desc_hl *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2153 */;
	struct htt_rx_indication_mpdu_range *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2152 */;
	enum htt_rx_pn_check_type cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2147 */;
	union htt_rx_pn_t cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2093 */;
	enum htt_security_types cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2092 */;
	enum htt_txrx_sec_cast_type cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2091 */;
	struct htt_rx_indication_hl *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2088 */;
	union htt_rx_pn_t *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2065 */;
	struct htt_hl_rx_desc *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2064 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2022 */[RX_HTT_HDR_STATUS_LEN];
	enum ath10k_pkt_rx_err cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2021 */;
	struct sk_buff_head cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 2015 */;
	unsigned long *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1997 */;
	struct ieee80211_rx_status *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1975 */;
	struct sk_buff_head *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1974 */;
	enum rx_msdu_decap_format cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1951 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1741 */[64];
	enum ath10k_pkt_rx_err *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1733 */;
	struct rfc1042_hdr cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1587 */;
	struct ethhdr cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1584 */;
	u8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1560 */[ETH_ALEN];
	struct ethhdr *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1557 */;
	const u8 cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1553 */[64];
	struct amsdu_subframe_hdr cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1545 */;
	unsigned long cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 152 */;
	dma_addr_t cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 134 */;
	struct sk_buff *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 133 */;
	struct ath10k_skb_rxcb *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 132 */;
	struct htt_rx_desc *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 131 */;
	struct ath10k_htt *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 129 */;
	int cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 129 */;
	char cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1284 */[32];
	struct ieee80211_hdr *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1250 */;
	char *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1250 */;
	size_t cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1250 */;
	const char *const cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1239 */[];
	struct cfg80211_chan_def cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1113 */;
	struct ieee80211_channel *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1110 */;
	struct cfg80211_chan_def *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1105 */;
	struct ieee80211_chanctx_conf *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1102 */;
	struct ieee80211_hw *cocci_id/* drivers/net/wireless/ath/ath10k/htt_rx.c 1101 */;
}
