cocci_test_suite() {
	struct ubi_fm_volhdr cocci_id/* drivers/mtd/ubi/fastmap.c 91 */;
	struct ubi_fm_eba cocci_id/* drivers/mtd/ubi/fastmap.c 89 */;
	struct ubi_fm_ec cocci_id/* drivers/mtd/ubi/fastmap.c 88 */;
	struct ubi_fm_scan_pool cocci_id/* drivers/mtd/ubi/fastmap.c 86 */;
	struct ubi_fm_hdr cocci_id/* drivers/mtd/ubi/fastmap.c 85 */;
	unsigned long long cocci_id/* drivers/mtd/ubi/fastmap.c 809 */;
	__be32 cocci_id/* drivers/mtd/ubi/fastmap.c 714 */;
	struct ubi_fm_sb cocci_id/* drivers/mtd/ubi/fastmap.c 570 */;
	void *cocci_id/* drivers/mtd/ubi/fastmap.c 562 */;
	size_t cocci_id/* drivers/mtd/ubi/fastmap.c 560 */;
	struct ubi_fm_eba *cocci_id/* drivers/mtd/ubi/fastmap.c 558 */;
	struct ubi_fm_volhdr *cocci_id/* drivers/mtd/ubi/fastmap.c 557 */;
	struct ubi_fm_ec *cocci_id/* drivers/mtd/ubi/fastmap.c 556 */;
	struct ubi_fm_scan_pool *cocci_id/* drivers/mtd/ubi/fastmap.c 555 */;
	struct ubi_fm_hdr *cocci_id/* drivers/mtd/ubi/fastmap.c 554 */;
	struct ubi_fm_sb *cocci_id/* drivers/mtd/ubi/fastmap.c 553 */;
	struct list_head cocci_id/* drivers/mtd/ubi/fastmap.c 550 */;
	struct rb_node *cocci_id/* drivers/mtd/ubi/fastmap.c 521 */;
	__be32 *cocci_id/* drivers/mtd/ubi/fastmap.c 401 */;
	unsigned long long *cocci_id/* drivers/mtd/ubi/fastmap.c 401 */;
	unsigned long *cocci_id/* drivers/mtd/ubi/fastmap.c 35 */;
	unsigned long cocci_id/* drivers/mtd/ubi/fastmap.c 23 */;
	struct ubi_ainf_peb cocci_id/* drivers/mtd/ubi/fastmap.c 213 */;
	struct rb_node **cocci_id/* drivers/mtd/ubi/fastmap.c 208 */;
	void cocci_id/* drivers/mtd/ubi/fastmap.c 203 */;
	u8 cocci_id/* drivers/mtd/ubi/fastmap.c 176 */;
	struct ubi_ainf_volume *cocci_id/* drivers/mtd/ubi/fastmap.c 175 */;
	struct ubi_vid_hdr *cocci_id/* drivers/mtd/ubi/fastmap.c 1446 */;
	struct ubi_vid_io_buf *cocci_id/* drivers/mtd/ubi/fastmap.c 1445 */;
	struct ubi_wl_entry *cocci_id/* drivers/mtd/ubi/fastmap.c 1444 */;
	struct ubi_fastmap_layout *cocci_id/* drivers/mtd/ubi/fastmap.c 1443 */;
	long long cocci_id/* drivers/mtd/ubi/fastmap.c 1392 */;
	struct ubi_ec_hdr *cocci_id/* drivers/mtd/ubi/fastmap.c 1391 */;
	struct ubi_ainf_peb *cocci_id/* drivers/mtd/ubi/fastmap.c 139 */;
	struct ubi_device *cocci_id/* drivers/mtd/ubi/fastmap.c 1388 */;
	struct ubi_attach_info *cocci_id/* drivers/mtd/ubi/fastmap.c 136 */;
	struct list_head *cocci_id/* drivers/mtd/ubi/fastmap.c 136 */;
	int cocci_id/* drivers/mtd/ubi/fastmap.c 136 */;
	struct ubi_eba_leb_desc cocci_id/* drivers/mtd/ubi/fastmap.c 1309 */;
	struct ubi_work *cocci_id/* drivers/mtd/ubi/fastmap.c 1136 */;
	struct ubi_volume *cocci_id/* drivers/mtd/ubi/fastmap.c 1109 */;
}
